### ISSUE TITLE
Error in Module Access Control for System Time

### ISSUE THREAD

**Issue by rostovtsev** [webmin/webmin#1006]
When going to Webmin/Webmin Users/username/Available Modules/System Time, I get this error returned:

`time::acl_security_form failed : Can't locate object method "text" via package "acl_sys" (perhaps you forgot to load "acl_sys"?) at /usr/libexec/webmin/time/acl_security.pl line 11.`

![image](https://user-images.githubusercontent.com/4426533/50644435-eba27080-0f81-11e9-81cc-b245ca28797a.png)

**Comment by jcameron** [comment]
Oops, not sure how that got in there. I will fix this in the next release.
