### ISSUE TITLE
Can't login to Webmin in Chrome Browser

### ISSUE THREAD

**Issue by Column01** [webmin/webmin#1007]
Hello Webmin Developers and Community,
My issue is I cannot connect to my Webmin panel in the chrome desktop browser. (YES it is the correct password... keep reading)
I tried from Firefox and Microsoft Edge and I could login fine with both of them. If I try through chrome, however, it just reloads the login page. I have attached a GIF of what happens when I try through chrome (the cursor is not synced properly to where it actually was since I used ShareX to record it.)
![ohucqzj - imgur](https://user-images.githubusercontent.com/26526649/50870417-f2682380-1385-11e9-9995-7a1678a6274a.gif)
Some things I have tried:
- Clearing cache
- Restarting Chrome
- Restarting the Webmin service
- Used a different a port
- Reinstalled Webmin
- Restarting my computer

The oddest part is when I look at the sessions in Webmin from Firefox, it shows my IP as being logged in a bunch (and not the Firefox session as it was there too), and I am wondering if that has something to do with this issue. Is there a way to log everyone out of the panel?
![IMG](https://i.imgur.com/XpkNO34.png)
I have not tried from my cellphone browser.
I do not wish to reinstall chrome if I do not have too. Any help would be appreciated.
Thanks!
Colin

**Comment by Column01** [comment]
Just tried on my phone with the chrome browser and it worked. Sadly looking like I'll need to reinstall it

**Comment by Column01** [comment]
Reinstalled Chrome, still not working. I went into chrome settings and allowed popups and re-directs for this site, still not working. Cleared all active logins in webmin, still not working. Any help is appreciated.

**Comment by jcameron** [comment]
Did you recently switch webmin from non-SSL to SSL mode, or vice-versa?

**Comment by jcameron** [comment]
So it works OK when SSL is not enabled?

**Comment by Column01** [comment]
Nope. Had it disabled due to a separate issue that would not let me log in. This is different from that.

**Comment by jcameron** [comment]
If you can give me the URL to your server and a test login, I can try myself and see if this is a browser-side issue or something on the server?

**Comment by Column01** [comment]
[Server URL](http://colinandress.mooo.com:10000)
Login Details (Only dashboard access)
Username: `test`
Password: `testing123`

**Comment by Column01** [comment]
Enabling SSL and using https:// to login allowed the connection. I believe this has to do with Chrome and not wanting to send the login details over an unsecure channel. Not an issue with webmin.
