### ISSUE TITLE
[MODULE REQUEST] WEBMIN update via LINK from GIT.

### ISSUE THREAD

**Issue by PauloBoaventura** [webmin/webmin#1008]
Sorry if I'm wrong to make this call. But as I have not found, it is clear from this tutorial. {http://www.webmin.com/git.html}

I wonder if in the WebMin Update part, I could have a button to update promptly, based on git. Or this code {LINK ABOVE}, could be coupled in this function.

We are waiting for new additions ...

**Comment by jcameron** [comment]
I'm confused ... what are you trying to do exactly?

**Comment by swelljoe** [comment]
Ilia had suggested this a while back, and I think he even implemented it in Authentic theme, but I vetoed it and it got pulled back out. I don't think switching to the git version should be in the GUI. Folks who know how to use the CLI tend to know what they're getting themselves into by running a development version (and there is a script for upgrading an existing install from git, I think), but offering it to less technical users is just asking for problems.

**Comment by gnadelwartz** [comment]
./update-from-repo.sh within webmin dir on cli

**Comment by PauloBoaventura** [comment]
This option was added by server ... In the year 2019.

**Comment by PauloBoaventura** [comment]
This option was added by server ... In the year 2019.

**Comment by rostovtsev** [comment]
>This option was added by server ... In the year 2019. 

What do you mean by, it was added?
