### ISSUE TITLE
Virtual IP is stripped off when main interface has no IP address

### ISSUE THREAD

**Issue by michaelbaisch** [webmin/webmin#1009]
Hello everyone,

when getting the `active_interfaces` and you only have an IPv4 address on a virtual interface eg `eth0:1` then the address is added to `eth0` and the virtual interface is ignored.

The line is removed here before getting the chance of getting processed:

https://github.com/webmin/webmin/blob/d61bee0dec9b997604c296d08037fc9c5096308c/net/linux-lib.pl#L76

when the input is for example like this:

```
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether *** brd ff:ff:ff:ff:ff:ff
    inet 192.168.178.53/24 brd 192.168.178.255 scope global eth0:1
       valid_lft forever preferred_lft forever
    inet6 ***/64 scope global dynamic mngtmpaddr 
       valid_lft 595628sec preferred_lft 595628sec
    inet6 ***/64 scope link 
       valid_lft forever preferred_lft forever
```

Greetings Michael

**Comment by jcameron** [comment]
That's a very unusual case - why is the IP not just on eth0 ?

**Comment by michaelbaisch** [comment]
Well `eth0` and `eth0:1` have both a specific function and for that a specific IP address. It is now possible to disable ("No address configured") each of those. And in the case where I disable `eth0` and let `eht0:1` as static (which is a valid thing to do in the user interface) I get incorrect data when trying to display the current state of the interfaces.

**Comment by jcameron** [comment]
It sounds like we should disable the ability to have `eth0` without an IP while `eth0:1` still has one. Or is that a configuration you are intentionally using (ie. because of bridging) ?

**Comment by michaelbaisch** [comment]
Yes it is very intentional. Additionally it sounds kinda wrong to me to to fix a parsing bug by not allowing something in some user interface. This state can still be reached by doing it manually and the net module will show wrong information. I'll try to figure out fixing in in the `active_interfaces` method.

**Comment by jcameron** [comment]
Ok, fair enough. Check out the patch that I just submitted and attached to this ticket.

**Comment by michaelbaisch** [comment]
Seems to work, thank you so much!
