### ISSUE TITLE
Bring back nofail mount option

### ISSUE THREAD

**Issue by mvglasow** [webmin/webmin#1012]
In earlier Webmin versions, the Disk and Network Filesystems module exposed the `nofail` option (i.e. continue normal boot if that filesystem fails to mount).

In Webmin 1.900 (and also a few versions back) this option is now gone, and default behavior now is to boot into emergency mode if any partition fails to mount at boot. This is undesirable in a number of situations.

I would therefore be very happy to see this option exposed in the UI again. If there is concern about cluttering the UI with too many settings, how about an “Advanced” section that is collapsed by default and contains rarely-needed options?

**Comment by flatline-studios** [comment]
Any word on this. I need this too.

As an additional, are we able to edit the fstab directly? Or will that interfere with webmin?

**Comment by Jostqu** [comment]
+1

**Comment by jcameron** [comment]
Which filesystem are you using there - EXT4, BTRFS, or something else?

**Comment by mvglasow** [comment]
The disk in question is BTRFS. I did use EXT4 earlier (until some 2 years ago iirc), but I no longer have any records of the exact configuration when I last had the `nofail` option and when I first noticed it was gone.

Is `nofail` related to the filesystem in any way?

**Comment by jcameron** [comment]
Looks like this option is available on all Linux filesystems.

We'll add it back in the next release.
