### ISSUE TITLE
Error installing software/updates on 1.900

### ISSUE THREAD

**Issue by trebr** [webmin/webmin#1013]
Now installing owncloud-mysql ..
HTTP/1.0 500 Perl execution failed Server: MiniServ/1.900 Date: Sat, 19 Jan 2019 23:27:11 GMT Content-type: text/html; Charset=iso-8859-1 Connection: closeError - Perl execution failed

Undefined subroutine &WebminCore::compare_version_numbers called at /usr/share/webmin/webmin-1.900/software/software-lib.pl line 234, line 3.

**Comment by jcameron** [comment]
This is a known bug in the current Webmin release which will be fixed in the next version.

**Comment by trebr** [comment]
What can I do until then? I'm trying to set up a file server and need to install owncloud.

**Comment by rostovtsev** [comment]
You can simply apply [this patch](https://github.com/webmin/webmin/commit/5d0bd909f0bfe45092ab783f95e4e989e5ed8b8f) to `...webmin/package-updates/package-updates-lib.pl` replacing `...` with the path where Webmin is installed. Usually it's either `/usr/share` or `/usr/libexec`, depending on the Linux distro.

You could also install Webmin devel version from [this link](http://webmin.com/devel.html).

**Comment by trebr** [comment]
Thanks for this, unfortunately the lines in my package-updates-lib.pl file already match the lines in the patch. Are there any other options please?

**Comment by trebr** [comment]
I must admit I have no knowledge of Perl but it does appear the subroutine mentioned in the original error (the title of my post) doesn't exist. Lines 221 to 234 of my software-lib.pl file are:

# compare_versions(ver1, ver2)
# Returns -1 if ver1 is older than ver2, 1 if newer, 0 if same
sub compare_versions
{
local ($ver1, $rel1) = split(/-/, $_[0], 2);
local ($ver2, $rel2) = split(/-/, $_[1], 2);
if ($rel1 != "" && $rel2 != "" && $config{'package_system'} eq 'rpm') {
	# If two RPM packages have releases, then the version part comparison
	# must be done first and separately so that release number parts don't
	# override version parts.
return &compare_versions($ver1, $ver2) || &compare_versions($rel1, $rel2);
}
return &compare_version_numbers($_[0], $_[1]);
}

The first comment says -1, 0 or 1 should be returned but there is nothing which returns any numbers. Also the subroutine compare_version_numbers isn't mentioned anywhere else in the file.

As I said, I know nothing about this and possibly the subroutine is mentioned in another file, it's just to my untrained eye there is a piece of code missing altogether.

**Comment by rostovtsev** [comment]
There might be more dependencies missing.

If you feel comfortable running `update-from-repo.sh` script to update Webmin completely, it's possible, and should be fairly safe and easy to do. 

You can find an update script in Webmin directory (mentioned above).
