### ISSUE TITLE
Bind module: Testing transfer masters clause

### ISSUE THREAD

**Issue by TakeMeNL** [webmin/webmin#1016]
So my named config has a `masters masterDns { ...ips..; }` clause which is not working nice with the test transfer function.
I get : 
```
Testing transfer of slave zone from masterdns ..
.. from masterdns : Failed : /bin/dig: couldn't get address for 'masterdns': not found 
```

**Comment by jcameron** [comment]
Thanks - this will be fixed in the next webmin release.

**Comment by TakeMeNL** [comment]
Thank you!
