### ISSUE TITLE
Software Update: New version displayed as current

### ISSUE THREAD

**Issue by rostovtsev** [webmin/webmin#1017]
Jamie, hi.

I have a [bug report](https://twitter.com/PlamenTachev/status/1090212143155347456?s=19) saying that when installing new updates, current and new versions are always displayed the same.

Example:

![twitter_bug_report_1](https://user-images.githubusercontent.com/4426533/51968975-439a9d00-2484-11e9-9f41-7a34ab5ff901.jpg)

**Comment by jcameron** [comment]
Yeah, this is a bug in Webmin - it will be fixed in the next release.

**Comment by rostovtsev** [comment]
Jamie, are you sure that you didn't forget about it, as I haven't found correspondent patch for it?

**Comment by jcameron** [comment]
I can't recall the exact patch, but it would be in either the `software` or `package-updates` modules.

**Comment by jcameron** [comment]
Yeah, that's the same issue.
