### ISSUE TITLE
Backup restore script fails

### ISSUE THREAD

**Issue by PitWenkin** [webmin/webmin#1022]
Restoring backups hangs on 'Show What Will Be Restored'

The following error shows up in `/var/webmin/miniserv.error`:
```
/virtual-server/restore.cgi : Perl execution failed : Experimental keys on scalar is now forbidden at /usr/share/webmin/virtual-server/restore.cgi line 160.
Type of arg 1 to keys must be hash or array (not scalar dereference) at /usr/share/webmin/virtual-server/restore.cgi line 160, near "$cont) "
```

I guess changing that line to `foreach my $k (keys %{$cont}) {` would fix it.

Experienced on
Ubuntu 18.04.1
Webmin 1.900

**Comment by rostovtsev** [comment]
Hi,

Yes this issue has already been fixed https://github.com/virtualmin/virtualmin-gpl/commit/29778435086b61470d59797b7036cd56d59836c4#diff-9b6e7456fb40c9398f26e79e7c33debf.

Thank you for reporting!
