### ISSUE TITLE
backup restore problem Virtualmin version 6.05

### ISSUE THREAD

**Issue by adamus007p** [webmin/webmin#1023]
Hello I have noticed a problem to restore a back up in the version.

Webmin version | 1.900 | 
Usermin version | 1.751
Virtualmin version | 6.05 | 
Authentic theme version | 19.22
Kernel and CPU | Linux 4.9.0-8-amd64 on x86_64

Operating system | Debian Linux 9
Debian 9.6
Perl version | 5.024001
Path to Perl | /usr/bin/perl
BIND version | 9.10
Postfix version | 3.1.8
Mail injection command | /usr/lib/sendmail -t
Logrotate version | 3.11.0
MySQL version | 10.1.37-MariaDB-0+deb9u1
ProFTPD version | 1.35

I wanted to migrate virtualmin and websites to new VPS.
Few websites, two bigger and other smaller.
Size of xxx.tar.gz more then 1,5GB total Backup is complete. Final size was 3.08 GB.
1,5GB and 2GB and rest. site1, site2 and others.

Via GUI it was possible to make a backup but it was not possible restore.
The wheel was wheeling and nothing happen after 1hour.

I was able to make a restore via command line, but there not all database have been imported, so there is something wrong.

I can reproduce the problem.

**Comment by jcameron** [comment]
There's a bug in the current release that can cause this, but we're releasing an update that will fix it.

**Comment by adamus007p** [comment]
Hello Jamie, is there any ETA?

**Comment by jcameron** [comment]
A couple of days at most
