### ISSUE TITLE
request user id & pass

### ISSUE THREAD

**Issue by happykozac** [webmin/webmin#1024]
hi!
As you mention on your website, could you send an ID & Pass to connect on my browser?
happykozac@ntymail.com.
Thanks

**Comment by swelljoe** [comment]
Are you asking for a user account on the Webmin wiki? There are no accounts on Webmin.com, but we do welcome contributors to the Webmin documentation.

**Comment by happykozac** [comment]
it is for the soft that works on firefox.
I'm not an admin and i don't now how to open webmin. 
I am on Debian stretch.
Thanks for helping

**Comment by swelljoe** [comment]
We don't know your login details!

Webmin is installable software; you install it on your server(s), and you login using the root account, or any account with sudo ALL privileges. If the [installation documentation for Webmin](https://doxfer.webmin.com/Webmin/Installation) isn't clear/low-level enough for you, there are a variety of videos on the subject on YouTube that might help (just be sure to use your native package manager, `apt` on Debian and use the deb package...don't follow any tutorials that tell you to use the tar.gz). https://www.youtube.com/results?search_query=installing+webmin
