### ISSUE TITLE
Webmin Custom/Secure HTTP headers

### ISSUE THREAD

**Issue by reload-kurt** [webmin/webmin#1026]
Is it possible to allow Miniserv to serve custom HTTP headers within the Webmin interface? We're required to run audits (even on IP-restricted addresses) and need to enable some HTTP headers like "Strict-Transport-Security", "X-XSS-Protection", "X-Frame-Options", "X-Content-Type-Options" etc.

**Comment by jcameron** [comment]
Good idea .. I will add an option for this.

**Comment by rostovtsev** [comment]
Will Usermin inherit it as well?

**Comment by jcameron** [comment]
Yes, although it will require editing /etc/usermin/config manually for now.

**Comment by omourtaka** [comment]
@webmin 
Can you please add possibility to add the Feature-Policy ?
For example : Feature-Policy: vibrate 'self'; microphone 'none'; payment 'none'; sync-xhr 'self' https://example.net
actually pattern check don't allow to add it cause so many spaces :)
Best regards 🥇

**Comment by jcameron** [comment]
You can define all the custom headers you want by editing `/etc/webmin/config` and adding a line like : 

`extra_headers=Feature-Policy: vibrate 'self'; microphone 'none'; payment 'none'; sync-xhr 'self'`

multiple headers can be separated by tabs.

**Comment by rostovtsev** [comment]
..I suppose, it's also possible doing it via UI.

![image](https://user-images.githubusercontent.com/4426533/71788394-c8961b00-3032-11ea-939e-77d7ea8822e7.png)

**Comment by omourtaka** [comment]
Hi,
![image](https://user-images.githubusercontent.com/59428509/72183293-e32f1200-33ed-11ea-9286-f5cca4f7a079.png)
it work but only by editing /etc/webmin/config no way by webgui
Thank you for the work arround (Y)

**Comment by rostovtsev** [comment]
Hi,

There was a [fix](https://github.com/webmin/webmin/commit/d7592cede9e7fe659c9b0e76416e864d86c67898) for it that Jamie made, just few days ago!

**Comment by chris001** [comment]
Wouldn't it be best for Webmin to set the default value, of new installations and updates, of `Extra HTTP Headers`, to the recommended secure headers, as in, the web information security universal consensus on "best practices" ??

**Comment by jcameron** [comment]
We do set some to print iframe clickjacking for example. @chris001 what others would you recommend?

**Comment by chris001** [comment]
> We do set some to **prevent** iframe clickjacking for example. @chris001 what others would you recommend?

* These:

```
Cache-Control: private, no-cache, no-store, must-revalidate, pre-check=0, post-check=0, max-age=0, s-maxage=0
Expires: 0 
Content-Security-Policy: script-src ‘self’  (I see you already generate this one and it's more detailed so keep it.)
X-XSS-Protection: 1; mode=block
X-Frame-Options: DENY  (I see this is already set to SAMEORIGIN so that's prob fine, if webmin still uses iframes.)
X-Content-Type-Options: nosniff
Access-Control-Allow-Origin: http://www.myvirtualmin.com
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
public-key-pins: pin-sha256=”t/OMbKSZLWdYUDmhOyUzS+ptUbrdVgb6Tv2R+EMLxJM=”; pin-sha256=”PvQGL6PvKOp6Nk3Y9B7npcpeL40twdPwZ4kA2IiixqA=”; pin-sha256=”ZyZ2XrPkTuoiLk/BR5FseiIV/diN3eWnSewbAIUMcn8=”; max-age=1200; report-uri=”https://www.myvirtualmin.com/report-pk"
feature-policy: autoplay 'none'; camera 'none'
expect-ct: max-age=604800, enforce, report-uri="https://www.myvirtualmin.com/report-ct"
```

* Would be nice if users could click one button to get the rating report on the strength of the security headers for their webmin instance at: https://securityheaders.io/

**Comment by chris001** [comment]
![webmin security headers](https://user-images.githubusercontent.com/259416/72279643-92453680-3604-11ea-83aa-8941c57bc662.png)

**Comment by chris001** [comment]
The problem is, when you enter these five or so HTTP security headers into the text box, each one separated by a newline, which is the only way to sensibly enter them for acceptable user experience, webmin complains with the error:
`Failed to save advanced options : Headers must be formatted like Header: Value`

**Comment by chris001** [comment]
Correction, the headers occupying multiple lines is fine.  The code only accepts simple "values". It (wrongfully) rejects complex "values" with the error message "`Failed to save advanced options : Headers must be formatted like Header: Value`", yet high security requires many of the headers to have complexity in the "value" part of "Header: Value".
For example:  
It accepts: `X-Content-Type-Options: nosniff` because it's a simple `Heaader: Value`.
It rejects: `Strict-Transport-Security: max-age=31536000; includeSubDomains; preload`
I presume the reason is because of the spaces and/or punctuation which make a "multi-part value" that it doesn't like, or can't regex.

**Comment by chris001** [comment]
After adding 2 simple test headers (`X-Content-Type-Options: nosniff` and `Strict-Transport-Security: max-age=31536000`), check at https://securityheaders.io gives:

**MISSING HEADERS:** 
* `Referrer-Policy` | Referrer Policy  is a new header that allows a site to control how much information the  browser includes with navigations away from a document and should be set  by all sites.

* `Feature Policy` | Feature Policy is a new header that allows a site to control which features and APIs can be used in the browser.

WARNINGS:

* `Content-Security-Policy` | This  policy contains `'unsafe-inline'` which is dangerous in the `script-src`  directive. This policy contains `'unsafe-eval'` which is dangerous in the  `script-src` directive.

**Comment by jcameron** [comment]
The issue of not being able to enter complex headers is fixed in the 1.941 Webmin releases, which is coming out now.

However, it does look like some of those should just be set by default. I'll need to do some research though, to make sure none of them break anything inadvertently.

**Comment by chris001** [comment]
FYI Here's the browser add-on I used to rate the security headers directly inside the browser:
https://addons.mozilla.org/en-US/firefox/addon/cookies-and-headers-analyser/

**Comment by chris001** [comment]
Need all these default secure HTTP headers, not only for webmin/virtualmin/cloudmin, but also, for all the new nginx sites and apache2 sites that webmin/virtualmin creates on behalf of the virtual server owners and sub server admins.

**Comment by kaleben0** [comment]
Just a note. All the extra_headers need to be in one continuous line. Separated by tabs

Like this : 

extra_headers=Feature-Policy: autoplay 'none';camera 'none'     Referrer-Policy: same-origin    X-Frame-Options: SAMEORIGIN     Content-Security-Policy: "default-src 'self' '*.bootstrapcdn.com ajax.googleapi
s.com code.jquery.com;"  Strict-Transport-Security: max-age=63072000; includeSubdomains; X-Content-Type-Options: nosniff

**Comment by chris001** [comment]
> Just a note. All the extra_headers need to be in one continuous line. Separated by tabs

The problem is, the text box, on the web user interface, doesn't allow users to enter tabs.  So there's no way for a normal web user to enter multiple headers separated by tabs.

**Comment by kaleben0** [comment]
Correct, I had to edit /etc/webmin/config via SSH to make the change. 

Sorry, I should have point that out. :)

**Comment by chris001** [comment]
> Correct, I had to edit /etc/webmin/config via SSH to make the change.
> 
> Sorry, I should have point that out. :)

The Web user interface should be updated to allow web users to enter multiple HTTP security headers, directly into the text box.

**Comment by rostovtsev** [comment]
> The Web user interface should be updated to allow web users to enter multiple HTTP security headers, directly into the text box.

I am confused. What stops you guys from putting on the textbox for **Extra HTTP headers** the following?

~~~
Feature-Policy: autoplay 'none';camera 'none' 
Referrer-Policy: same-origin 
X-Frame-Options: SAMEORIGIN 
Content-Security-Policy: "default-src 'self' '*.bootstrapcdn.com ajax.googleapis.com code.jquery.com;" 
Strict-Transport-Security: max-age=63072000; includeSubdomains; 
X-Content-Type-Options: nosniff
~~~

In case you have Webmin 1.941+ must work for you already.

**Comment by chris001** [comment]
> In case you have Webmin 1.941+ must work for you already.

My humblest apologies. Multi-part values are working now. Thank you!
