### ISSUE TITLE
Webmin behind reverse proxy redirects to 10000 port

### ISSUE THREAD

**Issue by lukasmrtvy** [webmin/webmin#1027]
This:
https://github.com/webmin/webmin/blob/master/miniserv.pl#L2243
will always evaluate port from miniserv, but if you are using reverse proxy on another port infront of webmin, request will be redictected to :10000 after login for example.

I am not sure about:
https://github.com/webmin/webmin/blob/master/miniserv.pl#L1628

There are a lot of discussion about it:
https://sourceforge.net/p/webadmin/discussion/600155/thread/6eb89f60/#982e/ffc7

Any fix?

**Comment by gnadelwartz** [comment]
you have to setup Proxypass and Proxypass Reverse plus webprefixnoredir=1  in /etc/webmin/config
this works for me.

see http://www.webmin.com/apache.html

**Comment by iwikus** [comment]
Yes, I hit this issue with haproxy as frontend and webmin as backend.
Workaround was in haproxy to delete port in this reponse

`     http-response replace-value Location (.*):.* \1`

but clean solution should be to fix it in code :)

**Comment by rostovtsev** [comment]
@iwikus Do you have set at `/etc/webmin/config` the following?

~~~
webprefixnoredir=1 
~~~

**Comment by vibo69** [comment]
hello, is there any solution for this problem? i tried every scenario but still cant get it to work. i did not try to modify miniserv.pl because i simply dont want to do it after every update ;) currently my config is

    ProxyPass / http://localhost:10000/
    ProxyPassReverse / /http://localhost:10000/
    ProxyPassReverseCookieDomain / http://localhost:10000/
    ProxyPassReverseCookiePath / http://localhost:10000/

**ssl=0**

referers_none=1
webprefixnoredir=1
nowebminup=
nohostname=0
nomoduleup=
gotoone=0
referers=127.0.0.1
referer=1
webprefix=

Webmin version | 1.910 | Authentic theme version | 19.34-beta7

**Comment by rostovtsev** [comment]
Where exactly you had this redirect happening?

**Comment by vibo69** [comment]
after login ;)

**Comment by rostovtsev** [comment]
Do you have it set as sub-directory or as sub domian?

How does your URL look like?

**Comment by vibo69** [comment]
as you can see from apache configuration it directs to root path.. so.. as a subdomain ;)
i believe problem occurred when i added:  ProxyPreserveHost on ..but i am not sure.
if you need any other details feel free to ask ;)

**Comment by vibo69** [comment]
..also one thing needs to be mentioned.. my apache serves on https and after login i get redirected to http

**Comment by rostovtsev** [comment]
Okay, just making sure.

Correct, [option](https://httpd.apache.org/docs/2.4/mod/mod_proxy.html#proxypreservehost) `ProxyPreserveHost on` should be set to off:

> When enabled, this option will pass the Host: line from the incoming request to the proxied host, instead of the hostname specified in the ProxyPass line.
This option should normally be turned Off. It is mostly useful in special configurations like proxied mass name-based virtual hosting, where the original Host header needs to be evaluated by the backend server.

**Comment by vibo69** [comment]
well.. i added this setting to be able to track from which IP other admins log in ;) without that i see only 127.. but that topic is for other issue eventually ;)

**Comment by rostovtsev** [comment]
Do not set `ProxyPreserveHost On` as discussed above, as it will cause redirect after login problem. If you wan to log real IPs, use `trust_real_ip` option set to `1` in _miniserv.conf_ file, or use UI to change it in _Webmin/Webmin Configuration/IP Access Control/Trust remote IP address provided by proxies_ setting it to _Yes_.

**Comment by iliarostovtsev** [comment]
This comment should help - https://github.com/webmin/webmin/issues/1135#issuecomment-663453121

**Comment by Rhandyx** [comment]
> 
> 
> This comment should help - [#1135 (comment)](https://github.com/webmin/webmin/issues/1135#issuecomment-663453121)

Thank you!
In my case I fix it with
```
/etc/webmin conf
#added by me to use proxy
webprefixnoredir=1
relative_redir=0
referers=subdomain.domain.com
## end of add
```

AND
```
/etc/webmin/miniserv.com
#edit and added by me
ssl=1
redirect_port=443
```

**Comment by deam0n** [comment]
I got around this issue by adding the following setting under webmin -> webmin configuration -> Web Server Options:
![image](https://user-images.githubusercontent.com/1869650/231918353-13bc21fc-d178-43e4-b3a5-6b235fc1846f.png)

**Comment by paulocoghi** [comment]
Following the instruction on https://webmin.com/faq/#can-i-run-webmin-or-usermin-behind-reverse-proxy, with way less variables to change, everything is working perfectly, with no undesired redirects.

**/etc/webmin/config**
```
referers=webmin.example.com
```

**/etc/webmin/miniserv.conf**
```
redirect_ssl=1
redirect_host=webmin.example.com
```

**Comment by jeepeegit** [comment]
This settings in npm advanced works for me. The last row fixed the problem:

real_ip_header CF-Connecting-IP;
proxy_set_header Host $host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;
proxy_redirect ~^(https?://[^:]+):10000(.*)$ $1$2;
