### ISSUE TITLE
Webmin Upload File Fail and hung at 4% only

### ISSUE THREAD

**Issue by manesvenom** [webmin/webmin#1035]
I tried to upload file using File manager or function Upload and Download in Others, the upload progress hung at 4% and stop there.

The upload.cgi thrown error message  in network inspector: Fail to load resource. The network connection was lost.
The up tracker.cgi thrown error message in network inspector: An error occur trying to load resource.

Operating system | CentOS Linux 7.6.1810
Authentic Theme 19.21
Webmin version | 1.900

**Comment by jcameron** [comment]
Does this happen regardless of the size of the file being uploaded?

**Comment by manesvenom** [comment]
Yes, if the file size is smaller than 30KB, the upload operation could be completed.

**Comment by jcameron** [comment]
Does changing the theme (at Webmin -> Change Language and Theme) make any difference?

**Comment by manesvenom** [comment]
I tried to switch the theme to Gray Famed Theme from Authentic Theme.

I tried to upload a file size- 1MB.
It stopped at : 30.61 kB of 1005.79 kB

**Comment by rostovtsev** [comment]
It's not the theme issue. Do you have Webmin running behind proxy?

**Comment by rostovtsev** [comment]
Besides, check that you don't have browser extensions enabled. There are browsers extensions, that can break uploads. Try in incognito mode, making sure that all extensions are off.

**Comment by manesvenom** [comment]
I just ran the command in Command Shell : env | grep proxy
no proxy was found 

Then I issued another command to check the connection, it seemed no proxy connection.
# wget http://google.com
--2019-03-27 16:55:03--  http://google.com/
Resolving google.com (google.com)... 172.217.161.142, 2404:6800:4005:80e::200e
Connecting to google.com (google.com)|172.217.161.142|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: http://www.google.com/ [following]
--2019-03-27 16:55:03--  http://www.google.com/
Resolving www.google.com (www.google.com)... 216.58.200.68, 2404:6800:4005:811::2004
Connecting to www.google.com (www.google.com)|216.58.200.68|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: 'index.html'

     0K .......... ..                                          3.54M=0.003s

2019-03-27 16:55:03 (3.54 MB/s) - 'index.html' saved [12474]

Then I tried to access to Webmin using incognito mode with all extensions off. No luck. It stopped at 4%.

I suspected it is related to issue of the network configuration.

**Comment by rostovtsev** [comment]
By proxy, I meant whether you access Webmin directly, entering port into URL, like _https://myhostname:10000_ or using proxy, like Apache or Nginx?

**Comment by manesvenom** [comment]
Direct access through https://myhostname:10000

**Comment by manesvenom** [comment]
Below is the network log message when the connection timeout: POST https://myhostname:10000/filemin/upload.cgi?path=%2F&id=349259494985367800 net::ERR_CONNECTION_RESET   bundle.min.js?1921999999999901:4

**Comment by rostovtsev** [comment]
It looks like something resets the connection. It can be cause by killed script, for example.

Okay, can you enable debug logging for File Manager, and send results to us, on upload, in the process and when it's done?

![image](https://user-images.githubusercontent.com/4426533/55073950-12170a00-50a0-11e9-8e32-d64e53d62ece.png)

**Comment by manesvenom** [comment]
[filemanager_debug.log](https://github.com/webmin/webmin/files/3013798/filemanager_debug.log)

Please find the log file as attached for the whole process.  I tried to upload a file : filemin.wbm.gz to /tmp folder and it stopped at 4%.

**Comment by rostovtsev** [comment]
Did you try uploading to some other folder, like to your home directory, for example?

**Comment by manesvenom** [comment]
[filemanager_debug_1.log](https://github.com/webmin/webmin/files/3013858/filemanager_debug_1.log)
Please find the another log file for the whole process to upload to my home directory. /root folder.

**Comment by manesvenom** [comment]
![Screen Shot 2019-03-27 at 11 23 37 PM](https://user-images.githubusercontent.com/7610019/55088839-672a3e80-50e7-11e9-8140-4e15c7c10843.png)
I just tried to alter the Web Server Options and restarted it after Save, now I have uploaded the large File now. Thanks.

**Comment by rostovtsev** [comment]
What options did you change?

**Comment by manesvenom** [comment]
![Screen Shot 2019-03-27 at 11 34 09 PM](https://user-images.githubusercontent.com/7610019/55089800-f71cb800-50e8-11e9-91dc-ab994157e2cb.png)
I set the Show stack trace for error messages to Yes and restarted the server. Then I could upload the file. However when I turned off the Show stack trace for error messages, it could not upload the file again. 
![Screen Shot 2019-03-27 at 11 33 35 PM](https://user-images.githubusercontent.com/7610019/55089962-3ea34400-50e9-11e9-8d36-d6267befea8c.png)
It stopped at 4% again. Before, it did not show the popup progress window and upload process finished very quick. 
I tried to turn on the Show Stack trace for error message to 'Yes' again, but it could not upload the file anymore.

**Comment by rostovtsev** [comment]
Okay.

By the way. What do you need Filemin 2.2? 🙂

**Comment by manesvenom** [comment]
From another thread, it said to uninstall the Filemanager and reinstall it might fix the issue of file upload. Then I tried to reinstall the File manager 😃 https://github.com/Real-Gecko/Filemin

**Comment by manesvenom** [comment]
> ![Screen Shot 2019-03-27 at 11 23 37 PM](https://user-images.githubusercontent.com/7610019/55088839-672a3e80-50e7-11e9-8140-4e15c7c10843.png)
> I just tried to alter the Webmin Configuration ->Web Server Options and restarted it after Save. now I can upload the large File. Thanks.

It might be false positive, it worked on other server only. I was working on another server and indeed it had no issue for file upload. I don't know why in the working server, it does not show the progress poup at all.

**Comment by rostovtsev** [comment]
If you relaying requests, a relay may have imposed limits, and drop the connection.

**Comment by manesvenom** [comment]
I replaced with a new network router and the problem was solved.
