### ISSUE TITLE
When interface has no "broadcast", active_interfaces() returns wrong info

### ISSUE THREAD

**Issue by michaelbaisch** [webmin/webmin#1040]
Hello,

I happened to accidentally have no broadcast configured on the `eth0` interface. This results in wrong results from `active_interfaces` method.

Example input:

```
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether *** brd ff:ff:ff:ff:ff:ff
    inet 192.168.178.54/24 scope global eth0
       valid_lft forever preferred_lft forever
    inet 192.168.200.195/24 brd 192.168.200.255 scope global eth0:1
       valid_lft forever preferred_lft forever
    inet6 ***/64 scope global dynamic mngtmpaddr 
       valid_lft 595628sec preferred_lft 595628sec
    inet6 ***/64 scope link 
       valid_lft forever preferred_lft forever
```

Return:

```
$VAR2 = { 'name' => 'eth0', 'duplex' => 'Full', 'netmask6' => [ '64', '64' ], 'address6' => [ '***', '***' ], 'ether' => '***', 'scope6' => [ 'global', 'link' ], 'up' => 1, 'broadcast' => '192.168.200.255', 'index' => 1, 'mtu' => '1500', 'edit' => 1, 'link' => 1, 'speed' => '1000Mb/s', 'fullname' => 'eth0' }; 
$VAR3 = { 'virtual' => '1', 'name' => 'eth0', 'address' => '192.168.178.54', 'up' => 1, 'broadcast' => '192.168.178.255', 'index' => 2, 'edit' => 1, 'mtu' => '1500', 'fullname' => 'eth0:1', 'netmask' => '255.255.255.0' }; 
```

You can see that `eth0` has no `address` and eth0:1  has the address from `eth0`.

This does not happen before https://github.com/webmin/webmin/commit/797039fb80ca7322832c019f0880a26a94d68bce

I believe it's related to https://github.com/webmin/webmin/blob/master/net/linux-lib.pl#L35 and https://github.com/webmin/webmin/blob/master/net/linux-lib.pl#L76. Probably not a very serious issue, but still a bug in the parser, so I wanted to let you know. 

Greetings Michael

**Comment by jcameron** [comment]
Check out the change I just checked in and attached to this but report - it should fix the issue.
