### ISSUE TITLE
Let's encrypt expired Certificat instead of new

### ISSUE THREAD

**Issue by GAS85** [webmin/webmin#1042]
Hello,
I'm using Webmin and Let's encrypt. I find out that Webmin will not use newer Certificate per default.
Long running Webmin:

    # service webmin status
    ● webmin.service - LSB: web-based administration interface for Unix systems
       Loaded: loaded (/etc/init.d/webmin; bad; vendor preset: enabled)
       Active: active (running) since Tue 2019-02-12 20:26:46 CET; 1 months 24 days ago

Certificate showing correct in WebMin, but never used in browser.
![image](https://user-images.githubusercontent.com/6813635/55709828-7cf20a80-59e9-11e9-879a-787fd0a4b0a5.png)

`service webmin reload` does not have any effect, I need to restart webmin by  `service webmin restart` to use new Certificate in Webmin. So as workaround I add cron job to restart webmin once in month, but it is not what expected. 

How to setup webmin that it is able to take new Cert automatically? Could it be default setting?

**Comment by jcameron** [comment]
How did you install this certificate - by just copying it to the `/etc/webmin` directory?

**Comment by GAS85** [comment]
I used Certbot to install Certificate via command line. After this just link it in Webmin Settings in "SSL Settings" as per Screenshot below. Cert renew Process is independent of WebMin.
![image](https://user-images.githubusercontent.com/6813635/55779138-fc90df80-5aa4-11e9-8c93-0ebdf47b17fc.png)

**Comment by jcameron** [comment]
OK - in that case, a full Webmin restart is needed.

**Comment by GAS85** [comment]
As workaround I add cron job to restart Webmin weekly.

**Comment by campones** [comment]
but so, that means your webmin is running under a domain name?

**Comment by GAS85** [comment]
Yes, webmin is running under Domain name with non standard Port. Webmin uses his own httpd server and this will not take new certificate automatically.
