### ISSUE TITLE
Request for: webmin/mysql/backup.pl

### ISSUE THREAD

**Issue by seansan** [webmin/webmin#1044]
Would it be possible to add the acceptance of a second param called --prefix

Tis way we can add a --prefix to the output filename

The ARGV can be read here https://github.com/webmin/webmin/blob/master/mysql/backup.pl#L15

And used here https://github.com/webmin/webmin/blob/master/mysql/backup.pl#L53

This is an improvement suggestion for output file prefix. Sorry perl is a long time go. I hope I got it right. If not then please update it to proper modern perl.

Why the change?
It should break nothing, just add something
It allows the creation of backup files with weekly/daily/montly versions
We can then setup 3 cronjobs same command, only different prefix
The result would be
/dir/$prefix$db.sqsl
Resulting in the following with prefixes --prefix daily- --prefix weekly- --prefix monthly-
/dir/daily-dbname.sql
/dir/weekly-dbname.sql
/dir/monthly-dbname.sql

**Comment by seansan** [comment]
https://github.com/webmin/webmin/pull/1043

**Comment by jcameron** [comment]
Good idea, I will add a field to the backup form for this.
