### ISSUE TITLE
When a VLAN interface has a virtual interface, active_interfaces() returns wrong info

### ISSUE THREAD

**Issue by michaelbaisch** [webmin/webmin#1045]
Hello,

have been working on VLAN interfaces and it appears there is another small parsing bug in the `active_interfaces` method, when there is also a virtual interface involved.

Input: 

```
4: eth0.701@eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether *** brd ff:ff:ff:ff:ff:ff
    inet 203.0.113.146/29 scope global eth0.701
       valid_lft forever preferred_lft forever
    inet6 fe80::ba27:ebff:fedb:3b8c/64 scope link 
       valid_lft forever preferred_lft forever
5: eth0.702@eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether *** brd ff:ff:ff:ff:ff:ff
    inet 192.168.200.195/24 brd 192.168.200.255 scope global eth0.702:1
       valid_lft forever preferred_lft forever
```

Return value:

```
$VAR4 = { 'fullname' => 'eth0.701@eth0', 'edit' => 1, 'up' => 1, 'address6' => [ 'fe80::ba27:ebff:fedb:3b8c' ], 'index' => 3, 'scope6' => [ 'link' ], 'mtu' => '1500', 'name' => 'eth0.701@eth0', 'ether' => '***', 'netmask6' => [ '64' ] };
$VAR5 = { 'fullname' => 'eth0.702@eth0', 'up' => 1, 'broadcast' => '192.168.200.255', 'edit' => 1, 'index' => 4, 'scope6' => [], 'address6' => [], 'mtu' => '1500', 'netmask6' => [], 'name' => 'eth0.702@eth0', 'ether' => '***' }
```

`eth0.702:1` is completely missing. It's because the name has an `@+interface_name` in it and that doesn't match with the part before the colon. https://github.com/webmin/webmin/blob/master/net/linux-lib.pl#L84

My suggestion is to replace line [26](https://github.com/webmin/webmin/blob/master/net/linux-lib.pl#L26):

```
$l =~ /^\d+:\s+(\S+):/ || next;
```

with 

```
$l =~ /^\d+:\s+(\S+?)[\@:]/ || next;
```

This way the `fullname` then is `eth0.702` without the @ part and in this way is also consistent with the names returned from `boot_interfaces()`.

Greetings,
Michael

**Comment by jcameron** [comment]
Good idea - we'll do this.

**Comment by michaelbaisch** [comment]
I'm afraid your regex doesn't work. `^\d+:\s+([^ \t\r\n\@]+):` will not match `5: eth0.702@eth0:` at all since there are characters (eth0) between the `@` sign and the colon. So if you don't want to use my initial suggestion, here is another suggestion `^\d+:\s+([^\s\@]+)\S+:`
