### ISSUE TITLE
Unable to load web-interface

### ISSUE THREAD

**Issue by TotomInc** [webmin/webmin#1050]
I installed webmin 1.900 on a Raspberry PI 3 and I'm unable to load the web-interface after I've successfully logged in with the `pi` user.

I've attached a screenshot of what the web-interface looks like.

Network calls done by the API seems to work well, however there are errors in the `bundle.min.js` script:

```javascript
bundle.min.js?1921999999999901:277 Uncaught ReferenceError: settings_leftmenu_width is not defined
    at load_init (bundle.min.js?1921999999999901:277)
    at bundle.min.js?1921999999999901:278
load_init @ bundle.min.js?1921999999999901:277
(anonymous) @ bundle.min.js?1921999999999901:278

bundle.min.js?1921999999999901:260 Uncaught ReferenceError: settings_side_slider_enabled is not defined
    at HTMLDocument.<anonymous> (bundle.min.js?1921999999999901:260)
(anonymous) @ bundle.min.js?1921999999999901:260

bundle.min.js?1921999999999901:261 Uncaught ReferenceError: settings_leftmenu_width is not defined
    at n (bundle.min.js?1921999999999901:261)
    at HTMLDocument.<anonymous> (bundle.min.js?1921999999999901:261)
n @ bundle.min.js?1921999999999901:261
(anonymous) @ bundle.min.js?1921999999999901:261

bundle.min.js?1921999999999901:272 Uncaught ReferenceError: config_portable_theme_locale_language is not defined
    at theme_config_post_load (bundle.min.js?1921999999999901:272)
    at Object.success (bundle.min.js?1921999999999901:272)
    at c (bundle.min.js?1921999999999901:24)
    at Object.fireWith [as resolveWith] (bundle.min.js?1921999999999901:24)
    at r (bundle.min.js?1921999999999901:25)
    at XMLHttpRequest.<anonymous> (bundle.min.js?1921999999999901:26)
```

![image](https://user-images.githubusercontent.com/9285210/56469529-62814d80-643b-11e9-9c5b-061ffbf97c1d.png)

**Comment by rostovtsev** [comment]
Hi,

I seems that something went wrong.

You could restart Webmin by running `/etc/webmin/restart` and force reload the browser by hitting `Ctrl+Shift+R`.

Besides, try to update the theme to the latest 19.31 stable version, using console script `./theme-update.sh`.

**Comment by TotomInc** [comment]
Sorry for asking this, but where can I find the `theme-update.sh` script?

I tried to look on `/var/webmin` but can't find it, where are stored webmin files?

**Comment by rostovtsev** [comment]
It's inside of `authentic-theme` directory, which is in place inside of Webmin root directory.

**Comment by swelljoe** [comment]
Webmin root directory is either `/usr/libexec/webmin` (rpm) or `/use/share/webmin` (deb). That's if you installed from a package (which is what is recommended).

**Comment by TotomInc** [comment]
After updating the theme, it seems to work well. Thanks for the help, but I don't know what caused this issue.
