### ISSUE TITLE
Webmin used with webprefix - bug for modules with the same name

### ISSUE THREAD

**Issue by rostovtsev** [webmin/webmin#1051]
Jamie, I discovered a fancy bug.

When used via proxy with directory, like `https://hostname/webprefix`, in case webprefix set to `webmin`, then _Webmin/Webmin Logs_ and _Webmin/Webmin Configuration_ do not work correctly. Authentic Theme relies on `get_module_name()` and it seems that module name is returned empty by mentioned sub, if the module's name and the webprefix name match.

**Comment by jcameron** [comment]
Does this happen only the the prefix name is actually "webmin" ?

**Comment by rostovtsev** [comment]
Yes, to check it I just changed web-prefix to `log` and then `logrotate` stopped working, then I did the same for `sys` and then `syslog` stopped working. It just returns broken page:

![image](https://user-images.githubusercontent.com/4426533/57189357-8f8f2f00-6f16-11e9-9305-8c36d8be7e66.png)

This is how it looks in Gray Theme:

![image](https://user-images.githubusercontent.com/4426533/57189396-ff9db500-6f16-11e9-92f2-d12e550816ae.png)


..and if you go to modules configuration, here what it returns:

![image](https://user-images.githubusercontent.com/4426533/57189404-18a66600-6f17-11e9-8af0-e4c74de10b9e.png)

**Comment by rostovtsev** [comment]
Jamie, you can certainly reproduce it. Why this is happening? :smirk:

**Comment by jcameron** [comment]
Try out the patch I just attached to this bug report, and see if that helps.

**Comment by rostovtsev** [comment]
It seems to work. Thanks! 

I will give more tests in other environments.

**Comment by rostovtsev** [comment]
Jamie, in case `webprefixnoredir=0` and `webprefix=/webmin`, Webmin Configuration module (webmin) doesn't work/open correctly.

![image](https://user-images.githubusercontent.com/4426533/58156829-b45a0500-7c7f-11e9-86ec-3364d2e46637.png)


I don't know if it's important and can be fixed without breaking anything, if it could, it's better be fixed.

**Comment by rostovtsev** [comment]
..worth mentioning, that the same with `webprefixnoredir=1` works correctly.

**Comment by jcameron** [comment]
Hmm ... now I'm not sure why I added that code in the first place.

In the case where it failed for you, were you accessing Webmin via a proxy under the `/webmin` path?

**Comment by rostovtsev** [comment]
Yes, correct. Modules `webmin` and `webminlog` failed in case of `webmin` prefix `webprefixnoredir=0`. In case webprefix is, `sys`, for instance, then modules starting with _sys_ would fail. :man_shrugging:

**Comment by jcameron** [comment]
Now I think about it, does that line `$sn =~ s/^$gconfig{'webprefix'}\//\//` even need to exist at all?

**Comment by rostovtsev** [comment]
In my test case it works just fine without it, disregard of `webprefixnoredir` configuration value. :nerd_face:
