### ISSUE TITLE
Drop super old themes

### ISSUE THREAD

**Issue by rostovtsev** [webmin/webmin#1052]
Jamie, hi. I would like to propose to completely avoid from showing in UI or remove super old themes (Old Webmin Theme, Caldera Theme, MSC.Linux Theme, and Old Blue Framed Theme). 

By default, I think, all of them could and should go nowadays, leaving only **Gray Framed Theme**  and   **Authentic Theme**. 

They look scary and practically useless.

Can we do it?

**Comment by jcameron** [comment]
Those old themes shouldn't even be in the latest package though, so they won't even show up in the menu.
