### ISSUE TITLE
File manager can not open folders

### ISSUE THREAD

**Issue by bird2019** [webmin/webmin#1053]
File manager can not open folders after a update today.
showing as attached screen shot.
![webminprob](https://user-images.githubusercontent.com/46427226/57208278-4cdf5c80-6fd3-11e9-8715-d6e32d98e6bc.PNG)
![webminupdate](https://user-images.githubusercontent.com/46427226/57208282-549f0100-6fd3-11e9-9476-b7954353bc72.PNG)
![webminupdate2](https://user-images.githubusercontent.com/46427226/57208283-57015b00-6fd3-11e9-98d9-ee0bb0563c7a.PNG)

**Comment by rostovtsev** [comment]
What it the folder name that your are trying to open and can not?

**Comment by bird2019** [comment]
Well, after logout and back in again, it works fine now.
Just now when I trying open any folder it would show the red screen.

**Comment by rostovtsev** [comment]
What is that exact folder name that you're trying to access and get and error?

**Comment by bird2019** [comment]
Once openning the file manager then the red screen pop out. it would disapear after seconds or could be closed manually. Then if try to open ANY folder, it showed the red creen again.

**Comment by rostovtsev** [comment]
Okay, any folder doesn't work?

Can you try to clear all cache and reload? Try inbuilt theme hotkeys to do that in no time - `Ctrl+Alt(Option)+Shift+Meta(Cmd)+R`.

**Comment by rostovtsev** [comment]
Okay, what is the output in browser's console of:

```JS
config_portable_module_filemanager_records_for_server_pagination
```

**Comment by rostovtsev** [comment]
and of:

```JS
config_portable_module_filemanager_records_per_page
```

**Comment by rostovtsev** [comment]
Okay, never mind. It's fixed on the latest [commit](https://github.com/authentic-theme/authentic-theme/commit/23d4e7c640465ceba572634542e9f3fd0a66d514).

Apparently, you have `config_portable_module_filemanager_records_per_page` set to _1000_ which is obsolete now.

By the way, can you please tell me, what is the point of setting pagination number to such high value?
