### ISSUE TITLE
Install modules gives Error 404

### ISSUE THREAD

**Issue by P0u1us** [webmin/webmin#1056]
Today I got a fresh new VPS install with the latest webmin v1.910 on it.
When selecting new un-used modules (like fail2ban or Postfix) from the drop down list
after the popup that it can be installed via recommended “[click here] to download/install via APT”
Then waiting for the build of packages list, which shows n packages, then click [install now]
It goes into directly into 404 File not found!
Looks like the link under the [install now] button is faulty.

I resolved it with rollback to v1.900, then it properly works.

**Comment by jcameron** [comment]
What gets logged to `/var/webmin/miniserv.error` when you get this 404 error?

**Comment by P0u1us** [comment]
you will be in luck ;-) as I am going to rebuild the server from scratch again tomorrow;, then I can give you the results. keep in mind that I am not going to rebuild it thereafter again; thus if you think of more info you would like, please inform me on forehand. As mentioned: I reverted to v1.900 as a solution, thus will do that again in the new build..

**Comment by P0u1us** [comment]
Hi, in miniserv.error there is nothing found on this,
it just gives an general error that webmin is not running (SSL yet):
[13/May/2019:09:41:35 +0200] [24.132.174.153] Document follows : This web server is running in SSL mode. Try the URL <a href='https://vmi265083.contaboserver.net:10000/'>https://vmi265083.contaboserver.net:10000/</a> instead.<br>

BUT, in miniserv.log, the following is noted:
24.132.174.153 - - [13/May/2019:09:34:30 +0200] "GET / HTTP/1.1" 401 4581
24.132.174.153 - - [13/May/2019:09:34:30 +0200] "GET /unauthenticated/css/bundle.min.css?1933999999999901 HTTP/1.1" 200 128144
24.132.174.153 - - [13/May/2019:09:34:30 +0200] "GET /unauthenticated/css/fonts-roboto.min.css?1933999999999901 HTTP/1.1" 200 351590
24.132.174.153 - - [13/May/2019:09:34:31 +0200] "GET /images/favicons/webmin/favicon-32x32.png HTTP/1.1" 200 1787
24.132.174.153 - root [13/May/2019:09:34:36 +0200] "POST /session_login.cgi HTTP/1.1" 302 0
24.132.174.153 - root [13/May/2019:09:34:37 +0200] "GET /unauthenticated/js/defaults.js?1933999999999901 HTTP/1.1" 200 4570
24.132.174.153 - root [13/May/2019:09:34:37 +0200] "GET /unauthenticated/css/bundle.min.css?1933999999999901 HTTP/1.1" 200 128144
24.132.174.153 - root [13/May/2019:09:34:37 +0200] "GET /unauthenticated/css/fonts-roboto.min.css?1933999999999901 HTTP/1.1" 200 351590
24.132.174.153 - root [13/May/2019:09:34:37 +0200] "GET /unauthenticated/js/bundle.min.js?1933999999999901 HTTP/1.1" 200 463767
24.132.174.153 - root [13/May/2019:09:34:37 +0200] "GET /images/favicons/webmin/favicon-16x16.png HTTP/1.1" 200 1146
24.132.174.153 - root [13/May/2019:09:34:37 +0200] "GET / HTTP/1.1" 200 63155
24.132.174.153 - root [13/May/2019:09:34:38 +0200] "GET /extensions/stats/stats.min.js?1933999999999901 HTTP/1.1" 200 1286
24.132.174.153 - root [13/May/2019:09:34:43 +0200] "POST /sysinfo.cgi HTTP/1.1" 200 12113
24.132.174.153 - root [13/May/2019:09:34:43 +0200] "GET /images/sort_both.png HTTP/1.1" 200 1136
24.132.174.153 - root [13/May/2019:09:35:31 +0200] "POST /fail2ban/ HTTP/1.1" 200 5057
24.132.174.153 - root [13/May/2019:09:35:34 +0200] "GET /software/install_pack.cgi?source=3&update=fail2ban&return=%2E%2E%2Ffail2ban%2F&returndesc=Fail2Ban%20module&caller=fail2ban HTTP/1.1" 302 0
24.132.174.153 - root [13/May/2019:09:36:03 +0200] "GET /package-updates/update.cgi?redir=/software/&redirdesc=Software%20Packages&mode=new&u=fail2ban HTTP/1.1" 200 51160
24.132.174.153 - root [13/May/2019:09:36:05 +0200] "POST /software/update.cgi HTTP/1.1" 404 3535
24.132.174.153 - root [13/May/2019:09:36:25 +0200] "POST /shell/index.cgi?stripped=1&stripped=2 HTTP/1.1" 200 2479
24.132.174.153 - root [13/May/2019:09:36:30 +0200] "POST /shell/index.cgi?stripped=1&stripped=2 HTTP/1.1" 200 2621
24.132.174.153 - root [13/May/2019:09:36:37 +0200] "POST /shell/index.cgi?stripped=1&stripped=2 HTTP/1.1" 200 2867
24.132.174.153 - root [13/May/2019:09:36:41 +0200] "POST /shell/index.cgi?stripped=1&stripped=2 HTTP/1.1" 200 2829
24.132.174.153 - root [13/May/2019:09:40:04 +0200] "POST /software/ HTTP/1.1" 200 12822
24.132.174.153 - root [13/May/2019:09:40:10 +0200] "POST /fail2ban/ HTTP/1.1" 200 5057
24.132.174.153 - root [13/May/2019:09:40:13 +0200] "GET /software/install_pack.cgi?source=3&update=fail2ban&return=%2E%2E%2Ffail2ban%2F&returndesc=Fail2Ban%20module&caller=fail2ban HTTP/1.1" 302 0
24.132.174.153 - root [13/May/2019:09:40:18 +0200] "GET /package-updates/update.cgi?redir=/software/&redirdesc=Software%20Packages&mode=new&u=fail2ban HTTP/1.1" 200 51160
24.132.174.153 - root [13/May/2019:09:40:21 +0200] "POST /software/update.cgi HTTP/1.1" 404 3535

Hope this will serve you!
I am rebuilding my server now and rollback webmin ;-)

**Comment by cookta2012** [comment]
I also get 

[16/May/2019:20:50:04 +0200] miniserv.pl started
[16/May/2019:20:50:04 +0200] IPv6 support cannot be enabled without the Socket6 perl module
[16/May/2019:20:50:04 +0200] Using MD5 module Digest::MD5
[16/May/2019:20:50:04 +0200] Using SHA512 module Crypt::SHA
[16/May/2019:20:50:04 +0200] PAM authentication enabled
[16/May/2019:20:50:21 +0200] [209.207.5.50] Document follows : This web server is running in SSL mode. Try the URL <a href='https://vmi265767.contabo.com:10000/'>https://vmi265767.contabo.com:10000/</a> instead.<br>
[16/May/2019:20:50:24 +0200] [209.207.5.50] Document follows : This web server is running in SSL mode. Try the URL <a href='https://vmi265767.contabo.com:10000/'>https://vmi265767.contabo.com:10000/</a> instead.<br>
[16/May/2019:20:50:25 +0200] [209.207.5.50] Document follows : This web server is running in SSL mode. Try the URL <a href='https://vmi265767.contabo.com:10000/'>https://vmi265767.contabo.com:10000/</a> instead.<br>
[16/May/2019:20:50:29 +0200] Reloading configuration
[16/May/2019:20:50:36 +0200] Reloading configuration
Use of uninitialized value in numeric ne (!=) at /usr/share/webmin/bind8/bind8-lib.pl line 2397.
Use of uninitialized value in string eq at /usr/share/webmin/webmin/webmin-lib.pl line 656.
Use of uninitialized value in string eq at /usr/share/webmin/webmin/webmin-lib.pl line 656.

**Comment by SoShoTech** [comment]
I'm getting the same error - running latest Webmin with Ubuntu 18.04.  As a workaround, am just ssh-ing in and manually installing the few php packages I need.

**Comment by jcameron** [comment]
For those seeing this error - does it make any difference if you switch to the older Grey Framed Theme?

**Comment by cookta2012** [comment]
that works for me. unfortunately it looks like the new theme is busted

**Comment by rostovtsev** [comment]
Hmmm. I am surprised to see this error as well.

I will work it out.

Thanks for reporting.

**Comment by rostovtsev** [comment]
Hmmmmm, actually older Gray Theme doesn't work as well:

![image](https://user-images.githubusercontent.com/4426533/57974681-f60b5700-79c4-11e9-8226-50ad95d35977.png)

**Comment by rostovtsev** [comment]
Okay, this error was appearing in 1.900.

Upgrading to 1.910 and trying again...

**Comment by rostovtsev** [comment]
Okay, I see the source of the issue. 

Progressive pages can also have redirects. Ahh.

**Comment by rostovtsev** [comment]
The latest commit to Authentic Theme repo fixes this issue.

Install latest development version using theme configuration to give it a try.

Upcoming theme release version 19.34 will fix this issue.

**Comment by rostovtsev** [comment]
Another fix has been added to make sure that history steps are working correctly (part of progressive page isn't added to browser history), when redirect happens upon progressive output. :alien: 

This issue can be considered solid solved. :nerd_face:

**Comment by P0u1us** [comment]
Thnx for your effort, we can now continue with life ;-)

**Comment by Akila1996522** [comment]
I have to face user interface after ssl installation. I mentioned it below
![image](https://github.com/webmin/webmin/assets/54936379/c8dfefc0-fb79-4031-89ee-3b2030a63daa)

After click on login to it redirect to 404 error . It show below
![image](https://github.com/webmin/webmin/assets/54936379/daafcde4-7b65-4c4f-8720-f7e33a3b7164)

Before change ssl=1 in miniserv.conf it show properly. But after change to ssl=0 it show as above screen shot. How can I install this properly
