### ISSUE TITLE
java file manager

### ISSUE THREAD

**Issue by campones** [webmin/webmin#1057]
Did you really remove the file manager?  I can't believe this is happening.

how can I downgrade to a previous version

thanks

**Comment by swelljoe** [comment]
Yes, Java in browsers has been deprecated for *years*. If browsers can't support it, neither can we.

And, you don't need to downgrade Webmin. The Java File Manager module is still available in the module repository, just install it in the Webmin->Webmin Modules page.

Can you tell us why you would choose the Java File Manager over the new File Manager?

**Comment by jcameron** [comment]
You can also directly download the module from here : http://download.webmin.com/download/modules/file.wbm.gz

**Comment by campones** [comment]
thats interesting, thanks, so I can keep webmin up to date and still have the module!

**Comment by campones** [comment]
> Can you tell us why you would choose the Java File Manager over the new File Manager?

> 

the java module provide a nice directory tree for fast access, it opens each file in separate windows, you can save and ctrl-z and save again in case of error. 

 it's not perfect but I like it much more than the html file manage. i know a lot of work has been commit to that manager but I just don't like it..

**Comment by swelljoe** [comment]
The new File Manager has a directory tree, too. It's been in there for a few months.

Files are opened in pseudo-windows...you can have many open, though they are limited to the browser window (it doesn't open a new browser window).

Save/undo/resave also works.

So...all features are there. We can't make you *like* it, but it has feature parity (and more) with the Java File Manager, as far as I know, including the obscure infrequently used features.

Anyway, I'm going to close this issue, as we can't realistically bring Java file manager back...Java in browsers is dead. We can't bring back the dead, so we have to make the HTML 5 file manager do the job (I think it's much better, but everybody has preferences and what they're used to).
