### ISSUE TITLE
show.cgi

### ISSUE THREAD

**Issue by gianni100** [webmin/webmin#1058]
Since I have upgraded to 1.910 I get an 404 Error when trying to show a logfile in the browser.

https://servername/file/show.cgi/var/log/fail2ban.log leads to 404 file not found.

What I am missing?

**Comment by rostovtsev** [comment]
Hi,

Does it happen in Java File Manager?

Could you provide the screenshot?

**Comment by gianni100** [comment]
I am opening a new browser-tab - then I am inserting the above adress (I have bookmarked it) ... I dont know whether this belongs to Java File Manager.


![grafik](https://user-images.githubusercontent.com/50586307/57630142-55203480-759d-11e9-82b3-edd9b8bd1d8a.png)

**Comment by rostovtsev** [comment]
Java File Manager was deleted from the last Webmin 1.910. You can manually install it using Webmin/Webmin Modules.

What is the main reason for using Java File Manager over HTML5 File Manager?

**Comment by gianni100** [comment]
Well in fact I am using the HTML5 File Manager.
I used this bookmark as it shows me the whole content of the fail2ban.log with a single click. Up to now I was not even aware, that this was belonging to the Java File Manager :)

Is there a similar possibility within in HTML5 FileManager? An adress that I can bookmark so it shows me the full content of fail2ban.log?

**Comment by rostovtsev** [comment]
Yes, you can do the same in File Manager's editor and click star to bookmark it. Or you could use System Logs module to do it, and then again bookmark it in the theme to have instant access to it. (It's better than using file editor).

**Comment by gianni100** [comment]
Thank you for helping me out :)

**Comment by swelljoe** [comment]
Closing this one, as Java File Manager has been intentionally removed, and there are alternative means of achieving the same end.
