### ISSUE TITLE
update.cgi not found when installing packages from unused modules.

### ISSUE THREAD

**Issue by askfinney** [webmin/webmin#1059]
On Debian 9, I'm getting a 404 file not found error.

Steps to reproduce:
1.) Click Un-used Modules
2.) Click any module
3.) Click install using "APT" and wait for package list to return.
4.) Click "install"

I've tried checking /usr/share/webmin/software and there is no update.cgi. I've also tried symbolically linking and modifying the scripts to use /webmin/update.cgi with no luck.

**Comment by rostovtsev** [comment]
Hi,

Yes, unfortunately there was a bug in the theme. It's fixed now. You can install latest development version of the theme (using theme configuration), to have it working.

**Comment by askfinney** [comment]
OK re-testing with the following:

1.) apt-get install apt-transport-https nano gnupl1 perl libnet-ssleay-perl openssl libauthen-pam-perl libpam-runtime libio-pty-perl apt-show-versions python wget

2.) _Adding_ deb https://download.webmin.com/download/repository sarge contrib _to_ /etc/apt/sources.list

3.) wget -qO -http://www.webmin.com/jcameron-key.asc | sudo apt-key add -

4.) Log in as _root_ and update theme.

Will report back and close.

**Comment by askfinney** [comment]
That worked. Thank you very much!
