### ISSUE TITLE
mount::list_system_info failed : Illegal division by zero at /usr/share/webmin/mount/system_info.pl line 31.

### ISSUE THREAD

**Issue by 1cabron** [webmin/webmin#1060]
![webmin issue](https://user-images.githubusercontent.com/50849934/58056958-76eb5f80-7b39-11e9-9534-a545d219bc2f.JPG)

**Comment by rostovtsev** [comment]
Hi,

There was a bug. It's been fixed a while ago.
https://github.com/webmin/webmin/commit/f6c2f11dc3e4ad2d9e8f183394090ad005c5e894

**Comment by 1cabron** [comment]
Hi,

I uninstalled Webmin, and reinstalled (with "Wget....), still get this error.  Will try again.

Thank you for responding. 
:)

**Comment by rostovtsev** [comment]
Just update the file from the error. That's all you need to do.

You are welcome.

**Comment by 1cabron** [comment]
Hi Rostovtsev,

My sincere apologies, but how do I update the file? I'm a newbie, and i have googled how to do, but have not been able to update the file.

Apologetic Canadian

**Comment by rostovtsev** [comment]
What is your distro?

**Comment by 1cabron** [comment]
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian

**Comment by rostovtsev** [comment]
Okay.

You can change this file in:

```
/usr/share/webmin/mount/system_info.pl
```

**Comment by 1cabron** [comment]
So i do this:

As root:
1. Copy the contents of the file you gave in your response 
2. Paste it into the existing file.
3. save it.
4. restart webmin

Am i correct?

**Comment by rostovtsev** [comment]
Yes, replace local file with this:

```
https://github.com/webmin/webmin/blob/f6c2f11dc3e4ad2d9e8f183394090ad005c5e894/mount/system_info.pl
```

**Comment by 1cabron** [comment]
:) will give it a go...thank you for your patience with me.  Thanks

**Comment by 1cabron** [comment]
I was unable to put the new file into the directory; due to the need to have root privileges. 

So I **uninstalledV1.91**  using this command /etc/webmin/uninstall.sh), 

and reinstalled it using the instructions from the Webmin site (using: root@debian:/usr/share/webmin/mount# wget http://prdownloads.sourceforge.net/webadmin/webmin_1.910_all.deb wget http://prdownloads.sourceforge.net/webadmin/webmin_1.910_all.deb

_I still get the error._

I have been using webin on 4 Linux headless boxes for 5 years, and never a problem. I don't have a problem with my other machines.

Appreciate any assistance you can provide.
Thanks.
. This resulted in the same error. I assume the download has the undated file.

After the reinstall of Webmin. I still got the error. Could it be that the updated webmin V1.91 doesn't have the updated file?

I still have the error

**Comment by rostovtsev** [comment]
Without `root` privileges you wouldn't be ble to uninstall/install Webmin.

Anyway, you can use File Manager to open and edit the file. Apart from that, you can call drop-down Command Line port (Alt+K) and edit needed file:

```
edit /usr/share/webmin/mount/system_info.pl
```

**Comment by 1cabron** [comment]
Hi Rostovtsev,

I used putty and logged in as root to uninstall/install. The uninstall/install was done successfully. I suspect that v1.91 doesn't have the updated file?

I attempted to use file manager (can't login as root), and was able to edit the file, but not able to save it.  I wish could login as root, makes life simpler (but more dangerous).


Edit:

I uninstalled (again), re-installed using apt-get, I still get the same error. Could there be another issue?

**Comment by rostovtsev** [comment]
:smile: Look, you could run `./update-from-repo.sh` script from `/usr/share/webmin/` using your SSH client and install latest version from Git. It will work.

**Comment by 1cabron** [comment]
It worked!!!! 

This was easy, and it worked.  

Thank you very much!!!

Appreciate your patience with resolving the issue!!!


:) :) 👍

**Comment by rostovtsev** [comment]
My pleasure.

**Comment by Asw20** [comment]
@iliaross  Thanks a lot it fixes my problem.

**Comment by linhux** [comment]
it worked :-) also on freebsd

**Comment by jmeca** [comment]
It work for me, too thank you very much
