### ISSUE TITLE
firewall6: config "save_file6" should be "save6_file" otherwise Error

### ISSUE THREAD

**Issue by iam-TJ** [webmin/webmin#1062]
webmin 1.910

miniserv.error and the web interface report:

Error: Missing file to read at firewall6::./firewall-lib.pl line 163

When trying to display the IPv6 rules via Network > Firewall{,6}  after setting the module config via Configuration > IPv6 Configuration > "File to save/edit IPv6 rules" having set a custom path to the save file.

In my case I'm setting it to "/etc/iptables/rules.v6" so that webmin will be in sync with the Debian/Ubuntu systemd netfilter-persistent.service that loads these rules at boot time.

It took me a while going back and forth through the source-code to figure this out and unfortunately I got lost tracking down the root-cause, so cannot offer a patch, but by adding "save6_file" into the webmin/firewall6/config file the web interface can now display the IPv6 rules.

**Comment by jcameron** [comment]
Thanks - I will fix Webmin in the next release to respect the `save_file6` option.
