### ISSUE TITLE
Allow disabling/enabling hosts entries

### ISSUE THREAD

**Issue by Bluscream** [webmin/webmin#1066]
I would be very thankful if the HOSTS module was able to toggle HOSTS entries without deleting them by either
```
127.0.0.1 localhost # Normal entry with comment
# 127.0.0.1 localhost # disabled entry with comment
```
OR just move disabled ones to `/etc/hosts.disabled` if that gives better performance

**Comment by jcameron** [comment]
I like the idea of commenting them out .. I'll add this to our TODO list

**Comment by jcameron** [comment]
This has been implemented for inclusion in the next release.
