### ISSUE TITLE
Download without Pop-up

### ISSUE THREAD

**Issue by michaelbaisch** [webmin/webmin#1068]
Hello again,

I'm building a another module, where the user has the ability to download a certain file. So I copied the functionally form here: https://github.com/webmin/webmin/blob/master/filemin/download.cgi . In the beginning the download wasn't working at all. I found out that it only works when I uncheck "Block pop-up windows" in my browser security settings. I played around a bit, looked at the HTTP header, changed the content-type, but with no luck. I guess it's possible somehow (other websites have no problem with this) and I can only guess that it has something to do with the dynamic content loading and the way webmin handles user sessions and access to pages.
The build-in downloading functions in filemin and the webmin configuration also requires pop-ups to not be blocked. 
Does anyone know a way to provide a file download without requiring to enable pop-ups in the browser?

Greetings,
Michael

**Comment by rostovtsev** [comment]
Michael, hi.

You could simply add to your link the following JavaScript code:

```
event.preventDefault(); window.location.replace(link_to_file)
```

**Comment by michaelbaisch** [comment]
Thanks for the hint, I had to modify it a bit to get it to work properly. For future reference:

```perl
print ui_buttons_row('backup.cgi', $text{'index_backup'},
                    $text{'index_backup_desc'});

print "<script type=\"text/javascript\"> \$(\"form[action*='backup.cgi'] button\").click(function(e){  window.location.replace('backup.cgi'); return false; }); </script>";
```

in this case `event.preventDefault()` doesn't work nicely because the webmin pages says it lost connection to the server for a while so I used `return false` here.

The download is working the only thing is that in the console there is still this error:

```
[Error] Failed to load resource: Frame load interrupted (backup.cgi, line 0)
```
