### ISSUE TITLE
ENCRYPT File Manager

### ISSUE THREAD

**Issue by PauloBoaventura** [webmin/webmin#1071]
### **_ENCRYPT File Manager_**
I searched in several places, as in the Webmin / Virtualmin Wiki ... But I did not quote any quotes ...

**I wonder where I can set this option. Does it have to be with LetsEncrypt or SSL?**

**_Any references in the WebMin or VirtualMin Guide?_**

I've attached some printscreen for better analysis ...

https://prntscr.com/o0qd2u
https://prntscr.com/o0pwp4

**Comment by rostovtsev** [comment]
Hi, Paulo.

Neither. You need to generate GPG key under the user, which you're going to use it. After key is generated, you'd be able to encrypt data with it.

Example of how to generate GPG key:

https://help.github.com/en/articles/generating-a-new-gpg-key
