### ISSUE TITLE
Autocorrect in the terminal is not disabled on iOS

### ISSUE THREAD

**Issue by janprzy** [webmin/webmin#1076]
Using the default terminal on iOS devices is extremely painful, since autocorrect is not fully disabled.

Inspecting the page's source code, I found that both _spellcheck_ and _autocomplete_ are disabled, but _autocorrect_ is not. Apparently, this flag is what Safari on iOS needs.
I would have tried myself if this works, but I couldn't find the responsible HTML file. 

I don't know it's got a name, but I'm talking about the terminal that appears when this button is pressed:
![Bildschirmfoto 2019-06-27 um 20 49 49](https://user-images.githubusercontent.com/41625296/60292633-dcdbbb80-991d-11e9-9d6b-9621261bb7a2.png)

**Comment by rostovtsev** [comment]
Hi, Jan.

You are right. It's fixed now. Please give it a try by installing latest development version of the theme using theme configuration page.

**Comment by janprzy** [comment]
That fixed it, thanks!
