### ISSUE TITLE
LDAP SSL certificate generation on Ubuntu 16.04

### ISSUE THREAD

**Issue by PitWenkin** [webmin/webmin#1078]
Last year I reported the bug:
https://www.virtualmin.com/node/40349

Which resulted in the following fix:
https://github.com/webmin/webmin/commit/e91b8bd929010cb05efe8e9196c2ed7b19d32d6f

While the fix is working on a recently installed Ubuntu 18.04 server, it is still not possible to generate SSL certificates on Ubuntu 16.04 installations

![Screen Shot 2019-07-05 at 16 34 49](https://user-images.githubusercontent.com/45786226/60729387-d911ef80-9f42-11e9-8e92-3dcec611daa3.png)

After clicking the 'Generate SSL Certificate'-button the button is disabled and a red loading animation at the top apears, but nothing happens. (On Ubuntu 18.04 shorty after clicking I'm presented with a form allowing me to fill out the certificate details)
![Screen Shot 2019-07-05 at 16 05 05](https://user-images.githubusercontent.com/45786226/60727725-e1682b80-9f3e-11e9-9bb4-f425b2fa93c3.png)

When reloading the screen after some minutes the following lines show up in syslog:

> Jul  5 16:07:55 st slapd[17422]: @(#) $OpenLDAP: slapd  (Ubuntu) (Apr 10 2019 13:01:36) $#012#011buildd@lgw01-amd64-031:/build/openldap-QaSHhB/openldap-2.4.42+dfsg/debian/build/servers/slapd
Jul  5 16:07:55 st slapd[17422]: daemon: bind(8) failed errno=98 (Address already in use)
Jul  5 16:07:55 st slapd[17422]: daemon: bind(8) failed errno=98 (Address already in use)
Jul  5 16:07:55 st slapd[17422]: slapd stopped.
Jul  5 16:07:55 st slapd[17422]: connections_destroy: nothing to destroy.
Jul  5 16:07:55 st slapd[22706]: conn=1004 op=0 do_extended: unsupported operation "1.3.6.1.4.1.1466.20037"

**Comment by jcameron** [comment]
Does anything get logged to `/var/webmin/miniserv.error` when this happens?

**Comment by PitWenkin** [comment]
There was no entry in `/var/webmin/miniserv.error`.

However I just logged in to the server and saw there was an update for webmin. After applying that update the whole process worked.  I'm presented with a form allowing me to fill out the certificate details which creates` ldap.cert` an l`dap.key` files in `/etc/ldap/slapd.d/`.

After wards I'm able to enable LDAP over SSL.

Whatever changed in the recent update seems to have fixed it
