### ISSUE TITLE
Error Uninstalling Minimal Version 

### ISSUE THREAD

**Issue by My-Random-Thoughts** [webmin/webmin#1080]
After installing **webmin-1.920-minimal.tar.gz**, I then removed it again with `sudo /etc/webmin/uninstall.sh`.  I got the following error:

`Stopping Webmin server in /home/user/Downloads/webmin-1.920`

`Running uninstall scripts ..`

`Can't locate WebminCore.pm in @INC (you may need to install the WebminCore module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.28.1 /usr/local/share/perl/5.28.1 /usr/lib/x86_64-linux-gnu/perl5/5.28 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.28 /usr/share/perl/5.28 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /home/user/Downloads/webmin-1.920/run-uninstalls.pl line 6.`

`BEGIN failed--compilation aborted at /home/user/Downloads/webmin-1.920/run-uninstalls.pl line 6.`

`Deleting /home/user/Downloads/webmin-1.920 ..`

`Deleting /etc/webmin ..`

`Done!`

System is Ubuntu 19.04 x64.

**Comment by DevDorrejo** [comment]
is uninstalled correctly, i recommend delete residual files manually.

**Comment by My-Random-Thoughts** [comment]
As far as I can tell everything was removed successfully except for the `webmin.service` startup service in systemd.  I had to remove that manually.

This was logged more for informational use rather than an issue I was having.  :)

**Comment by jcameron** [comment]
Does this same error happen if you install and then remove the full version of Webmin?

**Comment by DevDorrejo** [comment]
> 
> 
> As far as I can tell everything was removed successfully except for the `webmin.service` startup service in systemd. I had to remove that manually.
> 
> This was logged more for informational use rather than an issue I was having. :)

wow, i have installed today from the repo yum and the systemd service is not created.

**Comment by swelljoe** [comment]
systemd is a different issue from this altogether...has nothing to do with uninstalling the tarball install. Webmin currently does not ship a systemd unit file, it ships an initscript. Every distro we support has a compatibility layer, as far as I know. But, we'll likely add a systemd unit file soon.

**Comment by My-Random-Thoughts** [comment]
Sorry for the delay.  Yes I get the same error message when using the full version.  Additionally, when I installed it again, it had kept all my previous settings (I changed theme).  This was because I didn't delete the previous files/folder from the first "failed" uninstall.

As @swelljoe said, the systemd issue is separate, it will be because I previously ticked the "start at boot time" option.

**Comment by FireEmerald** [comment]
When installed via APT on Debian 10:
```
root@server:~# apt remove webmin
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following package was automatically installed and is no longer required:
  unzip
Use 'apt autoremove' to remove it.
The following packages will be REMOVED:
  webmin
0 upgraded, 0 newly installed, 1 to remove and 1 not upgraded.
After this operation, 175 MB disk space will be freed.
Do you want to continue? [Y/n] Y
(Reading database ... 58293 files and directories currently installed.)
Removing webmin (1.941) ...
Running uninstall scripts ..
Can't locate WebminCore.pm in @INC (you may need to install the WebminCore module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.28.1 /usr/local/share/perl/5.28.1 /usr/lib/x86_64-linux-gnu/perl5/5.28 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.28 /usr/share/perl/5.28 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /usr/share/webmin/run-uninstalls.pl line 6.
BEGIN failed--compilation aborted at /usr/share/webmin/run-uninstalls.pl line 6.
```
`/etc/init.d/webmin` is not deleted.

When installed as minimal version via TAR ball on Debian 10:
```
root@server:/etc/webmin# ./uninstall.sh
Are you sure you want to uninstall Webmin? (y/n) : y

Stopping Webmin server in /usr/share/webmin
Running uninstall scripts ..
Can't locate WebminCore.pm in @INC (you may need to install the WebminCore module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.28.1 /usr/local/share/perl/5.28.1 /usr/lib/x86_64-linux-gnu/perl5/5.28 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.28 /usr/share/perl/5.28 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /usr/share/webmin/run-uninstalls.pl line 6.
BEGIN failed--compilation aborted at /usr/share/webmin/run-uninstalls.pl line 6.
Deleting /usr/share/webmin ..
Deleting /etc/webmin ..
Done!
```
`/var/webmin/` is not deleted.

How about to fix the misleading error message and cleanup the missing files and directories?

**Comment by jcameron** [comment]
Ok, this will be fixed in the next Webmin release.
