### ISSUE TITLE
Change php-fpm port numbers start value from 8000 to user value

### ISSUE THREAD

**Issue by MurzNN** [webmin/webmin#1084]
At now Virtualmin starts to search php-fpm ports from 8000 number. But many servers actively use 8000-8100 range for other service (especially 8080).
Will be good to make this number configurable, for ability to change start port numbers (or range) to 11000, or any other user defined value.

**Comment by jcameron** [comment]
Not a bad suggestion. Maybe 9000 would be a better port to start from?

**Comment by MurzNN** [comment]
Yes, 9000 seems good start range, but on some servers it also can be busy, so will be good to have ability for configure it.

**Comment by chris001** [comment]
Many application servers use 9000 range because it's well know the 8000 range is already taken by web servers.
So the range default should be something typically unused ie 11000, and let it be admin configurable.

**Comment by iliarostovtsev** [comment]
Perhaps, just letting the user to define the port range would satisfy all eventually?

**Comment by chris001** [comment]
Yes.  Default should be a number much higher number than all the most common textbook examples (8000, 9000, and 10000).

**Comment by jcameron** [comment]
I've just checked in a change to allow that, for inclusion in the next release.

**Comment by swelljoe** [comment]
Default of 8000 is fine. There is a reasonable assumption that a Virtualmin system is dedicated to use by Virtualmin and the services it manages...it won't generally be running a bunch of other services on weird ports, and 8000 is a very common starting point for app servers. Being configurable solves all use cases, including unusual ones (like running other random stuff on your Virtualmin system).

**Comment by jcameron** [comment]
BTW, if you have the `lsof` command installed, Virtualmin will skip any ports already in use by **running** servers.

**Comment by iliarostovtsev** [comment]
> if you have the lsof command installed, Virtualmin will skip any ports already in use by running servers.

_lsof_ available on all **-linux** distros.

> I've just checked in a change to allow that, for inclusion in the next release.

That works just great, thanks Jamie!

**Comment by jcameron** [comment]
It's available, but not necessarily installed by default.
