### ISSUE TITLE
Servers with non standart web ports are not offered the SSL-Options

### ISSUE THREAD

**Issue by PitWenkin** [webmin/webmin#1085]
If using ports `8080 / 8088` instead of `80 / 443` the `SSL Options`-icon is not offered.

https://github.com/webmin/webmin/blob/ed88a51ed13255d8dfe1143afe665fc261e992f7/apache/virt_index.cgi#L21

![443](https://user-images.githubusercontent.com/45786226/62277248-0f5d6480-b446-11e9-827c-b155b8c9c0d4.png)

The link it would point to ( e.g. `edit_virt.cgi?virt=<domain>:8088&type=14&xnavigation=1`) however does seem to work

(This seems might be an issue due due the relation between webmin and virtualmin, therefore I'm not sure if this is the right place to submit it)

**Comment by jcameron** [comment]
Good point, we'll fix this logic in the next release.
