### ISSUE TITLE
[DNSSEC] Spaces in public key

### ISSUE THREAD

**Issue by TakeMeNL** [webmin/webmin#1086]
Hi there,

So i discovered a small "bug" the the way the public keys are printed on edit_zonekey.cgi (Setup DNSSEC Key) 
Because the key has newlines in it these appear as spaces. When you copy past the record, you need to manually remove these spaces. 

https://github.com/webmin/webmin/blob/e58109711331109aa7eff5e1459dbfce57d97916/bind8/edit_zonekey.cgi#L45

**Comment by jcameron** [comment]
Hi - are you referring to the key shown in the "Public key record" field?

**Comment by TakeMeNL** [comment]
Yes "Public key record" field for key signing and for zone signing

**Comment by jcameron** [comment]
Thanks - we'll fix this (see https://github.com/webmin/webmin/commit/332d71dcd66edbaf90e2bf011ddf681bd8d40265)

**Comment by TakeMeNL** [comment]
Thank you!
