### ISSUE TITLE
Reboot warning after Webmin update

### ISSUE THREAD

**Issue by mikewitlin** [webmin/webmin#1091]
After updating Webmin the warning to reboot message appears on Dashboard even after multiple reboots.  See attached screenshot:

![WebminWarning](https://user-images.githubusercontent.com/3359792/63361109-872ff800-c33d-11e9-894d-9533307a0bb9.png)

Any assistance in resolving this would be greatly appreciated.

Thanks,
Mike

**Comment by rostovtsev** [comment]
@mikewitlin 


What is the output of the following commands:

1. 

~~~Bash
rpm -q kernel --qf "%{INSTALLTIME}\n"
~~~

2. 

~~~Bash
sed -n '/^btime /s///p' /proc/stat
~~~

3. 

~~~Bash
rpm -q kernel-3.10.0-957.27.2.el7.x86_64
~~~

**Comment by rostovtsev** [comment]
Mike, so what is the output of commands above?

**Comment by rostovtsev** [comment]
Mike, it only takes a minute to provide the output of commands above. Could you do it?

**Comment by mikewitlin** [comment]
Thanks for the followup - I didn't see this right away.

Anyway, there was a new update that was posted and we went ahead and
applied it - now we are up and running on webmin 1.930 and theme 19.39-2.
and the Notice has been cleared.

Whatever it was the next update fixed it.

Thanks,
Mike

**Comment by shoulders** [comment]
this should be closed for the following:
- 2019
- solved by added a hide message button
- user says was fixed
