### ISSUE TITLE
Remove `exec` feature from help files

### ISSUE THREAD

**Issue by swelljoe** [webmin/webmin#1095]
There's a rarely used feature to execute arbitrary code in help files. Neat in theory...it's used to show the exact path to files and stuff, based on what Webmin knows about the system, etc., but moderately dangerous in practice. It means any help file could be a vector of attack. Since we get translations of those from somewhat untrusted sources, and maybe don't read them carefully every time they're updated, it seems wise to just close that path down.

It is very rarely used. I only see a few instances of it. So, it won't be painful to remove it.

Thanks to @brontide for pointing this out on reddit. I didn't even know help files had that feature!

Since the feature seems to mostly be used for displaying Webmin config variables, subbing in those variables in a non-executable way could be a reasonable compromise with getting rid of it entirely. (Though, I don't think it would seriously negatively impact the online docs to just remove it.)

**Comment by jcameron** [comment]
Good idea, I'll remove this since it's barely used.
