### ISSUE TITLE
Buggy 1.930

### ISSUE THREAD

**Issue by klaipedaville** [webmin/webmin#1096]
Is it possible to downgrade Webmin 1.930 to its previous version? Which one was it? 1.920? The reason is that first of all 1.930 crashed when I pressed the button to upgrade it from within the previous version. Now when I have installed it manually it deleted my SSL certificates and all its settings in SSL encryption, all my back up settings, all my webmin users, my IP access control, dnssec records, etc... all in all it wiped off all the webmin configuration settings clean...  I thought at first that I had installed some wrong software as it showed graphs and charts and stuff..  Plus, now its interface looks like hello 1950s Smile ..we rolled back that far Smile or is that an oldie vintage version of webmin now? Smile

Does anyone know if there are any archives of any older versions to downgrade to? Particularly, I am interested in just one previous version, I guess it was 1.920 if I am not mistaken. Many thanks!

**Comment by rostovtsev** [comment]
You could reinstall 1.930 (it works just fine on 5 of my machines) and restore old configuration (_/etc/webmin_) from a backup.

**Comment by klaipedaville** [comment]
Well, I am glad it works on yours, but it doesn' work on mine. I have tried
that for 2 times, but 1.930 just deletes all the settings incliding back
up, it cleans up itself clean. I reinstall, reconfigure it all back
manually as /etc/webmin gets virginly clean after installing, then I
reinstsll it again on top and voila.. all the settings are deleted again,
including back ups and everything else..  Просто недержание в виде энуреза
)) Are there any older versions to download?

**Comment by art-lucas** [comment]
What about from here: [https://download.webmin.com/download/virtualmin/](https://download.webmin.com/download/virtualmin/)?

**Comment by klaipedaville** [comment]
This is virtualmin, not webmin, Lucas

**Comment by art-lucas** [comment]
You're right. Here then: [https://sourceforge.net/projects/webadmin/files/](https://sourceforge.net/projects/webadmin/files/), but watch out for the security bug in versions 1.882 through 1.921. See [this post](https://github.com/webmin/webmin/issues/1093).

**Comment by swelljoe** [comment]
Downgrading is a terrible idea (there are security issues in earlier versions, including a quite serious one).

How did you install (deb, RPM, tarball)? And, how did you upgrade?

What you're describing is not how upgrades normally work, and as far as I know nothing changed in 1.930 with regard to how they work.

**Comment by klaipedaville** [comment]
I clearly said, "I pressed the button –upgrade- from within webmin". Which exact word do you not understand, Joe?

If you had two options: 1. Use an earlier version. 2. Keep the highest security standards possible and do not use it at all because it crashes. Which one would you go for, Joe? I’d suggest you turn off your computer and do not use it at all as this is the safest method to stay safe and extremely secure. LOL

**Comment by swelljoe** [comment]
Alright, do whatever you like.

**Comment by rostovtsev** [comment]
Okay, I would do the following.

1. Run: 

```
pkill -9 webmin
pkill -9 miniserv
```


2. Remove Webmin completely. If you installed it from repository use package manager otherwise uninstall script.

3. Install version 1.930 over again.

4. Stop Webmin process after re-installation. (`/etc/webmin/stop`)

5. Update with backed-up `/etc/webmin` folder

6. Start Webmin over again (`/etc/webmin/stop`).

Old version can be installed (not recommended) by using _downgrade_ command (or alternative) in your package manager.

**Comment by klaipedaville** [comment]
Thank you for your help, Ilia. Appreciate

Well, I re-installed it pretty much the same way you say it. It looks like it's up and running. However, it still spits out weird errors. For example, it never emails on scheduled file system backups. It also always says the following, "/bin/sh: 1: /etc/webmin/package-updates/update.pl: not found"

**Comment by rostovtsev** [comment]
> It also always says the following, "/bin/sh: 1: /etc/webmin/package-updates/update.pl: not found"

To fix it, go to _System/Software Package Updates_ choose _Scheduled Upgrades_ tab and click Save button in the _Scheduled checking options_ form.

> It never emails on scheduled file system backups.

To setup and debug send mail for Webmin go to _Webmin/Webmin Configuration/Sending Email_/

**Comment by klaipedaville** [comment]
It is "ticked" / chosen in Scheduled Upgrades by default.
I have never had to setup any SMTP/POP3 and so on to email me when the Filesystem Backup is run. There has always been an option (and there is now) under Filesystem Backup –> Backup Schedule –> Email Scheduled Output or Email Message Subject to. It has simply emailed me when I set either of these two (Email Scheduled Output or Email Message Subject). Is that not the case now? Am I missing something?

**Comment by klaipedaville** [comment]
It took me a couple of seconds to set it up. The email is set from Webmin/Webmin Configuration/Sending Email all right. It's all up and running. Sends OK, well-received anywhere. But... the email notification when FileSystem Backup is run never shows up / never arrives.

**Comment by klaipedaville** [comment]
The number of bugs keeps on growing.. here is another one:

Dump ‪293761553505266‬ does not exist! at
/usr/share/webmin/fsdump/backup.pl line
8.

**Comment by rostovtsev** [comment]
Webmin saves data about backups under _/etc/webmin/fsdump_ directory (by default).

The format for files containing backup details is is _\d{16}.dump_, for example _107581566730719.dump_.

In case you see the backup in Filesystems Backup module, simply enter it and save it once more.

**Comment by klaipedaville** [comment]
It says webmin looking in /usr/share/webmin/fsdump/backup.pl
not in /etc/webmin
mess up?

**Comment by klaipedaville** [comment]
Please, disregard my last message. That is your script "backup.pl"
Well, everything exists, your dump files (aka backup) are there , the Filesystem Backup module is also there, directories to back up are there, set up and saved, directories to back up to are also there and... the error is there as well...

**Comment by rostovtsev** [comment]
When does this error appear? Can you provide the screenshot or the screencast at best?

**Comment by klaipedaville** [comment]
There are no screenshots as it's not seen visually. It appeared when I
first created this thread. This is all it shows and spits out:

Dump ‪293761553505266‬ does not exist! at
/usr/share/webmin/fsdump/backup.pl line
8

Plus, emails never arrive when Filesystem Backup is run on schedule (as
mentioned earlier).

I can live without these two of course but the previous version had it
working.

Webmin 1.930 has been running for two days only now and I hope there won't
be any other issues popping up.

**Comment by klaipedaville** [comment]
I have two cron jobs that run at the same time. The first one says, "back up succeeded" and this is the one set, and the second one which is cron that reports errors and that runs at the same time says the following, "Dump 263341553497210 does not exist! at /usr/share/webmin/fsdump/backup.pl line 8." When I check the /etc/webmin/fsdump directory the mentioned files with these long numbers do not exist indeed. However, the back up files are created and saved OK to the directory I specify. 

Now do you mean I have to create these dump files manually? Go to /etc/webmin/fsdump and create all these "long numbered" files?

**Comment by rostovtsev** [comment]
> Now do you mean I have to create these dump files manually?

No, those files are created automatically.

**Comment by klaipedaville** [comment]
No, these files are not created automatically in Webmin 1.930 as per my numerous previous messages.
