### ISSUE TITLE
insufficient  padding on command prompt first line on version 1.930

### ISSUE THREAD

**Issue by Boldairdev** [webmin/webmin#1104]
With the new console font released in last version (1.930) , the first line of the command promtps has it's g q p and semicolons cropped due to 0px vertical padding :+1: 
![Screenshot_18](https://user-images.githubusercontent.com/4577713/64243653-feea4f00-cf07-11e9-9ff8-63e94bb04f23.png)

It's possible to correct it by changing 
.-shell-port-.opened input[data-command="true"] 
padding: 4px 6px 6px 6px;

![Screenshot_17](https://user-images.githubusercontent.com/4577713/64243692-0f022e80-cf08-11e9-9571-07d64c483c7e.png)

to : 

![Screenshot_20](https://user-images.githubusercontent.com/4577713/64244130-cbf48b00-cf08-11e9-8940-348c074c8870.png)

in bundle.min.css

It's minor, but not knowing if you typed ';' or ':' is a little off putting :)

**Comment by rostovtsev** [comment]
Can you provide the exact command that is getting cropped? :smiley_cat:

**Comment by Boldairdev** [comment]
That's the reason I provided a screenshot in my original post..

`apt-get autoremove -y ; apt-get autoclean`

in that line, the g, y, ';' are cropped at the bottom, no big deal again, except that on an azerty keyboard the ';' and ':' keys are next to each other, so you never know it you typed wrong or if it's just the padding.

Also, once there are several lines, this effect disappears, it's juts the padding on a single line that is not high enough, and only since the font has changed in 1.930, the problem did not occur with the default 'monospace' font in previous versions.

**Comment by rostovtsev** [comment]
Oh, no. I understand now. 

I was trying to make it work alike for multiple platforms.

Okay. What is your OS, desktop environment, browser and theirs versions? Do you have any fronts from Roboto family installed as local on your PC?


----


You are also saying that changing top padding from **4px** to **0** fixes the issue? It makes no sense to me, to be honest. Maybe you meant **0** to **4px**? :)

**Comment by rostovtsev** [comment]
Could you provide more details, pease?

**Comment by Boldairdev** [comment]
Windows 7, Firefox 68.0.2, no Roboto  font installed locally
what fixes it is putting :
    padding-top: 4px;
    padding-right: 6px;
    padding-bottom: 5px;
    padding-left: 6px;

(basically changing the 0 values ro 4px on top and 5px on bottom).

**Comment by rostovtsev** [comment]
Do you use system font scaling or zoom in/zoom out the page in the browser, where Webmin is run?

**Comment by Boldairdev** [comment]
Neither (sorry for the dalay i was away on week-end)

**Comment by rostovtsev** [comment]
Your offered padding required only for Firefox in Windows, as Chrome doesn't have such issue, right?

**Comment by rostovtsev** [comment]
Okay, fixed now. It will be added very soon to upcoming 19.40 release.

**Comment by Boldairdev** [comment]
@iliaross 
Thanks Ilia, I forgot to acknowledged, but it is indeed fixed since 1.940

**Comment by rostovtsev** [comment]
You're welcome. My pleasure.
