### ISSUE TITLE
Trying to upgrade webmin 1.900 on Debian 6.0

### ISSUE THREAD

**Issue by 1cabron** [webmin/webmin#1109]
Following is the error message when i try and update from Webmin console:
(yes, my system is a mess, I use it to store files only), did use it as a proxy server 10 yrs ago.

Setting up samba (2:3.5.6~dfsg-3squeeze11) ...
insserv: warning: script 'S99squid.sh' missing LSB tags and overrides
insserv: There is a loop at service squid.sh if started
insserv: There is a loop between service rc.local and checkroot if started
insserv:  loop involving service checkroot at depth 3
insserv:  loop involving service hdparm at depth 2
insserv: There is a loop between service squid.sh and pcmcia if started
insserv:  loop involving service pcmcia at depth 2
insserv:  loop involving service udev at depth 1
insserv: There is a loop at service rc.local if started
insserv: There is a loop between service squid.sh and mountall if started
insserv:  loop involving service mountall at depth 5
insserv:  loop involving service checkfs at depth 4
insserv: There is a loop between service rc.local and udev if started
insserv:  loop involving service mountkernfs at depth 1
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Max recursions depth 99 reached
insserv:  loop involving service bootlogs at depth 2
insserv: There is a loop between service rc.local and ifupdown-clean if started
insserv:  loop involving service ifupdown-clean at depth 1
insserv:  loop involving service squid.sh at depth 1
insserv:  loop involving service networking at depth 7
insserv:  loop involving service mtab at depth 5
insserv:  loop involving service module-init-tools at depth 5
insserv: There is a loop between service rc.local and mountdevsubfs if started
insserv:  loop involving service mountdevsubfs at depth 1
insserv: exiting now without changing boot order!
update-rc.d: error: insserv rejected the script header
dpkg: error processing samba (--configure):
 subprocess installed post-installation script returned error exit status 1
Setting up openssh-server (1:5.5p1-6+squeeze5) ...
insserv: warning: script 'S99squid.sh' missing LSB tags and overrides
insserv: There is a loop at service squid.sh if started
insserv: There is a loop between service rc.local and checkroot if started
insserv:  loop involving service checkroot at depth 3
insserv:  loop involving service hdparm at depth 2
insserv: There is a loop between service squid.sh and pcmcia if started
insserv:  loop involving service pcmcia at depth 2
insserv:  loop involving service udev at depth 1
insserv: There is a loop at service rc.local if started
insserv: There is a loop between service squid.sh and mountall if started
insserv:  loop involving service mountall at depth 5
insserv:  loop involving service checkfs at depth 4
insserv: There is a loop between service rc.local and udev if started
insserv:  loop involving service mountkernfs at depth 1
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Max recursions depth 99 reached
insserv:  loop involving service bootlogs at depth 2
insserv: There is a loop between service rc.local and ifupdown-clean if started
insserv:  loop involving service ifupdown-clean at depth 1
insserv:  loop involving service squid.sh at depth 1
insserv:  loop involving service networking at depth 7
insserv:  loop involving service mtab at depth 5
insserv:  loop involving service module-init-tools at depth 5
insserv: There is a loop between service rc.local and mountdevsubfs if started
insserv:  loop involving service mountdevsubfs at depth 1
insserv: exiting now without changing boot order!
update-rc.d: error: insserv rejected the script header
dpkg: error processing openssh-server (--configure):
 subprocess installed post-installation script returned error exit status 1
Setting up apache2.2-common (2.2.16-6+squeeze12) ...
insserv: warning: script 'S99squid.sh' missing LSB tags and overrides
insserv: There is a loop at service squid.sh if started
insserv: There is a loop between service rc.local and checkroot if started
insserv:  loop involving service checkroot at depth 3
insserv:  loop involving service hdparm at depth 2
insserv: There is a loop between service squid.sh and pcmcia if started
insserv:  loop involving service pcmcia at depth 2
insserv:  loop involving service udev at depth 1
insserv: There is a loop at service rc.local if started
insserv: There is a loop between service squid.sh and mountall if started
insserv:  loop involving service mountall at depth 5
insserv:  loop involving service checkfs at depth 4
insserv: There is a loop between service rc.local and udev if started
insserv:  loop involving service mountkernfs at depth 1
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Starting squid.sh depends on rc.local and therefore on system facility `$all' which can not be true!
insserv: Max recursions depth 99 reached
insserv:  loop involving service bootlogs at depth 2
insserv: There is a loop between service rc.local and ifupdown-clean if started
insserv:  loop involving service ifupdown-clean at depth 1
insserv:  loop involving service squid.sh at depth 1
insserv:  loop involving service networking at depth 7
insserv:  loop involving service mtab at depth 5
insserv:  loop involving service module-init-tools at depth 5
insserv: There is a loop between service rc.local and mountdevsubfs if started
insserv:  loop involving service mountdevsubfs at depth 1
insserv: exiting now without changing boot order!
update-rc.d: error: insserv rejected the script header
dpkg: error processing apache2.2-common (--configure):
 subprocess installed post-installation script returned error exit status 1
dpkg: dependency problems prevent configuration of ssh:
 ssh depends on openssh-server; however:
  Package openssh-server is not configured yet.
dpkg: error processing ssh (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of apache2:
 apache2 depends on apache2.2-common (= 2.2.16-6+squeeze12); however:
  Package apache2.2-common is not configured yet.
dpkg: error processing apache2 (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of apache2-mpm-worker:
 apache2-mpm-worker depends on apache2.2-common (= 2.2.16-6+squeeze12); however:
  Package apache2.2-common is not configured yet.
dpkg: error processing apache2-mpm-worker (--configure):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 samba
 openssh-server
 apache2.2-common
 ssh
 apache2
 apache2-mpm-worker
Reading package lists...
Building dependency tree...
Reading state information...
The following extra packages will be installed:
  unzip
Suggested packages:
  zip
The following NEW packages will be installed:
  unzip
The following packages will be upgraded:
  webmin
1 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
6 not fully installed or removed.
Need to get 17.1 MB of archives.
After this operation, 2343 kB of additional disk space will be used.
WARNING: The following packages cannot be authenticated!
  unzip webmin
E: There are problems and -y was used without --force-yes

**Comment by jcameron** [comment]
What happens if you SSH in as `root` and run `apt-get install webmin`

**Comment by 1cabron** [comment]
Tried it and here is the result--

root@debianlaptop:~# root@debianlaptop:~# apt-get install  webmin
-bash: root@debianlaptop:~#: command not found
root@debianlaptop:~# Reading package lists... Done
-bash: Reading: command not found
root@debianlaptop:~# Building dependency tree
-bash: Building: command not found
root@debianlaptop:~# Reading state information... Done
-bash: Reading: command not found
root@debianlaptop:~# The following extra packages will be installed:
-bash: The: command not found
root@debianlaptop:~#   unzip
-bash: unzip: command not found
root@debianlaptop:~# Suggested packages:
-bash: Suggested: command not found
root@debianlaptop:~#   zip
-bash: zip: command not found
root@debianlaptop:~# The following NEW packages will be installed:
-bash: The: command not found
root@debianlaptop:~#   unzip webmin
-bash: unzip: command not found
root@debianlaptop:~# 0 upgraded, 2 newly installed, 0 to remove and 0 not
upgraded.
-bash: 0: command not found
root@debianlaptop:~# 6 not fully installed or removed.
-bash: 6: command not found
root@debianlaptop:~# Need to get 179 kB/17.1 MB of archives.
-bash: Need: command not found
root@debianlaptop:~# After this operation, 175 MB of additional disk space
will be used.
-bash: After: command not found
root@debianlaptop:~# Do you want to continue [Y/n]? y
-bash: Do: command not found
root@debianlaptop:~# WARNING: The following packages cannot be
authenticated!
-bash: WARNING:: command not found
root@debianlaptop:~#   unzip webmin
-bash: unzip: command not found
root@debianlaptop:~# Install these packages without verification [y/N]? y
-bash: Install: command not found
root@debianlaptop:~# Err http://ftp.ca.debian.org/debian/ squeeze/main
unzip i386 6.0-4
-bash: Err: command not found
root@debianlaptop:~#   404  Not Found
-bash: 404: command not found
root@debianlaptop:~# Failed to fetch
http://ftp.ca.debian.org/debian/pool/main/u/unzip/unzip_6.0-4_i386.deb  404
 Not Found
-bash: Failed: command not found
root@debianlaptop:~# E: Unable to fetch some archives, maybe run apt-get
update or try with --fix-missing?
-bash: E:: command not found
root@debianlaptop:~# root@debianlaptop:~#
-bash: root@debianlaptop:~#: command not found
root@debianlaptop:~#



Thank you for any assistance you can provide.

**Comment by jcameron** [comment]
It looks like you pasted in a whole bunch of other text into the shell there?

**Comment by chris001** [comment]
It's as if the stderr and stdout are redirected to the stdin... ?!

**Comment by 1cabron** [comment]
Hi Chris,

Sorry, I don't understand your comment.

I think one issue is the repository address is incorrect/non functional. The "404" error might be a HTTP error.

I'm going to try to download webmin on the machine, and run the deb command? Your thoughts?

**Comment by chris001** [comment]
@1cabron 
I'd start by upgrading your debian operating system to 7, then 8.  Debian 6 is 8-9 years old and I believe it's not supported any more:
```
The Debian Long Term Support (LTS) Team hereby announces that Debian 6.0 ( squeeze ) support will reach its end-of-life on February 29, 2016, five years after its initial release on February 6, 2011. There will be no further security support for Debian 6.0.
```
PS are you running a physical server, full virtual kvm server, or vps/container?

**Comment by 1cabron** [comment]
great suggestion..l will put a pot of coffee on and start the process. I will close the file.  I appreciate all your assistance, and time.  Thank you.
