### ISSUE TITLE
CSS not working for login screen (folder 'unauthenticated')

### ISSUE THREAD

**Issue by msberends** [webmin/webmin#1116]
I'm having this login screen on 1.930 on Debian 10:

<img width="557" alt="Screenshot 2019-09-25 at 13 09 27" src="https://user-images.githubusercontent.com/31037261/65595813-d4833300-df95-11e9-959c-abe879102902.png">

It seems like my 'authenticated' folder is missing some CSS files:

<img width="491" alt="image" src="https://user-images.githubusercontent.com/31037261/65596076-668b3b80-df96-11e9-8676-93578a006a75.png">
<img width="315" alt="image" src="https://user-images.githubusercontent.com/31037261/65596089-6ee37680-df96-11e9-8262-ab864118a218.png">

Which seems true:

<img width="452" alt="Screenshot 2019-09-25 at 13 12 02" src="https://user-images.githubusercontent.com/31037261/65595917-18763800-df96-11e9-9593-e0080acf6c16.png">

But now I see this repository is also lacking them. What is happening? Am I doing something wrong here? Just downloaded the official deb and installed with `dpkg -I thedeb`.

**Comment by rostovtsev** [comment]
Hi,

Did you try to kill and then start Webmin over again? 

In case it's new install you could also run a command to reinstall it:

```
apt-get install --reinstall webmin
```

You should better [add a Webmin repo](https://www.digitalocean.com/community/tutorials/how-to-install-webmin-on-debian-10) to your system, to let package manager to handle updates for you.

Make sure that files `/etc/webmin/config` and `/etc/webmin/miniserv.conf` actually exist after installation.

---

The error that your are seeing is complaining about the other folder, it's not `/usr/share/webmin/unathenticated` but the folder inside of default theme (authentic-theme):

```
/usr/share/webmin/authentic-theme/unathenticated
```

---

Moreover, check for error log at _/var/webmin_ directory.

If non of the above helps, try restarting the server.

**Comment by rostovtsev** [comment]
Besides, it's expected default port 10000 is opened on the Firewall:

```
sudo ufw allow 10000
```

**Comment by msberends** [comment]
Thanks for the support!

Before I filed this issue, I did `apt-get install --reinstall webmin` (months ago) and only used `dpkg` to try to solve it. Neither worked. I have had this problem since the beginning. 

I use a reverse proxy, so no traffic on port 10000 from outside. Webmin itself works great, it’s only this login screen. The rest is all fine, include the loading of theme CSS files after login. 

Config files are there, everything works fine otherwise. Restarting the service or the server does not help. 

Any other ideas? I’ll check the logs.

**Comment by rostovtsev** [comment]
Can you go to _Webmin Configuration/Themes_ and change the theme to _Gray Theme_ and then back to _Authentic Theme_ once again. Does it fix your login screen then? If it doesn't, if you switch to _Gray Theme_ do you still see this issue on login screen?

In case you still see issues by trying the above, post your `/etc/webmin/config` and `/etc/webmin/miniserv.conf`, along with proxy setup.

**Comment by msberends** [comment]
> Can you go to Webmin Configuration/Themes and change the theme to Gray Theme and then back to Authentic Theme once again. Does it fix your login screen then?

It does!! Thank you! Although I’m not sure if there should be any possible fix from your side to prevent this bug for others, I’m closing this issue. Feel free to reopen it as you like. Thanks again!

**Comment by rostovtsev** [comment]
@msberends You are welcome! Do you have backups of `/etc/webmin/config` and `/etc/webmin/miniserv.conf` files left?
