### ISSUE TITLE
BUG: Validate Virtual Servers error, yet valid AAAA MX record exists.

### ISSUE THREAD

**Issue by chris001** [webmin/webmin#1118]
I have an IPv6-only domain with only IPV6 (AAAA) IP address for MX, as follows:

* domain is named `ipv6.mydomain.com`
* `IN MX` record says `mail.ip6.mydomain.com`
* The IP address of `mail` in this zone is the IPv6 address `IN AAAA  2001:aaaa:bbbb:cccc:dddd:eeee:ffff:0001`

Shouldn't it be valid to have a domain with a mail server that only listens on IPv6?

Yet, Virtualmin shows this red validation error:
`BIND DNS domain : This domain has email enabled, but none of the MX records point to it. Either the MX records should be corrected, or the email feature disabled if mail is hosted externally.`

**Comment by chris001** [comment]
Update:
This bug seems to be correlated with having a mail server on a "virtual server" (in the Virtualmin sense of the term) _**which is in fact a subdomain (`sub.mydomain.com`)**_, even when this virtual server's mail server is has an IPv4 address, and doesn't have an IPv6 address.
Details:
Virtualmin **top level** virtual server name: `sub.mydomain.com`
Mail server record in this DNS zone: `sub.mydomain.com IN MX mail.sub.mydomain.com.`
Address record for mail server: `mail  IN A 198.bbb.ccc.ddd`
Error thrown by "Validate Virtual Servers" command:
`Warning!  Warning - errors were found in this domain's DNS records : This domain has email enabled, but none of the MX records point to it. Either the MX records should be corrected, or the email feature disabled if mail is hosted externally.`

**Comment by jcameron** [comment]
This is bug - we didn't consider the case where the MX only points to an IPv6 address. It will be fixed in the next release.
