### ISSUE TITLE
system-status::list_system_info failed : Hour 'XX' out of range 0..23 at /usr/libexec/webmin/proc/linux-lib.pl line 59.

### ISSUE THREAD

**Issue by vsc55** [webmin/webmin#1119]
Hi,

At certain times of the day the following error is generated in the "Dashboard" section.
`system-status::list_system_info failed : Hour 'XX' out of range 0..23 at /usr/libexec/webmin/proc/linux-lib.pl line 59. `

Debug variables on the line that generates the error:
```
$I: 186
$LINE: username username Domain Users Domain Users 23195 23143 23143 0.0 20712 0 56:41 00:00:00 14:02 ? sshd: username@pts/0
$now[1]: 59 
$now[2]: 14
$now[3]: 28
$now[4]: 8
$now[5]: 119
$1: 56
$2: 41
$3:
```
LINE >>>> user = username, group = Domain Users

PS Version: ps from procps-ng 3.3.15
System: Gentoo Linux

Update:
This happens between 13:00 and 15:00.

**Comment by jcameron** [comment]
Thanks, we'll fix this in the next Webmin release.
