### ISSUE TITLE
Webmin can not find or can not configure apache modules

### ISSUE THREAD

**Issue by DevDorrejo** [webmin/webmin#1120]
Hello, i have webmin on opensuse leap 15.1 and tumbleweed, both are using the last version of webmin, and have apache web server working, now the issue is the next:

when i create a vhost with the need of a mod, like proxy, rewrite, ssl, webmin can't find or not let the user configure the modules, so when i try to run the server it said:

/ usr / sbin / httpd -d / etc / apache2 -f /etc/apache2/httpd.conf:
AH00526: Syntax error on line 18 of /etc/apache2/vhosts.d/_webmin.example.org.conf:
Invalid command 'ProxyPass', perhaps misspelled or defined by a module not included in the server configuration.

now if i make a search to see if the module are loaded:

/ etc / apache2 # grep -R "proxy"
sysconfig.d / loadmodule.conf: LoadModule proxy_module /usr/lib64/apache2-prefork/mod_proxy.so
sysconfig.d / loadmodule.conf: LoadModule proxy_http_module /usr/lib64/apache2-prefork/mod_proxy_http.so

appear to be loaded.

**Comment by DevDorrejo** [comment]
Now after did this:
1- Go to the configuration of apache webserver module.
2- Select No on the line with: "Always detect Apache modules automatically?"
3- Save.
4- Apache WebServer: Global Configuration Tab.
5- go to the option "Re-Configure Known Modules"
6- Select modules to be load and click Configure.

The modules selecteds, example mod_proxy, and after click configure, webmin not maintain the changes.

**Comment by DevDorrejo** [comment]
help?

**Comment by jcameron** [comment]
Your changes won't actually enabled any new modules, just change how Webmin detects them.

You should check the SuSE documentation for the correct way to enable Apache modules, since it is OS-specific.

**Comment by DevDorrejo** [comment]
i have found that if i install webmin on leap 15.1 get the configuration of the module correctly, but now i am getting a new error:

![image](https://user-images.githubusercontent.com/7697566/66359480-4ddf3600-e945-11e9-8659-073a85eb0bd1.png)


> Your changes won't actually enabled any new modules, just change how Webmin detects them.
> 
> You should check the SuSE documentation for the correct way to enable Apache modules, since it is OS-specific.

**Comment by DevDorrejo** [comment]
hello

**Comment by chris001** [comment]
@DevDorrejo 
Are you sure?  Those log messages are 12 days old, they were logged on Oct 7.

**Comment by ashcoft** [comment]
Either with me, error while using cli terminal.

**Comment by iliajie** [comment]
The latest Webmin 2.010 will have proper support for all new (clean) on openSUSE Leap and Tumbleweed!
