### ISSUE TITLE
Dovecot: Support TLS SNI (Server Name Identification)

### ISSUE THREAD

**Issue by iam-TJ** [webmin/webmin#1122]
Hit this recently on a multi-domain host where the X509 certificate offered by Dovecot is the 'first' domain's but Dovecot is handling logins for several domains.

Specifically, Microsoft Outlook reports a mismatched certificate common-name on each connection and it isn't possible to tell it to allow that permanently.

As Dovecot does support multi-domain SNI configuration, and webmin/virtualmin specifically manage multi-domain TLS X09 services, can we extend webmin's Dovecot module to at a minimum not over-write administrator-added SNI TLS configuration and preferably allow it to be reflected in the web interface and automatically created for all mail domains?

**Comment by iam-TJ** [comment]
Doh! Not sure how I missed it, but it is already supported. I was expecting the configuration to be added in /etc/dovecot/conf.d/ but just discovered SNI entries ("local_name XXXX") for all domains are written into the master config at /etc/dovecot/dovecot.conf.

Seems a bit brittle but at least it is there so I'll have to re-investigate the Microsoft Outlook angle.

**Comment by chris001** [comment]
You're right the SNI entries should probably be added in `/etc/dovecot/conf.d/` it's probably more resilient to Dovecot upgrades.
