### ISSUE TITLE
Privacy error

### ISSUE THREAD

**Issue by acollien** [webmin/webmin#1127]
Just randomly started happing a few days ago. No change to my network or way I assess (locally) webmin. Tried all browsers, and all the basic stuff (clearing cashes, restarting webmin service, restarting server, updating/upgrading packages etc.)

"Your connection is not private
Attackers might be trying to steal your information from 192.168.1.148 (for example, passwords, messages or credit cards). Learn more
NET::ERR_CERT_REVOKED"

"192.168.1.148 normally uses encryption to protect your information. When Google Chrome tried to connect to 192.168.1.148 this time, the website sent back unusual and incorrect credentials. This may happen when an attacker is trying to pretend to be 192.168.1.148, or a Wi-Fi sign-in screen has interrupted the connection. Your information is still secure because Google Chrome stopped the connection before any data was exchanged.

You cannot visit 192.168.1.148 right now because its certificate has been revoked. Network errors and attacks are usually temporary, so this page will probably work later."

<img width="1144" alt="Screen Shot 2019-10-13 at 23 16 11" src="https://user-images.githubusercontent.com/8148297/66715473-78326700-ee0f-11e9-972e-7ca5778cd550.png">

**Comment by jcameron** [comment]
This may be because it's impossible to have a valid SSL cert for an IP address in the first place.

**Comment by acollien** [comment]
> This may be because it's impossible to have a valid SSL cert for an IP address in the first place.

I'd been using it for a couple weeks with no issues though. Variaous package updates, reboots, etc. No issues. Now suddenly it won't let me in?

**Comment by acollien** [comment]
Unsure how/why, but it's righted itself...

**Comment by acollien** [comment]
And we're back. Seems that it is only affecting login via via and only chrome-based browsers.
(I am able to login when on LAN OK through chrome browsers, but not on wi-fi.) Doen't appear to be a wi-fi issue either as I can login in on wi-fi using Safari browsers (after accepting security warning.)
Have tried resetting chrome settings and removing all data/cookies etc. Strange, no?

**Comment by rostovtsev** [comment]
Yes, strange. 

What is your Chrome version? This could be caused by some installed Chrome extensions? First try disabling all of them to see how it affects it.

I run debugging Webmin 7h+ a day in Chrome and never had such issue.

There are [more options](https://support.turbotenant.com/hc/en-us/articles/115000855908-I-got-a-message-that-says-Your-connection-is-not-private-What-do-I-do-) to try.

**Comment by acollien** [comment]
> What is your Chrome version? This could be caused by some installed Chrome extensions? First try disabling all of them to see how it affects it.
I've got up-to-date Chrome (Version 77.0.3865.120 (Official Build) (64-bit)) and have tried with Canary and Brave.
> There are [more options](https://support.turbotenant.com/hc/en-us/articles/115000855908-I-got-a-message-that-says-Your-connection-is-not-private-What-do-I-do-) to try.
Cheers - tried a few site searches and all suggest similar fixes - none have worked yet unfortunately.

**Comment by acollien** [comment]
So far, only thing that works is disabling SSL in webmin.

**Comment by rostovtsev** [comment]
It's not safe. You can try setting up proxy and put Webmin behind proxy, connecting to proxy using SSL and within localhost keep it plain.

**Comment by acollien** [comment]
> It's not safe. You can try setting up proxy and put Webmin behind proxy, connecting to proxy using SSL and within localhost keep it plain.

This sounds a bit beyond me... unless you can link/post a step-guide?

**Comment by swelljoe** [comment]
If you can't give the Webmin system a proper hostname with DNS and a Let's Encrypt certificate, just give it a hostname in your local (your client machine) hosts file, and make a new self-signed certificate for that hostname.

**Comment by chris001** [comment]
#420 Running Webmin under Nginx

**Comment by acollien** [comment]
> If you can't give the Webmin system a proper hostname with DNS and a Let's Encrypt certificate, just give it a hostname in your local (your client machine) hosts file, and make a new self-signed certificate for that hostname.

Can you illustrate this please?

NB: Server is a stand-alone headless machine.

**Comment by swelljoe** [comment]
https://www.howtogeek.com/howto/27350/beginner-geek-how-to-edit-your-hosts-file/

https://doxfer.webmin.com/Webmin/Webmin_Configuration#SSL_Encryption

**Comment by swelljoe** [comment]
Apparently you'll also need this for Chrome (I'm pretty sure Firefox will let you accept a self-signed certificate with just a couple of clicks and warnings): https://stackoverflow.com/questions/7580508/getting-chrome-to-accept-self-signed-localhost-certificate
