### ISSUE TITLE
Zone transfer test fails for unnamed masters list.

### ISSUE THREAD

**Issue by lniles77** [webmin/webmin#1129]
My slave zone config has a simple 
`masters { ip_addr; };`
clause (generated by webmin).  This unnamed list of IPs for a masters clause is legal inside of a slave zone definition.  
The zone transfer test fails with:
`Testing transfer of slave zone from ..
.. from : Failed : /usr/bin/dig: couldn't get address for '': not found`
This appears to have been introduced by commit cede115 to fix #1016 -- the zone transfer test succeeds when I roll back that change.

**Comment by jcameron** [comment]
Thanks, I'll fix this back.

**Comment by t-offline** [comment]
Please have a look to my patch:

https://github.com/webmin/webmin/pull/1072

TIA
