### ISSUE TITLE
BIND module reading TXT record chokes with uninitialized value error

### ISSUE THREAD

**Issue by swelljoe** [webmin/webmin#1131]
Adding a TXT record like this: `discourse.virtualmin.com.       IN      TXT     "v=spf1 include:mailgun.org ~all"`

Succeeds, but results in this error when trying to view the TXT records for a domain (and the domain page doesn't recognize the new record):

```
Use of uninitialized value $bind8::in{"view"} in string eq at /usr/libexec/webmin/bind8/edit_master.cgi line 11.
Use of uninitialized value in concatenation (.) or string at ./bind8-lib.pl line 3153.
Use of uninitialized value $view in string eq at ./bind8-lib.pl line 3089.
Use of uninitialized value $view in string ne at ./bind8-lib.pl line 3089.
Use of uninitialized value in concatenation (.) or string at ./bind8-lib.pl line 3153.
Use of uninitialized value $rec{"ttl"} in pattern match (m//) at ./bind8-lib.pl line 1050.
Use of uninitialized value $v[0] in join or string at ./bind8-lib.pl line 1099.
Use of uninitialized value in concatenation (.) or string at /usr/libexec/webmin/bind8/edit_recs.cgi line 175.
Use of uninitialized value in pattern match (m//) at /usr/libexec/webmin/bind8/edit_recs.cgi line 183.
```

There are errors when viewing the domain records page, as well, but they are similar (uninitialized value). This may be related to the strict/warnings conversion...like years ago...surprised nobody has reported it, though. I've tested on current devel version 1.932 to confirm problem is the same.

Jamie, if this isn't an easy fix for you, I'll dig into it, but can't look at it today as I'm trying to get discourse running and test forum migration ASAP.

**Comment by jcameron** [comment]
Those warnings may be unrelated to the record not appearing. Shouldn't the type be SPF and not TXT?

**Comment by swelljoe** [comment]
Is there an SPF record type? I thought they were just TXT records with a special format.

**Comment by chris001** [comment]
At first SPF started as being saved in resource record type TXT, then IETF approved an SPF record type.  I'd assume, both types **_should_** work, for backward compatibility.

**Comment by jcameron** [comment]
Yes - in the olden days a TXT record was used instead, which was the style at the time. Modern BIND releases support a proper SPF type with the same format.

**Comment by swelljoe** [comment]
Hahah, lol, it *does* show up in the SPF page. That seems...quirky. But, I guess it's fine. Easier for folks who don't know what's going on under the hood. Confusing for me. ;-)
