### ISSUE TITLE
redirecting to webmin login page without setting up the ssl

### ISSUE THREAD

**Issue by smnajibi** [webmin/webmin#1134]
I have setup a proxy to access webmin panel via a subdomain with Apache and also copy a ssl to webmin to use port 10000 on https. Everything is working great for it. But port 443 for all of the other subdomains and main domain redirect to webmin login page while I didn't setup any ssl for them. These are my webmin and virtualmin versions:
Webmin version	1.930 	Usermin version	1.780
Virtualmin version	6.07	Authentic theme version	19.39-2

**Comment by rostovtsev** [comment]
It appears that you have Apache mis-configuration.

Have a look at [this thread](https://sourceforge.net/p/webadmin/discussion/600155/thread/6eb89f60/?limit=25) at first, to setup proxy for Webmin correctly.

If I guess correctly, it seems that you need to setup separate root directories for your other domains running in SSL individually.
