### ISSUE TITLE
No option to update webmin / virtualmin

### ISSUE THREAD

**Issue by nabtron** [webmin/webmin#1137]
I am running virtualmin / webmin on ubuntu 18.04

On the dashboard the versions are:
- webmin: 1.900
- virtualmin: 6.05

However there is no option to update webmin or virtualmin to the latest versions. 
Everything else is updated and working fine. 

Kindly direct me in the right direction.

**Comment by rostovtsev** [comment]
How did you install Virtualmin? Did you install it using install script or manually?

What server OS are you running?

**Comment by nabtron** [comment]
Thanks for responding

os: ubuntu 18.04

I installed it using:

wget http://software.virtualmin.com/gpl/scripts/install.sh
sudo /bin/sh install.sh

**Comment by rostovtsev** [comment]
Okay, check if repository enabled. In console try:

```
apt-get update
apt-get upgrade
```

**Comment by nabtron** [comment]
It returns this:

```
[root@instance-1 ~]# apt-get update
Get:1 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Hit:2 http://archive.canonical.com/ubuntu bionic InRelease
Hit:3 http://gce.clouds.archive.ubuntu.com/ubuntu bionic InRelease
Get:4 http://gce.clouds.archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:5 http://gce.clouds.archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Fetched 252 kB in 1s (189 kB/s)
Reading package lists...
[root@instance-1 ~]# apt-get upgrade
Reading package lists...
Building dependency tree...
Reading state information...
Calculating upgrade...
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

**Comment by rostovtsev** [comment]
There are no Virtualmin repos present on your output - make sure that they are enabled/present. Check your `/etc/apt/sources.list.d/`.

**Comment by nabtron** [comment]
It contains only 1 file
```
[root@instance-1 sources.list.d]# ls
partner.list
```
content of partner.list is:
```
# Enabled for Google Cloud SDK and gce-utils
deb http://archive.canonical.com/ubuntu bionic partner
```
Other files in the same folder /etc/apt/ are:
```
[root@instance-1 apt]# ls
apt.conf.d
auth.conf.d
preferences.d
sources.list
sources.list.d
sources.liste
trusted.gpg
trusted.gpg.d
trusted.gpg~
```

**Comment by rostovtsev** [comment]
`/etc/apt/sources.list` should contain all the repos for your Virtualmin.

It's probably got disabled? Uncomment the last two lines that contain _virtualmin.com_ URL in the list.

**Comment by rostovtsev** [comment]
By the way, you can use the same install script with the `--setup` param to fix your repos.

```
Setup software repositories and exit (no installation or configuration)\
```

**Comment by nabtron** [comment]
Perfect. Thank you, it worked!
