### ISSUE TITLE
Java File Manager no icons when connected via IP

### ISSUE THREAD

**Issue by campones** [webmin/webmin#1140]
hello

since 1900 I have an issue with the icons. basically they don't appear anymore

today just for fun ,  I setup ubuntu on a home server and set it up for both local (192.168.. ) and remote access with hostname then

when I have webmin open with the ip:10000 , no icons , when I have it opened with the hostname, it works normally!!!  

On all my server I use ip address:10000 and I lost icons

that could be the reason?

**Comment by rostovtsev** [comment]
Which icons exactly? In modules (like Webmin Configuration) or a theme svg (navigation menu) icons?

Maybe you could provide a screenshot? Any errors on the console?

In case it's a module, have a look here:
https://github.com/authentic-theme/authentic-theme/issues/975

**Comment by campones** [comment]
https://i.gyazo.com/35cea2f725460b6d12021f14bff92bfd.png

**Comment by campones** [comment]
using gray frame

**Comment by rostovtsev** [comment]
I truly don't understand why you never mentioned Java File Manager in the original question. This post would be useless for future reference.

Okay, there might be multiple reasons for it. At first try opening browser' console and see for errors?

For your information, I have it displayed.

![image](https://user-images.githubusercontent.com/4426533/69012394-48cec700-0986-11ea-99e7-5e93288a7080.png)

**Comment by rostovtsev** [comment]
There is absolutely no single reason to use Java File Manager in the end of 2019. What are your reasons, just curious?

**Comment by campones** [comment]
![ef3d703d93733535b1cad17a29f80aa9](https://user-images.githubusercontent.com/7072524/69012645-b4159a80-0980-11ea-9685-3912c1adfa9c.png)

well you see, I prefer to scroll down a long list than having a numbered menu . that takes a bunch of time to find what you are looking for

**Comment by rostovtsev** [comment]
Have a look at how you can do it at Authentic Theme. Can you do it faster??

![html5-file-manager-filtering_and_search](https://user-images.githubusercontent.com/4426533/69012806-f512ac80-098a-11ea-836d-949d90233279.gif)


Besides, you can go to File Manager configuration and set/define maximum number of entries to fall for server pagination. It's not recommended because it's slower but it's possible. Search works impressively fast.

![html5-file-manager-filtering_and_search-no-limit](https://user-images.githubusercontent.com/4426533/69012949-fabcc200-098b-11ea-87d8-e30fc80441a9.gif)

**Comment by campones** [comment]
it's true that, after switching to authentic theme, and setting up a bit the display, it looks great

great work as been done I recognize , maybe I ll get use to it one day

**Comment by campones** [comment]
yes thanks , I saw these options now

**Comment by campones** [comment]
I also see know it's possible to copy paste the same filename on the same folder , it rename automatically which was really missing for me before.

any idea how I can get a light theme when I edit a file, right now it's completely black with white font

**Comment by rostovtsev** [comment]
Yes.

![file-manager-dark-light-themes](https://user-images.githubusercontent.com/4426533/69013081-43c14600-098d-11ea-8751-b473a93a83d0.gif)

**Comment by campones** [comment]
awesome!

**Comment by rostovtsev** [comment]
Besides, latest releases of Authentic Theme supports File Manager's listing of millions+ of files, doing it super fast, while I just tried Java File Manager on only ~33.000 files and it was very-very slow.

**Comment by rostovtsev** [comment]
After 19.42 release (in few days), I will start enrolling ACL support to File Manager for 19.43 release. Possibly, I will also add file preview (any file) as well, and do other improvements for File Manager.

Thank you for your kind words!

**Comment by campones** [comment]
keep up the great work!

**Comment by rostovtsev** [comment]
Will do, will do.

**Comment by campones** [comment]
there should be a way to be able to copy the path of the current directory 

also one thing that I feel is missing for me is the use of shortcuts undo redo after saving.  this is a big minus for me, as when you edit a file in the java file manager I can save, then undo, resave on a separate popup tab. I think he when you open a file, it could open a separate windows that would appear on the taskbar that would be more user friendly, also you could have a lot more file being edited,  this is the big problem for me

**Comment by campones** [comment]
ok sorry, right click on the path and it became possible to copy it

**Comment by rostovtsev** [comment]
> ...  also you could have a lot more file being edited, this is the big problem for me.

I am trying to understand what you're trying to say. If I understand you right, you need an ability to undo made changes? You can already do it the standard way you do it on desktop, using _Ctr+Z_ (undo) or _Ctrl+Shift+Z_ or _Ctrl+Y_ (redo). Then you can use _Ctrl+Shift+S_ to save file as. There are two helpers with hotkeys.

By the way, the standard _Ctrl+C_ (copy to clipboard), _Ctrl+X_ (cut to clipboard), and _Ctrl+V_ (paste from clipboard) for files and directories, and text in editor work the same way as on desktop. You can even pass currently opened directory to inbuilt command shell by clicking _Alt+Shift+K_.

Have a look at the video-screencast to display how it can be done, and learn more about shortcuts, it's very useful. 


![file-manager-edit_undo_redo_and_more](https://user-images.githubusercontent.com/4426533/69071821-a83ade80-0a3b-11ea-99ca-adfae3ff6170.gif)

**Comment by campones** [comment]
interesting, actually since you show me it' s possible to open several windows,  I moved up one, but now I cannot close it . the upper part stays under the chrome fav bar

**Comment by rostovtsev** [comment]
It's possible to drag it back by using editor window's footer. Like this:

![file-manager-moving-window](https://user-images.githubusercontent.com/4426533/69073484-99a1f680-0a3e-11ea-8055-d5c3c966ab25.gif)

**Comment by campones** [comment]
great, I didn't know. Lot's of learning needed.  

And the ctrl Z Y works fine even after saving

the editing layout is obviously much better than the java manager. (but the navigation inside directories will always be faster by design in the java manager, I feel)  

So my suggestion would be if possible, an option to popup file being edited as a separate tab that would appears in the taskbar.

you know, it's kinda the same story with skype, they removed these tabs (one tab per conversation in the taskbar) and everyone was complaining.  They actually put back that option again few days ago

**Comment by rostovtsev** [comment]
Could you maybe elaborate the idea about popup and separate tab for file being edited? What do you mean by task bar?

Yes, it's a bit slower, at least so far, as long as we are parsing HTML, instead of using JSON.

**Comment by campones** [comment]
![ccec446c007215c86bf8c82224c0815a](https://user-images.githubusercontent.com/7072524/69075552-43cb4f80-0a3a-11ea-912b-0a7e6d05e845.png)

**Comment by rostovtsev** [comment]
🙂 I don't think it's possible!

**Comment by campones** [comment]
I thought so

**Comment by rostovtsev** [comment]
I don't think you need this really, as you can collapse file editor window, and have them all at the bottom of the screen.

**Comment by campones** [comment]
it's not the same as you need to look at that particular tab to have access to them.

**Comment by campones** [comment]
https://gyazo.com/57f5dd252621ffaeef163cf71b8c83d3

it's not letting me close it, and follow me everywhere!!

**Comment by rostovtsev** [comment]
That is odd. 😅 

How did you do it? I expect that you let go of the left click. You can let go dragging, then use left border to resize it (the same way you made it super-large but backwards). Right?

You can also press quickly double esc on the editor, to close its window.

Other than that, what is your browser and client OS?

**Comment by campones** [comment]
yes ofc I was not having my finger on the left click. but this is exactly as if I had it.. couldn't close, I just f5'd it

**Comment by campones** [comment]
good tip for the esc key

**Comment by rostovtsev** [comment]
The only way I could reproduce it is to do right click while dragging (holding left).

**Comment by rostovtsev** [comment]
Okay, that was a bug in jsPanel. Fixed upstream (please update and reload the cache) and created [pull request](https://github.com/Flyer53/jsPanel3/pull/72/commits/a680cfa27c9856cad8854d2d4da1be503362a317) to jsPanel repo to fix it.

Thanks for reporting!
