### ISSUE TITLE
midnight cron jobs not working

### ISSUE THREAD

**Issue by sewox** [webmin/webmin#1152]
Hi Everyone,

midnight cron jobs not working, I remove and recreate jobs but not working 

Webmin version 1.881
On  Debian Linux 9

**Comment by jcameron** [comment]
Do you mean they don't run, or you get an error message when you try to create such a job?

**Comment by sewox** [comment]
> Do you mean they don't run, or you get an error message when you try to create such a job?

don't run but, its work manually running

**Comment by jcameron** [comment]
Does anything get logged to `/var/log/cron.log` when it runs?

**Comment by sewox** [comment]
In the log file, I see that I have not worked, the first task should be skipped, then the task should be run.
first task but this task not work
![Screen Shot 2019-12-06 at 17 01 47](https://user-images.githubusercontent.com/4640711/70328450-207e0e00-184a-11ea-8a82-2942502a25ac.png)

second task 
![Screen Shot 2019-12-06 at 17 03 16](https://user-images.githubusercontent.com/4640711/70328644-97b3a200-184a-11ea-972a-5c59f66b5ec7.png)

The task in the first screenshot does not work in the images you see in the appendix, but the task in the second screenshot is running. and it doesn't do it continuously, it doesn't return an error message.

[cron.log](https://github.com/webmin/webmin/files/3932505/cron.log)

**Comment by jcameron** [comment]
But in the log, I do see a line indicating that the first task ran :

```Dec  6 00:00:01 Useroam CRON[15079]: (root) CMD (bash /zamanbaz/zamanbaz.logrotate)
```

**Comment by gnadelwartz** [comment]
> > Do you mean they don't run, or you get an error message when you try to create such a job?
> 
> don't run but, its work manually running

a working script in user/root env does not mean it's running under cron, because it's a different env.

try to redirect all output to a file and possibly add set +x to the script to see if it runs, where it fails or simply process nothing.
