### ISSUE TITLE
How to update

### ISSUE THREAD

**Issue by maicol07** [webmin/webmin#1159]
Hi, I've seen that you have released Webmin 1.940 but when I go to Webmin configuration --> Update Webmin --> From webmin.com it says there are no versions available. What can I do?
Thanks

**Comment by rostovtsev** [comment]
Please wait for another day or two.

**Comment by maicol07** [comment]
Also, I can't update neither to 1.933, 1.932 or 1.931! My webmin is stuck at 1.930

**Comment by chris001** [comment]
If you want to take a small risk, you can run this command in terminal, to update webmin directly from github code to 1.940, it takes a few minutes:
`/usr/share/webmin/update-from-repo.sh`  (on debian/ubuntu type of Linux)

**Comment by gnadelwartz** [comment]
there us no official release until now, only the dev repo is marked as 1.940.

before an official release will happen webmin must tested on supported platforms and update packages must be ceated. so pls wait a few days.

besides 1.93x: they was never released officially, with the exception of 1.931 together with virtualmin

https://github.com/webmin/webmin/releases

**Comment by maicol07** [comment]
Upgraded from System --> Software Packages Updates

**Comment by FlowerShopGuy** [comment]
`Webmin configuration --> Update Webmin`
I dont have this in my Webmin for some reason.

**Comment by iliajie** [comment]
> I dont have this in my Webmin for some reason.

It's great, and that means you have the [Webmin repository](https://webmin.com/download/#repository) configured; you should use the package manager to install the package upgrade.
