### ISSUE TITLE
Main Dashboard Tables width

### ISSUE THREAD

**Issue by to4ko** [webmin/webmin#1166]
Just get 1.94 and gettting this on main dashboard. Can it be fixed somehow? I mean get drives temp in few lines so the table columns will have identical width.

![image](https://user-images.githubusercontent.com/45161980/71450477-f5654b00-2773-11ea-802e-9f5a2372d41d.png)

**Comment by jcameron** [comment]
@iliaross looks like a theme issue when the number of drives is too high?

**Comment by rostovtsev** [comment]
Duh, thanks, and very appreciate giving a try and reporting a bug _**so**_ much! 

Fixed on the latest theme commit! Give it a try by force updating to the latest development version of the theme (from theme configuration page).

**Comment by to4ko** [comment]
Just get last dev version. Fantastic! Thanks!!!!!

![image](https://user-images.githubusercontent.com/45161980/71458041-003ed080-27b2-11ea-922c-3c5cf5219fdc.png)
