### ISSUE TITLE
Webmin and BIND on Windows version issue

### ISSUE THREAD

**Issue by UPS99** [webmin/webmin#1167]
We have an ISC BIND on Windows environment with 8 DNS servers covering more than 1000 servers in 2 datacenters and 5000+ users which has worked flawlessly for 12+ years.  The current servers are Win 2019 with BIND 9.11.11 ESV.  However, there is one exception - the master server (which is not used for direct DNS queries from clients) is still at BIND 9.9.1 .  We have never been able to get Webmin to work with any BIND version later than 9.9.1.  The version of Webmin does not matter.  The message "The server executable d:/dns/bin/named.exe does not appear to be BIND 8 or 9. Maybe your should use the BIND 4 module instead. Output from the command d:/dns/bin/named.exe -help was : Use -f to run from the command line." appears when attempting to run any later version.  This seems to be a result coming from the script "bind8-lib.pl", which runs several version checks for 8 and 9.  The only obvious difference is that beginning around v 9.9.1, the output of "named -v" is no longer just "BIND 9.9.1" but includes (Stable Release), (Extended Support Version), etc.   I can follow the Perl code to an extent, but that's about it.  Does anyone have any thoughts?  I would not be against bypassing the version checks - there is no way this would ever be used with BIND 8 or very old versions of 9.

**Comment by chris001** [comment]
The regex in the code needs adjusting to work with extra text on the end of the version line:
https://github.com/webmin/webmin/blob/master/bind8/bind8-lib.pl#L52

**Comment by UPS99** [comment]
I'm not sure if you meant this had been fixed in this recently updated file, or if it still needs adjusting.  Trying this still gives the same error.

**Comment by UPS99** [comment]
Fixed it !  There is a check for BIND 8 that appears to always run, regardless if 9 has already been detected.  I commented that out and everything works.   That check is running the invalid switch "named -help" which seems to be the cause of the error message.  This worked on this file, plus the original files included with versions 1.749 and 1.930

3 lines commented out (used "%" to avoid this site reformatting):

check_bind_8()
Returns the --help output if non BIND 8/9, or undef if is
sub check_bind_8
(
% my $fflag = $gconfig{'os_type'} eq 'windows' ? '-f' : '';
% my $out = `$config{'named_path'} -help $fflag 2>&1`;
%5return $out !~ /\[-f\]/ && $out !~ /\[-f\|/ ? $out : undef;
}

**Comment by chris001** [comment]
To format your text as code on github, you just put three backticks alone on a line before it, and after it, same thing, three backticks alone on a line, as shown here:
https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks

**Comment by jcameron** [comment]
What does `named` output when run with the `--help` flag on Windows?

**Comment by UPS99** [comment]
Every BIND version I had tried produces the same exact result to "named -help":
“Use -f to run from the command line.”
This includes testing on Windows 2008 R2 of BIND 9.9.1-P2 and 9.9.3
and testing on Windows 2019 of BIND 9.9.1-P2, 9.9.3, 9.9.5, 9.9.6, 9.9.7 , 9.9.9-P8, 9.11.11, and 9.14.9

However, only 9.9.1-P2, and some older versions I did not keep track of, produce the simple “BIND 9.9.1” response to “named –v”.  The others all append something, following a space - such as “(Extended Support Version)”.
(My reason for trying so many was the hope that I could find a later version that did not append anything.)

So I think that this suggests that the v8 check code I had commented out is only being run when the previous v9 check does not work correctly due to the long responses to "named -v".

**Comment by UPS99** [comment]
We have been running this in production for about 5 weeks now, with only the offending 3 lines in a version check routine in "bind8-lib.pl" commented out, and there have been no issues. 

Those lines repeated here:

local $fflag = $gconfig{'os_type'} eq 'windows' ? '-f' : '';
local $out = `$config{'named_path'} -help $fflag 2>&1`;
return $out !~ /\[-f\]/ && $out !~ /\[-f\|/ ? $out : undef;

**Comment by jcameron** [comment]
I had a look at the code, and realized that this check is obsolete even on Linux - so it's been removed for the next release.
