### ISSUE TITLE
Failing to fetch webmin package with Ubuntu 18.04

### ISSUE THREAD

**Issue by notboring** [webmin/webmin#1168]
apt-get throws a 404 error on Ubuntu 18.04 at the moment:
```
Err:1 http://download.webmin.com/download/repository sarge/contrib amd64 webmin all 1.940
  404  Not Found [IP: 108.60.199.109 80]
E: Failed to fetch http://download.webmin.com/download/repository/pool/contrib/w/webmin/webmin_1.940_all.deb  404  Not Found [IP: 108.60.199.109 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

I checked
`http://download.webmin.com/download/repository/pool/contrib/w/webmin/`

and wasn't able to find the missing file. There seems to be a new version named **webmin_1.940-2_all.deb** though. 

The release file
`http://download.webmin.com/download/repository/dists/sarge/contrib/binary-amd64/Packages`
is 3 days older and misses the -2 version.

**Comment by rostovtsev** [comment]
Hi,

Did you try running:

~~~
apt-get clean
~~~

**Comment by notboring** [comment]
Thanks a lot for the quick update! I was able to download and install the package using apt-get without any issues.

**Comment by jcameron** [comment]
This should be fixed now, but you may need to run `apt-get clean` to fix up any local caches.
