### ISSUE TITLE
Webmin Debain repo refresh failed, repo nolonger signed

### ISSUE THREAD

**Issue by KB3NZQ** [webmin/webmin#1169]
Went to pach my UNMS server this morning and i got this 
`sudo apt-get update
Hit:1 http://us-east-2.ec2.archive.ubuntu.com/ubuntu bionic InRelease
Get:2 http://us-east-2.ec2.archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:3 http://us-east-2.ec2.archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Hit:4 http://security.ubuntu.com/ubuntu bionic-security InRelease
Hit:5 https://download.docker.com/linux/ubuntu bionic InRelease
Hit:6 http://archive.canonical.com/ubuntu bionic InRelease
Ign:7 https://download.webmin.com/download/repository sarge InRelease
Get:8 https://download.webmin.com/download/repository sarge Release [1622 B]
Ign:9 https://download.webmin.com/download/repository sarge Release.gpg
Reading package lists... Done
E: The repository 'https://download.webmin.com/download/repository sarge Release' is no longer signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
`

I tried reinstalling the repo signing key with 
`wget -qO - http://www.webmin.com/jcameron-key.asc | sudo apt-key add -` 
then running sudo apt-get update again with same error. What changed? would like to get my paching done today.

**Comment by jcameron** [comment]
Does running `apt-cache clean all` fix this?

**Comment by jcameron** [comment]
Also, which Debian version is this? I just did a test on a Debian 10 VM, and was able to upgrade just fine.

**Comment by KB3NZQ** [comment]
Jamie I'll look when I get back to civilization I'm out on a hike with the
family right now

**Comment by KB3NZQ** [comment]
Jamie tried apt-cache clear no joy says it's invalid command. I'm running
Ubuntu 18.04.3 LTS  on Amazon aws

**Comment by chris001** [comment]
> Jamie tried apt-cache clear no joy says it's invalid command. I'm running Ubuntu 18.04.3 LTS on Amazon aws 
Try:
`apt-get clean all`
`apt-get update`
`apt-get upgrade`

**Comment by KB3NZQ** [comment]
Ok that fixes the problem did apt-get clean but not clean all.
Thanks as soon as I get back to the house I'll close the issue on github
