### ISSUE TITLE
Migration to organization

### ISSUE THREAD

**Issue by Neustradamus** [webmin/webmin#1171]
@jcameron, @rostovtsev, @swelljoe, @webmin, @usermin, @virtualmin: Any news?

Happy New Year 2020 <3

All informations already said in previous tickets!

Linked to:
- https://github.com/webmin/webmin/issues/876
- https://github.com/virtualmin/virtualmin-gpl/issues/97

**Comment by rostovtsev** [comment]
Happy New Year 2020, mate! 

There are no news about moving to organization yet. Sorry. Please don't ping us about it anymore. :smile: 

I know you gonna say, "why", "it takes only few moments", "the links would be redirected" and etc.

I will discuss with the team, what other moves we could take, for combining all stuff under one account.

**Comment by Neustradamus** [comment]
@rostovsev: Thanks for your reply!

Please do not close before solution!

Warning: Account /= Organization

**Comment by Neustradamus** [comment]
@jcameron, @iliaross, @swelljoe, @webmin, @usermin, @virtualmin: Can you reopen this not solved ticket?

**Comment by swelljoe** [comment]
Please stop @Neustradamus . We have all already replied to you. Now, you're just being rude.
