### ISSUE TITLE
issue with view login sessions

### ISSUE THREAD

**Issue by anil111222** [webmin/webmin#1175]
i was not able to see the login & logout sessions history  only it was showing the present login history and next day i was not able to see those login sessions also. when i use to change webmin configuration/ Authentication it was showing link " The Webmin server process is now restarting - please wait for a few seconds before continuing" .

**Comment by jcameron** [comment]
Can you post a screenshot so we can see which page you're referring to?

**Comment by anil111222** [comment]
![Screenshot (44)](https://user-images.githubusercontent.com/59677839/72051547-84807000-32e9-11ea-9f4b-31894c07eb6f.png)

**Comment by rostovtsev** [comment]
You are not looking at the right place.

You need to use _Webmin/Webmin Action Log_. Make sure that it's enabled, 
![image](https://user-images.githubusercontent.com/4426533/72075467-d8e51900-3304-11ea-973c-a8218fe56edc.png)


just as well as this option:

![image](https://user-images.githubusercontent.com/4426533/72075403-ba7f1d80-3304-11ea-9551-a404324bb6ef.png)

**Comment by anil111222** [comment]
![Screenshot (45)](https://user-images.githubusercontent.com/59677839/72125444-9cf69600-338e-11ea-9080-b0faed384e3c.png)
![Screenshot (47)](https://user-images.githubusercontent.com/59677839/72125554-08d8fe80-338f-11ea-85a9-b07f071913ee.png)

 i was not able to see the login & logout session history also.

**Comment by jcameron** [comment]
It won't show sessions that are already logged out - only those that are currently active.

**Comment by anil111222** [comment]
is there any possibility to show sessions logged-in & logged-out for at least for 7 days.

**Comment by jcameron** [comment]
You can see login and logout events at Webmin -> Webmin Actions Log.
