### ISSUE TITLE
Refresh/Update

### ISSUE THREAD

**Issue by kazuser** [webmin/webmin#1178]
![refresh-button](https://user-images.githubusercontent.com/3335273/72230651-14236880-35e1-11ea-8ad5-b32657404858.png)

Could you please add a refresh/update button?

**Comment by jcameron** [comment]
Yes, this will go into the next release : https://github.com/webmin/webmin/commit/9239327440a173ffa5c2c0d3dbedfe27fa0e0b2a

**Comment by rostovtsev** [comment]
Besides, right now, you can use `Alt+R` (by default) to reload current page.
