### ISSUE TITLE
[Netgear Stora] Error after login

### ISSUE THREAD

**Issue by Sigri44** [webmin/webmin#1180]
Hello, i have error after login to webmin : 

HTTP/1.0 500 Perl execution failed Server: MiniServ/1.940 Date: Sat, 18 Jan 2020 09:52:48 GMT Content-type: text/html; Charset=iso-8859-1 Connection: close
Error - Perl execution failed

Undefined subroutine &WebminCore::format_document_title called at /tmp/webmin/authentic-theme/authentic-init.pm line 1306.

I don't understand it, when i change directory folder to absolute path in require, same error.

**Comment by rostovtsev** [comment]
Hi,

This is odd error.

At first try upgrading to Webmin 1.941!

**Comment by Sigri44** [comment]
This is the last .tar.gz file.. !

**Comment by Sigri44** [comment]
Found it ! It's not yet stable on Sourceforce ...
But same mistake !

![image](https://user-images.githubusercontent.com/9304947/72667345-3cfd9080-3a1b-11ea-8083-78cdfa2e7e35.png)

**Comment by rostovtsev** [comment]
It looks like the theme installation is corrupted. Try updating the theme using `./theme-update.sh` from its directory.

**Comment by Sigri44** [comment]
![image](https://user-images.githubusercontent.com/9304947/72930122-8facb480-3d5b-11ea-808d-cb16b68462f0.png)

Corrupted too.

**Comment by rostovtsev** [comment]
Okay, I think I know what's going on. We discussed it with Jamie. It seems that you are running old-old Perl version that doesn't support branch reset group operators in regex.

Can you try to open/edit `authentic-funcs.pl` file and edit on line 431, where:

~~~Perl
sub format_document_title
{
    my ($title_initial) = $_[0] =~ /(?|.*:\s+(.*)|(.*))/;
    my ($product, $os_type) = $title_initial =~ /(?|(.*\d+).*(\(.*)|(.*\d+))/;
    $os_type = undef if (length($os_type) < 4);
    my $title = ($os_type ? "$product $os_type" : $product);
    $title =~ s/\R//g;
    return $title;
}
~~~

and replace it with:

~~~Perl
sub format_document_title
{
    return $_[0];
}
~~~

Does it change anything?

What is the output of 

~~~
perl -v
~~~

**Comment by Sigri44** [comment]
> 
> 
> Okay, I think I know what's going on. We discussed it with Jamie. It seems that you are running old-old Perl version that doesn't support branch reset group operators in regex.
> 
> Can you try to open/edit `authentic-funcs.pl` file and edit on line 431, where:
> 
> ```perl
> sub format_document_title
> {
>     my ($title_initial) = $_[0] =~ /(?|.*:\s+(.*)|(.*))/;
>     my ($product, $os_type) = $title_initial =~ /(?|(.*\d+).*(\(.*)|(.*\d+))/;
>     $os_type = undef if (length($os_type) < 4);
>     my $title = ($os_type ? "$product $os_type" : $product);
>     $title =~ s/\R//g;
>     return $title;
> }
> ```
> 
> and replace it with:
> 
> ```perl
> sub format_document_title
> {
>     return $_[0];
> }
> ```
> 
> Does it change anything?
> 
> What is the output of
> 
> ```
> perl -v
> ```

-bash-3.2# perl -v
This is perl, v5.10.0 built for arm-none-linux-gnueabi

It's the max on my system (Netgear Stora), and they recommend webmin.



Good job, semi-working !

![image](https://user-images.githubusercontent.com/9304947/72936649-e7511d00-3d67-11ea-80df-dab7eb6f82db.png)

**Comment by chris001** [comment]
I bet if you upgraded the perl 5.10.0 that it came with, to the current stable version of [perl 5.30.1](https://github.com/Perl/perl5/releases), Webmin'd work just fine.

**Comment by Sigri44** [comment]
> 
> 
> I bet if you upgraded the perl 5.10.0 that it came with, to the current stable version of [perl 5.30.1](https://github.com/Perl/perl5/releases), Webmin'd work just fine.

Unfortunately the springs and the community of Stora have been dead and buried for almost 2 years. We are a very small handful to continue to use this SIN, but the end is near.
IPKG, the package manager, doesn't allow Perl upgrades above the existing version, and I don't have enough knowledge to compile.

**Comment by chris001** [comment]
Have you ever used [perbrew](https://perlbrew.pl/) - it's made exactly for this reason, to let you use a new perl version, without any need to modify the (older) perl version that came with your system.

**Comment by rostovtsev** [comment]
@Sigri44 Where can I download ISO of this exact Linux distro?

**Comment by chris001** [comment]
> @Sigri44 Where can I download ISO of this exact Linux distro?
> 
> **Edit:**
> Supporting it might be insupportable hassle. 🙂

The Netgear Stora linux storage box appears to use **HipServ OS** which seems to be a type of **Red Hat Linux**.
Reference: https://github.com/Dees7/openstora

**Comment by Sigri44** [comment]
https://github.com/Sigri44/OpenStora

**Comment by swelljoe** [comment]
It's not reasonable for us to support an EOL and unsupported OS. Old versions of Webmin from the same era will obviously work, but it's not safe to run an unmaintained OS on a network-accessible device. Or, if you upgrade your Perl (even to just 5.10.1, which is the oldest version we test on), it should work.

**Comment by chris001** [comment]
@Sigri44 
What happens when you run these commands, as the root user, to install the latest stable perl version, separated from the system perl version, for webmin to run on this new perl version:
```
wget -O - https://install.perlbrew.pl | bash
perlbrew init
perlbrew install perl-5.30.1
perlbrew switch perl-5.30.1
```
