### ISSUE TITLE
issue with view login sessions:

### ISSUE THREAD

**Issue by anil111222** [webmin/webmin#1182]
![Screenshot (48)](https://user-images.githubusercontent.com/59677839/72714547-e6b45d00-3b94-11ea-867f-32542cad43a7.png)

unable to view the previous login sessions of the user . when the user logged in & logged out .
it was showing only active user login sessions . when the user logged out , it was showing logged out user details only for 2 hours in the view login sessions . 
how i can collect login and logout session details of each and every user for a perticular time period.

**Comment by rostovtsev** [comment]
Dupe:
https://github.com/webmin/webmin/issues/1175
