### ISSUE TITLE
SSL Encryption module in Webmin Configuration throws 500 error

### ISSUE THREAD

**Issue by sergebigras** [webmin/webmin#1186]
When I choose SSL Encryption module in Webmin Configuration, I get :

 500 - Error - Perl execution failed
Global symbol "$letsencrypt_cmd" requires explicit package name at /usr/libexec/webmin/webmin/edit_ssl.cgi line 308.

Running Webmin Version 1.941.0123.0806 on CentOS 7 with latest patches

**Comment by rostovtsev** [comment]
Hi,

What do you have set in _Webmin/Webmin Configuration/Module Configuration_?

![image](https://user-images.githubusercontent.com/4426533/73067524-fc3dc580-3eb9-11ea-86cb-c85e6c45c581.png)

What is the output of:

~~~
whereis certbot
~~~

**Comment by chris001** [comment]
https://certbot.eff.org/lets-encrypt/centosrhel7-other.html

**Comment by rostovtsev** [comment]
> Running Webmin Version 1.941.0123.0806 on CentOS 7 with latest patches

Duh, missed that you're running latest dev version.

Fixed. https://github.com/webmin/webmin/commit/d693dc34bea9cacfb89daaa9207e397886afb57f

Thank you **_**very much**_** for reporting!

**Comment by sergebigras** [comment]
Thanks ! Indeed fixed in last release !
