### ISSUE TITLE
Webmin 1.941 Stats History Loading ... (not loading)

### ISSUE THREAD

**Issue by rjalexa** [webmin/webmin#1195]
Worked well after clean install. Did some assorted system updates. Now statistics do not load anymore. Loading message and spinning circle.

Raspbian Buster Lite with Webmin 1.941

bob@rpibuster:/bin $ ps aux | grep webmin
root       641  0.0  0.4  22080 18532 ?        Ss   16:22   0:00 /usr/bin/perl /usr/share/webmin/miniserv.pl /etc/webmin/miniserv.conf

nginx webserver

What can I do to debug and fix this please?

**Comment by rjalexa** [comment]
I have a reproducible situation.
If I invoke webmin as https://192.168.X.Y/webmin/ it loads the statistics section just after the system information one and IT WORKS (it is then followed by the recent logins and disk usage sections)
but
the URL is transformed as https://192.168.X.Y/webmin/sysinfo.cgi?xnavigation=1 
with this URL if I reload the page the URL is transformed to https://192.168.X.Y/webmin/?xnavigation=1 and in this situation the webmin statistics section is loaded after all others and in this case it hangs without ever loading

**Comment by rostovtsev** [comment]
Hi,

This is odd. Do you have any errors on the console? 

Can you provide any screenshots?

---

Possible workaround. Go to `/tmp/.webmin` and backup this directory first. Then go to _Theme Configuration_ and click clear cache button. If it helps, email me previously backed-up directory.

![image](https://user-images.githubusercontent.com/4426533/73879278-38cfd080-486d-11ea-8fc3-8df419d699ca.png)

It's also worth clearing browser's cache.

**Comment by rjalexa** [comment]
Thank you very much for trying to understand.
The /tmp/.webmin directory was empty.
I did try the clear theme cache and also clear the browser cache but the behaviour is unmodified.
Here are the two different screenshots
![Screenshot 2020-02-05 21 35 35](https://user-images.githubusercontent.com/15216911/73881591-e8eb0c80-4860-11ea-8199-478fa1411c6e.png)
![Screenshot 2020-02-05 21 36 16](https://user-images.githubusercontent.com/15216911/73881614-f30d0b00-4860-11ea-9a29-880bd7f99804.png)

**Comment by rostovtsev** [comment]
What if you set your `webprefix` to something else rather than `webmin`?

**Comment by rostovtsev** [comment]
>  Did some assorted system updates.

What do you mean by that?

What systems updates

**Comment by rjalexa** [comment]
I did a few things to "harden" the webserver and OS, minor stuff involving changing the executability of the su command, creating a wheel group whose users only can run it, install a certbot certificate for nginx and stuff like that.

**Comment by rjalexa** [comment]
> What if you set your `webprefix` to something else rather than `webmin`?

I get an unformatted page

![Screenshot 2020-02-06 08 04 42](https://user-images.githubusercontent.com/15216911/73913505-81ac7700-48b7-11ea-8a25-cbd033b7b26c.png)

**Comment by rostovtsev** [comment]
> I get an unformulated page

I meant `webprefix` in `/etc/webmin`. If you set it to `mywebmin`, for example?

**Comment by rostovtsev** [comment]
I have just made a patch that should address redirects when using webprefix. Give it a try by installing latest development version of the theme from its Configuration Theme page.

**Comment by sv3t0sl4v** [comment]
I have a similar problem. It is not showing up at all since last update to 1.994

**Comment by iliajie** [comment]
Dupe https://github.com/webmin/webmin/issues/1665
