### ISSUE TITLE
File Manager: Saving a file in editor, does actually NOT save the file

### ISSUE THREAD

**Issue by Jezzper** [webmin/webmin#1196]
In File Manager (Others\File Manager) you can edit a text file, by right clicking on a file and choosing Edit. You can then save by clicking on the save icon (floppy disk). Popup shows it has "succesfully been saved" . However in reality the file has NOT been saved.
It is very easy to document. Just create a new file , add some text, save , close, open it again and you will see the added text is gone

Webmin version 1.941, theme 19.45, user Root, on Centos 7

**Comment by rostovtsev** [comment]
Hi,

Thanks for reporting. You really need to make sure that you are running Webmin 1.941. This issue has been fixed for theme 19.45 for sure.

Try force reloading browser's cache by clicking `Ctrl+Shift+R` or trying incognito tab. What browser are you seeing it on?

**Comment by Jezzper** [comment]
A restart of server seemed to fix the problem :-)
