### ISSUE TITLE
"Tables to cache" Title Not Display At "MySQL Server Configuration" Page

### ISSUE THREAD

**Issue by Francewhoa** [webmin/webmin#1197]
## Steps to Reproduce

1. Using Debian 10 Buster, install a fresh Webmin 1.941 & Virtualmin 6.08 
1. Navigate to "Webmin" ---> "Servers" ---> "MySQL Database Server" ---> "MySQL Server Configuration"
1. Below "Network buffer size" field, notice that the next field below is not display. This is the challenge. The number 1 in this screenshot shows the location of this challenge.
![screenshot_challenge---table_open_cache---table_cache---webmin---2020-02-05](https://user-images.githubusercontent.com/119942/73977126-95b79f00-48de-11ea-8121-2301a6bc1e75.jpg)
1. Expected result is the field titled `Tables to cache` needs to be display. So that end-users know what this configuration is for.

## Using

* Debian 10 Buster
* MariaDB 10.3.18 
* Webmin 1.941
* Virtualmin 6.08 
* Authentic theme version 19.46 

## Cause

This is a speculation about what might cause this challenge:
   1. Back in 2005, starting with MySQL 5.1.3 `table_cache` was depreciated and renamed to `table_open_cache`(1). In other words, it's the same variable. Just a new & clearer name.
   1. On Debian 10 Buster, the default database server is MariaDB 10.3.18. Maybe somehow Webmin searches the default `mariadb.conf.d` configuration file at `/etc/mysql/mariadb.conf.d` for `table_cache` variable. But found none. Because this variable name was depreciated. It is now call `table_open_cache`.
   1. In turn, somehow Webmin display no field title for `table_open_cache`. But does display its value if any are set.

(1)Sources about back in 2005, starting with MySQL 5.1.3 `table_cache` was depreciated and renamed to `table_open_cache`:

       * https://mariadb.com/kb/en/where-is-the-table_cache-in-mariadb/ or https://archive.md/TnZJb
       * https://bugs.mysql.com/bug.php?id=51599
       * https://bugs.mysql.com/bug.php?id=68315

For those not familiar with `Tables to cache`, with Debian 10 Buster with its default MariaDB 10.3.18 in the back end, `Tables to cache` is called the `table_open_cache` variable

If the end-user manually edit this configuration file at `/etc/mysql/mariadb.conf.d` then set `table_open_cache = 163840`. Then navigate to "Webmin" ---> "Servers" ---> "MySQL Database Server" ---> "MySQL Server Configuration" the value `163840` is display. But somehow the field title is still not display `Table to cache`. The number 2 in this screenshot shows this challenge.
![screenshot_challenge---table_open_cache---value_display---webmin---2020-02-05](https://user-images.githubusercontent.com/119942/73977989-3d819c80-48e0-11ea-9ee4-62cc79aac2bf.jpg)

## Note

* On Debian 10 Buster
   * The default database server is MariaDB. Which uses the variable `table_open_cache`
   * The configuration file is located at `/etc/mysql/mariadb.conf.d`
* On Debian 7 Wheezy
   * The default database server is MySQL. Which uses the variable  `table_cache`a
* @Francewhoa :) Note to myself. UB IT's Unique ID: 20200506.1229

**Comment by Francewhoa** [comment]
## Screenshot 

This screenshot show another fresh Webmin 1.941 installation we did today. Notice that the `table_open_cache` variable default value `512` is display. But somehow the field title is not.
![screenshot_challenge---fresh_webmin_installation---2020-02-05](https://user-images.githubusercontent.com/119942/73979535-2ee8b480-48e3-11ea-919e-a3b301729201.jpg)

## mariadb.conf.d

This `mariadb.conf.d` file is located at `/etc/mysql/mariadb.conf.d`. Its content is copied below. Notice the `table_open_cache = 512` line below.

```
[server]


[mysqld]




user                    = mysql
pid-file                = /run/mysqld/mysqld.pid
socket                  = /run/mysqld/mysqld.sock

basedir                 = /usr
datadir                 = /var/lib/mysql
tmpdir                  = /tmp
lc-messages-dir         = /usr/share/mysql




bind-address            = 127.0.0.1



















query_cache_size = 32M












log_error = /var/log/mysql/error.log













expire_logs_days        = 10




























character-set-server  = utf8mb4
collation-server      = utf8mb4_general_ci
innodb_file_per_table = 1
thread_cache_size = 8
myisam_sort_buffer_size = 64M
read_rnd_buffer_size = 8M
read_buffer_size = 2M
sort_buffer_size = 2M
table_open_cache = 512
max_allowed_packet = 1M
key_buffer_size = 384M

















[embedded]




[mariadb]




[mariadb-10.3]

```

**Comment by rostovtsev** [comment]
Francois, thanks for detailed and clear issue report. Pleasure to take a look. Appreciate this!!

Next Webmin version will have it fixed.

**Comment by Francewhoa** [comment]
Thanks @iliaross :) For both the fix and your quick reply
