### ISSUE TITLE
Webmin 1.941 Reverse Proxy Breaks Apache

### ISSUE THREAD

**Issue by DavidGhedini** [webmin/webmin#1201]
I'm using Apache Reverse Proxy (/webmin) with Authentic Theme and it seems to break the Apache Module.

Attempting to stop/start/restart Apache via Webmin goes to 404 error.  The url generated is:

`https://domain.com/webmin/apache/restart.cgi?redir=%2Fwebmin%2Fapache%2Findex%2Ecgi%3Fmode%3Dglobal`

I've attempted to use a different mapping other than /webmin, but issue is the same.

All other function/features work normally.

**Comment by rostovtsev** [comment]
Hi,

It's pretty expected - restarting Apache, while running Webmin behind the same Apache process will result in what you're experiencing! No surprise. It receives _SIGTERM_ upon loosing connection and script just stops.
