### ISSUE TITLE
NVMe, "Used by" Empty

### ISSUE THREAD

**Issue by arrmo** [webmin/webmin#1202]
Hi,

Inside Partitions on Local Disks > select the NVMe drive ... then Used by - column is empty, whereas it's populated for SATA drives.

But, if you select the Type (for the NVMe drive), Status does show where it is mounted (so the information is available, just not populated to Used by it seems).

Thanks!

**Comment by jcameron** [comment]
Can you post a screenshot of that page? Also, the contents of /proc/partitions and /etc/mtab would be useful.

**Comment by arrmo** [comment]
Sure, NP. Let me try to expain this a bit better (with pics and info, as you say),
a) Local partitions,
![image](https://user-images.githubusercontent.com/8756384/74768025-7e1cd680-524d-11ea-8f7d-93c20be1debd.png)
b) NVMe partition, Used by is empty,
![image](https://user-images.githubusercontent.com/8756384/74768059-8aa12f00-524d-11ea-8e8a-22baef5d299f.png)
c) Similar example, but for SATA partition,
![image](https://user-images.githubusercontent.com/8756384/74768095-955bc400-524d-11ea-8dd5-c4fb7d6d41ef.png)
d) And under NVME, select type (Linux EXT), it shows where mounted (Used by),
![image](https://user-images.githubusercontent.com/8756384/74768128-a86e9400-524d-11ea-9927-e7ff429a496d.png)

The files you asked for,
i) /proc/partitions,
```
major minor  #blocks  name

 259        0  500107608 nvme0n1
 259        1  500106240 nvme0n1p1
  11        0    1048575 sr0
   8        0  117220824 sda
   8        1     262144 sda1
   8        2     512000 sda2
   8        3  116445184 sda3
   8       16  244198584 sdb
   8       17  244197376 sdb1
   8       32 1953514584 sdc
   8       33 1953513472 sdc1
   9        0 1953382208 md0
   8       48 1953514584 sdd
   8       49 1953513472 sdd1
 253        0  344948736 dm-0
 253        1   15687680 dm-1
```
ii) /etc/mtab (OK, file is quite large, grep'd by nvm),
`/dev/nvme0n1p1 /mnt/ProgSSD ext4 rw,relatime 0 0
`

Thanks!

**Comment by jcameron** [comment]
Ok I see the bug - I've checked in a fix (which is attached to this ticket) for inclusion in the next release.

**Comment by arrmo** [comment]
Much appreciated! Not a big deal, but did want to let you know about it.

Thanks for Webmin!
