### ISSUE TITLE
DNS Zone SOA defaults ?

### ISSUE THREAD

**Issue by chris001** [webmin/webmin#1203]
It appears that the DNS Zone SOA default values are possibly very different than the range of what they should be for best DNS zone health.
Expire certainly is way off.  It's 7 days when the recommended range is 14-28 days.
I'm posting this issue as something to explore and discuss.  
Not 100% saying what the rest of the values should be, however, some of them appear to be of a different order of magnitude than the given RFC default values.
Currently virtualmin/webmin is using values like this:
```
@ IN SOA nameserver.example.com. postmaster.example.com. (
2020022200 ; serial number, just fine.
10800 ; refresh [ 3 hours ]
3600; retry [1 hour]
604800;  expire [7 days]
38400 ) ; min TTL [ 10 hours 40 minutes ]
```
RFC says:
```
@ IN SOA nameserver.example.com. postmaster.example.com. (
	1; serial number
	3600 ; refresh [1h]
	600; retry [10m]
	1209600 ; expire[14d]
	3600 ) ; min TTL [1h]
```

**Comment by jcameron** [comment]
Thanks - those defaults in Webmin are pretty old. We'll change them to be what you suggested.
