### ISSUE TITLE
Can't detect the mail agent

### ISSUE THREAD

**Issue by par7133** [webmin/webmin#1205]
Hello,

In OpenBSD 6.6 (ver 1.941), the 'read user mail' "applet" can't detect the system 'mail' program, so that the user email become unreadable.

Hope you can solve this problem too.

Daniele

**Comment by rostovtsev** [comment]
Hi,

If you need **mailboxes** module to work on OpenBSD, you need to setup/install a mail server.

The easiest way is to install, **exim** package, for example:

~~~
pkg_add -v exim
   1: exim-4.92.3
~~~

.. and then replace **smtpd** with **exim**:

~~~
/usr/local/sbin/exim-enable
~~~

**Comment by par7133** [comment]
Hello,

I had the expectation Webmin could leveraged the ObenBSD system/user mail 
...

Please use this like an hint / feature request.

Thx!
