### ISSUE TITLE
[SOLVED] ERR_SSL_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by manjotsc** [webmin/webmin#1208]
Site working fine on local network with certificate, but when access from outside the network doesn't work,

On LocalNetwork

![Annotation 2020-02-29 171734](https://user-images.githubusercontent.com/51430971/75616009-43525280-5b19-11ea-800a-000846ee5243.png)

On Externally:

![Annotation 2020-02-29 171746](https://user-images.githubusercontent.com/51430971/75616013-4cdbba80-5b19-11ea-89ce-a25eb6ea9a45.png)

**Comment by jcameron** [comment]
Are you using the same hostname or IP address locally vs externally?

**Comment by manjotsc** [comment]
@jcameron Yes I am using same hostname.

**Comment by jcameron** [comment]
Is there any kind of proxy or firewall that could be preventing external access?

**Comment by manjotsc** [comment]
@jcameron Firewall is disabled on debian box, and I am using PfSense as firewall.

**Comment by manjotsc** [comment]
@jcameron Just fixed I have websites running on my Webmin, One on **192.168.40.75 (Auth)** and the other one on ### 192.168.40.74 (Speed), I had opened the ### port 443 for Auth, and was trying to access **Speed**.
