### ISSUE TITLE
simple firewall creater

### ISSUE THREAD

**Issue by bgman111111** [webmin/webmin#1209]
hi

i start try webmin and strange. my question is: how simple firewall work. i want to block all and accept only selected port. When i select accept only this service and acruvate them after . it dont work. everything is allowed. when i select drop eveything include i had to make two rules from source eth1 and out eth1 it start block everything. so i add this service and again port 587 is opened. i look and port 587 is blocked... why there is no block all and acceot only selected. for strange fail2ban is not working and i need to... for mobile make blocked ip work  i had vlocked more than 250 ip ans when open from mobile it freeze. make something like notepad ip to be easy loading and add numbers so peoples xan change ut from they webmin.

**Comment by gnadelwartz** [comment]
https://rimuhosting.com/howto/firewall.jsp 

google is your friend
