### ISSUE TITLE
Create let's encrypt Certificate for host without virtualmin

### ISSUE THREAD

**Issue by budda85** [webmin/webmin#1210]
Hey,
where can I create a certificate in Webmin for an apache virtual host, that i've **not** created with virtualmin?
Is it possible?
Thx

**Comment by iliarostovtsev** [comment]
Hi,

You have two options:
  1. Use **Webmin/Webmin Configuration/SSL Encryption** tab
  2. Import virtual-server using **Virtualmin/Add Server/Import Virtual Server** page.
