### ISSUE TITLE
:ui_text_color called at /usr/share/webmin/mount/system_info.pl error in dashboard tab

### ISSUE THREAD

**Issue by gamahawk97** [webmin/webmin#1214]
Hello i have updated the webmin version to 1.941. But when i clicked the  dashboard tab  the page not  showed system information. Then i changed the code in system_info.pl  ui_text_type to ui_text_color . boom! dashboard is come back. 

   36                     if ($free_percent > 49) {
   37                         $free_percent_html = **ui_text_type**("$free_percent%", 'success');
   38                     } elsif ($free_percent > 9) {
   39                         $free_percent_html = **ui_text_type**("$free_percent%", 'warn');
   40                     } else {
   41                         $open = 1;
   42                         $free_percent_html = **ui_text_type**("$free_percent%", 'danger');
   43                     }

  if ($free_percent > 49) {
   37                         $free_percent_html = **ui_text_color**("$free_percent%", 'success');
   38                     } elsif ($free_percent > 9) {
   39                         $free_percent_html = **ui_text_color**("$free_percent%", 'warn');
   40                     } else {
   41                         $open = 1;
   42                         $free_percent_html = **ui_text_color**("$free_percent%", 'danger');
   43                     }

**Comment by iliarostovtsev** [comment]
Hi,

Thanks for your feedback.

The problem why you're seeing this, is that because your Webmin hasn't been restarted properly. Undo the previous patch or reinstall Webmin 1.941 and run the following command:

~~~
kill -9 -- -WEBMIN_PID
~~~

However, it's better to [install Webmin 1.942](http://download.webmin.com/devel/) from devel repo to work around stuck process.

**Comment by gamahawk97** [comment]
Actually i restarted, thank you for your kind answer :)
