### ISSUE TITLE
mysql module is looking for the wrong file 

### ISSUE THREAD

**Issue by willhertz** [webmin/webmin#1221]
Fresh install of virtualmin from script.
If you try to edit MySQL configuration via MySQL module you will receive an error messsage stating that the config files do not incude [mysqld] section.

If you look in module settings  the **MySQL configuration file** parameter (under System Configuration section)

Module looks for config files in
`/etc/mysql/conf.d/mysql.cnf`

which is basically an empty file with just [mysql] tag.
I think it's supposed to point to
`/etc/mysql/my.cnf`
That is just a this couple of includers:

!includedir /etc/mysql/conf.d/
!includedir /etc/mysql/mysql.conf.d/

Don't really know if it is related to new changes in MySQL or Ubuntu. I have never had this problem with a dozen of servers in Ubuntu 14.04.

```
Platform info
host:
    hostname: ubuntu2020.
    module root: /usr/share/webmin/virtual-server
    os: Ubuntu Linux 18.04.4
    root: /usr/share/webmin
    theme version: 19.45
    virtualmin version: 6.08.gpl
    webmin version: 1.941
        * Operating system
        * Ubuntu Linux 18.04.4
    *
        * Perl version
        * 5.026001
    *
        * Path to Perl
        * /usr/bin/perl
    *
        * BIND version
        * 9.11
    *
        * Apache version
        * 2.4.41
    *
        * PHP versions
        * 5.6.40, 7.2.29, 7.4.4
    *
        * Webalizer version
        * 2.23-08
    *
        * Logrotate version
        * 3.11.0
    *
        * MySQL version
        * 5.7.29
reboot: 0

```

--------------------------------

**Comment by jcameron** [comment]
Are you running the MySQL package that is installed by default on Ubuntu 18 ?

**Comment by willhertz** [comment]
Sorry for the late response, had been offline this week
 
> Are you running the MySQL package that is installed by default on Ubuntu 18 ?


Can't be sure, it was installed using the install.sh script downloaded. The only thing that I did before runinng install script was disabling cloud-init and setting a fixed IP. I ran the script as root (not sudo).
Script was downloaded and executed March 15 2020

**Comment by jcameron** [comment]
Ok, in that case you would be running the standard MySQL package.

**Comment by jcameron** [comment]
Looks like the correct path is indeed /etc/mysql/mysql.cnf - we'll fix this in the next release.
