### ISSUE TITLE
During setup enable-collection gets modified and becomes a circular loop

### ISSUE THREAD

**Issue by RoyceTheBiker** [webmin/webmin#1224]
I download the 1.941 tar file like so
```
wget https://sourceforge.net/projects/webadmin/files/webmin/1.941/webmin-1.941.tar.gz
echo "3a19228d92556c7722c6fe56c9d4b73d477a19845b0dae3f018fc7fc0306b29a  webmin-1.941.tar.gz" | sha256sum -c
````
I have confirmed that the source code in [GitHub](https://github.com/webmin/webmin/blob/master/system-status/enable-collection.pl) matches the file in the tar but during setup the file gets change and as you can see the very last line of the script calls itself. This causes setup to get locked in an endless loop and never finish.

I had an older install in my Debian Stretch that I used Webmin page to upgrade and now it also has the defective file.

Where is this file being modified?
Why is it being modified?
Is there a workaround?

```perl
#!/usr/bin/perl
open(CONF, "/etc/webmin/miniserv.conf") || die "Failed to open /etc/webmin/miniserv.conf : $!";
while(<CONF>) {
        $root = $1 if (/^root=(.*)/);
        }
close(CONF);
$root || die "No root= line found in /etc/webmin/miniserv.conf";
$ENV{'PERLLIB'} = "$root";
$ENV{'WEBMIN_CONFIG'} = "/etc/webmin";
$ENV{'WEBMIN_VAR'} = "/var/webmin";
chdir("$root/system-status");
exec("$root/system-status/enable-collection.pl", @ARGV) || die "Failed to run $root/system-status/enable-collection.pl : $!";
```

**Comment by RoyceTheBiker** [comment]
I set the file to immutable and got this while running setup.
```
Changing ownership and permissions ..
chown: /etc/webmin/system-status/enable-collection.pl: Operation not permitted
chgrp: /etc/webmin/system-status/enable-collection.pl: Operation not permitted
chmod: /etc/webmin/system-status/enable-collection.pl: Operation not permitted
chmod: /etc/webmin/system-status/enable-collection.pl: Operation not permitted
..done
```

**Comment by jcameron** [comment]
What directory did you install the tar.gz file into? It should not be /etc/webmin , as that's the config directory, not where the code should go.

**Comment by RoyceTheBiker** [comment]
That seems to be the mistake. 

Thank you.
