### ISSUE TITLE
No indication of view when editing zone file

### ISSUE THREAD

**Issue by imcdona** [webmin/webmin#1227]
Seeing as how it's common to have the same zone in multiple views it's all to easy to get confused as to which view the zone file you're editing belongs to. Displaying the view the zone belongs to when editing a zone would help

**Steps to reproduce on a DNS server configured with multiple views:**
**1.** Click on a zone to edit
**2.** Note that there is no indication of the view the zone file your editing belongs to

PS: I couldn't find a place to enter a feature request. My apologies in advance if this is the incorrect forum for feature requests.

Thanks

**Comment by jcameron** [comment]
Good suggestion - I will add this in the next release.
