### ISSUE TITLE
Full screen command shell gone

### ISSUE THREAD

**Issue by mbates14** [webmin/webmin#1229]
I noticed after updating webmin and its themes, that the full screen command shell is gone. its now the old school box where you can run commands. 

Is there any way to get back the full screen shell window? I used this quite alot and it was very handy so I didnt have to have Putty and my SSH certificates handy.

**Comment by iliarostovtsev** [comment]
Hi,

It's not gone, it's just some people requested that the old functionality would also be supported. You simply can: 

  1. Click **Alt+K** to call for it from any place (unless on the input or textarea typing)
  2. Click on the button in the top right of the module's header to access it:
       
![image](https://user-images.githubusercontent.com/4426533/78798578-d35da480-79c1-11ea-9432-2d91ef969dda.png)

  3. Click a button on navigation menu (can be disabled/enabled from theme configuration) to access it:

![image](https://user-images.githubusercontent.com/4426533/78798826-191a6d00-79c2-11ea-95c0-a6a1f267664d.png)
