### ISSUE TITLE
FreeBSD user batch export / import failure

### ISSUE THREAD

**Issue by byrnejb** [webmin/webmin#1230]
FreeBSd-12.1p3
Webmin 1.941

Requirement:  
Copy logon credentials of user accounts selected by primary group from one FreeBSD host to another FreeBSD host.

Action:  
On Host 1 use Webmin export to batch file utility to export user accounts to page display.
On Host 2 use Webmin execute batch file utility to read from text text box.

Expected Results:
User accounts copied from Host 1 are created on Host 2.

Actual Results:
Error page displays <Line 1 does not contain 11 fields>
User account is not added to Host 2.

**Comment by jcameron** [comment]
Thanks - we'll fix this in the next release.
