### ISSUE TITLE
MariaBD 10.4: The target table user of the INSERT is not insertable-into

### ISSUE THREAD

**Issue by mischapeters** [webmin/webmin#1232]
For some time now creation of users in MariaDB is no longer possible.
As soon as you create a user the following error gets presented by save_user.cgi

```
Failed to save user : SQL insert into user (host, user, Select_priv, Insert_priv, Update_priv, Delete_priv, Create_priv, Drop_priv, Reload_priv, Shutdown_priv, Process_priv, File_priv, Grant_priv, References_priv, Index_priv, Alter_priv, Show_db_priv, Super_priv, Create_tmp_table_priv, Lock_tables_priv, Execute_priv, Repl_slave_priv, Repl_client_priv, Create_view_priv, Show_view_priv, Create_routine_priv, Alter_routine_priv, Create_user_priv, Event_priv, Trigger_priv, Create_tablespace_priv, Delete_history_priv, ssl_type, ssl_cipher, x509_issuer, x509_subject, authentication_string) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) failed : The target table user of the INSERT is not insertable-into
```
I looked at the workarounds for Virtualmin, but they don't apply to Webmin without Virtualmin.

The setup:
Webmin version: 1.941
Operating system: FreeBSD 12.1-RELEASE-p1
MariaDB version: 10.4.12

Any ideas how to get out of this?

**Comment by chris001** [comment]
The answer is here:
https://serverfault.com/questions/997678/the-target-table-user-of-the-insert-is-not-insertable-into-mariadb-10-4-11
Post back your results!

**Comment by mischapeters** [comment]
Thanx @chris001 for the suggestion. It’s one of the first things I indeed found and looked at. The difference is that the root user is still there, and on the command line it’s not a problem.

**Comment by chris001** [comment]
Are you saying, when you try to create a mysql/mariadb user on the command line, it works for you?

**Comment by mischapeters** [comment]
> Are you saying, when you try to create a mysql/mariadb user on the command line, it works for you?

Correct.
And looking at the virtualmin fixes there is some additional version checking being done. Which is not the case in save_user.cgi.

**Comment by mischapeters** [comment]
I am referring to this patch: https://www.virtualmin.com/node/66724

**Comment by chris001** [comment]
"Hi all, the complete and easiest solution that I've found was :

    Make a backup of file feature-mysql.pl : mv /usr/share/webmin/virtual-server/feature-mysql.pl /usr/share/webmin/virtual-server/feature-mysql.pl.bak

    Get the latest feature-mysql.pl from here : https://github.com/virtualmin/virtualmin-gpl/blob/master/feature-mysql.pl

then put it in /usr/share/webmin/virtual-server/
"

**Comment by mischapeters** [comment]
> "Hi all, the complete and easiest solution that I've found was :
> 
> ```
> Make a backup of file feature-mysql.pl : mv /usr/share/webmin/virtual-server/feature-mysql.pl /usr/share/webmin/virtual-server/feature-mysql.pl.bak
> 
> Get the latest feature-mysql.pl from here : https://github.com/virtualmin/virtualmin-gpl/blob/master/feature-mysql.pl
> ```
> 
> then put it in /usr/share/webmin/virtual-server/
> "

I know. That file doesn’t exist. I am not using virtualmin.

**Comment by chris001** [comment]
Here's all the perl code files with the words maridb in them:
https://github.com/webmin/webmin/search?l=Perl&q=mariadb

**Comment by chris001** [comment]
To solve this properly, I think the `perl` code from `virtualmin`'s `/usr/share/webmin/virtual-server/feature-mysql.pl` needs to be refactored out of that `perl` code file in `virtualmin`, and into a corresponding `perl` code file in `webmin`.  Because `webmin` needs to communicate with `mariadb` correctly, also, not just `virtualmin`.

**Comment by chris001** [comment]
Did you already try `update-from-repo.sh` and see if that gets you new perl code which maybe solves this bug with `mariadb` ?

**Comment by mischapeters** [comment]
> Did you already try `update-from-repo.sh` and see if that gets you new perl code which maybe solves this bug with `mariadb` ?

Just did...

```
Webmin detected ...
Search for  configuration ... found: /usr/local/etc/webmin/miniserv.conf (alternative location)
Config path for Webmin is:  /usr/local/etc/webmin
Install path for Webmin is: /usr/local/lib/webmin

Warning: you are updating from DEV repository https://github.com/webmin/webmin , this may break your installation!
Would you like to update Webmin from https://github.com/webmin/webmin [y/N] y
Pulling in latest changes for Webmin  (https://github.com/webmin/webmin) ...
head: illegal byte count -- -1
usage: date [-jnRu] [-d dst] [-r seconds|file] [-t west] [-v[+|-]val[ymwdHMS]]
            [-I[date | hours | minutes | seconds]]
            [-f fmt date | [[[[[cc]yy]mm]dd]HH]MM[.ss]] [+format]
Start update for Webmin ....

Error: makedist.pl failed! aborting ...
```

**Comment by chris001** [comment]
The `update-from-repo.sh` failed.  Possibly a small bug when running on `FreeBSD`?  Maybe @swelljoe @jcameron or @iliaross have an idea how to get the `update-from-repo.sh` to work on FreeBSD 12?

**Comment by iliarostovtsev** [comment]
Yeah, GNU **date** command is more complete than BSD variant. I'll take a look when I have time.

**Comment by iliarostovtsev** [comment]
Support for MariaDB 10.4+ and MySQL 8+  has been implemented in Webmin 1.960 and Virtualmin 6.13. Let us know if it works for you.

**Comment by mischapeters** [comment]
This is great news! Will give it some time for the new release to show up in FreeBSD ports, if that fails I will do an update-from-repo. Will keep you posted! Thank you for taking the time to address this. 👍

**Comment by mischapeters** [comment]
Can confirm this is working beautifully again. Awesome job!

**Comment by iliaross** [comment]
> The `update-from-repo.sh` failed. Possibly a small bug when running on `FreeBSD`? Maybe @swelljoe @jcameron or @iliaross have an idea how to get the `update-from-repo.sh` to work on FreeBSD 12?

@chris001 Fixed https://github.com/webmin/webmin/commit/c777d9cb75ddeea03f67cef8329c7bf52a84e3a0
