### ISSUE TITLE
Webmin isn´t showing running processes

### ISSUE THREAD

**Issue by bodyslicer** [webmin/webmin#1235]
Hi, Webmin isn't showing running processes. I've removed and reinstalled the app several times with no success. My system is running Ubuntu Sever 20.04 LTS
![Sem título](https://user-images.githubusercontent.com/14083137/80913694-f1969600-8d1c-11ea-95bd-4d6c5c8404a7.jpg)

**Comment by iliarostovtsev** [comment]
Hi,

Thanks for heads up!

It's a bug in `ps` command output on Ubuntu 20.04 that for `ps V` returns:

~~~
ps from procps-ng UNKNOWN
~~~

.. instead of, for example:

~~~
ps from procps-ng 3.3.12
~~~

Submit this as a bug to appropriate place, please!

**Comment by jcameron** [comment]
Could we handle this more gracefully in Webmin though?

**Comment by iliarostovtsev** [comment]
The fastest is just to swap it and make it work when there is no version returned?
https://github.com/webmin/webmin/commit/613f3a5f41fd094037629965e4cea1b815ac2b7d

**Comment by jcameron** [comment]
Sure, we can do that. Since only Redhat 5.x and lower have the old `ps` version, arguably we could drop it.

**Comment by iliarostovtsev** [comment]
I think we should. However, you never know.

**Comment by jcameron** [comment]
Anyway, simply inverting the test seems like the right solution for now.
