### ISSUE TITLE
Webmin showing 0 Running Processes After Upgrading to Ubuntu 20.04

### ISSUE THREAD

**Issue by squidds** [webmin/webmin#1237]
![Screenshot_20200506_160423](https://user-images.githubusercontent.com/64927214/81223216-a6e27b80-8fb3-11ea-9355-0189e34a65ae.png)

I upgraded to Ubuntu Server 20.04 from 18.04, the webmin repository was disabled afterwards, needed to re-install, now I have everything back up and running, but for some reason no running processes are showing. Please let me know if you need more information. Thank You.

[screenshot](https://i.imgur.com/DR8Rskc.png)

**Comment by iliarostovtsev** [comment]
Hi,

It was [fixed here](https://github.com/webmin/webmin/commit/613f3a5f41fd094037629965e4cea1b815ac2b7d).
