### ISSUE TITLE
BIND - dnssec-keygen not working after upgrade to Ubuntu 20.04

### ISSUE THREAD

**Issue by damienbkx** [webmin/webmin#1241]
Hello, 
After upgrading to Ubuntu 20.04, I have the following error when trying to generate dnssec keys for a zone in Bind9 using Webmin Bind module.

```
Failed to generate new zone key : dnssec-keygen: fatal: The -r option has been deprecated.
System random data is always used.
```

This error happens both when generating keys for a new zone AND when the cron job tries to update the DNSSEC key

Thanks,

**Comment by iliarostovtsev** [comment]
Hi,

It's been fixed already and will ship with upcoming Webmin 1.950.

Meanwhile, go to **BIND DNS Server Configuration** page, open **Zone file options** tab and change **Entropy source for DNSSEC keys** option to **/dev/random**.

**Comment by iliarostovtsev** [comment]
The fix is here:

https://github.com/webmin/webmin/commit/1bc262481db121138b031e533d903ab1782c1b22

**Comment by damienbkx** [comment]
Thanks a lot! 
Have a great day!
