### ISSUE TITLE
Perl execution failed - Can't use an undefined value as an ARRAY reference

### ISSUE THREAD

**Issue by Denis-Leblanc** [webmin/webmin#1242]
Hi,
I would be very interested to know how you resolved this issue:
> NEW ISSUE - In Record Generators module I getting following Error - Perl execution failed Can't use an undefined value as an ARRAY reference at /usr/share/webmin/bind8/list_gen.cgi line 39
https://github.com/webmin/webmin/issues/1220#issuecomment-601475336

Currently, I notice the same problem on a fresh installation of webmin 1.942
I did 3 times the installation, thinking I made some mistakes.

Could it be related, but I also noticed that the reverses no longer generate automatically when creating an Address record (A record).
The miniserv.error log file does not show any information that could help me resolve this problem.

I would be very fond of solving this penalizing problem.
Regards,
Denis LEBLANC

**Comment by jcameron** [comment]
I just checked in a fix for this, which you can see linked from this bug. It will be fixed in the next Webmin release.
