### ISSUE TITLE
Cookie Attribute httpOnly and Secure in ALL cookies

### ISSUE THREAD

**Issue by lerd2805** [webmin/webmin#1245]
Could you add the httpOnly and Secure attributes to all cookies that webmin creates?
Using OpenVAS to scan vulnerabilities informs me that the webmin service lacks to include these two attributes in all its cookies, effectively when the webmin login is opened, two redirect and testing cookies are created that lack these attributes.
I took the liberty of trying to correct it myself, but I didn't succeed.

I apologize for my horrible English, I hope you could help me or tell me how to correct this little detail so that they do not appear in the vulnerability scanner.

Best regards
![cookies](https://user-images.githubusercontent.com/31492754/84188239-e55ad280-aa58-11ea-8eef-3e9f342529ee.PNG)

**Comment by jcameron** [comment]
That's odd, the testing=1 secure cookie should be set in SSL mode already.

@iliaross , can you check if the session_login.cgi script in the authentic theme is doing this properly? It may be looking at the wrong environment variable to check for SSL mode.

**Comment by iliarostovtsev** [comment]
I made a [patch](https://github.com/authentic-theme/authentic-theme/commit/7d6b234966be108c047d2c81526ff4e520940bec) to address it. However, _HttpOnly_ should be on by default unless directive `no_httponly=1` set in `/etc/webmin/miniserv.conf` file.

**Comment by Bulmer** [comment]
I know this is 6 years old, but this issue is the only thing stopping my PCI-Compliance scans. Could someone please advise what to do to address this?

**Comment by iliaross** [comment]
Thanks for the heads-up! We will fully fix it in Webmin 2.670. If you want to give a patch a try, you can do it now.

```
webmin patch https://github.com/webmin/authentic-theme/commit/0780d7d
```

**Comment by Bulmer** [comment]
Ok, thanks. Where is authentic-lib.pl located?

**Comment by iliaross** [comment]
It depends on the system, just find it:

find / -iname authentic-lib.pl
