### ISSUE TITLE
Unable to use VirtualAdmin after installation

### ISSUE THREAD

**Issue by marvoh** [webmin/webmin#1246]
Hi,

I keep getting the error below after a fresh installation of VirtualAdmin and going through the post-installation wizard.

500 - Error - Perl execution failed
Can't kill a non-numeric process ID at ../web-lib-funcs.pl line 6313.

When I look at the file https://github.com/webmin/webmin/blob/master/web-lib-funcs.pl, line 6313 looks like a comment.

Any leads?

**Comment by iliarostovtsev** [comment]
What OS distro are you using there and how did you install Webmin?

**Comment by marvoh** [comment]
I am using  Ubuntu 18.04.4 LTS. 

I installed Webadmin from deb http://download.webmin.com/download/repository sarge contrib

**Comment by iliarostovtsev** [comment]
Please update to Webmin 1.942, it doesn't have such issue.

~~~
apt-get install -y wget && wget https://software.virtualmin.com/gpl/debian/dists/virtualmin-universal/main/binary-amd64/webmin_1.942_all.deb && apt-get install ./webmin_1.942_all.deb && /etc/webmin/restart && rm -f webmin_1.942_all.deb
~~~

**Comment by marvoh** [comment]
I had the same version running. 

Running your suggestion has yielded same result

**Comment by iliarostovtsev** [comment]
It should't be an issue. 

Try:

~~~
apt-get install --reinstall webmin
/etc/webmin/restart
~~~

**Comment by marvoh** [comment]
Do I need to be root or a sudoer is fine because I'm still facing the same challenge?

**Comment by marvoh** [comment]
It looks like it's something to do with ClamAV. When I deselected the option I was able to proceed past it in the wizard

**Comment by iliarostovtsev** [comment]
> Do I need to be root or a sudoer is fine because I'm still facing the same challenge?

Certainly! 

> It looks like it's something to do with ClamAV. When I deselected the option I was able to proceed past it in the wizard

I will not dare to guess any further of what you're doing.

I don't know any of our products currently named VirtualAdmin? :slightly_smiling_face: 

If you refer to Virtualmin, please make sure that you're installing it on clean, official, minimal instance of Ubuntu 18.04, [following these instructions](https://www.virtualmin.com/download.html).
