### ISSUE TITLE
Error - Perl execution failed /usr/share/webmin-1.941/bind8/list_gen.cgi line 39.

### ISSUE THREAD

**Issue by MBISWAS005** [webmin/webmin#1247]
HTTP/1.0 500 Perl execution failed Server: MiniServ/1.941 
GMT Content-type: text/html; Charset=iso-8859-1 Connection: close
Error - Perl execution failed
Can't use an undefined value as an ARRAY reference at /usr/share/webmin-1.941/bind8/list_gen.cgi line 39.

**Comment by iliarostovtsev** [comment]
Hi,

Thanks for the heads up. However, this bug has been [fixed already](https://github.com/webmin/webmin/commit/facae1009621cc9c408db9bef41c82b139b2f349#diff-fc6f2b628b05e33bd490a49eedc6b4ea) and the patch will be included in the upcoming Webmin release.
