### ISSUE TITLE
custom command with MIME Output not working with "Authentic theme"

### ISSUE THREAD

**Issue by ED-SD** [webmin/webmin#1250]
If a custom command is created that returns a file (MIME Type is set correctly) it will not work with the Authentic Theme. With other themes (which do not use AJAX) it works.

I attached a screenshot of the error in the console of my browser.
<img width="621" alt="Bildschirmfoto 2020-06-20 um 15 39 58" src="https://user-images.githubusercontent.com/50275136/85203207-65f8b900-b30c-11ea-837a-ac8f76bb45d3.png">

**Comment by iliarostovtsev** [comment]
Hi,

Returns a file for download?

How can I reproduce it?

**Comment by ED-SD** [comment]
Hi,

you have to define a command, that returns any data. For example simply "cat" a zip-file. See my example:
<img width="1195" alt="define_command" src="https://user-images.githubusercontent.com/50275136/85217580-c3cfe400-b392-11ea-8ab5-2ec56a5747b9.png">

When you execute the command with an non-AJAX-Theme it will start a download:
<img width="1111" alt="Bildschirmfoto 2020-06-21 um 07 44 25" src="https://user-images.githubusercontent.com/50275136/85217625-288b3e80-b393-11ea-9ef5-d5ae6d252a11.png">

When you do this with the Authentic theme, the GUI will crash because the error in my first screenshot.

I hope it helps?

**Comment by iliarostovtsev** [comment]
Good Lord - what is the real life, useful application of doing it??

**Comment by ED-SD** [comment]
We are using Raspberry PI in embedded solutions. Webmin is used as administration interface for field technicians. Very often they have to send a collection of logs and configuration-files to 2nd level supporters. Because they are not very familiar with IT-stuff, the idea is to provide a custom command which collects the necessary files and put them in a ZIP-files that will be downloaded.

So you see, a very real life application ;-)

**Comment by iliarostovtsev** [comment]
Fixed. That's the only way to make it work as I see it.

https://github.com/webmin/webmin/commit/d6362cfb1393293bfa0eb04d8731b47bc3fbbfa5
https://github.com/authentic-theme/authentic-theme/commit/4b0e6d09d334a069d4740a26abc5282569ec7b2b

Give it a try.

**Comment by iliarostovtsev** [comment]
@jcameron I think considering the way it works in SPA apps, it should be renamed to **Download when possible**:

![image](https://user-images.githubusercontent.com/4426533/85234105-c45c8f00-b413-11ea-8f54-5cb8edb28b71.png)

**Comment by iliarostovtsev** [comment]
@jcameron I think that's the only reliable way to make it work in SPA themes:

https://github.com/webmin/webmin/commit/15086f346cd1a75a38e3a93cc62b23934daa7db3

**Comment by iliarostovtsev** [comment]
Unless a user needs to play audio or video in browser, what would be there other benefit, that couldn't done by either _Show in Webmin UI_ or _Download when possible_ options to have MIME type? Should I add try audio/video support?

**Comment by iliarostovtsev** [comment]
Okay, quick tests show that it's possible to stream audio/video to browser, I just don't know if it's needed.

**Comment by ED-SD** [comment]
it works now! thanks for fixing
