### ISSUE TITLE
Treat "un-shared" certificate from LE as non-self signed

### ISSUE THREAD

**Issue by iliarostovtsev** [webmin/webmin#1251]
I had **ubuntu20.domain.com** with wildcard cert from Lets Encrypt. Later, I created, **server3.ubuntu20.domain.com** virtual-server, which automatically started sharing certificate (because **ubuntu20.domain.com** had ***.ubuntu20.domain.com** available). Now, I've chosen to "break certificate" (on its SSL Certificate page) for **server3.ubuntu20.domain.com** and it started using its own certificate from its home dir. The good thing here, that it still uses legit, _**copied from**_ original domain (**ubuntu20.domain.com**) certificate. It's all working and seems fine but the issue is that on the SSL Certificate page it says **Self-signed** - shouldn't that be fixed or it's expected? 

I will say it again - the certificate is not self-signed but legit, wildcard from Lets Encrypt.

![image](https://user-images.githubusercontent.com/4426533/85206508-47ee8100-b32b-11ea-987e-95777d342454.png)

**Comment by jcameron** [comment]
Odd that Virtualmin isn't showing ANY details of the cert, like the issuer. Does this domain pass validation?

**Comment by iliarostovtsev** [comment]
Okay, I see what the issue is here - permissions - if copied **ssl.*** certs have some other permissions and cannot be read you get this screen. Permissions must be set to current virtual-server's user upon copying it.

**Comment by jcameron** [comment]
Yes - I should add this to the validation check.

**Comment by iliarostovtsev** [comment]
I think we also need this - https://github.com/virtualmin/virtualmin-gpl/commit/266c664f58ba8eb5bcb70a7e53952719b5d8560b
