### ISSUE TITLE
Webmin is not showing cpu temps

### ISSUE THREAD

**Issue by sidboy55555** [webmin/webmin#1253]
Hello,
I've updated my system to a amd fx 8350, from a intel 1st generation xeon.
Before the upgrade, I had the cpu temps on my webmin dashboard, with lm-sensors.
After my upgrade and reinstallation, webmin won't show the temps of the cpu anymore.
I've followed these instructions to get the "cpu temperatures" in the side dashboard: https://github.com/authentic-theme/authentic-theme/issues/887
in the terminal with the command "sensors", I'm seeing the temps. but not in webmin. Is there a way to fix this?
Sorry for my english, it isn't my native langauge.
- Sidney

![SharedScreenshot](https://user-images.githubusercontent.com/9865110/85744495-3b8c6e80-b705-11ea-9da8-370cee5e6eff.jpg)
![SharedScreenshot2](https://user-images.githubusercontent.com/9865110/85744501-3c250500-b705-11ea-8151-62bd5ce0e7ed.jpg)

**Comment by jcameron** [comment]
Can you attach the output of the `sensors` command to this bug report as text?

**Comment by iliarostovtsev** [comment]
@sidboy55555 Please try this patch and see if it works for you - https://github.com/webmin/webmin/commit/beaef6869bf42261bc5c0074a3e4b470618691b0

**Comment by sidboy55555** [comment]
Hi!
@jcameron 
**:~# sensors
k10temp-pci-00c3
Adapter: PCI adapter
temp1:        +25.5 C  (high = +70.0 C)
                       (crit = +90.0 C, hyst = +87.0 C)

f71889a-isa-0480
Adapter: ISA adapter
+3.3V:        +3.33 V
in1:          +1.46 V  (max =  +2.04 V)
in2:          +1.66 V
in3:          +0.94 V
in4:          +1.09 V
in5:          +1.09 V
in6:          +1.21 V
3VSB:         +3.36 V
Vbat:         +3.31 V
fan1:        1986 RPM
fan2:        2215 RPM
fan3:        1758 RPM
temp1:        +43.0 C  (high = +85.0 C, hyst = +81.0 C)
                       (crit = +100.0 C, hyst = +96.0 C)  sensor = transistor
temp2:        +50.0 C  (high = +85.0 C, hyst = +79.0 C)
                       (crit = +107.0 C, hyst = +101.0 C)  sensor = thermistor
temp3:        +36.0 C  (high = +70.0 C, hyst = +68.0 C)
                       (crit = +85.0 C, hyst = +83.0 C)  sensor = transistor

nouveau-pci-0200
Adapter: PCI adapter
temp1:        +49.0 C  (high = +95.0 C, hyst =  +3.0 C)
                       (crit = +105.0 C, hyst =  +2.0 C)
                       (emerg = +135.0 C, hyst =  +5.0 C)

fam15h_power-pci-00c4
Adapter: PCI adapter
power1:      108.90 W  (crit = 125.19 W)**

@iliaross 
Sorry I'm not that advanced yet, could you explain a little bit how I patch that code into webmin?
(file /etc/webmin/proclinux-lib.pl doesn't exists?)

**Comment by jcameron** [comment]
Thanks, it looks like the format has changed from what Webmin expects - the next release will include a fix for this.

**Comment by sidboy55555** [comment]
I've found the file, and it worked!
only problem now is, that the core counts aren't displayed well. and it added one extra core temp somehow?
![photo_2020-06-27_18-21-21](https://user-images.githubusercontent.com/9865110/85926943-04ec5a80-b8a3-11ea-80cd-9afb8661fb25.jpg)

**Comment by iliarostovtsev** [comment]
Jamie, that's what theme does. As it's not cool to display core starting from 0.

This code https://github.com/webmin/webmin/commit/beaef6869bf42261bc5c0074a3e4b470618691b0#diff-eb3ebd7dec782750faa0dd3af34acb62R506 should **-1** on **$1**. Doing so, will make it start from **0** as in other outputs.

**Comment by sidboy55555** [comment]
> 
> 
> Jamie, that's what theme does. As it's not cool to display core starting from 0.
> 
> This code [beaef68#diff-eb3ebd7dec782750faa0dd3af34acb62R506](https://github.com/webmin/webmin/commit/beaef6869bf42261bc5c0074a3e4b470618691b0#diff-eb3ebd7dec782750faa0dd3af34acb62R506) should **-1** on **$1**. Doing so, will make it start from **0** as in other outputs.
My core counts indeed starts from 2, and goes up to 4. but when I use this proposed code everything will be 0.
![SharedScreenshot](https://user-images.githubusercontent.com/9865110/85927496-c35dae80-b8a6-11ea-8358-737223bf427c.jpg)

**Comment by iliarostovtsev** [comment]
How about:

~~~
'core' => (int($1)-1),
~~~

**Comment by sidboy55555** [comment]
> 
> 
> How about:
> 
> ```
> 'core' => (int($1)-1),
> ```

Yes this did the trick! thanks a lot. I hope this will be fixed automatically in future builds :)
![photo_2020-06-27_19-07-57](https://user-images.githubusercontent.com/9865110/85927932-8646eb80-b8a9-11ea-8a2d-0127fcdfdc17.jpg)

**Comment by iliarostovtsev** [comment]
Okay, considering that all other outputs start from **0** - it should be fine. 

Please give it another check.

https://github.com/webmin/webmin/commit/50d8f0a52718da670867c47f50a3583cf732661d

**Comment by iliarostovtsev** [comment]
Fixed.

**Comment by iliarostovtsev** [comment]
There was a bug actually - the output was incorrect.

Here is the patch to correct it. 

https://github.com/webmin/webmin/commit/3fa7141ae729dd0355f6050198b5a4771c7a28b3

**Comment by sidboy55555** [comment]
> 
> 
> There was a bug actually - the output was incorrect.
> 
> Here is the patch to correct it.
> 
> [3fa7141](https://github.com/webmin/webmin/commit/3fa7141ae729dd0355f6050198b5a4771c7a28b3)

After I updated webmin (few days ago), the panel also showed the temperature of other pci devices, this code fixes that problem.

**Comment by iliarostovtsev** [comment]
Good to know. Thanks!
