### ISSUE TITLE
Cannot edit fields without defining a default value

### ISSUE THREAD

**Issue by MmAaXx500** [webmin/webmin#1254]
I'm using MariaDB 10.3.22 and Webmin 1.941 on Debian 10.

Steps to reproduce:
1. Create a table: 
```sql
CREATE TABLE some_table (
some_field int NOT NULL
) 
```
2. Select `some_field` and just click `save` or try to edit without specifying a default value
3. You get this error message:
```Failed to save field : SQL alter table `some_table` modify `some_field` int(2) not null default NULL failed : Invalid default value for 'some_field'```
4. Run this SQL (No error and the table altered):
```sql
ALTER TABLE some_table 
MODIFY COLUMN some_field int(2) NOT NULL;
```

I think when the Save button is clicked all parameters passed to the query, not only the modified parameters.

**Comment by iliarostovtsev** [comment]
Hi,

Thanks for the heads up.

This has already been fixed for upcoming Webmin 1.950.
