### ISSUE TITLE
failed install module on webmin

### ISSUE THREAD

**Issue by cSarcasme** [webmin/webmin#1255]
Hi,

When i try to install a module in webmin it say that

Failed to install standard module : Module postfix requires Webmin version 1.950 or above

Butwhen i check for update webmin it say i have the latest version i dont understand

It do failed for another module i try to install.

My installation on webmin is a fresh install.

Ty for anyhelp of good dev.

Have a nice day ;)

**Comment by iliarostovtsev** [comment]
Hi,

The new 1.950 release is around the corner!

You can try [devel](http://download.webmin.com/devel/) build for now.

**Comment by cSarcasme** [comment]
but why the module ask for a version who is not fully active i don t understand

**Comment by iliarostovtsev** [comment]
Modules are automatically rebuilt by our build system. 

Meanwhile, you could manually download a module and tweak deps version number in **module.info** file.

**Comment by cSarcasme** [comment]
OK
is it the1.950 is stable or it is better to wait ?
ty for your answer

**Comment by iliarostovtsev** [comment]
The one you can download now is practically a release version. We're planning to release it in hours.
