### ISSUE TITLE
1.951 nor 1.952 does not automatically restart after update

### ISSUE THREAD

**Issue by gitarent** [webmin/webmin#1258]
After upgrading to 1.951, the webmin main page becomes unavailable. Explicitly starting webmin seems needed.
`sudo /etc/webmin/start`

**Comment by gitarent** [comment]
update  goes ok when using
`sudo yum update`
but did not (re)start webin when updating from webmin dashboard.

**Comment by jcameron** [comment]
Ok, this seems like a bug. How exactly did you upgrade Webmin from the UI?

**Comment by gitarent** [comment]
Same as usual - dashboard mentions 'package update is available', I click on it, webmin lists all updatables, I click "update selected packages', and confirm that I want the upgrades. Then webmin looses contact with server.  If I connect via ssh, I can start webmin and everything works again.

**Comment by gitarent** [comment]
1.952 still same problem...
![afbeelding](https://user-images.githubusercontent.com/12545481/86521598-57091f00-be53-11ea-82ed-39b16b3a3924.png)
![afbeelding](https://user-images.githubusercontent.com/12545481/86521609-6be5b280-be53-11ea-9c22-4d9f68abf1e0.png)
![afbeelding](https://user-images.githubusercontent.com/12545481/86521621-83bd3680-be53-11ea-8d63-e0a330a33a8e.png)

**Comment by iliarostovtsev** [comment]
From which version you were upgrading? Was it from 1.942?

What OS is that? CentOS 8 or Fedora Server?

**Comment by gitarent** [comment]
> From which version you were upgrading? Was it from 1.942?
From 1.951 and 1.950

> What OS is that? CentOS 8 or Fedora Server?
CentOS 8.2 and CentOS 7.8 (Ubuntu updates fine)

**Comment by iliarostovtsev** [comment]
We are working on fixing it..

**Comment by gitarent** [comment]
1.953 seems to fix this issue on all systems (CentOS 6.10, 7.8, 8.2, Ubuntu 20.04)

**Comment by iliarostovtsev** [comment]
Good to know, thanks for heads up.
