### ISSUE TITLE
CANT CREATE ACCOUNT

### ISSUE THREAD

**Issue by modestdavid** [webmin/webmin#1261]
please  i will like to create webmin account, cant find the link from the homepage.

**Comment by swelljoe** [comment]
What page do you mean?

**Comment by modestdavid** [comment]
https://doxfer.webmin.com/

**Comment by chris001** [comment]
You have to ask them to make you an account on the doxfer, and then, they will...

**Comment by swelljoe** [comment]
What's your email address @modestdavid ? You can send it to me via email or DM on the Virtualmin forums if you don't want to post it here. I need something so it can send you a temp password..

**Comment by modestdavid** [comment]
modest683@gmail.com

**Comment by swelljoe** [comment]
Done. You should receive an email with a password reset link. Thanks for offering to help out with the documentation! Let me know if you have any questions about editing or structure or whatever. It's running MediaWiki, so nothing weird.

**Comment by modestdavid** [comment]
ok thanks

**Comment by chris001** [comment]
@modestdavid 
You should edit your comment above (your email address), and remove your email address... to avoid receiving an avalanche of spam/junk/scams...

**Comment by modestdavid** [comment]
@chris001 
ok thanks
