### ISSUE TITLE
Custom commands menu items from script stopped working

### ISSUE THREAD

**Issue by simonnetxtra** [webmin/webmin#1262]
In upgrading webmin instances from 1.941 to 1.953, custom command Menu selections are not working as they were before. We used a Menu item to allow the selection of specific folders on the servers and defined these using the script notation by ending the entry with the | (pipe) character to signify script output. For example the input parameter would be type "Menu" with the following as the parameter:

ls /www/htdocs |

This works if you have a Text type, in that the various options are just output to a single text box, but Menu now longer displays anything.

**Comment by boschkundendienst** [comment]
I have exactly the same problem which completely messes up my custom created interface and we currently are not able to administrate our custom OTP solution. Any updates on this?
I upgrade today via my package manager to 1.953 and this messed things up.

I verified, that the commands creating the menu items work on the command line and there is no permission problem.

**Comment by iliarostovtsev** [comment]
You need [this patch](https://github.com/webmin/webmin/commit/a1ad0504f05cae7a14d5285b1ef288d95790f187#diff-8b9035807842a4e4dbe009f3f1478127) or you can install latest Webmin 1.954 from here:

~~~
https://download.webmin.com/devel/
~~~

**Comment by boschkundendienst** [comment]
> You need [this patch](https://github.com/webmin/webmin/commit/a1ad0504f05cae7a14d5285b1ef288d95790f187#diff-8b9035807842a4e4dbe009f3f1478127) or you can install latest Webmin 1.954 from here:
> 
> ```
> https://download.webmin.com/devel/
> ```

Good to know, it is in the works. Will keep an eye on it until it is in the normal repos. Thanks for your feedback.

**Comment by iliarostovtsev** [comment]
.. just apply the patch by adding few lines of code. There is no reason to wait, if you need this working now.

**Comment by simonnetxtra** [comment]
Thanks, update to 1.954 is working fine now
