### ISSUE TITLE
Feature Request - Network Ups Tools 'nut' support for any linux distribution

### ISSUE THREAD

**Issue by qaron84** [webmin/webmin#1264]
great work you guys, your panel works flawlessly but i would like to request a module addon for nut or Network Ups Tools. in your site there is a module but it needs to be updated.

**Comment by jcameron** [comment]
Wow, I haven't used a UPS for so long that I forgot I even developed that module! Given that, an update is unlikely at the current time..

**Comment by qaron84** [comment]
damn brother ups functionality is paramount for every system.. :(

**Comment by swelljoe** [comment]
[What year is it?](http://whatyearisit.info/img/what_year_is_it.jpg)
