### ISSUE TITLE
Switching to static from DHCP on RHEL results in "Name or service not known" error

### ISSUE THREAD

**Issue by iliarostovtsev** [webmin/webmin#1266]
When you try setting up static configuration using UI, all configs seems to be edited correctly on both CentOS 7 and 8. However, after applying configuration (or rebooting) the network becomes unreachable. (command `ping google.com` doesn't work, returning an error).

The source of the problem is in edited `/etc/sysconfig/network-scripts/*` file that is missing **GATEWAY** directive. Adding it manually and restarting networking service fixes an issue.

Webmin should add it, I bet!?

**Comment by jcameron** [comment]
How did you set the default route in Webmin when switching to a static IP?

**Comment by iliarostovtsev** [comment]
I simply did most expected thing - I went to **Network Configuration/Edit Bootup Interface** and changed DHCP to static, setting up IP and a mask.

![image](https://user-images.githubusercontent.com/4426533/87856457-fdf7bb80-c927-11ea-8496-c879e09a8871.png)

**Comment by iliarostovtsev** [comment]
> How did you set the default route in Webmin when switching to a static IP?

I didn't do anything else on Webmin side. I thought, once I'm editing an interface it should be on the same page, once it wasn't there, I simply had to edit a file to make it work, by adding **GATEWAY** directive.

**Comment by iliarostovtsev** [comment]
It's unclear, why we don't have a field to set a gateway? We even have a broadcast but not gateway.

**Comment by chris001** [comment]
Yes, it appears to not be handling the `gateway` address!

**Comment by jcameron** [comment]
That page does set the gateway though - instead it's set on the "Routing and Gateways" page, because usually the gateway is independent of the interface.  The downside though is that changing from DHCP to a static IP requires visiting both pages.

**Comment by iliarostovtsev** [comment]
Couldn't we automate this somehow easily, when switching from DHCP to static?

**Comment by jcameron** [comment]
Maybe, by copying the existing gateway that was provided by DHCP and making it static..

**Comment by iliarostovtsev** [comment]
Yes, anything reasonable and fail proof that would not leave system unreachable. Unfortunately not everyone would know to configure gateway and UI must not trick users into creating error prone configurations, requiring knowledge into configuring it on more than a single page. I must say I like **Network Configuration** module and **Routing and Gateways** - all is done right. It's just not too straight forward for a normal user.

**Comment by jcameron** [comment]
Ok, I've checked in a change to do this.
