### ISSUE TITLE
Linux firewall page not loading after upgrade from version 1.950

### ISSUE THREAD

**Issue by EgyCodePro** [webmin/webmin#1268]
I'm having annoying issue sine previous update, I'm not sure its the 1.9.50 or after but the issue is when I click the Linux firewall  and Linux IPv6 firewall links under Networking tab the page continue loading forever and the server CPU load becomes high sometimes it hit 100%

I check for the running process and I can see running process with this command "iptables-restore --test" and there is another process related to it also, "sh -c (iptables-restore --test </etc/sysconfig/iptables 2>&1)", i tried to search for in log for iptables and searched for any message in journald log files but I can't find any log for that!

I tried to run this command from SSh terminal and it just start and don't return any data! just blank line after hitting enter!

Any idea how to solve this issue as I think it's iptables bug when running the command, I also removed all saved iptables rules in /etc/sysconfig/iptables and ip6tables rules but still have the same issue!

Thanks.

**Comment by iliarostovtsev** [comment]
https://github.com/webmin/webmin/commit/3db98c7a2de21147753f2c28da9c39a6a9b84629

**Comment by EgyCodePro** [comment]
I edited the file but I still have the same issue! please reopen the thread or how to report this as a bug?

**Comment by jcameron** [comment]
So is your issue that the page never loads, or that it just appears empty (no rules shown) ?

**Comment by EgyCodePro** [comment]
> So is your issue that the page never loads, or that it just appears empty (no rules shown) ?

Yes the page never loads, it just show loading red line/bar in the header!

**Comment by jcameron** [comment]
How about the IPv4 firewall page .. does that work?

**Comment by EgyCodePro** [comment]
> How about the IPv4 firewall page .. does that work?

Both IPv4 and IPv6 have the same issue! Thank you for your reply!

**Comment by jcameron** [comment]
Ok I think I know the issue - wait a bit for Webmin 1.954, which will fix this.

**Comment by EgyCodePro** [comment]
> Ok I think I know the issue - wait a bit for Webmin 1.954, which will fix this.

Thank you for your reply, do you have a temp. fix for this untill the official release!

**Comment by jcameron** [comment]
Yes, try this patch : https://github.com/webmin/webmin/commit/3db98c7a2de21147753f2c28da9c39a6a9b84629

**Comment by EgyCodePro** [comment]
I already tried this but it didn't fix the issue! This seems to fix the iptables-save command issue, my problem is with iptables-restore --test command!

> Yes, try this patch : [3db98c7](https://github.com/webmin/webmin/commit/3db98c7a2de21147753f2c28da9c39a6a9b84629)

**Comment by EgyCodePro** [comment]
Unfortunately I'm not familiar with cgi scripting language so I just commented out this line in index.cgi in both firewall and firewall6 folders

# my $err = &validate_iptables_config();

This disabled the iptables-restore --test command for both ipv4 and ipv6 firewall pages!

**Comment by jcameron** [comment]
Seems like maybe the currently saved config is invalid.

Does anything get logged to `/var/webmin/miniserv.error` when that line is put back?

**Comment by EgyCodePro** [comment]
I looked into this file and the only log related to iptables-restore command is when I terminate the process!

sh: line 1: 809692 Terminated              ( iptables-restore --test < /etc/sysconfig/iptables 2>&1 )

Where to check for the config data which you have mentioned in your last reply!

> Seems like maybe the currently saved config is invalid.
> 
> Does anything get logged to `/var/webmin/miniserv.error` when that line is put back?

**Comment by jcameron** [comment]
The config file is `/etc/sysconfig/iptables`

What happens if you SSH in as `root` and run : `iptables-restore --test < /etc/sysconfig/iptables`

**Comment by EgyCodePro** [comment]
Thank you, if I run this command via webmin command shell page the page just start load and don't return anything even after minutes, so I think its iptables issue not webmin!

Is there any idea how to downgrade iptables previous version?


> The config file is `/etc/sysconfig/iptables`
> 
> What happens if you SSH in as `root` and run : `iptables-restore --test < /etc/sysconfig/iptables`

**Comment by EgyCodePro** [comment]
Is there any log files for iptables and ip6tables?
