### ISSUE TITLE
Status mail wrong translation

### ISSUE THREAD

**Issue by DrCarsonBeckett** [webmin/webmin#1272]
When I get the a mail that the backup of virtualmin is done (via webmin), I receive a status mail about it.
In that mail, there is an issue with the "ö ä ü ß" and so on, meaning with umlaut from the german language.
> Die GesamtgrÃ¶ÃŸe betrÃ¤gt

It should be displayed as:
> Die Gesamtgröße beträgt

I think it appeared after the with update which enabled webmin and virtualmin to be updated through virtualmin/webmin itself (webpanel).

System:
Debian 10
Webmin-Version | 1.953 |
Usermin-Version | 1.802
Virtualmin Version | 6.10 |
Authentic theme version | 19.53

**Comment by jcameron** [comment]
Looks like possibly an encoding issue with the email. If you check the email headers, what character is shown in the Content-type: header?

**Comment by iliarostovtsev** [comment]
Considering that we have it written right in the language file at the first place:

![image](https://user-images.githubusercontent.com/4426533/88488065-6df2eb00-cf93-11ea-8eb3-90f53dd91909.png)


.. it seems the real issue is somewhere else ..

**Comment by DrCarsonBeckett** [comment]
Thats what I expected and thats why I am a bit confused to see it like that.
The headers are:

> Content-Type: text/plain;
	boundary="bound1595715095";
	charset="iso-8859-1"

**Comment by DrCarsonBeckett** [comment]
Same is with the status mails for renewed certificates.

**Comment by iliarostovtsev** [comment]
Can you please try applying this patch?

https://github.com/webmin/webmin/commit/00c1f1410ca45abd4fb0623b44d0211d4183cb60

**Comment by DrCarsonBeckett** [comment]
I will report back as soon as I get a new mail.

**Comment by DrCarsonBeckett** [comment]
I dont receive any status notifications via mail currently, which is a bit odd.
Tested in on a new installation too, where I restored the backup.

**Comment by DrCarsonBeckett** [comment]
Still the same after the patch you mentioned @iliaross .

**Comment by iliarostovtsev** [comment]
Can you download an email and send it to me raw, so I could reproduce an issue locally?

**Comment by DrCarsonBeckett** [comment]
How do you like me to send it to you?
I graped now one directly from the server, hope thats what you meant.

**Comment by iliaross** [comment]
You could _zip_ it and _drag and drop_ here, unless there is any private data in it. You could use [my web-site's](https://iliaross.io) form to submit a download link as well.

**Comment by DrCarsonBeckett** [comment]
You should have a message now.

**Comment by iliarostovtsev** [comment]
> Still the same after the patch you mentioned 

You need to make sure that you applied patch correctly. 

> You should have a message now.

Yes, I got it. It appears that the message itself is broken at the first place.

What is the original text that you add? Is this for status monitoring?

**Comment by iliarostovtsev** [comment]
Oh, I see what should be done.

**Comment by DrCarsonBeckett** [comment]
> You need to make sure that you applied patch correctly.

```
local $attach = $body =~ /^[\000-\177]*$/ ?
        { 'headers' => [ [ 'Content-type', 'text/plain' ] ],
          'data' => &entities_to_ascii($body) } :
        { 'headers' => [ [ 'Content-Type', 'text/plain; charset='.$cs ],
                         [ 'Content-Transfer-Encoding', 'quoted-printable' ] ],
          'data' => &quoted_encode($body) } :
        { 'headers' => [ [ 'Content-type', 'text/plain' ] ],
          'data' => &entities_to_ascii($body) };
          'data' => &quoted_encode($body) };
```
Thats how the code looks after the patch, its the same as mentioned in the link.





> What is the original text that you add? Is this for status monitoring?
What precisely do you mean? I just enabled that I receive a mail at the end of the backup.

**Comment by iliarostovtsev** [comment]
Okay, to double check - what is the source of the issue? Where is mail being sent from and where exactly do you see it broken? I haven't found anything specific on the config. What words get broken in particular? 

Besides, on my side outgoing mail works correctly and nothing gets encoded using _iso-8859-1_?

**Comment by iliarostovtsev** [comment]
Okay, so you're sending mail from _Read Mail_ module?

**Comment by iliarostovtsev** [comment]
Check this patch https://github.com/webmin/webmin/commit/43a86a8680b3bb5c59df116628202f4f4941a206 as well there should no other way you could have mail generated with ISO-8859-1.

**Comment by DrCarsonBeckett** [comment]
I am not sure, I only enabled the "Sending Email" from "Webmin Configuration" because I wanted to have mail alerts about unplanned and planed changes, as well for other reports.

Words which are broken:
GesamtgrÃ¶ÃŸe -> Gesamtgröße
abschlieÃŸen -> abschließen
fÃ¼r -> für
and so on.

Basically everything with umlauts "ö, ä, ü" and "ß".

> Check this patch [43a86a8](https://github.com/webmin/webmin/commit/43a86a8680b3bb5c59df116628202f4f4941a206) as well there should no other way you could have mail generated with ISO-8859-1.

I changed the code like you suggested and currently I am doing a backup something which should trigger a mail.

**Comment by iliarostovtsev** [comment]
Okay,

At them moment, check, If you send test mail manually, does it get received with broken chars?
![image](https://user-images.githubusercontent.com/4426533/88922723-2c0ac300-d279-11ea-8e80-b99cb15d6218.png)

**Comment by DrCarsonBeckett** [comment]
If I manually send a mail from to it, then it gets displayed fine.
Just received the report mail and its still broken.


> At them moment, check, If you send test mail manually, does it get received with broken chars?
If I want to do that, I get this error:
`
.. sending failed : Undefined subroutine &mailboxes::send_text_mail called. 
`

**Comment by iliarostovtsev** [comment]
It's unclear why this is happening. Can you add `error_stack=1` to `/etc/webmin/config`, restart Webmin and try again? Can you provide a screenshot of a page where it's happening?

**Comment by DrCarsonBeckett** [comment]
I attached the screenshots and I added the line to the config.
![2020-07-30_16h55_21](https://user-images.githubusercontent.com/38506927/88939086-6cbd0900-d286-11ea-8b59-2674ab18b74b.png)
![2020-07-30_16h55_13](https://user-images.githubusercontent.com/38506927/88939091-6d559f80-d286-11ea-81e9-67518cc27b7a.png)

**Comment by iliarostovtsev** [comment]
It seems that you have mis-edited the file. 

Try updating it again, it will include my patch too:

~~~
curl https://raw.githubusercontent.com/webmin/webmin/master/mailboxes/boxes-lib.pl -o /usr/share/webmin/mailboxes/boxes-lib.pl
~~~

**Comment by DrCarsonBeckett** [comment]
Seems to work now.

**Comment by DrCarsonBeckett** [comment]
Just received a new mail from the backup and there's still the problem.

**Comment by DrCarsonBeckett** [comment]
Its still happening, not every time but its still happening. 😕

**Comment by iliarostovtsev** [comment]
If you try opening the same email that fails in Usermin in Thunderbird or Outlook - does it get displayed correctly? It's possible that email encoding is broken on the message itself.

If you switch to Gray Theme, what results do you have? Broken the same way?

**Comment by DrCarsonBeckett** [comment]
It gets displayed wrong at Usermin and Outlook (2019). Odly, it gets displayed correctly in iOS with the default mail app.
Switching the theme didn't change anything sadly.

**Comment by iliaross** [comment]
Could you download this email with broken chars and send it to me to _support аt iliaross dоt io_?

**Comment by DrCarsonBeckett** [comment]
I just sent it.

**Comment by iliarostovtsev** [comment]
Okay. Look - email message itself is encoded in `utf-8` but content type headers say this

~~~
Content-Type: text/plain;
	boundary="bound1598739080";
	charset="iso-8859-1"
~~~

I don't think it's right. Can you try this patch please? https://github.com/virtualmin/virtualmin-gpl/commit/d2f46ca7214f966b22c32337050d298cee82b5e1

**Comment by DrCarsonBeckett** [comment]
I did patch it by replaing the file with the one from the github repo. Seemed more reliable to me. I am currently letting a backup run in the background to see if it worked. But I assue, to be on the safe side, I need to wait till the next scheduled one is done (sunday morining at 00:05).

**Comment by iliarostovtsev** [comment]
For this patch to work you would need to restart Webmin with `/etc/webmin/restart`.

**Comment by DrCarsonBeckett** [comment]
I did, but it didn't seem to fix it.

**Comment by iliarostovtsev** [comment]
Okay, I will take a close look.

**Comment by DrCarsonBeckett** [comment]
Thanks again.

**Comment by DrCarsonBeckett** [comment]
I applied the fixes from https://github.com/webmin/usermin/issues/62 but currently it's still not working or did I misunderstood the last comment from @iliaross ?

**Comment by iliarostovtsev** [comment]
You need to have latest theme applied and these fixes installed to **../usermin/mailbox**:

https://raw.githubusercontent.com/webmin/webmin/master/mailboxes/mailboxes-lib.pl
https://raw.githubusercontent.com/webmin/usermin/master/mailbox/mailbox-lib.pl

**Comment by DrCarsonBeckett** [comment]
Latest theme would be 19.61 right?

**Comment by iliarostovtsev** [comment]
Yes.

**Comment by DrCarsonBeckett** [comment]
Hmm, I get this error now:
> Error:  500 - Perl execution failed – Undefined subroutine &extensions::decode_utf7 called

After I did apply the patches via:
> curl https://raw.githubusercontent.com/webmin/webmin/master/mailboxes/mailboxes-lib.pl -o /usr/share/webmin/mailboxes/mailboxes-lib.pl
> curl https://raw.githubusercontent.com/webmin/usermin/master/mailbox/mailbox-lib.pl -o /usr/share/usermin/mailbox/mailbox-lib.pl
> /etc/init.d/webmin restart
> /etc/init.d/usermin restart

Do I have a spelling mistake somewhere or whats the issue?

Edit:
> 500 - Undefined subroutine &mailbox::decode_utf7 called at ./mailbox-lib.pl line 573.

@iliaross Thats the precise error I receive ones I log into usermin with the mail.

**Comment by iliarostovtsev** [comment]
We're about to release Webmin 1.962 and Usermin 1.811, which are going to include these patches. Within few days, as you install updates, please come back to us sharing how it works for you.

**Comment by DrCarsonBeckett** [comment]
As soon as I am able to get the versions, I will test it and report back.

**Comment by DrCarsonBeckett** [comment]
Works good now. Not sure why it didn't before but thanks again.

**Comment by iliarostovtsev** [comment]
Can you please send me `/etc/webmin/mailboxes`, `/etc/webmin/webmin` and `/etc/usermin/mailbox` dirs archives?

Are you sure that you're running latest Webmin 1.962 and Usermin 1.812? And Virtualmin 6.13? I really cannot reproduce this issue. All messages just come in with right encoding and charset.

Besides, add to the archive the message as it is stored on the disk in `~/Maildir/cur` folder.

**Comment by iliarostovtsev** [comment]
I just ran few tests and backup notification emails looks like this:

~~~
Return-Path: <webmin@debug-debian10-pro.localdomain>
X-Original-To: debian10-pro@debian10-pro
Delivered-To: debian10-pro@debug-debian10-pro
Received: by debug-debian10-pro.local (Postfix, from userid 0)
	id 49F4F27418; Tue,  1 Dec 2020 15:32:13 +0200 (EET)
From: webmin@debug-debian10-pro.localdomain
Subject: Sicherung von Virtualmin auf debug-debian10-pro.localdomain abgeschlossen
To: debian10-pro@debian10-pro
Date: Tue, 01 Dec 2020 15:32:13 +0200 (EET)
Message-Id: <1606829533.6666.2@debug-debian10-pro.localdomain>
MIME-Version: 1.0
Content-Type: multipart/mixed; boundary="bound1606829533"

This is a multi-part message in MIME format.

--bound1606829533
Content-type: text/plain

Erzeuge Backup für den virtuellen Server debian10-pro ..
    Kopiere Virtuelle Server Konfiguration ..
    ... Fertig!

    Sichern von Cron-Jobs ..
    .. nicht definiert.

    Kopiere DNS-Einträge für die Domaine ..
    ... Fertig!

    Sichere E-Mail-Aliase ..
    ... Fertig!

    Sichere E-Mailboxbenutzer ..
    ... Fertig!

    Sichere Mail und FTP Benutzer Cron Jobs ..
    .. nichts zum sichern

    Kopiere Konfiguration der virtuellen Apacheserver ..
    ... Fertig!

    Kopiere Apache Log Dateien ..
    ... Fertig!

    Kopiere SSL Apache Virtuelle Server Konfiguration und Zertifikat ..
    ... Fertig!

    Kopiere Logrotate-Konfiguration ..
    ... Fertig!

    Sichere MySQL-Datenbank debian10_pro ..
    ... Fertig!

    Sichere MySQL-Datenbank debian10_pro_mautic ..
    ... Fertig!

    Erzeuge TAR-Datei vom Home-Verzeichnis ..
    ... Fertig!

.. fertig in 9 Sekunden


Von Virtuelmin um https://debian10-pro:10000 gesendet

--bound1606829533--


~~~

**Comment by iliarostovtsev** [comment]
.. additionally by any chance, do you have anything related on the following file:

~~~
/etc/postfix/header_checks
~~~

**Comment by DrCarsonBeckett** [comment]
That's odd indeed.

I am positive that I am on the latest versions:
Webmin-Version | 1.962
Usermin-Version | 1.812
Virtualmin Version | 6.14
Authentic theme version | 19.62

And I don't got that file in the postfix dir under /etc .
I just send the archives to the same mail from the last time, I just removed the RSA keys, certs and acl because of sensitive data.

**Comment by iliarostovtsev** [comment]
Just to summarize - the issue is that your scheduled backups when run sends you broken status email message? Is there a way for you to attach this message in raw? You can get this from `~/Maildir/cur` or whatever location you store your mail in.

**Comment by DrCarsonBeckett** [comment]
That is correct. I just checked the mail in raw. When I watch it in usermin in raw, it's displayed wrong.
If I check it directly in SSH or download it, then its displayed correctly.
I can send the archive containing the file, but I trust you to keep the information in it private. Thanks.

**Comment by iliarostovtsev** [comment]
Based on the message headers - it's mailed by Microsoft Outlook and received by Postfix? This is confusing to me. Can you tell us more about your setup? 

What adds these wrong headers?

~~~
Content-Type: text/plain;
	boundary="bound0000000000";
	charset="iso-8859-1"
~~~

**Comment by DrCarsonBeckett** [comment]
I don't know what adds those and I pretty much use the out of the box virtualmin setup. I use dovecot with postfix for mails and let procmail run as a filter with spamassassin.
I didn't add something extra to the mail setup and didn't change something in that regard, except a few options given by virtualmin/webmin.
Is there an option to set specific charsets?

**Comment by iliarostovtsev** [comment]
What role Microsoft Outlook plays here?

**Comment by DrCarsonBeckett** [comment]
It's my desktop mail client. From what I read, Outlook likes to change the x-mailer header.

**Comment by iliarostovtsev** [comment]
How did you extract that message you previously sent me? It looks that the message is being sent from one machine to another, as it's being DKIM signed?

Look, Postfix delivers mail locally (unless setup otherwise). The message with Virtualmin backup report, should drop to your mailbox. If it's an external mailbox, please make sure to deliver it to local address, let's say `root` for testing purposes. Then go to **Webmin > Servers > Read User Mail** and see and download a message from there.

**Comment by DrCarsonBeckett** [comment]
I enabled DKIM via webmin. I copied the mail via cp (directly per SSH) to a folder where I got ftp access to, downloaded it, zip'ed it and send it to you.
I already checked the function you told me, like I said its displayed wrong there and I can't download a message from there. :-/

**Comment by iliarostovtsev** [comment]
Can I just login and see what's happening?

If not, do the following - set my email address for **Email backup report to** field and let it to be sent to me upon backup. I wanna see it.

**Comment by DrCarsonBeckett** [comment]
I just did it, the mail should arrive any moment or the following minutes.

**Comment by iliarostovtsev** [comment]
Danke! Received it - the email is perfectly fine, as I expected it! 🙂 

I will forward it to you for analysis! 😉

**Comment by iliarostovtsev** [comment]
I assume you need to check the configuration for your Microsoft Outlook.
