### ISSUE TITLE
lets encrypt

### ISSUE THREAD

**Issue by cSarcasme** [webmin/webmin#1273]
Hi,
let s encrypt work but when i try to connect it is say wrong certificat.

In let' s encrypt the domain i need to put is my domain:10000 because i just put mydomain with no:10000.

i have use this tutorial: https://www.digitalocean.com/community/tutorials/how-to-install-webmin-on-ubuntu-20-04

i am on debian 10 buster.

ty for any help

**Comment by iliarostovtsev** [comment]
Hi,

Webmin has its own web server, called _miniserv_. It has its own configuration, requests and loads requested certificates automatically. For _Apache_, you would have to configure it manually under each _VirtualHost_, with certificate that was requested. If you want this to be done automatically, you would need to use [Virtualmin](https://www.virtualmin.com/download.html) module.

**Comment by cSarcasme** [comment]
i have configure manualy like the link tutorial explain

but it doesn t work i don t understand why the encrypt work it say succeed.

before i have configure a virtualhost for apache for the domain lahordedesjoueurs.fr

and put  a alias i hosts like

myip ns254895.lahordedesjoueurs.fr lahordedesjoueurs.fr

the hosname: lahorde des joueurs.fr

my virtualhost: 

<VirtualHost *:80>
    ServerAdmin lahordedesjoueurs@gmail.com
    ServerName ns254895
    ServerAlias www.lahordedesjoueurs.fr
    DocumentRoot /var/www/lahordedesjoueurs.fr
    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>
when i connect to ns254895:10000

 SSL_ERROR_BAD_CERT_DOMAIN

**Comment by cSarcasme** [comment]
why close it dont want install virtualmin and it don t resolve my problem

**Comment by iliarostovtsev** [comment]
> when i connect to ns254895:10000

What happens if you connect using IP address, certificate will be displayed as invalid but if you check on certificate details in the browser, will you get the expected certificate reported back?

**Comment by cSarcasme** [comment]
yes it say the certificat is for la hordedesjoueurs.fr and not yourdomain:10000

**Comment by iliarostovtsev** [comment]
I am sorry. I don't see any issues in Webmin functionality in this regard. It requests certificate for _miniserv_ web-server, updates its config files and make it available for chosen and configured domain (in case web-server (Apache) and DNS (BIND) are configured correctly).

Considering the nature of your questions, I would highly recommend using Virtualmin, by installing it using [official install script](https://www.virtualmin.com/download.html) - it will do all the work for you!

This is the _Issue Tracker_ and not _Question and Answer_ portal.

You are welcome to try to address your question to [Virtualmin Forums](http://forum.virtualmin.com/).
