### ISSUE TITLE
Send test mail error

### ISSUE THREAD

**Issue by DrCarsonBeckett** [webmin/webmin#1274]
When I want to enable the "monitoring" for scheduled backups and other changes in the "webmin configuration -> sending email" I can select options, but when I pres save then it doesnt get saved.
Additionally, when I want to send a test mail, I get this error:

> Undefined subroutine &mailboxes::send_text_mail called. 

Operating system | Debian Linux 10
Webmin version | 1.953
Usermin version | 1.802
Virtualmin version | 6.10
Authentic theme version | 19.53

Additional information can be provided if necessary.

**Comment by DrCarsonBeckett** [comment]
I assume thats the reason why I dont receive email alerts. 😞

**Comment by iliarostovtsev** [comment]
> Undefined subroutine &mailboxes::send_text_mail called.

That makes no sense. Based on the previous issue you're submitted, are you sure that you correctly edited file and applied the patch?

**Comment by DrCarsonBeckett** [comment]
`local $attach = $body =~ /^[\000-\177]*$/ ?
        { 'headers' => [ [ 'Content-type', 'text/plain' ] ],
          'data' => &entities_to_ascii($body) } :
        { 'headers' => [ [ 'Content-Type', 'text/plain; charset='.$cs ],
                         [ 'Content-Transfer-Encoding', 'quoted-printable' ] ],
          'data' => &quoted_encode($body) } :
        { 'headers' => [ [ 'Content-type', 'text/plain' ] ],
          'data' => &entities_to_ascii($body) };
          'data' => &quoted_encode($body) };`

Thats how the code looks after the patch. I restarted webmin, usermin, dovecot and postfix after that.

**Comment by iliarostovtsev** [comment]
Can you email me the complete `/etc/webmin` folder?

**Comment by DrCarsonBeckett** [comment]
I can do that. I will message you the download link via your website again.

**Comment by DrCarsonBeckett** [comment]
You should have a mail now, thanks again!

**Comment by iliarostovtsev** [comment]
I got it but it doesn't contain data in folders.

**Comment by DrCarsonBeckett** [comment]
My bad, I forgot the "-r". It should be fine now, the link is the same.

**Comment by DrCarsonBeckett** [comment]
~~~
curl https://raw.githubusercontent.com/webmin/webmin/master/mailboxes/boxes-lib.pl -o /usr/share/webmin/mailboxes/boxes-lib.pl
~~~

Worked with that patched file.
