### ISSUE TITLE
Postfix bind issue

### ISSUE THREAD

**Issue by DrCarsonBeckett** [webmin/webmin#1275]
I had an issue with Postfix on my old installation. Since I wanted to reinstall it anyways, I did so. It worked fine and after I restarted the VPS ones, it stopped working. It might have not worked properly in the beginning.
The problem is that postfix didnt wanted to start, even though systemctl status postfix said its up.
A quick check from the log files revealed the issue: 

> postfix/master[843]: fatal: bind IP.IP.IP.IP port 465: Address already in use

I checked with netstat, but it actually there wasnt anything bound to it. I had a friend check it with me and he noitced the following issue (after a "google" search).
Postfix had this in the master.cf:

> #smtps  inet    n       -       y       -       -       smtpd -o syslog_name=postfix/smtps -o smtpd_tls_wrappermode=yes -o smtpd_sasl_auth_enable=yes -o smtpd_reject_unlisted_recipient=no -o smtpd_client_restrictions=$mua_client_restrictions -o   smtpd_helo_restrictions=$mua_helo_restrictions -o smtpd_sender_restrictions=$mua_sender_restrictions -o smtpd_recipient_restrictions= -o smtpd_relay_restrictions=permit_sasl_authenticated,reject -o milter_macro_daemon_name=ORIGINATING

Which is fine, the problem is that webmin edited additional binds for smtps at the end of the file.
I am not sure why this happened, but I never toucht the postfix main.cf or in that regard, any postfix files. 

We commented that line out and edited the binds, after a restart postfix was online again and could deliver mails.

I can provide log files if necessary.

System:
Debian 10
Webmin-Version | 1.953 |
Usermin-Version | 1.802
Virtualmin Version | 6.10 |
Authentic theme version | 19.53

**Comment by iliarostovtsev** [comment]
Hi,

Simply try:

~~~
pkill -9 master
~~~

**Comment by DrCarsonBeckett** [comment]
I tried that, didnt help. It works fine now. Just wanted to report that if its an isssue. If its was just a hickup on my server, then its fine too.

**Comment by iliarostovtsev** [comment]
Ah, okay. You're saying that Webmin mis-edited something?

How do we reproduce it?

**Comment by DrCarsonBeckett** [comment]
That I am not sure, thats the thing. I noticed that on my old installation and reinstalled because of that (couldnt fix it back then).
Since it happend on my new installation too, I reported it.
I did the following for the installation.

> Installed Debian 10 minimal
> apt install apt-transport-https
> Added the debian apache repo from sury, same for the php repo.
> apt update
> apt upgrade
> Installed virtualmin with a preseted FQDN (command line argument)
> Enabled clamav, preloading and the other thing which you can enable after you login the first time (first login wizard or something).
> Restored my virtualmin configuration backup
> Restored domains

After that I did the mentioned restart.

**Comment by iliarostovtsev** [comment]
What you are reporting was fixed by me for Virtualmin 6.10.

Is this possible that you have restored from the backups some old and broken configs?

**Comment by DrCarsonBeckett** [comment]
I restored a config via the restore function which was used before 6.10 was released. I updated the installation (previous) to 6.10.
I guess it got transfered then.
Thanks for the heads up!
