### ISSUE TITLE
impossible to connect in IMAP mode to Dovecot since last v1.954

### ISSUE THREAD

**Issue by Productivix** [webmin/webmin#1276]
hi, 
I used to collect my emails with Thunderbird in STARTTLS normal password mode up to the 1.953, I upgraded today in 1.954 and no more connection possible. No error message in logs. only a message in Thunderbird that says that the connexion is refused.
How to find the issue please ?
 thank you.
William

**Comment by chris001** [comment]
1. Click Webmin, 
2. System, 
3. System Logs, 
4. View log file,
5. `/var/log/dovecot/dovecot.log`

This will show you the error messages for logging into `Dovecot IMAP server`.

**Comment by chris001** [comment]
Ultra-loose Security bugs in Dovecot configuration in webmin were fixed recently, so probably your Dovecot configuration needs a slight tweak or adjustment to get it to work smoothly.  The error messages will provide information necessary to pinpoint the cause of your Thunderbird email app's login error.

**Comment by iliarostovtsev** [comment]
> Ultra-loose Security bugs in Dovecot configuration in webmin were fixed recently,

I am sorry, Chris, but what bug are you referring to?

**Comment by saisie-mobile** [comment]
hi, 
For logs, it depends of the dovecot config, in my case the logs are spread on many logs : the following command gives it : 
# doveadm log find
Looking for log files from /var/log
Debug: /var/log/syslog
Debug: /var/log/mail.log
Info: /var/log/syslog
Info: /var/log/mail.info
Info: /var/log/mail.log
Warning: /var/log/mail.warn
Warning: /var/log/syslog
Warning: /var/log/mail.info
Warning: /var/log/mail.log
Error: /var/log/mail.warn
Error: /var/log/syslog
Error: /var/log/mail.info
Error: /var/log/mail.err
Error: /var/log/mail.log
Fatal: /var/log/mail.warn
Fatal: /var/log/syslog
Fatal: /var/log/mail.info
Fatal: /var/log/mail.err
Fatal: /var/log/mail.log

This is not an issue.

To debug : I placed in dovecot.conf  :
auth_debug=yes
and in var/log/syslog I found that my login does not exist for dovecot with the command:
# doveadm user info@mydomain
answers : 
field	valueuserdb lookup: user info@mydomain doesn't exist

The questions are : 
- how with a such "minor upgrade" of Webmin, can the Dovecot system being not usable at that stage ?
- how can I add my users that worked before to this Dovecot please ?
thanks 
William

**Comment by saisie-mobile** [comment]
Ok , I correct the thing by reconfiguring manually point per point (I had a very old installation, up to date put with heritance ).
The ultra loose security is from Thunderbird v68 that will accept a certificate from a serveur named "toto" even if you say that you connect to "titi" (!) - the version 78 has corrected that. So this + your minor change == something that has problem to work. 
At the moment, it works in TLS 143, still not in pure 993 . 
Thks anyway.

**Comment by saisie-mobile** [comment]
the clue is also to simplify the Dovecot config file (after I say the warning) message de /var/log/syslog : 
Aug  1 22:29:16 myserver dovecot: master: Dovecot v2.2.13 starting up for imap, pop3, pop3 (core dumps disabled)
Aug  1 22:29:16 myserver dovecot: config: Warning: NOTE: You can get a new clean config file with: doveconf -n > dovecot-new.conf
Aug  1 22:29:16 myserver dovecot: config: Warning: Obsolete setting in /etc/dovecot/dovecot.conf:104: protocol { ssl_listen } has been replaced by service { inet_listener { address } }
so I made doveconf -n > dovecot-new.conf
saved the old config file and completed this new one until it works with the "auth_debug=yes" option , that I remove now it works.

**Comment by chris001** [comment]
> > Ultra-loose Security bugs in Dovecot configuration in webmin were fixed recently,
> 
> I am sorry, Chris, but what bug are you referring to?

Hi @iliaross The `IMAP` security bug where there was, until recently, no support for **Dovecot SNI** ("server name identification") unique certificates per email domain.  Without `SNI`, there was a shared certificate, so the mail app user would've had to accept a non-matching certificate, and due to that, an aggressive attacker could eavesdrop on our email communications by means of a man-in-the-middle attack.
Fixed recently in: https://github.com/virtualmin/virtualmin-gpl/issues/21
Additional comments: https://www.virtualmin.com/node/68434
Fixing this has tightened up security on Dovecot, which likely cause Thunderbird mail app IMAP login failures for @saisie-mobile
