### ISSUE TITLE
webmin debian Updated to 1.954?

### ISSUE THREAD

**Issue by That-Guy-Jack** [webmin/webmin#1280]
I've got the Webmin install on a raspberry pi running Debian, and a couple of days ago it had a notification to update to the latest version but according to the main website the latest is only 1.9.53. and also the update has broken the temp monitoring on the raspberry pi. 

Many thanks 
Jack

**Comment by That-Guy-Jack** [comment]
Managed to downgrade to 1.953 and the temp monitor is working again

**Comment by iliarostovtsev** [comment]
> and also the update has broken the temp monitoring on the raspberry pi.

What is the output of `sensors` command on your Raspberry Pi?

**Comment by That-Guy-Jack** [comment]
The output is with verstion 1.953: 
`[pi@Raspberry-Pi-Web-Server ~]# sensors
cpu_thermal-virtual-0
Adapter: Virtual device
temp1:        +38.6 C  

rpi_volt-isa-0000
Adapter: ISA adapter
in0:              N/A  
`

**Comment by iliarostovtsev** [comment]
> Managed to downgrade to 1.953 and the temp monitor is working again

No need. 1.954 is the official latest release, and must be installed instead of 1.953. Please install 1.954 first and try to apply [this patch](https://github.com/webmin/webmin/commit/a2f88e1d1a9095e9eea17c9532c8c1deb91b51f4) afterwards, which should fix your issue.

**Comment by That-Guy-Jack** [comment]
patch worked thanks : )
