### ISSUE TITLE
React.js Integration

### ISSUE THREAD

**Issue by lightninglu10** [webmin/webmin#1281]
Hey all, I want to use webmin as a base of a dashboard, but want to build new modules to add to webmin with React.js. I'm setting up an asset pipeline to allow for all of this to happen and I'm wondering if there's an example or best practices for utilizing a frontend framework like this into webmin.

**Comment by jcameron** [comment]
Sorry, but this isn't something we have much experience with.

@iliaross any thoughts?

**Comment by iliarostovtsev** [comment]
> I'm wondering if there's an example or best practices for utilizing a frontend framework like this into Webmin.

I don't think there is anything like this available yet. I think you will be a pioneer. :wink:
