### ISSUE TITLE
Raspbian empty systemd service files

### ISSUE THREAD

**Issue by gabrielcorneanu** [webmin/webmin#1282]
Webmin version 1.954
Raspbian Linux 10

Am I really the only one having this problem?? I have searched the web and did not find anything...
I have a RPi4 with latest Raspbian (used for OpenHab), and it seems that (Bootup and Shutdown) service files are not found.
The services are visible in the list, but when I open (almost) any of them, the content is empty.
It looks like it searches for .service files at wrong location...

To test, just open (on Raspbian) any default service (e.g. ssh, dbus, bluetooth)
The files are present in /lib/systemd/system/
Those found in /usr/lib/systemd/system/ are properly shown (including webmin)

**Comment by gabrielcorneanu** [comment]
In the meantime I found the error...
In file init-lib.pl, function "get_systemd_root" returns "/usr/lib/systemd/system" if it exists!

I modified like this (I don't really know if it should also test without ".service" extension)

I hope it helps.

```
sub get_systemd_root
{
my ($name) = @_;
if ($name && (-r "/etc/systemd/system/$name.service" ||
              -r "/etc/systemd/system/$name")) {
        return "/etc/systemd/system";
        }
if ($name && (-r "/usr/lib/systemd/system/$name.service" )) {
        return "/usr/lib/systemd/system";
        }
return "/lib/systemd/system";
}

```

**Comment by jcameron** [comment]
Thanks, we'll fix this in the next Webmin release.
