### ISSUE TITLE
Installation on Debian 10: webmin.postinst: cannot create /etc/webmin/stop: Directory nonexistent

### ISSUE THREAD

**Issue by col-panic** [webmin/webmin#1287]
On a fresh installed Debian 10, using the apt install with the repository mentioned in http://www.webmin.com/deb.html
the following messages appears during installation 

```
Setting up webmin (1.954) ...
/var/lib/dpkg/info/webmin.postinst: 4: /var/lib/dpkg/info/webmin.postinst: cannot create /etc/webmin/stop: Directory nonexistent
Webmin install complete. You can now login to https://debian:10000/
as root with your root password, or as any user who can use sudo
to run commands as root.
Processing triggers for systemd (241-7~deb10u4) ...
```

I'm not sure whether this is a problem

**Comment by jcameron** [comment]
We'll fix this in the next release. It's quite harmless though.

**Comment by MichaIng** [comment]
Thanks, just saw the same, visual only but good to not have an expected error message on every fresh install. My idea to fix it was to replace line 4 of postinst like this:
```
cat >/etc/webmin/stop 2>/dev/null <<'EOD'
```
->
```
[ ! -d /etc/webmin ] || cat >/etc/webmin/stop 2>/dev/null <<'EOD'
```

**Comment by jcameron** [comment]
Yes, that's basically what we'll do
