### ISSUE TITLE
Error - Perl execution failed

### ISSUE THREAD

**Issue by dhmusman** [webmin/webmin#1288]
Please let me know how i can resolve that issue.

HTTP/1.0 500 Perl execution failed Server: MiniServ/1.941 Date: Fri, 21 Aug 2020 07:23:53 GMT Content-type: text/html; Charset=iso-8859-1 Connection: close
Error - Perl execution failed

Modification of non-creatable array value attempted, subscript -1 at ./mysql-lib.pl line 467, line 2010. 

Virtualmin Virtual Servers
Version 6.08.gpl

ubuntu 16.04

**Comment by dhmusman** [comment]
@iliaross when i search something in database in Virtualmin, I got that issue.

**Comment by dhmusman** [comment]
@iliaross any idea how to fixed that issue?

**Comment by iliaross** [comment]
> @iliaross when i search something in database in Virtualmin, I got that issue.

It looks like an escaping issue.

What was the exact search string? Which page exactly did you run the search on?

**Comment by jcameron** [comment]
This could also be due to an error parsing the output from the `mysql` command in Webmin.

To avoid it, try installing the DBI and DBD::mysql Perl modules.

**Comment by dhmusman** [comment]
Please see my screenshot.

https://prnt.sc/u7aw9t

**Comment by iliarostovtsev** [comment]
Running Webmin 1.955 I cannot reproduce this issue. At first please upgrade to the latest Webmin 1.955 and Virtualmin 6.12.

**Comment by iliarostovtsev** [comment]
> To avoid it, try installing the DBI and DBD::mysql Perl modules.

Jamie, in fact, removing this package results in exactly the same error but only on older versions of MySQL/MariaDB.

**Comment by iliarostovtsev** [comment]
@dhmusman .. to work around the problem run the following command:

~~~
apt-get install libdbd-mysql-perl
~~~

**Comment by dhmusman** [comment]
@iliaross  thanks it resolve the issue.
