### ISSUE TITLE
netplan botches routes section on update

### ISSUE THREAD

**Issue by swelljoe** [webmin/webmin#1291]
See comparison of config before and after here: https://forum.virtualmin.com/t/dedicated-server-not-accessible-after-installing-virtualmin/107303/4

Leaves out on-link option.

**Comment by jcameron** [comment]
Looks like the problem is this block :  

```
        - on-link: true
          to: 0.0.0.0/0
          via: 136.243.133.25
```

Specifically, the on-link continuation line.

**Comment by jcameron** [comment]
Ok I checked in a fix for this, for inclusion in the next release.
