### ISSUE TITLE
IPv4 network address calculation error

### ISSUE THREAD

**Issue by R-Adrian** [webmin/webmin#1292]
on a fresh Hyper-V virtual machine, under /webmin/edit_access.cgi i tried to add an IP address filter to only allow connections from:
`172.16.0.0/12`
(but i do not want to check the box for allowing all local networks) and i get the message:
`Failed to update access list: Your current IP address (172.21.112.1) would be denied`

but if i specify the full quad-dotted netmask:
`172.16.0.0/255.240.0.0`
it works.

using Webmin version 1.955 on Ubuntu 20.04.1 LTS (installed from webmin APT repo)

**Comment by jcameron** [comment]
Thanks! I'll fix this in the next Webmin release.

Fun fact - this bug has been in Webmin for over 13 years, but you are the first person to find it :-)
