### ISSUE TITLE
webmin fails after upgrade to 1.955

### ISSUE THREAD

**Issue by Elfanar** [webmin/webmin#1293]
Hello,
After latest upgrade, webmin login no longer works. No error message is shown either ! nothing in the logs :(

**Comment by swelljoe** [comment]
What does "no longer works" mean?

**Comment by Elfanar** [comment]
means, when I fill password and hit login I get nothing, login does not happen, I stay at login page, no error shows up at login page, and I see this at console :
manifest.json:1 Manifest: Line: 1, column: 1, Syntax error.

and manifest.json content is in html format.

**Comment by swelljoe** [comment]
Restart Webmin. That sounds like it's serving out old files.

**Comment by Elfanar** [comment]
already tried that  first !

**Comment by iliarostovtsev** [comment]
> means, when I fill password and hit login I get nothing, login does not happen, I stay at login page, no error shows up at login page

Did you try another browser and/or incognito mode or just force reloading (_Ctrl+Shift+R_) the page after entering a login credentials?

**Comment by Elfanar** [comment]
I tried another browser, actualy tried both firefox and edge (and I never opened that page on them) they both gave same error, send me your email and I'll send you the link.

**Comment by iliarostovtsev** [comment]
Okay there - `support аt rostovtsev dоt io`

**Comment by iliarostovtsev** [comment]
It looks that you are behind proxy and the proxy doesn't do the redirect correctly.

**Comment by Elfanar** [comment]
it used to work before upgrade !

**Comment by iliarostovtsev** [comment]
Perhaps, this commit https://github.com/webmin/webmin/commit/49353baa58516c8d50f27755590b6c78b44f6551 is affecting you. Try removing `redirect_prefix` from config.
