### ISSUE TITLE
The download.webmin.com SSL Certificate Has Expired

### ISSUE THREAD

**Issue by craigkc** [webmin/webmin#1294]
This isn't a code issue, but I don't know a better way to get in touch with you.  The Let's Encrypt certificate on download.webmin.com expired this morning so it's surely throwing apt-get errors for everyone worldwide.  Your Let's Encrypt setup just needs fixed.

![webmin-certificate-expiration](https://user-images.githubusercontent.com/1191263/92635279-2acaae00-f29b-11ea-9023-3d228ae06315.jpg)

**Comment by iliarostovtsev** [comment]
Hi,

I can see that our certificate is valid until November 8?

![image](https://user-images.githubusercontent.com/4426533/92635795-14dedc80-f2df-11ea-9931-2c9c1520b840.png)

**Comment by craigkc** [comment]
Perhaps there are geo-diverse web servers or more than one behind a load balancer?  Maybe some in the cluster are updated but not others?

I just found that someone else reported it here.  https://sourceforge.net/p/webadmin/discussion/600155/thread/edc2fcbd1f/

**Comment by iliarostovtsev** [comment]
Is running install or reinstall `ca-certificates` help?

~~~
apt-get install --reinstall ca-certificates
~~~

**Comment by iliarostovtsev** [comment]
Perhaps it's a browser's cache issue? Can you try some other browser and see if you're getting the same issue?

Is the time set on the machine in sync, by the way?

**Comment by craigkc** [comment]
Time is in sync on the Windows PC in my original screenshot.  Reinstalling CA certs didn't help.  The original symptom was apt-get update on another system.  I've verified its clock is correct and attached the actual error that machine is getting as well that caused me to check it via browser.

![webmin-certificate-expiration-02](https://user-images.githubusercontent.com/1191263/92636421-f0621080-f29c-11ea-9688-4b0470a5f653.jpg)

**Comment by craigkc** [comment]
This is not a browser or time sync issue.  Below are 3 different independent sites I used to triple-check the certificate your Apache v2.4.6 host is serving.  It has expired.

![webmin-certificate-expiration-03](https://user-images.githubusercontent.com/1191263/92637534-91050000-f29e-11ea-9404-b24b9e1736e3.jpg)
![webmin-certificate-expiration-04](https://user-images.githubusercontent.com/1191263/92637542-93fff080-f29e-11ea-8848-0af2fc96740b.jpg)
![webmin-certificate-expiration-05](https://user-images.githubusercontent.com/1191263/92637547-95c9b400-f29e-11ea-8c46-83bc84477f40.jpg)

**Comment by iliarostovtsev** [comment]
I think I know why it's happening. I will let @swelljoe know. Thanks.

**Comment by hwhcheung** [comment]
Yes, we have this issues for our Linux servers in this morning too.

**Comment by iliarostovtsev** [comment]
Okay, thanks. It seems to be fixed now.

**Comment by iliarostovtsev** [comment]
Okay, stand by. Not fully fixed yet. There is one more mirror to sync with. We will fix it shortly..

**Comment by iliarostovtsev** [comment]
Okay, this time it's fixed.

**Comment by rakrist08** [comment]
It happen to me. How to fix it ?
```
Setup repository? (y/N) y
  Downloading Webmin key ..
  ..failed : ERROR: The certificate of 'download.webmin.com' is not trusted. ERROR: The certificate of 'download.webmin.com' has expired.
```

**Comment by iliajie** [comment]
> It happen to me. How to fix it ?
> 
> ```
> Setup repository? (y/N) y
>   Downloading Webmin key ..
>   ..failed : ERROR: The certificate of 'download.webmin.com' is not trusted. ERROR: The certificate of 'download.webmin.com' has expired.
> ```

What is the output of the following commands on your system:

```
date
cat /etc/os-release
ping download.webmin.com
```

**Comment by rakrist08** [comment]
date
`Tue Nov 14 13:05:10 CET 2023`
cat /etc/os-release
`PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
`
ping download.webmin.com
`PING download.webmin.com (104.207.151.13) 56(84) bytes of data.
64 bytes from 104.207.151.13.vultrusercontent.com (104.207.151.13): icmp_seq=3 ttl=51 time=146 ms
64 bytes from 104.207.151.13.vultrusercontent.com (104.207.151.13): icmp_seq=4 ttl=51 time=146 ms
64 bytes from 104.207.151.13.vultrusercontent.com (104.207.151.13): icmp_seq=5 ttl=51 time=145 ms
64 bytes from 104.207.151.13.vultrusercontent.com (104.207.151.13): icmp_seq=6 ttl=51 time=146 ms
64 bytes from 104.207.151.13.vultrusercontent.com (104.207.151.13): icmp_seq=7 ttl=51 time=145 ms
^C
--- download.webmin.com ping statistics ---
7 packets transmitted, 5 received, 28.5714% packet loss, time 67ms
rtt min/avg/max/mdev = 145.475/145.530/145.567/0.343 ms`

**Comment by iliajie** [comment]
Unless you can upgrade CA certificates by running `apt-get install ca-certificates` to resolve this, the work-around would be is to edit `setup-repos.sh` script manually and replace `webmin_download="https://$webmin_host"` with `webmin_download="http://$webmin_host"` instead.

I don't see any issues with `download.webmin.com` certificate by the way.

**Comment by rakrist08** [comment]
I already updated my ca-certificates. I'll try to change https to http

**Comment by rakrist08** [comment]
> Unless you can upgrade CA certificates by running `apt-get install ca-certificates` to resolve this, the work-around would be is to edit `setup-repos.sh` script manually and replace `webmin_download="https://$webmin_host"` with `webmin_download="http://$webmin_host"` instead.
> 
> I don't see any issues with `download.webmin.com` certificate by the way.

fixed by changing https to http. Thank you sir
