### ISSUE TITLE
No CPU Temperature in Webmin

### ISSUE THREAD

**Issue by motorsense** [webmin/webmin#1297]
Hello,
i have lm-sensors installed and configured. sensors says: 
`iwlwifi_1-virtual-0
Adapter: Virtual device
temp1:            N/A

nct6792-isa-0290
Adapter: ISA adapter
in0:                    +0.14 V  (min =  +0.00 V, max =  +1.74 V)
in1:                    +0.00 V  (min =  +0.00 V, max =  +0.00 V)
in2:                    +3.34 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in3:                    +3.33 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in4:                    +0.00 V  (min =  +0.00 V, max =  +0.00 V)
in5:                    +0.00 V  (min =  +0.00 V, max =  +0.00 V)
in6:                    +0.72 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in7:                    +3.46 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in8:                    +3.31 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in9:                    +1.86 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in10:                   +0.18 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in11:                   +0.14 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in12:                   +1.83 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in13:                   +1.68 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in14:                   +0.00 V  (min =  +0.00 V, max =  +0.00 V)
fan1:                   820 RPM  (min =    0 RPM)
fan2:                  1130 RPM  (min =    0 RPM)
fan3:                   783 RPM  (min =    0 RPM)
fan4:                     0 RPM  (min =    0 RPM)
fan5:                     0 RPM  (min =    0 RPM)
SYSTIN:                +117.0°C  (high =  +0.0°C, hyst =  +0.0°C)  sensor = thermistor
CPUTIN:                 -62.5°C  (high = +80.0°C, hyst = +75.0°C)  sensor = thermistor
AUXTIN0:                +41.0°C  (high =  +0.0°C, hyst =  +0.0°C)  ALARM  sensor = thermistor
AUXTIN1:               +108.0°C    sensor = thermistor
AUXTIN2:               +106.0°C    sensor = thermistor
AUXTIN3:               -128.0°C    sensor = thermistor
SMBUSMASTER 0:          +49.5°C
PCH_CHIP_CPU_MAX_TEMP:   +0.0°C
PCH_CHIP_TEMP:           +0.0°C
PCH_CPU_TEMP:            +0.0°C
intrusion0:            OK
intrusion1:            ALARM
beep_enable:           disabled

k10temp-pci-00c3
Adapter: PCI adapter
Tdie:         +49.4°C  (high = +70.0°C)
Tctl:         +49.4°C
`
Webmin don´t show the CPU temperature.

**Comment by iliarostovtsev** [comment]
Hi,

Which Webmin version do you have currently installed and which of the output above relates to CPU?

**Comment by motorsense** [comment]
I have Webmin 1.955 and a Ryzen 3700x CPU.

**Comment by iliarostovtsev** [comment]
I don't see how this sensor's output is correct. There is no core temp data at all. It looks like a bug in other software.

**Comment by motorsense** [comment]
Hi i have found the following at Hwinfo.

-CPU (Tctl): This is the T_control temperature available on AMD CPUs only. On several generations before Zen (Ryzen), this is not a reliable representation of the temperature. On AMD Zen series this is the temperature used to control cooling and is a fixed offset from the real CPU temperature. Offset is used mostly on X-series and some Threadripper CPUs; in such case two values are shown: Tctl and Tdie. If no offset is used, then only a single value is shown as Tctl/Tdie, which equals the real temperature.

-CPU (Tdie): This value is shown in case the CPU uses an offset from Tctl and represents the real temperature (Tdie = Tctl - Tctl_offset).

So I think Tdie is the CPU temperature.
