### ISSUE TITLE
miniserv.error log file 

### ISSUE THREAD

**Issue by MoadKey** [webmin/webmin#1298]
Hi,
Webmin keep crushing after update under ubuntu 18.04.5 lts

**miniserv.erro**
[15/Sep/2020:07:56:34 -0400] miniserv.pl started
[15/Sep/2020:07:56:34 -0400] IPv6 support enabled
[15/Sep/2020:07:56:34 -0400] Using MD5 module Digest::MD5
[15/Sep/2020:07:56:34 -0400] Using SHA512 module Crypt::SHA
[15/Sep/2020:07:56:34 -0400] PAM authentication enabled
Use of uninitialized value $out in pattern match (m//) at /usr/share/webmin/bind8/bind8-lib.pl line 106.
Use of uninitialized value $ip in concatenation (.) or string at /usr/share/webmin/system-status/system_info.pl line 39.

**Comment by fcarelse** [comment]
Having the same issue for a long time.
Just going to have to edit the system_info.pl file myself to stop this error from crashing the system.
Will probably make a pull request if I find a fix.

**Comment by jcameron** [comment]
Those are just warning messages - they won't actually cause miniserv.pl to crash.

Is anything logged to /var/log/messages ?

**Comment by fcarelse** [comment]
Nothing related to Webmin in /var/log/messages
Only <10 lines in it.

**Comment by jcameron** [comment]
How much RAM does your system have? In a low-memory situation, the kernel might kill processes to free up RAM.

**Comment by fcarelse** [comment]
2.48 GiB used /  834.86 MiB cached  / 3.76 GiB total
Just grabbed from a random point in time.

**Comment by jcameron** [comment]
Also check the output from the `dmesg` command for any messages about the OOM killer.
