### ISSUE TITLE
How to adjust Stats History interval?

### ISSUE THREAD

**Issue by metallicats** [webmin/webmin#1304]
Hi is there any option to adjust the Stats History interval? It seems like it's updating every 3 seconds. I need to adjust it every 1 min. Thanks!

**Comment by jcameron** [comment]
Do you mean how often the page refreshes in your browser? Or how often the stats are collected?

**Comment by iliarostovtsev** [comment]
If by _Stats History_ you mean this:

![image](https://user-images.githubusercontent.com/4426533/94338432-d2b1dc80-fffa-11ea-8169-e36214871137.png)

.. then, yes, there is a way to change interval on theme configuration page:

![image](https://user-images.githubusercontent.com/4426533/94338460-05f46b80-fffb-11ea-839e-e73deed3f2d4.png)
