### ISSUE TITLE
"Couldn't open /etc/securetty: No such file or directory" error on Ubuntu 20.04

### ISSUE THREAD

**Issue by ycecube** [webmin/webmin#1306]
I've freshly installed webmin on ubuntu 20.04 and after installation when I try to log in I can see the following messages in the authn.log:

```
Oct  4 07:09:16 xyz webmin[37825]: Webmin starting
Oct  4 07:09:17 xyz sudo: pam_unix(sudo:session): session closed for user root
Oct  4 07:09:46 xyz perl[38144]: pam_unix(webmin:auth): Couldn't open /etc/securetty: No such file or directory
Oct  4 07:09:46 xyz perl[38144]: pam_unix(webmin:auth): Couldn't open /etc/securetty: No such file or directory
Oct  4 07:09:49 xyz webmin[38144]: Invalid login as linux_user from xxx.xxx.xxx.xxx
```

Is there anything that I can do about it?

**Comment by jcameron** [comment]
As long as Virtualmin logins are working OK, I think you can just ignore this.

**Comment by ycecube** [comment]
I'm not using virtualmin.

**Comment by jcameron** [comment]
Sorry, I meant Webmin logins.

**Comment by ycecube** [comment]
I see, but it is not working.
By the way how does the login actually works? For local login I have set up a yubikey as 2fa.

**Comment by jcameron** [comment]
So when you login via SSH, do you get prompted for a second factor?

**Comment by ycecube** [comment]
Not through SSH, although I'm using the key for that too, but I've changed it to ask for the key only when I physically access the machine.

**Comment by iliarostovtsev** [comment]
> Oct  4 07:09:46 xyz perl[38144]: pam_unix(webmin:auth): Couldn't open /etc/securetty: No such file or directory

At the moment, this is standard warning at all installations get. Not related to Webmin at all.

> Not through SSH, although I'm using the key for that too, but I've changed it to ask for the key only when I physically access the machine.

You need to make sure that `linux_user` has `~./ssh/authorized_keys` in place with proper permissions (`700` for `.ssh` directory and `600` for `authorized_keys` file). You can get a clearer picture of what's happening by running connection in verbose mode, like:

~~~
ssh -v user@server
~~~

**Comment by ycecube** [comment]
The SSH works properly, permission are set as you said, but I get an invalid_login when I try to login through the https://FQDN:1000 address.

**Comment by jcameron** [comment]
Can you post the contents of your `/etc/pam.d/webmin` file?

**Comment by ycecube** [comment]
```
#%PAM-1.0
@include common-auth
@include common-account
@include common-password
@include common-session
```

Ah okay I got it now, common-auth has the yubikey requirement, I've changed it to the one that doesn't have, it's working now, thanks!
Although this is just a workaround, are you planning to support yubikeys in the future? Or is it already supported?

**Comment by jcameron** [comment]
Yubikey support is on our TODO list, although it will be supported not via PAM.

**Comment by ycecube** [comment]
Okay, that's understandable, thank you for your help!
