### ISSUE TITLE
Bootup and Shutdown Errors

### ISSUE THREAD

**Issue by TheBudda** [webmin/webmin#1307]
I do not know what's going on here. Webmin was working fine for months. After upgrading to webmin 19.60, I got no Bootup and Shutdown menu. Please see screenshot attached 

This issue is only on my dedicated server with OVH. My home server is working fine with 19.60

![webmin_2020-10-12_19-27](https://user-images.githubusercontent.com/16983376/95781541-ee3d0880-0cc5-11eb-88b0-aeca30507c37.png)
 
Kind regards
Budda

**Comment by iliarostovtsev** [comment]
Hi,

We haven't released Webmin 1.960 yet. 

Does this error still happen, if you downgrade back to Webmin 1.955?

**Comment by jcameron** [comment]
Possibly some change in the `systemctl` command has broken Webmin

If you SSH in as `root` and run `systemctl list-units --full --all -t service --no-legend` , what does it output?

**Comment by TheBudda** [comment]
Hi @iliaross @jcameron 

Sorry my bad, I got webmin 1.955 is installed! Authentic theme version 19.60 

The output of the command (systemctl list-units --full --all -t service --no-legend) is very big, so I put it in a text file for you to view

[systemctl list-units.txt](https://github.com/webmin/webmin/files/5368522/systemctl.list-units.txt)

**Comment by TheBudda** [comment]
This screenshot is from my home server. I got no issues with my home server, but you can see 19.60 installed on this box as well

![webmin_home_server_2020-10-13_03-14](https://user-images.githubusercontent.com/16983376/95807506-41cd4780-0d02-11eb-9946-6e9b9170aa40.png)

**Comment by TheBudda** [comment]
I just downloaded webmin_1.955_all.deb to try the downgrade. But when I install webmin_1.955_all.deb I get webmin 1.54 not 1.55 O_0

![webmin_19 54_2020-10-13_03-23](https://user-images.githubusercontent.com/16983376/95808009-768dce80-0d03-11eb-8962-6b34e99c5a0f.png)

**Comment by iliarostovtsev** [comment]
If you reinstall Webmin does it fix your issue?

~~~
yum reinstall webmin
apt-get install --reinstall webmin
~~~

**Comment by TheBudda** [comment]
I reinstalled webmin 1.955 and still the same

**Comment by TheBudda** [comment]
everything else is working fine just Bootup and Shutdown Errors. I have restarted the server as well

**Comment by TheBudda** [comment]
Fixed!! I got an update on my server at home, upgrade to Linux 5.4.51-050451-generic on x86_64. When I checked on my OVH server, there was no update. I then went to ubuntu mainline grabbed the Linux 5.4.51-050451-generic on x86_64.debs install them deleted the others, kept 2 versions update grab, reboot and bingo, all is back working again 

![Bootup and Shutdown_2020-10-14_03-27](https://user-images.githubusercontent.com/16983376/95936372-4f9bcf00-0dcd-11eb-9b7e-e000a06b41ed.png)

**Comment by jcameron** [comment]
Do you know which package you updated to fix this?

**Comment by TheBudda** [comment]
> Do you know which package you updated to fix this?

Here you got dude >> https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.4.51/
