### ISSUE TITLE
Unable to identify operating system

### ISSUE THREAD

**Issue by zynexiz** [webmin/webmin#1311]
I'm running CentOS 8 Stream release, and had Webmin 1.955-1 installed on it. Suddenly, it complained that the OS couldn't be identified and some perl modules failed. I removed it, and tried reinstalling it but got "Unable to identify operating system" both when installing from yum repo, and trying to install the downloaded rpm.

I tried so search for the error, but mostly just fond some very old posts about it. Looking in os_list.txt I fond these lines;

```
CentOS Linux			$1	redhat-linux	10.0	`cat /etc/centos-release /etc/redhat-release 2>/dev/null` =~ /CentOS\s+release\s+(\S+)/i && $1 < 4
CentOS Linux			$2	redhat-linux	$2+8.0	`cat /etc/centos-release /etc/redhat-release 2>/dev/null` =~ /CentOS\s+(Linux\s+)?release\s+(\S+)/i && $2 >= 4
```
Inside my centos-release, it said "CentOS Stream release 8". Changing the release file to "CentOS release 8" fixed it, so it does seem that the stream part mess things up. I did mange to install it after I first installed my new server, it might be that the centos-release file changed after that, not sure. If the file updates again, I guess I will face the same issue.

**Comment by iliarostovtsev** [comment]
Hi,

Thanks for reporting. Upcoming Webmin 1.960 will have _CentOS 8 Stream_ releases recognized properly.
