### ISSUE TITLE
script created cluster copy does not respect scheduled (sched=1)

### ISSUE THREAD

**Issue by pieter-groeneweg** [webmin/webmin#1314]
Webmin version | 1.955 | Usermin version | 1.803
Virtualmin version | 6.12 | Authentic theme version | 19.54
On Debian 10

I am creating a cluster copy on server creation in Virtualmin.
Like:
```
#!/bin/sh
cat > /etc/webmin/cluster-copy/copies/$VIRTUALSERVER_DOM.copy <<EOL
cmdlocal=
mins=0
files=/path/to/originalfile.ext
servers=123.123.123.123
id=$VIRTUALSERVER_DOM
beforelocal=
dest=/path/to/destinationfile.ext
email=
dmode=1
days=*
before=
weekdays=*
cmd=
months=*
sched=1
hours=*
EOL
```

The script nicely creates a cluster copy script in /etc/webmin/cluster-copy/copies/
All attributes and values in place.
When in webmin->cluster->cluster copy files I can see the created script.
The list shows:
```
files to copy|copy to servers|Scheduld?|Action
/path/to/originalfile.ext|123.123.123.123|Yes, every hour at 0 past the hour|>execute
```

I expected the file copy to happen at every hour.. nothing is copied.
If I click execute, files are copied allright.

It seems not to respect the scheduled (sched=1) as when In webmin I click on the clickable "files to copy" I see the copy on schedule is still set to "No." And not to "Yes..."

To make it work I need to select "Yes, at times scheduled below .." and save.

The scripted output still looks the same when I check in /etc/webmin/cluster-copy/copies/

However now the scheduled flag is respected.. and files are copied every hour...

I hope I explained this well.. do ask if I didn't..

**Comment by pieter-groeneweg** [comment]
Found it. It needed a cron job created with the same schedule with copy.pl $VIRTUALSERVER_DOM.copy

```
#create a cronjob
crontab_exists() {
	crontab -u root -l | grep "/etc/webmin/cluster-copy/copy.pl $VIRTUALSERVER_DOM" 
}

if ! crontab_exists; then
(crontab -u root -l ; echo "0 * * * * /etc/webmin/cluster-copy/copy.pl $VIRTUALSERVER_DOM") | crontab -u root -
fi
```

**Comment by jcameron** [comment]
This is expected - when a copy is created in Virtualmin, a cron job is also setup to run it on the selected schedule.
