### ISSUE TITLE
Changed wordpress domain name and now I can't login - Redirect to port 10000

### ISSUE THREAD

**Issue by PhilipRochester** [webmin/webmin#1315]
Hi guys, 

I'm pretty new to webmin. Built a website in wordpress on a test domain and just updated webmin for the real domain to bring the website live. 

Made the domain change in virtualmin via Server Configuration > Change Domain New

After I change the domain, I could not access the website via (newdomain.com/wp-login), I then reverted to reinstate the test domain (test.com/wp-login) and now I can not get access. 

I am now on the (test.com/wp-login) domain to try get back into the website, tried adding define WP_SITEURL and WP_HOME to the wp-config.php file but this did not work. 

The wordpress domain for login in just keeps redirecting to webmin login screen on port 10000 rather than the wordpress login that I want. 

How can I fix this? 

I also tried restarting the Apache, but this did not help.

**Comment by iliarostovtsev** [comment]
Hi, Philip.

This is an issue tracker for Webmin - you will have more luck getting an answer to your question from [Virtualmin Forums](https://forum.virtualmin.com/).
