### ISSUE TITLE
Webmin 1.960 configure to startup at Boot 

### ISSUE THREAD

**Issue by parveen-kumar-1** [webmin/webmin#1318]
sudo sh setup.sh

Start Webmin at boot time (y/n): y

Configuring Webmin to start at boot time..
sh: 1: Syntax error: ")" unexpected
..done

Why do we get this error in between about a ) expected.. Pls chk and fix. 
This is a Bitnami "Wordpress Multitier" Azure VM image.

**Comment by jcameron** [comment]
Which Linux distribution or operating system is your VM image running?

**Comment by shoulders** [comment]
this should be closed
