### ISSUE TITLE
Change Apache Vhost Default?

### ISSUE THREAD

**Issue by justinhilles** [webmin/webmin#132]
Hi All,

I have a kinda weird request.  I was wondering if there was any way to modify the Default Vhost Template at all?  I want to not include "Allow from All" for the Directory Directive. Looking through the source, i havent found a way to do this and im wondering if its even possible?

Thanks

Justin

**Comment by joekrukosky** [comment]
jcameron, thanks, your comment was a big help.

Just in case anyone else comes across this and wants to know how to modify the create_virt.cgi.  Here's the changes to apache/create_virt.cgi that worked for me to add "Allow from All" by default.
On Ubuntu 14.04 and webmin 1.780 the file was in:
  /usr/share/webmin/apache/create_virt.cgi

Around line 215 there is an _if ($in{'adddir'} && $in{'root'}) {_
In that if statement I made the change adding the "Allow from All" as such (changes are bold):

if ($in{'adddir'} && $in{'root'}) {
	# Add a <Directory> section for the root
	$dirsect = { 'name' => 'Directory',
		     'value' => "\"$in{'root'}\"",
		     'type' => 1,
		     'members' => [
			{ 'name' => 'allow',
			  'value' => 'from all' },
			{ 'name' => 'Options',
			  'value' => 'None' },
			**{ 'name' => 'AllowOverride',**
			 **'value' => 'All' },**
			],
		   };
