### ISSUE TITLE
Webmin requires 'unzip' on Debian but dependency not documented

### ISSUE THREAD

**Issue by mas94uk** [webmin/webmin#1320]
I installed a fresh Debian system on a Buffalo Linkstation (https://github.com/1000001101000/Debian_on_Buffalo) and then installed webmin using the `wget` method instructions [here](https://www.webmin.com/deb.html).  This includes:
`apt-get install perl libnet-ssleay-perl openssl libauthen-pam-perl libpam-runtime libio-pty-perl apt-show-versions python`

However a dependency is missing: unzip.

`apt-get install unzip`
fixes it.

**Comment by jcameron** [comment]
Thanks - I'll add that to the docs.
