### ISSUE TITLE
Fail to add iscsi target if iscsi server listen to wildcard address 0.0.0.0

### ISSUE THREAD

**Issue by ccy** [webmin/webmin#1321]
I start a TrueNAS server (192.168.0.136) configure to serve iSCSI target via IPv4 wildcard address `0.0.0.0`.

In a Debian host install with `webmin` and `open-iscsi`, It can discover the iSCSI targets:

```bash
$ iscsiadm -m discovery -t st -p 192.168.0.136
192.168.0.136:3260,-1 iqn.2005-10.org.freenas.ctl:v1
```
However, when use Webmin to show targets in `iSCSI Client | Add iSCSI Connection`.  it prompt error:

    Failed to add iSCSI connection : No iSCSI targets were found on 192.168.0.136

Here is the directory content of `/etc/iscsi/nodes` after discovery:

```bash
$ tree /etc/iscsi/nodes/
/etc/iscsi/nodes/
└── iqn.2005-10.org.freenas.ctl:v1
    └── 192.168.0.136,3260

1 directory, 1 file
```
and debug output of discovery:

```bash
$ iscsiadm -m discovery -t st -p 192.168.0.136 --debug 10
...
iscsiadm: updated 'node.conn[0].iscsi.OFMarker', 'No' => 'No'
iscsiadm: Could not open /etc/iscsi/nodes/iqn.2005-10.org.freenas.ctl:v1/192.168.0.136,3260,-1/default err No such file or directory
iscsiadm: Removing config file /etc/iscsi/nodes/iqn.2005-10.org.freenas.ctl:v1/192.168.0.136,3260 iface id default
iscsiadm: overwriting existing record
iscsiadm: Looking for config file /etc/iscsi/nodes/iqn.2005-10.org.freenas.ctl:v1/192.168.0.136,3260
192.168.0.136:3260,-1 iqn.2005-10.org.freenas.ctl:v1
```

The discovery action attempt to look for file `192.168.0.136,3260,-1/default` but it doesn't exist.

If I configure the iSCSI portal to listen to a fixed IP address, then everything work.

```bash
$ iscsiadm -m discovery -t st -p 192.168.0.136
192.168.0.136:3260,1 iqn.2005-10.org.freenas.ctl:v1

$ tree /etc/iscsi/nodes/
/etc/iscsi/nodes/
└── iqn.2005-10.org.freenas.ctl:v1
    └── 192.168.0.136,3260,1
        └── default

2 directories, 1 file
```

I am not sure if it is a bug in `WebMin` or `open-iscsi` package.

**Comment by jcameron** [comment]
Thanks - this a bug in Webmin caused by the -1 in the `iscsiadm` output. We'll fix it in the next release.
