### ISSUE TITLE
Graphical Issue on dashboard "Network Interfaces"

### ISSUE THREAD

**Issue by pweibel** [webmin/webmin#1323]
In the group box "Network Interfaces" the first item looks not properly alligned:
![10-11-_2020_16-09-36](https://user-images.githubusercontent.com/88119/98692506-7d921600-236f-11eb-87ee-715c4ef2de8e.png)

But it's ok compared with the others. Maybe a few pixels more padding on left would help.

**Comment by pweibel** [comment]
It isn't an issue, only a user experience point.

**Comment by iliarostovtsev** [comment]
Hi,

@pweibel `venet0:0` is a virtual interface of `venet0` and `venet0:0` has intentional padding, to indicate it's located under `venet0`. What padding you're talking about? Of the `venet0`?

**Comment by pweibel** [comment]
The padding for the first line with "venet0".

**Comment by iliarostovtsev** [comment]
Okay, [fixed](https://github.com/authentic-theme/authentic-theme/commit/3e6bbc3f8879bad83aa4d30ba98938d7d4248670). In the future we will make it more consistent across all modules, which is more difficult as of many nested tables being used, in variety of ways.
