### ISSUE TITLE
Two-Factor Authentification does not work on CentOS 7 at all

### ISSUE THREAD

**Issue by dvolozhinok** [webmin/webmin#1329]
All commands was performed from root

Result of hostnamectl
```
Static hostname: authen-test.cloudapp.vip
Icon name: computer-vm
Chassis: vm
Machine ID: adf9299009f744f376e4e8cc3431c2db
Boot ID: 0913c00907b34b54a44a25129d6a6110
Virtualization: kvm
Operating System: CentOS Linux 7 (Core)
CPE OS Name: cpe:/o:centos:centos:7
Kernel: Linux 3.10.0-1127.10.1.el7.x86_64
Architecture: x86-64
```

When I select Google Authentificator in Two-Factor Authentication, I always get this error:
`Failed to save two-factor authentication : The Perl module Authen::OATH needed for two-factor authentication is not installed. Use the Perl Modules page in Webmin to install it.`

OK, it shows me to install module. However it installs module but this does not change anything.
`/etc/init.d/webmin restart`after it does not give anything

Method with MCAP also does not work:
```
yum -y install gcc
yum -y install perl-CPAN
perl -MCPAN -e "install Test::Moose"
perl -MCPAN -e "install Types::Standard"
perl -MCPAN -e "install Moo"
perl -MCPAN -e "install Authen::OATH"
perl -e 'use Authen::OATH;'
```

I have googled all solutions but they does not work. For example, I have tried various solutions and they all does not work, for example:
https://www.virtualmin.com/node/43279
https://www.orangecoat.com/how-to/duo-security-and-webmin-virtualmin-two-factor-authentication-login-integration

Maybe something wrong with package? No, 5 days of building rpm packages of new version of Authen::OATH lead to absolutely nothing!!!

New packages but the same error!

```
mkdir -p /root/Authen/
cd /root/Authen/
wget -i https://scripts.s3.dtln.ru/linklist.txt
rm -f linklist.txt
rpm -Uvh http://repo.openfusion.net/centos7-x86_64/openfusion-release-0.7-1.of.el7.noarch.rpm
yum localinstall *.rpm --skip-broken
## perl-IO-Pager is problematic. It requires /usr/local/bin/perl for some reason!
rpm -i --nodeps perl-IO-Pager-2.10-1.el7.noarch
And this does not work!
```

If you need logs, you can take all the logs you need. VM is still active, I can add you public key.
If you can't fix this, please change 2FA solution for Google Authenticator to another one!

**Comment by iliarostovtsev** [comment]
Hi,

> When I select Google Authentificator in Two-Factor Authentication, I always get this error:

Do the following for CentOS.

1. First install these packages (ignore any warnings if packages are missing, as the list of packages below must work on CentOS 8 as well):

~~~
yum install perl-Digest-SHA1 perl-Digest-HMAC perl-Moo perl-Test perl-Authen-SASL perl-Math-BigInt perl-Test-Needs perl-Type-Tiny
~~~

2. Then go and try to enable 2FA again - you will see the prompt to install **Authen:OATH** as before - do it but on the second screen, just hit the following button (not blue button that suggests building dependencies).

![image](https://user-images.githubusercontent.com/4426533/99537739-1b639180-29bd-11eb-8d11-95d7ab97b490.png)


.. and that will work!

**Comment by dvolozhinok** [comment]
Still fail:
```
No package perl-Test available.
No package perl-Math-BigInt available.
```
No such packages for CentOS 7.
Packes with close name: perl-Math-BigInt-GMP perl-Test-Base don't do the trick.
Any ideas?

**Comment by iliarostovtsev** [comment]
> Packes with close name: perl-Math-BigInt-GMP perl-Test-Base don't do the trick. Any ideas?

Like I said - ignore those warnings. It will workif you follow instructions above (worked on my CentOS 7 flawlessly).

> Also I have a question. If I have built packages, can I replace building phase with RPMs install?

I have no clue what those packages are from. They might.

**Comment by dvolozhinok** [comment]
Error with installing modules:
```
Installing Perl module Authen::OATH from package perl(Authen::OATH) ..

    Installing package(s) with command /bin/yum -y install perl(Authen::OATH) ..

    .. install failed!

Some modules failed to install from packages, trying installation from source instead..

Downloading http://www.cpan.org/authors/id/O/OA/OALDERS/Authen-OATH-2.0.1.tar.gz (13 KiB) ..
     Received 1 KiB (7 %)
     Received 2 KiB (15 %)
     Received 3 KiB (23 %)
     Received 4 KiB (30 %)
     Received 6 KiB (46 %)
     Received 7 KiB (53 %)
     Received 8 KiB (61 %)
     Received 10 KiB (76 %)
     Received 11 KiB (84 %)
     Received 12 KiB (92 %)
     Received 13 KiB (100 %)
.. download complete.
```

Then I pressed Make install and in was successful.
`Make and install of Authen::OATH successful.`

But I still get the same error:
`Failed to save two-factor authentication : The Perl module Authen::OATH needed for two-factor authentication is not installed. Use the Perl Modules page in Webmin to install it.`
Even after system reboot.

> I have no clue what those packages are from. They might.
It's Authen-OATH-2.0.1 but in RPM package. And all it's decencies. Built from source specially for this task to avoid process of building.

**Comment by dvolozhinok** [comment]
I've thought that maybe VM template is a problem origin. But another VM template from another virtualization cluster lead to the same error. Absolutely the same problems.

**Comment by jcameron** [comment]
If you SSH in and run `perl -e 'use Authen::OATH'` , what does it output?

**Comment by pixel-paul** [comment]
Apologies for jumping in on this, but I am having exactly the same issues with CentOS 7, after following @iliaross steps. 

yum cannot find: 

```
No package perl-Moo available.
No package perl-Test available.
No package perl-Math-BigInt available.
No package perl-Type-Tiny available.
```

Output from perl -e 'use Authen::OATH':

```
Can't locate Moo.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /usr/local/share/perl5/Authen/OATH.pm line 8.
BEGIN failed--compilation aborted at /usr/local/share/perl5/Authen/OATH.pm line 8.
Compilation failed in require at -e line 1.
BEGIN failed--compilation aborted at -e line 1.
```

**Comment by iliaross** [comment]
> Apologies for jumping in on this, but I am having exactly the same issues with CentOS 7, after following @iliaross steps.

You're right, I forgot to mention that you also need `epel-release` package installed.

~~~
yum install epel-release
yum clean all
yum install perl-Digest-SHA1 perl-Digest-HMAC perl-Moo perl-Test perl-Authen-SASL perl-Math-BigInt perl-Test-Needs perl-Type-Tiny
~~~

**Comment by iliarostovtsev** [comment]
..  with CentOS 7.9 things keep changing. It is indeed no longer works! Uff. 

@pixel-paul 

> yum cannot find:
> No package perl-Moo available.
> No package perl-Test available.
> No package perl-Math-BigInt available.
>No package perl-Type-Tiny available.

Unfortunately, it's true. You can make sure that you have `gcc` installed and try to compiling all needed modules manually (not recommended).

The other more reliable and probably cleaner, and easier way to solve this is to understand what Perl module is missing exactly,  by running `perl -e 'use Authen::OATH;'` (which should be installed already by Webmin at the first step mentioned [above](https://github.com/webmin/webmin/issues/1329#issuecomment-729686560)), which would return an error on missing dependency - look at the mentioned line in the error message and you would see, for example:

**Error:**

~~~
BEGIN failed--compilation aborted at /usr/share/perl5/vendor_perl/Method/Generate/Constructor.pm line 4.
~~~

**File:**
~~~
1 package Method::Generate::Constructor;
2
3 use Moo::_strictures;
4 use Sub::Quote qw(quote_sub quotify);
5 use Sub::Defer;
6 use Moo::_Utils qw(_getstash _getglob);
7 use Moo::_mro;
~~~

.. afterwards go and try installing missing packages by converting missing Perl module name to a package name. For example, missing `Sub::Quote` would be called on all RHEL systems `perl-Sub-Quote` and `libsub-quote-perl` on Debian/Ubuntu (just an example, as you don't need this for Ubuntu/Debian as `libauthen-oath-perl` available already).

.. but the problem is that neither `perl-Sub-Quote` nor `perl-Moo` available on CentOS 7.9. 

There are other, third-party repos, which provide those for CentOS 7, and one of them is OpenFusion (by Gavin Carr @gavincarr), which I could recommend, and which you could install as :

~~~
yum install https://repo.openfusion.net/centos7-x86_64/openfusion-release-0.8-1.of.el7.noarch.rpm
~~~

.. afterwards run : 

~~~
yum clean
yum install perl-Moo perl-Sub-Quote perl-Type-Tiny
~~~ 

.. and afterwards, running `perl -e 'use Authen::OATH;'` should return no errors on CentOS 7.9 too. If it still does, follow steps above, to figure out which modules are missing, and tell us later which are those.

@gavincarr Gavin, first of all thank you for maintaining the repo! I would like to ask, on top of everything and what you are already building, wouldn't that be too hard and time consuming to add `perl-Authen-OATH` to your repos as well?

**Comment by gavincarr** [comment]
Hi Ilia,

On Fri, Nov 27, 2020 at 02:40:33AM -0800, Ilia Rostovtsev wrote:
> @gavincarr Gavin, first of all thank you for maintaining the repo! I
> would like to ask, on top of everything and what you are already
> building, wouldn't that be too hard and time consuming to add `perl-Authen-
> OATH` to your repos as well?

Thanks for the kind words. No, it's not hard to add Authen::OATH into
the mix - it should be available in the repo now.

Cheers,
Gavin

**Comment by iliarostovtsev** [comment]
Gavin, thanks a lot. I was going to give it a try but the repos look down?

![image](https://user-images.githubusercontent.com/4426533/100476899-da275c00-30f7-11eb-89b9-2090d110e3aa.png)

**Comment by iliarostovtsev** [comment]
Gavin, before I gave it a test using `https` (which returned an error) but using `http` repo works just fine.

I can confirm that it's getting installed as expected, with the only unresolved dependency problem.

![image](https://user-images.githubusercontent.com/4426533/100477893-b580b380-30fa-11eb-8f82-2fceb27914aa.png)


.. and unresolved dependency is `perl-Sub-Quote`, which requires manual installation. Do you think you could fix it?

![image](https://user-images.githubusercontent.com/4426533/100478061-1f00c200-30fb-11eb-8502-372008384515.png)

**Comment by gavincarr** [comment]
Hi Ilia,

It's not Authen::OATH, it's the Moo module that requires Sub::Quote, and
the dependencies were slightly wrong. Can you try now?

Cheers,
Gavin

**Comment by iliarostovtsev** [comment]
Gavin, now it works just flawlessly. Thank you very much!

For the future reference, and anyone wanting to setup Google Authenticator for Webmin on CentOS 6, 7 or 8 (by installing missing `perl-Authen-OATH` without compiling missing Perl modules), simply install Gavin Carr's **Open Fusion RPM Repository** `.rpm` file (CentOS [6 link](http://repo.openfusion.net/centos6-x86_64/openfusion-release-0.8-1.of.el6.noarch.rpm), [7 link](http://repo.openfusion.net/centos7-x86_64/openfusion-release-0.8-1.of.el7.noarch.rpm), [8 link](http://repo.openfusion.net/centos8-x86_64/openfusion-release-0.8-1.of.el8.noarch.rpm)) run `yum clean` afterwards and go to Webmin to install everything automatically.

As well, using console it could be done as follows.

**CentOS 6**

~~~
yum install http://repo.openfusion.net/centos6-x86_64/openfusion-release-0.8-1.of.el6.noarch.rpm
yum clean all
yum install perl-Authen-OATH
~~~


**CentOS 7**

~~~
yum install http://repo.openfusion.net/centos7-x86_64/openfusion-release-0.8-1.of.el7.noarch.rpm
yum clean all
yum install perl-Authen-OATH
~~~


**CentOS 8**

~~~
yum install http://repo.openfusion.net/centos8-x86_64/openfusion-release-0.8-1.of.el8.noarch.rpm
yum clean all
yum install perl-Authen-OATH
~~~

@gavincarr Gavin, perhaps adding additional repo file to link to the latest repo release, like `openfusion-release-latest.of.el8.noarch.rpm`, could help for references from a distant future.

**Comment by dvolozhinok** [comment]
```
yum install http://repo.openfusion.net/centos7-x86_64/openfusion-release-0.8-1.of.el7.noarch.rpm
yum clean all
yum install perl-Authen-OATH
```

This solution does work on CentOS 7
After installing Webmin panel shows:

```
The Webmin server process is now restarting - please wait for a few seconds before continuing.

You can now enroll for two-factor authentication in the Webmin Users module.

To learn more about Google Authenticator, see it's website at http://en.wikipedia.org/wiki/Google_Authenticator.
```

Enroll works.
Thank you!

**Comment by voron** [comment]
I have to use
```
yum install http://repo.openfusion.net/centos7-x86_64/openfusion-release-0.8-1.of.el7.noarch.rpm
yum clean all
yum install perl-Authen-OATH perl-Moo perl-Sub-Quote perl-Type-Tiny perl-Exporter-Tiny
```
to get it working on CentOS 7
```
# perl -e 'use Authen::OATH;'
#
```

**Comment by iliajie** [comment]
There is no need for this, as Webmin now bundles `Authen::OATH` module.
