### ISSUE TITLE
Documentation is down

### ISSUE THREAD

**Issue by pavelklecansky** [webmin/webmin#1330]
I don't know if it just my problem but can't [documentation site](http://doxfer.webmin.com/Webmin) . 
![image](https://user-images.githubusercontent.com/28779692/99553187-24089780-29be-11eb-8445-9390307ffcd5.png)
Can someone please explain why is that ? Thank you.

**Comment by ColdForest** [comment]
I've been seeing this for last 1-2 days as well....

**Comment by ColdForest** [comment]
Anyone know what's up with the documentation site (still down)? Are others seeing this too?

**Comment by iliarostovtsev** [comment]
Yes, it's still down. @swelljoe is going to fix it in the near future. Sorry about this.

**Comment by gitowiec** [comment]
I can't access doxfer.webmin.com/Webmin/Main_Page
Please fix it, because I just installed webmin and I don't know what to do next!

**Comment by iliarostovtsev** [comment]
It's been fixed! Sorry about the delay!

**Comment by ColdForest** [comment]
thx!
