### ISSUE TITLE
failure upgrading to Webmin 1.962 (from 1.960) on Ubuntu server 20.04.1

### ISSUE THREAD

**Issue by FBachofner** [webmin/webmin#1331]
Webmin notifies an upgrade is available.

After pressing the "Upgrade Webmin Now" button in the dashboard . . .

```
Running setup.sh script to upgrade Webmin .. Please wait a minute until it is complete before continuing.

/bin/sh: 1: cd: can't cd to ../../webmin-1.962

```
I'm not sure from which directory the upgrader is trying to CD, but /usr/share/webmin-1.962 is already there !

Interestingly,  /usr/share/webmin-1.962  is owned by "3001:uucp"   I have never looked into the Webmin upgrade process in this detail before, but this seems potentially germane.  Perhaps "3001:uucp" does not have access to "cd" (although that seems odd -- changing dirs is not quite the same as read/write/execute permissions)

I have this happening on a number of similarly configured servers.

Thanks in advance for any insights or confirming this is a bug.

**Comment by FBachofner** [comment]
Additional consideration:

LinuxMint 20 (based on Ubuntu 20.04) does not seem to ever experience this problem.

However, on LinuxMint installations I help manage, Webmin appears to be installed in   /usr/share/webmin  (i.e. no version number), so there is already a significant difference in the installations.

**Comment by jcameron** [comment]
How did you install Webmin originally on this system? Was it from a .deb file, or a .tar.gz ?

**Comment by webmst** [comment]
I found the following error in /var/log/webmin/miniserv.error -  repeated several times - that allegedly accounts for all the failed attempts to upgrade:

`Use of uninitialized value $mode in chop at /usr/local/lib/webmin-1.960/webmin/webmin-lib.pl line 1776.`

(I'm running webmin-1.960 on several FreeBSD servers and the upgrade procedure failed to either 1.961 or 1.962)

**Comment by KDA54** [comment]
I'm having the same problem - Ubuntu 20.04, upgrading Webmin from 1.960 to 1.962. In my case the log file is:
     /var/webmin/miniserv.error
but I'm getting the same messages - repeated 9 times:
    Use of uninitialized value $mode in chop at /usr/local/webmin-1.960/webmin/webmin-lib.pl line 1776.

Any suggestions on how I can push through this upgrade?

Thanks
Kevin

**Comment by chris001** [comment]
@webmst @KDA54 

> Any suggestions on how I can push through this upgrade?

You can brute force the upgrade by running `update-from-repo.sh` 
On Debian, run the command : `/usr/share/webmin/update-from-repo.sh`
Find the location of the shell script on your OS distro, run: `locate update-from-repo.sh`
If no results, run `updatedb &`

**Comment by swelljoe** [comment]
Don't use the tarball to install on a system that has packages. And, don't use the update-from-repo.sh script unless you're developing or desperately need some specific fix and can't apply the patch manually.

**Comment by webmst** [comment]
@swelljoe
I agree with what you said (prefer packages to tarballs and mass update from repo when really necessary), still (I guess) webmin is always installed from a package first  and then automatically upgraded from a tarball. Anyway, to understand how to patch it manually, I've seen that the `webmin-lib.pl` file on the repo (updated 14 days ago) is different from the automatically donwloaded tarball I have and `upgrade.cgi` on the repo was also modified yesterday. What would you suggest in this case? To copy those 2 files to our systems?

**Comment by FBachofner** [comment]
Hi @jcameron 

> How did you install Webmin originally on this system? Was it from a .deb file, or a .tar.gz ?

.deb file.

I always do the following:

1. add the PPA to my system
2. wget the "jcameron-key.asc" and
3. finally `sudo apt-get install webmin` (after updating my repositories)


Thanks for any insights!

**Comment by jcameron** [comment]
Very odd that it's attempting to upgrade from a tar.gz then!

You should be able to upgrade by just running `apt-get install webmin`

**Comment by FBachofner** [comment]
Hi Jamie (@jcameron)

> Very odd that it's attempting to upgrade from a tar.gz then!

This (upgrading from the Webmin dashboard, which I guess you are saying invokes the tar.gz file) has always worked before (I probably first used Webmin >6 years ago).

If you think about it, it's a GREAT (even if not originally intended) feature.  Such a case does not require logging into the server with SSH to `sudo apt-get install webmin` or any other method (i.e. `apt-get update && apt-get upgrade` ).

It has also reliably allowed me to update Webmin much _earlier_ than the PPA is ever updated.  :-)

 
> You should be able to upgrade by just running `apt-get install webmin`

When I have done that in the past it seemed to bork my customized Webmin configuration.

Also, at that point the newest version has probably not shown up in the repository anyway, or it would have already upgraded automatically during a scheduled `apt-get update && apt-get upgrade` . . . right?


As always, thanks for your attentiveness.  I am so impressed with your efforts on this supremely useful tool!

**Comment by jcameron** [comment]
What Webmin *should* do when upgrading from the dashboard is download the same format package as was used originally - so if you installed from a .deb (either with dpkg or using apt-get), the upgrade should also be to a .deb. It's the same code as the tar.gz that we release at the same time, so there's no downside..

I just re-tested this on a Debian 10 system, and it worked as expected for me..

**Comment by iliarostovtsev** [comment]
> I just re-tested this on a Debian 10 system, and it worked as expected for me..

It also works as expected for me on RHEL.

@FBachofner What file `/usr/share/webmin/install-type` contains on your system?

**Comment by FBachofner** [comment]
Hi @iliaross 

Thanks for your interest.  [ your authentic-theme skin for Webmin is awesome! ]

**_Interesting!_** `/usr/share/webmin` does not exist at all.

Meanwhile, `/usr/share/webmin-1.960/install-type` _contains not a single entry_  (on the LinuxMint computer from where I am writing, the entry in `/usr/share/webmin/install-type` is `deb` which is what I would expect from my installation type).  Webmin works fine on both machines.

@jcameron what folders would I expect in a properly upgradeable Webmin installation **_on Ubuntu_**?  I ask because:

- the Webmin folder structure has also seemed different to me in the past (between Ubuntu and LinuxMint) -- seems strange given how closely related these projects are (LM is based on Ubuntu . . . recently the LTR version which is identical on both machines I am using to compare).
- sometimes I may be a bit aggressive on folder pruning and because the upgrader is complaining about a folder not being there (_although_ `/usr/share/webmin-1.962` folder which is in the process of being installed _is_ already there!). 
- perhaps I deleted something that doesn't affect other functionality in Webmin?

[ Please note: while `/usr/share/webmin` is "missing" on the machine is question, Webmin works fine.  Nothing is working because of any caching, either.  The machine has been rebooted after a kernel upgrade and Webmin continues to work. ]

So, on the "non-dashboard-upgradeable" Ubuntu box . . . in addition to `/usr/share/webmin-1.960` I have:

- `/etc/webmin`
- `/usr/share/webmin-1.962`  the version to which I am attempting to upgrade

I have various other Webmin-related symlinks, docs, services and other stuff (in `/sys/fs/cgroup` and `/sys/kernel/slab`) and so forth, but the above list seems comprehensive for actual program files.


BTW, if it makes any difference, the server in question was probably first "Webmined" with version 1.670, on or about 2014-01-24.  Ubuntu has been in-place upgraded 3x from 14.x ---> 16.x ---> 18.x ---> 20.04.1

**Comment by maddox32** [comment]
I have exactly the same occurring as described in the initial post: failed install, and the 1.962 folder owned by user 3001.

In this case, it occurs on MacOS 10.15 Catalina, originally installed via tar.gz, and several times updates via the dashboard without issue.  webmin folders are /usr/local/webmin-1.96x, /usr/local/etc/webmin en /usr/local/var/webmin.

As a check, I ran the setup.sh with sudo directly from the webmin-1.962 folder, and that resulted in an, at first sight, healthy fresh install.

**Comment by shades-aus** [comment]
I also had issues doing upgrades to a freshly installed system via the Software repository in Ubuntu.

For some reason, there are some expected requirements that are not in the install script that you need to install first. 
The additional packages I needed to be installed were "git" and "curl" so running "sudo apt install git curl -y" without the quotes, did fix it for me.
I then followed the advice from **chris001** posted above. 6th post I believe.

"**chris001**
You can brute force the upgrade by running update-from-repo.sh
On Debian, run the command : /usr/share/webmin/update-from-repo.sh
Find the location of the shell script on your OS distro, run: locate update-from-repo.sh
If no results, run updatedb &"

**Comment by FBachofner** [comment]
Sorry I forgot about this open issue.

As best as I can tell, all my servers are now successfully updated to 1.973.

I think this issue (failure to upgrade to 1.962) was resolved (i.e. magically went away!) around the time 1.97x was released.

This upcoming weekend I will see whether I have any "straggler" servers I have "forgotten" about.

**Comment by swelljoe** [comment]
> I then followed the advice from **chris001** posted above. 6th post I believe.
> 
> "**chris001**
> You can brute force the upgrade by running update-from-repo.sh
> On Debian, run the command : /usr/share/webmin/update-from-repo.sh
> Find the location of the shell script on your OS distro, run: locate update-from-repo.sh
> If no results, run updatedb &"

I just saw this, and I want to say: Do not do this. This is *not* upgrading using a package. It is updating directly from the development git repository, which is _not_ a package. It should only be done if you are a developer working on Webmin-related stuff or testing a specific bugfix and a developer (me, Jamie, Ilia, or Kay, probably) has told you to do so (and I will never tell you to do so, because I think it is too risky for non-devs to try to use it).

This should never be the way Webmin is installed on a production server.

**Comment by KDA54** [comment]
No problem!

 

I manually upgraded my systems to use 1.962 (IIRC), and then everything was fine. The problem was in 1.960.

 

Cheers

 

Kevin
