### ISSUE TITLE
failure to change "Hosts" to "any" in its config right after installation of mariadb

### ISSUE THREAD

**Issue by gitowiec** [webmin/webmin#1333]
Steps to reproduce:
1. Install Webmin on Debian 10 VPS
2. Login and click Un-used Modules, choose Mysql Database Server
3. Install MariaDB through option in the module.
4. Click User Permissions
5. Choose root
6. Change "Hosts" to "any" (leaving password set to None)
7. Click "Save" and observe error message like this:
 ```
Failed to save user : SQL set password for 'root'@'%' = password('') failed : Can't find any matching row in the user table
```

**Comment by jcameron** [comment]
@iliaross could this be related to changes you were making in the MySQL module? Ideally if the password mode isn't changed, no "set password" command will be run.

**Comment by iliarostovtsev** [comment]
> Failed to save user : SQL set password for 'root'@'%' = password('') failed : Can't find any matching row in the user table

Confirmed.

>  could this be related to changes you were making in the MySQL module? Ideally if the password mode isn't changed, no "set password" command will be run.

@jcameron The only obstacle is that we need to have an ability to properly set password to **None**.

I will work on it..

**Comment by iliarostovtsev** [comment]
Okay, this issue was fixed, plus additionally:

 1. Allow renaming admin user and/or password without loosing connectivity
 2. Prevent locking admin accounts
 3. Other improvements

Known bugs - host isn't saved. _ALTER_ user doesn't work with accounts without passwords.

**Comment by iliarostovtsev** [comment]
Okay, [finalizing changes](https://github.com/webmin/webmin/commit/4ab8bdc11d027163091059029084cedbd1226441). Everything must work now! Thanks for reporting!
