### ISSUE TITLE
Archived files are gone from webmin

### ISSUE THREAD

**Issue by muhammadwafa** [webmin/webmin#1334]
Here is my Files

    1. file1.txt
    2. file2.txt
    3. file3.txt

I selected **file1.txt** and **file2.txt**

Then I clicked  **Create new archive**
I checked the **Move to archive**

Now **file1.txt** and **file2.txt** are gone

**How and where can I find them ?**

**Comment by iliarostovtsev** [comment]
Hi,

> .. Then I clicked Create new archive. Now file1.txt and file2.txt are gone. How and where can I find them ?

If you move files to an archive they are moved to the archive (reside on inside if the archive). Like if you move your car to a garage, it's no longer on the street.

If you want your files to be simply archived, do not move them to the archive. 😉 

> How and where can I find them ?

Unarchive a newly created archived file (found on the same directory).

**Comment by muhammadwafa** [comment]
Thank you very much for your reply.

We guess that checking the checkbox "move files" does move the files into the archive and removes them from the disk while all files were copied into the archive when this checkbox is unchecked.

However, it seems that there was no archive created as we were not able to find any file with an ending like tar.gz. We searched for such files using the following command:

find / -iname *.tar.gz

This command does unfortunately not return any result.

We then created a test folder at /home/files and some files and sub folders in it. Afterwards we tried to create an archive by checking the checkbox "move files"
in the first step and on a second step we kept this checkbox unchecked. In both cases no archive was created. Then we found out, that the command 'tar' was not installed. This command is usually used to create tar.gz archives. After installing this command we were able to create an archive successfully. The archive was created in the same folder.

According to this, we unfortunately have to say that it seems that the files are irrecoverable lost, we are afraid. It seems that the file manager of Webmin fails silently in case the tar command was not found but the files were deleted in any way. This is of course a serious bug in Webmin which should not happen. However, since we are not the developer of this panel, it is unfortunately out of our scope, we kindly ask for your understanding.

**Comment by iliarostovtsev** [comment]
Good Lord! Who would've thought that `tar` command would miss!?

> This is of course a serious bug in Webmin which should not happen. 

Certainly this is! We will fix that! Sorry about this!

Is this CentOS 8?

**Comment by ghost** [comment]
Hi @iliaross thank you.
Yeah CentOS 8 on VPS server.

**Comment by muhammadwafa** [comment]
This problem happend for me when `tar` was not installed on CentOS 8

**Comment by muhammadwafa** [comment]
Unfortunately I didnt had any copy of those files and Now I am have to start from zero on my app.

**Comment by iliarostovtsev** [comment]
I have reworked how it's archive compress/extract is handled. This kind of issue should never happen again.

Sorry and thank you for reporting!

Next Webmin release will have it fixed. Meanwhile, you could install development version of the theme to give it a try.

> This problem happend for me when tar was not installed on CentOS 8

@jcameron Jamie, `tar` command is essential, let's set it as a dependency.

**Comment by jcameron** [comment]
I'm actually surprised that any system is missing the `tar` command, since it's been a fundamental Unix tool for decades!

I'll add it to our package dependencies.
