### ISSUE TITLE
Cluster user config no longer works. Automatic home directory is not being populated

### ISSUE THREAD

**Issue by jkast90** [webmin/webmin#1336]
![image](https://user-images.githubusercontent.com/45980291/101421338-4b61ce80-38b1-11eb-92da-4e2011e3c1dd.png)

![image](https://user-images.githubusercontent.com/45980291/101421355-57e62700-38b1-11eb-8571-48cce32991dc.png)

**Comment by jkast90** [comment]
version 1.962

**Comment by jcameron** [comment]
I see the bug that causes this - it will be fixed in the next Virtualmin release.

**Comment by iliarostovtsev** [comment]
> I see the bug that causes this - it will be fixed in the next Virtualmin release.

@jkast90 I'm sure Jamie meant next Webmin release.

**Comment by jcameron** [comment]
Yes, that's what I meant
