### ISSUE TITLE
APT repository access fails due to untrusted certificate

### ISSUE THREAD

**Issue by MichaIng** [webmin/webmin#1337]
For reference: https://github.com/MichaIng/DietPi/issues/3961
```
Err:7 https://download.webmin.com/download/repository sarge Release
  Certificate verification failed: The certificate is NOT trusted. The certificate issuer is unknown.  Could not handshake: Error in the certificate verification. [IP: 108.60.199.109 443]
```
Strangely browsers and `openssl s_client` show the certificate perfectly valid.

**Comment by jcameron** [comment]
Which Linux distro are you running there?

**Comment by MichaIng** [comment]
DietPi, i.e. Debian. Same result on Buster and Bullseye and from different locations. It worked well until a few hours ago (based on user report).

**Comment by MichaIng** [comment]
Okay, it is the HTTPS certificate and it is trusted in ~50% of the tests and 50% of cases not when doing repeated accesses through APT, apt update or apt install are both affected the same way. Check the issue on our repository, strange thing 🤔.

**Comment by jcameron** [comment]
Yes, there are two webservers - there is a bit of delay between re-syncs of the cert.

**Comment by MichaIng** [comment]
That might be the issue then, if one was signed by the "new" Let's Encrypt `R3` intermediate while the other one still with the older `Let's Encrypt Authority X3` intermediate. At least that is what seems to not match between intermediate and root certificate in case of the failing requests.

Probably all is sorted soon 🙏.

**Comment by MichaIng** [comment]
Seems to be sorted, both server now serve certificates with the correct new `R3` intermediate.
