### ISSUE TITLE
[Question] webmin url in email notifications

### ISSUE THREAD

**Issue by pedrom34** [webmin/webmin#1338]
Hey,

I have webmin on my selfhosted server, it's reachable on http://localip:10000. From the outside, I use a nginx reverse proxy, and I access webmin from https://webmin.domain.tld/

Everything is working great, except that when I receive a notification for packages updates the email reads this:
Updates can be installed at
http://hostname:10000/package-updates/

How can I change this address to the one I specified in nginx?

**Comment by iliarostovtsev** [comment]
Hi,

I don't think it's currently possible, as when notifications are generated `get_system_hostname()` is used to extract the actual hostname.

**Comment by jcameron** [comment]
Correct, this can't be changed currently.

**Comment by iliarostovtsev** [comment]
Should we make this configurable?

**Comment by pedrom34** [comment]
> Should we make this configurable?

Well, if you ask me... :smile:

**Comment by jcameron** [comment]
Yes - I'll update this ticket with progress.

**Comment by jcameron** [comment]
Ok, this has been implemented for inclusion in the next Webmin release.

**Comment by pedrom34** [comment]
Hey @jcameron 

Can you tell me where can I find this option now that it has been implemented? Because, I cannot find it haha 😭 

Thanks!

**Comment by iliarostovtsev** [comment]
> Can you tell me where can I find this option now that it has been implemented? Because, I cannot find it haha sob

Have a look at **Webmin > Webmin Configuration > Sending Email** page and there will be an option called **From address for email from Webmin**:

![image](https://user-images.githubusercontent.com/4426533/104438639-41627800-55a1-11eb-99c8-81ef1c0eee7f.png)

**Comment by pedrom34** [comment]
Thank you, that did the trick 😄
