### ISSUE TITLE
Webmin Version 1.680 breaks Dansguardian Version 2.10.1.1

### ISSUE THREAD

**Issue by prgwiz** [webmin/webmin#136]
Upgrading Webmin to 1.68 from the previous version breaks "View/Edit A Filter Group's Lists".  I have verified this on 2 separate servers.

**Comment by shoulders** [comment]
this should be closed because it is not really a bug as @jamies says

> Ok, that explains it - that is a new security feature in Webmin to block unsafe use of JS that may result from XSS attacks. To turn it off, add the line no_content_security_policy=1 to /etc/webmin/config
