### ISSUE TITLE
Server communications are lost when adding a virtual interface

### ISSUE THREAD

**Issue by E-Rosello** [webmin/webmin#1426]
Hi, 
I've recently started to use webmin & virtualmin on a fresh server at SoYouStart (OVH) with some additional IP Fail Over adresses.
To avoid any possible mess, I used the virtalmin installation script just after installing Ubuntu 20.04 LTS on the server.
I think both tools are really great with such a smotth installation process!

My objective is to have virtual servers each of them with a specific dedicated address.
Originally everything went as expected but when trying to reboot the server after creating the first virtual server I was no longer able to ping the server and I had to restart in "rescue mode" to edit the /etc/netplan/50-cloud-init.yaml file and remove the "addresses:" entry.

I've also tried to use the OVH document (https://support.us.ovhcloud.com/hc/en-us/articles/360014248820-How-to-Configure-IP-Aliasing-on-a-VPS) as a guide line, but I believe webmin is also modifying some the configuration files and I'm rapidly getting lost.

I don´t understand either why the Loopback is not present in the list of interfaces activated at Boot.

Now, everytime I try to add a virtual interface to en0l the communications are lost.

Is this related with https://github.com/webmin/webmin/issues/1269 ?

Thanks in advance for your suggestions and help!

**Comment by iliarostovtsev** [comment]
Hi,

If you manually upgrade to Webmin 1.970 will it solve the problem?

~~~
wget http://download.webmin.com/devel/deb/webmin_1.970_all.deb
apt-get install ./webmin_1.970_all.deb
~~~

**Comment by E-Rosello** [comment]
Hi, and thank you so much for your quick reply.
Right know I'm on Webmin 1.962 + Virtualmin 6.14.
I will try to update and get back to you shorthly.

Rgds:

Eric

**Comment by E-Rosello** [comment]
Hi Again,

Thank for the advise, Definetely better, now I was able to add the additional IPs without crashing the network but still something weird going on.

This is my initial configuration for the single (as far I know) network interface:
![eno1](https://user-images.githubusercontent.com/77150242/104037550-0c3adc00-51d5-11eb-8168-ef9eee480b55.jpg)

Now I'm adding the 3 additional IPs (only the first one is currently assigned to a virtual server)
![VirtInt](https://user-images.githubusercontent.com/77150242/104038531-879c8d80-51d5-11eb-877b-7c1daf3644c9.jpg)

With all of them selected, only the first one became active.
To activate all of them I had to select them again and activate one by one.
Finally they were all active and responding:
![IpAddr](https://user-images.githubusercontent.com/77150242/104038920-ff6ab800-51d5-11eb-8f3c-77cdd7e2e636.jpg)

But even with all of them responding they are not listed as active:
![VirtIntAct](https://user-images.githubusercontent.com/77150242/104040955-946eb080-51d8-11eb-8660-77b310ebb6b3.jpg)

And then unfortunately, if I reboot the server, the communication is lost again and I have to reboot in rescue mode.
Is it a conflict with the virtual interfaces been created before the DHCP has been completed?
I 'm doing something really stupid (excuse me if it is the case)?

Thanks again!

**Comment by iliarostovtsev** [comment]
> This is my initial configuration for the single (as far I know) network interface:

Please convert DHCP to Static configuration!

**Comment by E-Rosello** [comment]
Hi, I thought inserting network: {config: disabled} in /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg (https://support.us.ovhcloud.com/hc/en-us/articles/360014248820-How-to-Configure-IP-Aliasing-on-a-VPS) would allow the configuration to remain after a reboot without having to turn off the DHCP.
In any case, I have followed your advise and removed the DHCP configuration and provided static addresses, but I'm afraid the problem remains the same. After a reboot the server is no longer responding.
I know the server is not suposed to be rebooted, but I don´t feel confortable and I would really like to figure out were's the problem and how to solve to be on the safe side.

Thanks again for your patience and great help!

PS: When looking at the active interfaces, it looks like the last one is never displayed.

**Comment by iliarostovtsev** [comment]
Server must have an ability for a reboot.

What is the output of the files under `/etc/netplan` before and after they changed by Webmin, and then after reboot? 

If you configure it manually, does it survive the reboot? Did you ask your service provider about cloud init scripts?

**Comment by E-Rosello** [comment]
Good morning,

I've looked at the /var/log/cloud-init.log but my knowledge is too limited to identify when things go wrong. (no obvious error message)
From what I see webmin is only adding the additianl IPs in the addresses: section of the  /etc/netplan/50-cloud-init.yaml and this seems to work.
I have the feeling the issue is on the sequencing during the boot/initialisation phase and I'm have found a workaround.
I have now two files in /etc/netplan:
- 01-cloud-init.yaml uses DHCP and has no additional addresses
- 50-cloud-init.yaml no DHCP and has the virtual interfaces addresses

Thanks to the 01 prefix this file is read first and with this sloppy arrangement I can reboot and have the virtual interfaces enabled and working once the second file (50-cloud-init.yaml) is scanned.
This is how the result looks like in webmin:
![TwoCfg](https://user-images.githubusercontent.com/77150242/104086527-0d155180-5259-11eb-91b4-2aae441d3da4.jpg)

I will open a ticket with my service provider but from my experience it may take a while before I get anything back...
I understand my workaround may look terrible to you and therefore I'm open to better suggestions or let me know if you anticipate any issues with this solution.

Thanks again!

**Comment by E-Rosello** [comment]
After applying a recent Ubuntu 20.04 LTS update, I noticed that after the required reboot 50-cloud-init.yaml was over written again.
I decided to use the approach described in my previous post but leaving 50-cloud-init.yaml unchanged and adding a 90-cloud-init.yaml file where I create the virtual interfaces with the additional IP addresses.
This appears to work, and the configuration survived the update and consequent reboot.
No news from my ISP :-( 
If anybody has a better/recomended solution, please feel free to comment.

**Comment by jcameron** [comment]
So the Ubuntu update over-wrote 50-cloud-init.yaml? I wonder where it's getting the source of truth for that file from..

**Comment by E-Rosello** [comment]
Hi Jamie,

When I logged in webmin few days ago there was a bunch of packages to be updated (I should have taken a snapshot :-(  ), few of them related to netplan and the source was "Focal-updates".
After updating and rebooting I had again issues with virtual interfaces and then realised that 50-cloud-init.yaml had been modified.
I don't know if this is relevant but I believe my ISP is using Kubernetes (https://microk8s.io/high-availability) to manage his servers.
I don´t know what is the root cause of these changes so I'm just trying to find a way to cope with it to have a stable and reliable configuration.
Perhaps I´m missing something really obvious or doing something really stupid...?

**Comment by iliarostovtsev** [comment]
It is hard to say offhand why that might be happening but simple work around would be is to prevent config _50-cloud-init.yaml_ file modification, like:

~~~
chattr +i /etc/netplan/50-cloud-init.yaml
~~~

.. reboot and later check the logs for possible errors for helping figuring out the source of the problem.

**Comment by E-Rosello** [comment]
Hi Ilia, thank you for your input.
I also thought about this possibility, but I was concern about other issues it could cause...
I believe the file is overwritten only in certain circumstances and I don´t know how to reproduce them.
In addition, if the network interface crashes the ISP recovery process is a time consuming exercise.
Unfortunately I have to focus on the installation and configuration of additional packages, so I believe I´m going to leave it as it is at the present...
