### ISSUE TITLE
How to set static IP on Bonded network Interface

### ISSUE THREAD

**Issue by rdewild** [webmin/webmin#1427]
I have a Ubuntu Linux 20.04.1 server with two 1GB NIC cards. During Ubuntu Installation the interfaces were bonded
I installed and use Webmin 1.970
The system is performing well. However, The IP address is dynamic which does not work in my environment. During a reboot after upgrading Webmin earlier this week the IP address changed again. I know, I could reserve the address in my DHCP server, but prefer to have a static IP .
The Network Interfaces module in Webmin reports the following Active Now settigns:
bondeth1_eth2 Bonded                    192.168.1.240
eno1                 Ethernet 1000Mb/s  No address configured
enp2s0             Ethernet 1000Mb/s  No address configured 

When I try to change the IP address on the bondeth1_eth2 I get the following error when I save:
Failed to save interface : sh: 1: ifup: not found

My question is can I safely install ifupdown? Ubuntu removed it in 18.04.
Is there a better/safer way to manage the IP of my server. e.g. using Netplan outside of Webmin?

**Comment by rdewild** [comment]
I ended up using Netplan outside of Webmin.
I manually edited the file: /etc/netplan/00-installer-config.yaml

# This is the network config written by 'subiquity'
network:
  bonds:
    bondeth1_eth2:
      dhcp4: false
      addresses:
        - 192.168.1.87/24
      gateway4: 192.168.1.254
      nameservers:
              addresses: [192.168.1.254, 8.8.8.8, 8.8.4.4]
      interfaces:
      - eno1
      - enp2s0
      parameters:
        mode: balance-rr
  ethernets:
    eno1: {}
    enp2s0: {}
  version: 2

Then,  $sudo netplan apply to activate the new IP.

The server now has a static IP and I was able to reconnect with Webmin and it now reports the new static IP.
So, all good.
Hopefully this helps someone.

**Comment by jcameron** [comment]
Is Webmin correctly detecting that you're using Netplan? You should be able to see this on the first page of the Network Configuration module.

Unfortunately, right now we don't supported bonded interfaces in the Netplan config.
