### ISSUE TITLE
Upgrade Webmin from Version 1.962 to 1.970 on raspberry3b results in Perl Error

### ISSUE THREAD

**Issue by W-M-B** [webmin/webmin#1428]
Hello all,
yesterday Webmin propsed to upgrade  from Version 1.962 to 1.970.
I ran the upgrade process which completed without an error message.
in the webbrowser I log in and then get the Website with:
```
Error - Perl execution failed
Undefined subroutine &main::get_miniserv_config called at /usr/share/webmin/authentic-theme/session_login.cgi line 15. 
```
![210108-18_54_44-Mozilla Firefox](https://user-images.githubusercontent.com/46317115/104048253-36939600-51e3-11eb-81ac-06ff30269508.jpg)

I rebooted no difference
I deleted /etc/webmin and /usr/shared/webmin
manually downloaded webmin again and installed it
same.
this was on a blackberry 3b in active use since 11 month.
as I didnt find anything on the issue while googling I tried it on another raspberry pi 3b in use since 6 month.
Same result..

Any Idea how I can continue from this.
both rpis are patched to the latest version..

**Comment by iliarostovtsev** [comment]
Hi,

Thanks for the heads up.

Can you please post outputs of `/etc/webmin/miniserv.conf` and `/etc/webmin/config` with which it fails?

> Any Idea how I can continue from this.

Look at [this thread](https://forum.virtualmin.com/t/perl-error-after-webmin-update/108856/4?u=ilia) and [this thread](https://sourceforge.net/p/webadmin/bugs/5442/?page=1).

**Comment by W-M-B** [comment]
thanks for the workaround .. will do it after dinner :-)
 
> Can you please post outputs of `/etc/webmin/miniserv.conf` and `/etc/webmin/config` with which it fails?
sorry I dont understand what todo here .. is the a logfile or how do I run this? the /etc/webmin/ folder is actually more or less empty on my raspberries.. stop and uninstall.sh is available

**Comment by iliarostovtsev** [comment]
> sorry I dont understand what todo here 


What is the output of : 

~~~
cat /etc/webmin/miniserv.conf | grep preroot
~~~

and

~~~
cat /etc/webmin/config | grep theme
~~~

**Comment by W-M-B** [comment]
while trying to provide the information I found out that my tries to repair has deleted some files.
I ran the uninstall.sh and then installed the new version from scratch (no update).
and it works now on one machine. . I will repeat on the other one.
Sorry that I cannot provide the information you wanted.
but clean install (temporary) solved the issue as well and I will not switch themes for now
