### ISSUE TITLE
Failed to read systemd units

### ISSUE THREAD

**Issue by htttito** [webmin/webmin#1429]
Hi!
After update to 1.970 i have problems in the Module:
- Bootup and Shutdown
- Scheduled Commands
System is Ubuntu 20.04. server

![webmin](https://user-images.githubusercontent.com/40149753/104061981-e07e1d00-51f9-11eb-9666-4ccbb1d50a78.jpg)
![webmin2](https://user-images.githubusercontent.com/40149753/104061991-e411a400-51f9-11eb-8ae9-9cef587c8255.jpg)

**Comment by htttito** [comment]
I fix it by my own....
It was a kernel problem...i have installed the hwe-20.04 (5.8.0-36-generic)
Jump back to the old kernel and all is OK..

**Comment by BluCobalt** [comment]
Reverting to a 4.x kernel (was using elrepo kernel-ml) on RHEL 8 fixed this problem for me, too.
