### ISSUE TITLE
NFS exports fail

### ISSUE THREAD

**Issue by Bedenk** [webmin/webmin#1431]
Hi there, I run into this problem. Ubuntu 20.04 server. Webmin 1.970.

When i want to open a NFS export by click on it I get the following remarks.

Edit Export
HTTP/1.0 500 Perl execution failed Server: MiniServ/1.970 Date: Sun, 10 Jan 2021 21:49:09 GMT Content-type: text/html; Charset=utf-8 Connection: close
Error - Perl execution failed
Can't use an undefined value as a HASH reference at /usr/share/webmin/exports/edit_export.cgi line 25.

It seems to be a little bug I think.

**Comment by jcameron** [comment]
Yes - I'll fix this in the next release.
