### ISSUE TITLE
Upgrade Webmin from Version 1.962 to 1.970 results in Perl Error

### ISSUE THREAD

**Issue by PitWenkin** [webmin/webmin#1432]
I got an error on one server and then found #1428.
I could reproduce on a second (±similar) server:

System before update:

```
Operating system | Ubuntu Linux 16.04.5
Webmin version | 1.962
Usermin version | 1.812
Virtualmin version | 6.14 
Authentic theme version | 19.62
```

![Screenshot 2021-01-12 at 11 17 57](https://user-images.githubusercontent.com/45786226/104301882-6fc05480-54c8-11eb-840c-cef9c76204e2.png)

After clicking the `Upgrade Webmin Now` button the following happend while `Unpacking webmin`:

![Screenshot 2021-01-12 at 11 18 35](https://user-images.githubusercontent.com/45786226/104302389-0260f380-54c9-11eb-935f-697164d4098e.png)

And then when `Setting up webmin`:
![Screenshot 2021-01-12 at 11 18 55](https://user-images.githubusercontent.com/45786226/104303215-1b1dd900-54ca-11eb-8c4f-0d1923f2353d.png)

Both servers were however able to recover after ± one minute:
![Screenshot 2021-01-12 at 11 29 46](https://user-images.githubusercontent.com/45786226/104302804-85824980-54c9-11eb-9370-f8921d3ed5cd.png)

```
# cat /etc/webmin/miniserv.conf | grep preroot
preroot=authentic-theme
# cat /etc/webmin/config | grep theme
theme=authentic-theme
```

**Comment by iliarostovtsev** [comment]
Hi,

Thanks for the heads up. This issue should be addressed in Webmin 1.971 [devel](https://www.webmin.com/devel.html) version.

Manual installation link:

~~~
https://download.webmin.com/devel/tarballs/webmin-1.971.tar.gz
~~~

> cat /etc/webmin/miniserv.conf | grep preroot
> preroot=authentic-theme
> cat /etc/webmin/config | grep theme
> theme=authentic-theme

If that's all you got on the configs, then it should work. Try reloading Webmin manually using `/etc/webmin/restart` command. Does it help?

If not, upgrading to 1.971 manually fixes an issue for you?

**Comment by iliarostovtsev** [comment]
Did 1.971 work for you?

**Comment by ToddC-HV** [comment]
Yes - thanks!  Going to the devel version 1.971 worked and fixed the same issue I was having this morning when I upgraded and ran patches on 4 of our Ubuntu servers.  two upgraded and did the Webmin piece just fine to 1.970 and the other 2 failed with the referenced error.  I pulled down 1.971 and ran the setup again and I'm back into both systems now.

**Comment by PitWenkin** [comment]
Sorry I broke my development server, and don't realy want to try a development version on a a live server.
