### ISSUE TITLE
Webmin - DNSSEC - Resign takes 3+ hours

### ISSUE THREAD

**Issue by bbs2web** [webmin/webmin#1434]
We have our own IP assignments and subsequently have template reverse and forward records setup, for example:
```
[root@debian ~]# host 1.2.3.4
4.3.2.1.in-addr.arpa domain name pointer 1-2-3-4.connect.company.net.
[root@debian ~]# host 1-2-3-4.connect.company.net.
1-2-3-4.connect.company.net has address 1.2.3.4
```

The connect.company.net zone record is subsequently not small (13k+ records) so I would expect it to take a while to get resigned. The dnssec-tool however only runs for about 30 seconds with '/usr/bin/perl /usr/webmin-1.970/bind8/resign.pl' then taking an additional 3+ hours afterwards.

The majority of time is spent in the following functions:
```
for(my $i=$#recs; $i>=0; $i--) {
        if ($recs[$i]->{'type'} eq 'NSEC' ||
            $recs[$i]->{'type'} eq 'NSEC3' ||
            $recs[$i]->{'type'} eq 'RRSIG' ||
            $recs[$i]->{'type'} eq 'NSEC3PARAM') {
                &delete_record($fn, $recs[$i]);
                }
        }
my @signedrecs = &read_zone_file($fn.".webmin-signed", $dom);
foreach my $r (@signedrecs) {
        if ($r->{'type'} eq 'NSEC' ||
            $r->{'type'} eq 'NSEC3' ||
            $r->{'type'} eq 'RRSIG' ||
            $r->{'type'} eq 'NSEC3PARAM') {
                &create_record($fn, $r->{'name'}, $r->{'ttl'}, $r->{'class'},
                               $r->{'type'}, join(" ", @{$r->{'values'}}),
                               $r->{'comment'});
                }
        }
```

From my limited understanding of Perl it appears to simply remove all existing 'NSEC', 'NSEC3', 'RRSIG' and 'NSEC3PARAM' records from the zone file and then dumps all those record types from the signed file in to the primary zone file.
Seeing that Webmin puts DNSSEC records on a single line the following would at least remove the overhead on removing the records one by one:
```
grep -vw -e RRSIG -e NSEC -e NSEC3 -e NSEC3PARAM zonefile
```

Any ideas on optimising this? We're running BIND 9.12 which has support for in-line signing, does it fully automate resigning when required (eg editing a zone in Webmin or otherwise daily) and handle key roll overs?

**Comment by jcameron** [comment]
This could be an N^2 algorithm where the time for each record being deleted is proportional to the length of the file.

I'll take a look at the code and see if it can be optimized..

**Comment by jcameron** [comment]
I've checked in a fix for this (which you can see linked above), which will be included in the next Webmin release.

**Comment by chris001** [comment]
In favor of exploring the possibility of adding support for `BIND9` inline signing as it should eliminate possible issues since `BIND9` could automate its `DNSSEC` work.
