### ISSUE TITLE
Support using aptitude instead of apt-get

### ISSUE THREAD

**Issue by maicol07** [webmin/webmin#1435]
Hi,

can you add an option to select apt-get or aptitude? Currently, upgrades/installs can only be done with apt-get.

Thanks

**Comment by swelljoe** [comment]
Why would it make sense for Webmin to use aptitude? It can't interact with it, and that's the only benefit I'm aware of for using aptitude? It would, I think, be exactly the same for the user and would require more code to support aptitude as well.

**Comment by maicol07** [comment]
@swelljoe It is easier with Aptitude to solve package upgrades conflicts

**Comment by iliarostovtsev** [comment]
Actually, **Webmin > Software Packages** module on its configuration page already has an option to use _aptitude_ over _apt-get_.

![image](https://user-images.githubusercontent.com/4426533/105233423-e4575b00-5b7a-11eb-921a-f7ca851a8b4f.png)
