### ISSUE TITLE
No more CPU graph on webmin.

### ISSUE THREAD

**Issue by Silvers12** [webmin/webmin#1444]
Hi,
Today i see my CPU graph Disappeared. I don't know why and i don't know how can i show it ?

I'm on debian 10 
![image](https://user-images.githubusercontent.com/9714780/107360509-52d26d80-6ad6-11eb-9571-78f6fd2e1289.png)
Version Webmin : 1.970

![image](https://user-images.githubusercontent.com/9714780/107359607-2cf89900-6ad5-11eb-8529-9aa06a40f3d0.png)

![image](https://user-images.githubusercontent.com/9714780/107359626-33871080-6ad5-11eb-961e-b35e0d821a88.png)

![image](https://user-images.githubusercontent.com/9714780/107359670-413c9600-6ad5-11eb-99e4-4b7c84d06ddd.png)

Thx for your help ;)

**Comment by Silvers12** [comment]
OK i find it !!!
Just reinstall PHP7.4 and done !

**Comment by swelljoe** [comment]
What? That can't possibly be what solved it. Webmin doesn't use PHP for anything. It's all Perl.

**Comment by Silvers12** [comment]
I know ... But that's true ... strange
