### ISSUE TITLE
How to cluster webmin servers when behind nginx proxy server?

### ISSUE THREAD

**Issue by BobWs** [webmin/webmin#1445]
Hi,
I'm running webmin on two debian VM servers and accessing it via a reverse proxy server `webmin.mydomain.com`. So far so good.
But I would like to cluster the servers so I have added the second server to the Webmin server index and to Cluster Webmin Servers. 

But when I click on the added server in Managed Servers I get to see this:
![Screen_Shot 1](https://user-images.githubusercontent.com/5485820/107744823-a978bb00-6d13-11eb-869e-ed09c070b600.png)

![Screen_Shot 2](https://user-images.githubusercontent.com/5485820/107744940-d62cd280-6d13-11eb-8959-6a86dad1cf23.png)

**Comment by iliarostovtsev** [comment]
Hi,

It works for me!

The error your seeing on the first screenshot usually comes up when `theme-name` set for options `theme` and `preroot` are out of sync among `/etc/webmin/config` and `/etc/webmin/miniserv.conf`. This will not long be an issue in upcoming Webmin 1.972.
