### ISSUE TITLE
Any plans to support AlmaLinux 

### ISSUE THREAD

**Issue by hurricane66** [webmin/webmin#1446]
Hi.
Any plans to support AlmaLinux, a 1:1 binary compatible fork of RHEL 8 (https://almalinux.org/#about) ?

Some output from an AlmaLinux release 8.3 RC server:

cat /etc/redhat-release -> "AlmaLinux release 8.3 RC (Purple Manul)"
uname -srm -> "Linux 4.18.0-240.el8.x86_64 x86_64"

Thanks.

**Comment by iliarostovtsev** [comment]
Yes,

Good point. Thanks for reminding! I'll update this ticket later today when done.

**Comment by iliarostovtsev** [comment]
Okay, done. Thanks.

**Comment by iliarostovtsev** [comment]
https://github.com/webmin/webmin/commit/4c44b589fb1a4d9aaa5032eff8534b96ea21c227
