### ISSUE TITLE
Cronjob not working in combination with log notification 

### ISSUE THREAD

**Issue by BobWs** [webmin/webmin#1448]
Hi,
I’ve setup a cronjob to run on a schedule for updating my docker container and when I run the scheduled cronjob with this command `/home/User/script.sh ` everything works fine and my container is updated. 

But when I schedule a cronjob with this command ```/home/User/script.sh >/home/User/cronlog/`date +\%Y-\%m-\%d-\%H:\%M:\%S`-[name]-cron.log 2>&1``` The cronjob won’t run as scheduled. If I run it manually it works and I get my log output. 

Anyone an idea why the automated scheduled cronjob won’t start but then when I run it manually with  the command above it works. 

If anyone has a better solution for this so I can run scheduled cronjobs with a notification and log output I’m all ears. 
TIA

**Comment by iliarostovtsev** [comment]
Hi,

Thanks for contacting us. At first, I would like to remind everyone that Webmin GitHub repo is not Q/A resource and made for bug reports only. 😉 


> Anyone an idea why the automated scheduled cronjob won’t start but then when I run it manually with the command above it works.

Yes, perhaps shell is not set to Bash, as default shell for MacOS is Z shell (_zsh_) and it doesn't support such syntax.


> If anyone has a better solution for this so I can run scheduled cronjobs with a notification and log output I’m all ears.

Create a script that will look like:


~~~Bash
#!/bin/bash

/home/User/script.sh >/home/User/cronlog/`date +\%Y-\%m-\%d-\%H:\%M:\%S`-[name]-cron.log
~~~

.. and use it in your Cronjob.

**Comment by BobWs** [comment]
Oh, I’m sorry for the Q/A😰
Thanks for the tip anyway!

**Comment by iliarostovtsev** [comment]
> Oh, I’m sorry for the Q/A😰

Please don't get me wrong!

> Thanks for the tip anyway!

You're welcome!
