### ISSUE TITLE
Undefined subroutine after upgrade to 1.972

### ISSUE THREAD

**Issue by nickklius** [webmin/webmin#1450]
```
Error — Perl execution failed

Undefined subroutine &firewall::check_ipvx_address called at /usr/share/webmin/firewall/save_rule.cgi line 128.

```
Trying to save firewall SNAT rule and getting the error.
Previously used _check_ipaddress_ subroutine, now it's _check_ipvx_address_. 
The function isn't working despite it's defined in firewall4/6-lib.pl.

**Comment by iliarostovtsev** [comment]
Hi,

Thanks for the heads up.

Check this patch out, please. https://github.com/webmin/webmin/commit/b477bf37e0cf6d1cd0f043819bba10833f07dd19
