### ISSUE TITLE
Bind8 restart_zone redirects to different URL.

### ISSUE THREAD

**Issue by MarcHagen** [webmin/webmin#1454]
Webmin: 1.962 

When im within the DNS domain edit page (`/bind8/edit_master.cgi?zone=domain.nl&view=18&xnavigation=1`) and
hit the restart_zone button (which has the this url: `restart_zone.cgi?return=1&view=18&zone=domain.nl`) it redirects me to:
`Location: /bind8/edit_master.cgi?zone=domain.nl ` and presents me with a domain thats not in the same VIEW. Because i have some domains with different ips in views. So i get a random one.

**Comment by jcameron** [comment]
@iliaross this appears to be a side-effect of this commit : https://github.com/webmin/webmin/commit/24267b8afd48d6fc9069bd2732e5ea27b1d4c749

Which is the `view=` param not added when `restart` is set to `1` ?

**Comment by iliarostovtsev** [comment]
Yes, alright. Fixed https://github.com/webmin/webmin/commit/4c6ba93328cac7c784cb1d08ff96d1fef8ce4518

Thanks for reporting @MarcHagen
