### ISSUE TITLE
Mails stuck in postfix mail queue

### ISSUE THREAD

**Issue by dollysingh197** [webmin/webmin#1461]
I have completed my setup but when I am sending emails they  are landing in the mails queue section of the Postfix mail server. This is the last thing that I have to resolve. I do not know what is causing this issue. Any help will be really appreciated..

**Comment by iliarostovtsev** [comment]
Hi,

This is Issue Tracker and not Q/A resource. Sorry. You are welcome to ask this question on [forum.virtualmin.com](https://forum.virtualmin.com).

However, we suggest looking at `maillog` first and investigating more on the errors seen, as most likely you won't get any help, if you don't show what you have tried.
