### ISSUE TITLE
Unix useranme change but webmin user not change

### ISSUE THREAD

**Issue by TongTC** [webmin/webmin#1462]
Hi
Good day.

I would like  to change webmin user/password when Unix user/password change but I cannot  do it. Webmin user still not change username/password.

Could you suggest how to confige this problem ?

I have set refer picture below.

![Capture](https://user-images.githubusercontent.com/56378146/111568961-54c5d580-87d4-11eb-8184-436fc0f353a8.JPG)

Best Regard

**Comment by jcameron** [comment]
You can instead just configure the Webmin user to use a Unix password for authentication.

**Comment by TongTC** [comment]
Thank you so much for your reply

I already configure refer your suggestion but still username not change.

When I change username in user and group module 

<img width="941" alt="a" src="https://user-images.githubusercontent.com/56378146/111867589-a2466c00-89a7-11eb-8f9e-e6261e84a09e.png">


some time Webmin User module also change but sometime not change

I need to "Convert Unix To Webmin Users" agian.

<img width="164" alt="a" src="https://user-images.githubusercontent.com/56378146/111867524-22200680-89a7-11eb-99f9-ba630fbfb5fc.png">

I would like to when I change username in Username and Group module it effect to Usermin module also

How to do ?

Sorry for inconvienient

Best Regard

**Comment by jcameron** [comment]
In the User and Groups module, when saving the user do you have the option to "change in other modules" enabled? It's down the bottom of the page.

**Comment by TongTC** [comment]
Dear @jcameron 
Thank you for your support

"change in other modules" enabled? 

Yes, Enabled.

<img width="748" alt="Capture" src="https://user-images.githubusercontent.com/56378146/111900098-0d08ad80-8a63-11eb-8a15-75a9a5798541.PNG">

### Note
I can change username in webmin module but cannot change by user and group module sometime.

Best Regard

**Comment by jcameron** [comment]
So does the user always failed to get renamed, or just sometimes?

**Comment by TongTC** [comment]
Dear @jcameron 

Thank you for your supporting.

So does the user always failed to get renamed, or just sometimes?
**- Sometimes**

Best Regard

**Comment by jcameron** [comment]
Hmm .. that's very odd. Is there some obvious reason why it would work for some users and not others?

**Comment by TongTC** [comment]
Dear @jcameron 

Thank you for your suport.

I try to find point that make this issue.

I already found  when I config in **Webmin Module**  user not catagorize modules

![Untitled](https://user-images.githubusercontent.com/56378146/111958674-199f0b80-8b20-11eb-902c-cd9457d17395.png)




It seem to Webmin module username are seperated from Unix User

Can I config it to be same as Unix user  whether I not  **Catagorize Modules** config ?


Best Regard

**Comment by jcameron** [comment]
Can you confirm that is the factor which controls if the rename works or not?

Looking at the code, I can't see how that option would effect renaming.

**Comment by TongTC** [comment]
Dear @jcameron 

For confirm please refer to link video.

[https://youtu.be/YVps3yfQUz8](url)

Thank you so much for your support

Best Regard

**Comment by TongTC** [comment]
Hello

Now I can solve this problem.

Thank you @jcameron so much.

Best Regard

**Comment by iliarostovtsev** [comment]
> Now I can solve this problem. Thank you @jcameron so much.

Wait, what was the problem and a solution?

**Comment by TongTC** [comment]
Hello @iliaross 

The problem is  when I change User name from Users and Groups module 

It seem to User name (Webmin User module) not change follow Users and Group (Unix User)

If setting sync user as piture below:

<img width="959" alt="Capture1" src="https://user-images.githubusercontent.com/56378146/113643264-1ffabf00-96ac-11eb-9f7d-97d12d49f1d4.PNG">

then I found that if set setting sync as below it work normally. **that is I don't know why  ^^**

<img width="960" alt="Capture2" src="https://user-images.githubusercontent.com/56378146/113643370-5fc1a680-96ac-11eb-96d0-9518345d7bbd.PNG">

Thank you.

Best Regard

**Comment by jcameron** [comment]
Ok, I see now how that behavior could happen. In the next release, I'll add an option to rename users even when the password isn't synced.

**Comment by TongTC** [comment]
> Ok, I see now how that behavior could happen. In the next release, I'll add an option to rename users even when the password isn't synced.

Thank you so much.
