### ISSUE TITLE
after webmin upgrade, bookmarks gone

### ISSUE THREAD

**Issue by alirizaaribas-ibg** [webmin/webmin#1464]
Hi,
After upgrading webmin, at preferences of filemin, there is no bookmarks list. It is easy to add a list of bulk into bookmark. What is the solution?
Thanks

![gnome-shell-screenshot-1F6S00](https://user-images.githubusercontent.com/55430656/112111463-46f1c500-8bc5-11eb-85c6-8d7a2bb0931e.png)
![gnome-shell-screenshot-5CVP00](https://user-images.githubusercontent.com/55430656/112111490-507b2d00-8bc5-11eb-92c4-f43061115380.png)

**Comment by iliarostovtsev** [comment]
Dupe - https://sourceforge.net/p/webadmin/discussion/600155/thread/7ca7f2feeb/?limit=25#cce4

**Comment by alirizaaribas-ibg** [comment]
Works. Thank you.

**Comment by FBachofner** [comment]
Where is the bookmarks file stored _previous_ to 1.973 ?

I pulled my whole 1.973 configuration to a new server and bookmarks somehow did not come with it.  Meanwhile, on the old server (already upgraded to 1.973) the bookmarks are still available, but they are NOT at ```~/.filemin/bookmarks```

That folder does not even exist.

**Comment by iliarostovtsev** [comment]
`~/` default to the user home directory.

If you still don't know where it is, just use File Manager search in file content feature to find it.

**Comment by FBachofner** [comment]
Thanks @iliaross 

Turns out the Filemin bookmark file is in /root/.filemin

This seems odd as I am not logging in as "root" rather as a named user (with !

On the other hand, https://192.168.1.100:10000/acl/edit_user.cgi?user=root&xnavigation=1

shows my "Username" to be "root"

)(&@#$%#$&^ is going on here?!  (on other Ubuntu 20.04 systems it is the same)

**Comment by iliarostovtsev** [comment]
You're logged in as `root` capable user (which is in `wheel/adm` group).
