### ISSUE TITLE
Undefined subroutine &miniserv::get_error_style

### ISSUE THREAD

**Issue by PitWenkin** [webmin/webmin#1466]
I got an email about a failed cronjob /etc/webmin/status/monitor.pl

Content of mail was only "Undefined subroutine &miniserv::get_error_style called at ../web-lib-funcs.pl line 3853."

System Configuration:
Operating system	Ubuntu Linux 16.04.7
Webmin version	1.973
Usermin version	1.823
Virtualmin version	6.15
Authentic theme version	19.73 

Should be this line in the current code:
https://github.com/webmin/webmin/blob/ae071bf4f60642a9592a099d9ec9f5529c4049ab/web-lib-funcs.pl#L3857

**Comment by iliarostovtsev** [comment]
Hi,

I have reworked this part. It was a bad overall approach.

Thanks for pointing out.

https://github.com/webmin/webmin/issues/1466
