### ISSUE TITLE
Checksum mismatch

### ISSUE THREAD

**Issue by erchbox** [webmin/webmin#1467]
I downloaded today the latest version 1.973

The calculated RPM package checksum:
```
~/Downloads> md5sum webmin-1.973-1.noarch.rpm
30b1a28ed923e10932626820b25db01d  webmin-1.973-1.noarch.rpm
```

does not match the one appearing on the [downlod webpage](https://www.webmin.com/download.html)

Filename |MD5 Checksum
---------|------------
webmin-1.973-1.noarch.rpm |1878fd2a7102733630ac2c5e0b092d02

Would you please advise?

**Comment by iliarostovtsev** [comment]
Hi,

It looks that we repacked it (after discovering a small bug) right afterwards, and never updated initial checksum on the website.

Webmin 1.974 will have it fixed.

**Comment by erchbox** [comment]
Hi,

Could you please confirm what the correct MD5 checksum for 1.973 is?

**Comment by iliarostovtsev** [comment]
@jcameron Jamie what is the expected _checksum_ for latest Webmin 1.973?

**Comment by jcameron** [comment]
It should be `30b1a28ed923e10932626820b25db01d`

I just forgot to update that md5.html page after re-packaging to fix a bug. It's fixed now though.
