### ISSUE TITLE
DNS lost after reboot

### ISSUE THREAD

**Issue by stoufa06** [webmin/webmin#147]
Hello

Webmin's network configuration module edits /etc/resolv.conf directly instead of configuring DNS via /etc/network/interfaces (resolvconf package). If the system is configured to use the resolvconf mechanism, DNS settings will be lost on reboot.

This is an old bug http://sourceforge.net/p/webadmin/bugs/3391/ but was not fixed. I am configuring dns through webmin but i am loosing it on reboot.

Is there any fix for this?

thank you for response

**Comment by philmck** [comment]
Still failing sometimes for me with Ubuntu 14.04.3  and Webmin 1.782. There must be another cause. I've checked that it's not caused by the hypervisor (KVM).

**Comment by jcameron** [comment]
philmck - check if your network interface is configured using DHCP. That can cause the DNS settings to be overridden.

**Comment by philmck** [comment]
It's not using DHCP (at least, not according to webmin and my understanding of network/interfaces)

**Comment by jcameron** [comment]
Is Webmin updating the `PEERDNS` or `DNS` lines in `/etc/sysconfig/network-scripts/ifcfg-eth0` ? That should be fixed in the latest release, but only if you changed the DNS servers after upgrading.

**Comment by philmck** [comment]
That's a RedHat path and I'm on Ubuntu so no. But it is updating in dns-nameservers under eth0 in /etc/network/interfaces. I did notice though that IPv6 DNS settings are in the inet section rather than the inet6 section, which seems wrong.

The "post-up iptables-restore < /etc/iptables.up.rules" line is NOT being updated by webmin now but it's recognised if I put it in manually.

**Comment by jcameron** [comment]
It looks like you have a different problem to the original poster then. Is your issue that /etc/resolv.conf is being over-written with the wrong nameservers on reboot?

**Comment by qooob** [comment]
Cockpit rewrites net-config files and probably resolve.conf as well. Do you use Cockpit?

**Comment by philmck** [comment]
My problem is DNS settings being lost on reboot, I'm not sure which files are causing that exactly. Resolv.conf is changing but I believe it's a symlink in Ubuntu and generated automatically. As far as I can tell the problem only happens now (in Webmin 1.782) after a forced "power loss" kind of reboot.

I'm not using Cockpit.

**Comment by qooob** [comment]
[http://askubuntu.com/questions/157154/how-do-i-include-lines-in-resolv-conf-that-wont-get-lost-on-reboot](http://askubuntu.com/q/157154)

**Comment by philmck** [comment]
Thanks for your help qooob, but the consensus there seems to be to configure nameservers in /etc/network/interfaces. But the DNS settings in that file are changing in this situation and I suspect that's what causes resolv.conf to change in turn.
