### ISSUE TITLE
text login python needed

### ISSUE THREAD

**Issue by stefanlk** [webmin/webmin#1472]
In debian bullseye, there is no standard command "/usr/bin/python" anymore.
I tried to use the tool text login and get the error "command python not found".
How can I best correct this or is there a correction in webmin needed?
I think webmin shall call the right python2/3 command.

**Comment by iliarostovtsev** [comment]
Hi,

Check [this commit](https://github.com/webmin/webmin/commit/c6430c2c2de4fb51e7282a737ce95b085581a615). It explains the problem and displays a solution.

Make sure that you're running latest Webmin 1.973.

**Comment by stefanlk** [comment]
Thanks, the get_python_cmd would work over the first error.
The following packages are installed:
![grafik](https://user-images.githubusercontent.com/32956179/114442228-9fb4ec00-9bcc-11eb-9784-100faab8d9b9.png)

But I cannot still test the rest, because ajaxterm isn't included anymore in newer linux Ubuntu/debian.
Stefan

**Comment by iliarostovtsev** [comment]
What is the output of `python --version` and `python2 --version` commands?

**Comment by stefanlk** [comment]
~$ python
python2.7  python3    python3.9
~$ python2.7 --version
Python 2.7.18
~$ python3 --version
Python 3.9.2

**Comment by iliarostovtsev** [comment]
> ~$ python
python2.7 python3 python3.9
~$ python2.7 --version
Python 2.7.18
~$ python3 --version
Python 3.9.2

This is not what I asked, sorry.

> In debian bullseye, there is no standard command "/usr/bin/python" anymore.

You need to make sure that `python` command (command if available on the path) returns Python 2 as Python 3 not supported with Text Login module.

If `python` command not available you could symlink `python2.7` to `python2`, which would work as well.

**Comment by stefanlk** [comment]
Thanks for the response,
what you can see: there is no link of python or python2 command.
I think, debian bullseye do not install such commands and I think I can do the symlinks and also I do not have to do it.
Also there is a good reason, why the symlinks do not exist anymore.
Also I do not need this text login anymore, because I cannot install ajaxterm with apt normal install anymore.
So it will be better to migrate the webmin module to support f.ex. Wetty
Thanks
Stefan
