### ISSUE TITLE
Home Page Module Documentation Link Down/Incorrect

### ISSUE THREAD

**Issue by ColdForest** [webmin/webmin#1475]
The following module documentation link, referenced from the https://www.webmin.com/docs.html link is unavailable: http://doxfer.webmin.com/Modules

The following link, however, is sound/correct: https://doxfer.webmin.com/Webmin/Webmin_Modules.

**Comment by iliarostovtsev** [comment]
@jcameron Jamie, could you fix that link?

Also, can we mention somewhere that Windows is no longer supported/tested.

**Comment by jcameron** [comment]
Thanks, it's fixed now.
