### ISSUE TITLE
German translation in Scheduled Backup

### ISSUE THREAD

**Issue by JProof** [webmin/webmin#1476]
I did not find the file for the translation.

Url to the backup config:
https://myHost:10000/virtual-server/backup_form.cgi?new=1&xnavigation=1

The word "Spielplan" should be replaced with "**Zeitplan**"
![ksnip_20210419-073501](https://user-images.githubusercontent.com/12245927/115186575-43792d00-a0e2-11eb-9984-d8d22e4cf686.png)

**Comment by iliarostovtsev** [comment]
Hi,

Danke. It's in Virtualmin module (`webmin/virtual-server/lang`)

[Fixed here](https://github.com/virtualmin/virtualmin-gpl/commit/14967ee9c64c44943d21d1dbde197c4d7906e739).
