### ISSUE TITLE
A safe default for the SSH Server page

### ISSUE THREAD

**Issue by fakemoth** [webmin/webmin#1481]
The consensus says that SSH1 should not be used, it's just legacy for (extreme) compatibility, so a few points here:
- the default in modern distros is the second version, as it should be; this is not stated explicitly as an uncommented option in the sshd config file; at least I never saw it in a default one...
- if you do the right thing and disable SSH v1 in "Webmin > Servers > SSH Server > Networking > Accept protocols" and check only the SSH v2 one, it will write in the config file "Protocol 2". Also the default, works, kinda unnecessary.
- if you let the defaults PRESENTED by Webmin with both versions checked, but hit Save for some reason, it will write "Protocol 1,2" in the sshd_config file. So it works as advertised also, and it will activate/add version one of the protocol. But not good if you don't really mean it.

So everything is fine, it's just not a safe/sane default on the Webmin side.

**Comment by jcameron** [comment]
Good point - I'll change the interpretation of the default to SSH v2 only in the next release.
