### ISSUE TITLE
Default page for webmin issue

### ISSUE THREAD

**Issue by DrCarsonBeckett** [webmin/webmin#1483]
Since I updated to the version 1.974 I always get redirected to the system and server status page instead of the dashboard, even though the default page for webmin is set to the dashboard.
It worked fine with the 1.973 version. Did not change any settings regarding that.
I can provide more details or log files in necessary.

Versions currently used:
Webmin-Version | 1.974 |
Usermin-Version | 1.823
Virtualmin Version | 6.16 |
Authentic theme version | 19.75

**Comment by iliarostovtsev** [comment]
Hi,

Thanks for the heads up. This issue has been address and the fix will be included in upcoming Webmin 1.975.

Meanwhile, you can go to theme configuration and change default page for Webmin - 

![image](https://user-images.githubusercontent.com/4426533/117499600-2074c700-af84-11eb-8957-b69fcc890526.png)
