### ISSUE TITLE
HOW TO FIX (Error: `/mnt/mnt/Share`- No such file or directory.) ?

### ISSUE THREAD

**Issue by TongTC** [webmin/webmin#1487]
Dear @iliarostovtsev 

I would like to how to fix problem about missing of directory refer picture below:

<img width="895" alt="22" src="https://user-images.githubusercontent.com/56378146/119247220-02c57580-bbb2-11eb-86a6-0b201689cadc.png">

The problem is the directory has been doubleded (/mnt/mnt/share).

And I set directory in the ACL as below:

<img width="747" alt="11" src="https://user-images.githubusercontent.com/56378146/119247222-06f19300-bbb2-11eb-9fc6-0b606c67c9b0.PNG">

Could you let me know how to fix it ?

Best regards

**Comment by iliarostovtsev** [comment]
Howdy there,

Thanks for your report! It looks like a bug in a tree view when only one allowed directory is used. The workaround for now would be to create an empty `/tmp-empty-dir-no-data` (or whatever name) and add this to allowed directories or turning off the tree view.

**Comment by TongTC** [comment]
Ok Lia Thank you so much for your suggestion.

**Comment by iliarostovtsev** [comment]
Okay, I think I got it completely right this time. You can try updating to Authentic Theme 19.76-beta3 and see if it works for you or if you manage to find any other issues.

**Comment by TongTC** [comment]
Hello @iliaross 

OK I will try.

Thank you so much.
