### ISSUE TITLE
Linux Firewall module can not apply the configuration 

### ISSUE THREAD

**Issue by schwerg** [webmin/webmin#1495]
Since the uptate to Webmin 1.974, running on Debian Buster (10.9), "Apply Configuration" on the "Linux Firewall" tab results in "Failed to apply configuration : Failed to restart iptables.service: Unit iptables.service not found."
Furthermore the activation at boot is reset to "No" and can not be activated again ("Bootup action iptables does not exist".

Before the update the setup worked well.

**Comment by iliarostovtsev** [comment]
Hi, Georg.

This issue has been discussed numerous times and will be fixed for upcoming Webmin 1.980.

Thanks for the heads up anyway.
