### ISSUE TITLE
Problem with config_portable_theme_locale_language is not defined

### ISSUE THREAD

**Issue by Madriix** [webmin/webmin#1497]
Hello
When going to webmin, there are sometimes pages that lag (like the CSF page) and I have this error:

```
Uncaught ReferenceError: config_portable_theme_locale_language is not defined
    load_init https://webmin.xxxx.net:10000/unauthenticated/js/bundle.min.js?19819999999999901:464
    <anonymous> https://webmin.xxxxv.net:10000/unauthenticated/js/bundle.min.js?19819999999999901:464
```

By putting the classic theme, it loads quickly but not with the original theme (which I prefer)

How to solve?

**Comment by iliarostovtsev** [comment]
Hi,

This issue has been sorted on the latest theme 19.81 release, which is distributed with the latest Webmin 1.979.

**Comment by Madriix** [comment]
Here is the version I have been using since this morning:

Version Webmin 	1.979
	Version de thème authentique 	19.81
Version du pare-feu 	Sécurité et pare-feu ConfigServer 14.10   

I have this problem on this version

module CSF page never loads

**Comment by Madriix** [comment]
Maybe I have to delete my cookies from my browser?
or do I have to reinstall webmin?

**Comment by iliarostovtsev** [comment]
You should force reload browser's cache, try incognito mode or another browser.

**Comment by Madriix** [comment]
I am in Firefox (latest version) and it does not work
With Firefox in private browsing this does not work either
With Chrome latest version the webmin works well (I tried without private browsing only)

What does that mean?

I deleted the cookies and cleared the cache on Firefox, the problem persists

**Comment by Madriix** [comment]
I uninstalled then reinstalled webmin, the problem is not resolved on Firefox 89.0

**Comment by iliarostovtsev** [comment]
> I uninstalled then reinstalled webmin, the problem is not resolved on Firefox 89.0

It works for me just fine in Firefox 89 on Linux and MacOS. I assume the problem is caused by some installed extensions. What Firefox browser's extensions do you have installed?

**Comment by Madriix** [comment]
I tried to deactivate all extensions yesterday, but the problem is still there.
I have tried again now and even turned off Firefox tracking, but the problem persists.

Here is the problem to summarize:

- When you arrive on the Webmin home page (https://webmin.xxx.net:10000/) there is a dashboard and by clicking on Security and firewall ConfigServer it does not open, in the console I have this: Uncaught InternalError: too much recursion and clicking on it puts this in red: https://zupimages.net/up/21/24/s1h7.png


-  also I tried to right-click on "ConfigServer Security and Firewall" and open in a new tab and I got this error: Uncaught ReferenceError: config_portable_theme_locale_language is not defined, it points to https://zupimages.net/up/21/24/z9j4.png

**Comment by iliarostovtsev** [comment]
This is an odd error. However, I still presume that this is a cache issue. Try going to theme configuration page, and it's update page and then update to the latest development version of the theme. Later, go to **Webmin ⇾ Webmin Configuration: Web Server Options** and set to _Never_ option called _Gzip compress static files_ and then reload the page using **`Ctrl+Shift+R`** hotkey?

Does it help? Can you should me the full screenshot of an error?

**Comment by Madriix** [comment]
A few moments ago I installed Windows 7 64bits SP1 on Virtualbox and I installed the latest Firefox.
I then go to Webmin I enter my login and password and I go to the  CSF page with firefox, it was fast. I reload the page 2 or 3 times and everything is fine.
Then I go to my firefox from my real PC and I search, I try to do "CTRL F5" etc .. and without success.
And suddenly now even on Firefox in Virtualbox the CSF page does not want to load at all since now.

On Firefox in Virtualbox, the only things I've done are a few things like this:
- Successful launch of webmin and CSF page for the first time
- Bookmark https: //webmin....net: 10000 (bookmark)
- Disable the automatic update of firefox
- I also removed the "Pocket" button
- I tweaked a bit on another firefox (my other pc) and then I came back to Virtualbox, I reload the web page but the CSF page does not want to start anymore.
There is no plugin or extension - All are by default

There are therefore bugs on two OS (two Windows 7 with Firefox).

The bug only occurs with the CSF page

**Comment by iliarostovtsev** [comment]
Could you attach as a _.zip_ the following files from the server where it doesn't work:

~~~
/etc/csf/csf.htmltag
/etc/csf/csf.header
/etc/csf/csf.footer
/etc/csf/csf.bodytag
/etc/csf/csf.body
~~~

**Comment by Madriix** [comment]
I sent by email: developers@webmin.com

**Comment by iliarostovtsev** [comment]
Can you please use my website mail-form to submit a download link?

**Comment by iliarostovtsev** [comment]
I got your files.

I can try Firefox on Windows though. I am confused about your situation. Can I login and have a look?

**Comment by iliarostovtsev** [comment]
Is this still an issue with Firefox 89.0.1?

**Comment by iliarostovtsev** [comment]
Okay, update the theme with the latest development version one more time and tell me if it fixes your issue.

**Comment by Madriix** [comment]
@iliaross 
Thank. This is fixed now with the latest theme beta update. 
And if not yes I have Firefox 89.0.1 (x64).

So it will always be resolved for the next stable versions?

**Comment by iliarostovtsev** [comment]
> So it will always be resolved for the next stable versions?

Yes, it will be on the next stable release. Besides, I will look more through the code to optimize regex whenever possible. What I have used before wasn't optimal, so thank you for reporting it and being patient.
