### ISSUE TITLE
Can install this Raspberry Pi Zero?

### ISSUE THREAD

**Issue by asyba** [webmin/webmin#1499]
Will work on my Raspberry Pi  Zero W ?

**Comment by chris001** [comment]
It should work fine, as it only requires Perl, and Raspberry Pi Zero W supports Perl.
Try to install it, and report back your results here!

**Comment by asyba** [comment]
> It should work fine, as it only requires Perl, and Raspberry Pi Zero W supports Perl.
> Try to install it, and report back your results here!

but what about the resources that this program uses?
because my Pi has:
1GHz, single-core CPU
512MB RAM

And I have already installed pi-hole and homebridge.
for example right now I have free ram: 226.77MB

**Comment by swelljoe** [comment]
Webmin only needs ~10-20MB of RAM (depending on architecture and Perl version, among other things).

But, note that Virtualmin (at least the installer) definitely does not support ARM architecture devices, a it includes binary packages only built for x86/x86_64.
