### ISSUE TITLE
Filemin on MacOS El Capitan will not load for any browser on Big Sur

### ISSUE THREAD

**Issue by PlymouthExpat** [webmin/webmin#1500]
Home server (10-year-old Mac Mini) has El Capitan and runs Server 5.2 with Webmin 1.974. For some months, I have been unable to open the file manager (/filemin/) while using Safari/Opera/Firefox on an iMac (iMac20,1) with Big Sur (11 to 11.4) - with Webmin using Authentic theme. Hovering the cursor over the link, I can see that it should go to [IPAddress]:10000/filemin/ but nothing seems to happen.

I noticed in a thread that a similar error occurred some years ago with Virtualmin and wondered if there is something peculiar about my current setup causing the issue. The problem does not exist when using another theme and it does not exist when using Safari on an iPad Air (2020).

I would be grateful for any pointers.

**Comment by iliarostovtsev** [comment]
Hello, 

I have tested the recent release of Authentic Theme with Big Sur and in all browser I got (Chrome, Chrome Beta, Chrome Canary, Forefox and Safari) it worked just fine.

If you open browser's console do you get any errors logged?

Have you tried disabling all exptesisnon and/ 
or trying incognito mode? Have you tried accessing the same server you're having issue with on Big Sur from another computer or from your phone?

Do you have latest browser's versions installed? Which are they?

**Comment by PlymouthExpat** [comment]
Thanks for the v. swift response.

On clicking link, console shows: "Failed to load resource: The internet connection appears to be offline." When using 'Gray Framed Theme, no error! There are no extensions running. Incognito mode?

From second (slightly older) iMac (also Big Sur), I have the same problem. I do not have a problem when using Safari on my iPad.

Safari: 14.1.1 (16611.2.7.1.4)
Opera: 75.0.3969.218 (x86_64)
Firefox: 89.0.2

**Comment by iliarostovtsev** [comment]
What link in particular are you clicking?

Is there a way you could add a screencast of the whole process with browser's console opened or at least a screenshot?

**Comment by PlymouthExpat** [comment]
I have uploaded a screen recording to my own site at [https://www.kugro.org.uk/media/Screen_Recording_2021-07-05_at_9.05.46am.mov](https://www.kugro.org.uk/media/Screen_Recording_2021-07-05_at_9.05.46am.mov) as it's too big to upload here.

**Comment by iliarostovtsev** [comment]
The link you shared is invalid?

**Comment by PlymouthExpat** [comment]
I’ll try and take some screenshots of it as it runs (it works for me) and upload them here.

**Comment by iliarostovtsev** [comment]
You could upload this to Google Drive and share the link with me. I would like to see video-screenscast, really.

**Comment by PlymouthExpat** [comment]
https://drive.google.com/file/d/1OJhSHvmlsLgci3Hstb39hmmex3fKdCrq/view?usp=sharing

**Comment by iliarostovtsev** [comment]
Not sure off hand what could cause this issue. So Webmin is running on MacOS and being opened locally? If so, are there any errors printed in _miniserv_ log under `/var/webmin` directory? Perhaps some missing Perl modules? What is Perl version installed there? Also, what address in the URL are you using? Do you use a hostname/domainname or an IP address?

Is there a way for me to login and have a look? You could send me credentials using the contact form on my website.

**Comment by PlymouthExpat** [comment]
No, sorry, it's not available from outside my LAN.

**Comment by chris001** [comment]
Nota Bene @PlymouthExpat , @iliaross asked 6 other key questions, besides that one you answered about logging in from his side!.....

**Comment by PlymouthExpat** [comment]
Thank you, @chris001, for that! I appreciate that @iliaross is giving up time to help me, but I can’t respond immediately without trying to find the answers to his questions, which takes time. I’ll respond as soon as I possibly can, as I’m very grateful for all the help I’ve received so far.

**Comment by PlymouthExpat** [comment]
Sorry for the hiatus in the thread, but I was dragged away from this by other worldly priorities. Anyway, nothing has changed on the MacOS El Capitan server (old Mac Mini) running webmin 1.974 and certain modules (such as filemin) will not generate a response when access to the server is from an iMac (on same LAN) running Big Sur. However, I have now been able to ascertain that attempting to access from Windows 10 or Windows 11 (running in Parallels on the iMac), using Firefox, appears to have no problem at all. My conclusion: it is the latest security configuration built in to Big Sur (rather than just in Safari) that causes my problem. Thank you for the earlier offers of assistance; I shall not seek to solve the problem here, as I believe it to be a function of Apple's software!!

**Comment by iliarostovtsev** [comment]
@PlymouthExpat Janette, does it still fail with Webmin 1.981? Besides, does it fail in Safari or in Chrome and Firefox too? What is the browser version where it fails?

I have just tried opening File Manager in Safari on Big Sur and it worked just fine for me. It would be helpful if you could check for browser's console errors and/or `miniserv.log` specific errors.

**Comment by PlymouthExpat** [comment]
Using Firefox on Windows 11, attempting to upgrade Webmin using Webmin upgrade module produces "Failed to upgrade from www.webmin.com : Failed to read HTTP response line". I will try to upgrade manually.

On the iMac (Big Sur), the errors are similar across all browsers: Safari (the worst), Firefox (it seems to try, but the console shows the same errors), Opera. I don't use Chrome. All browsers are the latest versions.

From your observation of being able to open File Manager using Big Sur, it seems that it is my iMac's particular configuration, but my partner's iMac (also Big Sur) shows exactly the same error (clicking on 'File Manager' displays 'Failed to load resource. The internet connection appears to be offline.' in the Console.

Perl5.18

log entries on clicking File Manager on my partner's iMac:

192.168.147.61 - miniskuell_admin [17/Sep/2021:21:55:11 +0100] "POST /filemin/ HTTP/1.1" 200 58880
192.168.147.61 - miniskuell_admin [17/Sep/2021:21:55:11 +0100] "GET /stats.cgi?xhr-stats=general&sdata=1 HTTP/1.1" 200 44350
192.168.147.61 - miniskuell_admin [17/Sep/2021:21:55:11 +0100] "GET /index.cgi/?xhr-error=1 HTTP/1.1" 200 0
192.168.147.61 - miniskuell_admin [17/Sep/2021:21:55:12 +0100] "GET /stats.cgi?xhr-stats=general&sdata=1 HTTP/1.1" 200 44423
192.168.147.61 - miniskuell_admin [17/Sep/2021:21:55:19 +0100] "GET /stats.cgi?xhr-stats=general&sdata=1 HTTP/1.1" 200 44496

**Comment by iliarostovtsev** [comment]
Want is your client? MacOS Big Sur? Using a browser on Big Sur and connecting to the server returns this error? What is the server? MacOS Captain?

1. What if you connect to the other server using MacOS Big Sur as a client, like a local virtual machine running Webmin?
2. What if you connect to existing server with another client, like Linux or Windows desktop - what does it do?
3. What if you install Chrome on Big Sur and try again?

Yes, upgrading Webmin and the theme would be the best to get more relevant test results.

**Comment by PlymouthExpat** [comment]
Server is a Mac Mini running macOS El Capitan (10.11.6), Server 5.2 (16S1195), Perl 5.18 and Webmin 1.974. Client is iMac running macOS Big Sur (11.6). Browsers in use on client are Safari, Firefox and Opera. All 3 browsers produce similar results.

Running either Safari or Firefox on the server appears to give no problems accessing the File Manager, although Safari changes the left sidebar text from white to dark grey.

Running Firefox on Windows 11 (in Parallels on my main iMac) gives no problems.

Chrome (seldom used but already installed on iMac (and up-to-date)) doesn't even get as far as displaying the sidebar, reporting - in Console - Failed to load resource: net::ERR_INTERNET_DISCONNECTED

**Comment by iliarostovtsev** [comment]
It doesn't seem to me as something we can actually fix on our end.

I'd recommend trying restarting Webmin at first or better installing latest Webmin 1.981.

**Comment by PlymouthExpat** [comment]
Thank you. I agree that it’s not for you to fix; I was just hoping that someone might have experienced the same thing and have some pointers. Nevertheless, I think I have seen enough to know that Big Sur itself is not the problem, but something else in the system that is preventing full communication. I shall attempt to upgrade Webmin on the Mac Mini manually. If I ever find out what is causing my problem, I’ll report back.

**Comment by iliarostovtsev** [comment]
Try moving `/etc/webmin` somewhere, and re-install Webmin using the latest 1.981 package. It might "auto-resolve" this way.

**Comment by PlymouthExpat** [comment]
Action taken as you suggested, with server Webmin now at 1.981. No change to problem seen when accessing from Big Sur-based client. Safari on iPad has no problems. The only time problems are evident is when accessed from either of the iMacs, both running Big Sur. The fact that you have no problem accessing Webmin's File Manager from Big Sur indicates a macOS configuration problem here. At least I know now where to look, having removed all other possible obstacles.

Thank you for your assistance in this. As I mentioned previously, I shall report back if I ever get to the bottom of the issue!!

**Comment by PlymouthExpat** [comment]
Sooner than I expected, here I am reporting back!

Apple has updated its Safari application and, I suspect, a whole raft of other critical core software elements - elements that had prevented not just Safari from accessing Webmin on my local server but other browsers too. I now have no problem with Webmin's filemin and speed of access to a couple of other external servers that I manage has improved too.
