### ISSUE TITLE
Filemanager greyed out on iOS with dialogs

### ISSUE THREAD

**Issue by HonkXL** [webmin/webmin#1508]
When using the filemanager on iOS devices like iPad, most things work fine. But the filemanager gets greyed out and does not accept any input when opening any dialog box.

See screenshot. It's not possible here to enter text to the field. The only way out is to go back and reload the page.

![webmin-filemanager](https://user-images.githubusercontent.com/16715040/128828402-8ff75f2f-8be1-46af-8619-a49428818593.jpg)

**Comment by jcameron** [comment]
@iliaross any idea about this one?

**Comment by iliarostovtsev** [comment]
This is a known issue in mobile mode on iPad. There is no straight forward solution to this with such DOM structure, although I can work around this problem fairly easy.

The work-around that you could use at the moment is simple - switch browser to use _Desktop Mode_ for this page.

**Comment by iliarostovtsev** [comment]
This issue will be fixed with theme 19.83 release.
