### ISSUE TITLE
Dovecot not running after deletion of subdomain with certificate

### ISSUE THREAD

**Issue by HonkXL** [webmin/webmin#1510]
After deletion of a subdomain with own certificate (let's encrypt), everything works fine, but when restarting the server, Dovecot refuses to start. Verified on Debian 10 and CentOS 8.

Problem is, that in
/etc/dovecot/dovecot.conf
some parts to the old subdomains still exist - ssl_cert and ssl_key are pointing to files that are now deleted because of the deletioin of the subdomain.

In some cases the entries in the dovecot.conf are removed, but not every time. I did not find out, when it works and when not.
The deleted subdomain was a subserver of mydomain.de

local_name subdomain.mydomain.de {
  ssl_cert = </home/mydomain/domains/subdomain.mydomain.de/ssl.combined
  ssl_key = </home/mydomain/domains/subdomain.mydomain.de/ssl.key
}
local_name *.subdomain.mydomain.de {
  ssl_cert = </home/mydomain/domains/subdomain.mydomain.de/ssl.combined
  ssl_key = </home/mydomain/domains/subdomain.mydomain.de/ssl.key
}

All domainnames are anonymized and not MY domains!

**Comment by jcameron** [comment]
Are you running the latest Webmin and Virtualmin releases? Older versions had a bug that could cause this, but it should be fixed in the latest release.

**Comment by HonkXL** [comment]
OK - I will test this end of the week. Of course is everything up-to-date.
