### ISSUE TITLE
Webmin Ver 1.980 File Manager Bug

### ISSUE THREAD

**Issue by www3cc** [webmin/webmin#1516]
File Manager management module cannot be connected to upload folder

Webmin Ver : 1.980

https://user-images.githubusercontent.com/46883314/130717451-b0f0d4c8-93b6-4b89-90c2-0399e9e48279.mp4

**Comment by iliarostovtsev** [comment]
Hi,

It just overwrites existing file?

**Comment by www3cc** [comment]
@iliaross 

Video presentation did not overwrite existing files

Single is the directory

Can't upload the catalog

There will be no problem with the file

**Comment by iliarostovtsev** [comment]
Directory uploads haven't been implemented yet.

**Comment by www3cc** [comment]
@iliaross 
I hope that the Webmin team can realize the upload catalog function

https://user-images.githubusercontent.com/46883314/130749389-d73b448e-a96f-4129-8183-d1b75ae36bb5.mp4

**Comment by www3cc** [comment]
@iliaross 

Update 1.982 version

Implement catalog upload

Thanks to the webmin team

**Comment by webotop** [comment]
Hi,

New update Webmin 1990 does not overwrite file anymore ( file manager )... The checkbox option just gone.

**Comment by iliarostovtsev** [comment]
> New update Webmin 1990 does not overwrite file anymore ( file manager )... The checkbox option just gone.

It doesn't overwrite files by default but you can change that on **File Manager ⇾ Preferences: Advanced options** page using **Do not overwrite existing files upon** option.

**Comment by webotop** [comment]
Thanks didn't know this option there. Perfect.

**Comment by www3cc** [comment]
@iliaross 

The upload directory needs to be checked by yourself
It is inconvenient to select
Is there room for improvement?
Auto-detect directory?

**Comment by www3cc** [comment]
> > New update Webmin 1990 does not overwrite file anymore ( file manager )... The checkbox option just gone.
> 
> It doesn't overwrite files by default but you can change that on **File Manager ⇾ Preferences: Advanced options** page using **Do not overwrite existing files upon** option.

Whether to overwrite the file function is very practical
Thank you webmin team for development

**Comment by nekohayo** [comment]
I've tried this out with the version bundled with Virtualmin 7.10, and the overwrite option does not seem to work at all when set to prompt the user, whether you set it to overwrite or not by default, it never prompts you; it automatically creates a file with " (1)" appended to the filename. Is this the right ticket for this, or this should be a new ticket?

**Comment by iliajie** [comment]
> Is this the right ticket for this, or this should be a new ticket?

Please create a new ticket, providing steps to reproduce the issue; add screenshots for clarity. Thank you!

**Comment by nekohayo** [comment]
OK, I have filed #2113 for the remainder of the overwriting-related UX issue I can see.
