### ISSUE TITLE
File Manager cannot access by others user 

### ISSUE THREAD

**Issue by TongTC** [webmin/webmin#1522]
Dear All  

Thank you for your good development of the Webmin and Themes.

Today I have  problem  about using File Manager module

please refer picture

![Inkedclient_group_webmin_config_LI](https://user-images.githubusercontent.com/56378146/132936825-b95b3a38-1367-4ff8-9cd2-8a7f9814d319.jpg)

A picture above is config for group I used **Same as webmin login**  but I cannot access to see the directory /u03

show message as below:

<img width="752" alt="filemin_connot_show" src="https://user-images.githubusercontent.com/56378146/132936894-c438480f-7876-45d4-917b-ee11f0b30e43.png">

Then, I try to change as Root  I can access to see and no problem as the picture below

![Inkedroot_permission_LI](https://user-images.githubusercontent.com/56378146/132936927-70ac8abd-c45b-441c-a90a-8f108d16e304.jpg)

Then.......

<img width="728" alt="can_show" src="https://user-images.githubusercontent.com/56378146/132936967-7f518805-c82b-4a3d-aac1-eb4498c34e56.png">

Because I would like to grant client access file by Webmin user.

How can I fix this problem ?

Best Regard

**Comment by iliarostovtsev** [comment]
Please make sure that you're running latest Webmin 1.981.

I think the right option would be is to use correspondent *Specific Unix User* option.

**Comment by TongTC** [comment]
Dear All

I have fixed this problem already.

I would like to share for all of you.

**If you create user that have no user Home directory, you will cannot access the any directory in the File Manager module.

Therefore, If you need to  access the the directory by File Manager module you need to create user with home directory also.**

Thank you for all of developers Webmin

Best Regard
