### ISSUE TITLE
set "every x minutes" to 0, the loop will not stop.

### ISSUE THREAD

**Issue by niyari** [webmin/webmin#1527]
https://github.com/webmin/webmin/blob/454c3c6153ebbd7a080dd54843b7f150e160ce29/servers/save_auto.cgi#L17

> 	$in{'mins'} =~ /^\d+$/ || &error($text{'auto_emins'});
	$in{'mins'} > 0 || &error($text{'auto_emins'}); # Exclude zero.  or 1 ... 59min?

If the input is zero, it will stop here.
https://github.com/webmin/webmin/blob/454c3c6153ebbd7a080dd54843b7f150e160ce29/servers/save_auto.cgi#L59

**Comment by jcameron** [comment]
You're right, we'll fix this.
