### ISSUE TITLE
Remove line feed (CRLF) character from the translation list.

### ISSUE THREAD

**Issue by niyari** [webmin/webmin#1528]
This is not a problem for many translation lists, but if there is a CRLF in the string that toggles tabs, an error will occur on the JavaScript side.
Specifying LF or removing line feeds on loading seems to solve the problem.

Webmin 1.981 / Gray Framed Theme
![test](https://user-images.githubusercontent.com/2970321/134983083-3fa75bb8-35bb-47ff-b623-c4aba926c961.png)

**Comment by jcameron** [comment]
Thanks for pointing this out .. we'll fix it in the next release.
