### ISSUE TITLE
Please help me understand what is happening in the backend

### ISSUE THREAD

**Issue by Stefan-CPlanet** [webmin/webmin#1532]
Hello I would like to know what happens in the background creating samba groups?

So let's say I created a group from the terminal:

`sudo groupadd Test-Group
`
I created a user, made its samba password, and added it to the group:
```
sudo adduser --system --no-create-home  test-user -s /sbin/nologin
(echo $password; echo $password) | sudo smbpasswd -a test-user
sudo smbpasswd -e  test-user
usermod -aG Test-group test-user
```
but I do not understand what happens when I go into:
**Webmin ->  Servers -> Samba Windows File Sharing -> Samba groups -> Add new Samba group**

what command happens in the background when I enter:
Group name:Test-Group
Type: Local group
Unix group: Test-Group

I would like to know what is going on in the background , what command is happening for webmin to make unix group also a samba group.

I am doing a frontend for the group manager to be able to change the user permissions but don't want to allow him access to Webmin not to mess things up. 

Thanks a lot in advance

**Comment by jcameron** [comment]
If you have full logging enabled in Webmin, you can see what commands are run for each action at Webmin -> Webmin Actions Log.

**Comment by Stefan-CPlanet** [comment]
Hi @jcameron , thanks for the response.
I did as you suggested, enabled logs, and did the  action and the log came back with:1633419386.86762.0 [05/Oct/2021 1633419386.86762.0 [05/Oct/2021 09:36:26] root 46c28ed9b35e6318dba4c7d659862d1b 192.168.3.30 samba save_group.cgi "create" "group" "group-gqs" 

but I am not quite understanding what it does still, what is save_group.cgi?
Thanks for the help, I really appreciate it

**Comment by Stefan-CPlanet** [comment]
That is what I am seeing but no luck getting the command from the log.

However we managed to get the code by modifying /usr/share/webmin/samba/samba-lib.pl to output into browser when group is created and I managed to come up with command:

/usr/bin/net -s /etc/samba/smb.conf groupmap add  unixgroup=$group ntgroup=$group type=l 2>&1

Thank you for the help.
