### ISSUE TITLE
Feature request: Folder Upload in Filemin

### ISSUE THREAD

**Issue by WolfgangDpunkt** [webmin/webmin#1539]
Please add the possibility to upload folders

I am very fond of Webmin, it is very powerful and sophisticated. The more I was surprised that the File Manager does not support the upload of folders.
In fact, unfortunately, the user does not even necessarily notice this, because folders are uploaded as an empty text file (a kind of dummy file).
I use Firefox on the Mac, but this shouldn't be a problem, because folder upload works in all current browsers as far as I know.
There are apparently even ready-made JS libraries you could use (ex. Dropzone.js)

Thanks a lot! If this feature would be added, I could save myself from having to use extra another file manager, they are all not as fancy and efficient as Webmin (resp. filemin)

**Comment by jcameron** [comment]
@iliaross I thought this was possible already?

**Comment by iliarostovtsev** [comment]
I have added basic support for directories upload on the [commit](https://github.com/webmin/webmin/commit/9f0fc2e4852835e890f736538917234938a9d005) above.

For Authentic Theme, I've been working on making it more user friendly, updating text labels and so automatic detection of whatever user drops would work. I will update this ticket when Authentic Theme receives this (most probably tomorrow). 

Although, basic directory uploads would work in Authentic right now as well.

**Comment by iliarostovtsev** [comment]
Alright, Authentic Theme support been added too.

**Example:**

![image](https://user-images.githubusercontent.com/4426533/139510608-d1a50682-a47f-4be6-a34a-210e2127cb27.png)


![image](https://user-images.githubusercontent.com/4426533/139510621-ab306dec-7990-482d-a97a-cc4e243acb6c.png)


![image](https://user-images.githubusercontent.com/4426533/139510796-0d2ff551-bcaa-4acb-9d01-9a5bee7c088d.png)

**Comment by www3cc** [comment]
Upload catalog

Function has been implemented

**Comment by Soundman2020** [comment]
This works, but only for one directory at a time.  You can't drag and drop several directories, for example. It will accept all of them, but then only show / upload one of them.

**Comment by iliarostovtsev** [comment]
Because you just can't upload multiple directories at once. The workaround would be is to go one directory up (parent) and upload that instead.

**Comment by www3cc** [comment]
@iliaross 
Has upload catalog function
But not at the same level
Upload files and directories together
I look forward to improving

**Comment by www3cc** [comment]
@iliaross 

https://user-images.githubusercontent.com/46883314/145778884-147c8f86-4529-428b-b187-f32bfc539fd2.mp4

**Comment by www3cc** [comment]
Current solution
The only one at the top
Create parent folder

https://user-images.githubusercontent.com/46883314/145780084-79dd0480-bb31-4542-ae1c-706e251c6928.mp4

**Comment by iliarostovtsev** [comment]
> I look forward to improving

Me either. 🙂

> Upload files and directories together

Not sooner than it gets supported by browsers.
