### ISSUE TITLE
File Manager missing upload + unzip

### ISSUE THREAD

**Issue by pirod** [webmin/webmin#1544]
Hi,

The old Java File Manager was very very good. The newer HTML replacement still lacks crucial features we had in Java one.

	Full list of files in directory WITHOUT pagination
	Upload ZIP and unarchive + delete ZIP all in one go
-       Copy/paste file with popup to rename file if the name is the same
-       Browsing tree speed is bad

Coud at least these be added/improved? 

thanks
Pierre

**Comment by iliarostovtsev** [comment]
Hi,

> Full list of files in directory WITHOUT pagination

We already have an ability to display 500 files without pagination in UI and 10.000 files without server pagination. Anything more than that would result in worsen UX.

> Copy/paste file with popup to rename file if the name is the same

We already automatically rename the pasted files with the same name. Renaming in-place would probably be a nice feature to have. Both doesn't seem easy to implement and as important enough to put efforts in. 

>   Browsing tree speed is bad

**Comment by iliarostovtsev** [comment]
In which cases browsing speed is bad? What do you have set in File Manager configuration under **Tree view** for **Extracted depth on initial load** and **Exclude /dev, /proc, /run, /sys, /tmp from traversing on initial load**?

> Upload ZIP and unarchive + delete ZIP all in one go

This is a good feature. I will look into adding it.

**Comment by iliarostovtsev** [comment]
Okay, done -- Support for _upload + extract_ will be included to the next Webmin release.

It will have a new checkbox called **"Extract Compressed"**, which will work with multiple archive types (including _deb_ and _rpm_). It will even be possible to upload a directory with mixed content of regular files/directories and archives, which will also be extracted.
