### ISSUE TITLE
setup.sh error

### ISSUE THREAD

**Issue by ThatOneOcto** [webmin/webmin#1547]
When I was installing webmin on a local headless arch linux install, I got this error
```./setup.sh: line 864: hostname: command not found```

**Comment by jcameron** [comment]
Which operating system are you installing Webmin on? I'm surprised that the `hostname` command would be missing ..

**Comment by ThatOneOcto** [comment]
> Which operating system are you installing Webmin on? I'm surprised that the `hostname` command would be missing ..

I am on arch, also if hostname is a command what is the package for it on the arch repository

**Comment by jcameron** [comment]
Have a look at https://www.reddit.com/r/archlinux/comments/jmwzl2/hostname_command_not_found/

**Comment by jcameron** [comment]
Also, does the `uname -n` command output the hostname on your system?

**Comment by ThatOneOcto** [comment]
> Also, does the `uname -n` command output the hostname on your system?

It does

**Comment by jcameron** [comment]
Excellent - I will have Webmin use the `uname -n` command as a fallback in the next release.
