### ISSUE TITLE
Activation of 2FA on CentOS 8 not possible

### ISSUE THREAD

**Issue by HonkXL** [webmin/webmin#1551]
When trying to activate 2FA in the webmin-settings on CentOS 8 I get a message that Authen::OATH is not installed. In the message I can click to "install", but this ends up in an error (it's working on Debian 10).

For CentOS 8 the manual workaround is:

yum -y install perl-CPAN
perl -MCPAN -e "install Test::Moose"
perl -MCPAN -e "install Types::Standard"
perl -MCPAN -e "install Moo"
perl -MCPAN -e "install Authen::OATH"

After this I can activate it in the webmin-settings.

I think this should be fixed that it can activated over the GUI on CentOS 8, too.

**Comment by iliarostovtsev** [comment]
Hi,

This is not something we can help with. There is just no **`perl-Authen-OATH`** module in default CentOS 8 repos. 

Although, check this link, where you can find Gavin's repos with **`perl-Authen-OATH`** available -

https://github.com/webmin/webmin/issues/1329#issuecomment-736494712

**Comment by iliarostovtsev** [comment]
@swelljoe Do you think we should build it on our own?

**Comment by HonkXL** [comment]
Yes, it's not in the repo. But the text in the message says "click here to install".
Possible soultions:

1. Don't offer the installation in the text. Bring up a help text that shows the 5 commands shown above and the text "to install the missed modules do this on shell".
2. Instead of installing a package to the things above, they are working on CentOS and everything is running. No difference in the user experience between Debian and CentOS.
