### ISSUE TITLE
webmin 1.982 (updated from 1.981) broke sensors Info on Systeminformation Dashboard

### ISSUE THREAD

**Issue by chrissi55** [webmin/webmin#1552]
Since updated version 1.982 the "sensors" info on my raspberry-pi 4B is no longer displayed.

Before til 1.981 the CPU temperature was shown on my Dashboard.

Has changes been made for the Systeminfo Screen so that these infos are missing now?

Would be very kind to fix this.

Regards
chrissi

**Comment by iliarostovtsev** [comment]
Hi,

What is the `sensors` command output? Attach it as text please.

**Comment by frankswebstuff** [comment]
I just updated webmin to 1.982 and have the same result. My sensors output is shown below. 
~$ sensors
coretemp-isa-0000
Adapter: ISA adapter
Core 0:       +43.0Â°C  (high = +74.0Â°C, crit = +100.0Â°C)
Core 1:       +40.0Â°C  (high = +74.0Â°C, crit = +100.0Â°C)
Core 2:       +39.0Â°C  (high = +74.0Â°C, crit = +100.0Â°C)
Core 3:       +38.0Â°C  (high = +74.0Â°C, crit = +100.0Â°C)

**Comment by iliarostovtsev** [comment]
Thanks for reporting it.

I will look into this slightly later today and try to fix it right before the next minor Webmin release.

**Comment by iliarostovtsev** [comment]
It will be fixed on the next Webmin release. Thanks for reporting.
