### ISSUE TITLE
Webmin 1.982: PERL EXECUTION FAILED

### ISSUE THREAD

**Issue by goldmont** [webmin/webmin#1553]
Hi there, after upgrading to V1.982, it doesn't load **Address Records** page.

Error:

> HTTP/1.0 500 Perl execution failed Server: MiniServ/1.982 Date: Sat, 27 Nov 2021 13:20:35 GMT Content-type: text/html; Charset=utf-8 Connection: close
ERROR — PERL EXECUTION FAILED
Modification of non-creatable array value attempted, subscript -1 at /usr/share/webmin/bind8/edit_recs.cgi line 94.

Is there any solution? Thanks.

**Comment by iliarostovtsev** [comment]
What is on the line 93-95

**Comment by jcameron** [comment]
Ok I see the cause of this ..

**Comment by jcameron** [comment]
See attached commit for the fix - we will likely do a minor release for this.

**Comment by goldmont** [comment]
Thank you man.

**Comment by narwahls** [comment]
Hello!

I updated my Webmin Install today and got 1.982 with the aformentioned changes.
By browser default webmin is displayed in german.
The Error is still present in german.
When I enforce the UI to use english, the error is gone.

This is just for your interest.

**Comment by iliarostovtsev** [comment]
Yes, of course. We need to update all translations.

This is done. Thanks a lot for mentioning this!
