### ISSUE TITLE
Custom link "Module Config" is not available when Immediately is enabled.

### ISSUE THREAD

**Issue by niyari** [webmin/webmin#1555]
With this combination of settings, the user does not seem to be able to reach the settings screen unless they specify the URL directly.
![image](https://user-images.githubusercontent.com/2970321/143732957-dc467b11-c1d4-4cd0-8bd7-bb0418cdad35.png)

**Comment by iliarostovtsev** [comment]
Hi,

Yes, the option "**Go to URL immediately**" is intended to work like this.

FYI, Authentic Theme has very sophisticated custom links implementation, allowing you configure any kind of link.

**Comment by niyari** [comment]
What should I do if I want to change the URL when the setting is enabled?

**Comment by iliarostovtsev** [comment]
You could find the module config, under `/etc/webmin/link/config` and edit `window` param manually.

**Comment by niyari** [comment]
Found it! Thank you!
![image](https://user-images.githubusercontent.com/2970321/144550215-8e6e63aa-bcf2-42bf-965d-672cc1bc3f1c.png)
