### ISSUE TITLE
Too many connections (26) from IP X.X.X.X

### ISSUE THREAD

**Issue by Bluscream** [webmin/webmin#1558]
Whenever i'm doing literally anything on webmin, it disconnects me with `Can’t establish a connection to the server at X.X.X.X:X.` on the clientside and spamming `Too many connections (26) from IP X.X.X.X` in `/var/webmin/miniserv.error`

Until i `service webmin restart` i get `ERR_CONNECTION_CLOSED` in chrome

**Comment by jcameron** [comment]
Which browser are you using there? Also, are you connecting directly to Webmin, or via a proxy?

This error shouldn't happen unless there are many many clients connecting at the same time ...

**Comment by iliarostovtsev** [comment]
Also, there was a bug on the theme side which affected, server owners and mail users with disabled status collection.

The simple work around would be is to update the theme to the latest development version which has all these issues fixed.

**Comment by Bluscream** [comment]
> Which browser are you using there? Also, are you connecting directly to Webmin, or via a proxy?
> 
> This error shouldn't happen unless there are many many clients connecting at the same time ...

Chrome and direct

**Comment by Bluscream** [comment]
> Also, there was a bug on the theme side which affected, server owners and mail users with disabled status collection.
> 
> The simple work around would be is to update the theme to the latest development version which has all these issues fixed.

sadly i don't see the Force update button on the theme settings page anymore, so i tried installing the latest release from github instead. i hope that fixes it

**Comment by iliarostovtsev** [comment]
> sadly i don't see the Force update button on the theme settings page anymore, so i tried installing the latest release from github instead. i hope that fixes it

This button is available, just not that easily found anymore but still there, and can be found on **Theme Configuration/Updates** page (last option in drowdown).

**Comment by Bluscream** [comment]
So even after forcing the dev theme i still have the same problem.

Can you tell me where the setting for max connections is located so i can increase it?

**Comment by jcameron** [comment]
You can edit `/etc/webmin/miniserv.conf` and increase or add a line like `maxconns=50`

**Comment by Bluscream** [comment]
Thanks, let's hope this works 👍🏻

**Comment by Bluscream** [comment]
I set it to 150 and that seemed to work, thanks ^^
