### ISSUE TITLE
MySQL 8 removes options

### ISSUE THREAD

**Issue by swelljoe** [webmin/webmin#1561]
MySQL version 8.0.x removes a bunch of configuration options.

In particular, Webmin MySQL module allows adding the now missing `query_cache_size` option on Ubuntu 20.04, which prevents MySQL from starting.

Notice from the MySQL folks: https://dev.mysql.com/doc/refman/8.0/en/added-deprecated-removed.html#optvars-removed

And, the forum discussion that brought this to my attention: https://forum.virtualmin.com/t/mysql-server-configuration-creating-error/

**Comment by iliarostovtsev** [comment]
I remember making a [patch](https://github.com/virtualmin/virtualmin-gpl/commit/ac43de6) on Virtualmin side to handle this in Virtualmin wizard.

You're right that we needed a [fix](https://github.com/webmin/webmin/commit/732941d30ad291d4ec3a4bfb74a26a86d0e936f3) on Webmin side as well.
