### ISSUE TITLE
Bugfixes to get SpamAssassin spamtrap/hamtrap working

### ISSUE THREAD

**Issue by MrPeteH** [webmin/webmin#1562]
As noted in my forum post, I discovered several weak elements in the /usr/share/webmin/virtual-server/spamtrap.pl script. Below are two recommended code changes, without which I could not make this function operate as intended:

1) sub `parse_received_header` doesn't recognize a standard Postfix header
Postfix has a different Received: line for "local submissions". Inserting the following code before the "Authenticated" line provides proper support:
```
elsif ($str =~ /by\s+(\S+)\s+\(Postfix, from userid (\S+)\)/i) {
        # by my.dom.ain (Postfix, from userid 1022)
        $uname = getpwuid($2);
        }
```
2) Webmin only checks `from`, `to` and `cc` headers for recognized users. But any use of aliases breaks this. 
A simple addition solves it, since a non-alias mailbox is very likely used to forward messages to spam/ham trap, and/or a non-alias mailbox is very likely the final delivery target of the original message. The needed edit:
Change:
` foreach $h ('from', 'to', 'cc',) {`
To:
` foreach $h ('from', 'to', 'cc','resent-from','delivered-to') {`

**Comment by jcameron** [comment]
Thanks for the suggestions! We'll include these in the next release of Virtualmin..
