### ISSUE TITLE
Suggestion for "http remote service" tool

### ISSUE THREAD

**Issue by luison** [webmin/webmin#1564]
Perhaps I am missing something but I would like to suggest an improvement to the "http remote service" tool of System and Server Status.

I haven't worked out a way to monitor that an http request responds with a 401. This is... if an URL should be unaccesible to unknown IPs for example, the correct state would be to not respond with 200 but a 401 instead.

![image](https://user-images.githubusercontent.com/745632/146053205-6411e98a-9b4f-42f3-a03f-da117dee31ff.png)

The "head" response seems to now allow the regexp evaluation tool and I am not sure why as the a regexp over the responded headers would allow me to test that the response includes any code... 401, 301, etc.

**Comment by jcameron** [comment]
That's an excellent idea ...

**Comment by jcameron** [comment]
I have implemented this for inclusion in the next release of Webmin.
