### ISSUE TITLE
Invitation Contributing to Webmin Support for Debian 11

### ISSUE THREAD

**Issue by Francewhoa** [webmin/webmin#1565]
## Summary

This ticket is about inviting volunteer service contributions to facilitate **Webmin** support for the released [**Debian 11 Bullseye**](https://www.debian.org/News/2021/20210814). And ask if there is anything needed we could contribute to? Documentation? Testing? What else? Both me and other contributors expressed interest in this. We're wondering is any is presently needed?

2 questions below

-------------------------------

Below is the same message as above. But with details if you're interested in those.

## Contributing

This ticket is for all contributors interested to facilitate **Webmin** support for Debian 11. If Virtualmin team, or any other contributors need any, you are really welcome to use this ticket.

This ticket is to offer volunteer contributions to facilitate **Webmin** support for Debian 11 Bullseye. If Virtualmin team, or any other contributors need any, you are really welcome to use this ticket.

For example, in addition to my offer of volunteer contributor time, my company Ubertus.org is both willing & happy to offer **access to up to USD 4,000 yearly of advanced online & reputable testing tools.** Such as [BrowserStack](https://www.browserstack.com) and [Sauce Labs](https://saucelabs.com/) accounts. For those not familiar with those tools, they allow you to remotely test with 3000+ remotely controlled real devices and browsers. Those accounts are limited. So Ubertus offers them first to contributors who demonstrated past public interest to contribute to **Webmin**. No strings attached. This is a [gift](https://en.wikipedia.org/wiki/Gift_economy) for those efforts. And Ubertus do not expect anything in return.

## Questions

**Question 1. For Contributors.**
Any other volunteer contributors interested to offer testing or documentation or anything else to your liking? All are welcome to join the efforts to facilitate **Webmin** support for **Debian 11 Bullseye**. I believe that both small and large contributions can facilitate such efforts. You're welcome to subscribe or add comments on this ticket. So that you're notified about future needs to facilitate any efforts.

**Question 2. For Staff.** 
Beside testing and documentation, is there any other types of volunteer service contributions that would facilitate the efforts for **Webmin** support for **Debian 11 Bullseye**?

## Intention

What is my intention with this ticket? 
1. Facilitate interested volunteer contributions. Toward **Webmin** support for Debian 11. 
2. Invite others to express any need for contributions for this
3. All of the above free from interference. In other words, other volunteers are really free to decide what is their gift, where, when, how they contribute it. I would welcome the same in return.

What is **not** my intention with this ticket? Nothing else than the above. I understand that Virtualmin staff do not pre-annonce date for Debian 11. I believe that this is fair and make sense. This choice was successful in the past. I know that it is a lot of work to support any new OS version. Obviously, this ticket is an **invitation** to express need if any are needed. Not force contributions to others. For those not interested, feel really free to decline this invitation. I also have no intention of interfered with other contributors. Speaking for myself, you are really free from interference. I believe that diversity is a strength.

Speaking for myself, one of the main benefit I see with Libre/Open Source software is that if I'm interested in a product supporting a new OS version. One of many ways to potentially reach that goal faster, is for volunteers to offer to contribute. In turn, others, from their own free will, are welcome to decide if any are needed. Both very small and very large contributions can make a difference 💚 .

Cheers,

Francois Carpentier (Francewhoa)

## Related Tickets

* #1570  
*  #343 
*  #1565

**Comment by iliarostovtsev** [comment]
https://forum.virtualmin.com/t/virtualmin-7-and-debian-11/113031/7?u=ilia
