### ISSUE TITLE
Expired GPG certificate 

### ISSUE THREAD

**Issue by pateze** [webmin/webmin#1567]
Hello! I am trying to install webmin on ubuntu adding the repository to the sources.list and it does not allow me to install the certificate because it is expired. I had to do it manually. Here is what my terminal shows me when doing an apt update: 
```
...
Err:4 https://download.webmin.com/download/repository sarge Release
  Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 108.60.199.109 443]
...
```

**Comment by jcameron** [comment]
This can happen if your system doesn't have updated CA certificates. The fix is to run `apt install ca-certificate`

**Comment by pateze** [comment]
Oops... something strange happened with my ubuntu (or apt), because it had all the dependencies installed correctly, however the error persisted, which led me to deduce that it was the certificate! 😆 I managed to fix it with a simple... Reboot!
Thank you very much for your help @jcameron.
