### ISSUE TITLE
Feature-Wish - copy Version to clipboard

### ISSUE THREAD

**Issue by xstable** [webmin/webmin#1569]
If you fill a Ticket in forum (e.g. https://forum.virtualmin.com/) you have - and should - add Information about your environment. 

They are still there in Webmin, but you can't copy it - by markt and copy.
![image](https://user-images.githubusercontent.com/1778068/147385180-7d3ec8ae-9c5e-47af-af5e-ffe272d88df3.png)

Would be great if there would be a simple way to click on a button to copy all - for support tickets needed information - to the clipboard. 
This become very handy and will save a lot's of time in sum.

**Comment by jcameron** [comment]
@iliaross could we add this to the dashboard in the theme?

**Comment by iliarostovtsev** [comment]
Yes, I will add it.

**Comment by iliarostovtsev** [comment]
The latest **19.84.8-beta1** adds support for copying complete system information to clipboard.

![image](https://user-images.githubusercontent.com/4426533/147510978-1d764d75-7ac4-41ff-82db-f55745a2a8de.png)

It can be copied as markdown text or plain text.

**Plain text** example:

```
System Information
System hostname: debug-debian10-pro.localdomain
Operating system: Debian Linux 10
Time on system: Monday, December 27, 2021 5:26 PM
Kernel and CPU: Linux 4.19.0-13-amd64 on x86_64
Processor information: Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz, 2 cores
System uptime: 6 hours, 45 minutes
Running processes: 125
CPU load averages: 0.46 (1 min) 0.19 (5 mins) 0.12 (15 mins)
Real memory: 590.37 MiB used /  724.05 MiB cached  / 1.94 GiB total
Virtual memory: 60.75 MiB used / 974.99 MiB total
Local disk space: 3.56 GiB used /  10.19 GiB free  / 13.76 GiB total
Package updates: 77  package updates are available

Software Versions
Webmin version: 1.979.0627.1240
Usermin version: 1.823
Virtualmin version: 6.16  Pro
Authentic theme version: 19.84.8-beta1-3
Perl version: 5.028001
Path to Perl: /usr/bin/perl
Python version: 3.7.3
Path to Python: /bin/python3
BIND version: 9.11
Postfix version: 3.4.14
Mail injection command: /usr/lib/sendmail -t
Apache version: 2.4.38
PHP versions: 7.3.27
Webalizer version: 2.23-08
Logrotate version: 3.14.0
MariaDB version: 10.3.29
ProFTPD version: 1.36
SpamAssassin version: 3.4.2

Virtualmin Counts
DNS domains: 3
Virtual websites: 3
SSL websites: 2
Mail domains: 3
Databases: 2
Mail/FTP users: 1
Mail aliases: 8

```

**Markdown text** example:

|SYSTEM INFORMATION&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;| |
|---|---|
|**System hostname:** |debug-debian10-pro.localdomain|
|**Operating system:** |Debian Linux 10|
|**Time on system:** |Monday, December 27, 2021 5:27 PM|
|**Kernel and CPU:** |Linux 4.19.0-13-amd64 on x86_64|
|**Processor information:** |Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz, 2 cores|
|**System uptime:** |6 hours, 45 minutes|
|**Running processes:** |121|
|**CPU load averages:** |0.24 (1 min) 0.17 (5 mins) 0.11 (15 mins)|
|**Real memory:** |467.55 MiB used /  724.09 MiB cached  / 1.94 GiB total|
|**Virtual memory:** |60.75 MiB used / 974.99 MiB total|
|**Local disk space:** |3.56 GiB used /  10.19 GiB free  / 13.76 GiB total|
|**Package updates:** |77  package updates are available|

|SOFTWARE VERSIONS&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;| |
|---|---|
|**Webmin version:** |1.979.0627.1240|
|**Usermin version:** |1.823|
|**Virtualmin version:** |6.16  Pro|
|**Authentic theme version:** |19.84.8-beta1-3|
|**Perl version:** |5.028001|
|**Path to Perl:** |/usr/bin/perl|
|**Python version:** |3.7.3|
|**Path to Python:** |/bin/python3|
|**BIND version:** |9.11|
|**Postfix version:** |3.4.14|
|**Mail injection command:** |/usr/lib/sendmail -t|
|**Apache version:** |2.4.38|
|**PHP versions:** |7.3.27|
|**Webalizer version:** |2.23-08|
|**Logrotate version:** |3.14.0|
|**MariaDB version:** |10.3.29|
|**ProFTPD version:** |1.36|
|**SpamAssassin version:** |3.4.2|

|VIRTUALMIN COUNTS&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;| |
|---|---|
|**DNS domains:** |3|
|**Virtual websites:** |3|
|**SSL websites:** |2|
|**Mail domains:** |3|
|**Databases:** |2|
|**Mail/FTP users:** |1|
|**Mail aliases:** |8|



---


Yet, it is still not possible to select the text directly, what you mentioned in the first place, as that is a drag-and-drop element. Assuming newly added feature, do you think you would still need that? I haven't checked yet if it's possible to make it work without a hassle.

**Comment by iliarostovtsev** [comment]
Alright, I think it was quite annoying that it wasn't possible to copy text from draggable. With the latest commit, it will be possible to copy text from draggable on the Dashboard by using the standard operation (holding down Alt key while selecting the text (moving mouse left/right)). Also it will be possible to select text with double clicking on it.

Thanks for reporting.
