### ISSUE TITLE
Virtualmin needs option to set default IP addresses to wildcard

### ISSUE THREAD

**Issue by robbrandt** [webmin/webmin#157]
As described here:
http://www.virtualmin.com/node/33057

In a nutshell, you cannot rely on getting the same IP address from Amazon if you stop the server for any length of time and then start it again.  Public addresses are handled via Elastic IPs, which are outside of the server instance.  So the most reliable way of setting up virtual hosts is with the IP address wildcarded.  But there doesn't seem to be  a way of doing that in Virtualmin.

Our use case is for single servers, but I think this issue would be an even bigger nightmare when using autoscaling, which will start additional instances of servers in a "cluster" depending on load.  Virtually guaranteed that the secondary instances are going to get new IP addresses.

**Comment by manusfreedom** [comment]
NameVirtualHost is deprecated in Apache 2.4:
AH00548: NameVirtualHost has no effect and will be removed in the next release

**Comment by qooob** [comment]
+1 and mod_mpm_itk! ;)

**Comment by jcameron** [comment]
Virtualmin shouldn't be adding a `NameVirtualHost` directive anywhere if you're running Apache 2.4 or above.

**Comment by manusfreedom** [comment]
Yes, but it adds IP instead of '*'.

**Comment by rocksfrow** [comment]
has anything ever come of this? i'm having the same issue -- lack of the ability to create new virtual hosts in virtualmin with wildcard IP addresses (name-based apache hosting)

**Comment by rocksfrow** [comment]
@jcameron

**Comment by aminhusni** [comment]
Having the same problem. I have a "floating IP" from Digitalocean and I can't use it unless I go in and edit manually of the site's config files(/etc/apache2/sites-available) to <VirtualHost *:80> instead of having an IP address.

**Comment by jcameron** [comment]
In recent versions, as long all your existing Virtualhost blocks use *:80 and you have a NameVirtualHost entry for *:80, it will also be used for new domains.

**Comment by chris001** [comment]
> and you have a NameVirtualHost entry for *:80, it will also be used for new domains.
@jcameron But isn't `NameVirtualHost` deprecated and setting it no longer has any effect on recent versions of apache i.ee 2.4 and newer.
* https://serverfault.com/questions/735233/is-namevirtualhost-necessary
* `Nov 10 13:55:05 hostname apache2[1718]: Starting web server: apache2: NameVirtualHost has no effect and will be removed in the next release /etc/apache2/ports.conf:6`
* https://httpd.apache.org/docs/2.4/mod/core.html#namevirtualhost

**Comment by rocksfrow** [comment]
During my testing, the very first vhost created after appending
namevirtualhost * ends up with the IP in the confit not *. Does the default
vhost need converted to * first?

**Comment by jcameron** [comment]
@chris001  - you're right, under Apache 2.4+ you don't need NameVirtualHost at all.

@rocksfrow - yes, the default virtualhost should be converted to use * instead of an IP. Apache has some surprising rules about how it selects the matching virtualhost, which are made extra complex when * and non-* are in use at the same time.

**Comment by rocksfrow** [comment]
Sweet I’ll test tonight thanks!

**Comment by aminhusni** [comment]
Solved it by putting the IP address as 0.0.0.0 instead.

**Comment by Sam-Butler** [comment]
I'm having the same issue with Virtualmin 6.06 on CentOS 7.6.1810 with Apache 2.4.6 (from a non-Virtualmin repo). Despite having no IPs anywhere in the conf and with or without a NameVirtualHost directive, every new vhost is created with the server's IP. We use Unison to push the conf to another node and both connect to the same NFS device so they can be load balanced, while Virtualmin runs on only one of the nodes. We've done this successfully on a previous cluster with no obvious differences, and that one creates new vhosts with *:80. Obviously we can't have the  IP in the conf or the other node won't listen.

I'm tearing my hair out here, does anyone have any wisdom?

**Comment by swelljoe** [comment]
This is a quite old ticket, and default behavior in Virtualmin has changed since it was first discussed.

I'm going to close it, as there *is* an option to always use wildcards, and quite a bit of the discussion on the ticket is now misleading since default behavior regarding whether Virtualmin will use a wildcard changed a few revisions back (and it can't be "tricked" into using `*` instead of IPs by adding one VirtualHost with a `*`). But, the comment from @pafcioooo is right. That is where it is configured.
