### ISSUE TITLE
webmin login page is not normal when access from reverse proxy

### ISSUE THREAD

**Issue by Unstable0** [webmin/webmin#1573]
when I try to access my site `example.xyz/wmin` it shows this

![Screen Shot 2565-01-04 at 7 08 36 AM](https://user-images.githubusercontent.com/46888825/147993477-77e644c7-4dbd-4289-840d-b73ca2a9c90d.png)

my webmin is running on `example.xyz:2087` and I make a reverse proxy to proxy `example.xyz/wmin` to `example.xyz:2087`

I'm using polka and http-proxy-middleware

this is my server.js

```js
const { handler } = polka() // You can also use Express
	.use("/wmin", createProxyMiddleware({
		target: "https://example.xyz:2087/", changeOrigin: true, prependPath: true, followRedirects: true, headers: {
			Host: "example.xyz:2087"
		},
		pathRewrite: {
			["^/wmin"]: "/wmin/",
		}, cookiePathRewrite: {
			"/wmin/": "https://example.xyz:2087/"
		},
		cookieDomainRewrite: {
			"/wmin/": "https://example.xyz:2087/"
		}
	}))
	.use(
		compression({ threshold: 0 }),
		sirv('static', { dev }),
		sapper.middleware()
	)

createServer(options, handler).listen(ssl_port, _ => {
	console.log("Server Running on Port 443")
});
```

**Comment by jcameron** [comment]
Do you have the line `webprefix=/wmin` in your `/etc/webmin/config` file, so that Webmin knows about the different path?

**Comment by Unstable0** [comment]
yes i do

**Comment by jcameron** [comment]
@iliaross it looks like the rest of the theme login page isn't being displayed properly in this case?

**Comment by Unstable0** [comment]
yep

**Comment by Unstable0** [comment]
but it;s fine now, I switched to nginx and changed my webmin port to 10000

```
    location /webmin/ {
        proxy_pass https://localhost:10000/;
    }
```

and now it work when I access `example.xyz/webmin
thanks for helping tho

![Screen Shot 2565-01-04 at 11 29 32 AM](https://user-images.githubusercontent.com/46888825/148009657-e765835b-c9eb-47fa-9d45-983eefb8a83f.png)
