### ISSUE TITLE
NSEC3 support with safer algorithms

### ISSUE THREAD

**Issue by danci1973** [webmin/webmin#1576]
I recently installed Webmin 1.984 for primary purpose of managing Bind with DNSSEC. I quickly realized that Webmin's Bind8 module only supports NSEC3 with the two algorithms that have 'NSEC3' in their name (NSEC3RSASHA1 and NSEC3DSA, which shouldn't be used anymore), even though other (newer and safer) algorithms are also NSEC3 capable - I know of these, but there could be more:

- RSASHA256
- RSASHA512
- ECCGOST
- ECDSAP256SHA256
- ECDSAP384SHA384

My coding skills are quite limited, so my very simplistic 'fix' for this is adding these algorithms to the regex that selects whether dnssec-signzone should generate NSEC3 records or not (i.e. using -3 argument):

``` diff
--- bind8/bind8-lib.pl-20210110 2022-01-10 21:21:15.897651396 +0100
+++ bind8/bind8-lib.pl  2022-01-10 21:18:11.387758578 +0100
@@ -3487,7 +3487,7 @@
        $out = &backquote_logged(
                "cd ".quotemeta($dir)." && ".
                "$config{'signzone'} -o ".quotemeta($dom).
-               ($alg =~ /^NSEC3/ ? " -3 -" : "").
+               ($alg =~ /^NSEC3|RSASHA256|RSASHA512|ECCGOST|ECDSAP256SHA256|ECDSAP384SHA384/ ? " -3 -" : "").
                " -f ".quotemeta($signed)." ".
                quotemeta($chrootfn)." 2>&1");
        last if (!$?);
```

This works for my purpose as I have no reason for not using NSEC3 with algorithms that support it, but if there are any legitimate reasons to do so, it would be better to have a toggle for using / not usingNSEC3.

I hope someone with better Perl skills (and possibly DNSSEC knowledge) can pick this up and propose a better fix.

**Comment by jcameron** [comment]
Thanks! I will include this in the next Webmin release.
