### ISSUE TITLE
NSEC3PARAM - original TTL error

### ISSUE THREAD

**Issue by danci1973** [webmin/webmin#1577]
After recently implementing DNSSEC through Webmin 1.984, https://dnsviz.net reported an error regarding the TTL of NSEC3PARAM and it's RRSIG record:

> RRSIG example.com/NSEC3PARAM alg 13, id 48018: The TTL of the RRset (3600) exceeds the value of the Original TTL field of the RRSIG RR covering it (0).

dnssec-signzone utility creates the NSEC3PARAM and it's RRSIG record with 0 TTL:
```
                        0       NSEC3PARAM 1 0 10 -
                        0       RRSIG   NSEC3PARAM 13 2 0 (
                                        20220209194832 20220110194832 12073 example.com.
                                        q8p+rkhXmv8/NOTGMOlT9mCo20cNhTrfllEp
                                        4uXn4O4bHG5BW4JpuSCKB0BQc+5b1FtJklaQ
                                        PEuh7dSB3cVAfA== )
```

However, when Webmin's Bind8 module merges these records back to the original zone file, it omits the TTL field and leaves it emtpy:
```
example.com. IN      NSEC3PARAM      1 0 10 -
example.com,. IN      RRSIG   NSEC3PARAM 13 2 0 20220209194832 20220110194832 12073 example.com. q8p+rkhXmv8/NOTGMOlT9mCo20cNhTrfllEp 4uXn4O4bHG5BW4JpuSCKB0BQc+5b1FtJklaQ PEuh7dSB3cVAfA==
```

The problem is, that RRSIG record includes the 'original TTL' field, which is, of course, 0 and is therefore inconsistent with the actual TTL.

I think the problem lies in the _make_record_ subroutine, specifically the 'return' statement:

``` perl
# make_record(name, ttl, class, type, values, comment)
# Returns a string for some zone record
sub make_record
{
my ($name, $ttl, $cls, $type, $values, $cmt) = @_;
$type = $type eq "SPF" && !$config{'spf_record'} ? "TXT" :
        $type eq "DMARC" ? "TXT" : $type;
return $name . ($ttl ? "\t".$ttl : "") . "\t" . $cls . "\t" . $type ."\t" .
       $values . ($cmt ? "\t;$cmt" : "");
}
```

I think the `($ttl ? "\t".$ttl : "")` part returns an empty string if $ttl=0 - which it should not. Since TTL can (obviously) be 0, this should also be returned as such.

Unfortunately, my Perl is to weak to propose a fix.

**Comment by jcameron** [comment]
Thanks for pointing this out! We'll fix it in the next release of Webmin..

**Comment by danci1973** [comment]
After a good night's sleep I've come up with a possible fix:

``` diff
--- records-lib.pl-20220110     2022-01-10 22:56:50.404277307 +0100
+++ records-lib.pl      2022-01-11 08:16:56.097904803 +0100
@@ -478,7 +478,7 @@
 my ($name, $ttl, $cls, $type, $values, $cmt) = @_;
 $type = $type eq "SPF" && !$config{'spf_record'} ? "TXT" :
         $type eq "DMARC" ? "TXT" : $type;
-return $name . ($ttl ? "\t".$ttl : "") . "\t" . $cls . "\t" . $type ."\t" .
+return $name . ($ttl eq "" ? "" : "\t".$ttl) . "\t" . $cls . "\t" . $type ."\t" .
        $values . ($cmt ? "\t;$cmt" : "");
 }
```
Instead of checking just $ttl, check if it's empty and return `"\t".$ttl` if it is not.
