### ISSUE TITLE
fail2ban: adding multiple ports to jail 

### ISSUE THREAD

**Issue by gaos23** [webmin/webmin#158]
webmin module : fail2ban
When i want to add multiple ports ( like 80,8080 ) to jail and want to save it
get error : Failed to save jail : Invalid port number for action 1

**Comment by jeremybrown82** [comment]
Is there any way to block a range of ports?

**Comment by jcameron** [comment]
You can enter something like 1000:2000 to match all ports in that range.

**Comment by jeremybrown82** [comment]
Interesting, there seems to be no way to do it in GUFW. Although i'm sure it works in UFW.

**Comment by jucajuca** [comment]
> Thanks - this will be supported in the next Webmin release.

where can I configure multiple ports for sshd? 

best,

**Comment by iliarostovtsev** [comment]
> where can I configure multiple ports for sshd?

You can configure it on **Webmin > Servers > SSH Server > Networking**, and adding ports as space separated list - 

![image](https://user-images.githubusercontent.com/4426533/93755292-b03f4e00-fc0b-11ea-8ff7-3b8c39a4173c.png)

**Comment by jucajuca** [comment]
oh, thanks, I was talking about fail2ban. But I changed the ports manually in the jail.local file.
