### ISSUE TITLE
webmin.com Certificate outdated

### ISSUE THREAD

**Issue by HanseGarant** [webmin/webmin#1582]
Hi Admins!

Today we wanted to install webmin on our linux VM.
We're receiving errors because of an outdated certificate. I think I'm not alone in this point.

It would be fine, if you could renew the certificate shortly.

Best regards

**Comment by jomymathew** [comment]
I'm seeing this on my end as well.

It's causing some (resolvable) issues with apt also since http://download.webmin.com/download/repository isn't signed either.

**Comment by iliarostovtsev** [comment]
The issue with the certificate has been fixed.

Thanks for reporting.
