### ISSUE TITLE
Custom Commands - edit Syntax Highlight not based on file type

### ISSUE THREAD

**Issue by GAS85** [webmin/webmin#1591]
Hello dear community,

When I edit files, Syntax Highlight is always set to the wrong format - `PEG.js`. And I need to select correct one manually. Is there is a way to automate it? I check `MIME` Section, but didn't found anything related to Webmin there.

E.g. I have `.sh` file
![grafik](https://user-images.githubusercontent.com/6813635/152308519-6e2b6581-5530-4350-86d3-0eb3ceafcc34.png)

and `PEG.js` is always chosen, so no highlight till I change it manually:
![grafik](https://user-images.githubusercontent.com/6813635/152308667-b231c7ee-0e11-4905-95ec-2e5a474c744d.png)

The same issue is with `yaml` files and all other:
![grafik](https://user-images.githubusercontent.com/6813635/152308797-a15086d9-435c-489a-a797-8c8da5ded32e.png)

**Comment by iliarostovtsev** [comment]
Hi,

You are right. This is a bug! This will be fixed on the next Webmin release. Thanks for reporting.

**Comment by iliarostovtsev** [comment]
We will also add an ability to detach a file to separate pop-up editor, when editing a file in Custom module.
