### ISSUE TITLE
Bandwidth Module - WEBMIN_CONFIG not set at .../web-lib-funcs.pl 

### ISSUE THREAD

**Issue by Sarge2013** [webmin/webmin#1598]
Hello,
I don't know is bandwidth module is still alive - but may be it's a small bug what can be easily fixed ?
Environment - CentOS 7, SYSLOG-NG, latest Webmin -> Bandwidth module installed but even after few hours same story "No traffic has been summarized by this module yet."

Well, located and tried to run directly from command line (at-least to see what it will say)
**cd /usr/libexec/webmin/bandwidth/ ;
perl /usr/libexec/webmin/bandwidth/rotate.pl**

Answer
**WEBMIN_CONFIG not set at ../web-lib-funcs.pl line 4779.
Compilation failed in require at ./rotate.pl line 5.**

May be this is the reason why "no traffic summarized..." ?

So if this module still "workable" - thanks for any idea how to try fix,
Regards
Serge

**Comment by jcameron** [comment]
That command isn't supposed to be run directly - instead you have to run `/etc/webmin/bandwidth/rotate.pl` which sets the right environment variables.

**Comment by Sarge2013** [comment]
Strange but default YUM installation from your repo did not install /etc/webmin/bandwidth/rotate.pl
I have copied
cp /usr/libexec/webmin/bandwidth/rotate.pl /etc/webmin/bandwidth/rotate.pl
and run Update Statistic from Webmin GUI - no effect, then tried from command line
perl /etc/webmin/bandwidth/rotate.pl
...same answer
WEBMIN_CONFIG not set at ../web-lib-funcs.pl line 4779.
Compilation failed in require at /etc/webmin/bandwidth/rotate.pl line 5.

Such a feeling the module can't find the right environment...and this is the only reason why it can't start to collect data.
But I'm not a PERL developer to understand what and where is wrong - so I can't manage with the code myself, just can follow the instructions what where to change.
(it should be a useful module, it's a pity to not use the one)

**Comment by Sarge2013** [comment]
I found it's wrong rotate.pl
Replaced with content
#!/usr/bin/perl
open(CONF, "</etc/webmin/miniserv.conf") || die "Failed to open /etc/webmin/miniserv.conf : $!";
while(<CONF>) {
        $root = $1 if (/^root=(.*)/);
        }
close(CONF);
$root || die "No root= line found in /etc/webmin/miniserv.conf";
$ENV{'PERLLIB'} = "$root";
$ENV{'WEBMIN_CONFIG'} = "/etc/webmin";
$ENV{'WEBMIN_VAR'} = "/var/webmin";
delete($ENV{'MINISERV_CONFIG'});
chdir("$root/bandwidth");
exec("$root/bandwidth/rotate.pl", @ARGV) || die "Failed to run $root/bandwidth/rotate.pl : $!";
************* EOF
and run again 
cd / ; perl /etc/webmin/bandwidth/rotate.pl
NO ERRORS ! - but again no a visible result.
/var/log/bandwidth - empty
/etc/webmin/bandwidth/hours/ - empty too

**Comment by Sarge2013** [comment]
I've Turned-Off Monitoring and enabled again, I see the cron added
0 * * * * /etc/webmin/bandwidth/rotate.pl
also iptables rules
-A FORWARD -o enp3s0 -j LOG --log-level 7 --log-prefix BANDWIDTH_OUT:
-A FORWARD -i enp3s0 -j LOG --log-level 7 --log-prefix BANDWIDTH_IN:
-A OUTPUT -o enp3s0 -j LOG --log-level 7 --log-prefix BANDWIDTH_OUT:
-A INPUT -i enp3s0 -j LOG --log-level 7 --log-prefix BANDWIDTH_IN:

Not found any changes in /etc/syslog-ng/syslog-ng.conf if should be...
...so it looks like everything is running - but anyway no any output...

**Comment by jcameron** [comment]
That file should be created the first time you do the setup process in the Bandwidth module, like in this screenshot : 

![image](https://user-images.githubusercontent.com/102706/153768732-35c85912-bc69-427a-b803-e677c0b6a968.png)

**Comment by Sarge2013** [comment]
Of course I did this setup ! as I wrote above - 
I've Turned-Off Monitoring and enabled again, I see the cron added
0 * * * * /etc/webmin/bandwidth/rotate.pl
also iptables rules
-A FORWARD -o enp3s0 -j LOG --log-level 7 --log-prefix BANDWIDTH_OUT:
-A FORWARD -i enp3s0 -j LOG --log-level 7 --log-prefix BANDWIDTH_IN:
-A OUTPUT -o enp3s0 -j LOG --log-level 7 --log-prefix BANDWIDTH_OUT:
-A INPUT -i enp3s0 -j LOG --log-level 7 --log-prefix BANDWIDTH_IN:

**But I assure you NO FILE BW.PL exists at my server - nowhere ! I made all possible searches !**
I've downloaded your source installation webmin-1.984.tar.gz,untar the one and made inside search for bw.pl file using
ack "bw.pl" /webmin-1.984/
so no one file inside /webmin-1.984/ contains bw.pl
As I understand - it means that no one part of code can't create file bw.pl
Could you please cross-check your code from your side ?

**Comment by iliarostovtsev** [comment]
> But I assure you NO FILE BW.PL exists at my server - nowhere ! I made all possible searches !

Jamie meant to say **`/etc/webmin/bandwidth/rotate.pl`** file, not **`bw.pl`** file as the latter created in Virtualmin.

**Comment by iliarostovtsev** [comment]
> But I assure you NO FILE BW.PL exists at my server - nowhere ! I made all possible searches !

Jamie meant to say **`/etc/webmin/bandwidth/rotate.pl`** file, not **`bw.pl`** file as the latter created in Virtualmin.

**Comment by Sarge2013** [comment]
I did not understand why you have closed the issue if the problem still exists.
I inform that no data has collected by Bandwidth Module
/var/log/bandwidth = 0
/etc/webmin/bandwidth/hours/ - empty
Webmin GUI - see picture
![2022-02-14 15 17 51 usloft6336 startdedicated com c1a261870f93](https://user-images.githubusercontent.com/5161375/153871850-08ff6af4-80fc-43be-bc78-927e09128c26.png)
If you assure this module works - where are the data ?

**Comment by Sarge2013** [comment]
May be we'd better to close this issue but continue on issue [https://github.com/webmin/webmin/issues/1600](https://github.com/webmin/webmin/issues/1600) as there more exact problem description.
