### ISSUE TITLE
RP-PPPOE ADSL module seems incompatible with Debian based distributions

### ISSUE THREAD

**Issue by JSebMe** [webmin/webmin#1599]
The ADSL module is not working with Debian based distributions like Ubuntu. Each time I tried it, I faced a "not found rp-pppoe" warning. There is no rp-pppoe package for Debian, PPPOECONF is the way to go. If it is supposed to work with pppoeconf, it is not working easy enough. I am able to use pppoeconf in terminal to connect to my ISP, but if I wish to use Webmin, I need this connection to register to Webmin as a base for my routing config. So, if it's supposed to work, how? And it needs to be etheir simplified or well explained instead of a simple "sorry, it's not working" kind of a message. But, I think it isn't working at all. I search a lot on that issue without having found any solution and I don't understand why, because I am surely not alone using PPPOE to connect to my ISP.  
Thanks

**Comment by jcameron** [comment]
Do you know if `pppoeconf` uses the same config file format and command line flags as `rp-pppoe` ? Webmin would only be compatible if it does..

**Comment by JSebMe** [comment]
I tried to compare the 2 and would say no even if I can't be certain due to the lack of information on RP-PPPOE. But, my searches seem to result in showing that rp-pppoe isn't anymore a solution in Debian (forks of it too) and CENTOS later than 4 or 5. So, I would like to help clarify this issue but I'm not even close of having the required knowledges... sorry

**Comment by JSebMe** [comment]
Maybe this page could help : 
https://www.systutorials.com/docs/linux/man/8-pppoeconf/

I didn't find anything that obvious for rp-pppoe

**Comment by jcameron** [comment]
Unfortunately you can't use pppoeconf with Webmin then - we'd need to create a whole new module for it.

**Comment by JSebMe** [comment]
Ok. So I did right by opening this issue. I'm a bit confused to see that nobody has report that problem before... So, I can be optimistic to see it someday? Do this comment have to be closed? I will let you do what is best. Thanks

**Comment by swelljoe** [comment]
Unless you're volunteering to build and mainatin it, I would consider the odds of a module being made for it very, very, slim. This is an extremely niche tool. I mean, nobody was even maintaining it for many years, and maybe someone recently adopted it (https://github.com/dfskoll/rp-pppoe)

It's just not a thing that comes up very often these days. I didn't know PPPOE was even still in common use as a protocol.

**Comment by JSebMe** [comment]
A last question. I will not make that module because I can't with my knowledges even if I would have been interested...
Is there a way to use a PPPOE config with pppoeconf and use it safely in Webin without the module? Until now, my working PPPOE is shown in Webmin.

**Comment by jcameron** [comment]
What kind of configuration of PPPOE do you want to do in Webmin?

**Comment by JSebMe** [comment]
The only way to avoid double NAT with my ISP gateway is to use its pppoe passthrough method. What I want is connecting one of my ethernet card with pppoe and be recognized as my wan interface in Webmin. I can setup the connection with pppoeconf through the terminal, but Webmin doesn't see it as a normal DHCP client interface. Webmin shows the hardware interface (ENP3S0) connected to the gateway as a part of its internal network with an ip given by its DHCP server, but at the same time my ppp0 (configure with pppoeconf on ENP3S0) connection is shown within the active interfaces but greyed out (I don't know how to interact with it and tell webmin that it was my WAN interface instead of the other network. At least ppp0 appeared in Active Interfaces. RP-PPP0E wasn't working though.
