### ISSUE TITLE
Bandwidth Module - No traffic has been summarized 

### ISSUE THREAD

**Issue by Sarge2013** [webmin/webmin#1600]
Hello,
In previous issue we solved the start of this module - but still not solved why it does not generate any data (as should be from description). I suppose we have to finalize the issue.
Environment - CentOS 7, SYSLOG-NG, latest Webmin 1-984.
So - no data has collected by Bandwidth Module
/var/log/bandwidth = 0
/etc/webmin/bandwidth/hours/ - empty
Webmin GUI - see picture
![Bandwidth_State](https://user-images.githubusercontent.com/5161375/153935985-8514cbc7-72cc-4b95-a807-ee52d4e2903f.png)

As I wrote before - it should be a useful module as per it's description, it's a pity to not use the one.
But is this module still alive and workable ?
Regards
Serge

**Comment by jcameron** [comment]
Which firewall are you using on your system? If it's IPtables, check in the Linux Firewall module that there are LOG rules setup ..

**Comment by Sarge2013** [comment]
I see that cron job created
0 * * * * /etc/webmin/bandwidth/rotate.pl

Also I see IPTABLES rules /etc/sysconfig/iptables
-A FORWARD -o enp3s0 -j LOG --log-level 7 --log-prefix BANDWIDTH_OUT:
-A FORWARD -i enp3s0 -j LOG --log-level 7 --log-prefix BANDWIDTH_IN:
-A OUTPUT -o enp3s0 -j LOG --log-level 7 --log-prefix BANDWIDTH_OUT:
-A INPUT -i enp3s0 -j LOG --log-level 7 --log-prefix BANDWIDTH_IN:

Not found any changes in /etc/syslog-ng/syslog-ng.conf
I don't know what changes Bandwidth module should create there. 
If you inform what rules should be there for SYSLOG-NG - I'll check.

So it looks like everything is running - but anyway no any data collected.
As there no much settings for this module and no a debug mode - that's difficult to say more about a potential reason.

**Comment by Sarge2013** [comment]
Hello,
it seems I found a potential reason why no data generated in 
/var/log/bandwidth
but I need some time to cross-check before posting the proven solution here.

In the meantime - let me ask - is it possible to generate a report not from Webmin Bandwidth Module GUI - but from command line ?

**Comment by jcameron** [comment]
Sorry, no .. the report is only visible in the UI.

**Comment by Sarge2013** [comment]
Thank you, understood about command line...
With UI - how to see how much traffic for incoming and outgoing ? (downloaded and uploaded)
Graphic does not give such an information
![Report1](https://user-images.githubusercontent.com/5161375/154832259-d75566fd-0470-47ee-b50c-1f9ce786d58f.png)

Instead of such a graphic - could be just a table where downloaded and uploaded volume shown as numbers ?

**Comment by jcameron** [comment]
What if we added another column for upload and download usage?

**Comment by Sarge2013** [comment]
It would be a great solution ! because this is really important to know incoming and outgoing traffic separately !

**Comment by jcameron** [comment]
Excellent - looks for this in the next Webmin release.
