### ISSUE TITLE
Unable to delete folders in File Manager

### ISSUE THREAD

**Issue by lettore** [webmin/webmin#1604]
With the latest version I'm unable to delete and copy dirs, gives as error unable to delete - is a directory.

**Comment by iliarostovtsev** [comment]
Do you have a trash enabled on File Manager configuration (to delete files safely to trash) - if you disable this option does it work then?

Does the user you're logged in with have a home dir?

**Comment by lettore** [comment]
Disabling the trash worked, thanks.

**Comment by iliarostovtsev** [comment]
Were you low on disk space or quota?

**Comment by lettore** [comment]
No, I have 500gb of free space.

Il Dom 20 Feb 2022, 22:21 Ilia ***@***.***> ha scritto:

**Comment by iliarostovtsev** [comment]
> No, I have 500gb of free space.

It would be super useful to have a remote login. You could add my public ssh-key and I could have a closer look with move to trash option enabled. If that's not possible, can you provide more details.

Most importantly what errors do you have on the browser's console and a screenshot of an error when you try to delete it?

Also, is this master login (root) or some other su-capable user?

**Comment by lettore** [comment]
This is the response trying to delete a folder with recycle bin enabled.
![image](https://user-images.githubusercontent.com/34779795/154949940-c03244ff-57a3-4120-9cd7-4b5d62a9d138.png)
I get no errors in browser console.
Cut/paste seems to works anyway.
I have this problem only on one machine of the 6 I use, this happened updating to last version.
My user is member of sudo group.

**Comment by lettore** [comment]
Yes the user have a home dir, but as I said until yesterday deleting was working fine. It's just after updating to latest version I have errors.
One of them are this one
![image](https://user-images.githubusercontent.com/34779795/154953196-7f8c8176-b448-46f9-8d89-627517e1b230.png)
It happens when I browse a Glusterfs mounted dir.

**Comment by lettore** [comment]
I have updated thorugh the web interface, I'm using the default authentic theme. Webmin 1.984
