### ISSUE TITLE
Feature request - Command Line for Bandwidth Module

### ISSUE THREAD

**Issue by Sarge2013** [webmin/webmin#1606]
Hello,
In spite of the fact Bandwidth Monitor module was created long ago - as a sysadmin I have to say the one collects and analyzes the network traffic very well.
But let me note very often for sysadmins much better to collect exact information using not GUI - but a command line.
Something like
perl /webmin/bandwidth/a_script.pl - port 80 - yesterday - incoming > a_file.txt - or to a variable what can be used in BASH scripts.
IMHO it could be very useful,
Regards
Serge

**Comment by jcameron** [comment]
You could perhaps try parsing the underlying data files that Webmin collects, which are in `/etc/webmin/bandwidth/hours`

**Comment by Sarge2013** [comment]
Yes, you're right - it's possible to write a simple script what will be parsing the records under /etc/webmin/bandwidth/hours/
But there are the questions for understanding - here is example of the records from example file /etc/webmin/bandwidth/hours/456974
255.255.255.255_UDP_1947_57010=48 0
171.224.121.130_TCP_443_9536=1296 8571
171.224.121.130_TCP_443_41058=1871 11606

It's easy to understand what a line begins from - but what are next parameters ?
IP(171.224.121.130)_Protocol(TCP)_Port(443)_?(9536)= ?(1296) ?(8571)
171.224.121.130_TCP_443_9536=1296 8571

And how to understand - is that record about INCOMING traffic or OUTGOING traffic ?
Please, inform.

**Comment by jcameron** [comment]
The _ separated fields are : 

IP , protocol, server port, client port = incoming , outgoing

The client port doesn't matter 99% of the time, since it's dynamically assigned.

**Comment by Sarge2013** [comment]
Thank you very much for explanations !
So finally, the record in file /etc/webmin/bandwidth/hours/456974
171.224.121.130_TCP_443_9536=1296 8571
means
from IP 171.224.121.130 by Protocol TCP through Port 443 (server) from a dynamic client port 9536 - incoming traffic 1296 and outgoing traffic 8571
Is that correct ?

What is unit measure here ? - incoming traffic 1296 and outgoing traffic 8571 - is that 1296/8571 Bytes ? 
Also about name of files created like /etc/webmin/bandwidth/hours/456974 - is 456974 means something ?

**Comment by Sarge2013** [comment]
Thank you for the final explanations.
IMHO it's a very specific filename to be human readable :) "number of hours since Jan 1st 1970" !
Could be added at-least an option for new configs - give old style filename "number of hours since Jan 1st 1970" or give a new style filename YYYYMMDDHH - much more easier to understand what is the file if we see filename 2022022616 !
Regards
Serge

**Comment by jcameron** [comment]
The filename isn't really meant to be human-readable .. the reason I used that time format is because Unix timestamps are normally stored as "seconds since 1st Jan 1970"

**Comment by Sarge2013** [comment]
Ah : ) understood about Unix time.
Actually you could close the issue, but I'd offer to include to next release of Bandwidth Monitor some useful (IMHO) information something like :
***
Directory storing the information by default - /etc/webmin/bandwidth/hours/ where files for module parsing arises from default log /var/log/bandwidth (both locations can be changed in Module settings).
Every line of files under /etc/webmin/bandwidth/hours contains information about traffic, for example
171.224.121.130_TCP_443_9536=1296 8571
what means
traffic from IP 171.224.121.130 by Protocol TCP through Port 443 (at your server) from a remote dynamic client port 9536 - incoming traffic 1296 Bytes and outgoing traffic 8571 Bytes
so you can write your own parsing script for your specific needs in addition to Webmin Bandwidth Monitor GUI.
*** 
Who needs - they will understood and use.
Thanks again for ll your explanations !
As to me - your Bandwidth Monitor is one of the best because collects and parses the traffic information exactly as it should be without any unnecessary "extras".
...I just regret still not solved why it does not work together with LFD (issue 1605) - but as said - this is because of a something from LFD namely - hopefully will be solved someday.
Regards,
Serge

**Comment by jcameron** [comment]
I suppose what we should really do is add a command-line API tool for dumping bandwidth stats. However, you're the first person to ever ask for this, so it's not too high on my priority list :-)

**Comment by Sarge2013** [comment]
In a reply - I suppose this is just because your Bandwidth Monitor module not well-known and undervalued.
Last two months I was doing many investigations for myself - and while all found solutions were too simple (without whole picture of traffic) - or too heavy (and also not suitable).
Just suddenly I found Bandwidth Monitor at Webmin - and I understood this is exactly the right instrument.
This module collects all necessary comprehansive information - and very laconic - in comparison with other solutions.
I do not push you :) to write a command-line API tool asap - but when ready I'd be glad to write a couple of reviews,
Regards
Serge

**Comment by Sarge2013** [comment]
To avoid a new issue - let me just inform that Webmin 1.990 (update from 1.984 through yum on Centos 7) - does not create necessary configuration at SYSLOG-NG service configuration.
/etc/syslog-ng/syslog-ng.conf
When I've added manually to this file
destination d_bandwidth {
  file("/var/log/bandwidth");
  };
filter f_bandwidth {
  facility(kern) and priority(debug);
  };
log {
  source(s_sys);
  filter(f_bandwidth);
  destination(d_bandwidth);
  };
- everything works fine. Please, check and fix this issue.

Thank you for new version and more convenient and informative UI ( although command line API in a future is still awaiting feature :) )
Regards,
Serge

**Comment by jcameron** [comment]
Did it create an incorrect syslog-ng configuration, or nothing at all?

**Comment by Sarge2013** [comment]
Nothing at all

**Comment by jcameron** [comment]
Did it add anything to another config file, like /etc/syslog.conf or /etc/rsyslog.conf ?

**Comment by Sarge2013** [comment]
I found it has added to /etc/rsyslog.conf one line in the end of file 
kern.=debug	-/var/log/bandwidth
But instead of RSYSLOG service I use SYSLOG-NG service, RSYSLOG service is disabled.
I've paid attention that previous UI version of Bandwidth has recognized SYSLOG-NG - see screenshot
![Bandwidth_State](https://user-images.githubusercontent.com/5161375/156986125-0f5ab1dc-e282-4885-9011-0329824e85c6.png)
but current version does not recognize SYSLOG-NG - see current screenshot
![image](https://user-images.githubusercontent.com/5161375/156986491-f2ee03bc-ecac-4f09-8299-a84f063bc7e0.png)

SO I SUPPOSE this is the reason why last version Bandwidth Module did not add anything to 
/etc/syslog-ng/syslog-ng.conf
but instead has added to
/etc/rsyslog.conf 

As I wrote above - when I manually add necessary config to /etc/syslog-ng/syslog-ng.conf - everything works.

**Comment by jcameron** [comment]
This may be due to the stricter check I added for syslog-NG being installed in the latest Webmin release.

If you go to the System Logs NG module, does it show syslog-ng as installed and running?

**Comment by Sarge2013** [comment]
Yes, may be...because Webmin System Logs NG module shows
![image](https://user-images.githubusercontent.com/5161375/157187371-52012724-84b6-409d-9c28-8cd7c67d7bac.png)

but actually on shell
service syslog-ng status
Active: active (running)

And when I press green button on System Logs NG module - nothing happens and button still green.
So Webmin "thinks" System Logs NG module does not running.

**Comment by jcameron** [comment]
It looks like Webmin is looking in the wrong place for the syslog-ng PID file.

Which Linux distribution and version are you running there?

**Comment by Sarge2013** [comment]
Centos 7 latest - 3.10.0-1160.53.1.el7.x86_64
PID location as I found
/usr/sbin/syslog-ng -F -p /var/run/syslogd.pid
...no more any "syslog" running besides SYSLOG-NG.

**Comment by Sarge2013** [comment]
...and sorry I have a question not relating to feature or issue at all - how to disable at start Dashboard
![image](https://user-images.githubusercontent.com/5161375/157394534-878ea1c1-2fe9-48ad-bb82-9043e2fb147f.png)
?
It's definitely not an actual information to load every time when Webmin starts...as sysadmin I know what are my network interfaces :) and disk usage anyway shown at the top of Dashboard using round graph...

**Comment by jcameron** [comment]
Ok, I see the issue - Webmin it looking for the PID file at `/run/syslogd.pid`

Try editing `/etc/webmin/syslog-ng/config` and fixing the `pid_file=` line.

**Comment by Sarge2013** [comment]
I set in
/etc/webmin/syslog-ng/config 
pid_file=/var/run/syslogd.pid
and restarted Webmin service.
OK - now Webmin System Logs NG module shows correctly
![image](https://user-images.githubusercontent.com/5161375/157616768-694eb81b-45ff-47d1-8ee7-72466b7593c6.png)
But Bandwidth Module anyway shows
Using IPtables firewall and Syslog - not Using IPtables firewall and Syslog-NG

**Comment by jcameron** [comment]
How did you install syslog-NG on CentOS 7? It doesn't appear to be one of the standard packages available in YUM.

**Comment by Sarge2013** [comment]
Hm...you have surprised me :) I've checked
yum info syslog-ng
Installed Packages
Name        : syslog-ng
Arch        : x86_64
Version     : 3.5.6
Release     : 3.el7
Size        : 1.6 M
Repo        : installed
From repo   : epel
...so nothing too special...installed from yum but from EPEL repository...
yum install syslog-ng syslog-ng-libdbi
...that's all...

**Comment by jcameron** [comment]
Ah, ok .. it's in EPEL.

I found another bug that was causing syslog-ng to not be detected correctly, which will go into the next Webmin release. You can also see the fix here : https://github.com/webmin/webmin/commit/17f79c94b2ee7cbde934792dc8683baafa783c40
