### ISSUE TITLE
Cannot activate firewall at boot

### ISSUE THREAD

**Issue by kazso** [webmin/webmin#1608]
On a fresh Ubuntu 20.04 install Webmin 1.990 throws this error, if I want to activate firewall at boot:
`Undefined subroutine &firewall::iptable_restore_command called at ./firewall-lib.pl line 319`

Looking at the files /usr/share/webmin/firewall/firewall-lib.pl and /usr/share/webmin/firewall6/firewall-lib.pl there seems to be a typo.
Line 319 reads: `local $res = &iptable_restore_command();`
But it should be: `local $res = &iptables_restore_command();`

After manually editing these firewall-lib.pl files "Activate at boot" button works under Networking/Linux Firewall and Networking/Linux IPv6 Firewall.

**Comment by iliarostovtsev** [comment]
Hello,

You are right! Thanks for finding this. We will fix this in the next Webmin release.
