### ISSUE TITLE
Error when cron tries to resign dnssec zone

### ISSUE THREAD

**Issue by mruepp** [webmin/webmin#1609]
Recently I got Errors with scheduled zone resigning of two dnssec zones:
Re-signing of [redacted](redacted) failed : Re-signing failed : dnssec-signzone: fatal: Zone contains NSEC records.  Use -u to update to NSEC3.

 Re-signing of [ruepp.at](redacted) failed : Re-signing failed : dnssec-signzone: fatal: Zone contains NSEC records.  Use -u to update to NSEC3.

This is not expected to happen and can be fatal if the zone key don't gets updated and the zone invalid especially when the zone is the one pointing to the webmin management hosts.
<img width="1062" alt="Screen Shot 2022-03-13 at 19 13 07" src="https://user-images.githubusercontent.com/10906913/158073302-b843227f-4458-4046-b6bf-a93269628cfa.png">

**Comment by jcameron** [comment]
Another user reported this bug in Webmin 1.990 - the fix is here https://github.com/webmin/webmin/commit/cef983f4f20e6375de745cfa39dece4dcc166b63 , and will be included in the next release.
