### ISSUE TITLE
postgresql (rocky linux) and others

### ISSUE THREAD

**Issue by we-sell-bags** [webmin/webmin#1615]
Generally the postgres is at:

/var/lib/pgsql/12/data/pg_hba.conf

not 
/var/lib/pgsql/data/pg_hba.conf

they have inserted a version number in the pqsql directory, to ensure migrations are in the correct place 
so the plugin is failing until reconfigured
it says the database is not initialised, perhaps better checking of the plugin to see if it found the config file and the error messages stating this , rather than database not initialised.

**Comment by jcameron** [comment]
Thanks - I'll have Webmin look for files like `/var/lib/pgsql/12/data/pg_hba.conf` in the next release.
