### ISSUE TITLE
Revert new logic for uploading files

### ISSUE THREAD

**Issue by Osiris-Team** [webmin/webmin#1616]
In the latest webmin version uploading a file does not replace the existing file with the same name anymore... Also, the properties of the file get lost, since I have to delete the old file and rename the uploaded file back to its original name.

This makes uploading files a pain...
At least add a config section to enable the old logic.

**Comment by iliajie** [comment]
This has been fixed already in the latest development version of the theme, as explained [here](https://forum.virtualmin.com/t/virtualmin-file-manager-extract-changed-and-now-it-automatically-create-a-new-folder-on-top-of-every-extract/114497/7?u=ilia) in Virtualmin Community Forum.

You can either install latest development version of the theme or simply go to **File Manager ⇾ Preferences: Advanced options** page and change an option with the name **Do not overwrite existing files upon ..** to **No**.

**Comment by Osiris-Team** [comment]
Thanks!
