### ISSUE TITLE
Replace Webalizer with GoAccess?

### ISSUE THREAD

**Issue by by** [webmin/webmin#1618]
With Webalizer gone for good, wouldn't it be a good idea to support an alternative like GoAccess (https://goaccess.io)? – Thanks!

**Comment by iliajie** [comment]
Hi,

GoAccess is a great tool for terminal use but I don't think Webalizer can be compared with GoAccess. The best replacement for Webalizer would be AWStats, which isn't going anywhere (will be installed and supported with Virtualmin 7). AWStats provides a great stats on virtual server (per domain) basis.

**Comment by jcameron** [comment]
Also, we've had a plugin for AWstats for Virtualmin available for quite a while now.

**Comment by by** [comment]
Thanks!
