### ISSUE TITLE
Webmin install frozen 

### ISSUE THREAD

**Issue by htttito** [webmin/webmin#1620]
Hi JC!
There an issue when installing webmin 1.990 with repository on ubuntu server 20.04.
The install froze. 
The only thing that works is to manually install it with ./setup.sh!

**Comment by swelljoe** [comment]
> The only thing that works is to manually install it with ./setup.sh!

Never do that.

> There an issue when installing webmin 1.990 with repository on ubuntu server 20.04.

We were seeing what we think is a DDoS against our download server today, but I thought we'd sorted it out an hour or so ago. But, if you saw the problem more recently than that, I guess we did not.

**Comment by swelljoe** [comment]
It looks fine to me, at the moment.

If you continue to have problems, you could temporarily add an entry to your hosts file to use the other download.webmin.com IP (there are two, and AFAIK 104.207.151.13 hasn't had any issues). You shouldn't make that permanent, as we may change IPs at any time, but if the alternative is doing something really dumb like installing from a tarball, you should take the less dumb path of hard-coding an IP in your hosts file for a little while.

**Comment by htttito** [comment]
Thank you!
First:
Today i try to install webmin with repository - not working: The installation froze....
Second:
I download the file webmin 1.990.deb and install it with dpkg - not working: The install froze....
I try it with 1.810, 1.9....  - not working: The install froze....
Third:
I download the webmin.tar.gz  file and install it with ./setup.sh - that's working

Is there something missing in the new ubuntu server 20.04.4 ??
This is the first time a have this issue!

**Comment by swelljoe** [comment]
Oh, that's nothing to do with our download server. Something is wrong with...I don't know what. At what point does it "freeze"? Do other package installs work?

**Comment by htttito** [comment]
it freeze always by extracting the file..
![Bildschirmfoto vom 2022-04-09 23-24-58](https://user-images.githubusercontent.com/40149753/162592109-343c0d72-177a-4e2f-bcf6-39e8c13e36a4.png)
.

**Comment by iliajie** [comment]
Perhaps, an instance went to sleep (not setup to run in background)? 🙂

**Comment by htttito** [comment]
Thank you all!
There is no Issue.
You must wait a long long time, but then all is OK.

**Comment by borgogelli** [comment]
Same problem for me. 
What's the cause ?

**Comment by chris001** [comment]
I think you must wait very long, like... about 2-3 minutes? finally, it continues and completes the install.

**Comment by jcameron** [comment]
@freeyourit which Webmin version are you installing? The OP was installing 1.990, which is pretty old..
