### ISSUE TITLE
fail2ban: display current status for jails

### ISSUE THREAD

**Issue by iliajie** [webmin/webmin#1623]
It would be cool to add another iconed-button called Jail Status to simply display status for each jail.

We could get the list of active jails with regular status command:

```
~# fail2ban-client status
root@ubuntu22-gpl:~# fail2ban-client status
Status
|- Number of jail:	6
`- Jail list:	dovecot, postfix, postfix-sasl, proftpd, sshd, webmin-auth
```

and then iterate over status for each unit to get details, like:

```
~# fail2ban-client status webmin-auth
Status for the jail: webmin-auth
|- Filter
|  |- Currently failed:	0
|  |- Total failed:	5
|  `- Journal matches:	
`- Actions
   |- Currently banned:	1
   |- Total banned:	1
   `- Banned IP list:	10.211.55.2
```

**Comment by jcameron** [comment]
That would be useful, yeah! I'll add this to my TODO list ..

**Comment by iliajie** [comment]
Let me send you PR for this. :)

**Comment by iliajie** [comment]
Jamie, there, have a look -

https://github.com/webmin/webmin/pull/1624
