### ISSUE TITLE
"New group with same name as user"  in "LDAP Users and Groups"

### ISSUE THREAD

**Issue by resposit** [webmin/webmin#1626]
Hello,

in the standard "Users and Groups" module there are two options that allow me to create the primary group automatically for a new user with same uid/gid:
> Create new group for new users?

> Assign same ID to new user and group?

In the "LDAP Users and Groups" module those options seem to be missing.
It means, every time I want to create a new LDAP user and LDAé primary group with same name and uid and gid I have to:
- first create a LDAP group xxx with a certain gid=nnn
- then create a LDAP user xxx with uid=nnn and set xxx as the primary group

Is there an easier/automatic way to accomplish that ?  Or would it be possible to extend the "LDAP Users and Groups" with those options ?

Thanks

**Comment by jcameron** [comment]
Yes, we should extend the LDAP module to support group creation at the same time as users.

That's slightly more complex, so I will update this ticket with progress.

**Comment by jcameron** [comment]
This will be fixed in the next Webmin release..
