### ISSUE TITLE
Cluster Change Passwords

### ISSUE THREAD

**Issue by AlucardGO** [webmin/webmin#1627]
![Capturar](https://user-images.githubusercontent.com/103897437/163725692-14c85445-9e3d-42d7-9afb-a22983f76bce.PNG)
I am new using Webmin, and I got this error that I can't fix. Can someone help me ? thanks!

**Comment by iliajie** [comment]
Hello,

Sorry, you're right. It [was a bug](https://github.com/webmin/webmin/commit/6b08bdc8fbd396cc4a3792945e4558928205e638).

We will fix this for upcoming Webmin 1.991.

**Comment by AlucardGO** [comment]
Ok, thx.

Obter o Outlook para Android<https://aka.ms/AAb9ysg>
________________________________
