### ISSUE TITLE
Terminal Problem

### ISSUE THREAD

**Issue by vincenzogianfelice** [webmin/webmin#1631]
Hi. when I try to open the terminal and type something, the error of bytes truncated to 0 always appears. And before this problem, if I typed, for example, htop, the error "Unable to connect the graphic interface" came out

Debian 9 (x64)
Perl 5.24

**Comment by jcameron** [comment]
Can you attached a screenshot of the terminal when this happens?

**Comment by swelljoe** [comment]
If you're talking about the popup command shell, it is not an interactive terminal. You cannot run any interactive commands in it.

**Comment by vincenzogianfelice** [comment]
![Screenshot_20220505_143412](https://user-images.githubusercontent.com/30395310/166924050-0449b58c-5928-48a3-a1c4-49fe57b6ed89.png)

**Comment by iliajie** [comment]
`htop` is interactive command. Try something like `top -b -n 1`.

**Comment by vincenzogianfelice** [comment]
and there is no possibility to have an interactive shell in webmin? type like the shellinabox program

**Comment by iliajie** [comment]
Unfortunately, we have never had time to dedicate for implementing this yet.
