### ISSUE TITLE
Feature Request: LVM2 support (raid, thin pools, etc)

### ISSUE THREAD

**Issue by luison** [webmin/webmin#1637]
Please apologize if feature request are supposed to be registered elsewhere.

We've been increasingly using LVM2 features for raids and mirroring instead of having a linux raid added as an LVM PV.
This LVM2 options add great flexibility to mirror and raid creation per logical volume and offers options like the creation of a thin-pool over a LV.

Webmin currently supports LVM2 raid units with reduced info, but does not support creating a new LV with n mirrors or converting one. This would be a great feature as there are also very few graphical interfaces for LVM2, even on graphical Linux.

https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_and_managing_logical_volumes/assembly_configure-mange-raid-configuring-and-managing-logical-volumes#proc-replacing-failed-raid-device-replacing-a-raid-device

**Comment by chris001** [comment]
https://github.com/dominikschulz/Linux-LVM2
https://metacpan.org/pod/Linux::LVM2

**Comment by jcameron** [comment]
Webmin does support LVM2 already, but not mirror or RAID volumes - normally I rely on an underlying Linux RAID volume for that. But this is an excellent feature idea .. I'll add it to the long-term TODO list.

**Comment by chris001** [comment]
https://github.com/globalcitizen/storage-graph

https://github.com/pavlozt/serverviz

**Comment by jcameron** [comment]
FYI, Webmin does support thin pools already.
