### ISSUE TITLE
RPC error : Invalid user for RPC after update to 1.993

### ISSUE THREAD

**Issue by ghost235** [webmin/webmin#1639]
Hi,
after updating to webmin 1.993 cloudmin and webmin can not connect. Im using not "root".
With webmin 1.984 all works fine.

**Comment by tengkuhaidi** [comment]
same issue

> Hi, after updating to webmin 1.993 cloudmin and webmin can not connect. Im using not "root". With webmin 1.984 all works fine.

i have same issue

**Comment by jcameron** [comment]
Apologies, this is fixed in version 1.994 which we just released.
