### ISSUE TITLE
User root broken with 1.993 update

### ISSUE THREAD

**Issue by poqdavid** [webmin/webmin#1640]
Everything was just fine and after I updated to 1.993 it broke so when I try to do things as root in the file manager it's doing things as totally a different user

**Comment by iliajie** [comment]
Can you give more details on hoe to reproduce an issue?

**Comment by poqdavid** [comment]
Oh well I just updated webmin from the web UI and I even rebooted the whole server
After the update, I went to the file manager to edit a folder owned by root and it failed.
Then I tested it by making a file in a different folder and the file and the file wasn't owned by root which it should have been

**Comment by iliajie** [comment]
What user are you logged in with? Are you logged in as `root` or as root capable _sudo_ user?

Is this a safe Webmin user or regular Webmin user?

**Comment by iliajie** [comment]
Doesn't matter. I see the bug. We will fix it in the next release as soon as possible!

**Comment by iliajie** [comment]
Upgrade to Webmin 1.994 and read [this thread](https://sourceforge.net/p/webadmin/bugs/5562/#84e2) to fix ongoing problem locally (for separate Webmin users), if needed.

It will be fully resolved in Webmin 1.995.

**Comment by poqdavid** [comment]
Awesome thank you

**Comment by iliajie** [comment]
The mentioned patch in PR is not correct.

**Comment by poqdavid** [comment]
Oh, btw after 1.994 I can edit files but not create files or folders
