### ISSUE TITLE
Error webmin in file manager

### ISSUE THREAD

**Issue by tengkuhaidi** [webmin/webmin#1642]
![image](https://user-images.githubusercontent.com/24238945/169936054-0dfa94ee-21d9-4545-b3c4-d85cec8bcc3b.png)

when I open my code after the latest webmin update, it looks like this, please fix it quickly. thank

**Comment by iliajie** [comment]
Hello,

Please upgrade to Webmin 1.994 and read [this thread](https://sourceforge.net/p/webadmin/bugs/5562/#84e2) to fix the problem locally (for separate Webmin users), if needed.
