### ISSUE TITLE
Real Time Monitoring disappeared after update to  1.993 

### ISSUE THREAD

**Issue by n-hdev** [webmin/webmin#1643]
Like the title says upgraded a couple of my servers to 1.993 and I no longer have real time monitoring displaying on the dashboard. There are also no options for it (comparing it to 1.991 on my other servers) in the theme options.

Has this feature been removed/moved?

**Comment by iliajie** [comment]
Hello,

Please upgrade to Webmin 1.994 and read [this thread](https://sourceforge.net/p/webadmin/bugs/5562/#84e2) to fix the problem locally, if needed.

**Comment by n-hdev** [comment]
Hi... Thanks, that fixed the problem!

**Comment by iliajie** [comment]
For your information, that mentioned earlier PR is incorrect and shouldn't be used on the systems with multiple users. We are working on a new implementation.

Sorry about that.

**Comment by n-hdev** [comment]
Thanks for letting me know. All of my public servers are single users so no big deal. But I'll wait for a fix on this issue before upgrading the others.

Oddly, my home Raspberry Pi upgraded without issue, though I use the root user on that, whereas I don't on my public servers, not sure if that made a difference.
