### ISSUE TITLE
.deb files incompatible with old dpkg versions, trivial fix

### ISSUE THREAD

**Issue by TomasRiker** [webmin/webmin#1650]
Today I was unable to install the following updates on my old Ubuntu (12.04):

```
webmin-virtualmin-htpasswd_3.1_all.deb
webmin-virtualmin-awstats_6.0_all.deb
```

The error message I got was:

`dpkg-deb: error: archive '/var/cache/apt/archives/webmin-virtualmin-awstats_6.0_all.deb' contains not understood data member control.tar.xz, giving up`

Seems like my old dpkg version can't handle .tar.xz.

I fixed it by unpacking the .deb file on another machine running a newer Ubuntu using `dpkg-deb -R` and re-packing it with `dpkg-deb -b -Zgzip`.

Then, I could install the modified .deb files without any problem.

So, if the `-Zgzip` switch is added during the process of building the .deb files, the problem will be gone.

**Comment by jcameron** [comment]
@swelljoe what script do you use to create these module .deb files?

**Comment by swelljoe** [comment]
Ubuntu 12.04 reached end of life over five years ago. If you don't mind using (really) old software, just keep using old software. Your Virtualmin plugin updates are the least of your worries here...you've got a whole lot of system packages that haven't been updated in five+ years, including unpatched Apache and kernel security issues.

I used the -Zgzip flag for years, but at some point it feels irresponsible to support very old distros in Virtualmin. And, also imposes a cost on everyone else (though a small cost; bigger downloads, slower installs, added up over hundreds of thousands of installs is still something).

**Comment by TomasRiker** [comment]
Ubuntu ESM (Extended Security Maintenance) offered updated packages for 12.04 for some more years. Of course I understand your point of view. I just thought that the change may have been unintended because I didn't see it documented.

**Comment by swelljoe** [comment]
I've always been emphatic that Virtualmin repos and packages only support currently maintained distros. If older distros are accidentally supported beyond the life of the OS, that's...well, an accident.

https://www.virtualmin.com/os-support/

I would consider adding a paid option for supporting distros during their paid period (e.g. ESM, and I think Red Hat has something similar for RHEL). Not sure there would be sufficient takers to justify the extra labor, though. Most folks using Virtualmin tend to want to stay at least reasonably current so they can update to newer versions of web apps and such, and stay on top of current TLS versions for PCI.

**Comment by chris001** [comment]
@TomasRiker  You've got me wondering, is there any particular reason why you've stayed on end of life Ubuntu Precise 12.04?  Because it's so easy to upgrade Ubuntu OS from the command line!

1. How to upgrade (Precise) 12.04 to (Trusty) 14.04 https://www.virtualmin.com/documentation/system/os/ubuntu-precise-to-trusty/
2. How to upgrade 14.04 to (Xenial) 16.04 https://www.virtualmin.com/documentation/system/os/ubuntu-trusty-to-xenial/
3. How to upgrade 16.04 to (Bionic) 18.04 https://forum.virtualmin.com/t/successfully-updated-ubuntu-16-04-to-18-04-on-linode/108125
4. How to upgrade 18.04 to (Focal) 20.04 https://ubuntu.com/blog/how-to-upgrade-from-ubuntu-18-04-lts-to-20-04-lts-today

**Comment by iliajie** [comment]
Where is how to upgrade to Ubuntu 22.04? 🙂

**Comment by chris001** [comment]
How to upgrade Ubuntu 20.04 to 22.04: https://www.techrepublic.com/article/how-to-upgrade-ubuntu-server-from-20-04-to-22-04/
😄

**Comment by iliajie** [comment]
I'd be surprised if eventually upgrading from 12 to 22 would work.

**Comment by TomasRiker** [comment]
> @TomasRiker You've got me wondering, is there any particular reason why you've stayed on end of life Ubuntu Precise 12.04? Because it's so easy to upgrade Ubuntu OS from the command line!

I couldn't even get the first upgrade to 14.04 done without breaking the system, unfortunately.

**Comment by chris001** [comment]
What was the breakage / error?

**Comment by TomasRiker** [comment]
I don't remember, it was some years ago. I do remember that my conclusion
was that fixing it was beyond my capabilities and that I would eventually
have to setup everything from scratch with a newer version.

Chris Coleman ***@***.***> schrieb am Do., 26. Mai 2022,
23:42:

**Comment by chris001** [comment]
In case you missed it.. Ubuntu [offers free and paid tech support service](https://ubuntu.com/advantage) and would probably do the upgrade, no problem.
Also Virtualmin would probably do the upgrade or migration job as paid tech support, just [ask in the support ticket tracker](https://www.virtualmin.com/documentation/system/support/).
