### ISSUE TITLE
Webmin default password hashing format

### ISSUE THREAD

**Issue by iliajie** [webmin/webmin#1653]
Based on my [latest PR](https://github.com/webmin/webmin/pull/1652) to support _yescrypt_, and when trying to set **Webmin password hashing format** to **Use standard Unix crypt encryption** on **Webmin ⇾ Webmin Configuration: Authentication** page doesn't seem to use _yescrypt_ on Ubuntu 22.04, while it should have.

Also, the default must not be set to MD5 in 2022. If we fix the default to work properly (like Ubuntu 22.04 use _yescrypt_ and Debian 10 use _sha512_ and etc whatever system default is there), then **Use standard Unix crypt encryption** should be a new reasonable default. :--)

**Comment by jcameron** [comment]
I think `yescrypt` is too new to make the default yet, but `sha512` seems reasonable.

**Comment by iliajie** [comment]
This is not the point. We don't care. We rely on the system. System must decide which hashing format to use.

Let's continue on [this PR](https://github.com/webmin/webmin/pull/1654).
