### ISSUE TITLE
Google Chrome Update "Scroll bug"

### ISSUE THREAD

**Issue by VitaliyIshkevychDeveloper** [webmin/webmin#1657]
Google Chrome was updated few days ago. After that, the scroll began to stop when scrolling. To continue scrolling I must move the cursor and continue scrolling. Please fix it.
PS: Microsoft Edge and Mozilla Firefox scroll is correct.

**Comment by iliajie** [comment]
Hello,

Could you please share a video-screencast or at least a screenshot?

**Comment by VitaliyIshkevychDeveloper** [comment]
When I do not move the cursor, the scroll only works for a few lines. If you move the cursor scroll will work again. If the cursor moves all the time then scrolling works well.

https://youtu.be/CWCipRv1ZLI

**Comment by VitaliyIshkevychDeveloper** [comment]
> Hello,
> 
> Could you please share a video-screencast or at least a screenshot?

When I do not move the cursor, the scroll only works for a few lines. If you move the cursor scroll will work again. If the cursor moves all the time then scrolling works well.

https://youtu.be/CWCipRv1ZLI

**Comment by iliajie** [comment]
Hi again, Vitaliy,

Look I do not see this bug happening on MacOS in latest (102) version of Chrome and development (103).

Besides, I do not think we are capable of fixing system specific issues like this.

**Comment by iliajie** [comment]
I will be fixed (by upstream CodeMirror update) in upcoming theme 19.96 release.
