### ISSUE TITLE
Refreshing system information

### ISSUE THREAD

**Issue by Slipy007** [webmin/webmin#1660]
Hi,

I can't get webmin (1.994) (Authentic theme V19.93.1) to update my new upgrade from my linux host. I rebooted the host and I know the new upgrade from the host is working but webmin won't say it on system information dash board. It still has the old system information.

I have no clue how to fix it. I've tried the refresh icon on the dash board and it doesn't update system information either. Firefox problem?

Thank you

**Comment by chris001** [comment]
What happens when you go thru the menu `Webmin > Webmin Configuration > Restart Webmin (yellow button at the bottom of the screen)` wait a few seconds, and then `Dashboard`

**Comment by Slipy007** [comment]
Same issue

**Comment by chris001** [comment]
What do you mean when you say, "to update my new upgrade from my linux host" ??
"I know the new upgrade from the host is working"??  How do you know that??
What are you trying to upgrade... Webmin?  Packages for your linux distro?  
Which linux distro and version are you using??

**Comment by Slipy007** [comment]
> What do you mean when you say, "to update my new upgrade from my linux host" ?? "I know the new upgrade from the host is working"?? How do you know that?? What are you trying to upgrade... Webmin? Packages for your linux distro? Which linux distro and version are you using??

How do I know because I asked them.... 

Ubuntu Linux 20.04.4
All I want is to have webmin update system information from the linux host.
