### ISSUE TITLE
Use fail2ban.local instead of fail2ban.conf

### ISSUE THREAD

**Issue by alanmels** [webmin/webmin#1661]
If you click on the config editor at Webmin > Networking > Fail2Ban Intrusion Detector > Edit Config files, then it automatically opens the `/etc/fail2ban/fail2ban.conf` for editing. However, the official documentation on https://www.fail2ban.org/wiki/index.php/HOWTO_fail2ban_0.7.x suggests creating a `fail2ban.conf` to override settings in `fail2ban.conf`. Is that right? Maybe Webmin should copy `fail2ban.conf` to `fail2ban.local` and offer that one for editing instead?

**Comment by Chaots** [comment]
It would be good if this change is made. It would make updating fail2ban better as there is no more need tonrevert / manually update files.

**Comment by iliajie** [comment]
Hello,

We already write custom config to the `fail2ban/fail2ban.local` file when you edit **Global Configuration**, using the module using UI.

I have checked in a fix to always display `fail2ban.local` file, even if empty and show it first in a list.
