### ISSUE TITLE
repology.org | Problems in Wikidata

### ISSUE THREAD

**Issue by Ricky-Tigg** [webmin/webmin#1663]
Hello. In its current configuration, [Repology](https://repology.org/), an on-line service aimed to be a packaging hub, gets its information associated to packages from a unique source – [Wikidata](https://www.wikidata.org). Thus that very dependency makes it unreliable, as the information it gathers can at best be as in-accurate as the one that is present in that source. As a consequence, are present there package versions having been **assigned wrong label colour codes**.

_legend | label colour codes involved in issue_

![repology org_label_colour_codes](https://user-images.githubusercontent.com/26058215/172784115-ccb46888-2310-4961-8fb8-37b212475e91.png)

The component _webmin_ currently [illustrates](https://repology.org/projects/?search=webmin) that case. Components whose definitions are erroneous are [reported](https://repology.org/repository/wikidata/problems).Its maintenance takes place at [page](https://www.wikidata.org/wiki/Q576322).

**Comment by swelljoe** [comment]
Can you clarify what is wrong and what it has to do with us? (The Webmin package shows the current version as 1.994, which is correct.)

**Comment by Ricky-Tigg** [comment]
My fault!; I had read it as _1.984_. So there is only "_Homepage link http://www.webmin.com/ is a permanent redirect to its HTTPS counterpart https://www.webmin.com/ and should be updated._" that remained valid.



"
