### ISSUE TITLE
No more stats history graphs?

### ISSUE THREAD

**Issue by sv3t0sl4v** [webmin/webmin#1665]
Wait? Where did the stats history graphs of CPU, Memory, Processes, Disk and  Network IO go since last update 1.994? How do I bring them back up? If not possible, what are the alternatives? It was very useful. I don't find it in theme settings anymore, either.

**Comment by iliajie** [comment]
Dupe - https://github.com/webmin/authentic-theme/issues/1600#issuecomment-1152426820

**Comment by kolshix** [comment]
in left menu  (bottom place) -> buttons with icon , select "theme setting"  -> There you will find the "restore default" button.
