### ISSUE TITLE
Webmin default hashing format must not be `md5` rather system default

### ISSUE THREAD

**Issue by iliajie** [webmin/webmin#1666]
Jamie, nearly forgotten. As we now have a facility to use system hashing format in Webmin as well, it would be very important to change `md5pass` to `0` (Use standard Unix `crypt` encryption) to be set by default.

The problem is that by default **_right now_** it's set to `1` which is `md5` and this is very bad.

I am talking about this option to be changed by default:
<img width="1181" alt="image" src="https://user-images.githubusercontent.com/4426533/173713723-f85fb76e-c0bf-421e-89ce-558b94ae39a8.png">

Webmin ACL module and `webmin passwd` command are both supporting it just fine.

**Comment by jcameron** [comment]
If we switch to `crypt` format, will use actually use the system default, or fall back to DES crypt which is even less secure? I guess that depends on what random salt we pass to `crypt` ..

**Comment by iliajie** [comment]
Please, just let me send you a PR for a review.

**Comment by iliajie** [comment]
Solved in this PR https://github.com/webmin/webmin/pull/1669. Testings took a lot of time.

**Comment by jcameron** [comment]
Ok, I've added a bunch of comments to that PR.

**Comment by iliajie** [comment]
Replied and fix all.
