### ISSUE TITLE
Terminal not working properly:TERM variable unset

### ISSUE THREAD

**Issue by freebrowser1** [webmin/webmin#1684]
When starting a terminal in Webmin, not all commands work properly. I tried to run [Midnight Commander](https://github.com/MidnightCommander/mc) but it says TERM is not set, even after I explicitly set TERM. MC is indeed a rather advanced terminal app, but in any normal SSH terminal it does work. And even in the web terminal of another web admin app [Cockpit](https://github.com/cockpit-project/cockpit).

See this example.

```
root@raspberry-pi ~]# mc
The TERM environment variable is unset!
[root@raspberry-pi ~]# export TERM=xterm-256color && mc 
Cannot establish connection to the host.
[root@raspberry-pi ~]# export TERM=xterm-256color
[root@raspberry-pi ~]# mc
The TERM environment variable is unset!

[root@raspberry-pi ~]#
```
This occurs not only on Raspberry Pi server but on any server.

**Comment by swelljoe** [comment]
It is not an interactive terminal.

It is a shell that can run non-interactive commands. It's basically a simple wrapper around the Command Shell module (which is also not an interactive terminal).
