### ISSUE TITLE
Mount NFS "Force NFS Version" not respected in mount commands

### ISSUE THREAD

**Issue by ShawnSack** [webmin/webmin#1688]
Running Ubuntu 22.04
Webmin 1.997
Browse to Disk and Network Filesystems
Select Type: Network Filesystem (nfs)
Define a remote export and select "4" under Force NFS version
Click Save
At this point the page will hang and timeout 5 minutes later because my remote export doesn't support 4.2. Reviewing proc reveals that the mount commands executed by webmin/mount/save_mount.cgi and not including the forced NFS version. 

```
sh -c (mount -t nfs host\.example\.com\:\/Amazon \/tmp\/\.webmin\/225240_23819_1_save_mount\.cgi) 2>&1
mount -t nfs host.example.com:/Amazon /tmp/.webmin/225240_23819_1_save_mount.cgi
/sbin/mount.nfs host.example.com:/Amazon /tmp/.webmin/225240_23819_1_save_mount.cgi -o rw
```
![image](https://user-images.githubusercontent.com/16391875/179325692-aa69acbc-ec3f-42b9-86ce-1205ef198b18.png)

I would expect "-o mountvers=4" to be appended to command

**Comment by jcameron** [comment]
The bug here is that Webmin tries a test mount to validate the NFS path before doing the real mount, but this doesn't get the NFS version flag properly. We'll fix this in the next release ..
