### ISSUE TITLE
Enabling git prevents apache2 from starting

### ISSUE THREAD

**Issue by janderk2** [webmin/webmin#1689]
Testing the beta install on Debian 11.

When enabling git for a domain or importing a domain with git, apache2 won’t (re)start.
```
Jul 12 12:02:54 cloud11.website.com apachectl[11746]: AH00526: Syntax error on line 46 of /etc/apache2/sites-enabled/website.com.conf:
Jul 12 12:02:54 cloud11.website.com apachectl[11746]: Invalid command 'DAV', perhaps misspelled or defined by a module not included in the se>
Jul 12 12:02:54 cloud11.website.com apachectl[11743]: Action 'start' failed.
Jul 12 12:02:54 cloud11.website.com apachectl[11743]: The Apache error log may have more information.
Jul 12 12:02:54 cloud11.website.com systemd[1]: apache2.service: Control process exited, code=exited, status=1/FAILURE
```
The problem is that enabling git adds DAV to the apache config file:
`DAV on
`
Which causes the error at apache2 startup, because mod_dav and mod_dav_fs are not enabled by default.

I understood that DAV is no longer supported. If that is the case enabling git should also no longer add DAV lines to the config files. And git should only be supported through ssh and no longer through DAV. Which also means the git example commands shown should be updated as they right now tell users how to use git through DAV.

**Comment by swelljoe** [comment]
I assume you're talking about the virtualmin-git module (https://github.com/virtualmin/virtualmin-git)?

**Comment by janderk2** [comment]
Guess so. I followed the instructions here: https://www.virtualmin.com/documentation/web/git/
which told me to install `apt-get install webmin-virtualmin-git` on Debian.

Is that the same?

**Comment by janderk2** [comment]
If I read this correctly the DAV directive is added to apache config [here](https://github.com/virtualmin/virtualmin-git/blob/master/virtual_feature.pl#L231).

It looks like there is a [check for mod_rewrite](https://github.com/virtualmin/virtualmin-git/blob/master/virtual_feature.pl#L224). If there is another for mod_dav and mod_davfs then at least apache2 will restart.

**Comment by janderk2** [comment]
I will repost this bug report on the https://github.com/virtualmin/virtualmin-git section.
