### ISSUE TITLE
Support for degree fahrenheit

### ISSUE THREAD

**Issue by Morketh** [webmin/webmin#169]
digging through the code i changed about 4 lines to switch over to Farenheit to display the CPU temperatures on the system information page
system-status/system-status-lib.pl 411 --> sensors -f
status/sensors-monitor.pl 71 --> sensors -f
gray-theme/right.cgi 110 and 89 --> &#8457;
would it be possible to add these changes to an option in the webmin configuration page? id be willing to code them myself given some pointers on where to go for that configuration page and then make a pull-request

**Comment by shoulders** [comment]
this should be closed because

- no-one uses fahrenheit 😄 , all technology uses Centigrade
- If this feature was going to be added it would of been done by now.
- it can always be re-requested.

**Comment by iliajie** [comment]
We already have it configurable in "Webmin ⇾ Webmin Configuration: Background Status Collection" page.
