### ISSUE TITLE
Samba - Follow symlinks not working

### ISSUE THREAD

**Issue by rw-donaldp** [webmin/webmin#1695]
Despite having "Allow symlinks outside share?" set., Windows clients could not access symlinked directories.
Not sure why but I found a fairly old thread that had a solution that worked:

To get the symlinks to work I had to add the following to /etc/samba/smb.conf

follow symlinks = yes
wide links = yes
unix extensions = no

See: https://superuser.com/questions/128716/ubuntu-latest-samba-version-symlinks-no-longer-work-on-share-mounted-in-windo

OS - Ubuntu 20.04

**Comment by jcameron** [comment]
Yeah, this lines up with what the Samba docs say for links outside the share.

I will add support for the "unix extensions" option in the next Webmin release.

**Comment by tigerblue77** [comment]
Can be close I think ?

**Comment by jeastberg** [comment]
After months of trying to get the latest Ubuntu Samba symlinks to work, I abandoned what used to work for years on an older version of Samba.  I found unionfs to do what I needed and is probably more secure.  Don't waste any more time on samba symlinks.  You're welcome. :-)
