### ISSUE TITLE
The website webmin.com seems to be down

### ISSUE THREAD

**Issue by clst** [webmin/webmin#1699]
Does this also affect the display of updated versions?  
I don't get the notification in the UI that's usually there.

**Comment by swelljoe** [comment]
It would only affect showing available updates if you didn't use the apt or yum repo (which you obviously should do). The apt/yum repo runs on a different server from Webmin.com, and that server is up.  I don't have any access to webmin.com, so I can't do anything about it, but Jamie will be awake in an hour or three.

**Comment by clst** [comment]
Ah I see, thanks for the quick reply...  
Yes this server does not have a traditional package manger. Let's hope it's nothing serious.

**Comment by clst** [comment]
The website is back up.

**Comment by chris001** [comment]
Not the first time the webmin site has gone down.  Uptime is not as high as it should be.

Easy and free tool to improve webmin site uptime:  

Activate cloudflare as the front end for the webmin website.

Why this helps?  When the webmin site is down, cloudflare will return a cached copy of all static pages, until the webmin site is up again.

Way better look than letting users get a 404 or 503!

**Comment by unknown10777** [comment]
I got an idea about this.
the website seems to be an static page that doesn't contains javascript, so create a Github pages to store HTMLs and PNGs may be an free and easy way.
