### ISSUE TITLE
Undefined subroutine &main::get_miniserv_config

### ISSUE THREAD

**Issue by ianh999** [webmin/webmin#1703]
Issue on Rocky Linux 9 which says 

ERROR - PERL EXECUTION FAILED

Undefined subroutine &main::get_miniserv_config called at /usr/libexec/webmin/authentic-theme/session_login.cgi line 15.

I tried restarting, earlier versions that will load on Rocky Linux 9

I also tried ssh in as root then run /etc/webmin/restart-by-force-kill

Unfortunately no success

No urgency, it's a new build using Rocky 9 and not production

Thanks for your efforts

**Comment by iliajie** [comment]
What is Webmin version that you had installed on your Rocky 9?

What is the output of:

```
cat  /usr/libexec/webmin/authentic-theme/session_login.cgi  | grep get_miniserv_config -A5 -B5
```

.. and:

```
webmin -v
```

.. and:

```
webmin --versions
```

**Comment by iliajie** [comment]
Also, is this a clean install or an upgrade? If it's an upgrade which version did you have installed before upgrading?

**Comment by iliajie** [comment]
Moreover, can you please attach `/etc/webmin/miniserv.conf` and `/etc/webmin/config` files.

**Comment by ianh999** [comment]
> 
Clean install of Rocky 9 (I've installed 2x VMs both behave the same, Rocky 9 downloaded yesterday)

Its a clean install of 1.996
and I've tried versions back to 1.95

**Comment by ianh999** [comment]
> Moreover, can you please attach `/etc/webmin/miniserv.conf` and `/etc/webmin/config` files.
[config.txt](https://github.com/webmin/webmin/files/9227776/config.txt)
[miniserv.conf.txt](https://github.com/webmin/webmin/files/9227777/miniserv.conf.txt)

**Comment by ianh999** [comment]
> cat  /usr/libexec/webmin/authentic-theme/session_login.cgi  | grep get_miniserv_config -A5 -B5

[root@melvit1126 webmin]# cat  /usr/libexec/webmin/authentic-theme/session_login.cgi  | grep get_miniserv_config -A5 -B5
our (%in, %gconfig, %tconfig, %text, $config_directory, $current_theme, %theme_text);

do("$ENV{'THEME_ROOT'}/authentic-lib.pl");

my %miniserv;
get_miniserv_config(\%miniserv);
load_theme_library();

my $charset = &get_charset();

# Check to add error handler
[root@melvit1126 webmin]# 

********

[root@melvit1126 webmin]# webmin -v
1.995

*********

[root@melvit1126 webmin]# webmin -versions
Webmin: 1.995 [/usr/libexec/webmin]
  Themes: 
    Authentic Theme: 19.95.2 [authentic-theme]

**Comment by ianh999** [comment]
> > 
> 
> Clean install of Rocky 9 (I've installed 2x VMs both behave the same, Rocky 9 downloaded yesterday)
> 
> Its a clean install of Webmin 1.995 and I've tried Webmin versions back to 1.95

The second system is running 1.998, same issue... could it be something unexpected in the Rocky 8 system

**Comment by ianh999** [comment]
Solved by - yum install perl

**Comment by iliajie** [comment]
> Solved by - yum install perl

This is very interesting solution.

Although, thanks anyway! I will check Rocky over again with another clean install, and see which dependencies can be added to make sure all Perl package are getting installed on _rpm_ based systems for Webmin to work correctly. The latest versions of RHEL systems stopped installing as a standard Perl dependency, such fundamental modules as `perl-lib`, `perl-File-Basename` and `perl-open` ..

**Comment by iliajie** [comment]
We will update list of dependencies for Webmin starting with 1.999.

https://github.com/webmin/webmin/commit/d1d958bd6e4a3810f9f848dcbb4172bda4c69dff

**Comment by ianh999** [comment]
> > Solved by - yum install perl
> 
> This is very interesting solution.
> 
> Although, thanks anyway! I will check Rocky over again with another clean install, and see which dependencies can be added to make sure all Perl package are getting installed on _rpm_ based systems for Webmin to work correctly. The latest versions of RHEL systems stopped installing as a standard Perl dependency, such fundamental modules as `perl-lib`, `perl-File-Basename` and `perl-open` ..

Thank you for your enthusiastic support
