### ISSUE TITLE
Webmin not accepting interfaces with a dash ( - ) in the device / name field.

### ISSUE THREAD

**Issue by Chaots** [webmin/webmin#1705]
Webmin version 1.994
Usermin version 1.840
Virtualmin version 7.1  
Authentic theme version 19.93.1
OS CentOS 7 Latest

- To reproduce, create an interface ( the type does not matter ) and use a - in the device / name as the example bridge below.
- Activate and verify the the interface is up with ifup / nmcli.
- Navigate to Webmin -> Networking -> Network configuration -> Network interfaces.

The result is Webmin not showing the device in the list of  the tab: "Activated on boot". It will list it on the "Active now" tab, though making changes from there randomly leads to corrupted network configurations.

example with an empty bridge file /etc/sysconfig/network-scripts/ifcfg-br-wan
```
NAME=br-wan
DEVICE=br-wan
ONBOOT=yes
BOOTPROTO=none
TYPE=Bridge
IPV4_FAILURE_FATAL=no
IPV6_FAILURE_FATAL=no
UUID=400bc7d9-0b6e-4b28-a7f6-e51bac33310e
ZONE=public
IPV6INIT=no
IPV6_ADDR_GEN_MODE=stable-privacy
IPV6_AUTOCONF=no
IPV6_DEFROUTE=no
```

**Comment by jcameron** [comment]
Thanks for pointing this out - we'll fix this in the next Webmin release.
