### ISSUE TITLE
Request a button can jump to release logs (show what new juicy things has been added in new version and history versions)

### ISSUE THREAD

**Issue by unknown10777** [webmin/webmin#1707]
The reason I want this button is I don't really like update things unless it fixed CVEs or other bugs.
![image](https://user-images.githubusercontent.com/83267603/182039530-a9d84b28-d271-41b5-aaec-5612af48c8bb.png)
![image](https://user-images.githubusercontent.com/83267603/182039587-48fa96d9-871f-489b-a6a0-3fb3b99af7a4.png)

**Comment by unknown10777** [comment]
Well... forge the function in "update webmin" page is a possible idea like this
![image](https://user-images.githubusercontent.com/83267603/182040070-d287e036-3d4f-4954-9537-33bf889f5745.png)
"Before updating Webmin, You should read the release logs to avoid any issues."
"release logs"
"Confirm" "Return"

**Comment by jcameron** [comment]
Good idea, I'll add this to the upgrade UI.
