### ISSUE TITLE
CPU temp not showing for AMD Ryzen on MSI B550 Tomahawk MB

### ISSUE THREAD

**Issue by coderexpress** [webmin/webmin#1714]
CPU Temps not showing on MSI B550, with Ryzen 5600
sensors cmd output:

k10temp-pci-00c3
Adapter: PCI adapter
Tctl: +27.0 C
Tccd1: +23.8 C

nvme-pci-0100
Adapter: PCI adapter
Composite: +24.9 C (low = -273.1 C, high = +84.8 C)
(crit = +89.8 C)

nct6687-isa-0a20
Adapter: ISA adapter
VIN0: 1.01 V (min = +0.00 V, max = +0.00 V)
VIN1: 1.02 V (min = +0.00 V, max = +0.00 V)
VIN2: 976.00 mV (min = +0.00 V, max = +0.00 V)
VIN3: 592.00 mV (min = +0.00 V, max = +0.00 V)
VIN4: 944.00 mV (min = +0.00 V, max = +0.00 V)
VIN5: 1.04 V (min = +0.00 V, max = +0.00 V)
VIN6: 896.00 mV (min = +0.00 V, max = +0.00 V)
VIN7: 1.55 V (min = +0.00 V, max = +0.00 V)
VCC: 3.34 V (min = +0.00 V, max = +0.00 V)
VTT: 1.84 V (min = +0.00 V, max = +0.00 V)
fan1: 789 RPM (min = 0 RPM)
fan2: 0 RPM (min = 0 RPM)
fan3: 0 RPM (min = 0 RPM)
fan4: 1534 RPM (min = 0 RPM)
fan5: 0 RPM (min = 0 RPM)
fan6: 0 RPM (min = 0 RPM)
fan7: 0 RPM (min = 0 RPM)
fan8: 0 RPM (min = 0 RPM)
fan9: 0 RPM (min = 0 RPM)
fan10: 0 RPM (min = 0 RPM)
AMD TSI Addr 98h: +27.0 C (low = +0.0 C)
(high = +0.0 C, hyst = +0.0 C)
(crit = +0.0 C) sensor = AMD AMDSI
Diode 0 (curr): +28.5 C (low = +0.0 C)
(high = +0.0 C, hyst = +0.0 C)
(crit = +0.0 C) sensor = thermal diode
Thermistor 15: +25.0 C (low = +0.0 C)
(high = +0.0 C, hyst = +0.0 C)
(crit = +0.0 C) sensor = thermistor
Thermistor 1: +32.0 C (low = +0.0 C)
(high = +0.0 C, hyst = +0.0 C)
(crit = +0.0 C) sensor = thermistor
Thermistor 16: +24.5 C (low = +0.0 C)
(high = +0.0 C, hyst = +0.0 C)
(crit = +0.0 C) sensor = thermistor
Thermistor 0: +23.5 C (low = +0.0 C)
(high = +0.0 C, hyst = +0.0 C)
(crit = +0.0 C) sensor = thermistor
Thermistor 15: +25.0 C (low = +0.0 C)
(high = +120.0 C, hyst = +33.0 C)
(crit = +0.0 C) sensor = thermistor
intrusion0: ALARM
beep_enable: disabled

the motherboard uses this kernel module nct6683 to access the motherboard sensors.

Thank you in advance

**Comment by iliajie** [comment]
> Composite: +24.9 C (low = -273.1 C, high = +84.8 C)

-273.1 C .. are you on space station?

> CPU Temps not showing on MSI B550, with Ryzen 5600
> > sensors cmd output:

Thanks for the heads up. It will be fixed on the next Webmin release.

**Comment by coderexpress** [comment]
> > Composite: +24.9 C (low = -273.1 C, high = +84.8 C)
> 
> -273.1 C .. are you on a space station?
> 
> > CPU Temps not showing on MSI B550, with Ryzen 5600
> > > sensors cmd output:
> 
> Thanks for the heads up. It will be fixed on the next Webmin release.

thank you so much
I have the server under the house, winter here in oz,
I think these are reference temps that can be picked up lows and highs.
Awesome work!
