### ISSUE TITLE
Anyone able to install 1.999-2 deb package on Linux Mint 21?

### ISSUE THREAD

**Issue by gderf** [webmin/webmin#1717]
Install reports:

grep: /etc/webmin/miniserv.conf: No such file or directory

And running service webmin start gives:

Failed to start webmin.service: Unit webmin.service not found.

**Comment by iliajie** [comment]
Hello,

How exactly did you install Webmin?

**Comment by iliajie** [comment]
Also, what is the output of the following commands:

```
cat /etc/os-release
```

and

```
cat /etc/lsb-release
```

**Comment by gderf** [comment]
This was an upgrade from Linux Mint 20 to Linux Mint 21 which apparently caused Webmin to be uninstalled in the process. I then re-enabled the webmin Debian repo and did:

apt-get update
apt-get install webmin

But the install completed as in my original post. Furthermore, downloading the deb package and installing using dpkg has the same result.

Per request:

fred@telescope ~ $ cat /etc/os-release
NAME="Linux Mint"
VERSION="21 (Vanessa)"
ID=linuxmint
ID_LIKE="ubuntu debian"
PRETTY_NAME="Linux Mint 21"
VERSION_ID="21"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.linuxmint.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=vanessa
UBUNTU_CODENAME=jammy
fred@telescope ~ $ cat /etc/lsb-release
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=21
DISTRIB_CODENAME=vanessa
DISTRIB_DESCRIPTION="Linux Mint 21 Vanessa"
fred@telescope ~ $ 

I have seen a report or two elsewhere that installing the tarball works.

**Comment by iliajie** [comment]
Thanks for the provided details. We will have a closer look.

What is the output of:

```
find / -name miniserv.conf
```

and

```
find / -name webmin
```

**Comment by gderf** [comment]
root@telescope:/home/fred# **find / -name miniserv.con**f
root@telescope:/home/fred#

root@telescope:/home/fred# **find / -name webmin**
/var/webmin
/usr/share/doc/webmin
/usr/share/webmin
/usr/share/webmin/gray-theme/webmin
/usr/share/webmin/authentic-theme/images/modules/webmin
/usr/share/webmin/authentic-theme/images/favicons/webmin
/usr/share/webmin/webmin
/usr/share/webmin/bin/webmin
/usr/bin/webmin
/etc/webmin
/etc/pam.d/webmin
root@telescope:/home/fred#

**Comment by iliajie** [comment]
Can you install earlier versions of Webmin, i.e. `webmin=1.994`?

**Comment by waltkelly** [comment]
I had same problem. The install of Linux Mint 21 was a completely fresh install from mint live usb media. It failed when the install tried to start the webmin service, and there was at that point, nothing installed to /etc/webmin except the file "uninstall.sh". I think the reason most upgrades to Mint 21 succeed,  is that the /etc/webmin directory contains a miniserv.conf (and possibly other needed files) from the old Linux Mint 20 system.

I got webmin 1.999 to work by using an rsync copy of everything webmin related from another machine, and starting the service manually. This was mostly successful, but the system status module failed. So I did "apt reinstall webmin", which now was successful due to the populated /etc/webmin, and I have a working webmin on Mint 21.

I hope this helps.

**Comment by gderf** [comment]
> Can you install earlier versions of Webmin, i.e. `webmin=1.994`?

Fails.

fred@telescope ~/Downloads $ **sudo dpkg -i webmin_1.994_all.deb**
[sudo] password for fred:        
Selecting previously unselected package webmin.
(Reading database ... 375092 files and directories currently installed.)
Preparing to unpack webmin_1.994_all.deb ...
Unpacking webmin (1.994) ...
Setting up webmin (1.994) ...
W: Webmin server cannot be restarted. It is advised to restart it manually by
running "/etc/webmin/restart-by-force-kill" when upgrade process is finished
grep: /etc/webmin/miniserv.conf: No such file or directory
fred@telescope ~/Downloads $ sudo /etc/webmin/restart-by-force-kill
sudo: /etc/webmin/restart-by-force-kill: command not found
fred@telescope ~/Downloads $

**Comment by gderf** [comment]
> I had same problem. The install of Linux Mint 21 was a completely fresh install from mint live usb media. It failed when the install tried to start the webmin service, and there was at that point, nothing installed to /etc/webmin except the file "uninstall.sh". I think the reason most upgrades to Mint 21 succeed, is that the /etc/webmin directory contains a miniserv.conf (and possibly other needed files) from the old Linux Mint 20 system.
> 
> I got webmin 1.999 to work by using an rsync copy of everything webmin related from another machine, and starting the service manually. This was mostly successful, but the system status module failed. So I did "apt reinstall webmin", which now was successful due to the populated /etc/webmin, and I have a working webmin on Mint 21.
> 
> I hope this helps.

Thanks for the tip. I followed it and it worked.

**Comment by iliajie** [comment]
Alright, thanks for the heads up. We will add support for latest versions of Mint Linux.
