### ISSUE TITLE
Linux Mint 21 Vanessa webmin Failed to detect operating system

### ISSUE THREAD

**Issue by tudo75** [webmin/webmin#1720]
I tried to install latest webmin and get this error 

```
***********************************************************************
        Welcome to the Webmin setup script, version 1.999
***********************************************************************
Webmin is a web-based interface that allows Unix-like operating
systems and common Unix services to be easily administered.

Installing Webmin in /usr/share/webmin

***********************************************************************
Webmin uses separate directories for configuration files and log files.
Unless you want to run multiple versions of Webmin at the same time
you can just accept the defaults.

Config file directory [/etc/webmin]: Log file directory [/var/webmin]: 
***********************************************************************
Webmin is written entirely in Perl. Please enter the full path to the
Perl 5 interpreter on your system.


Testing Perl ..
.. done

***********************************************************************
Failed to detect operating system
Webmin install complete. You can now login to http://SIGMUNDX:/
as root with your root password, or as any user who can use sudo
to run commands as root.
```

**Comment by jcameron** [comment]
@iliaross will the 2.000 version of Webmin support Linux Mint 21?

**Comment by chris001** [comment]
Even if it says it fails to detect OS, does it let you log in when you browse to `https://IP.address.of.server:10000` ?

**Comment by iliaross** [comment]
> @iliaross will the 2.000 version of Webmin support Linux Mint 21?
> 

Yes, Mint Linux support will be fixed with Webmin 2.000 release.

**Comment by iliajie** [comment]
> Even if it says it fails to detect OS, does it let you log in when you browse to `https://IP.address.of.server:10000` ?

I don't think it would even start, as there was no `miniserv.conf` file.

**Comment by tudo75** [comment]
> I don't think it would even start, as there was no `miniserv.conf` file.

Right!

```
$ webmin
Failed to open /etc/webmin/miniserv.conf
```

**Comment by iliajie** [comment]
You can try installing a [devel build](https://ilia.engineer/webmin-latest.noarch.rpm) and let me know if that works for you.

**Comment by tudo75** [comment]
Your link point to an rpm build, but Mint use deb packages

**Comment by tudo75** [comment]
Tried the installer script and it seemed to work. Webmin start and I can login to web interface

**Comment by iliajie** [comment]
You're right. Sorry. Check this [link](https://ilia.engineer/webmin_latest_all.deb) out please.

**Comment by tudo75** [comment]
Uninstalled previous an tried your dev build. 
Webmin start and I can login with my user account. 
All seems to work.

Thank you for your work!

**Comment by iliajie** [comment]
Glad to hear it worked! Thanks for your feedback.
