### ISSUE TITLE
The PWA name is incorrect（the hostname was I installed webmin at the first time (1) ）, not the newest one(2).

### ISSUE THREAD

**Issue by unknown10777** [webmin/webmin#1728]
![image](https://user-images.githubusercontent.com/83267603/187052785-d4033627-ad97-428b-8bbc-0c3c6e523156.png)
I tried to lookup "Webmin on" in source code and got nothing about it.

**Comment by chris001** [comment]
1. Click the menu (three lines). 
2. Click, "Webmin", "Networking", "Network Configuration", "Hostname".  
3. Edit the hostname, type your newest hostname.  
4. Click "Save".  Click "Apply configuration".

Comment with your results!

**Comment by unknown10777** [comment]
![image](https://user-images.githubusercontent.com/83267603/187083163-70406b9f-72a7-45c6-8704-92469486986c.png)
sorry but as you can see, there's no hostname configurations in network configuration. The hostname (2) is correct but hostname (1) is an old one. I want to change the old one(1) into the new one(2).

**Comment by chris001** [comment]
That's not the screen.  
Go to the "Network configuration" screen..
Then click "Hostname and DNS client".  
Set the hostname.
Click "Save", 
Click "Apply configuration".

![webmin network config hostname](https://user-images.githubusercontent.com/259416/187083869-980ec8a3-6bd6-480f-ae14-90e021eb15b7.png)

**Comment by unknown10777** [comment]
![image](https://user-images.githubusercontent.com/83267603/187085754-66b712b0-1cfd-4f49-b093-a67ef58a1ca4.png)
I see. it didn't change.

**Comment by unknown10777** [comment]
I think we didn't get the point. I mean the PWA which is Progressive Web Apps.

**Comment by chris001** [comment]
1. When you go to terminal, what's the output of the command `hostname` ?
2. What's the output of  the command `cat /etc/hosts` ?
3. What is your hosting server type: OpenVZ, KVM, physical server, other?
4. What's your hosting company customer facing server management panel software: cpanel, whm, solusvm, virtualizor, other ?

**Comment by unknown10777** [comment]
![image](https://user-images.githubusercontent.com/83267603/187087383-8bdbd2ef-a530-49fe-b118-be90a0c2cea6.png)
it's desktop x86.

**Comment by chris001** [comment]
`cat /etc/hostname`, and edit if not correct.  
Then `sudo reboot` to apply changes,

**Comment by unknown10777** [comment]
![image](https://user-images.githubusercontent.com/83267603/187088663-0e985597-0beb-401c-8309-5bc25eb2fff0.png)
I think we are thinking two different things.
The hostname at PWA (this application title) is incorrect.
The hostname at webmin, zsh and hostname(Sumeru.lan) is correct.
I want to change the PWA's hostname which is on the title(JichengKaliNas.lan).

**Comment by chris001** [comment]
1. Did you `sudo reboot` ? You should.
2. You can disable the hostname at the top of the browser: "By default every page in Webmin shows your system's hostname and operating system in the browser status bar. To have it shown elsewhere or turn it off altogether, select one of the following options from the Display login and hostname menu : *At bottom of browser *The information is shown in the browser's status area, which is usually at the bottom of the window. *In browser title *The information is added to the title of each page, which usually appears in the browser window title. *Above page heading *The information is shown above the title of each page. *Nowhere *The hostname and operating system information is not shown anywhere. If you are worried about un-trusted users learning too much about your system, this is the option to choose."

**Comment by iliajie** [comment]
The tile that is displayed on the UI side can be configured on the theme configuration at `Theme Configuration: General defaults` and `Webmin ⇾ Webmin Configuration: User Interface` pages.

**Comment by unknown10777** [comment]
Thanks. It worked when I changed the UI settings.
