### ISSUE TITLE
nginx module error

### ISSUE THREAD

**Issue by b0blee** [webmin/webmin#1732]
The nginx server module will not load. The error messages is:

Unescaped left brace in regex is illegal here in regex; marked by <-- HERE in m/server { <-- HERE $/ at ./nginx-lib.pl line 199. Compilation failed in require at /usr/share/webmin/nginx/index.cgi line 6.

**Comment by iliajie** [comment]
Hello,

We do not support this version of the Nginx module. Sorry.

The supported module (by us) is Virtualmin Nginx module but it requires Virtualmin module to be installed <sup>[1](https://www.virtualmin.com/download/)</sup> <sup>[2](https://www.virtualmin.com/os-support/)</sup>.
