### ISSUE TITLE
Feature request: System and Server Status module Report status to web endpoint

### ISSUE THREAD

**Issue by TheSpanner** [webmin/webmin#1733]
The System and Server Status module can only send reports to email.
It would be great if we could send the report as a POST to a web endpoint

![image](https://user-images.githubusercontent.com/18556096/188326362-40a7f82e-a9b6-4623-b455-cb46ec466eaf.png)

**Comment by chris001** [comment]
A lot of talk about this on the forum in 2009!
https://forum.virtualmin.com/t/feature-request-network-service-monitoring/33910

These are two free solutions, ready to install and try now:

1. Install Nagios core free, and install the nagios webmin module on your webmin.
https://exchange.nagios.org/directory/Addons/Configuration/Nagios-Webmin-Module/details

2. Install Zabbix free open source, and install the zabbix agent for Linux on your webmin.
https://www.zabbix.com/

**Comment by jcameron** [comment]
You can also have the System and Server Status module run a command of your choice when a monitor goes down, which could be a `wget` command that sends the POST request you want.

**Comment by luison** [comment]
Another voter for this feature... as a sort of webhook.
The process could be the same as on the monitors with a command on down and up, but if it was here in the config it could apply to all monitors automatically but in that case it would have to be clear how to pass to the cmd the parameters of the monitor... name, type, value, etc

**Comment by jcameron** [comment]
Any particular format that would make sense for the URL parameters in this webhook call? Like is there some monitoring system you'd like to integrate with?

**Comment by luison** [comment]
Not particularly. For flexibility nowadays a post with a JSON of all the
alert data and a field to support a key for authentication I guess.

In our case we would use a webhook to receive alerts and try to build an
scalable notification solution.

**Comment by jcameron** [comment]
Ok, I've implemented this feature for inclusion in the next Webmin release.
