### ISSUE TITLE
sshd ssh-keygen "Setup SSH key for new Unix users" home dir trailing slash no longer supported, Debian 11

### ISSUE THREAD

**Issue by hayden-t** [webmin/webmin#1740]
Debian 11 Virtualmin 7.1-1 Webmin 1.999 
This seems to be a new thing, as Debian 9 does not bomb from this

If you specify a home for a new user via webmin like so:
/home/test/
ssh-keygen will fail to create the missing .ssh folder, 
```
ssh-keygen
Generating public/private rsa key pair.
Enter file in which to save the key (/home/test//.ssh/id_rsa): 
Enter passphrase (empty for no passphrase): 
Enter same passphrase again: 
Saving key "/home/test//.ssh/id_rsa" failed: No such file or directory
```
but /home/test as home works

**Comment by jcameron** [comment]
Thanks, I'll fix this by disallowing trailing /
