### ISSUE TITLE
How to view `systemd timers`?

### ISSUE THREAD

**Issue by Sopor** [webmin/webmin#1745]
I'm running Let's Encrypt and it seems that they have made it easier to install.

Now you don't need to add anything to the Cron jobs. Instead it will be added here:
```
$ systemctl list-timers
NEXT                         LEFT          LAST                         PASSED       UNIT                         ACTIVATES
Mon 2022-09-19 06:14:00 CEST 5h 31min left n/a                          n/a          snap.certbot.renew.timer     snap.certbot.renew.service
```
But where can i find this in Webmin without running `systemctl list-timers` and how can i add and edit the list from Webmin?

If i run:
```
$ sudo systemctl list-timers
NEXT                         LEFT          LAST                         PASSED        UNIT                         ACTIVATES
Tue 2022-09-20 19:09:00 CEST 5min left     Tue 2022-09-20 18:39:03 CEST 24min ago     phpsessionclean.timer        phpsessionclean.service
Tue 2022-09-20 22:40:23 CEST 3h 36min left Mon 2022-09-19 22:40:24 CEST 20h ago       systemd-tmpfiles-clean.timer systemd-tmpfiles-clean.service
Wed 2022-09-21 00:00:00 CEST 4h 56min left Tue 2022-09-20 00:00:02 CEST 19h ago       logrotate.timer              logrotate.service
Wed 2022-09-21 06:14:00 CEST 11h left      Tue 2022-09-20 16:11:02 CEST 2h 52min ago  snap.certbot.renew.timer     snap.certbot.renew.service
Mon 2022-09-26 01:38:42 CEST 5 days left   Mon 2022-09-19 00:45:13 CEST 1 day 18h ago fstrim.timer                 fstrim.service

5 timers listed.
```
I did try the filter but it wasn't that easy. I wrote `timer` but it will not show all timer there 😕
![image](https://user-images.githubusercontent.com/5789283/191329361-492cd935-db1f-47a4-92f5-056a22267127.png)

So, there isn't any easy way to list the timers without running the `systemctl list-timers`?

**Comment by jcameron** [comment]
Are systemd timers something different from regular cron jobs?

**Comment by jcameron** [comment]
Ok ... well if you are using Webmin or Virtualmin, you don't need to setup a timer to renew Let's Encrypt certs, because Webmin will do this for you automatically by creating a Cron job.

**Comment by jcameron** [comment]
Ok .. in that case, we would need to eventually look into adding support for timers as a feature.

**Comment by iliajie** [comment]
We already [read](https://github.com/webmin/webmin/blob/master/init/init-lib.pl#L2140-L2146) `list-unit-files` that include timers too .. so, we could just include `.timer` with `$l =~ /^(\S+\.timer)` test ..

**Comment by jcameron** [comment]
We could, but I feel like the UI should be separate for timers vs. bootup actions.

**Comment by iliajie** [comment]
Isn't timers like a regular editable unit files?

**Comment by jcameron** [comment]
Yes, but presumably they have different attributes to units started at boot time?

**Comment by chris001** [comment]
[Differences between `cron` and `systemd timers`](https://fedoramagazine.org/systemd-timers-for-scheduling-tasks/)

**Comment by iliajie** [comment]
> Yes, but presumably they have different attributes to units started at boot time?

Which attributes do you have in mind?

A timer is configured with a generic `[Unit]` and `[Install]` sections. Timers can be stopped and started, enabled and disabled.

**Comment by FBachofner** [comment]
Hi Jamie @jcameron 

> Ok .. in that case, we would need to eventually look into adding support for timers as a feature.

Is this on the roadmap?  I have started messing around with timers and this would be an awesome addition to Webmin.

**Comment by iliajie** [comment]
It must already be added in the latest Webmin 2.021.
