### ISSUE TITLE
Ajaxterm requires Python to run, but the python command was not found on your system. 

### ISSUE THREAD

**Issue by Sopor** [webmin/webmin#1746]
First i got:
`Ajaxterm requires Python to run, but the python command was not found on your system.`

I then did as Jamie suggested and created a symlink and now i get this:
`Ajaxterm did not start accepting connections on port 10001 after 30 seconds.`

It seems to be a bug from 2021 `https://sourceforge.net/p/webadmin/bugs/5463` 😥

I don't even know what `Text login` do, but if i don't try it out i will never know 😊

**Comment by chris001** [comment]
The fix seems to be mentioned on this sourceforge discussion:
https://sourceforge.net/p/webadmin/bugs/5463/

**Comment by jcameron** [comment]
@Sopor which Python version do you have installed?

**Comment by Sopor** [comment]
Python 3.9.2 only.

**Comment by chris001** [comment]
I think it requires python 2.x only which you can install alongside python 3.x and have both on your system

**Comment by Sopor** [comment]
@chris001 I have been running both before and it is always a mess when both are installed. Python 2.x should not be used anymore.

**Comment by chris001** [comment]
@Sopor Unfortunately, Ajaxterm doesn't support python 3.  Did you try @iliaross [simple fix](https://github.com/webmin/webmin/commit/c6430c2c2de4fb51e7282a737ce95b085581a615) ?

**Comment by Sopor** [comment]
Now when Python 2.x is almost obsolete, more and more users will get this issue with Ajaxterm and therefore I think there should be some kind of message telling the users what is wrong.
It will tell you that Python is required, but because this is a known issue the message could be rewritten and explain why and how to fix it?

I'm not sure how @iliaross fix will help when it only work with Python 2.x, but i'm not a Python expert 😁

If the fix works, why isn't it added in the Webmin repo? As it is now, every user has to make the changes by themself 🙁

I assume Ajaxterm isn't updated anymore, so there will not be any Ajaxterm for Python 3 😕

**Comment by chris001** [comment]
I agree, it would be nicer experience for the users if the error message would say, "your system doesn't have `python2`, which is required by `Ajaxterm`, click this button to install `python2`".

**Comment by chris001** [comment]
@jcameron `Ajaxterm` github repo shows it was last updated 12 years ago.  Now is a good time to look at a different terminal which is compatible with current software and actively maintained, for example, [hyper](https://github.com/vercel/hyper), and there are others...

**Comment by iliaross** [comment]
> I'm not sure how @iliaross fix will help when it only work with Python 2.x, but i'm not a Python expert 😁

I would suggest not to use Ajaxterm at all. If you really need it you can always install `python2` which is not really advisable either.



> @jcameron `Ajaxterm` github repo shows it was last updated 12 years ago. Now is a good time to look at a different terminal which is compatible with current software and actively maintained, for example, [hyper](https://github.com/vercel/hyper), and there are others...

The simplest solution (even pretty old one) is to install `shellinabox` package from your OS repos (it's still supported on the latest Ubuntu 22.04 for example) and just connect to your server using `https://example.com:4200` .

Perhaps, a better solution would be to setup and use [noVNC](https://github.com/novnc/noVNC)?

**Comment by chris001** [comment]
Also look at [wetty](https://github.com/butlerx/wetty) its repo was updated 7 hours ago, has many maintainers, much better user experience than Ajaxterm as it uses full `xterm.js` terminal emulation in javascript in the browser, thru a faster server websocket, compared to Ajaxterm's slower `ajax` requests sent over the `http` protocol!

**Comment by swelljoe** [comment]
wetty is a non-starter. It requires nodejs, and a pretty recent version. Node is too much for Webmin to depend (and I hate the JavaScript ecosystem at this point...the dependencies are absurd).

We already have a [long discussion about how to include a real interactive terminal in Webmin](https://github.com/webmin/authentic-theme/issues/1037), which mentions a couple of options that _could_ work...please make any suggestions and continue the conversation there (I don't know why that ticket is on Authentic Theme, but it's already going and has covered the bases about what any such solution needs to do: Low dependencies, maintained, relies only on things we can expect to be installed already...like Python or Perl, nodejs is right the heck out).

**Comment by swelljoe** [comment]
I'm going to close this, as the solution to the original problem is "install python2". Whether OP wants to do that is up to them. But, that's how you make AJAXTerm work.

Not much else to discuss about it, as we're not going to try to port AJAXTerm to run with Python 3 or take over maintainence of it, and if it's unmaintained, we probably shouldn't even be offering it.

**Comment by iliajie** [comment]
The conversation will be continued here - https://github.com/webmin/authentic-theme/issues/1037#issuecomment-1261518235
