### ISSUE TITLE
Centos 7 cant  install 	IP access control  - Authen::Libwrap

### ISSUE THREAD

**Issue by zeteticl** [webmin/webmin#1749]
![image](https://user-images.githubusercontent.com/23254376/193988626-a4406675-6795-40f8-824b-0f89060773e6.png)

How could i  solve it?
It is in centos 7.

**Comment by jcameron** [comment]
How did you get to that page where Webmin offers to install that module?

**Comment by zeteticl** [comment]
Thank you!
