### ISSUE TITLE
add service monitor to System and Server Status without using webmin interface

### ISSUE THREAD

**Issue by jpgpi250** [webmin/webmin#1755]
My debian system runs services, such as chrony, pihole-FTL, unbound, ...

I want to add monitors for these services to the default list, by simply editing (or adding) files and restart webmin to activate the monitors.

Is this even possible?

I tried to add a monitor to webmin (System and Server Status), using the interface, following the instructions in [this pdf](https://ptgmedia.pearsoncmg.com/images/0131408828/downloads/0131408828.pdf). The manual says to add a "check process" monitor and use a "perl regular expression" as a parameter, however, I have no idea how to do this, and can't find any example, using duckduckgo.

will added monitors be saved, when making a backup /restore of the webmin configuration?

Thanks for your time and effort.

**Comment by jcameron** [comment]
Yes, it is possible to create a new monitor by adding a `.serv` file under `/etc/webmin/status/services` , which can just be a copy of an existing file. The format should be mostly self-explanatory ..

**Comment by jpgpi250** [comment]
I only have '/etc/webmin/status', there is no 'services' folder (and no '.serv' files)
the folder '/etc/webmin/status' only contains a single file, 'config'

**Comment by jcameron** [comment]
Do you see any existing monitors at Tools -> System and Server Status?

**Comment by jcameron** [comment]
That's very surprising, as that default set of monitors is usually stored in `/etc/webmin/status/services` after the first time you open the module.

**Comment by jpgpi250** [comment]
my bad, I looked for these files on a fresh installed system, where I never opened the module.
I opened the module, the files appeared. Sorry for this.

Anyway, I then copied an existing file to a new file (/etc/webmin/status/services/unbound.serv), and edited it, content:
```
id=unbound
type=unbound
desc=Unbound
depends=unbound
```
checked the permissions and owner to match the other files
stopped webmin (sudo service webmin stop)
started webmin
no joy, unbound hasn't been added to the webmin page

I looked for all .serv files on the system (sudo find / -type f -name "*.serv") and noticed there are also .serv files in /usr/share/webmin/status/services, so I duplicated the unbound.serv file in that location, restart webmin, no joy...

Tried to remove all serv files in /etc/webmin/status/services, stop/start webmin, module now says  "No monitors are currently defined."
restored these files, including the unbound file, stop/start webmin, predifined monitors reappear, but still no unbound monitor, thus no joy.

there must be something else, required, to make the monitor appear.

also tried, adding /etc/webmin/unbound/config, content:
```
unbound_dir=/etc/unbound
unbound_daemon=/usr/sbin/unbound
unbound_config=/etc/unbound/unbound.conf
start_cmd=sudo systemctl start unbound
stop_cmd=sudo systemctl stop unbound
pid_file=/run/unbound.pid
```
no joy...

your advice please...

**Comment by jcameron** [comment]
Yes, you can enter the process name as a regular expression, like `^unbound$` , which will match only processes whose name is just "unbound"

**Comment by jcameron** [comment]
What is the process name shown as at System -> Running Processes?

**Comment by jpgpi250** [comment]
![image](https://user-images.githubusercontent.com/24669386/195669918-be2d1e96-28b8-44fb-a3a0-e8daa30ab2ad.png)

**Comment by jcameron** [comment]
Ok, in that case you should set the name to match to be that full command, like `/usr/sbin/unbound -d -v`

**Comment by jpgpi250** [comment]
that seems to be working, thanks 

![image](https://user-images.githubusercontent.com/24669386/195677668-990e2955-bc7d-47a0-b629-cf51835b856d.png)
![image](https://user-images.githubusercontent.com/24669386/195677787-ae3cca5a-f5fa-4a5d-9034-c31a27c07a75.png)

**Comment by jpgpi250** [comment]
tested on several services, using the output of 'which unbound', combined with '^' works.
examples:
`which kresd` -> /usr/sbin/kresd -> `cmd=^/usr/sbin/kresd`
`which dnsmasq` -> /usr/sbin/dnsmasq -> `cmd=^/usr/sbin/dnsmasq`

thanks for your time and effort
