### ISSUE TITLE
White screen when try to view webmin

### ISSUE THREAD

**Issue by python-coding-404** [webmin/webmin#1756]
I haved install webmin using the deb
when i opend the page it was just nothing only text curser when i inpuect the dom
i know that there was a login page so i blidy login in to webmin 
then i say the aria where that navbar is had a clor of grey 
i am currently using 1.999-2 and nothing has gone wrong

**Comment by iliajie** [comment]
Hello,

The latest Webmin version is 2.001

> White screen when try to view webmin

This can happen if `/etc/webmin/miniserv.conf` file has `allow=` set to a specific IPs.

**Comment by python-coding-404** [comment]
Closed because i updated my webmin 
to 2.000
and it worked
