### ISSUE TITLE
2FA won't work (Perl Module installation not possible)

### ISSUE THREAD

**Issue by CoreattackSystems** [webmin/webmin#1783]
Hey guys i had Webmin for quite some time and wanted to user 2FA now. So I tried to activate it but it is stuck at the 
`Failed to save two-factor authentication : The Perl module Authen::OATH needed for two-factor authentication is not installed. Use the [Perl Modules](https://192.168.2.100:10000/cpan/download.cgi?source=3&cpan=Authen::OATH&mode=2&return=/webmin/&returndesc=Webmin%20configuration) page in Webmin to install it.` site.
It puts one CPU Core at full capacity and another one if you retry that process if that helps. (Tried to wait but 45mins was enough i thought) Well I tried to go to this site directly and it works. 
But when i try to install it it wants to get missing prerequistits but same happens there. 
Nothing changed after reinstalling.

System used is based on Debian (DietPi)
I did not install it via the adding repository method

Thanks for every help

**Comment by jcameron** [comment]
What if you try to install that module by logging in your system as `root` and running `perl -MCPAN -e 'install Authen::OATH'`

**Comment by CoreattackSystems** [comment]
Hey thanks for the reply. I did run the command you gave me and it did not
work at first but the error messages indicated a problem with some packages
on my system. After I fixed these everything went smoothly. Thank you very
much

Jamie Cameron ***@***.***> schrieb am So., 13. Nov. 2022,
05:30:

**Comment by iliajie** [comment]
@swelljoe Joe, do you think it would be hard to build `Authen::OATH` for our users?

**Comment by swelljoe** [comment]
Not easily, as Authen::OATH has several non-core dependencies, so I'd have to package some of its other deps. But, I'm looking into it.

**Comment by iliajie** [comment]
Upcoming Webmin 2.010 will have 2FA working out of the box as `Authen::OATH` will be bundled.
