### ISSUE TITLE
Dovecot start command checks for protocols

### ISSUE THREAD

**Issue by iliajie** [webmin/webmin#1793]
https://github.com/webmin/webmin/blob/c0c993efec7ace1c5f352eabc7b2bcbb46884776/dovecot/start.cgi#L7-L8

Jamie, this may break the systems (i.e. openSUSE) where `protocols` directive is commented out by default. Although, does it mean that Dovecot isn't serving connections by default?

I suggest removing it.

**Comment by jcameron** [comment]
Odd, because I found that Dovecot doesn't start unless this option is set. Maybe on later versions of Dovecot there's a sensible default?

**Comment by iliajie** [comment]
> Maybe on later versions of Dovecot there's a sensible default?

Yeah, I think it has changed for the past 15 years. I can tell that the recent versions of Dovecot may have `protocols` directive commented out and things still work the same (expected) way!

```
[root@alma9-pro ~]# ss -tnlp | grep dovecot
LISTEN 0      100                                  0.0.0.0:993        0.0.0.0:*    users:(("dovecot",pid=148783,fd=41))                                                 
LISTEN 0      100                                  0.0.0.0:995        0.0.0.0:*    users:(("dovecot",pid=148783,fd=23))                                                 
LISTEN 0      100                                  0.0.0.0:110        0.0.0.0:*    users:(("dovecot",pid=148783,fd=21))                                                 
LISTEN 0      100                                  0.0.0.0:143        0.0.0.0:*    users:(("dovecot",pid=148783,fd=39))                                                 
LISTEN 0      100                                     [::]:993           [::]:*    users:(("dovecot",pid=148783,fd=42))                                                 
LISTEN 0      100                                     [::]:995           [::]:*    users:(("dovecot",pid=148783,fd=24))                                                 
LISTEN 0      100                                     [::]:110           [::]:*    users:(("dovecot",pid=148783,fd=22))                                                 
LISTEN 0      100                                     [::]:143           [::]:*    users:(("dovecot",pid=148783,fd=40))  
```

I get the same output disregard of `protocols` enabled or disabled in `dovecot.conf` file. That said the default is:

```
protocols = imap pop3
```

I don't believe we need that check anymore.

**Comment by jcameron** [comment]
Ok, I'll remove it!

**Comment by iliajie** [comment]
Thanks!
