### ISSUE TITLE
Webmin 2.000 Empty Dashboard

### ISSUE THREAD

**Issue by naota-sensei** [webmin/webmin#1795]
Gday for everyone!
Dashboard is empty, i dont see anything. One time i see error "webmin system information can't be recollected"
And when i open dashboard link in the left menu, sometimes webmin lock my IP address, i found it in webmin error.log with comment: To many connections from @my ip address@
![image](https://user-images.githubusercontent.com/117346238/203997463-9944cb17-8ccb-499f-a9af-8ad176160d23.png)

Ubuntu 20, install webmin from repositories. Try reinstall, webmin and update system, nothing changed.

**Comment by naota-sensei** [comment]
Ubuntu 20, install webmin from repositories.

**Comment by iliajie** [comment]
Hello,

You can control connection concurrency in `Webmin ⇾ Webmin Configuration: Ports and Addresses` page.

**Comment by naota-sensei** [comment]
Thx, but what about SystemInfo on dashboard, its broken?

**Comment by naota-sensei** [comment]
But again, dashboard work 1 time at all. And i see freez session from my IP
![image](https://user-images.githubusercontent.com/117346238/204041108-3d14d5bb-3283-407b-8fa3-2e5153c2cd99.png)

**Comment by naota-sensei** [comment]
one user session, i think its ubnormal.
 CGroup: /system.slice/webmin.service
             ├─ 33341 /usr/bin/perl /usr/share/webmin/miniserv.pl --nofork /etc/webmin/miniserv.conf
             ├─ 33442 /usr/share/webmin/authentic-theme/index.cgi
             ├─ 34498 /usr/share/webmin/authentic-theme/index.cgi
             ├─ 35281 /usr/share/webmin/authentic-theme/sysinfo.cgi
             ├─ 35966 /usr/share/webmin/authentic-theme/index.cgi
             ├─ 36643 /usr/share/webmin/authentic-theme/index.cgi
             ├─ 37428 /usr/share/webmin/authentic-theme/index.cgi
             ├─ 39290 /usr/share/webmin/authentic-theme/index.cgi
             ├─ 43373 /usr/share/webmin/authentic-theme/index.cgi
             ├─ 44611 /usr/share/webmin/authentic-theme/index.cgi
             ├─ 45157 /usr/share/webmin/authentic-theme/index.cgi
             ├─ 46484 /usr/share/webmin/authentic-theme/index.cgi
             ├─ 47102 /usr/share/webmin/authentic-theme/index.cgi
             ├─ 47750 /usr/share/webmin/authentic-theme/index.cgi
             ├─ 62695 /usr/share/webmin/authentic-theme/index.cgi
             ├─ 64054 /usr/share/webmin/authentic-theme/index.cgi
             ├─ 65432 /usr/share/webmin/authentic-theme/index.cgi
             ├─ 66474 /usr/share/webmin/authentic-theme/index.cgi
             ├─ 67997 /usr/share/webmin/authentic-theme/index.cgi
             ├─ 68764 /usr/share/webmin/authentic-theme/index.cgi
             ├─ 68942 /usr/share/webmin/authentic-theme/index.cgi
             ├─ 70293 /usr/share/webmin/authentic-theme/index.cgi
             ├─ 71706 /usr/share/webmin/authentic-theme/index.cgi
             ├─ 74094 /usr/share/webmin/authentic-theme/index.cgi
             ├─ 76299 /usr/share/webmin/authentic-theme/index.cgi
             ├─ 77527 /usr/share/webmin/authentic-theme/index.cgi
             ├─ 78667 /usr/share/webmin/authentic-theme/index.cgi
             ├─ 79720 /usr/share/webmin/authentic-theme/index.cgi
             ├─ 80695 /usr/share/webmin/authentic-theme/index.cgi
             ├─ 81248 /usr/share/webmin/authentic-theme/index.cgi
             ├─ 82384 /usr/share/webmin/authentic-theme/index.cgi
             ├─ 83378 /usr/share/webmin/authentic-theme/index.cgi
             ├─ 84222 /usr/share/webmin/authentic-theme/sysinfo.cgi
             ├─ 84581 /usr/share/webmin/authentic-theme/index.cgi
             ├─ 85052 /usr/share/webmin/authentic-theme/sysinfo.cgi
             ├─ 85088 /usr/share/webmin/authentic-theme/index.cgi
             ├─ 85173 /usr/share/webmin/authentic-theme/sysinfo.cgi
             ├─ 85210 /usr/share/webmin/authentic-theme/index.cgi
             ├─ 85445 /usr/share/webmin/authentic-theme/index.cgi
             ├─ 85618 /usr/share/webmin/authentic-theme/sysinfo.cgi
             ├─ 85738 /usr/share/webmin/authentic-theme/sysinfo.cgi
             ├─ 86007 /usr/share/webmin/authentic-theme/index.cgi
             ├─ 89255 /usr/share/webmin/authentic-theme/index.cgi
             ├─ 90668 /usr/share/webmin/authentic-theme/index.cgi
             ├─ 91782 /usr/share/webmin/authentic-theme/index.cgi
             ├─ 92500 /usr/share/webmin/authentic-theme/index.cgi
             ├─ 93284 /usr/share/webmin/authentic-theme/sysinfo.cgi
             ├─ 93425 /usr/share/webmin/authentic-theme/index.cgi
             ├─ 94984 /usr/share/webmin/authentic-theme/index.cgi
             ├─ 95157 /usr/share/webmin/authentic-theme/index.cgi
             ├─ 95826 /usr/share/webmin/authentic-theme/index.cgi
             ├─ 96225 /usr/share/webmin/authentic-theme/index.cgi
             ├─ 97015 /usr/share/webmin/authentic-theme/index.cgi
             ├─ 97368 /usr/share/webmin/authentic-theme/index.cgi
             ├─101498 /usr/share/webmin/authentic-theme/index.cgi
             ├─102597 /usr/share/webmin/authentic-theme/index.cgi
             ├─102871 /usr/share/webmin/authentic-theme/sysinfo.cgi

**Comment by jcameron** [comment]
All those hung `index.cgi` processes are odd. What output do you get if you run `lsof -p 101498` to show open connections from that process?

**Comment by naota-sensei** [comment]
COMMAND      PID USER   FD   TYPE             DEVICE  SIZE/OFF    NODE NAME
/usr/shar 129113 root  cwd    DIR                8,2     36864 3416767 /usr/share/webmin/status
/usr/shar 129113 root  rtd    DIR                8,2      4096       2 /
/usr/shar 129113 root  txt    REG                8,2   3478464 1181382 /usr/bin/perl
/usr/shar 129113 root  mem    REG                8,2     51856 1179982 /usr/lib/x86_64-linux-gnu/libnss_files-2.31.so
/usr/shar 129113 root  mem    REG                8,2    101352 1179988 /usr/lib/x86_64-linux-gnu/libresolv-2.31.so
/usr/shar 129113 root  mem    REG                8,2     27112 1179981 /usr/lib/x86_64-linux-gnu/libnss_dns-2.31.so
/usr/shar 129113 root  mem    REG                8,2     43872 1315009 /usr/lib/x86_64-linux-gnu/perl/5.30.0/auto/Data/Dumper/Dumper.so
/usr/shar 129113 root  mem    REG                8,2     18840 1315474 /usr/lib/x86_64-linux-gnu/perl/5.30.0/auto/MIME/Base64/Base64.so
/usr/shar 129113 root  mem    REG                8,2     56208 1315473 /usr/lib/x86_64-linux-gnu/perl/5.30.0/auto/List/Util/Util.so
/usr/shar 129113 root  mem    REG                8,2     18984 1314990 /usr/lib/x86_64-linux-gnu/perl/5.30.0/auto/Cwd/Cwd.so
/usr/shar 129113 root  mem    REG                8,2    113832 1315484 /usr/lib/x86_64-linux-gnu/perl/5.30.0/auto/Storable/Storable.so
/usr/shar 129113 root  mem    REG                8,2     47944 1315440 /usr/lib/x86_64-linux-gnu/perl/5.30.0/auto/Encode/Encode.so
/usr/shar 129113 root  mem    REG                8,2     31336 1315481 /usr/lib/x86_64-linux-gnu/perl/5.30.0/auto/SDBM_File/SDBM_File.so
/usr/shar 129113 root  mem    REG                8,2     43000 3282893 /usr/lib/x86_64-linux-gnu/perl5/5.30/auto/IO/Tty/Tty.so
/usr/shar 129113 root  mem    REG                8,2     27064 1185676 /usr/lib/x86_64-linux-gnu/libcap-ng.so.0.0.0
/usr/shar 129113 root  mem    REG                8,2    133200 1185666 /usr/lib/x86_64-linux-gnu/libaudit.so.1.0.0
/usr/shar 129113 root  mem    REG                8,2     68320 1180114 /usr/lib/x86_64-linux-gnu/libpam.so.0.84.2
/usr/shar 129113 root  mem    REG                8,2     23152 1315470 /usr/lib/x86_64-linux-gnu/perl/5.30.0/auto/IO/IO.so
/usr/shar 129113 root  mem    REG                8,2     39408 3282881 /usr/lib/x86_64-linux-gnu/perl5/5.30/auto/Authen/PAM/PAM.so
/usr/shar 129113 root  mem    REG                8,2     23088 1315430 /usr/lib/x86_64-linux-gnu/perl/5.30.0/auto/Digest/MD5/MD5.so
/usr/shar 129113 root  mem    REG                8,2   2954080 1180083 /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
/usr/shar 129113 root  mem    REG                8,2    598104 1180216 /usr/lib/x86_64-linux-gnu/libssl.so.1.1
/usr/shar 129113 root  mem    REG                8,2     23064 1445043 /usr/lib/x86_64-linux-gnu/perl/5.30.0/auto/Sys/Syslog/Syslog.so
/usr/shar 129113 root  mem    REG                8,2    608256 3282767 /usr/lib/x86_64-linux-gnu/perl5/5.30/auto/Net/SSLeay/SSLeay.so
/usr/shar 129113 root  mem    REG                8,2     35424 1445159 /usr/lib/x86_64-linux-gnu/perl/5.30.0/auto/Time/HiRes/HiRes.so
/usr/shar 129113 root  mem    REG                8,2     31520 1315460 /usr/lib/x86_64-linux-gnu/perl/5.30.0/auto/File/Glob/Glob.so
/usr/shar 129113 root  mem    REG                8,2    114480 1315480 /usr/lib/x86_64-linux-gnu/perl/5.30.0/auto/POSIX/POSIX.so
/usr/shar 129113 root  mem    REG                8,2     47832 1315482 /usr/lib/x86_64-linux-gnu/perl/5.30.0/auto/Socket/Socket.so
/usr/shar 129113 root  mem    REG                8,2   3035952 1180870 /usr/lib/locale/locale-archive
/usr/shar 129113 root  mem    REG                8,2    202760 1185680 /usr/lib/x86_64-linux-gnu/libcrypt.so.1.1.0
/usr/shar 129113 root  mem    REG                8,2   2029592 1179974 /usr/lib/x86_64-linux-gnu/libc-2.31.so
/usr/shar 129113 root  mem    REG                8,2    157224 1179987 /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
/usr/shar 129113 root  mem    REG                8,2   1369384 1179976 /usr/lib/x86_64-linux-gnu/libm-2.31.so
/usr/shar 129113 root  mem    REG                8,2     18848 1179975 /usr/lib/x86_64-linux-gnu/libdl-2.31.so
/usr/shar 129113 root  mem    REG                8,2     22896 1315456 /usr/lib/x86_64-linux-gnu/perl/5.30.0/auto/Fcntl/Fcntl.so
/usr/shar 129113 root  mem    REG                8,2    191504 1179715 /usr/lib/x86_64-linux-gnu/ld-2.31.so
/usr/shar 129113 root    0r   CHR                1,3       0t0       6 /dev/null
/usr/shar 129113 root    1w   CHR                1,3       0t0       6 /dev/null
/usr/shar 129113 root    2w   REG                8,2 111099068 1968083 /var/webmin/miniserv.error
/usr/shar 129113 root    3u  unix 0xffff9b4ceffe1400       0t0 1549337 type=DGRAM
/usr/shar 129113 root    4w   CHR                1,3       0t0       6 /dev/null
/usr/shar 129113 root    5w   REG                8,2   5236565 1966507 /var/webmin/miniserv.log
/usr/shar 129113 root    6u   REG                8,2      1024 1968094 /var/webmin/sessiondb.pag
/usr/shar 129113 root    7u   REG                8,2         0 1968095 /var/webmin/sessiondb.dir
/usr/shar 129113 root    8u  IPv4            1555898       0t0     TCP "my server":42796->secureprojects.sourceforge.net:http (CLOSE_WAIT)
/usr/shar 129113 root    9u  IPv4            1554219       0t0     TCP "my server":webmin->"my client IP":5085 (CLOSE_WAIT)
/usr/shar 129113 root   10u  IPv4            1555900       0t0     TCP "my server":55420->secureprojects.sourceforge.net:https (ESTABLISHED)
/usr/shar 129113 root   15w  FIFO               0,13       0t0 1554220 pipe
/usr/shar 129113 root   16r  FIFO               0,13       0t0 1554221 pipe

**Comment by jcameron** [comment]
Seems like it is hung connecting to www.webmin.com . Does this process continue to run for more than 5 seconds?

Also, do you have any firewall blocking outgoing connections?

**Comment by naota-sensei** [comment]
Yes, run more 5 seconds. 
FW - classic NGFW, and yes webmin.com blocking. Webmin need connect to webmin.com to stable work?

**Comment by jcameron** [comment]
You can turn this off by adding the line `nowebminup=1` to `/etc/webmin/config`

**Comment by naota-sensei** [comment]
> You can turn this off by adding the line `nowebminup=1` to `/etc/webmin/config`
This is solution to my problem. I really owe you one.
