### ISSUE TITLE
Webmin 2.010 no longer loads on Pale Moon

### ISSUE THREAD

**Issue by wolfbeast** [webmin/webmin#1802]
As [reported](https://forum.palemoon.org/viewtopic.php?f=70&t=29127) on our forum, an upgrade from 2.000 to 2.010 resulted in Webmin no longer loading on the Pale Moon browser due to unsupported Regex extensions in `bundle.min.js`.
There was no mention of anything like this in the webmin release notes.

```
Content Security Policy: Directive ‘child-src’ has been deprecated. Please use directive ‘worker-src’ to control workers, or directive ‘frame-src’ to control frames respectively. (unknown)
SyntaxError: invalid identity escape in regular expression bundle.min.js:183:486802
```

**Comment by iliajie** [comment]
Hello,

What is your Pale Moon browser version?

**Comment by wolfbeast** [comment]
Mine is 31.4.1 - I'm assuming the forum reporter's version is the same.
I've declined to upgrade Webmin on my servers for the time being as I need to be able to manage them in production...
Looking at the relnotes, I'm guessing the 2.003 update might have caused the problem if you replaced the grey framed theme with something from virtualmin?

**Comment by swelljoe** [comment]
Grey Theme and Virtualmin Framed Theme do not load bundle.min.js (that's an Authentic thing).

**Comment by iliajie** [comment]
ES9 was introduced back in 2018, which is 5 years ago. Pale Moon website says:

> Pale Moon is an Open Source, Goanna-based web browser completely built from its own, independently developed source that has been forked off from Firefox/Mozilla code a number of years ago, and focuses on efficiency and ease of use **by carefully selecting features and optimizations** to improve the browser's stability and user experience

I don't know what should I do, as I think five years is more than enough time to enroll support for ES9. My personal suggestion would be to use Mozilla Firefox browser instead. Authentic Theme is complex, nevertheless, I could add support for antiquated browsers, although I don't know if it really should be done.

We are all very happy to see IE go, and prefer not to add extra complexity any further.

Also, I cannot even install Pale Moon on Mac.

Where exactly do you get this error? On the very initial load?

**Comment by iliajie** [comment]
I have checked it on my Microsoft Windows 11 machine and Pale Moon fails even though the corresponding (ES9) code is in `try {} catch() {}` block.

What is the point of using Pale Moon? Isn't Firefox fast and secure enough?

**Comment by wolfbeast** [comment]
> Grey Theme and Virtualmin Framed Theme do not load bundle.min.js (that's an Authentic thing).

Oh that's good then. Can that be selected upon installation instead of Authentic (i.e. without having to load Authentic first to change the theme?). I personally don't care about Authentic as it's heavy and error-prone even on mainstream.

> I don't know what should I do, as I think five years is more than enough time to enroll support for ES9.

I understand your reasoning, however ES2018's regex changes specifically are literally **_only_** possible with V8's implementation (even Mozilla has literally taken Chrome code and glued it into Firefox in a months' long process with a full team of devs at their disposal) and we've been trying to incorporate these regex extensions but they are literally _redefining_ how regex is supposed to work and so far have had little luck.

Why are you enrolling ES9, exactly, anyway? Are you even writing this regex code yourself or is it just a configuration bit in Sveltekit (i.e. just telling it that it should "spit out" this code)? Can't you just configure it to use ES2017 as a cap, if so?

>  Isn't Firefox fast and secure enough?

It isn't. There are a multitude of reasons why users choose Pale Moon (by the way, there is a Mac build called [White Star](https://www.dbsoft.org/whitestar.php)) not in the least issues with Mozilla's incessant and always-on telemetry of their browser use, tight integration with Mozilla-run or partnered services (i.e. considerable privacy issues), reliance on Rust which isn't available on all operating systems, multi-process resource hogging and sec issues, lack of customizability, limited extension capabilities, etc.

There are obviously solutions here, barring demanding that we somehow wave a magic wand to rewrite swathes of our JS engine to suddenly have Chrome-implementation exclusive capabilities: easy configuration of the theme upon install/upgrade, or poking Sveltekit to use ES2017, or otherwise not use the Regex extensions.

**Comment by iliajie** [comment]
> (even Mozilla has literally taken Chrome code and glued it into Firefox in a months' long process with a full team of devs at their disposal) and we've been trying to incorporate these regex extensions but they are literally _redefining_ how regex is supposed to work and so far have had little luck.

I have fixed support for all Goanna based browsers. Give it a try by updating the theme by running `webmin update-devel --product webmin --theme` command.

**Comment by wolfbeast** [comment]
> Also, it sounds like biased accusation (in terms of being error-prone).

I can only tell you that whenever I was presented with it, it regularly failed to work properly, regardless of browser in use at the time. Quite possible it has improved over time but it's been my personal real-world experience with it on a variety of CentOS servers and various web clients. Does that now make me biased against wanting to use it? Absolutely. Is the accusation biased? Absolutely not. I understand a lot of work went into it and I appreciate the effort - but if I run into practical issues with it, then that trumps any look.

> Are you Pale Moon developer?

Yes.

> don't you think that a new regex code that was added to Authentic theme recently shouldn't fail on Pale Moon as it's in try-catch block?

That's not how syntax errors work. Those fail in the parser, not interpreter. Malformed JS source code can't be expected to actually be run through the interpreter (where script flow happens and try/catch would have an effect), i.e. syntax errors bail out execution before anything runs. You can't compile code with syntax errors in other languages either ;)

> I have fixed support for all Goanna based browsers. Give it a try by updating the theme

Thank you, I appreciate it! I'll give it a try when I have some free time (likely not today).

**Comment by wolfbeast** [comment]
Sorry for the slow response.
I performed the update as suggested with `webmin update-devel --product webmin --theme` and Authentic was updated to 20.11 -- switching to it on Pale moon i can confirm with casual inspection everything seems to be in order. Thank you.

**Comment by iliajie** [comment]
You're welcome. Let me know if you find anything else.

**Comment by mattatobin** [comment]
I would only add that as an essential system administrator tool webmin, IF it is going to use the shinys coming from the Chromium Monoculture + Token WhatWG Vote/Competition, then maybe the SIMPLEST thing to do so that  when this invulnerably happens again for a Pale Moon user or any other web client built off an alternatively evolved classical mozilla codebase (or something new) would be to offer a `nojs=1` query argument that would allow you to login and control a limited selection of core webmin options without JS (and using basic but classy styling) SUCH as current/default theme from said web client.

That way providing the webmin team remain awesome and provide spot-fallbacks for non-Chromium/Current Firefox this would be a great enhancement and relieve pressure when `Stage 4` comes to call :)

As for right now? I thank you for continuing to support community web clients (even when some community members aren't always the nicest, including my self historically) and platforms outside Chrome.

It is so rare now a days.

**Comment by iliajie** [comment]
> would be to offer a `nojs=1` query argument that would allow you to login

It wouldn't be possible to do it for Authentic, although Gray Framed theme is already pretty JavaScript independent. I will look into making navigation to work in Gray theme without JavaScript.

**Comment by iliajie** [comment]
I have removed from Gray Framed Theme JavaScript dependency and switched it to use a new, simple and very nice HTML only accordions in navigation menu .. so, navigation will be possible in browsers with disabled JavaScript.

**Comment by mattatobin** [comment]
Well I didn't want to assume your plans for the simpler themes. This is fantastic news. Maybe I should look into doing some web design work. Maybe I can replicate an HTML-only Authentic style and offer it as a add-on theme along with a few more styles.

I AM very good at style replication using more primitive markup. Skinning in general needs to make a come back in a major way. Anyway, sorry for all the off-topic. Thanks again for being awesome, hopefully I can contribute something back in time.

**Comment by iliajie** [comment]
You are welcome. Although, I think that there are a very few users which have their JavaScript disabled.

**Comment by SlySven** [comment]
> You are welcome. Although, I think that there are a very few users which have their JavaScript disabled.

Maybe not disabled per se but being very selective about where it comes from or what it does - just think about all the browser "add-ons" that are around trying to selectively limit that javascript... :astonished:

**Comment by mattatobin** [comment]
Just keep in mind that alternatively evolved forks of classical mozilla technologies retain not only the ability to disable javascript globally but with various mechanisms provided, extensions such as those used by content blockers or by instructing the xul browser element in question to disable js for that instance..

That is very attractive to a more than trivial amount of a well defined subset of users. Not me.. But JS bustages are why fallbacks remain important.
