### ISSUE TITLE
Webmin module Cyrus IMAPd 1.6.8

### ISSUE THREAD

**Issue by ITfee** [webmin/webmin#1803]
I use this Cyrus IMAPd 1.6.8 module from Roberto Tecchio in Webmin 1.990:
https://www.webmin.com/cgi-bin/search_third.cgi?search=cyrus%20imapd

In general the module is still working, but it is buggy:

- The mailbox tree /webmin/cyrus-imapd/mailbox.cgi is not showing up anymore
- The information given for single user under /webmin/cyrus-imapd/mbox_info.cgi?mbox=user/username is not correct anymore. Size of the mailbox is just showing the size of the inbox, but not of the complete mailbox.

Can this be fixed?

**Comment by jcameron** [comment]
You'd have to report this to the author of that module, sorry..

**Comment by ITfee** [comment]
I can't find his contact on his web page: http://www.tecchio.net/webmin/cyrus/
How can I report the issue to the author?

**Comment by chris001** [comment]
@ITfee 
In the file `BUGS`:
```
to report a bug:

- subscribe to my dedicated forum, at http://www.tecchio.net/forum.php
(PREFERRED)
- **email me at roberto@tecchio.net**

please send me at least the following details when reporting a bug:

- your system/distribution
- version of this module
- version of hylafax  ( / cyryus / webmin )

patches are always welcome :-)
```

**Comment by ITfee** [comment]
I've contacted the developer, he will not continue developing this Webmin module:

> "I'm sorry. I stopped developing that module since 2018"
