### ISSUE TITLE
after updating to 2.010 terminal not working, status 503

### ISSUE THREAD

**Issue by starkapandan** [webmin/webmin#1804]
hi, after updating to latest version the terminal(full screen one) does not work. Going to tools->commandshell works, but going to tools->terminal says "connecting" with 503 error. Ensured that this was not caused by reverseproxy, going into the machine and going to localhost:10000 has the same issue. any idea whats going on?

**Comment by iliajie** [comment]
Hello,

What is your actual Webmin configuration set in `miniserv.conf` and `config`? What is your reverse proxy configuration?

**Comment by starkapandan** [comment]
minserv.conf:`port=10000
addtype_cgi=internal/cgi
realm=Webmin Server
logfile=/var/webmin/miniserv.log
errorlog=/var/webmin/miniserv.error
pidfile=/var/webmin/miniserv.pid
logtime=168
ssl=0
no_ssl2=1
no_ssl3=1
no_tls1=1
no_tls1_1=1
ssl_honorcipherorder=1
no_sslcompression=1
env_WEBMIN_CONFIG=/etc/webmin
env_WEBMIN_VAR=/var/webmin
atboot=1
logout=/etc/webmin/logout-flag
listen=10000
denyfile=\.pl$
log=1
blockhost_failures=5
blockhost_time=60
syslog=1
ipv6=1
session=1
premodules=WebminCore
userfile=/etc/webmin/miniserv.users
keyfile=/etc/webmin/miniserv.pem
passwd_file=/etc/shadow
passwd_uindex=0
passwd_pindex=1
passwd_cindex=2
passwd_mindex=4
passwd_mode=0
preroot=authentic-theme
passdelay=1
login_script=/etc/webmin/login.pl
failed_script=/etc/webmin/failed.pl
logout_script=/etc/webmin/logout.pl
cipher_list_def=1
sudo=1
error_handler_403=403.cgi
error_handler_401=401.cgi
error_handler_404=404.cgi
nolog=\/stats\.cgi\?xhr\-stats\=general
root=/usr/share/webmin
mimetypes=/usr/share/webmin/mime.types
server=MiniServ/2.010
websockets_/xterm/ws-555=host=127.0.0.1 port=555 wspath=/ user=root time=1670009446
websockets_/xterm/ws-556=host=127.0.0.1 port=556 wspath=/ user=root time=1670009468
websockets_/xterm/ws-557=host=127.0.0.1 port=557 wspath=/ user=root time=1670009499
websockets_/xterm/ws-558=host=127.0.0.1 port=558 wspath=/ user=root time=1670012070
websockets_/xterm/ws-559=host=127.0.0.1 port=559 wspath=/ user=root time=1670012116
websockets_/xterm/ws-560=host=127.0.0.1 port=560 wspath=/ user=root time=1670012395
websockets_/xterm/ws-561=host=127.0.0.1 port=561 wspath=/ user=root time=1670012650
websockets_/xterm/ws-562=host=127.0.0.1 port=562 wspath=/ user=root time=1670012695
websockets_/xterm/ws-563=host=127.0.0.1 port=563 wspath=/ user=root time=1670012722
websockets_/xterm/ws-564=host=127.0.0.1 port=564 wspath=/ user=root time=1670012911
websockets_/xterm/ws-565=host=127.0.0.1 port=565 wspath=/ user=root time=1670012923
websockets_/xterm/ws-566=host=127.0.0.1 port=566 wspath=/ user=root time=1670013057
websockets_/xterm/ws-567=host=127.0.0.1 port=567 wspath=/ user=root time=1670013095
websockets_/xterm/ws-568=host=127.0.0.1 port=568 wspath=/ user=root time=1670013435
websockets_/xterm/ws-569=host=127.0.0.1 port=569 wspath=/ user=root time=1670013920
websockets_/xterm/ws-570=host=127.0.0.1 port=570 wspath=/ user=root time=1670013950
`

apache config:
`<VirtualHost *:443>
	ServerName webmin.internal.HOSTNAME.com

	<Location />
		ProxyPreserveHost on
		ProxyPass        http://localhost:10000/
		ProxyPassReverse http://localhost:10000/
	</Location>
    <Proxy *>
		AuthType Basic 
		AuthName "Internal" 
		AuthUserFile ${APACHE_WEB_SECRETS}/htaccess_passwords/Internal.htpasswd
		Require valid-user
    </Proxy>

	SSLEngine on
	SSLCertificateFile /etc/letsencrypt/live/HOSTNAME.com/fullchain.pem
	SSLCertificateKeyFile /etc/letsencrypt/live/HOSTNAME.com/privkey.pem
	Include /etc/letsencrypt/options-ssl-apache.conf
</VirtualHost>`

**Comment by iliajie** [comment]
I don't see how it can work for you as stand alone module and not as drop-down. It should fail in both cases.

Also, I don't see you proxying Websockets. You should use a balancer. It proxies both `http` and `ws` automatically, or setup Apache to proxy websockets as well.

And at the moment `ssl=0` mode won't work. Use SSL enabled proxy. Webmin 2.011 will fix that (working in non SSL).

**Comment by starkapandan** [comment]
![image](https://user-images.githubusercontent.com/46032536/205484513-f2a84083-068a-435f-90a4-e03061ce4bfa.png)
![image](https://user-images.githubusercontent.com/46032536/205484527-90fe5a47-ddb3-488b-aadf-5fae8d219bfc.png)

Im not familiar with balancers, will look into it, and ssl was set to false in webmin. My thought was that webmin used regular http, while using my proxy would force ssl for users accessing over the internet.

**Comment by starkapandan** [comment]
Hmm i checked into some guides only on how to setup reverse proxy for webmin, i can not find any that proxies websockets or similar, all seems to only proxy localhost:10000 and call it day?

**Comment by iliajie** [comment]
You should try something like:

```
 SSLProxyEngine on
<Proxy balancer://wm>
  BalancerMember https://127.0.0.1:10000
  SSLProxyCheckPeerName off
  SSLProxyCheckPeerCN off
  SSLProxyCheckPeerExpire off
  </Proxy>
ProxyPass / balancer://wm/
```

**Comment by iliajie** [comment]
Wait, sorry. You cannot use either `127.0.0.1` nor `localhost`. Use resolvable hostname, like `host1.dom1.com`.

**Comment by iliajie** [comment]
What you call Terminal now, in the past was Command Shell.

What error message do you get if you visit Tools / Terminal page? Also, what is getting logged to `/.tmp/webmin/ws-555.out` file?

Most likely some dependencies are missing.

Try this [devel package](https://ilia.engineer/webmin_2.010-10_all.deb). Perhaps, the issue you're having has already been fixed.

**Comment by starkapandan** [comment]
yeah the some form of dependecy issues make sense! will check!

**Comment by starkapandan** [comment]
I actually did not have the /.tmp/webmin/ws-555.out file at all, not even a file in whole system named ws-555.out? Checked all the webmin logs 
![image](https://user-images.githubusercontent.com/46032536/205900152-d79f6ac2-2059-4424-920d-149d01e17c39.png)

Nothing of interest there either, but indeed a missing dependecy seems to be the case, will continue digging further in the logs. I sadly dont have a separate dev/prod environments but running everything directly in production atm therefore installing canary and below packages not fully tested to ensure stability, especially for powertools such as webmin where one bug could corrupt the server would indeed by a last resort in my case :( But thats awesome news though new versions are on the way! will wait for the next version (if i can't find the missing package), if that doesn't fix it will try out the developer packages as a last resort!

**Comment by starkapandan** [comment]
hmm seemed to have tracked down the issue, when webmin runs in http mode it fails, but if i try to run in https then it works(not apache proxy) but just https://localhost:10000 instead of http://localhost:10000

Error i recieved was: 
Undefined subroutine &Net::SSLeay::CTX_new called at /usr/share/webmin/miniserv.pl line 4584.

It seems that the miniserv is trying to call some form of method through ssl, when not using it which might be the reason its crashing.

So enabling ssl on webmin and then proxying apache to https://localhost:10000 seems to solve this issue.
My only wondering is, isn't it unneccesary to use ssl for a localhost server that none is able to reach anyways? i am always adding ssl through the apache proxy, so i guess it's double ssl layers now, seems overkill and potential performance slowdown?

**Comment by iliajie** [comment]
> My only wondering is, isn't it unneccesary to use ssl for a localhost server that none is able to reach anyways? 

Any _root_ capable processes/apps still can read local network traffics. I would suggest to always use SSL, although it may not be strictly necessary inside the same host.

> i am always adding ssl through the apache proxy, so i guess it's double ssl layers now, seems overkill and potential performance slowdown?

Performance impact is neglectable.

Have you tried the devel package mentioned in the link above? It makes it work in non SSL mode too..

**Comment by starkapandan** [comment]
Got out another laptop install dev package, that seemed to work indeed!
Thats good suggestion, will enable ssl asap then!

**Comment by starkapandan** [comment]
This issue can then be closed as the reason is clear and fixed in upcoming version!
