### ISSUE TITLE
Custom commands input fields alignment issue for users without permission to create new commands

### ISSUE THREAD

**Issue by SugoiDev** [webmin/webmin#1809]
Running Webmin 2.010 on Ubuntu Linux 22.04.1, installed via apt after using [setup-repos.sh](https://github.com/webmin/webmin/blob/master/setup-repos.sh)

Logging in with an user for which the "create new custom command" privilege has been disabled will break the layout of the custom commands module.

---

How it looks if we disable the "create new custom command"

![image](https://user-images.githubusercontent.com/7355630/207972167-4187f8a9-39eb-4d15-8d3f-cc32e1f9aa17.png)

Normal

![image](https://user-images.githubusercontent.com/7355630/207974904-41445d14-7377-47cf-ab22-b5d7bc00d8eb.png)

**Comment by jcameron** [comment]
Does this still happen if you select a different theme in Webmin (at Webmin -> Change Language and Theme), like the older "Frame Theme" ?

**Comment by SugoiDev** [comment]
Hi, thanks for looking into it.

The issue only happens with the "Authentic Theme". The legacy and framed themes work as expected.

![image](https://user-images.githubusercontent.com/7355630/208091513-aa58fef7-cd86-438e-90de-659bc5bc5e2d.png)


![image](https://user-images.githubusercontent.com/7355630/208091586-ae2d2dc7-64db-410f-bf96-4d2736bb33ae.png)

**Comment by iliajie** [comment]
Hello,

Thanks. We will fix this bug in the next Webmin release.
