### ISSUE TITLE
Usermin MySQL Database module,  returns error, when using MariaDB

### ISSUE THREAD

**Issue by qooob** [webmin/webmin#181]
https://github.com/webmin/webmin/issues/new#Jamie, hi!

It's been there for as long as I can remember, just didn't have chance to report it.
If you go to Usermin->MySQL Database it returns an error, in case MariaDB is used:

```
The MySQL client program /usr/bin/mysql does not appear to be the correct version. Webmin only supports MySQL versions 3 and above.
The command /usr/bin/mysql -V returned :

/usr/bin/mysql  Ver 15.1 Distrib 10.0.11-MariaDB, for Linux (x86_64) using readline 5.1
```

**Comment by jcameron** [comment]
Are you running Webmin 1.730 there? It should have fixed this issue..

**Comment by qooob** [comment]
Yes. It's in Usermin.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by jcameron** [comment]
In that case, which Usermin version are  you running?

**Comment by qooob** [comment]
All is the latest .... x40

**Comment by jcameron** [comment]
Ok, I see the bug now - Usermin wasn't updated to handle MariaDB like Webmin was. This will be fixed in the next release (and is fixed by the commit above).

**Comment by qooob** [comment]
Alright, thank you! The fix is working now.
