### ISSUE TITLE
BIND does not reload dynamic reverse zone if changed via forward entry

### ISSUE THREAD

**Issue by bsiege** [webmin/webmin#1810]
Forward and Reverse Zone are dynamic.
Edit some (IPv6) hostname and set "Update Reverse yes" Name is updated and active immediate because it is dynamic.
Reverse is updated correctly but not activated. Direct reload not possible because "dynamic Zone"
Open some entry in reverse zone and click save, then Zone is actual...

**Comment by jcameron** [comment]
Thanks for pointing this out - we'll fix it in the 2.011 Webmin release.
