### ISSUE TITLE
Starting without systemd on Linux?

### ISSUE THREAD

**Issue by GamePlayer-8** [webmin/webmin#1811]
Good evening,

Is there a way to start Webmin without systemd?

**Comment by GamePlayer-8** [comment]
Alr, figured out that `webmin-init` is a file to boot the Webmin up.
Although, why installer can't make a symlink to that file in `/usr/bin`?

**Comment by iliajie** [comment]
> Is there a way to start Webmin without systemd?

Historically, it was always possible to start/stop/restart using `/etc/webmin/start` or `/etc/webmin/stop` or `/etc/webmin/restart` commands. Use that instead on systems without `systemd`.

**Comment by GamePlayer-8** [comment]
Actually `/etc/webmin/start` command is pointing at `systemd` command:
```shell
#!/bin/sh
/usr/bin/systemctl start webmin
```

**Comment by iliajie** [comment]
That means your system has `systemd`? What is the output of `systemctl` command on your system? What is your OS and version actually?

**Comment by GamePlayer-8** [comment]
It's Artix Linux with `OpenRC` init system.

I used Webmin tar.gz package from Official webmin page.

Webmin version: `2.010`

**Comment by GamePlayer-8** [comment]
`systemctl` says command not found.

**Comment by iliajie** [comment]
And how did you install it?

**Comment by GamePlayer-8** [comment]
As root:
```shell
tar -xvf <tar.gz file>
mv webmin-2.010 /usr/share/
cd /usr/share/webmin-2.010
sh setup.sh
```

**Comment by GamePlayer-8** [comment]
Everything went fine, but at the end sys, failed to start Webmin.

**Comment by iliajie** [comment]
That is confusing!

What is the output of `find / -not -path "./proc/*" -not -path "./run/*" -not -path "/snap/*" -name systemctl` command?

Either way, you can start Webmin on your system by using `/etc/webmin/.start-init` or `/etc/webmin/.stop-init` or `/etc/webmin/.restart-init` commands.

**Comment by GamePlayer-8** [comment]
`find / -not -path "./proc/*" -not -path "./run/*" -not -path "/snap/*" -name systemctl`:
```shell
/var/lib/containers/storage/overlay/c01c63c6823dd8a296c2134ea94d31121069f1c52f8f8789836bc7ea2e5cdc93/diff/usr/share/bash-completion/completions/systemctl
/var/lib/containers/storage/overlay/c01c63c6823dd8a296c2134ea94d31121069f1c52f8f8789836bc7ea2e5cdc93/diff/bin/systemctl
/var/lib/containers/storage/overlay/196bc049b8b12b2b23bed0441f3bc8bc07bb15657cd9ce734f1f007948f82451/diff/usr/bin/systemctl
/var/lib/containers/storage/overlay/196bc049b8b12b2b23bed0441f3bc8bc07bb15657cd9ce734f1f007948f82451/diff/usr/share/bash-completion/completions/systemctl
/var/lib/containers/storage/overlay/295d6a056bfd381abf9c462629066b0458373045a1dca7d13ef6128cb38c977e/diff/usr/share/bash-completion/completions/systemctl
/var/lib/containers/storage/overlay/295d6a056bfd381abf9c462629066b0458373045a1dca7d13ef6128cb38c977e/diff/bin/systemctl
/var/lib/containers/storage/overlay/3a347f671db0a5a00ce77d24a310cbd50e0523e83383ab41fbdd53e9e694a574/diff/usr/share/bash-completion/completions/systemctl
/var/lib/containers/storage/overlay/3a347f671db0a5a00ce77d24a310cbd50e0523e83383ab41fbdd53e9e694a574/diff/bin/systemctl

```

**Comment by iliajie** [comment]
The fix for you would be to symlink `/etc/webmin/{start|stop|restart}` with mentioned earlier `.{start|stop|restart}-init` commands.

**Comment by GamePlayer-8** [comment]
Yea, now Webmin started. I'll link it to OpenRC init.

**Comment by iliajie** [comment]
How did you install ArcLinux?

**Comment by GamePlayer-8** [comment]
Artix Linux? From ISO what's on [the official page](https://artixlinux.org)

**Comment by iliajie** [comment]
> Artix Linux? 

Oh, we don't support it yet. I will take a look..

**Comment by iliajie** [comment]
It seems that we don't support Arch Linux either. I think we just treat it as generic Linux distro.

By the way, I have installed Artix Linux and installed Webmin on it with no problem, and it created init scripts correctly too (not as for `systemd` system, i.e. running `/etc/webmin/start` worked just fine).

<img width="946" alt="image" src="https://user-images.githubusercontent.com/4426533/209552436-30ab4689-2d06-4749-be70-c5f0cb6e97c1.png">

**Comment by GamePlayer-8** [comment]
hmm, weird.
