### ISSUE TITLE
Failed to install standard module : Module samba requires Webmin version 2.010 or above

### ISSUE THREAD

**Issue by willhertz** [webmin/webmin#1814]
This is 
webmin 2.001 
under 
Virtualmin Version 7.5
installed from 
https://software.virtualmin.com/gpl/scripts/virtualmin-install.sh
script in fresh Ubuntu 22.04 on Jan 6th 2023.

Is there some way to access an older version of samba module?

**Comment by jcameron** [comment]
No, but you could upgrade Webmin buy installing the latest package from www.webmin.com/download.html

**Comment by willhertz** [comment]
Thanks gonna try.

Then it's safe to install the webmin standalone module regardless of being a virtualmin installation?

**Comment by jcameron** [comment]
Yes, it's the same package.

**Comment by willhertz** [comment]
Thanks for the great advice. Now Working flawless
