### ISSUE TITLE
BIND DNS rndc: 'freeze' failed: already frozen

### ISSUE THREAD

**Issue by burgandyit** [webmin/webmin#1815]
Attempting to update a zone file and usually have no issues. After updating the file, I would typically perform the following - 
rndc freeze
rndc reload
rndc thaw

After which all would work and be updated. However now after updating the file and going through the above commands I am met by the error - rndc: 'freeze' failed: already frozen and it simply won't go away. I have given it time and attempted to reload and thaw but it just remains frozen and won't update

**Comment by burgandyit** [comment]
Okay after performing a named service reload I am able to freeze/unfreeze however the CNAME record I am updating is giving me back 
rndc: 'reload' failed: CNAME and other data

**Comment by jcameron** [comment]
Seems like there's a problem with one of the CNAME records? What does the line in the zone file contain?

**Comment by burgandyit** [comment]
Thanks for your comment. We had a $ORIGIN line with blank space underneath followed by another $ORIGIN that was causing our issue. Once we removed the first $ORIGIN it removed the errors and allowed for us to reload the zone.

**Comment by jcameron** [comment]
Great!
