### ISSUE TITLE
Zone file parsing issue after rndc sync is run

### ISSUE THREAD

**Issue by elcfd** [webmin/webmin#1816]
Hi,

If I create a zone through webmin and add the following addresses the created zone file can be seen below:

```
$ttl 3600
whitetree.xyz.  IN      SOA     webmin.example.com. charlie.whitetree.xyz. (
                        2023011004
                        3600
                        600
                        1209600
                        3600 )
whitetree.xyz.  IN      NS      webmin.example.com.
test1.whitetree.xyz.    IN      A       172.10.0.10
test2.whitetree.xyz.    300000  IN      A       172.10.0.11
test3.whitetree.xyz.    IN      A       172.10.0.14
test4.whitetree.xyz.    180     IN      A       172.10.0.19
```
In the web gui the entries show up as expected with the correct ttl values.

I have setup rndc as well as dns keys to allow an ansible playbook to remotely update the zone using the ansible nsupdate module.

When I run this playbook against the server a journal file is created alongside the existing zone file as expected.

When I then click back into the zone in webmin gui the `rndc sync -clean` command is run as per https://github.com/webmin/webmin/issues/870

However, the address list in webmin now shows the ttl to all be default despite the fact that some of these were set to non default values before:

![Screenshot_2023-01-10_23-31-43](https://user-images.githubusercontent.com/48883749/211684343-e0464457-b43f-4afb-bbc6-f146d384d709.png)

Another look at the zone file shows that `rndc` has changed the format of the file:

```
$ORIGIN .
$TTL 3600       ; 1 hour
whitetree.xyz           IN SOA  webmin.example.com. charlie.whitetree.xyz. (
                                2023011005 ; serial
                                3600       ; refresh (1 hour)
                                600        ; retry (10 minutes)
                                1209600    ; expire (2 weeks)
                                3600       ; minimum (1 hour)
                                )
                        NS      webmin.example.com.
$ORIGIN whitetree.xyz.
ansible                 A       192.168.1.1
test1                   A       172.10.0.10
$TTL 300000     ; 3 days 11 hours 20 minutes
test2                   A       172.10.0.11
$TTL 3600       ; 1 hour
test3                   A       172.10.0.14
$TTL 180        ; 3 minutes
test4                   A       172.10.0.19
```

It seems that webmin is unable to parse the changed format in the zone file.

Environment Details
```
Ubuntu 22.04.1 LTS (jammy)
Webmin version 2.010
```

Many Thanks,

Charlie

**Comment by jcameron** [comment]
This is kind of intentional - Webmin doesn't show the TTL on those records because it's set separately from the record. I suppose we could show it in the records list, but it would be tricky to allow editing the TTL in this case because the $ttl line applies to all records following it..

**Comment by jcameron** [comment]
What I'll do for the next Webmin release is show the TTL set on each record and the default  from the zone file, so it's clear what TTL is being used in this case.

**Comment by elcfd** [comment]
Hi @jcameron,

Thank you for the prompt reply.

I have a bit more information which I think means that the commit pushed earlier isn't needed. As you already pointed out after `rndc sync` is run having webmin edit the new zone file format issues will occur.

Bind allows for a `masterfile-style full;` directive in the `named.conf`.

```
zone "whitetree.xyz" {
        type master;
        file "/var/lib/bind/whitetree.xyz.hosts";
        masterfile-style full;
        allow-update { key ansible; };
        };
```

This can be added to a particular zone or in the overall options section.

When I added this after running ansible and going back into the zone via the Webmin GUI the resulting zone file looks like this:

```
whitetree.xyz.                                3600 IN SOA       webmin.example.com. charlie.whitetree.xyz. 2023011103 3600 600 1209600 3600
whitetree.xyz.                                3600 IN NS        webmin.example.com.
ansible.whitetree.xyz.                        3600 IN A         192.168.0.14
test2.whitetree.xyz.                          30 IN A           172.10.0.19
test3.whitetree.xyz.                          3600 IN A         172.10.0.19
```

Brilliant - as this is in the format which Webmin can read and also edit.

The only remaining issue is that the `ttl` now are in number form as the `default` value is not recognised:

![Screenshot_2023-01-11_17-41-38](https://user-images.githubusercontent.com/48883749/211879436-2a06e1c0-0813-4c7a-93e6-47fcbe2769e4.png)

In the above screenshot `ansible.whitetree.xyz` and `test3.whitetree.xyz` should be `default` not the number `3600`.

If this could be fixed that would be great.

I think this is a more desirable solution which does not deviate from Webmin's current behaviour.

Thank you for you help with this.

Regards.

Charlie

**Comment by jcameron** [comment]
Yes, `masterfile-style full` seems like the best choice to preserve the zone file format. However, I will keep the current Webmin behavior of showing the effective TTL when listing records, as this covers the case where the zone file has been manually edited.
