### ISSUE TITLE
IPTables Activate at boot: Unable to load 21

### ISSUE THREAD

**Issue by hayden-t** [webmin/webmin#1818]
This is a weird one not expecting solved as prob specific to my install, and i got a work around.

Just leaving breadcrumb fro someone else, the error is generated by /net/debian-linux-lib.pl 

```
    sub modify_interface_def
    {
    my ($name, $addrfam, $method, $options, $mode, $file) = @_;
    $file ||= $network_interfaces_config;
    #error($file);
    # make a backup copy
    &copy_source_dest($file, $file."~");
    local *OLDCFGFILE, *NEWCFGFILE;
    &open_readfile(OLDCFGFILE, $file."~") ||
	    error("Unable to open $file");
    &lock_file($file);
```

which is being fed from 
```

local $pri = &get_primary_network_interface();
	 		
	local ($debpri) = grep { $_->[0] eq $pri->{'fullname'} }
			       &net::get_interface_defs();
	#error(@$debpri);
	@{$debpri->[3]} = grep {
			($_->[0] ne "pre-up" && $_->[0] ne "post-up") ||
			 $_->[1] !~ /^\S*ip${ipvx}tables/ } @{$debpri->[3]};
	
	#@$debpri[5] = '';	
	&net::modify_interface_def(@$debpri);
```

get_interface_defs() returns 

```
	push(@ret, [$name, $addrfam, $method, \@iface_options,
			    $file, $lnum]);
```

which doesnt line up arg wise with modify_interface_def

so not sure why
if i dump #error(@$debpri) i get (21 is the line number) but the args are in the wrong spot i think because one is missing

venet0:0inetstaticARRAY(0x562410c42a78)/etc/network/interfaces21

**Comment by hayden-t** [comment]
I followed this up  a bit more, it seems the 'static' bit being inserted by `local ($debpri) = grep { $_->[0] eq $pri->{'fullname'} }
			       &net::get_interface_defs();` is doing it the flow is like

```
push(@ret, [$name, $addrfam, $method, \@iface_options, $file, $lnum]);

loinetloopbackARRAY(0x56241181c390)/etc/network/interfaces6

venet0:0inetstaticARRAY(0x562410c42a78)/etc/network/interfaces21

($name, $addrfam, $method, $options, $mode, $file)
```

**Comment by iliajie** [comment]
Hello,

What is the content of `/etc/network/interfaces` file on your system? Also, what directory `/etc/network/` contains?

**Comment by hayden-t** [comment]
![image](https://user-images.githubusercontent.com/1000743/212645037-1a8a9fd5-2413-407a-bb11-2b2a61c26844.png)

```
# This configuration file is auto-generated.
# WARNING: Do not edit this file, otherwise your changes will be lost.
# Please edit template /etc/network/interfaces.template instead.
auto lo
iface lo inet loopback
# Auto generated venet0 interfaces
auto venet0
iface venet0 inet static
	address 127.0.0.1
	netmask 255.255.255.255
	broadcast 0.0.0.0
	up route add default dev venet0
iface venet0 inet6 static
	address ::2
	netmask 128
	up ip -6 r a default dev venet0
	up ip addr add 2a02:4780:2:430e::1/64 dev venet0
auto venet0:0
iface venet0:0 inet static
	address 45.80.152.179
	netmask 255.255.255.0
	post-up iptables-restore < /etc/iptables.up.rules

```

**Comment by hayden-t** [comment]
even though im able to get through the activate at boot button, and the radio saves between page reloads, my firewall rules are not restoring after reboot, and the toggle is reverting back to no

**Comment by iliajie** [comment]
Is this the new issue for you popped up with Webmin 2.011?

You can manually run `iptables-restore < /etc/iptables.up.rules` to restore them.

**Comment by hayden-t** [comment]
its a new install, had some issue, as its debian 11 running 4.19 kernel due to openvz limitations, so firewalld wouldnt run (not 100% sure why ) so uninstalled it and running iptables without it. not sure if the button never worked or something during my setup phase broke it. but could you see the way the params are getting mixed up...

**Comment by iliajie** [comment]
> but could you see the way the params are getting mixed up

I'm working on something else right now. I'll have a look a bit later or Jamie will. Thanks for reporting it.

> firewalld wouldnt run (not 100% sure why ) so uninstalled it and running iptables without it.

FirewallD is the front end for nf/iptables. I don't see how it may not work.

**Comment by hayden-t** [comment]
yeah it seems related to python nftables, but i get an error for iptables too

ERROR: 'python-nftables' failed: internal:0:0-0: Error: Could not process rule: No such file or directory
ERROR: '/usr/sbin/ebtables-restore --noflush' failed: ebtables-restore v1.8.7 (nf_tables): line 11: TABLE_ADD failed (No such file or directory): table nat - Google Search

**Comment by hayden-t** [comment]
I installed iptables-persistent package and it seems to have created the /etc/iptables folder so now webmin is saving my rules into there as well for it to use on startup.

**Comment by iliajie** [comment]
I'm glad to hear that it is working for you.

Has the problem been solved then?

**Comment by hayden-t** [comment]
Well its a work around, but the activate on boot button is still broken.

**Comment by iliajie** [comment]
If you go to Webmin Log page, right after you click activate on boot button, what does it log exactly?

**Comment by jcameron** [comment]
I looked into this, and the Webmin code is indeed incorrect  - we'll fix this in the next release.

**Comment by hayden-t** [comment]
ah neat, thanks !
