### ISSUE TITLE
Cannot start Webmin after upgrade to 2.011

### ISSUE THREAD

**Issue by pixel-paul** [webmin/webmin#1819]
Webmin version | 2.011
-- | --
Operating system from Webmin | CentOS Linux 8.5.2111
Virtualmin version | 7.5.gpl (GPL)

Server is an out of date CentOS Linux release 8.5.2111 server (it's not publicly accessible). 

I upgraded to Webmin 2.011 and now Webmin will not start:

```
# journalctl -xe
-- Unit webmin.service has begun starting up.
Jan 16 22:18:44 myserver.example.com webmin[2890423]: Webmin starting
```
```
# systemctl status webmin.service
● webmin.service - Webmin server daemon
   Loaded: loaded (/usr/lib/systemd/system/webmin.service; enabled; vendor preset: disabled)
   Active: activating (start) since Mon 2023-01-16 22:21:13 GMT; 2ms ago
Cntrl PID: 2890547 ((iserv.pl))
    Tasks: 0 (limit: 101405)
   Memory: 0B
   CGroup: /system.slice/webmin.service
           └─2890547 [(iserv.pl)]

Jan 16 22:21:13 myserver.example.com systemd[1]: Starting Webmin server daemon...
```

There are these errors in  `/var/webmin/miniserv.error`

`[16/Jan/2023:22:02:27 +0000] [192.168.0.10] / : Perl execution failed : Undefined subroutine &main::authentic called at /usr/libexec/webmin/authentic-theme/index.cgi line 12.`

**Comment by iliajie** [comment]
Hello,

That is an odd issue. Does it help if you run `/etc/webmin/restart-by-force-kill` command?

**Comment by pixel-paul** [comment]
`/etc/webmin/restart-by-force-kill` did the trick!

I didn't know about that command. 

Thanks!

Paul

**Comment by iliajie** [comment]
How did you upgrade Webmin? Using UI or SSH or ..? Also, from which version did you upgrade to 2.011?

**Comment by pixel-paul** [comment]
@iliaross I updated using the UI. 

I am unsure which version this server was running. Is this logged anywhere?

**Comment by iliajie** [comment]
> Is this logged anywhere?

Yes, it is logged using Webmin Action Log module.
