### ISSUE TITLE
Suggestion of dropping support for all non-UTF-8 languages/files

### ISSUE THREAD

**Issue by iliarostovtsev** [webmin/webmin#182]
Jamie, how about making all language files in Webmin/Usermin _UTF-8_ by default, without any _non-UTF-8_, like `EN`, `RU` or other. They all should be `EN.UTF-8`, `RU.UTF-8` and etc (and called just by name English, Russian, Polish ..)

It creates additional problems and has no practical usage in real-world situations, right?

Example:
https://github.com/qooob/authentic-theme/issues/64

**Comment by jcameron** [comment]
I guess this could be done for most languages - however, a few (like Chinese) still have another non-UTF8 encoding that is in common use ... and not all users may be able to switch.

**Comment by qooob** [comment]
You mean UTF-8 is not enough for some languages? Alright, then let it be any other it has to be. I just wanted to propose to drop more than one option, when choosing language. Contemporary browsers would support anyway encoding, right? It would be nice to have just English, Russian, Chinese and so on, instead of  (English (EN), English (UTF8)) and etc...

Is it possible?

**Comment by qooob** [comment]
Non-UTF8 should be dropped unless it's something like ZH_TW.BIG5. There is absolutely no reason (I might be wrong) to have  at the same time `EN` and `EN.UTF-8`, `EN_GB` and `EN_GB.UTF-8` and etc.

It's confusing, I guess. Is there any reason for us to ship it the old way? Could we just clean the things up to make it unambiguous?

**Comment by jcameron** [comment]
Only reason is to support old old browsers that can't handle UTF-8

**Comment by qooob** [comment]
I see. Alright then, if it's worth it.

**Comment by qooob** [comment]
Should we reconsider? It creates a lot of confusion?

**Comment by jcameron** [comment]
I'm still not entirely sure if it's worth it, since en.UTF-8 is already the default language for new installs. Maybe I could start by hiding other character sets in the UI before going all the way?

**Comment by qooob** [comment]
Aha, yes probably, as it sounds as a safe start.

But I need to take a look first at `edit_file.cgi` first, making sure the editor could simply keep initial encoding of the files. If do it, then there is no other reason for leaving non-UTF8, I suppose.

**Comment by iliarostovtsev** [comment]
Finally, Webmin 1.950+ has `utf-8` only encoding for all languages.
