### ISSUE TITLE
Debian (testing) kernel 6+ detected as Generic linux

### ISSUE THREAD

**Issue by damcko8888** [webmin/webmin#1820]
i have: 
 lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux bookworm/sid
Release:        n/a
Codename:       bookworm
kernel: 6.0.0-6-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.0.12-1 (2022-12-09) x86_64 GNU/Linux

after updating to kernel 6 webmin detects it as Generic linux...
all modules in server disappered excep SSH and Read user mail.
in "system" Software packages and Updates also disappered so packages updates are not shown in webmin Dashboard.

I tried to change config file from "generic-linux" to "debian-linux" but webmin still Shows :
"Operating system Generic Linux has been upgraded to version 6.0"
![Capture](https://user-images.githubusercontent.com/44280839/212869510-e9586d48-a46d-452c-80dd-278ad6b55f2f.PNG)

**Comment by jcameron** [comment]
Thanks, we'll fix this in the next Webmin release (version 2.012)
