### ISSUE TITLE
Improved exception handling: missing nfs-common

### ISSUE THREAD

**Issue by Sacha00Z** [webmin/webmin#1829]
If nfs-common is not installed, and you attempt to mount an nfs server using webmin "Disk and Network Filesystems", the error message is not helpful.

Instead of reporting a missing OS package, the error message suggests that the NFS directory could not be found on the server. This message suggests that the form field "nfs_dir" has an incorrect value.

**Operating system**
Ubuntu Linux 22.04.1

**Kernel and CPU**
Linux 5.15.0-58-generic on x86_64

Mounting an NFS v3 server (QNAP QTS)

**Comment by jcameron** [comment]
Is the `showmount` command missing when `nfs-common` is not installed?

**Comment by Sacha00Z** [comment]
Hmmm... It's hard to answer this properly without a decent test (Kubuntu 22.04.1 ships without nfs-common, but very well may have it included in the base distro). Anything I tell you now will be a guess.

According to [this site](https://packages.ubuntu.com/jammy/nfs-common), `showmount` is not included in nfs-common, so I guess it could be included in the base distro or installed as a dependency. Webmin was my first change to the base system on my last install, and that's the basis of my assumption. I'll try it out when do my next install, and let you know.

**Comment by jcameron** [comment]
I looked into this some more, and the real issue is that we don't handle the case where `showmount` is missing. I'll fix this in the next release ...
