### ISSUE TITLE
Dashboard reports Kernel upgrade to 6.1 while it's 6.1.x

### ISSUE THREAD

**Issue by GamePlayer-8** [webmin/webmin#1830]
Heyo,

There's a problem with a popup about upgrading Linux Kernel.
Says to upgrade Kernel to 6.1 while it's already 6.1.x.
Here's how it looks:
![image](https://user-images.githubusercontent.com/115881539/215711651-88cfa9e3-5908-47e6-86a8-de953fc88b39.png)
![image](https://user-images.githubusercontent.com/115881539/215711691-de2ccd13-749a-446d-8a87-8443d38c8ade.png)

Init System: OpenRC.
Linux Distribution: Artix Linux.

**Comment by iliajie** [comment]
Hello,

You can manually adjust it on `Webmin ⇾ Webmin Configuration: Operating System and Environment` page.

**Comment by GamePlayer-8** [comment]
Oh I see. The checkbox wasn't switched on.

Now the popup is gone, issue solved.
