### ISSUE TITLE
Webmin "spam" module: Replace whitelist/blacklist with welcomelist/blocklist - SpamAssassin 4.0

### ISSUE THREAD

**Issue by amishmm** [webmin/webmin#1832]
Recently (on 17 December 2022) Apache project released [SpamAssassin version 4.0](https://spamassassin.apache.org/news.html).

Also development of SpamAssassin v3.4 branch has been stopped since 12 April 2021 i.e. almost 2 years back.

One of the [major changes](http://svn.apache.org/repos/asf/spamassassin/trunk/UPGRADE) in SpamAssassin 4.0 was replacement of word "whitelist / WHITELIST" with word "welcomelist / WELCOMELIST" and replacement of word "blacklist / BLACKLIST" with word "blocklist / BLOCKLIST". Old "race/color based" words are now deprecated.

Change is applicable to both config files as well as SpamAssassin rule files.

So Webmin's "spam" module needs to be changed accordingly to implement the same.

PS: Old config (i.e. words whitelist/blacklist) will remain [acceptable till SpamAssassin v4.1.0](https://cwiki.apache.org/confluence/display/spamassassin/WelcomelistBlocklist).

**Comment by jcameron** [comment]
Hmmm ... I guess we'd need to check for both directives, and set the one that's actually in use in the config.

Do all 4.0 series versions support the new directive names?

**Comment by amishmm** [comment]
There is only one 4.0 series version currently. i.e. 4.0.0. And yes it supports new directive name. Because thats the version, the new directive names are introduced.

We need to check for SpamAssassin version and set the directive accordingly. If old directive is there and version is 4.0.0 then it should be renamed. (when the next time the config is saved)

Better and much easier/quicker option would be to have duplicate of "spam" module and call it "spam3" module which supports SpamAssassin 3.0.

Then make changes to existing "spam" module to replace "white with welcome" and "black with block".

The new "spam" module, will NOT work if it detects SpamAssasin version 4 and ask users either to upgrade or use spam3 module.

In future, when Apache discards SpamAssassin completely, we can simply remove "spam3" module.

**Comment by jcameron** [comment]
Actually there's no need for a while new module - I will just update the existing one to use these directives if running SpamAssassin 4.0 (unless the old ones are in use).

**Comment by amishmm** [comment]
The reason I was asking to replace "white with welcome" and "black with block" in whole code was to make webmin's own directives, used in webmin spam config file and language files to also use race/color neutral words.

Sooner or later Apache will stop supporting old v3 version anyway (development stopped in 2021) and also stop supporting old directives too. (I assume within a year)

And then minor confusion will start in User interface, when Webmin will be calling lists as say, "Auto Whitelist" but officially SpamAssassin will be calling the list as "Auto Welcomelist". Same for "Blacklist" and "Blocklist".

Even for person editing the code, he/she will have to keep that in mind that webmin and SpamAssassin uses different terms.

What I did is: (ofcourse it works only for v4 but its quick and instant fix)
```
# module code change
cd spam
sed -i -e 's/white/welcome/g' -e 's/black/block/g' -e 's/White/Welcome/g' -e 's/Black/Block/g' *.pl *.cgi config* defaultacl lang/*
find . -name '*white*' -exec rename white welcome '{}' \+

# local webmin spam config change
sed -i -e 's/white/welcome/g' -e 's/black/block/g' /etc/webmin/spam/*
```

And it works fine.

PS: Similar change needs to be done for spam module of usermin too.

**Comment by jcameron** [comment]
We could also update the UI to use the new words in SpamAssassin 4.0. However, I wouldn't update the code for a long time, as we still have to support older systems and older versions of SpamAssassin for the foreseeable future ...
