### ISSUE TITLE
setup-repos.sh not detect Linux mint 21 ID correct

### ISSUE THREAD

**Issue by antosim** [webmin/webmin#1834]
When executing the setup-repos.sh on Linux Mint 21, the ID_LIKE is not identified correct in the script and the setup fails. The ID_LIKE is set to ubuntu by the  _osid=$(echo "$osid" | sed 's/\s.*$//')_.
From the  /etc/os-release file: ID_LIKE="ubuntu debian" .

I modified the check **if [ "$osid" = "debian" ] ; then**  with
**if [ "$osid" = "debian" ] || [ "$osid" = "ubuntu" ] ; then**

and the setup worked.

**Comment by iliajie** [comment]
Alright, thanks for reporting it! We will fix it on the next Webmin release.
