### ISSUE TITLE
Webmin Module Upgrade, Individually

### ISSUE THREAD

**Issue by dpurnam** [webmin/webmin#1837]
Hello and thank you for keeping up this amazing GUI tool for managing linux servers, especially for noobs such as myself.

Is there a way to upgrade Webmin Modules for Ex. OpenSSH Server to the latest available release? I've been running into SSH access issues since quite a while and I wonder if staying up-to-date with latest available release of OpenSSH Server would also give us an added security benefit along with getting rid of deprecated function/calls within.

**Comment by jcameron** [comment]
Webmin modules, like for OpenSSH, are separate from the OpenSSH server itself. If there is a new version of the server available, you should see it listed in available package updates shown on the Dashboard page.

**Comment by dpurnam** [comment]
> Webmin modules, like for OpenSSH, are separate from the OpenSSH server itself. If there is a new version of the server available, you should see it listed in available package updates shown on the Dashboard page.

Thanks but that's precisely my point the current webmin release (2.x) doesn't have the OpenSSH module (SSH Server - OpenSSH_7.9) matching latest available OpenSSH Server (OpenSSH_9.x). 

So how would one upgrade such as Webmin module to latest available public release (not webmin release) while still maintaining the integrity within webmin, if possible?

**Comment by swelljoe** [comment]
You're misunderstanding. The Webmin module is _not_ OpenSSH.

If you want to upgrade OpenSSH, you do it using your system package manager. Webmin does not provide the services it manages, those come from your OS.

**Comment by dpurnam** [comment]
> does not provide the servic

Very well understood, thank you, both.

**Comment by dpurnam** [comment]
Well understood, thank you, both.

> You're misunderstanding. The Webmin module is _not_ OpenSSH.
> 
> If you want to upgrade OpenSSH, you do it using your system package manager. Webmin does not provide the services it manages, those come from your OS.
