### ISSUE TITLE
In Read User Mail, using report as spam function, get Permission Denied error

### ISSUE THREAD

**Issue by fallingrock** [webmin/webmin#184]
In Read User Mail, using report as spam function, get Permission Denied error ...

Reporting the selected messages to Razor and other SpamAssassin spam-blocking databases ..

Learned tokens from 1 message(s) (1 message(s) examined)

Failed to open temp file /var/spool/mail/sheldon1.del : Permission denied

Webmin version 1.730

/var/spool/mail is owned by root.mail and has 775 permissions.

**Comment by jcameron** [comment]
/var/spool/mail needs to be mode 777 so that users can write to it.

**Comment by sgrayban** [comment]
Actually I think its chmode 7777 to keep the gw from changing.

**Comment by fallingrock** [comment]
On 1/7/2015 3:55 PM, Jamie Cameron wrote:
> /var/spool/mail needs to be mode 777 so that users can write to it.

This has never been a problem in the past.  Only with the upgrade to 1.730 did it cause a problem.

My other systems have the same permissions on /var/spool/mail.

Also, I don't think users should be able to write to /var/spool/mail ... only to their personal mail file (which is owned by them).

david


-- 
IBM i on Power Systems: For when you can't afford to be out of business!

I'm riding a metric century (100 km / 62 miles) in the 2015 American Diabetes Association's Tour de Cure to raise money for diabetes research, education, advocacy, and awareness.  You can make a tax deductible donation to my ride by visiting http://email.diabetessucks.net.  My goal is $5500 but any amount is appreciated.

See where I get my donations from ... visit http://email.diabetessucks.net/mapdonations.php for an interactive map (it's a geeky thing).

**Comment by jcameron** [comment]
If users can't write to /var/spool/mail , how does email delivery to new users via procmail work then? Typically this is done with user's permissions.

**Comment by fallingrock** [comment]
On 1/7/2015 7:30 PM, Jamie Cameron wrote:
> If users can't write to /var/spool/mail , how does email delivery to
> new users via procmail work then? Typically this is done with user's
> permissions.

Correct me if I'm wrong ... but as long as users are owners of their mail files in /var/spool/mail, they have the necessary authority for mail to be processed.

My system doesn't have any problems running procmail or any other mail programs.

As I mentioned, this problem never manifest before 1.730 of webmin.

david


-- 
IBM i on Power Systems: For when you can't afford to be out of business!

I'm riding a metric century (100 km / 62 miles) in the 2015 American Diabetes Association's Tour de Cure to raise money for diabetes research, education, advocacy, and awareness.  You can make a tax deductible donation to my ride by visiting http://email.diabetessucks.net.  My goal is $5500 but any amount is appreciated.

See where I get my donations from ... visit http://email.diabetessucks.net/mapdonations.php for an interactive map (it's a geeky thing).

**Comment by jcameron** [comment]
You're right, this needs some fixing in Webmin..

**Comment by supportadl** [comment]
Hi !!
I've the same problem on my mail server. I receive this error while trying to delete an email into mailbox through Webmin.
Failed to open temp file /var/spool/mail/user_domain.it.del : Permission denied
Thanks.

**Comment by jcameron** [comment]
FYI, the latest development release of Webmin fixes this - see http://www.webmin.com/devel.html

**Comment by supportadl** [comment]
Hi. I already have version 1.730 of Webmin installed. I'm using also Virtualmin GPL 4.14.
On Webmin webpage I see this version: Webmin 1.730. Do I need to update manually to version 1.732?
Is it a stable version?
Or is it better to wait for the automatic update?
Thanks.

**Comment by jcameron** [comment]
You can upgrade to 1.732 to get the fix immediately, or you can wait for 1.740 to be officially released.

**Comment by supportadl** [comment]
Thanks a lot !
