### ISSUE TITLE
setup-repos.sh is not detecting Oracle Linux.

### ISSUE THREAD

**Issue by davicavalheiro** [webmin/webmin#1840]
I tried using **_setup-repos.sh_** on Oracle Linux 8.7, and the script is not working and is showing the following error message:

`Error: Unknown OS : fedora`

**Comment by iliajie** [comment]
Thanks for the heads up! You're right. Must be fixed in [this patch](https://github.com/webmin/webmin/issues/1840). Please give it a try.

**Comment by davicavalheiro** [comment]
Worked perfectly!

Thank you.
