### ISSUE TITLE
Reverse proxy under sub-directory got 401

### ISSUE THREAD

**Issue by 1-1-2** [webmin/webmin#1841]
Using a newly install webmin 2.013, I follow the instruction - [Can I run Webmin or Usermin behind reverse proxy?](https://github.com/webmin/webmin.com/blob/main/content/faq.md#can-i-run-webmin-or-usermin-behind-reverse-proxy)

With config file below:
```ini
# /etc/webmin/config
referers=my.domain
webprefix=/thewebmin
webprefixnoredir=1

# /etc/webmin/miniserv.conf
redirect_ssl=1
redirect_host=my.domain
redirect_prefix=/thewebmin
cookiepath=/thewebmin

# /etc/webmin/xterm/config
host=my.domain/thewebmin
```

> I see only login page without formatting and login does not work.
![image](https://user-images.githubusercontent.com/6775697/219585952-7858713f-a465-4f1b-8b46-0931b1d40187.png)
Originally posted by @Mimikoo in https://github.com/webmin/webmin/issues/1838#issuecomment-1434265599

Got status 200 without any data received in browser, while status 401 in miniserv.log
![image](https://user-images.githubusercontent.com/50569812/219868689-71004a03-e846-4c4f-8c63-1377c58e8456.png)

```ini
# /var/webmin/miniserv.log
"GET /thewebmin/ HTTP/1.1" 401 5009
"GET /thewebmin/unauthenticated/css/bundle.min.css?2013000009999999999 HTTP/1.1" 401 5009
"GET /thewebmin/unauthenticated/css/fonts-roboto.min.css?2013000009999999999 HTTP/1.1" 401 5009
"GET /thewebmin/unauthenticated/css/fonts-roboto.min.css?2013000009999999999 HTTP/1.1" 401 5009
```
----
With no sub-directory, everything works well:
```ini
# /etc/webmin/config
referers=my.domain

# /etc/webmin/miniserv.conf
redirect_ssl=1
redirect_host=my.domain

# /etc/webmin/xterm/config
host=my.domain
```
```ini
# /var/webmin/miniserv.log
"GET /thewebmin HTTP/1.1" 401 4926
"GET /unauthenticated/css/bundle.min.css?2013000009999999999 HTTP/1.1" 200 174146
"GET /unauthenticated/css/fonts-roboto.min.css?2013000009999999999 HTTP/1.1" 200 971
"GET /unauthenticated/fonts/KFOlCnqEu92Fr1MmEU9fBBc4.woff2 HTTP/1.1" 200 15920
"GET /unauthenticated/fonts/KFOmCnqEu92Fr1Mu4mxK.woff2 HTTP/1.1" 200 15688
"GET /unauthenticated/fonts/KFOkCnqEu92Fr1Mu51xIIzI.woff2 HTTP/1.1" 200 17304
"GET /unauthenticated/fonts/KFOlCnqEu92Fr1MmSU5fBBc4.woff2 HTTP/1.1" 200 15732
"GET /images/favicons/webmin/favicon-32x32.png HTTP/1.1" 200 1787
"GET /service-worker.js HTTP/1.1" 401 4926
```
Did i miss anything?
Best regards.

**Comment by 1-1-2** [comment]
For those who are planning to use caddy v2, and not so familiar with nginx. (like me)

[This line](https://github.com/webmin/webmin.com/blob/140a49589189c21565fb10ce2c3b0ab75209ed7f/content/faq.md?plain=1#L162) in Nginx configuration:
>        proxy_pass https://localhost:10000/;

The **proxy_pass** with `/` at the very end, means `handle_path` in Caddyfile.

---

So the lines added to config files should be:
```ini
# /etc/webmin/config
referers=your.domain
webprefix=/thewebmin
webprefixnoredir=1

# /etc/webmin/miniserv.conf
redirect_ssl=1
redirect_host=your.domain
redirect_prefix=/thewebmin
cookiepath=/thewebmin

# /etc/webmin/xterm/config
host=your.domain/thewebmin
```

In Caddyfile:
```
your.domain {
    handle_path /thewebmin/* {
        reverse_proxy localhost:10000 {
            transport http {
                read_buffer 0
                write_buffer 0
                tls_insecure_skip_verify
                versions 1.1
            }
        }
    }
}
```

**Comment by iliajie** [comment]
Thank you for sharing this! I hope it will be useful for Caddy users!
