### ISSUE TITLE
module toggle from Virtualmin to Webmin has wrong colors/highlight

### ISSUE THREAD

**Issue by verne-wv** [webmin/webmin#1845]
In the newly renamed Frame Theme (used to be called Gray I believe), in left.cgi I think, somewhere is the code (maybe its CSS code) that changes the color of the words Virtualmin/Webmin as you toggle from one to the other.

In the old Virtualmin Framed Theme, the blue color one is the one NOT currently in use, and the black color one is the current environment --- aka does the left menu have Webmin items or Virtualmin items.  The blue color follows the very common webpage html usage where a live link is in blue.

My test system that I just updated today says in theme.info this is v2.013

**Comment by verne-wv** [comment]
It may take me days or weeks to tweak it myself, so if its easy to make a custom edit or theme extension, I would love to have pointers as to the exact thing to change to go back to the old behavior.

Also I believe the older Virtualmin Framed Theme did it the 'older way' for .... many many years   :-)

or ... what about some other color or highlighting (font size change?) or marking of some sort to indicate which is the 'active' side of things?   Of course the new Authentic Theme handles this nicely by having the entire left panel have a background of blue, so having the upper 'block' also have a background of blue (to match the lower section) makes it clear which module is the active one.   For other readers here I want to mention that Authentic has the words/text in white (or faded white) all the time.

This might be another reason for me to move away from the Framed themes to Authentic  :-)   I keep looking for something I do in Framed that I cannot find in Authentic, or just don't know how to do in Authentic.   I must say, I do like the theme extension that Authentic has -- not sure if Framed can pull in custom CSS (or even needs to) like Authentic can.

**Comment by iliajie** [comment]
> Also I believe the older Virtualmin Framed Theme did it the 'older way' for .... many many years :-) And in this older presentation style (mostly text, some colored, all on a white background), I would respectfully disagree --- the colored item does not (to me) represent the selected item.

Alright, I agree actually. I will fix that tomorrow!

> For other readers here I want to mention that Authentic has the words/text in white (or faded white) all the time.

Could you elaborate on this please?

> Not sure if Framed can pull in custom CSS (or even needs to) like Authentic can.

It actually can but it's just easier to use Authentic. It has quite a lot of improvements.

**Comment by verne-wv** [comment]
regarding the text in Authentic, I was just trying to make the comparison of general styles of presentation --- Authentic has WEBMIN and VIRTUALMIN in white all the time, but changes the background of the surrounding box to indicate which is the active module, and by extension the inactive 'area' is clickable.   Whereas in Frame the words themselves change color and the background for both areas/boxes remains white all the time.

p.s. if I had CLOUD, would I see a 3rd item at the top?

**Comment by iliajie** [comment]
> if I had CLOUD, would I see a 3rd item at the top?

If you had Cloudmin installed? If, so the answer is _yes_.

**Comment by iliajie** [comment]
This will be fixed on the next Webmin release.
