### ISSUE TITLE
2.020 Debian version has a LOT of new dependancies 

### ISSUE THREAD

**Issue by superian** [webmin/webmin#1858]
Twenty-something previously unrequired Perl packages are installed when upgrading from version 2.013 to 2.020

Is this deliberate?

I can't see anything obvious in the release notes that would need this.

**Comment by iliajie** [comment]
Hello,

This is expected as we added locale support and it installs recommended packages (i.e. `libdatetime-perl`, `libdatetime-timezone-perl`, `libdatetime-locale-perl` and `libtime-piece-perl`) and its dependencies will be installed.

So, this is all expected.

**Comment by swelljoe** [comment]
They are Recommends: not Depends:, and I don't think four new Perl modules is really "a lot"). If you don't want them, nothing is forcing it (Recommends are soft dependencies). And, they have been added for proper time zone/locale support. And, yes, it is intentional.

**Comment by superian** [comment]
Ah, OK. As normally just webmin itself is downloaded it made me wonder to the point that I was comparing files and checking the release notes to see if they said anything about the jump in version number and the number of packages involved.

Now I'm at home and not doing upgrades by phone, I can see that it was _forty seven_ perl packages that apt-get pulled in to get those four plus all their dependencies .

Ah, these servers do seem to pull in 'recommends' by default, but not 'suggests'.

So thank you, but next time something like this is done, perhaps you could mention it in the release notes?

**Comment by superian** [comment]
Closing

**Comment by EdwardDanchetzNI** [comment]
it appears that the additional Perl packages were added intentionally to support time and date locale functionality. These packages were recommended dependencies and not mandatory, so they were not required to be installed. It's recommended to check the release notes for any significant changes in the future.
