### ISSUE TITLE
Webmin 2.020 update not showing up on Ubuntu Server 22.04.2 LTS

### ISSUE THREAD

**Issue by tweek11** [webmin/webmin#1859]
Noticed yesterday that version 2.020 was released - However when checking for the update on my Ubuntu 22.04.2 LTS Server (64 Bit) it does not show up and indicates i currently have the latest version of 2.013.

When click on the Webmin Configuration -> Upgrade Webmin with the option "Latest version from www.webmin.com" it returns "Failed to upgrade from www.webmin.com : You are already running the latest version of Webmin "

Upon checking the box for "Upgrade even if new version is the same or older?" It returns the following screenshot attached below.

Sudo apt-get update from cli returns no available updates. 

Also apt-cache returned the following:
apt-cache policy webmin
webmin:
  Installed: 2.013
  Candidate: 2.013
  Version table:
 *** 2.013 100
        100 /var/lib/dpkg/status

So my question is as follows - Is the update/release for Webmin 2.020 on Ubuntu Server 22.04.2 being staggered out a few days to ensure there are not any major complications with it beforehand? That is regarding pushing the update available notification.

Thank you for your time and consideration.

![webmin](https://user-images.githubusercontent.com/91363983/225411776-ce4afdd5-2f8f-4d39-8df9-0423722b4551.jpg)

**Comment by jcameron** [comment]
@iliaross this new version check currently assumes that there is a link to webmin-2.020.tar.gz on www.webmin.com , but it doesn't appear to be there in the re-design. Can you take a look?

**Comment by iliajie** [comment]
Thanks for the heads-up. Fixed now!

**Comment by tweek11** [comment]
Still replicating the same thing on my end - Even rebooted the server on my end and tried again - Webmin GUI and even from cli still indicates version 2.013 is the latest version.

**Comment by iliajie** [comment]
It's cached. Also, it will take about 24 hours after Jamie rebuilds `webmin.com`.

**Comment by tweek11** [comment]
Appreciate the clarification and at the same time - All the work and effort you all put into such a great product.

**Comment by jcameron** [comment]
Ok I've updated the site ... please try again now.

**Comment by tweek11** [comment]
Same replication even after another reboot - no notification of pending update or ability to manually update. 

![Webmin2](https://user-images.githubusercontent.com/91363983/225466072-550c6c3c-1470-4481-b416-45c37612376c.jpg)

**Comment by iliajie** [comment]
Notifications for update will come a bit later. It's cached data. They using right side slider to clear the cache.

**Comment by tweek11** [comment]
No problem - I'll be patient and check on things later this evening or in the morning. I'm certainly in no hurry.
