### ISSUE TITLE
Gray-theme broke virtualmin interface.

### ISSUE THREAD

**Issue by darkshram** [webmin/webmin#186]
I was using the blue framed theme because gray framed theme always gave me lots troubles with virtualmin's interface. Now that blue-theme is gone and that was replaced with gray-theme, I have virtualmin's interface broken. Lots of buttons and features are gone. I can't add new virtual servers neither add new users to any existing virtualserver. Please, see images below. Is there something I am missing or doing wrong? Any chance to bring back blue-theme? I have 15 servers with this issue.

![image003](https://cloud.githubusercontent.com/assets/10327500/5785972/940cc7c0-9da3-11e4-9f0c-70ffc09f73dd.png)
![image010](https://cloud.githubusercontent.com/assets/10327500/5785973/940f0c92-9da3-11e4-9569-cb4b76f1533f.jpg)

**Comment by jcameron** [comment]
This is a bug in the gray theme, which will be fixed in the next release. The alternatives till then are :

1 - Apply this patch https://github.com/webmin/webmin/commit/3037f233ac30f58c28e86f21c5ab366357c3d883

2 - Use the Virtualmin Framed Theme, which has a much nicer UI for Virtualmin anyway.

**Comment by darkshram** [comment]
Thank you.

Because of the urgency of some customers (all of them need virtualmin), I had to repackage RPMs of webmin with a copy of the old blue framed theme and applied to all our servers (and shared package to other users with the same issue). I'll wait for next release, but after this issue we will have to do extensive test before upgrading our servers.

We made tests with the virtualmin theme but broke the whole webmin interface (can't remember the error, we were on a hurry and under a lot of presure). I will test it again tomorrow and document here (in a new issue) everything.

**Comment by jcameron** [comment]
Another option is to install the latest development version of Webmin, from http://www.webmin.com/devel.html

**Comment by darkshram** [comment]
You may keep this issue closed. Excuse for keep posting here. Where should I report virtual-server-theme issues? There is no Github repositoy for virtualmin. Should I open a new issue here? Error in virtual-server-theme is "Missing Content-Type Header". It makes Webmin completely unusable until editing miniserv.conf to change theme back.

Use of uninitialized value in string eq at /usr/libexec/webmin/gray-theme/left.cgi line 161.
Use of uninitialized value in concatenation (.) or string at /usr/libexec/webmin/gray-theme/left.cgi line 174.
Use of uninitialized value in string eq at /usr/libexec/webmin/gray-theme/left.cgi line 161.
Use of uninitialized value in string eq at /usr/libexec/webmin/gray-theme/left.cgi line 161.
Use of uninitialized value in string eq at /usr/libexec/webmin/gray-theme/left.cgi line 161.
Use of uninitialized value in string eq at /usr/libexec/webmin/gray-theme/left.cgi line 161.
[17/Jan/2015:00:26:50 -0600] Reloading configuration
[17/Jan/2015:00:26:52 -0600] [192.168.70.1] / : Missing Content-Type Header

**Comment by jcameron** [comment]
You can file a bug report at https://www.virtualmin.com/support.html .

**Comment by sgrayban** [comment]
Those errors say that the gray theme is still active and being used.. at least thats what I see.
