### ISSUE TITLE
Webmin 2.020 - Error — Perl execution failed - 

### ISSUE THREAD

**Issue by HelArcherix** [webmin/webmin#1861]
After upgrading to Webmin 2.020 i'm getting 

Error — Perl execution failed
Can't use an undefined value as an ARRAY reference at /usr/share/webmin/authentic-theme/authentic-lib.pl line 1667.
![Screenshot 2023-03-16 at 10-23-19 Dashboard — Webmin 2 020 on vmi554361 (Ubuntu Linux 20 04 5)](https://user-images.githubusercontent.com/44784335/225588124-378a904a-0eb0-4871-be8c-dcb06a32d465.png)

**Comment by iliajie** [comment]
Hello,

Try force restarting Webmin using `/etc/webmin/restart-by-force-kill` command.

If that doesn't help how did you upgrade Webmin exactly?

**Comment by iliajie** [comment]
> 2nd updated the theme

You don't really need to upgrade the theme because Webmin always includes the latest version of the theme.

> --> /etc/webmin/restart-by-force-kill --> Same result

Try reinstalling Webmin by SSH'ing to your server and running `apt-get install --reinstall webmin` command.

**Comment by HelArcherix** [comment]
Thaks, for the input. I'm not that tech-savvy

It's running Ubuntu 20.04. It basically popped up to upgrade to Webmin 2020, and I clicked on that. Returned to the main screen, in the lower left corner there was a button to update the theme, I clicked on it. After that i decided to restart the server and the error appears.

**Comment by iliajie** [comment]
Can you share your `/etc/webmin/config` and `/etc/webmin/miniserv.conf` files?

**Comment by daniktheboss** [comment]
I had the same thing, had to update perl. Try that.

**Comment by HelArcherix** [comment]
> Can you share your `/etc/webmin/config` and `/etc/webmin/miniserv.conf` files?

Config:
passwd_mindex=4
md5pass=0
referers_none=1
os_type=debian-linux
real_os_version=20.04.5
passwd_cindex=2
tempdelete_days=7
product=webmin
theme=authentic-theme
passwd_pindex=1
passwd_file=/etc/shadow
by_view=0
real_os_type=Ubuntu Linux
os_version=11.0
ld_env=LD_LIBRARY_PATH
find_pid_command=ps auwwwx | grep NAME | grep -v grep | awk '{ print $2 }'
path=/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin
lang=en
log=1
passwd_uindex=0
webprefix=
theme_root=authentic-theme

miniserv.conf:
port=10000
addtype_cgi=internal/cgi
realm=Webmin Server
logfile=/var/webmin/miniserv.log
errorlog=/var/webmin/miniserv.error
pidfile=/var/webmin/miniserv.pid
logtime=168
ssl=1
no_ssl2=1
no_ssl3=1
no_tls1=1
no_tls1_1=1
ssl_honorcipherorder=1
no_sslcompression=1
env_WEBMIN_CONFIG=/etc/webmin
env_WEBMIN_VAR=/var/webmin
atboot=1
logout=/etc/webmin/logout-flag
listen=10000
denyfile=\.pl$
log=1
blockhost_failures=5
blockhost_time=60
syslog=1
ipv6=1
session=1
premodules=WebminCore
userfile=/etc/webmin/miniserv.users
keyfile=/etc/webmin/miniserv.pem
passwd_file=/etc/shadow
passwd_uindex=0
passwd_pindex=1
passwd_cindex=2
passwd_mindex=4
passwd_mode=0
preroot=authentic-theme
passdelay=1
login_script=/etc/webmin/login.pl
failed_script=/etc/webmin/failed.pl
logout_script=/etc/webmin/logout.pl
cipher_list_def=1
sudo=1
error_handler_403=403.cgi
error_handler_404=404.cgi
error_handler_401=401.cgi
nolog=\/stats\.cgi\?xhr\-stats\=general
root=/usr/share/webmin
mimetypes=/usr/share/webmin/mime.types
server=MiniServ/2.020
logouttimes=
preroot_root=authentic-theme

**Comment by iliajie** [comment]
Thanks for sharing those, however I believe that the root cause of the initial issue is already fixed.

We will try to make a bug fix release of Webmin 2.021 as soon as possible.
