### ISSUE TITLE
where are the alerts / warnings stored

### ISSUE THREAD

**Issue by jpgpi250** [webmin/webmin#1862]
The message
```
Warning: Recent package updates (such as a new kernel version) require a reboot to be fully applied.
```
appears in webmin.

I'm using [needrestart](https://packages.debian.org/bullseye/needrestart) on debian, needrestart says there is no need to restart or reboot.

- What triggers this message (code)?
- Where can I find the messages, so I can possibly use / detect the warning, using a bash script?

Thanks for your time and effort.

**Comment by iliajie** [comment]
> What triggers this message (code)?

If your system is detected correctly (i.e. `debian-linux`) then we just check for `/var/run/reboot-required` file presence which indicates that reboot is needed.

> Where can I find the messages, so I can possibly use / detect the warning, using a bash script?

In _bash_ just test if mentioned file exists.


You can check if your OS is detected properly by Webmin using this command:

```
grep -Rs os_type= /etc/webmin
```

It should return something like this:

```
/etc/webmin/config:os_type=debian-linux
/etc/webmin/config:real_os_type=Debian Linux
```

**Comment by jpgpi250** [comment]
thanks

just checked, everything is exactly as you described.
