### ISSUE TITLE
Termina doesn't work

### ISSUE THREAD

**Issue by SylvainLegrand** [webmin/webmin#1867]
On Unbuntu 20.21
Webmin 2.020
Authentic theme 20.21

Since webmin 2 The terminal doesn't work anymore.
When I try to launch it, it turn with 'connexion..' message

**Comment by iliajie** [comment]
Hello,

What error do you get logged exactly in `/tmp/.webmin/ws-xxx.out` when trying to connect to the Terminal? Are there any errors printed in the browser's console? Are there any other specific errors printed to `/var/webmin/miniserv.error` log file?

Which Webmin version did you have installed previously, before upgrading to 2.020? Do you have Webmin placed behind reverse proxy? If so, what is the configuration of the proxy server?

**Comment by SylvainLegrand** [comment]
`/tmp/.webmin/ws-555.out` : `Running shell '/bin/bash -bash' with pid 1476043
listening on port 555
timeout waiting for connection at /usr/share/webmin/xterm/shellserver.pl line 103.`

I used Webmin for a while (maybe more than 5 years) and I upgrade it regularly.

To avoid unsafe port error on my web browser I use a reverse proxy on Apache 2.4 to manage Webmin access.
The proxy configurtion : `
	SSLProxyEngine On

	SSLProxyCheckPeerCN Off

	SSLProxyCheckPeerName Off

	SSLProxyVerify none

	ProxyPass / https://subdomain.mydomain.ovh:10080/

	ProxyPassReverse / https://subdomain.mydomain.ovh:10080/

	ProxyPreserveHost On`

**Comment by iliajie** [comment]
Please refer to this detailed manual on how to properly configure Apache to proxy WebSockets correctly:

https://webmin.com/faq/#can-i-run-webmin-or-usermin-behind-reverse-proxy
