### ISSUE TITLE
Grey and Blue framed themes mixed up

### ISSUE THREAD

**Issue by wolfbeast** [webmin/webmin#187]
One of the more recent Webmin updates started to cause confusion between 2 themes: the grey framed theme and the blue framed theme. In the theme selector, both are now called grey framed theme, and the actual styling is a mix of the two.

A brand new installation of webmin on a brand new CentOS 6 installation (installed via yum repo) displays the exact same problem I saw before after updating on an older machine. it worked properly before, so this is a recent regression (I think around the area of 1.6 -> 1.7)

**Comment by wolfbeast** [comment]
I realized that the mixed graphics were cached in my browser. So.. the blue framed theme was removed? Why? Of all the themes in Webmin, that was the one I always used...

**Comment by jcameron** [comment]
Yes, it was removed in the 1.730 release - the gray theme should be functionally identical though. The gray theme appearing twice in the theme list is a bug though, which will be fixed in the next release.

**Comment by sgrayban** [comment]
Why was the blue frame theme removed in the first place ? Shouldn't things like this be talked about before your guys simply remove major code and/or themes ?

**Comment by jcameron** [comment]
Because it hadn't been the default for new installs for many versions now, and updating it to use the new theme API would have been a fair bit of work. 

I'm curious as to why you preferred the blue theme though? It's CSS was pretty outdated..

**Comment by wolfbeast** [comment]
> I'm curious as to why you preferred the blue theme though? It's CSS was pretty outdated..

It's nice and **compact** and (to me) a lot **clearer**. Also, I like some **color** in my UIs when I can have it.
If you're talking about "outdated", some other themes should go first.

I tried manually installing the blue theme from the webmin website and that obviously is a disaster (probably because of the API changes) so please do find a way to get a more compact and clear theme a la blue framed back into Webmin, thanks.

**Comment by jcameron** [comment]
Ok, in response to popular demand I've made the blue theme available again, from http://download.webmin.com/download/modules/old-blue-theme-1.0.wbm.gz

**Comment by wolfbeast** [comment]
Fantastic!
I'll have to go through all my servers and install it, but it's worth the comfort.

**Comment by qooob** [comment]
@wolfbeast Try my Authentic Theme! ;)

**Comment by wolfbeast** [comment]
@iliaross No thanks. I looked at it and got rid of it in a big hurry. Absolutely terrible.

**Comment by qooob** [comment]
What is exactly seems terrible for you? :))

**Comment by wolfbeast** [comment]
Everything - but it's completely off-topic for this issue so if you want to discuss it please contact me through a different channel than this bugreport.

**Comment by qooob** [comment]
I will leave this up to you!

Thanks for the very exhaustive answer! :))
