### ISSUE TITLE
The system log viewer scrollbars are hidden

### ISSUE THREAD

**Issue by Stephano2000** [webmin/webmin#1876]
The System Logs Viewer's scrollbars are hidden.

Steps to reproduce:
- Syatem -> System Logs Viewer
- Click syslog's view button
- There are no scrollbars
- Scroll vertically with the mouse wheel or press repeatedly the down arrow key until the log scrolls up. The vertical scrollbars will appear (though very thin and faint)
- Shift scroll horizontally with the mouse wheel or press repeatedly the right arrow key until the log scrolls left. The horizontal scrollbars will appear (though very thin and faint)
- If the mouse isn't moved, the scrollbars will disappear again

**Comment by iliajie** [comment]
Hello,

Using the latest Webmin 2.021 I cannot see that the scrolbars are missing. Also, we don't hide scrollbars, your browser does and this is OS specific. I remember Firefox did that in some OSes. It's possible to disable it though.

Also, if that's not helpful, please provide a screenshot to better understand the problem.

**Comment by Stephano2000** [comment]
Firefox has a setting "Always Show Scrollbars". Enabling it always shows the scrollbars in Webmin and Virtualmin.
As far as I know, setting it to false (which is the default and preferred setting) hides the scrollbars, but shows them once the mouse is moved or the page is scrolled one way or the other. The latter (false) doesn't work with Webmin and Virtualmin.

![Screenshot from 2023-04-03 21-34-09](https://user-images.githubusercontent.com/3524476/229601077-46da2b32-5d75-44b9-a139-8cc2a3fa5cba.png)

**Comment by iliajie** [comment]
This is your OS specific, and we expect to have scroll bars _always_ displayed!

[Screen Recording 2023-04-04 at 11.09.32.webm](https://user-images.githubusercontent.com/4426533/229729824-c1320bdd-479c-4837-93e0-ee817f2f5bfb.webm)

**Comment by Stephano2000** [comment]
The culprit is probably one or a combination of OS, browser, and memo/scrollbox component.
