### ISSUE TITLE
Protected Web Directories - Unix Crypt Not working Properly

### ISSUE THREAD

**Issue by scarynightingale** [webmin/webmin#1877]
This was working before I updated to the latest version (Webmin 2.021).

Webmin > Tools > Protected Web Directories >

When I set up a new protected directory - adding users - the password created is not Unix crypt.

Example - username: test | password: test. 
Password encryption | Unix crypt

Using Webmin: 
test:057ab7f4613361d8f8304e8c0eb3300d8b2f1693 (does not work)
- I keep getting prompted to enter the login credentials.
- from apache log:  user test user: authentication failure for "*****": Password Mismatch

Using terminal: 
- htpasswd -nb test test
- test:$apr1$4CzmqwSn$QWv/mNJXQDCu1ijA5uicu1  (works no issues)

**Comment by jcameron** [comment]
Seems like we're using the system password hashing format for htpasswd files even when it's not supported, and we should be using only either `md5` or `crypt`.

Do you have digest encryption enabled for this protected directory? It should be shown in the directory list on the "Protected Web Directories" page.

**Comment by iliajie** [comment]
> Using Webmin:
> test:057ab7f4613361d8f8304e8c0eb3300d8b2f1693 (does not work)

That is an odd looking hash. What OS you're seeing it on? It works for me on all Alma, Rocky, Debian and Ubuntu.

> Seems like we're using the system password hashing format for htpasswd files even when it's not supported

We're supposed to be using system default hashing format, which supposed to work across Webmin in the same way. How is this possible that system password hashing format is not supported?

**Comment by scarynightingale** [comment]
It is a Mac server. Webmin was totally working before the upgrade. I have numerous directories setup - I have always used it without issue.  I have it set - and always have it set - to crypt. See screen shot. 

<img width="986" alt="Screenshot 2023-04-04 at 8 04 21 AM" src="https://user-images.githubusercontent.com/82041887/229773517-0d3542bc-291b-427e-9142-6bc7864d8264.png">

**Comment by iliajie** [comment]
If you go to **Users and Groups** module config, on the second page (i.e., **New user options**), what **Password encryption method** do you have selected there?

**Comment by iliajie** [comment]
Also, how does one of the old **user:hash** pair look like, which is expected to work on your system?

**Comment by iliajie** [comment]
Oh, that looks like the worst out of all - an old DES format. The solution for your situation would be using MD5, which would be an improvement anyway.

The reason why it doesn't work automatically for you anymore in **Unix crypt** mode is a question of missing Perl modules (most probably).

How old is your macOS system?

**Comment by iliajie** [comment]
Can you use `md5` in this particular case to work-around the problem?

**Comment by iliajie** [comment]
Try [this patch](https://github.com/webmin/webmin/commit/36f2e5d07742e720f42df0133a06f3551ed32657). It should work for you.

**Comment by scarynightingale** [comment]
> Try [this patch](https://github.com/webmin/webmin/commit/36f2e5d07742e720f42df0133a06f3551ed32657). It should work for you.

IT TOTALLY WORKED. Thank you! 

Will this be incorporated in newer versions? Thanks again - I sincerely appreciate it!

**Comment by iliajie** [comment]
What pair do you get generated, if you try switching to MD5?

**Comment by scarynightingale** [comment]
Username: test
Password: test

test:$1$80638447$Z.H9r3Kr/aBcWLaNeG5eP.

The Apache server keeps asking for my logion credentials... it doesn't work. I changed the realm to MD5 - then added the test user - then went to get the prompt - and it doesn't work. I could (and likely) be doing something wrong though...

**Comment by jcameron** [comment]
@iliaross maybe for `htpasswd` files we should force use of a limited set of hashing algorithms? After all, we don't know which ones Apache supports..

**Comment by iliajie** [comment]
Jamie, I don't this we should, because Apache doesn't care, as it uses system's `crypt()`, i.e. Apache supposed to recognize any hash that given system supports.

**Comment by jcameron** [comment]
Ok, makes sense.. I think your patch should fix this then.
