### ISSUE TITLE
Feature request: Add setting to disable DSN

### ISSUE THREAD

**Issue by Stephano2000** [webmin/webmin#1879]
References:
- https://github.com/virtualmin/virtualmin-gpl/issues/543
- https://www.postfix.org/postconf.5.html#smtpd_discard_ehlo_keywords
- https://www.postfix.org/postconf.5.html#smtpd_discard_ehlo_keyword_address_maps

This is related to disabling DNS due to spoofed spam generating backscatter.

Please add a text box in Webmin/Servers/Postfix Mail Server/SMTP Server Options:
"smtpd_discard_ehlo_keywords"
so that one can enter the required text, and the result (added to main.cf) will be like:
smtpd_discard_ehlo_keywords = silent-discard, dsn

A more detailed and demanding feature would be implementing smtpd_discard_ehlo_keyword_address_maps as well.

**Comment by jcameron** [comment]
Nice idea, I'll add an option for this ..
