### ISSUE TITLE
Navigation confusion in MySQL module

### ISSUE THREAD

**Issue by qooob** [webmin/webmin#188]
In case Virtualmin module is installed, click at one of `database name` -> there find a back button that will offer you to `Return to database list`, which will actually takes you to `Virtualmin module` and you end up in `Edit Databases` of `Virtualmin`.

__Eventually you end up in absolutely different module that you start from. It's not right.__

P.S. Mind blowing, fully reworked Authentic Theme 9.0.0 is going to be released within a week! :fireworks:  (..just wanted to share my happy feelings about it..)

**Comment by jcameron** [comment]
Yeah, that was an attempt to make the experience of editing a database nicer when coming in from Virtualmin .. but as you said, for non-Virtualmin users it doesn't make sense. I'll change it.
