### ISSUE TITLE
Correct Postfix Header Checks section

### ISSUE THREAD

**Issue by Stephano2000** [webmin/webmin#1880]
Reference: https://www.postfix.org/postconf.5.html#mime_header_checks

Webmin/Servers/Postfix Mail Server/Header Checks currently mentions "MIME header checking tables" but the setting is actually for "header checking tables", in the sense that it results in setting header_checks instead of mime_header_checks. Although by default, mime_header_checks defaults to $header_checks, but then the UI wording would be misleading.
So either:
- Mention that the setting is for all headers including MIME
or
- Have 2 different sections: one for "Header Checks" and one for "MIME Header Checks"

**Comment by jcameron** [comment]
Thanks for the suggestion - I've implemented this for the next Webmin release.
