### ISSUE TITLE
Drive temps not being reported on Dashboard - Data in smartctl -A or -a or -x

### ISSUE THREAD

**Issue by antonical** [webmin/webmin#1881]
See this post with Joe and his suggestion " Probably quickest to open an issue on github including the smartctl output for these drives that show the temperature. If the data is there, but not in an already recognized format, Webmin would need a minor code change."

[https://forum.virtualmin.com/t/hp-microserver-gen-8-clean-ubuntu-22-04-no-drive-temps-on-the-dashboard/120053/3](url)

Examples:
`sudo smartctl -a /dev/sdc
smartctl 7.2 2020-12-30 r5155 [x86_64-linux-5.15.0-69-generic] (local build)
Copyright (C) 2002-20, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF INFORMATION SECTION ===
Vendor:               IBM-ESXS
Product:              ST33000650SS
Revision:             BC3D
Compliance:           SPC-4
User Capacity:        3,000,592,982,016 bytes [3.00 TB]
Logical block size:   512 bytes
Formatted with type 2 protection
8 bytes of protection information per logical block
Rotation Rate:        7200 rpm
Form Factor:          3.5 inches
Logical Unit id:      0x5000c50056bb0b0f
Serial number:        Z2982BX10000C3471QYZ
Device type:          disk
Transport protocol:   SAS (SPL-3)
Local Time is:        Wed Apr  5 08:39:06 2023 BST
SMART support is:     Available - device has SMART capability.
SMART support is:     Enabled
Temperature Warning:  Enabled

=== START OF READ SMART DATA SECTION ===
SMART Health Status: OK

Current Drive Temperature:     38 C
Drive Trip Temperature:        65 C
`
`sudo smartctl -A /dev/sdc
smartctl 7.2 2020-12-30 r5155 [x86_64-linux-5.15.0-69-generic] (local build)
Copyright (C) 2002-20, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF READ SMART DATA SECTION ===
Current Drive Temperature:     38 C
Drive Trip Temperature:        65 C

Accumulated power on time, hours:minutes 5645:48
Elements in grown defect list: 0
`
As you can see smartctl is providing the raw data from the drive. Can this be added to Webmin please as being able to see the drive temps on the dashboard is important as this is a NAS.

If there is a small hack I can do in the interim to get them showing up that would be great.

Cheers
Spart

**Comment by iliajie** [comment]
Hey, Spart. Thanks for the heads up. Try [this patch](https://github.com/webmin/webmin/commit/364c37d75548612a8dd275e22c5c8c4f07db07b1), I think, it should work for you.

**Comment by antonical** [comment]
Hello ilia,

Yes, that worked after restarting webmin. Now all drive temps are reported as normal.

Thank you. I assume this will be in the next release.

Cheers
Spart
