### ISSUE TITLE
Disk Quotas - multiple table headers

### ISSUE THREAD

**Issue by qooob** [webmin/webmin#189]
It's invalid to have two `<thead></thead>` tags inside one `<table>`. When listing users/goups there are 2  `<thead>` and thus I can't run `dataTables` on this table because it's invalid.

Can this be fixed? Why not just put that first header outside of the table in a `div`?

**Comment by jcameron** [comment]
Yes, this can be fixed ... I'll change it in the next release.

**Comment by qooob** [comment]
Thanks!

**Comment by qooob** [comment]
Alright. Unfortunately it will not work.

Here is your code.

```
# Generate first header (with blocks and files)
...
...
#print &ui_columns_start(\@hcols, 100, 0, \@tds);   - I had to comment this as it CAN'T be the part of the table - could be put in a _div_, right above
```

```
# Generate second header (with used/soft/hard)
...
...
#print &ui_columns_start(\@hcols, 100, 0, \@tds); - Can't be that but rather:
print &ui_columns_header(\@hcols, \@tds);
```

Could you please fix it ASAP, so I could pull it and work with quotas sorting in my theme? Because that is the only way to get the proper table structure and make it work.

**Comment by jcameron** [comment]
So is this in list_users.cgi ? Because there is only one ui_columns_start call in that file... with no nesting.

**Comment by qooob** [comment]
I'm refering to the previous version, the on is in distro now. New version even worse. It pretends to be good and it's not. Header of the table should contain titles for columns, not something else. Can you please do it ASAP as I can release new version as it's dependent on how it's gonna look.

**Comment by qooob** [comment]
Dear, Jamie, sorry! You probably sick and tired of this already. It would be good to fix it but in case you **can't do it right now**, please revert to the previous version, the actual, current one (the one that is in Repos now). There were two `thead` elements and I could deal with this in my theme, whereas last commit you made, makes much for difficult. Besides the same thing with 2 `thead` is in Usermin. Let's just keep 2 `thead` for so far.. and in Webmin 2.0. we'll make it right but it's gonna be new theme anyway - so everyone is happy..

**Comment by jcameron** [comment]
I wonder if you could send me a version of the file (or a github patch) that brings it into the state  the works for you? I think I'm going in the wrong direction because I'm not sure what you are looking for ..

**Comment by qooob** [comment]
Alright. Let's me show it for you.

I will use as a starting point. the current list_users.cgi (1.730), not last commit.

You generate a structure in your output:

```HTML
<table>
   <thead>...</thead>
   <thead>...</thead>
   ...
<table>
```

The way it looks is on the screenshot.  It's wrong and it breaks both HTML and JavaScript dataTables.

![screenshot from 2015-03-04 10 03 46](https://cloud.githubusercontent.com/assets/4426533/6479420/13a17f90-c256-11e4-8fa4-5bbc6751198c.png)

Next, I made a script that takes the first `<thead>...</thead>` out of that table and make it a separate table with proper structure putting it above the initial one, so the structure of the table that we need also becomes valid and looks like this (this what you should produce with Perl):

```HTML
<table>
   <tbody>
      <tr>
       ...
       ...
      <th>Disk space (23.43 GB total / 19.96 GB free / 10.86 GB granted)</th>
      <th>Files (24576000 total / 24459782 free / 0 granted)</th>
    </tr>
  </tbody>
</table>
<table>
   <thead>...</thead>
    ...
<table>
```

Screenshot to see how it looks and that dataTables are initialized correctly:

![screenshot from 2015-03-04 10 12 12](https://cloud.githubusercontent.com/assets/4426533/6479486/04d19814-c257-11e4-9f30-76a8af564e58.png)


**What you could do?**
   1. Produce the structre where the first `thead` is taken above the initial table into a separate table.
   2. Leave it as it was *before last commit*. Last commit  makes it even worse. The way it was in version 1.730 is alright with the theme even though it's incorrect the theme engine will fix it.

**Comment by jcameron** [comment]
Ok, I see what you mean now - I didn't realize that I'd put that line showing the total disk size as a table header, which is really stupid! I have checked in a fix to make the table more normal.

**Comment by qooob** [comment]
Jamie, I checked what you've done! It's almost perfect, besides the fact that you can't put <table> inside of <p>. I checked with your theme and it works fine but it breaks my theme and needs _one_ tiny tiny fix, please check the screenshot first:

![screenshot from 2015-03-05 11 18 33](https://cloud.githubusercontent.com/assets/4426533/6501441/a4cd8da0-c329-11e4-914d-34058f7eeeac.png)

Could you please replace the part on line 70 (for users) and 69 (for groups) from 
`print "</b><p>\n";` 
to 
`print "</b><br>\n";`

Then it will be fine in either way (in both themes).

Thank you very much in advance for fixing it!

**Comment by jcameron** [comment]
Sure, I'll change  that now.

**Comment by qooob** [comment]
Thanks a lot!
