### ISSUE TITLE
Since I updated apt-get update & upgrade, tar.gz compression doesn't work anymore

### ISSUE THREAD

**Issue by Madriix** [webmin/webmin#1892]
Hi
Since I updated sudo apt-get update, sudo apt-get upgrade, tar.gz compression no longer works, the little blue popup is stuck at the bottom of the screen but it doesn't understand anything. Do you know why ?
Just before the update everything was working fine

I'm on Debian 11 and do sudo apt-get update and upgrade about 3 or 4 times a year
Regards

**Comment by iliajie** [comment]
Hello,

If you try to _tar_ something in the Terminal, does it work then? If not, what error do you see?

**Comment by Madriix** [comment]
The "tar" command works fine on the ssh terminal, it creates the .tar.gz fine.
Where could the problem come from?

**Comment by iliajie** [comment]
> Where could the problem come from?

The problem was introduced with [this](https://github.com/webmin/webmin/commit/f46cc45) patch.

Try this https://github.com/webmin/webmin/commit/14a07d49591b4fa37a1cc94d059dda27ddb858e5 fix.

**Comment by Madriix** [comment]
I looked in the /etc/webmin folder there is no file named "web-lib-funcs.pl". How to apply this patch?

**Comment by Madriix** [comment]
@iliaross I went to `"/usr/share/webmin"` and opened "web-lib-funcs.pl" changing line 330 to replace the line, restarted webmin and everything works now it's solved, thanks;

**Comment by iliajie** [comment]
Alright, good to know.
