### ISSUE TITLE
some keys broken in terminal window

### ISSUE THREAD

**Issue by dpark77** [webmin/webmin#1896]
As I recent updated to the latest version, noticed a little changes in terminal or shell window design.
There appears to be a problem though with nano editor.
Before the update, CTRL+w would prompt for options, but now it just closes my browser tab. I haven't checked other editors but CTRL+[key] functions seem no longer be working in browser.

**Comment by iliajie** [comment]
Hello,

Which browser you're seeing this issue in? Also, does `nano` screen has a focus (you can mouse click inside `nano` window to make sure it gets focused) before you're hitting those combos?

**Comment by chris001** [comment]
Same issue.  Firefox 113.  Click in the terminal, run `nano`, press `Ctrl+w` to search in `nano`, and it closed the FF browser tab!

**Comment by iliajie** [comment]
Are you on Windows 11?

Also, does this issue happen in Chrome (or other Chromium based browser, like Edge)?

**Comment by chris001** [comment]
Win 10.  Same issue in Edge Chromium, `Ctrl+w` happens to be the same command to close the Edge browser tab.

**Comment by iliajie** [comment]
I have given a deep look to this issue, and if you want to use `Ctrl+W` in `nano` you simply _cannot_ do this in web apps. `Ctrl+W` hotkey is a system hotkey and cannot be caught (prevented).

However, there are still some great alternatives to search in `nano` on Windows and Linux systems in web based terminal. The first would be is to simply use `F6` to call search dialog in `nano`. The other is just to replace `Ctrl` key press with double `Esc`, i.e. `Esc+Esc - W` would also show a search dialog in `nano`. 😉 

I hope that helps!

**Comment by chris001** [comment]
When the terminal is in focus, it probably makes sense to use the [beforeunload](https://developer.mozilla.org/en-US/docs/Web/Events/beforeunload) event to warn the user about leaving the page.  So it doesn't just close the browser tab.

**Comment by iliajie** [comment]
> When the terminal is in focus, it probably makes sense to use the [beforeunload](https://developer.mozilla.org/en-US/docs/Web/Events/beforeunload) event to warn the user about leaving the page. So `Ctrl+w` ("search" in nano editor) doesn't just close the browser tab.

Yeah, that may work. I'll have a look.

**Comment by swelljoe** [comment]
While I agree with the sentiment that doing stuff like this in a browser window is extremely suboptimal, some VNC software solves it by adding buttons for commonly used key combos that can't work in a browser. Other handle it with an entire soft keyboard that has latching control/alt keys.
