### ISSUE TITLE
Deprecated use of `pg_shadow`

### ISSUE THREAD

**Issue by devadattas** [webmin/webmin#1898]
Please use `pg_user` instead of `pg_shadow` as most modern versions of Postgres allow access to `pg_user` only.

https://github.com/webmin/webmin/blob/d1fe5d1bae6a4c15c8728f3bf84fb423118f3921/postgresql/newdb_form.cgi#L19

**Comment by devadattas** [comment]
Same here as well:

https://github.com/webmin/webmin/blob/d1fe5d1bae6a4c15c8728f3bf84fb423118f3921/postgresql/edit_grant.cgi#L42

The `get_pg_shadow_table` can be used from https://github.com/webmin/webmin/blob/d1fe5d1bae6a4c15c8728f3bf84fb423118f3921/postgresql/postgresql-lib.pl#LL1313C5-L1313C24 to resolve this.

**Comment by jcameron** [comment]
Which PostgreSQL version are you seeing this issue on?

**Comment by chris001** [comment]
Looks like [`pg_shadow` was removed from 9.5 and replaced with `pg_authid` in 8.1](https://pgpedia.info/p/pg_shadow-table.html).  Current stable is [15.2](https://www.postgresql.org/download/).
More [details and code how to fix](https://sourceforge.net/p/webadmin/bugs/4702/).

**Comment by jcameron** [comment]
OK, it looks like Webmin already knows about these different table names, but just wasn't using them on that page! This will be fixed in the next release..
