### ISSUE TITLE
Webmin 2.02105062143 does not recognize Debian Linux 12 properly

### ISSUE THREAD

**Issue by by** [webmin/webmin#1900]
When installing/updating webmin from git, it does not recognize Debian bookwork/12 properly on a Raspberry Pi 4, albeit lsb_release -a shows:
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 12 (bookworm)
Release:	12
Codename:	bookworm

**Comment by iliajie** [comment]
Hello,

What is the output of `cat /etc/os-release` and `cat /etc/debian_version` commands?

**Comment by iliajie** [comment]
I ran tests and latest Webmin works just fine with Debian 12 (including Virtualmin installer).

Does it work if you install a _.deb_ package instead of installing from source?

**Comment by by** [comment]
Thanks and it does run well but still displays Debian Linux 11 on the Raspberry Pi 4 64-bit.
`cat /etc/os-release` outputs
```
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
and `cat /etc/debian_version` shows
`12.0`

**Comment by iliajie** [comment]
Can I see the screenshot of the dashboard?

**Comment by by** [comment]
Sure, see attached.
![Image 07 05 23 at 18 16](https://user-images.githubusercontent.com/335425/236689615-09a950ec-7377-4d0e-964b-d05891b22adb.jpg)

**Comment by iliajie** [comment]
If you click **Force Refresh** system information button on the top right of the dashboard, does it then bring you an alert in the dashboard to update OS version?

**Comment by by** [comment]
No, it does not, I'm sorry!

**Comment by iliajie** [comment]
You can always manually adjust OS version from **Webmin Configuration** page.

**Comment by by** [comment]
Will do, thanks
