### ISSUE TITLE
wrong usage of local disk space in version 2.021

### ISSUE THREAD

**Issue by tsingkong** [webmin/webmin#1901]
I upgrade webmin from 2.020 to 2.021, and it shows wrong usage of local disk space. It looks like all mount points space are taken into total space, but only root mount point is taken into used space. as the following shows:
![webmin_bug](https://user-images.githubusercontent.com/2121913/236746731-44fc92eb-1b63-42dc-b9d6-3823a83610d0.png)

**Comment by jcameron** [comment]
Ok I see the bug that causes this ... it will be fixed in the next Webmin release by these commits : https://github.com/webmin/webmin/commit/41a7d61df4e539e4aa8e4d1bc5f63b95a5419be1 and https://github.com/webmin/webmin/commit/25e5b2f4fc24b4ede703133a1baba9d6c0a31943
