### ISSUE TITLE
Error while adding new mysql user

### ISSUE THREAD

**Issue by sanjeev0990** [webmin/webmin#1909]
getting error while adding new mysql user in webmin. Ubuntu server 22.04. Same error getting in virtualmin also. Please fix it

**Comment by jcameron** [comment]
What's the exact error message that you're getting?

**Comment by iliajie** [comment]
@sanjeev0990 Are you using MySQL or MariaDB with Ubuntu 22.04?

Also, is the problem that you created a MySQL/MariaDB user using Webmin, and then could not login with that user using console, i.e. `mysql -u newuser -p`, right? If so, if you go back to Webmin UI, click on newly created MySQL/MariaDB user and change password for it, does it work then?

**Comment by sanjeev0990** [comment]
I am getting this error with MariaDB in Webmin in Ubuntu server 22.04. Its annoying, i am getting this error and when I am checking the users then I am seeing user is created then why this error. :(

Failed to save user : SQL alter user &#39;dbtest-hello&#39;@&#39;&#39; with max_user_connections 0 failed : Operation ALTER USER failed for &#39;dbtest-hello&#39;@&#39;%&#39;

**Comment by sanjeev0990** [comment]
I am just trying to create a new database user. I am entering new database username, password and host to localhost and not giving any permission and hitting create button then I am getting the error. Its in mariadb. its working fine but when I run secure mysql installation then after that when i am trying to create the database user then i am getting the error. please fix it.

**Comment by iliajie** [comment]
> I am just trying to create a new database user. I am entering new database username, password and host to localhost and not giving any permission and hitting create button then I am getting the error. 

Could you provide a screenshot with an error message that pops up after you hit **Create** button?

**Comment by iliajie** [comment]
Nevermind, I also see this issue now!

**Comment by iliajie** [comment]
This patch https://github.com/webmin/webmin/commit/d33b1e2681542c52df4ce21e94a5349cda4eb80d will fix the issue you initially reported.

**Comment by iliajie** [comment]
fgj .:KSM|

**Comment by iliajie** [comment]
> Same error getting in virtualmin also.

Also, could you specify where it didn't work for you in Virtualmin exactly? At which page in Virtualmin you were trying to create MariaDB user which it didn't work for you?
