### ISSUE TITLE
&list_combined_system_info() doubles packages updates

### ISSUE THREAD

**Issue by qooob** [webmin/webmin#191]
In some case `&list_combined_system_info()` doubles _Package Updates_ information. It happens in [_Authentic Theme_](https://github.com/qooob/authentic-theme) and in _Virtualmin Framed Theme_

![screenshot from 2015-02-21 11 20 25](https://cloud.githubusercontent.com/assets/4426533/6313469/5ea43182-b9bd-11e4-98a4-dca542c08352.png)
![screenshot from 2015-02-21 11 20 51](https://cloud.githubusercontent.com/assets/4426533/6313470/5ea616c8-b9bd-11e4-8926-6a2af4b5be46.png)

**Comment by jcameron** [comment]
Ok, I see the bug that causes this - it happens if you have both Cloudmin and Virtualmin installed and accessible to the same user. I'll fix it in the next release.

**Comment by qooob** [comment]
Perfect, thanks. While you're here, could you tell me what the 3 value is for in Charts Array (that displays Quotas on System Information Page).

Example:

```
$VAR1 = { 'chart' => [ '1073741824', 110587904, 10125312 ],
$VAR1 = { 'chart' => [ '1073741824', 409600, 8192 ],
```

The numbers on the right of the bars are (in this case) 115.12 MB of 1024 MB and 408kB of 1024MB.

It's obvious how to count `%` . First is _Total_, second is _Used_ and what the _Third_ option is for?

**Comment by jcameron** [comment]
The 3rd value is usage by something else, in this case the size of the domain's databases. For a chart like this, the theme should render a "stacked" bar chart with two different colors.
