### ISSUE TITLE
PAM authentication not working

### ISSUE THREAD

**Issue by Talkabout** [webmin/webmin#1911]
Hi guys,

I am trying to figure out what the problem is on one of my servers, where webmin refuses to authenticate via PAM. It is not a configuration issue, as the exact same configuration works on another server AND if I force to use PAM via code, it also works.
Here are the details:

when starting webmin I get "PAM test failed - maybe /etc/pam.d/webmin does not exist". This is a "generic" error and does not give any reason why it doesn't work

I checked the code and tried to find the place where it fails. Actually everyhing is executed correctly. The only thing that fails is that "Authen::PAM" is NOT calling the "pam_conv_func" function. That is why this if block here:

![image](https://github.com/webmin/webmin/assets/10157917/e3c649db-2d5d-4fa3-bc22-2c7637574888)

goes into the "else" part and basically deactivates PAM completely.

I also checked the return value of
`$pamh->pam_authenticate();`
And also here the execution is successful (indicated by a return value 0)

Funny thing is: when I set
`$pam_conv_func_called = 1;`
hardcoded, all authentications with all users work perfectly fine.

On the other server, installed the same way, the conversion function is called correctly and there is no issue at all.

Any idea what can be missing on my second server so the "conversion" function defined for Authen::PAM is not called but all other parts seem to work fine? I am a little bit out of ideas, your help is much appreciated!

Thanks!

Bye

**Comment by Talkabout** [comment]
Ok, problem solved. It seems that the "pam_test_user" needs to be configured on that system. Not sure why on the other one it is not required, but adding "pam_test_user=test" to the miniserv.conf file now allows the users to login. Still a little bit weird, maybe somebody can commet on this behavior :)

**Comment by chris001** [comment]
[The code is here](https://github.com/webmin/webmin/commit/01da1d69e5d69ed023ebf62376fc996f31061a2a).

**Comment by Talkabout** [comment]
Thanks for the hint, it helped in determining the difference.

Server 1 has a root user WITH a password configured, meaning that root login is allowed. This works with webmin.

Server 2 has a root user WITHOUT password, which means I can switch to root but cannot login with root. This seems to be problematic with the PAM check implemented in webmin. Most likely as the login succeeds (root without password), the conversion function is not required to be called and webmin assumes PAM does not work.

2 possible solutions:
- give root a password
- change "pam_test_user" to something else than root

Bye

**Comment by jcameron** [comment]
On server 2, how are you switching to the root user? Is this with `sudo`, or just the `su` command?

**Comment by Talkabout** [comment]
Both ways work. The second one (su) works without providing a password. SSH login with root is disabled.

**Comment by jcameron** [comment]
In that case, you should be able to login to Webmin as any user who has permissions to `su` to root.

**Comment by Talkabout** [comment]
Not exactly. The "PAM" check in webmin simply fails if the login as root is possible without password (which seems to be the default setting in raspbian).
Not sure if setting the default test user for pam to "root" is a good idea. I'd suggest to take something more "cryptic" to avoid such coincidences. In any case for me setting the "pam_test_user" in config to "test" solved the issue, but other users having the same constallation might not be able to figure that out by themselves. A hint in the doc might be a good idea.

**Comment by jcameron** [comment]
Ah, I see now ... I didn't read the first comments in this ticket carefully enough.

The next release of Webmin will handle this case better by looking at the return value from `pam_authenticate` when testing if PAM works.
