### ISSUE TITLE
Hamburger menu not working on mobile device (iPhone)

### ISSUE THREAD

**Issue by jlrosssc** [webmin/webmin#1914]
I am running Webmin 2.021 with the Authentic 20.21 theme.  Everything works as expected on an iPad or computer but on an iPhone, the main screen appropriately detects and displays the information scaled for a mobile device, however, when I select the hamburger menu, the screen displays the menu and then immediately goes away.  I've tried this from Chrome and Firefox with the same result.  It will not allow changing to the various other menus since the selections hide.

**Comment by iliajie** [comment]
Hello,

Thanks for the heads up. This issue was fixed already.

https://github.com/webmin/webmin/issues/1870#issuecomment-1492681680
