### ISSUE TITLE
Unable to install Webmin due to GPG key import failure

### ISSUE THREAD

**Issue by khs-kks** [webmin/webmin#1919]
I am attempting to install Webmin on an AlmaLinux 9.2 system. During the installation process, I encountered an error related to the GPG key import. The detailed error message is as follows:

```
Webmin - noarch                                                                                                                        3.0 MB/s | 3.0 kB     00:00    
Importing GPG key 0xFF6ADD85:
 Userid     : "Webmin Developers <developers@webmin.com>"
 Fingerprint: B966 3227 39F9 8E2E 092E 69CF 28E1 1943 FF6A DD85
 From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-webmin-developers
warning: Signature not supported. Hash algorithm SHA1 not available.
Key import failed (code 2). Failing package is: webmin-2.021-1.noarch
 GPG Keys are configured as: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-webmin-developers
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: GPG check FAILED

```

It appears that the GPG key import process is failing due to the unavailability of the SHA1 hash algorithm. This prevents the installation of the Webmin package.

### **Steps to Reproduce:**

Run the command `dnf install webmin` on an AlmaLinux 9.2 system.
Confirm the error message mentioned above is displayed.

### **Expected Behavior:**

The Webmin package should be installed successfully without any GPG key import issues.

### **Actual Behavior:**

The GPG key import process fails with the error message "Key import failed (code 2). GPG check FAILED."

### **Environment:**

 - Operating System: AlmaLinux 9.2
 
 
### **Additional Information:**
 
  - Output of the command `dnf repolist` :
  
  ```
repo id                                                                            repo name
appstream                                                                      AlmaLinux 9 - AppStream
baseos                                                                            AlmaLinux 9 - BaseOS
extras                                                                              AlmaLinux 9 - Extras
webmin-noarch                                                              Webmin - noarch
  ```
  
  - Output of the command `cat /etc/yum.repos.d/webmin.repo` :
    
```
[webmin-noarch]
name=Webmin - noarch
baseurl=https://download.webmin.com/download/newkey/yum
enabled=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-webmin-developers
gpgcheck=1
```    

  - Output of the command `cat /etc/pki/rpm-gpg/RPM-GPG-KEY-webmin-developers` :
  
  ```
  -----BEGIN PGP PUBLIC KEY BLOCK-----
Version: GnuPG v2.0.22 (GNU/Linux)

mQINBGRtB+oBEADEkUC5dO003IdKHwNWIwiRkDevPhb0mQ96pZt5eN04kYyWqETE
SEFdCej+KZ+dwK0Whi+sw0vHw7yMuCmSKIzShDb4CFV7K0KXC1jCIJ35NEnb1G1p
Ix0i9S1KF7Twh+CEiSJ4umWoFx0AU2I4lZbtAuDNjMgts4ilBrnqchXKWK3BpfZn
xnvgFbVIiFsVR03TcobsJGZbPsh8NdA9TAF3YlhGZu6ECOIcNu88AlOOlEtm3W1p
O6xnmLSL89bIPSw3mGndlhot7BwlwrlKZYzI05B4HJdqGeZ7Wp+QP3/E5EsG7udy
OdNCdusj2O5OlQbnIwOp/fBCRJOEiC+nBHEnhsmc7TbtTeq5ugPuRYAe3e0ke/Fz
6yT271rYBOQ/DzzzXJPs8Vyba4qkTXjVq1fmfvNFDvAB1K3vEVGzCXCAWf2eihU0
fDZrDouluWd3brGBqirNkVb4+JsHUmIfmUthwZ7GNTyyV6epdfrgI3nIA4L6IeY6
LBYvoE9jXF4P/TcwCZrZCMYuycjONmIXXX08cz3C0Q2kQTvmKpC5LoCQo2Eds1gJ
MYEVDE3jKsu7xsr3Ao77ZjF2S8GomRXUX9F+/w0GNBpX6eNNFjuSjqIk4+60I+ku
yl6lkKsu5nz7Ud2yutyG2idWQJUkhaVNbHwX9pNTjHI2aRkC+KTN/zD6WQARAQAB
tClXZWJtaW4gRGV2ZWxvcGVycyA8ZGV2ZWxvcGVyc0B3ZWJtaW4uY29tPokCOQQT
AQIAIwUCZG0H6gIbAwcLCQgHAwIBBhUIAgkKCwQWAgMBAh4BAheAAAoJECjhGUP/
at2Fwf4P/jXUkH25s7fKthMLmjHxKhvTPKzfUSPqJTriOES14VEO5bJNFJOjWE3k
U/jZ+8f4FEF3fAPcOBM+Ngh/SEMvJ/S077tnoo6rc5KLAUKiQ9BdCK6QZ/9wbO8+
c9JFFsaD9NMPA8QpGSr9/rYYpT6mkW85WoYIz0r1NwLKFn4TgV6Nx/kDk514b5nK
4GYfyYgNYbnEmMIx0eI28ErHJgTEUZvR0UAJ059vEdMWUoc+WGG5aHf93KE7oZCu
J/3EqboZZNPyT/vmxTWvz4LFZlbPAMAj7pEmeCDh26sQprIs+oNqYTXAjbdoY+qq
cMEjZlC2/lhKdCFhm6JKddChspfbfpQL22oElCNiufx8631YHP+lA0TTE1UbYA1W
LLny/3wAox3a8jswdoBP5AoJ0puTM3R7vihGXgjZcbMyLJw4EH7K0v+JEDkBtZCm
iiFNf3NuPpDVMBuXQ4D8PaHvJOuCMP3ztaDZ2J3Z+o1dt2k1CuSHSBRv0840rC+q
32U7m/P59cfZH7QMH5Tqb+6JPATSHnEUoteiuYKD2PPUetUWBqK1DN0PniZKRYtD
8akmd9AAPnpM1Z5uc72JJWazXtk/lxiBwTXeXlWhGqv0YtG5xlCltwR8grSJvmiu
5nFXjsDRLC4K2fPVVvtdPmvwBFEfzc2SeEht1micA+yDOKDH/JY6uQINBGRtB+oB
EADpxTcNHMb3FPHzwF9C7nwYBUUmHUhu8Gyagd0EOwMoF7BOVXVebKchAk3ChR5W
y4PFz3raCO4F9noYJSH5dlloG7RMugWUOqngwDgvA/lN8DiVgMnLZfnP9cgzd201
I2bZis9iq96JEl+fAcGr2nOZIlVDBps5ywntBpkSgpDv8Nz/RbDnU1v5AKDhZUYw
zhOLkZEruQXmCahTaDJp5ANmn/Hdzb/tTXBktUewFzDsfb/qFWxEPq92l2ncx87g
mqpTqZ1efDr1IQTDgz5ls9cy5OzBpRS1H3fhBPnJtW+ZO8c9FQ0c/PQPNBCMNpQQ
DUTfrLcw4SeWrGTtPK4eju4tbrdf5buqSkVEFk0tcx8dyHdsxZvSygXrEPcg74zN
vehYFVwMw+wcO5ldh8aaqkWi3llR8gZ31FcLxMV6wnynK+vQTBI/SOJbY1bRQMCN
Wb0A8WMi8CzSDt1QVG8Ld31yIEeVOOaDt8FHNx/8buUwWZmwcxyfMllQ7kHurduP
w/GucXyaRB82snLzLklJJg0/jy6kITdSr2Kuc+gaK8otYeXliC4escoKtekBkhhG
aeKhx/ZfFIZt5WXCdln87/z1fXCOjwj/jaBJyCRoixWN39WAauHOBIqXoQ16gUxY
2z+onTyHLqwEi2QN+M00ZzBso9zQAIBajR1aA5NRyyXjWwARAQABiQIfBBgBAgAJ
BQJkbQfqAhsMAAoJECjhGUP/at2Fc+IP/3Y+7NNJ4rp1fgdtYql1qJ7jxbDr7mRu
7z8efqLc+nheCVhJHOW27zI9ZI6pJgyM7EKrN7ELT0ZQzwAyWDJCMPNxLc+AowKB
lBNb7NdYqhfyv9yUlS7cNKy7M9T5I0C/H33pzoznz3R6kpVGM7Q4yEdy5vtFEnpt
wQZAKEW+2LLi77g2q7JXJdfCfgSBEVLawy22r8rKAfyIF81v4pTmTOO0lobmKpel
B5yJJQ39jBhBM7u/tWDBk/bC3tGfvzdDgpmvCTgp6YjpMQIPo6ZSMyceFGPzh7q/
4ttgl6s8lruwq0Ro0WqUDtxtUcdohy2kUtPMqK/Gj3htEuuEMolKANLHc+sUcqXV
iqn8txn8Ihp3+JGtd1l3fFQ4EHo/uP2FDkndwYZ/7F8Xrk8RhJsuEe1FxWdY32Nb
SXaLrrthsgDsqymbvNjDzIFVvU95yUIllVJ0dvyqpcoSZjbVCfNjp/Lxvb0bKgUq
3yT0TYlLLVPz6dUL8Kg9gTEY+SQd28LjaG8q1PS8IRXKgWWRvwGXL+PqJXZLWy+b
qKgOFb2IO27/cQUG50eq74QAMsJuP/vKpLsDOKbXcsrwFOBM6UXo6pYKBd46PSOS
IvHac4C3xCWxo2vfxpEy6Xd5G3BYV4sICuZdgKus/n9lupg7GbO9UrwdXpuQw36i
bk6OFSh+t0wH
=1KZ4
-----END PGP PUBLIC KEY BLOCK-----
  ```

**Comment by jcameron** [comment]
The short-term work around for this is to run `update-crypto-policies --set DEFAULT:SHA1` 

But we'll update the signing algorithm ...

**Comment by iliajie** [comment]
@khs-kks Try [this](https://github.com/webmin/webmin/commit/98b67cd60e19f5a293835d280f0991e5d5e39f15) patched version of `repo-setup.sh` script. You can simply do over again:

```
rm -f setup-repos.sh
wget https://raw.githubusercontent.com/webmin/webmin/master/setup-repos.sh
sh setup-repos.sh
```

**Comment by iliajie** [comment]
> The short-term work around for this is to run `update-crypto-policies --set DEFAULT:SHA1`

Jamie, we shouldn't do it! Besides, you have already setup all new repos to work with the new key? We simply don't need to import old key for the new repo.

**Comment by khs-kks** [comment]
Greetings,

changing the crypto-policy worked.

Here is the output of 

```
rm -f setup-repos.sh
wget https://raw.githubusercontent.com/webmin/webmin/master/setup-repos.sh
sh setup-repos.sh
```

```
Setup Webmin official repository? (y/N) y
  Downloading Webmin key ..
  .. done
  Installing Webmin key ..
warning: Signature not supported. Hash algorithm SHA1 not available.
warning: Signature not supported. Hash algorithm SHA1 not available.
error: developers-key.asc: key 1 import failed.
  .. done
  Setting up Webmin repository ..
  .. done
```

**Comment by khs-kks** [comment]
I ran `setup-repos.sh` from the master branch which I just downloaded. Have not removed the existing repo and key beforehand though. Should I remove them before running the script again ?

**Comment by jcameron** [comment]
I'm going to update the repo to use a new signing hash, once I figure out how to do it!

**Comment by iliajie** [comment]
Haven't you already figured this out? Both new Debian and RHEL repos are working just fine ..

**Comment by jcameron** [comment]
I updated the key, but the issue here is the hash algorithm used when signing the RPM with that key.

**Comment by jcameron** [comment]
Ok, future RPMs in the  new repository will use SHA-256.

**Comment by LA-Dery** [comment]
Looks like this issue has popped back up - or maybe was never seen on Oracle Linux (rpm-based).

error: Verifying a signature, but no certificate was provided:
  Signature 4f1c created at Tue Nov 25 03:40:33 2025 invalid: signature relies on legacy cryptography
      because: Policy rejected non-revocation signature (Binary) requiring collision resistance
      because: SHA1 is not considered secure
error: Verifying a signature, but no certificate was provided:
  Signature 96dc created at Tue Nov 25 03:40:33 2025 invalid: signature relies on legacy cryptography
      because: Policy rejected non-revocation signature (Binary) requiring collision resistance
      because: SHA1 is not considered secure
Webmin                                                                                            14 kB/s | 1.3 kB     00:00    
Importing GPG key 0x11F63C51:
 Userid     : ""
 Fingerprint: 1719 003A CE3E 5A41 E2DE 70DF D97A 3AE9 11F6 3C51
 From       : https://www.webmin.com/jcameron-key.asc
Is this ok [y/N]: y
error: Certificate D97A3AE911F63C51:
  Policy rejects D97A3AE911F63C51: No binding signature at time 2026-01-07T18:38:01Z
error: Verifying a signature, but no certificate was provided:
  Signature 7851 created at Mon Nov 24 02:43:25 2025 invalid: signature relies on legacy cryptography
      because: Policy rejected non-revocation signature (Binary) requiring collision resistance
      because: SHA1 is not considered secure
error: Verifying a signature, but no certificate was provided:
  Signature 9001 created at Mon Nov 24 02:43:25 2025 invalid: signature relies on legacy cryptography
      because: Policy rejected non-revocation signature (Binary) requiring collision resistance
      because: SHA1 is not considered secure
error: Verifying a signature, but no certificate was provided:
  Signature 7851 created at Mon Nov 24 02:43:25 2025 invalid: signature relies on legacy cryptography
      because: Policy rejected non-revocation signature (Binary) requiring collision resistance
      because: SHA1 is not considered secure
error: Verifying a signature, but no certificate was provided:
  Signature 9001 created at Mon Nov 24 02:43:25 2025 invalid: signature relies on legacy cryptography
      because: Policy rejected non-revocation signature (Binary) requiring collision resistance
      because: SHA1 is not considered secure
Key import failed (code 2). Failing package is: usermin-2.510-1.noarch
 GPG Keys are configured as: https://www.webmin.com/jcameron-key.asc
Public key for webmin-2.610-1.noarch.rpm is not installed. Failing package is: webmin-2.610-1.noarch
 GPG Keys are configured as: https://www.webmin.com/jcameron-key.asc
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: GPG check FAILED
