### ISSUE TITLE
How to obtain the real IP address

### ISSUE THREAD

**Issue by fengymi** [webmin/webmin#1921]
![image](https://github.com/webmin/webmin/assets/17907299/a36049f2-c7cb-4514-a778-122e3bd0e97d)

![image](https://github.com/webmin/webmin/assets/17907299/b289f14e-dadf-4306-aad6-2949ed108abb)

IP cannot obtain real IP by nginx proxy

**Comment by iliajie** [comment]
Hello,

Check this tutorial for Nginx out:

https://webmin.com/faq/#can-i-run-webmin-or-usermin-behind-reverse-proxy

**Comment by jcameron** [comment]
Is the real issue here that Nginx isn't forwarding the remote IP for display in the session log?

**Comment by jcameron** [comment]
The fix for that is to edit `/etc/webmin/miniserv.conf` , add the line `trust_real_ip=1` then run `/etc/webmin/restart`

**Comment by fengymi** [comment]
> Hello,
> 
> Check this tutorial for Nginx out:
> 
> https://webmin.com/faq/#can-i-run-webmin-or-usermin-behind-reverse-proxy

system is running, but dashboard display IP is not the expected IP

**Comment by fengymi** [comment]
> /et

I made the changes and restarted it, but the IP still shows 127.0.0.1

> The fix for that is to edit `/etc/webmin/miniserv.conf` , add the line `trust_real_ip=1` then run `/etc/webmin/restart`

you are right

**Comment by fengymi** [comment]
> The fix for that is to edit `/etc/webmin/miniserv.conf` , add the line `trust_real_ip=1` then run `/etc/webmin/restart`

By the way, is there a version that supports Docker dashboards now

**Comment by jcameron** [comment]
So did adding trust_real_ip=1 not help, even after logging out of Webmin and logging in again?

**Comment by fengymi** [comment]
> So did adding trust_real_ip=1 not help, even after logging out of Webmin and logging in again?

adding trust_real_ip=1 is success .
