### ISSUE TITLE
[Webmin][File Manager] Column names word-wrapping in File Manager since Chrome update 114.0.5735.110

### ISSUE THREAD

**Issue by Mecha-Weasel** [webmin/webmin#1922]
Ever since the recent update to the Chrome browser (v114.0.5735.110), I have noticed that various columns in File Manager are now word-wrapping - whereas before the browser update they all displayed fine.

Example:
![Webmin-File-Manager-Wrapping-Issue](https://github.com/webmin/webmin/assets/3591043/f2a8d9f1-d5f6-4d30-9f08-51dd00e4ab15)

**Comment by iliajie** [comment]
Hello,

Sorry about that! It has been fixed quite some time ago. You could manually update Authentic theme alone using Theme Configuration page. Note, that this time you would need to disable Usermin updates (on the same page).

**Comment by Mecha-Weasel** [comment]
Thanks.
Updated Authentic Theme to "latest development branch" (20.30-RC1-35).
Symptom went away in File Manager.

**Comment by iliajie** [comment]
Great to hear!
