### ISSUE TITLE
[Webmin][Linux IPTables Firewall Module] Bad table column spacing in Linux IP Tables Firewall module rules interface

### ISSUE THREAD

**Issue by Mecha-Weasel** [webmin/webmin#1923]
In the rules list for the "Linux IP Tables Firewall" module of Webmin, the columns are weirdly sized.  I believe this issue pre-dates 2.0x releases actually, maybe since 1.9?

As seen in the screenshot, a ton of wasted space is allocated to the "Action" column, that could be better used for the "Condition" and/or "Description" columns.

This is non-breaking issue, everything is functional - just annoying. :-)
![Webmin-Linux-Firewall-Rules-List-Issue](https://github.com/webmin/webmin/assets/3591043/d143fd69-ffec-47a2-a88f-3738918c81c5)

**Comment by iliajie** [comment]
Hello,

Agreed! Fixed in this commit https://github.com/webmin/webmin/commit/18552ad5abba712a3cc84f5ab50ce7adbb3b59cb.

**Comment by Mecha-Weasel** [comment]
PS: I forgot to mention, same issue on the **IP6Tables** version of the module.

**Comment by iliajie** [comment]
It is also fixed for IPv6 version of the module. Thanks!

**Comment by Mecha-Weasel** [comment]
I edited the firewall/index.cgi slightly differently to better accommodate my long rule details WITH comments displayed:

            push(@tds, "width=5", "width=10% nowrap",
				"width=50%", "nowrap", "nowrap");  

Might want to have something that does that automatically, IF comments are being displayed?
