### ISSUE TITLE
Is it able to log user events when readonly mode is set to 1?

### ISSUE THREAD

**Issue by siicosmos** [webmin/webmin#1925]
I am trying to customize Webmin a bit. I'm looking into the code to see whether I can log user events when the read-only mode is set. I can see the miniserv.log is still logging things, but not the webmin.log. Any help? Much appreciated!!

**Comment by jcameron** [comment]
So in readonly mode, Webmin should never perform any operations which change the state of the system ... so there isn't really anything to log.

**Comment by siicosmos** [comment]
Right, I understand that situation. But I want to monitor the actions the user trying to take.

**Comment by siicosmos** [comment]
[line 6808](https://github.com/webmin/webmin/blob/3e9a0e84fc3f04d1c65edcdd8248d607b3f94805/web-lib-funcs.pl#L6808)
Is this the right function that logs user action?

**Comment by jcameron** [comment]
Yes, and you could enable logging even when in readonly mode by removing this line : https://github.com/webmin/webmin/blob/3e9a0e84fc3f04d1c65edcdd8248d607b3f94805/web-lib-funcs.pl#L6833

**Comment by siicosmos** [comment]
> Yes, and you could enable logging even when in readonly mode by removing this line :
> 
> https://github.com/webmin/webmin/blob/3e9a0e84fc3f04d1c65edcdd8248d607b3f94805/web-lib-funcs.pl#L6833

I tried to change it to this `return if (!$gconfig{'log'});`. It seems working. Not very sure about what $gconifg{'log'} does, so...

**Comment by siicosmos** [comment]
> > Yes, and you could enable logging even when in readonly mode by removing this line :
> 
> I wonder, wouldn't it work if `log=1` added to the config?

The global config under `/usr/local/webmin/`? I am on ubuntu 20.04. My installation root path is  `/usr/local/webmin/`. I have a `config-debian-linux` here.

**Comment by jcameron** [comment]
It's in /etc/webmin/config

**Comment by siicosmos** [comment]
> > Yes, and you could enable logging even when in readonly mode by removing this line :
> 
> I wonder, wouldn't it work if `log=1` added to the config?

I tried adding `log=1` in the /etc/webmin/config, but it did not work.

**Comment by siicosmos** [comment]
thanks for the help guys. I am closing this issue.
