### ISSUE TITLE
Quotas array return an issue?

### ISSUE THREAD

**Issue by qooob** [webmin/webmin#193]
Jamie, hi!

Here is what quotas array provides:
```
$VAR1 = {
'chart' => [
'137438953472',
176570368,
8192
],
'value' => '168.40 MB of 2 GB',
'desc' => 'domain3.tld'
};
```
I calculate it very simply: `(SecondValue/FirstValue) * 100` = %

The problem is that 137438953472 is not 2GB but ~128GB?

This is a bug, right? It's the same in the Virtualmin Framed Theme.

Here is more about this issue: https://github.com/qooob/authentic-theme/issues/110#issuecomment-75549328

**Comment by jcameron** [comment]
The first value is the total - for example, how much quota the user has.
The second value is the space used by regular files.
The third value is the space used by databases.

**Comment by qooob** [comment]
Yes, I understand and expect that. Why then in array you can see inconsistency:

```
'137438953472',
176570368
```

and 

```
'168.40 MB of 2 GB',
```

2 GB is not `137438953472`.

It should be something like `'168.40 MB of 137 GB',`

Also just noticed that the first value is in `'`.. 

Array doesn't return the correspondent values, right?

**Comment by jcameron** [comment]
Yeah, that does seem wrong. Which section of the page was this chart in?

**Comment by qooob** [comment]
...I asked  that guy (_7starsone_) to join this conversation to provide more info..

This data is returned to System Information page and delivered by the `list_combined_system_info()`. ..but I would think that it has nothing to do with this new function, because I remember I encountered it years ago and tried to report it already. I would also guess _7starsone_ has CentOS 6 installation or at least, I remember that it was happening with me on that..

Ask for more info if needed. Bug is there..

**Comment by 7starsone** [comment]
CentOS 7 ;-)

**Comment by 7starsone** [comment]
[root@myhost ~]# quota myuser
Disk quotas for user myuser (uid 509):
     Filesystem  blocks   quota   limit   grace   files   quota   limit   grace
       /dev/md2   37632  2097152 2097152            1842       0       0

**Comment by qooob** [comment]
@7starsone percentage is wrong only because of the total value is wrong. It should be counted out of 2gb and not 128gb. If you count it from 128gb - 0% is correct.. :) - that's what happening. I think Jamie will find the issue now..

**Comment by jcameron** [comment]
Ok, I see the cause - the reason is that the bar chart size (the first number) is the max quota across all domains, so that the usage parts of the bar charts are on the same scale. However, a theme can change this behavior to scale each chart independently by passing a hash ref to list_combined_system_info , which has the key "qshow" set to 1.

**Comment by qooob** [comment]
Alright, I will take a look. Thanks!

**Comment by qooob** [comment]
Jamie, for some reason I have negative values on my production server.

```
$VAR1 = [ '1073741824', -8888320, 15740928 ];
$VAR2 = [ '1073741824', -14544896, 14544896 ];
```

Why this is happening? I created/renamed some users manually using `Users and Groups`. In CLI it ruturns for `qouta username`:

```
Disk quotas for user username (uid 600): none
```

**Comment by jcameron** [comment]
OK, that looks like a completely different breakage! 

Does the domain perhaps have files that are owned by the domain admin user, but not his group?

**Comment by qooob** [comment]
In general no. There is one virtual server, that has SSL certificates owned by root user. The rest has proper user:group settings. All web users have in secondary groups apache user. That's pretty much it.

**Comment by qooob** [comment]
...and it happens with all domains..

**Comment by qooob** [comment]
..and I recently, completely reinstalled Virtualmin, including deleting all /etc/webmin/virtual-server files hoping that it would help but it didn't..

**Comment by jcameron** [comment]
Does clicking on System Settings -> Re-check Configuration by any chance fix this?

**Comment by jcameron** [comment]
It looks like the cause of this negative number is that Virtualmin is subtracting the space used by databases from the first number, on the assumption that it will be displayed separately. On your system is /var/lib/mysql on a separate partition from /home ? And are database directories owned by domain owner Unix users?

**Comment by qooob** [comment]
@jcameron Clicking on Re-Check doesn't do much, just checked it a and says it's all ok. Returned the following concerning quotas:

```
Both user and group quotas are enabled for home and email directories.
```

Speaking about that this bug _connected_ with having/not having DB for virtual-servers - sounds true. Virtual-servers that don't have DB look with 0 value (which is also incorrect) :)

Like I mentioned to Joe, `/home` and `/var/lib/mysql` are different partitions and mounted manually after boot as they are having `LUKS` encryption.

Running `mount | grep ' /home'` and `mount | grep ' /var/lib/mysql '` I made sure that the output is as follows, and has `grpquota,usrquota` flags.

```
/dev/mapper/home on /home type ext4 (rw,grpquota,usrquota)
```
and 
```
/dev/mapper/database on /var/lib/mysql type ext4 (rw,grpquota,usrquota)
```

Webmin Disk Quotas module returns correct values.

**Comment by qooob** [comment]
Jamie, about the DB ownerships:

I have DB owned as follows:
```
    4 drwxr-xr-x   8 mysql mysql         4096 Feb 25 19:52 .
    4 drwxr-xr-x. 31 root  root            4096 Oct 29 14:43 ..
    8 -rw-------   1 root  root                  8192 Feb 26 12:29 aquota.group
    8 -rw-------   1 root  root             6144 Feb 25 19:52 aquota.user
    52 -rw-rw----   1 mysql mysql             49152 Feb 25 16:15 aria_log.00000001
    4 -rw-rw----   1 mysql mysql                52 Feb 25 16:15 aria_log_control
    18432 -rw-r-----   1 mysql mysql          18874368 Feb 26 12:32 ibdata1
    49152 -rw-rw----   1 mysql mysql          50331648 Feb 26 12:32 ib_logfile0
    49152 -rw-rw----   1 mysql mysql          50331648 Feb 26 12:32 ib_logfile1
    4 drwx------   2 mysql username1           4096 Feb 17 15:23 username1
    4 drwx------   2 mysql username1           4096 Nov 30 13:52 _username1
   16 drws--S---   2 mysql username2       16384 Mar 23  2013 username2
    0 -rw-rw----   1 mysql mysql                 0 Apr  2  2014 multi-master.info
    4 drwx------   2 mysql mysql                4096 Apr 10  2014 mysql
    0 srwxrwxrwx   1 mysql mysql               0 Feb 25 16:15 mysql.sock
    4 -rw-r--r--   1 root  root                      15 Apr 10  2014 mysql_upgrade_info
    4 drwx------   2 mysql mysql                4096 Apr 10  2014 performance_schema
    4 drwx------   2 mysql username3        4096 Jul 27  2014 username3_ru_roundcubemail
```

Still the same. Here is the output

```
Home disk space used (including sub-servers)	-13.87 MB (0 bytes by server administrator, 0 bytes by mail / FTP users)
Space used by databases	13.87 MB (13.87 MB in this server, 0 bytes in sub-servers)
```

Here is the screenshot:
![screenshot from 2015-02-26 12 43 06](https://cloud.githubusercontent.com/assets/4426533/6389476/38f7d744-bdb5-11e4-8f3f-e50e60a93f00.png)

**Comment by jcameron** [comment]
Ok, it looks like the underlying issue is that Virtualmin cannot get the current disk usage for the domain's group properly. Can you post the output from the following commands :

quota -u domain
quota -g domain
repquota -u /home | grep domain
repquota -g /home | grep domain

**Comment by qooob** [comment]
`quota -u rostovtseva.ru` - Disk quotas for user rostovtseva.ru (uid 500): none **(this is because it's not set and Ulimited)**

`quota -g rostovtseva.ru` - Disk quotas for group rostovtseva.ru (gid 500): none **(same here)**

`repquota -u /home | grep rostovtseva.ru`

`rostovtseva.ru -- 8134380       0       0           7574     0     0`   **Same info that I get in Disk Quotas module**

`repquota -g /home | grep rostovtseva.ru`
`rostovtseva.ru -- 8134380       0       0           7574     0     0`   **(same here)**


Then I made changes in Disk Quota and set limit to 10gb: Here is the obvious and expectable change:

`quota -u rostovtseva.ru`

```
Filesystem  blocks   quota   limit   grace   files   quota   limit   grace
/dev/mapper/home
                8134380  10485760 16777216            7574       0       0
```

**Comment by qooob** [comment]
Please notice it's `/dev/mapper/home`

**Comment by jcameron** [comment]
After setting an actual quota for the user, does Virtualmin display correct usage information?

I'd expect that the quota command would still display usage for a user, even if no limit is set. Maybe that is the source of the problem...

**Comment by qooob** [comment]
No, unfortunatelly. I also restarted Webmin.

Besides here is my config, it might help:


```
display_max=100
block_size=1024
user_copy_command=edquota -u -p
threshold_pc=
group_copy_command=edquota -g -p
group_quotaoff_command=quotaoff -g
quotacheck_command=quotacheck -u -g
group_edquota_command=edquota -g
group_quota_command=quota -v -g
group_repquota_command=repquota -g -v
sort_mode=2
user_quota_command=quota -v -u
hide_uids=0
user_edquota_command=edquota -u
show_grace=1
group_setquota_command=setquota -g
user_quotaoff_command=quotaoff -u
email_msg=Disk usage for user ${USER} on filesystem ${FS} has reached ${PERCENT}% of the	allowed quota.		${USED} of disk space is being used, out of a maximum of ${QUOTA}.
pc_show=2
user_quotaon_command=quotaon -u
group_quotaon_command=quotaon -g
user_setquota_command=setquota -u
user_grace_command=edquota -u -t
user_repquota_command=repquota -u -v
block_mode=1
group_grace_command=edquota -g -t
gemail_subject=
gemail_msg=
email_subject=
```

`quota -v rostovtseva.ru` or when using any other username, really **always display quotas**, when removing `-v` flag, and if quotas is not set, it returns none.

After **testing** I found out the following:

`blockdev --getbsz /dev/sda1` (device that has /home folder, when the lower is mounted)
**1024**

`blockdev --getbsz /dev/mapper/home`
**4096**

**Comment by jcameron** [comment]
Do you have any custom quota commands set at System Settings -> Virtualmin Configuration -> Quota commands?

**Comment by qooob** [comment]
I'm not at the PC now, but I would think no, because I just recently cleared and reinstall Virtualmin. I willdouble check to confirm.

**Comment by qooob** [comment]
There I have `Use external commands to get and set quotas?` set to `No` and the rest to ` Use standard programs`.

So the answer is no. If you can't figure it out like this (it's hard without having it), please tell me which way to look in the code. Which files/lines of code?

**Comment by jcameron** [comment]
So the relevant code to look at is the "get_domain_quota" function, in virtual-server-lib-funcs.pl

**Comment by qooob** [comment]
Alright, here is the output of the following part of the code:

`virtual-server-lib-funcs.pl` lines **10697-10710**

Using this code:
```Perl
# Get from real quotas
&require_useradmin();
local $n = &quota::group_filesystems($d->{'group'});
for(my $i=0; $i<$n; $i++) {
	if ($quota::filesys{$i,'filesys'} eq
	    $config{'home_quotas'}) {
		$home = $quota::filesys{$i,'ublocks'};
		}
	elsif ($config{'mail_quotas'} &&
	       $quota::filesys{$i,'filesys'} eq
	       $config{'mail_quotas'}) {
		$mail = $quota::filesys{$i,'ublocks'};
		}
	}
```

1. Output of `$quota::filesys{$i,'filesys'}`:
```
'/';
'/boot';
'/tmp';
'/usr';
'/var';
'/var/lib/mysql';
'/home';
```

2. Output of `$quota::filesys{$i,'ublocks'}`:
```
0
0
0
0
0
3408
1659272  # on my system it's 1.6GB
```

3. Output of `$config{'home_quotas'}` and `$config{'mail_quotas'}`:
```
/
/
/
/
/
/
/
```

4. Output of `&quota_bsize("home")`:
```
1024
1024
1024
1024
1024
1024
1024
```

Please find out the cause! Ask for more output if needed. Thank you very much.

**Comment by jcameron** [comment]
Ok, it looks like the real issue is that $config{'home_quotas'} is set to / when it really should be /home

Can you also post the contents of your /etc/fstab and /etc/mtab files?

**Comment by qooob** [comment]
Before I continue! I _mount_ `/home` and `/var/lib/mysql` _manually_, as those partitions (LUKS) require  password. If I put all of this stuff to `fstab/crypttab` I would need KVM every time I restart the server, to enter the password.

Content of `fstab`

```
UUID=a9c9fc83-ea5a-46e7-88b5-6e9fe0b11c82 /	                  ext4	  grpquota,usrquota,rw 0 1
UUID=72897587-7f83-4d12-9db8-4439de028fc6	/boot	ext4	usrquota,grpquota	0	2
UUID=cf02cb9f-8183-456e-b157-55c4c3b6fb20	/tmp	ext3	noexec,nosuid,usrquota,grpquota	0	2
UUID=ae35b15e-a78b-4d17-b0ba-221883f36cf4	/usr	ext4	usrquota,grpquota	0	2
UUID=7ae25442-f411-4e52-b018-42950fade39b	/var	ext4	usrquota,grpquota	0	2

UUID=a30beb6b-4641-4ec2-a96d-31a604bd7c03 swap                    swap    defaults             0 0

tmpfs                                     /dev/shm                tmpfs   noexec,nosuid        0 0
devpts                                    /dev/pts                devpts  gid=5,mode=620       0 0
sysfs                                     /sys                    sysfs   defaults             0 0
proc                                      /proc                   proc    defaults             0 0

```

Content of `mtab`:

```
/dev/sdb2 / ext4 rw,grpquota,usrquota 0 0
proc /proc proc rw 0 0
sysfs /sys sysfs rw 0 0
devpts /dev/pts devpts rw,gid=5,mode=620 0 0
tmpfs /dev/shm tmpfs rw,noexec,nosuid 0 0
/dev/sdb1 /boot ext4 rw,usrquota,grpquota 0 0
/dev/sdb6 /tmp ext3 rw,noexec,nosuid,usrquota,grpquota 0 0
/dev/sdb3 /usr ext4 rw,usrquota,grpquota 0 0
/dev/sdb5 /var ext4 rw,usrquota,grpquota 0 0
none /proc/sys/fs/binfmt_misc binfmt_misc rw 0 0
/dev/mapper/database /var/lib/mysql ext4 rw,grpquota,usrquota 0 0
/dev/mapper/home /home ext4 rw,grpquota,usrquota 0 0
/dev/sda3 /backup ext4 rw 0 0
/dev/sda1 /backup/boot ext4 rw 0 0
/dev/sda4 /backup/usr ext4 rw 0 0
/dev/sda5 /backup/var ext4 rw 0 0
/dev/mapper/backups /backup/backups ext4 rw 0 0
```

**Comment by qooob** [comment]
Besides, if it matters `/tmp ext3 rw,noexec`.

**Comment by swelljoe** [comment]
You can still have an entry in fstab for /home, even if it is not mounted during boot. Just set it to noauto in the options.

**Comment by qooob** [comment]
So what do I do? Edit `fstab` and restart the server? Any other commands I could run right now?

**Comment by qooob** [comment]
> You can still have an entry in fstab for /home
And then, when I mount my LUKS partitions to `/home` it will make a difference really ( I mean whether I have it in `fstab` or not )?

**Comment by swelljoe** [comment]
Jamie, is there a reason Virtualmin doesn't pull this data from mtab, rather than fstab? Since mtab is the current state of the mounted filesystems, and fstab is more theoretical...and wrong in this case.

**Comment by qooob** [comment]
@swelljoe sounds reasonable!

**Comment by jcameron** [comment]
After editing /etc/fstab , you should only need to re-run the configuration check in Virtualmin.

The reason it looks for the /etc/fstab entry is that (as far as I know), quotas cannot be enabled for a filesystem without an /etc/fstab entry.

**Comment by qooob** [comment]
Alright, that worked!! :) Thank you very much, now I can make quotas work in my theme!

Jamie, please say, could the following break in some way my boot. Restoring `fstab` on remote and production system is pain in the back.

For me it looks correct though. What do you think? I added:

```
/dev/sda							/home			ext4	usrquota,grpquota,noauto		0 0
/dev/sdc							/var/lib/mysql	ext4	usrquota,grpquota,noauto		0 0
```

**Comment by qooob** [comment]
In addition to above, the problem arises concerning the same subject:

When I go to `Virtualmin-Edit Users` and set user quota 4TB, I have this error in return:

```
.. Administration user failed! : setquota: Cannot set quota for user 518 from kernel on /dev/mapper/home: Numerical result out of range setquota: Cannot write quota for 501 on /dev/mapper/home: Numerical result out of range at /usr/libexec/webmin/web-lib-funcs.pl line 1397.
```

Besides after all, other users max quota becomes 4TB only in that array (we spoke at the beginning of the discussion), that first number of the array for all now `4398046511104`. Do I miss something?

**Comment by qooob** [comment]
Jamie, is there a reason why it's happening the way it is? Imagine you have 3 domains:

```
domain1.tld
domain2.tld
domain3.tld
```

For each you have set different limits. On domain _domain1.tld_, let's say 1GB and for _domain2.tld_ and _domain3.tld_ let's say 100MB. What is happening now is that if you set quota for domain _domain1.tld_, greater than for any other existing, which is 1GB in my particular example, the other  domains are getting the same max value (1GB and **not** 100MB).

`list_combined_system_info()` returns that MAX number as first number in that array **and not the one that was specified* (100MB in this example).

So the result of that function is incorrect by nature? You said:

>However, a theme can change this behavior to scale each chart independently by passing a hash ref to list_combined_system_info, which has the key "qshow" set to 1.

Well what is the point of that? If there is a point and I don't get it, could you please tell me how to force 
`my @info = &list_combined_system_info();` return domain specific MAX value? I tried `&list_combined_system_info({'qshow', 1});` but it changes nothing!

**Comment by 7starsone** [comment]
indeed, was the original issue I talked about... i imagined that it returned the max value assigned among the domains, e.g. to one of them I assigned 128 GB and now it always returns 128 GB instead of "domain specific MAX value" ;-)

**Comment by qooob** [comment]
Alright, Jamie! ;) I seem to figure the bug out and fixed it!

1. If we enable `$qshow` it will only return percent and not actual values! But please tell me how to enable it using `&list_combined_system_info()` - I just couldn't find this out!

2. I believe there is a bug in `system_info.pl`.

I made the following adjustments and replaced incorrectly used `my $maxquota = $info->{'maxquota'};` with actual `->{'uquota'}`.

On the line 314, where you have `foreach my $q (@quota) {`

I added:

``` Perl
foreach my $uq ($q->[0]->{'uquota'}) {
	our $uq = int($uq * 1024);
}
```

Where later, on line 328 I replaced `$maxquota` with `$uq`. Which makes now *real domain quota* being returned to 

The line 328 should be as follows:

```Perl
$chart->{'chart'} = [ $uq, $q->[1], $q->[3] ];
```

When passing data to evaluate **each** domain allowed quota, we should not use `$maxquota` but `$uq`

I works now as expected.

Please test it and tell me what you think. Please don't forget about 1 point.

@7starsone You can test it by editing file `system_info.pl` in `/usr/libexec/webmin/virtual-server`.

**Comment by 7starsone** [comment]
edited the system_info.pl but now it always returns 0 for any domain

e.g.
```
$VAR1 = {
          'chart' => [
                       0,
                       3526225920,
                       6327111680
                     ],
          'value' => '9.18 GB',
          'desc' => '<a class=\'ui_link\' href=\'/virtual-server/edit_domain.cgi?dom=141676138110898\'>mydomain.com</a>'
```

**Comment by 7starsone** [comment]
```my $maxquota = $info->{'uquota'};```
the same... with any
```'chart' => [
                       0,
                       ...
```

**Comment by qooob** [comment]
No, that's not right. Put my foreach right under existing foreach and then replace line 328 - it will work

**Comment by 7starsone** [comment]
ok, now it works

**Comment by qooob** [comment]
Actually to fix this _bug_ and make it more concise, the line 328 should be simply replaced with the following and that's all, no previous code.

```
# By actual usage
foreach my $uq ($q->[0]->{'uquota'}) {
	$chart->{'chart'} = [ int($uq * 1024), $q->[1], $q->[3] ];
}
```

**Comment by qooob** [comment]
Getting tired, sorry :). Even more simple, no `foreach` needed line 328 with this:

```Perl
$chart->{'chart'} = [ int($q->[0]->{'uquota'} * 1024), $q->[1], $q->[3] ];
```

It will not affect the actual result, just code concision.

**Comment by 7starsone** [comment]
ok ;-) have you the new version ready ?

**Comment by qooob** [comment]
I'm waiting for Jamie's decision on `Disk Quotas module` issue and `this bug` too. After that + 24h and epic release, 10.0.0 will be out! :D

**Comment by jcameron** [comment]
So there is a bug in the current 4.14 Virtualmin release that causes the qshow field to be ignored :-( However, the upcoming 4.15 release will fix it.

As for your fstab change, this shouldn't prevent the system from booting as those entries have the "noauto" attribute set.

**Comment by qooob** [comment]
Thank you, Jamie!!

1. So if I do in the theme now `@info = &list_combined_system_info( {'qshow', 1} )` it will work in 4.15?

2. Jamie, why having `int($q->[0]->{'uquota'} * 1024)` is not right? Having `$info->{'maxquota'}` seens totally wrong here?

**Comment by jcameron** [comment]
1. Yes, that will work in the 4.15 release.

2. "maxquota" is used so that all the graphs are scaled the same - a usage of 100 MB looks the same for two domains, even if their quota is different.

**Comment by qooob** [comment]
Alright! Thanks, Jamie! I already tested it with 4.15 `system_info.pl` - it works as expected!

... I just released mega version of my Theme. Please try! ;)

**Comment by 7starsone** [comment]
nice job :-)
i have a domain with bandwidth ***unlimited***: why I see 81% on the Bandwidth from sysinfo.cgi ?

**Comment by qooob** [comment]
Screenshot please! :)

**Comment by qooob** [comment]
Hey let's move away from Webmin repo.. https://github.com/qooob/authentic-theme/issues/110

**Comment by qooob** [comment]
Jamie, hi again! We have a person, who states that he/she doesn't get back percent array, even if everything is used properly from my side and the latest Webmin 1.730/Virtualmin 4.15 are installed. How is this possible? Please take a look at the following link, it could be another bug on your side, as I don't do much there at all. https://github.com/qooob/authentic-theme/issues/110#issuecomment-77681244

Quotas work fine with me, Joe too and others. So, not sure what to say there.

**Comment by jcameron** [comment]
Looks like in that case, the cached system information hadn't been updated. That should happen every  few minutes though..
