### ISSUE TITLE
Get rid of “Operating system Ubuntu Linux has been upgraded to version 18.04.6. Release notes”

### ISSUE THREAD

**Issue by faxotherapy** [webmin/webmin#1932]
Hi, I udpated from 18.04 to 20.04.6, but Webmin persisently shows the following:

<img width="538" alt="annoying-webmin-message" src="https://github.com/webmin/webmin/assets/6538008/affd17d6-cf3b-4cf8-a6d3-3364fc7a8ad7">

Furthermore, the warning box is irrelevant since I upgraded to 20.04.6

Unfortunately, clicking on either “Release notes” or “Update Detected Operating System” does not get the warning off the screen.

Thank you.

**Comment by iliajie** [comment]
Hello,

If you click refresh button at the top right of the Dashboard, does the message go away? Although, before trying that, try force reloading the page first using `Ctrl+Shift+R` hotkey.

**Comment by faxotherapy** [comment]
Hi, unfortunately, the box still persists. I refreshed the page with the top right button and cleared browser cache.

The issues came after I did the following: Dasboard > Webmin > Webmin Configuration > Operating System and Environment > Ticked the box to detect the OS version. Since then, that above-mentioned box appeared.

**Comment by faxotherapy** [comment]
<img width="1365" alt="webmin-os-env" src="https://github.com/webmin/webmin/assets/6538008/8d88abb5-7624-45ed-b4fa-7b9c9549de02">

**Comment by iliajie** [comment]
Alright, and what is the output of the following commands:

```
ls -lsa /var/webmin/modules/webmin/oscache
cat /var/webmin/modules/webmin/oscache
lsattr /var/webmin/modules/webmin/oscache
```

**Comment by faxotherapy** [comment]
```shell
root@Camelot:~# ls -lsa /var/webmin/modules/webmin/oscache
4 -rw-r--r-- 1 root root 103 22.06.2023•17:56 /var/webmin/modules/webmin/oscache

root@Camelot:~# cat /var/webmin/modules/webmin/oscache
real_os_version=20.04.6
os_type=debian-linux
real_os_type=Ubuntu Linux
os_version=11.0
time=1687449383

root@Camelot:~# lsattr /var/webmin/modules/webmin/oscache
--------------e----- /var/webmin/modules/webmin/oscache
```

**Comment by iliajie** [comment]
It seems that the file `/var/webmin/modules/webmin/oscache` isn't writable. You should look deeper into the problem under this angle..

**Comment by faxotherapy** [comment]
I guess I'll need to do a tedious juggling with chmod and chown until I find the right permisison combination as I'm not inclined to use blindly those commands recursively? I don't see any _webmin_ group. Instead, I see a _bin_ group for webmin. Maybe doing a re-install of Webmin while preserving my configuration file would be best suited?

**Comment by faxotherapy** [comment]
Thanks for your suggestion. I deleted the file, but after refreshing the dashboard, the box still shows up.

**Comment by faxotherapy** [comment]
Solved!

**Comment by sigma415** [comment]
In my case I had to delete the file `realos-cache` in same directory to get rid of the warning.
