### ISSUE TITLE
Unable Support for MariaDB 11

### ISSUE THREAD

**Issue by devadattas** [webmin/webmin#1933]
After upgrading to MariaDB 11 we get the following error:

<img width="1389" alt="image" src="https://github.com/webmin/webmin/assets/56180/bee413c0-a49f-4979-a5cd-e8b7473b1e5f">

```
The MariaDB client program /usr/bin/mysql does not appear to be the correct version. Webmin only supports MariaDB versions 3 and above.
The command /usr/bin/mysql -V returned :

/usr/bin/mysql: Deprecated program name. It will be removed in a future release, use '/usr/bin/mariadb' instead
/usr/bin/mysql from 11.0.2-MariaDB, client 15.2 for debian-linux-gnu (x86_64) using readline 5.2
```

**Comment by jcameron** [comment]
Thanks for the patch!

**Comment by iliajie** [comment]
I have also given MariaDB 11 a try on my test Alma 9.2 machine and the upgrade worked just fine. The old databases didn't seem to break and everything seems to be running smoothly.

Also, MariaDB 11 deprecated all old `mysql` prefixes. So, there is no longer `mysql` command but `mariadb`. There is no longer `mysqldump` but `mariadb-dump` ..

Jamie, should we address it somehow? I mean, if Webmin detects that MariaDB 11 is installed we could change internally all commands prefixes from `mysql` to `maridb-` in `mysql-lib.pl` file .. We could do it using standard configs .. but it won't work if a user manually upgrades MariaDB to version 11 ..

**Comment by jcameron** [comment]
We should just change the default commands in /etc/webmin/mysql/config based on the Linux distro version, if it ships with MariaDB.

**Comment by magosla** [comment]
I am having the same issue with webmin version: 2.105 installed on Rocky Linux 9, MariaDB version: 11.2.1
![Capture](https://github.com/webmin/webmin/assets/1365590/3758e69a-4afd-4f1e-9103-6bd761f770cc)

**Comment by iliajie** [comment]
> We should just change the default commands in /etc/webmin/mysql/config based on the Linux distro version, if it ships with MariaDB.

MariaDB 11 isn't shipped yet with any stable distro yet.

> I am having the same issue with webmin version: 2.105 installed on Rocky Linux 9, MariaDB version: 11.2.1

You should edit module config and manually fix paths for the new MariaDB commands.

**Comment by iliajie** [comment]
> We should just change the default commands in /etc/webmin/mysql/config based on the Linux distro version, if it ships with MariaDB.

Perhaps we should tweak config on the fly?

**Comment by magosla** [comment]
> You should edit module config and manually fix paths for the new MariaDB commands.

Updating the System configuration fixed the issue. Thanks

**Comment by dpurnam** [comment]
Thanks, I rather re-created relevant/missing `mysql` symlinks to appripriate `mariadb-` binaries

**Comment by iliaross** [comment]
> Thanks, I rather re-created relevant/missing `mysql` symlinks to appripriate `mariadb-` binaries

This isn't a very good idea.
