### ISSUE TITLE
Dashboard missing disk

### ISSUE THREAD

**Issue by Isti6github** [webmin/webmin#1936]
Hello,

I would like to see on the webmin dashboard all disks usage (3 different) , but I only see 2…
Could you help me?
See attached pictures.
![dashboard](https://github.com/webmin/webmin/assets/127151924/d1967bce-d1f5-44f1-b425-b9388cb83be3)
![disk](https://github.com/webmin/webmin/assets/127151924/c81a7c73-10da-43ef-85f4-f2b9c63f73d4)
![disk2](https://github.com/webmin/webmin/assets/127151924/06b331ad-dade-4280-94e3-7ed14e6011bd)

**Comment by jcameron** [comment]
Thanks, we'll fix this in the next Webmin release.
