### ISSUE TITLE
How to use webmin to create raid5 and boot and mount it to the specified location？

### ISSUE THREAD

**Issue by liutt1312** [webmin/webmin#1938]
How to use webmin to create raid5 and boot and mount it to the specified location？
Can you provide steps？

**Comment by jcameron** [comment]
Sure, the steps are : 

1 - Make sure you have three or more partitions (on three different disks) available for RAID
2 - Go to Hardware -> Linux RAID and click "Create RAID device of level" and choose RAID 5
3 - Select the three partitions to include
4 - Click Create
5 - After that, click on the new device name and click the button to format it as EXT4
6 - Go to System -> Disk and Network Filesystems and mount the new RAID device somewhere

**Comment by liutt1312** [comment]
Okay, thank you very much
