### ISSUE TITLE
Add a new journalctl query the system logs module

### ISSUE THREAD

**Issue by naturedamends** [webmin/webmin#1946]
I would like to add a new log viewer entry that would display arbitrary log commands 

I would like to add 

```
journalctl -b CONTAINER_NAME=container-name -b CONTAINER_NAME=some-othername
```

However this could be supplied by providing arguments to the command.

Would be happy to help with PR, or with some support I could perhaps do it myself.

**Comment by jcameron** [comment]
So the log viewer module does support extra files to view already (on the module configuration page), but not arbitrary commands. However, in the next Webmin release I'll add the ability to enter a command with a `|` character at the end, which will cause the output to be displayed.
