### ISSUE TITLE
Disk Quota Module - 3TB limit?

### ISSUE THREAD

**Issue by qooob** [webmin/webmin#195]
When I go to `Virtualmin-Edit Users` and set user quota 4TB, I have this error in return:

```
.. Administration user failed! : setquota: Cannot set quota for user 501 from kernel on /dev/mapper/home: Numerical result out of range setquota: Cannot write quota for 501 on /dev/mapper/home: Numerical result out of range at /usr/libexec/webmin/web-lib-funcs.pl line 1397.
```

Same error happens on Disk Quotas module:

```
setquota: Cannot set quota for user 501 from kernel on /dev/mapper/home: Numerical result out of range setquota: Cannot write quota for 501 on /dev/mapper/home: Numerical result out of range
```

At the same time, when set 512GB - All if fine. There no even a dropdown for `TB`.

It's a bug, right?

**Comment by qooob** [comment]
When setting 3TB - all is working fine! 4TB returns an error above.

Actually, I have found something in bug track on RedHat: https://access.redhat.com/solutions/381493

**Comment by qooob** [comment]
:up:  The problem still exists.

**Comment by jcameron** [comment]
Webmin itself certainly doesn't impose any limit ... but the filesystem might.
