### ISSUE TITLE
sudo apt update: Could not connect to download.webmin.com:443 (45.76.69.64), connection timed out

### ISSUE THREAD

**Issue by Danrancan** [webmin/webmin#1952]
Looks like there is a problem with the webmin repo for Ubuntu 20.04 at least. In a sudo apt update I am getting

>  Could not connect to download.webmin.com:443 (45.76.69.64), connection timed out
> W: Failed to fetch https://download.webmin.com/download/repository/dists/sarge/InRelease  Could not connect to download.webmin.com:443 (45.76.69.64), connection timed out Could not connect to download.webmin.com:443 (104.207.151.13), connection timed out
> W: Some index files failed to download. They have been ignored, or old ones used instead.

Whats up?

**Comment by jcameron** [comment]
@swelljoe looks like download1.webmin.com (45.76.69.64 on Vultr) is down. Do you have access to their admin panel to restart it?

**Comment by DavidGhedini** [comment]
It's been on and off all day.  Works for a few minutes and then stops.

**Comment by jcameron** [comment]
Try it again now - turns out the server was up, but it just needed an Apache restart
