### ISSUE TITLE
fix ur gpt keys and repos lmao 

### ISSUE THREAD

**Issue by BigLOnline** [webmin/webmin#1954]
L

**Comment by jcameron** [comment]
Um, can you provide more details on how they're not working?

**Comment by BigLOnline** [comment]
![Screenshot_20230716-133854.png](https://github.com/webmin/webmin/assets/70815584/6cfba5c9-ba9d-49c6-914e-41d2bb97c604)

![Screenshot_20230716-130219.png](https://github.com/webmin/webmin/assets/70815584/8590a221-3f76-4e61-92a4-1fa2c043d48e)

Can't remove webmin either. Debian 12 - can't get the webmin key either stays stuck

**Comment by BigLOnline** [comment]
I'm gonna do a fresh install most likely

**Comment by BigLOnline** [comment]
UPDATE: The repo is fine but ![Screenshot_20230716-140332.png](https://github.com/webmin/webmin/assets/70815584/359477d7-45c8-4fd3-b806-57d16c78ca3c)

I try to pull the key but it won't pull, timeout

**Comment by BigLOnline** [comment]
I did wget -q https://www.webmin.com/jcameron-key.asc -O- | sudo apt-key add - sudo add-apt-repository "deb [arch=amd64] http://download.webmin.com/download/repository sarge contrib" and "no key "

**Comment by BigLOnline** [comment]
I removed the old key and added the key and got the key is depricated

**Comment by iliajie** [comment]
> I did wget -q https://www.webmin.com/jcameron-key.asc -O- | sudo apt-key add - sudo add-apt-repository "deb [arch=amd64] http://download.webmin.com/download/repository sarge contrib" and "no key "

You shouldn't.

You should do this https://webmin.com/download/#setup.

**Comment by iliajie** [comment]
Meaning, you should do:

```
curl -o setup-repos.sh https://raw.githubusercontent.com/webmin/webmin/master/setup-repos.sh
sh setup-repos.sh
```

**Comment by BigLOnline** [comment]
Did that as well

**Comment by BigLOnline** [comment]
It stays stuck on getting the webmin key and never proceeds

**Comment by BigLOnline** [comment]
Issue is resolved

**Comment by iliajie** [comment]
Good to know. It works for me in Debian 12 too.
