### ISSUE TITLE
Webmin & Cloudflared tunnel

### ISSUE THREAD

**Issue by BigLOnline** [webmin/webmin#1956]
Webmin has issues communicating over the Cloudflared tunnel, it'll not login once I put said info, instead I have to reload tab to login??? Unsure if this is an issue that is you're guys end, I run a tunnel on my server and communicate with other systems so the ip will always be the internal of the pc I use is there a way to get the connectors origin ip when a client comes to the website that I host webmin on?

**Comment by jcameron** [comment]
Can you provide more details about what's going wrong, like a screenshot or screen recording?

**Comment by chris001** [comment]
The origin IP is in the headers, something like `X-CF-IP`

**Comment by jcameron** [comment]
So if you add `trust_remote_ip=1` to `/etc/webmin/miniserv.conf` and restart Webmin, it will look at the headers X-Forwarded-For and X-Real-IP to get the remote IP addresses. 

According to https://developers.cloudflare.com/fundamentals/get-started/reference/http-request-headers/#true-client-ip-enterprise-plan-only the header Cloudflare sets is `True-Client-IP`. We could add support for that as well ...

**Comment by iliajie** [comment]
Shouldn't we also include `CF-Connecting-IP` and `CF-Connecting-IPv6` .. because CF documentation states:

> There is no difference between the True-Client-IP and CF-Connecting-IP headers besides the name of the header. Some Enterprise customers with legacy devices need True-Client-IP to avoid updating firewalls or load-balancers to read a custom header name.

**Comment by jcameron** [comment]
Sure, I'll add support for CF-Connecting-IP as well.

**Comment by chris001** [comment]
> Sure, I'll add support for CF-Connecting-IP as well.

For full compatibility please add also [`CF-Connecting-IPv6`](https://github.com/cloudflare/cloudflare-docs/blob/production/content/fundamentals/get-started/reference/http-request-headers.md#cf-connecting-ipv6)

**Comment by jcameron** [comment]
Is that one only used when tunneling from IPv6 to v4, or also when just doing v6 to v6?

**Comment by jcameron** [comment]
Sure, I'll add support for that header..
