### ISSUE TITLE
File uploader pop-up window height

### ISSUE THREAD

**Issue by qooob** [webmin/webmin#196]
Jamie, could you please increase the size of the pop-up window from `100` to `128`.

I'm talking about this line from `web-lib-funcs.pl`:

`my $opener = "window.open(\"$gconfig{'webprefix'}/uptracker.cgi?id=$id&uid=$<\", \"uptracker\", \"toolbar=no,menubar=no,scrollbars=no,width=500,height=100\");";`

It seems to little in Authentic Theme?

**Comment by jcameron** [comment]
Sure, will do.

**Comment by qooob** [comment]
Thank you, Jamie! :)
