### ISSUE TITLE
Webmin 2.021. I can't change gateway in mode "Network config type: Debian Linux"

### ISSUE THREAD

**Issue by fantvin** [webmin/webmin#1960]
I use Debian GNU/Linux 11 (bullseye)
I deleted netplan and installed webmin.
Network config type set to "Debian Linux"
When I click button "Save"
![image](https://github.com/webmin/webmin/assets/25223552/35921eda-d029-43c8-a0fb-aba3f291e7e5)
and get error
![image](https://github.com/webmin/webmin/assets/25223552/220ebb0f-afe6-434a-a4b3-6a953d97fbcc)

**Comment by fantvin** [comment]
String 950 working incorrectly in file /usr/share/webmin/net/debian-linux-lib.pl
I change to:
$file = $network_interfaces_config;
and it's work very well.
I see string $file ||= $network_interfaces_config; in other functions.
I dо'nt know working this correctly there

**Comment by jcameron** [comment]
Thanks - we'll fix this in Virtualmin 2.100!
