### ISSUE TITLE
Any way to make it so I don't have to input y when running setup-repos.sh?

### ISSUE THREAD

**Issue by kriki200** [webmin/webmin#1961]
It would be way better, if I could just bbrun it automatically, without the need of user input.

**Comment by swelljoe** [comment]
I'm surprised it doesn't have an `-f` option (I checked, it doesn't). I thought this script borrowed code from the `virtualmin-install.sh`, which does have such an option. It should definitely be able to be run without human input.

**Comment by iliajie** [comment]
Thanks for bringing this up! It was fixed on this [commit](https://github.com/webmin/webmin/commit/d384e696f7f7f16caae6cbf8a425c370e0c7e8b9).

Also, there is nothing wrong in using `yes | ./setup-repos.sh`, I think, right .. ?

**Comment by kriki200** [comment]
> Thanks for bringing this up! It was fixed on this [commit](https://github.com/webmin/webmin/commit/d384e696f7f7f16caae6cbf8a425c370e0c7e8b9).
> 
> Also, there is nothing wrong in using `yes | ./setup-repos.sh`, I think, right .. ?

Thank you.
