### ISSUE TITLE
Enable support for client certificates behind reverse proxies

### ISSUE THREAD

**Issue by g-regor** [webmin/webmin#1962]
The server should get the distinguished name from a header (`X-SSL-Client-DN`), instead getting it from the cert received on the SSL connection, since the Webmin in this case won't be running on SSL and the proxy would set the header.

Obviously this would need to be explicitly enabled in the config like the `trust_real_ip`.

**Comment by jcameron** [comment]
That seems like a reasonable suggestion. But can you explain further in what situation this would be useful?

**Comment by g-regor** [comment]
What is there to explain further? Both client certificate logins and reverse proxies can be used already, just not used together.

**Comment by jcameron** [comment]
Ok I think I see what you mean now.

What is the format of the `X-SSL-Client-DN` header?

**Comment by g-regor** [comment]
It's something like `/CN=username/C=US`.

It should be the same as what is set for the user's "SSL certificate name" field, so I think the format shouldn't really matter.

**Comment by jcameron** [comment]
Ok, check out the patch linked above - it should add support for trusting the proxied SSL client cert.

**Comment by g-regor** [comment]
Sorry for the delay. I finally found time to test it.

It isn't working. It's only checking the proxied SSL client cert, if the server is running with SSL and the client cert was provided normally, but the server is running unencrypted behind the proxy.

**Comment by jcameron** [comment]
Oh so in your case, is the Webmin webserver not running with SSL enabled?

**Comment by g-regor** [comment]
No. Only the reverse proxy is handling SSL.

**Comment by jcameron** [comment]
Ok I see the issue .. this will be fixed in the next release.

**Comment by iliajie** [comment]
> Ok I see the issue .. this will be fixed in the next release.

Jamie, thanks! But could you please document how this feature that allows the proxy server to authenticate users via SSL actually works? That would be really helpful to everyone!

**Comment by jcameron** [comment]
Ah yes I should document this, as it can cause confusing and potentially security issues if setup wrong.

**Comment by iliajie** [comment]
> Ah yes I should document this, as it can cause confusing and potentially security issues if setup wrong.

Thanks, Jamie! Any update on this?

**Comment by jcameron** [comment]
I added a new config option to control this behavior, with some help docs in the Webmin UI.

**Comment by iliajie** [comment]
> I added a new config option to control this behavior, with some help docs in the Webmin UI.

Jamie, could you please always link a related commit to a ticket? Without it, it's more difficult to follow.

If you add the link to a new line in the commit message, the commit message will look nice without being too long.

**Comment by jcameron** [comment]
> Jamie, could you please always link a related commit to a ticket? Without it, it's more difficult to follow.

Generally I do, but sometimes I forget. Is there any way to add that linkage after commit though?

**Comment by iliajie** [comment]
> > Jamie, could you please always link a related commit to a ticket? Without it, it's more difficult to follow.
> 
> Generally I do, but sometimes I forget. Is there any way to add that linkage after commit though?

No, there’s no easy way to do it—editing a commit message in traditional sense isn’t really possible. However, you can find the commit, add a **comment** with the ticket link, and it will show up on the mentioned ticket...
