### ISSUE TITLE
Update to 2.021 installed lynx browser

### ISSUE THREAD

**Issue by kahomono** [webmin/webmin#1963]
My webmin on one machine just updated to 2.021 and the update included installation of lynx.    Which seems... odd.

I perused the changelog and could find no mention. 

Is this legit?

**Comment by kahomono** [comment]
oh hmm it looks like it's mentioned in pr 1915 but then why am I only getting it now?

**Comment by iliajie** [comment]
Well, `lynx` is a weak dependency for converting HTML emails to text. I used `lynx` because it produces the best results. If you want, you can remove it though.
