### ISSUE TITLE
Newkey repository stuck on 2.021

### ISSUE THREAD

**Issue by prilly-dev** [webmin/webmin#1965]
Seems there are some issues with the newkey repository, using this repository created with the script seems to work now after the key was changed a while back. anyway the release file says latest version is 2.021.

**Comment by jcameron** [comment]
Which Linux distribution are you on there?

**Comment by prilly-dev** [comment]
Debian bookworm

**Comment by PerunisGit** [comment]
I have the same issue but on Ubuntu 22.04

**Comment by jcameron** [comment]
Ok, give it a try now .. the repo has been fixed.

**Comment by prilly-dev** [comment]
Works, thank you
