### ISSUE TITLE
Webmin 2.100 update not showing up on Ubuntu Server 22.04.2 LTS

### ISSUE THREAD

**Issue by tweek11** [webmin/webmin#1967]
Noticed that version 2.100 was released - However when checking for the update on my Ubuntu 22.04.2 LTS Server (64 Bit) it does not show up and indicates i currently have the latest version of 2.021.

When click on the Webmin Configuration -> Upgrade Webmin with the option "Latest version from www.webmin.com" it returns "Failed to upgrade from www.webmin.com : You are already running the latest version of Webmin 

Also apt-cache returned the following:
apt-cache policy webmin
webmin:
Installed: 2.021
Candidate: 2.021
Version table:
*** 2.021 100
100 /var/lib/dpkg/status

This is a identical issue i posted about back in March via ticket #1859. Apparently you needed to update/rebuild something on the back-end. Than something with cache taking 24 hours to clear. 

So my question is as follows - which options below would you suggest for a long term resolution. I hate pestering you all with this issue.
1 - Should i just perform a dpkg -r webmin and reinstall? Or would the /etc/webmin/uninstall.sh be a better option.
Or
2 - If i were to run the setup-repos.sh would this be a viable solution - I'm hesitant on doing this without asking first. Since I'm not sure if it would create a conflict with repos and webmin originally being installed via dpkg package. 
  
Thank you for your time and consideration.

**Comment by jcameron** [comment]
Apologies, we didn't update the latest version on the Webmin website. Please try upgrading again now ..

**Comment by tweek11** [comment]
All good - Auto update option didn't appear on home screen. However running the manual update was successful. 

Thank you kindly.
Marking closed.
