### ISSUE TITLE
Feature Request: Select available PostgreSQL server

### ISSUE THREAD

**Issue by Co0olCat** [webmin/webmin#1968]
Hi,

Great project. I am long term user.

It would be great to allow selection of on of installed PostgreSQL servers. It should support as different versions installations, as well as same version multiple instances.

Thank you.

Kind regards,
TY

**Comment by jcameron** [comment]
Do you mean being able to select from multiple different versions of PostgreSQL that are installed? This is already possible by cloning the PostgreSQL module and then changing the configuration for each clone..

**Comment by Co0olCat** [comment]
Thank you. Cloning module is a solution, but I would prefer more elegant solution. Similar to Apache module. Thank you

**Comment by jcameron** [comment]
Cloning is the only supported solution in Webmin right now. You can do this at Webmin -> Webmin Configuration -> Webmin Modules -> Clone.

**Comment by Co0olCat** [comment]
NP. Thank you
