### ISSUE TITLE
borked upgrade on Fedora 38 -- key issues

### ISSUE THREAD

**Issue by FBachofner** [webmin/webmin#1969]
With multiple key-related problems upgrading Webmin (from 2.000 to 2.100) on Fedora 38 on one particular host, I manually deleted the two old gpg keys related to Webmin (one for Jamie, the other for Ilia)

now on `dnf upgrade` I get

> error: rpmdbNextIterator: skipping h#    3342 
> Header V4 DSA/SHA1 Signature, key ID 11f63c51: BAD
> Header SHA1 digest: OK
> error: Verifying a signature using certificate 1719003ACE3E5A41E2DE70DFD97A3AE911F63C51 (Jamie Cameron <jcameron@webmin.com>):
>   Key D97A3AE911F63C51 invalid: not signing capable
> error: rpmdbNextIterator: skipping h#    3342 
> Header V4 DSA/SHA1 Signature, key ID 11f63c51: BAD
> Header SHA1 digest: OK

Possibly _worse_, in anger about all the key problems I then manually deleted everything related to Webmin 2.000 and now dnf won't even let me "uninstall" it, so an "upgrade" may be the only way to repair this deplorable situation.

FYI, after deleting the old gpg keys and the old, wrong-key webmin repo and before discovering all these additional challenges, I did a `wget https://raw.githubusercontent.com/webmin/webmin/master/setup-repos.sh` and then ran the script AFTER having deleted the old keys.  The _new_ key is indeed in /etc/pki/rpm-gpg/

I still have "jcameron-key.asc" which might be of benefit in this situation but I am not sure how to get it back into use since there is no obvious analogue to apt's `sudo apt-key add` [ although I anticipate reading about gpg program options will help ]

Any advice would be appreciated.

**Comment by iliajie** [comment]
> I did a `wget https://raw.githubusercontent.com/webmin/webmin/master/setup-repos.sh` and then ran the script AFTER having deleted the old keys.

Infact, running `setup-repos.sh` script should be enough to correctly setup your Webmin repos.

What output do you get if running:

```
rpm -q --queryformat "%{SUMMARY}\n" $(rpm -q gpg-pubkey)
gpg --list-keys
```

**Comment by JustThat70** [comment]
I am having the same issue upgrading from 2.021 to 2.1 on fedora 38

Removing all webmin kleys from /etc/pki/rpm-gpg, downloading setup-repos.sh and running it did not resolve the issue. 

```
error: Verifying a signature using certificate 1719003ACE3E5A41E2DE70DFD97A3AE911F63C51 (Jamie Cameron <jcameron@webmin.com>):
  Key D97A3AE911F63C51 invalid: not signing capable
```

I was wondering if it might be related to https://discussion.fedoraproject.org/t/popular-third-party-rpms-fail-to-install-update-remove-due-to-security-policies-verification/70498. I tried setting the crypto-policy to "legacy" and rebooting but that did not help. 

Output of the requested commands:


```
 ᐅ rpm -q --queryformat "%{SUMMARY}\n" $(rpm -q gpg-pubkey)
RPM Fusion free repository for Fedora (2020) <rpmfusion-buildsys@lists.rpmfusion.org> public key
gpg(Vivaldi Package Composer KEY04 <packager@vivaldi.com>)
gpg(Jamie Cameron <jcameron@webmin.com>)
gpg(Fedora 27 (27) <fedora-27@fedoraproject.org>)
Fedora (32) <fedora-32-primary@fedoraproject.org> public key
gpg(Fedora (31) <fedora-31-primary@fedoraproject.org>)
Fedora (33) <fedora-33-primary@fedoraproject.org> public key
gpg(Vivaldi Package Composer KEY03 <packager@vivaldi.com>)
RPM Fusion free repository for Fedora (32) <rpmfusion-buildsys@lists.rpmfusion.org> public key
gpg(Fedora 28 (28) <fedora-28@fedoraproject.org>)
gpg(Fedora 29 (29) <fedora-29@fedoraproject.org>)
gpg(Fedora 26 Primary (26) <fedora-26-primary@fedoraproject.org>)
Fedora (34) <fedora-34-primary@fedoraproject.org> public key
gpg(Access Server (Access Server Package Key) <packaging@openvpn.net>)
Fedora (35) <fedora-35-primary@fedoraproject.org> public key
Fedora (36) <fedora-36-primary@fedoraproject.org> public key
Fedora (37) <fedora-37-primary@fedoraproject.org> public key
Fedora (38) <fedora-38-primary@fedoraproject.org> public key
Webmin Developers <developers@webmin.com> public key

 ᐅ gpg --list-keys
/root/.gnupg/pubring.gpg
------------------------
pub   dsa1024 2002-02-28 [SCA]
      1719003ACE3E5A41E2DE70DFD97A3AE911F63C51
uid           [ unknown] Jamie Cameron <jcameron@webmin.com>
sub   elg1024 2002-02-28 [E]

pub   rsa4096 2017-04-10 [SC]
      EC60F3DA9CB79ADCCF560D1F121E166DD9C821AB
uid           [ unknown] Ilia Rostovtsev <gpg@ilia.engineer>
uid           [ unknown] Ilia Rostovtsev <ilia@iliaross.ru>
uid           [ unknown] Ilia Rostovtsev <ilia@iliaross.io>
sub   rsa4096 2017-04-10 [E]

pub   rsa4096 2014-10-28 [SC]
      409B6B1796C275462A1703113804BB82D39DC0E3
uid           [ unknown] Michal Papis (RVM signing) <mpapis@gmail.com>
uid           [ unknown] Michal Papis <michal.papis@toptal.com>
uid           [ unknown] [jpeg image of size 5015]
sub   rsa2048 2015-11-02 [E]

```

**Comment by iliaross** [comment]
> I tried setting the crypto-policy to "legacy" and rebooting but that did not help.

Do not do it.

> pub   rsa4096 2017-04-10 [SC]
>      EC60F3DA9CB79ADCCF560D1F121E166DD9C821AB
> uid           [ unknown] Ilia Rostovtsev <gpg@ilia.engineer>
> uid           [ unknown] Ilia Rostovtsev <ilia@iliaross.ru>
> uid           [ unknown] Ilia Rostovtsev <ilia@iliaross.io>

That raises questions actually, as it seems that `gnupg_setup()` hasn't been running on your system. Did you update Webmin using UI, i.e. `upgrade.cgi` script .. I presume not .. or you were running Webmin upgrades using UI it in the past and then switched to using repos?

Anyway, I think you can try the following to fix your problem.

SSH to your server and run the following commands:

```
wget https://raw.githubusercontent.com/webmin/webmin/master/setup-repos.sh
sh setup-repos.sh
dnf clean all
dnf update
```

**Comment by JustThat70** [comment]
I was running upgrades in the UI and, when that failed with the same error I posted above, I tried using dnf.

I've already tried the steps you recommended and just tried them again. Same error

```
error: Verifying a signature using certificate 1719003ACE3E5A41E2DE70DFD97A3AE911F63C51 (Jamie Cameron <jcameron@webmin.com>):
  Key D97A3AE911F63C51 invalid: not signing capable
```

![image](https://github.com/webmin/webmin/assets/8411201/c883f6d5-2184-4038-b69e-bba486244b43)

**Comment by iliajie** [comment]
https://github.com/webmin/webmin/issues/1974#issuecomment-1666467760

**Comment by JustThat70** [comment]
The steps in #1974 worked for me but I had to upgrade from 2.100-1 to 2.101-1 using the same method. 

Thanks!

**Comment by iliajie** [comment]
> The steps in #1974 worked for me but I had to upgrade from 2.100-1 to 2.101-1 using the same method.

What error did you get exactly when upgrading Webmin 2.100 to 2.101 using UI?

**Comment by JustThat70** [comment]
Same certificate error as before. Wondering if the next update will still fail through the UI...

**Comment by JustThat70** [comment]
Apparently, 2.102 isn't signed either

![image](https://github.com/webmin/webmin/assets/8411201/51460af4-439d-45b6-886d-0a62f5f700bd)

**Comment by jcameron** [comment]
What if you try installing from this file instead : https://sourceforge.net/projects/webadmin/files/webmin/2.102/newkey/webmin-2.102-1.noarch.rpm/download

**Comment by FBachofner** [comment]
Hi @jcameron 

> What if you try installing from this file instead : https://sourceforge.net/projects/webadmin/files/webmin/2.102/newkey/webmin-2.102-1.noarch.rpm/download

I have just tried that as the upgrade still fails on multiple systems.

Here's what happens:

> Running transaction check
> error: Verifying a signature using certificate 1719003ACE3E5A41E2DE70DFD97A3AE911F63C51 (Jamie Cameron <jcameron@webmin.com>):
>   Key D97A3AE911F63C51 invalid: not signing capable
> error: rpmdbNextIterator: skipping h#    4703 
> Header V4 DSA/SHA1 Signature, key ID 11f63c51: BAD
> Header SHA256 digest: OK
> Header SHA1 digest: OK
> error: Verifying a signature using certificate 1719003ACE3E5A41E2DE70DFD97A3AE911F63C51 (Jamie Cameron <jcameron@webmin.com>):
>   Key D97A3AE911F63C51 invalid: not signing capable
> error: rpmdbNextIterator: skipping h#    4703 
> Header V4 DSA/SHA1 Signature, key ID 11f63c51: BAD
> Header SHA256 digest: OK
> Header SHA1 digest: OK
> Error: An rpm exception occurred: package not installed


I really hope this "growing pain" gets addressed soon.

**Comment by jcameron** [comment]
What does your /etc/yum.repos.d/webmin.repo file contain?

**Comment by FBachofner** [comment]
> [webmin-noarch]
> name=Webmin - noarch
> baseurl=https://download.webmin.com/download/newkey/yum
> enabled=1
> gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-webmin-developers
> gpgcheck=1

**Comment by JustThat70** [comment]
I was able to upgrade via yum/dnf.

Hope the in-app update gets fixed soon

**Comment by jcameron** [comment]
The next release will fix this by upgrading from files with the new key..

**Comment by FBachofner** [comment]
> I was able to upgrade via yum/dnf.
> 
> Hope the in-app update gets fixed soon

Where the upgrades fail for my systems, it fails regardless whether the in-app updater or the dnf updater is used.

Also, clearing everything out (repos, keys, etc.) has no positive effect.  That's the weirdest part.

Obviously a _fresh_ install (i.e. where there is zero prior Webmin installation or where the installed app has been completely removed -- including all config files when I tried that) does work.

**Comment by iliajie** [comment]
> Also, clearing everything out (repos, keys, etc.) has no positive effect. That's the weirdest part.

And what is so weird about it? Can you show the screenshot to see what and how fails?

**Comment by FBachofner** [comment]
> What does your /etc/yum.repos.d/webmin.repo file contain?

```
[webmin-noarch]
name=Webmin - noarch
baseurl=https://download.webmin.com/download/newkey/yum
enabled=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-webmin-developers
gpgcheck=1
```


I've still got an un-upgradeable mess on a number of systems, unfortunately.

Completely cleaning out old keys doesn't help either and makes webmin "unremovable"

**Comment by FBachofner** [comment]
What is the best way to completely remove webmin *manually* and also completely remove any and all OLD keys which might interfere with the installation of Webmin using the preferred method (i.e. using the setup-repos.sh  script)

**Comment by FBachofner** [comment]
> Anyway, I think you can try the following to fix your problem.
> 
> SSH to your server and run the following commands:
> 
> ```
> wget https://raw.githubusercontent.com/webmin/webmin/master/setup-repos.sh
> sh setup-repos.sh
> dnf clean all
> dnf update
> ```

So I just tried this as it seems quite a bit more "automated" than what I had tried on other hosts.

Here's the result:

`[redacted]$ sudo dnf update
Fedora 38 - x86_64                                                                                                                                       5.5 MB/s |  83 MB     00:15    
Fedora 38 openh264 (From Cisco) - x86_64                                                                                                                 2.6 kB/s | 2.5 kB     00:00    
Fedora Modular 38 - x86_64                                                                                                                               2.5 MB/s | 2.8 MB     00:01    
Fedora 38 - x86_64 - Updates                                                                                                                             1.4 MB/s |  33 MB     00:23    
Fedora Modular 38 - x86_64 - Updates                                                                                                                     1.2 MB/s | 2.1 MB     00:01    
Webmin - noarch                                                                                                                                          4.3 MB/s | 1.1 MB     00:00    
Dependencies resolved.
=========================================================================================================================================================================================
 Package                                         Architecture                         Version                                          Repository                                   Size
=========================================================================================================================================================================================
Upgrading:
 webmin                                          noarch                               2.102-1                                          webmin-noarch                                39 M
Installing group/module packages:
 libertas-firmware                               noarch                               20230919-1.fc38                                  updates                                     543 k
     replacing  libertas-usb8388-firmware.noarch 2:20230625-151.fc38

Transaction Summary
=========================================================================================================================================================================================
Install  1 Package
Upgrade  1 Package

Total download size: 39 M
Is this ok [y/N]: y
Downloading Packages:
(1/2): libertas-firmware-20230919-1.fc38.noarch.rpm                                                                                                      1.2 MB/s | 543 kB     00:00    
(2/2): webmin-2.102-1.noarch.rpm                                                                                                                          39 MB/s |  39 MB     00:00    
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                                                     33 MB/s |  39 MB     00:01     
Running transaction check
error: Verifying a signature using certificate 1719003ACE3E5A41E2DE70DFD97A3AE911F63C51 (Jamie Cameron <jcameron@webmin.com>):
  Key D97A3AE911F63C51 invalid: not signing capable
error: rpmdbNextIterator: skipping h#    4703 
Header V4 DSA/SHA1 Signature, key ID 11f63c51: BAD
Header SHA256 digest: OK
Header SHA1 digest: OK
error: Verifying a signature using certificate 1719003ACE3E5A41E2DE70DFD97A3AE911F63C51 (Jamie Cameron <jcameron@webmin.com>):
  Key D97A3AE911F63C51 invalid: not signing capable
error: rpmdbNextIterator: skipping h#    4703 
Header V4 DSA/SHA1 Signature, key ID 11f63c51: BAD
Header SHA256 digest: OK
Header SHA1 digest: OK
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: An rpm exception occurred: package not installed
`

The " libertas-firmware-20230919-1.fc38.noarch.rpm " installed fine, Webmin upgrade not

**Comment by FBachofner** [comment]
I HAVE to figure out a way to cleanly and _easily_ git rid of Webmin on a fairly large number of hosts and than successfully install (de novo) on Fedora 38 systems.

Users are really starting to complain that they see unresolved Webmin (i.e. pending) updates and I can't even ```dnf remove webmin``` successfully in 90+% of cases!

**Comment by chris001** [comment]
> I HAVE to figure out a way to cleanly and _easily_ git rid of Webmin on a fairly large number of hosts and then successfully install (de novo) on Fedora 38 systems.

After running `setup-repos.sh`, an ubuntu 22 system here was showing a serious error with `apt update`:
```
E: Conflicting values set for option Signed-By regarding source https://download.webmin.com/download/newkey/repository/ stable: /usr/share/keyrings/debian-webmin-developers.gpg != /usr/share/keyrings/ubuntu-webmin-developers.gpg
E: The list of sources could not be read.
```
...because there was a conflicting line in `/etc/apt/sourees.list`:
`deb [signed-by=/usr/share/keyrings/debian-webmin-developers.gpg] https://download.webmin.com/download/newkey/repository stable contrib`
The `debian-webmin-developers.gpg` key is different from the `ubuntu-webmin-developers.gpg` key.
So I commented out that `debian-webmin-developers.gpg` key.
Because in the file: `/etc/apt/sources.list.d/webmin.list`, it uses the ubuntu key to verify the webmin ubuntu repo.
Using only the ubuntu key, allowed the system to update itself and work normally.

Maybe you have a similar situation. 
Is it possible you have a `fedora` key in conflict with a different rpm distro key?

**Comment by iliajie** [comment]
> ...because there was a conflicting line in `/etc/apt/sourees.list`:
> `deb [signed-by=/usr/share/keyrings/debian-webmin-developers.gpg] https://download.webmin.com/download/newkey/repository stable contrib`
> The `debian-webmin-developers.gpg` key is different from the `ubuntu-webmin-developers.gpg` key.
> So I commented out that `debian-webmin-developers.gpg` key.

That cannot be right. The latest `setup-repos.sh` installs correct key, i.e. `/usr/share/keyrings/ubuntu-webmin-developers.gpg`.



> > SSH to your server and run the following commands:
> > ```
> > wget https://raw.githubusercontent.com/webmin/webmin/master/setup-repos.sh
> > sh setup-repos.sh
> > dnf clean all
> > dnf update
> > ```
> 
> So I just tried this as it seems quite a bit more "automated" than what I had tried on other hosts.
> 
> Here's the result:

It works for me just fine in Fedora 38! It must be some other unrelated problem.

**Comment by FBachofner** [comment]
> It works for me just fine in Fedora 38! It must be some other unrelated problem.

Multiple people have experienced problems, expressed here and elsewhere.

A post or so later I asked:
`What is the best way to completely remove webmin manually and also completely remove any and all OLD keys which might interfere with the installation of Webmin using the preferred method (i.e. using the setup-repos.sh script)`

At this point I don't care about maintaining _anything_ related to Webmin by "upgrading."

I want to remove it and then install de novo.

I can not even uninstall on Fedora.

This situation is completely insane!

**Comment by FBachofner** [comment]
>I want to remove it and then install de novo.
>I can now not even uninstall Webmin from Fedora.


OK, just to show: in general, no problem can withstand the "assault" of concentrated effort and properly applied, critical thinking.

Here's what has worked reliably on a fairly large number of _production_ systems so far (after quite a bit of trial and error on a non-critical system):
1. figure out _exactly_ which version of Webmin is installed: `sudo dnf list installed | grep webmin`
2. uninstall it with no mercy! `rpm -e --nosignature webmin-2.100-1.noarch`  [ using the version number from the prior output ]
- nota bene: there _may_ be another way to do this, but the `--nosignature` switch is what enabled me to reliably remove earlier versions of Webmin notwithstanding the signing key debaccle.  Conversely, `dnf remove webmin` and other variants failed every time
3. make *_sure_* the entry in the rpm/dnf DB is _purged_: `rpm -e --justdb webmin-2.100-1.noarch`
- NB: this does not seem to be required, but the feedback that the previous command resulted in removal of Webmin is comforting (and this only takes a couple seconds by merely editing the prior command using virtually any Linux terminal's "command recall")

the rest is pretty much as described earlier by @iliaross 

4. `wget https://raw.githubusercontent.com/webmin/webmin/master/setup-repos.sh`
5. `sh setup-repos.sh`
6. `dnf install webmin`

This results in what seems to be a proper, up-to-date installation of Webmin.

I'll report back as to whether dnf can update it properly when the next version is released.  [ I hope this issue can be kept open for a bit for this reason.  I'm also happy to help anyone who may be having similar issues, especially on Fedora. ]

**Comment by FBachofner** [comment]
FYI, the removal described by me above does _not_ seem to nuke /etc/webmin (which contains all the configuration data)

In each instance the new installation (i.e. 2.102-1 took on the previous configuration whether that was from 2.021 or another Webmin version)

I personally symlink /etc/webmin to another location (where we keep such configuration information in "one" place so it is easy to keep backed up), but this does not seem to be the reason for the maintenance of /etc/webmin on deletion.

One test system I was using to figure out a solution _did_ however, rename /etc/webmin to /etc/webmin.rpmsave (or similar) when I deleted Webmin.  [ _That_ system did not have /etc/webmin symlinked . . . ]

Your mileage may vary: if you want to maintain your Webmin config, back up /etc/webmin before removing Webmin and reinstalling!

Good luck, all!  :-)

**Comment by chris001** [comment]
> That cannot be right. The latest `setup-repos.sh` installs correct key, i.e. `/usr/share/keyrings/ubuntu-webmin-developers.gpg`.

It installed the correct key (`ubuntu-webmin-developers.gpg`) in `/etc/apt/sources.list.d/webmin.list`. However it didn't remove any other different/incorrect keys that were previously installed (`debian-webmin-developers.gpg`) in the main `/etc/apt/sources.list` file.

**Comment by iliajie** [comment]
It means you ran `setup-repos.sh` script more than once.

Also, even though the key `debian-webmin-developers.gpg` wasn't removed &mdash; what difference does it make? I agree it may be cleaner to remove it, however, it shouldn't have any practical effect.

**Comment by chris001** [comment]
I'd hope it t shouldn't have any practical effect, however, it had a huge effect.  The `apt update` failed and halted, without doing any update, while there were 2 different/conflicting keys, one key in the `sources.list` (the debian key) and the other in the `/etc/apt/sources.list.d/webmin.list` (the ubunutu key). The error was:
```
E: Conflicting values set for option Signed-By regarding source https://download.webmin.com/download/newkey/repository/ stable: /usr/share/keyrings/debian-webmin-developers.gpg != /usr/share/keyrings/ubuntu-webmin-developers.gpg
E: The list of sources could not be read.
```

**Comment by iliajie** [comment]
> one key in the `sources.list` (the debian key) and the other

But that _should_ never happen! We don't configure anything in `sources.list`. Did you configure it manually in `sources.list` files?

**Comment by chris001** [comment]
> > one key in the `sources.list` (the debian key) and the other
> 
> But that _should_ never happen! We don't configure anything in `sources.list`. Did you configure it manually in `sources.list` files?

Not manually.  For `sources.list` to have been configured, it was an official command line script or a copy-pasted series of commands that configured the debian key in there.

**Comment by iliajie** [comment]
I will fix `setup-repos.sh` to remove all other `webmin.com` repos before configuring a new one.

**Comment by FBachofner** [comment]
> I will fix `setup-repos.sh` to remove all other `webmin.com` repos before configuring a new one.

It would be great if it also removed antiquated keys (i.e. such as the one installed with jcameron-key.asc)

Reviewing my work from Saturday it seems at least some of the Fedora 38 production systems still have that key installed [even though I had (_attempted_ to, only, apparently) removed them]

This seems to be why upgrade/installation with dnf (and all other possible options short of force removal of prior versions) failed with a key error.

**Comment by FBachofner** [comment]
> Also, even though the key `debian-webmin-developers.gpg` wasn't removed — what difference does it make? I agree it may be cleaner to remove it, however, it shouldn't have any practical effect.

On over ten Fedora 38 systems it had a profound effect.

"Jamie Cameron <jcameron@webmin.com> public key" is still evident on each of these (even though I had attempted to remove them).

In each case, Webmin was not upgradeable/installable (regardless of method -- i.e. dnf upgrade, manual install with rpm or upgrade within webmin UI) until webmin was forcibly removed with bypassing of signature check (i.e. similar to `rpm -e --nosignature webmin-2.100-1.noarch` )

**Comment by iliajie** [comment]
> ot manually. For `sources.list` to have been configured, it was an official command line script or a copy-pasted series of commands that had the side-effect of having configured the `debian` key in there on ubuntu 22.

It will be fixed in the next release of `setup-repos.sh`. We will remove old Webmin repo from `sources.list` file.

> The "Jamie Cameron <[jcameron@webmin.com](mailto:jcameron@webmin.com)> public key" is still evident on each of these (even though I had attempted to remove them).

We don't configure new repos to use Jamie's old key.

**Comment by FBachofner** [comment]
> We don't configure new repos to use Jamie's old key.

I understand that.

The problem is that the key _remained_ even when deleting the old repos and even with manual key deletions (I recognize I may have done something incorrectly in that regard).

The existence of the OLD key seems to be the nexus of the failed updates and/or new installations which is why I [asked/suggested](https://github.com/webmin/webmin/issues/1969#issuecomment-1743376967) that the `setup-repos.sh` be reworked to include removal of any antiquated Webmin signing keys.

**Comment by FBachofner** [comment]
@jcameron & @iliaross 

Can this issue possibly be kept open?

As I mentioned:
>I'll report back as to whether dnf can update it properly when the next version is released. [ I hope this issue can be kept open for a bit for this reason. I'm also happy to help anyone who may be having similar issues, especially on Fedora. ]

**Comment by iliajie** [comment]
> The existence of the OLD key seems to be the nexus of the failed updates and/or new installations which is why I [asked/suggested](https://github.com/webmin/webmin/issues/1969#issuecomment-1743376967) that the `setup-repos.sh` be reworked to include removal of any antiquated Webmin signing keys.

No, it cannot be the problem, because you shouldn't even have old key on Fedora 38 installed. Also, `/etc/yum.repos.d/webmin.repo` file tells package manager which key should be used with `gpgkey=` directive ..
