### ISSUE TITLE
Proposal of adding two security improvements

### ISSUE THREAD

**Issue by qooob** [webmin/webmin#197]
Jamie, it would be very nice to have:
1. _The ability to return an empty_ respond for blocked hosts/users and other possible messages from Webmin's minserv. Just an option (Yes/No), that would let return no messages/text from `Minserv` at all.
2. Another option, could/should be added to `Webmin->Webmin Configuration->IP Access Control` that would let run arbitrary script (or just specified command) any time a user lands on `/session_login.cgi` page. Usually Webmin port is moved from default and port scan activity is blocked, nevertheless, it would be interesting to know by getting an email or sms (depending on what command is supplied in that script) if someone eventually landed on Webmin/Usermin login page. I realize it could be done by parsing `minserv.log` file but it's different story.. Like another option under `Also check TCP-wrappers hosts.allow and hosts.deny files?` with `Yes/No` and `input` box for the script path. It isn't very hard to do, right?

**Comment by jcameron** [comment]
1. So is the idea here that an attacker wouldn't know they are being blocked?

2. There are existing tools that can do this, like fail2ban - it analyses log files, and can run some script when certain messages (like a failed login) are detected.

**Comment by qooob** [comment]
1. Reason is that it's always more confusing for an attacker. It's like `drop` by iptables.

2. Analyzing log lines is fine, I know but having an option like that to notify admins on user landing on login page is an advantage., from my point of view.

**Comment by jcameron** [comment]
For 2, are you looking to be notified when there is a failed login, or when anyone just visits the login page? Because the latter could be pretty noisy..

**Comment by qooob** [comment]
No, failed login is something `fail2ban` or `csf` could and actually should do. No. It's just all about knowing the fact of landing on the page. What do you mean by noisy? :)

**Comment by jcameron** [comment]
By noisy, I mean that there are many attackers who randomly scan systems and request the root page of webservers. Every time one of them hits your system, you're going to get notified.

If you really do want this feature though, it could still be done using a fail2ban rule that watches /var/webmin/miniserv.log for requests to / and triggers an email (not a block) when this happens.

**Comment by qooob** [comment]
It could be noisy! :) But it's optional and could always be disabled. Besides, it wouldn't be noisy, if server already blocks IP for port scan and Webmin port is moved.. Alright. You don't feel like doing it? :) Maybe I should do it then, in my theme.. I just wanted to be global like.

**Comment by jcameron** [comment]
I certainly could add this, but I feel like it would be un-necessary duplication of effort when tools like fail2ban already exist to do the same thing.

**Comment by qooob** [comment]
I totally agree that it could be done by fail2ban and other tools.. but for me it seems that it would be better to have it done by Webmin means, rather than installing another app and keep it in memory just for that. Same good to have an option not to display minserv messages and act like `drop` in iptables. I don't want to insist too much, sorry. I just find it useful.

**Comment by qooob** [comment]
Jamie, what is your final answer on that? Rather no? :) I can easily make the 2 question work in the theme but I can't do much with the first one. I would like to propose to have such great feature for  *unauthorized/blocked user visits the login page*. 1. `Yes` - Show messages like they are shown now 2. `No` - return no messages and better do kind of like a DROP 

Quotation:
>DROP target for iptables rules. This can be set to either DROP ot REJECT.
REJECT will send back an error packet, DROP will not respond at all. REJECT
is more polite, however it does provide extra information to a hacker and
lets them know that a firewall is blocking their attempts. DROP hangs their
connection, thereby frustrating attempts to port scan the server.

So far you only have polite respond and having impolite is also very important!! :D
