### ISSUE TITLE
Redirect won't work for both domain and IP

### ISSUE THREAD

**Issue by nikkopt** [webmin/webmin#1970]
I have nginx reverse proxy working with webmin in order to access it through a domain.
Using
`redirect_port=443`
works fine when i login but sometimes i have my dns server down and have to access webmin through its IP address. Unfortunately it will also try to redirect to port 443 and fail to load.
Is there a way of having it work fine for both the IP and domain?
Haven't found anything online regarding this.

**Comment by jcameron** [comment]
Unfortunately not - webmin can only be accessed in either direct mode or proxy mode.

**Comment by iliajie** [comment]
Well, if you could allocated a private IP for Webmin to listen on and made Webmin listed on 443 port, then it could work ...

**Comment by nikkopt** [comment]
> Well, if you could allocated a private IP for Webmin to listen on and made Webmin listed on 443 port, then it could work ...

Not an option in my case, already have another service in that port.

**Comment by iliajie** [comment]
> Not an option in my case, already have another service in that port.

It wouldn't matter if that was a separate, a private IP address.

**Comment by nikkopt** [comment]
> > Not an option in my case, already have another service in that port.
> 
> It wouldn't matter if that was a separate, a private IP address.

You mean by creating a virtual nic?

**Comment by nikkopt** [comment]
> > You mean by creating a virtual nic?
> 
> Yep.

Thanks, gonna give it a try.
