### ISSUE TITLE
Apache: Document Options

### ISSUE THREAD

**Issue by iliajie** [webmin/webmin#1971]
Jamie, if we change **Follow symbolic links** option in **Apache: Document Options** page then Apache config gets `FollowSymLinks` option.

However, the problem is that there may already be options like:

```
Options -Indexes +IncludesNOEXEC +SymLinksIfOwnerMatch 
```

.. and Webmin Apache module just adds:

```
Options FollowSymLinks +IncludesNOEXEC -Indexes +SymLinksIfOwnerMatch
```

.. and that will make Apache not to start, e.g.:

```
AH00526: Syntax error on line 57 of /etc/apache2/sites-enabled/ubuntu22-pro.virtualmin.dev.con> ....
ubuntu22-pro.virtualmin.dev apachectl[79775]: Either all Options must start with + or -, or no Option may.
```

So, the fix for this exact issue is changing edited config file from:

```
Options FollowSymLinks +IncludesNOEXEC -Indexes +SymLinksIfOwnerMatch
```

.. to:

```
Options +FollowSymLinks +IncludesNOEXEC -Indexes +SymLinksIfOwnerMatch
```

Can Webmin Apache module be changed to do that automatically?

**Comment by jcameron** [comment]
I've checked in a fix to prevent this kind of incompatible option setting from being saved..

**Comment by iliajie** [comment]
Thanks.

I have given a test to this patch but I couldn't change the option at all, e.g.:

<img width="1440" alt="image" src="https://github.com/webmin/webmin/assets/4426533/d30577e2-6b01-49ba-b75c-38ab5183a513">

**Comment by iliajie** [comment]
However, it seems to work with **Enable** option (while not with **Yes**). Is this expected?

**Comment by webmin** [comment]
Can you post a screenshot of the previous page showing which settings you had selected?

**Comment by iliajie** [comment]
Yes, sure:

<img width="1438" alt="image" src="https://github.com/webmin/webmin/assets/4426533/d63812c6-a815-40cf-b936-0a56679d1097">

So, in example of **Follow symbolic links** &mdash; all available options, i.e. **No**, **Enable** and **Disable** can be changed/saved and Webmin writes correct configs. Using **Yes** option doesn't work until all other options are switched to be either **Yes** or **No**.

In the end your code does _everything_ correctly, it's just that it's super complicated to grasp the point without playing around with it first and looking at config changes. 

I will change the error message a bit to help making it easier to understand.
