### ISSUE TITLE
Module development: "head-stuff" and "body-stuff" are ignored in &header method calls

### ISSUE THREAD

**Issue by klugerama** [webmin/webmin#1977]
I hope I'm doing it correctly, but calling `header(title, image, [help], [config], [nomodule], [nowebmin], [rightside], [head-stuff], [body-stuff], [below])` doesn't seem to include anything in the `<head>` block or `<body>` tag, no matter what I put for those values.

It appears to work correctly with the Legacy theme, but not with `authentic-theme`; although I suspect the issue is not with the theme code itself. I'm not smart enough to figure out how `header` is actually being called.

I tried adding some `print` statements into the `header` method in `web-lib-funcs.pl` (and restarting webmin), but the only argument value that appears to show up is the title (`@_[0]`). The other arguments (such as `rightside` and `below`) seem to work as intended, but don't show up when I try to `print` them from that method so there must be some other processing occurring prior to that code executing that is not including the `head-stuff` and `body-stuff` values in the resulting call.

**Comment by iliajie** [comment]
Hello,

Can you show some code which fails to work?

**Comment by klugerama** [comment]
`&header($text{"index_title"}, "", "intro", 1, 0, 0, &restart_button(), "<script type='text/javascript'>//test</script>", "body-stuff-test", $text{"index_dns_servers"});`

This is from `[dns_servers.cgi](https://github.com/klugerama/webmin-dnsmasq/blob/main/dnsmasq/dns_servers.cgi)` in my repo https://github.com/klugerama/webmin-dnsmasq

**Comment by iliajie** [comment]
I don't see much issues there. It loads for me with minimal tweaks, e.g.:

<img width="1440" alt="image" src="https://github.com/webmin/webmin/assets/4426533/f611d502-943b-4793-ab04-f1ebe3220585">

What error do you see exactly?

**Comment by klugerama** [comment]
There's no error, it just doesn't add anything the `<head>` block.

Yes, it mostly works right now because I have workarounds in my code to add scripts and CSS in the body, but it would be a lot cleaner and generally better if I could put them in the `<head>' block. Particularly because there appears to be processing that occurs after loading/rendering, and I wouldn't have to kludge up so much re-formatting _after_ it's already been modified by the theme's js/css.

One of the things I'm trying to accomplish is editing in a modal window. This package has a _lot_ of values that can be specified multiple times, so showing them in a list makes sense. But each value contains several properties, so using webmin's `popup_window_*` isn't ideal.

Instead I made my own actual popup windows, but I'm trying to adapt it to use modals. I find myself adding lots of scripts here and there, and employing the use of `$(document).ready(function() { setTimeout(function() { }, 10); });` which feels very kludgy. I have to add that to every page. It seems like it would be better if I could put all my js into a js file, and all my css into a css file and include them in the `<head>`.

**Comment by iliajie** [comment]
Can you show me the exact code that works in Gray Theme and doesn't work/display in Authentic Theme, and adding screenshots as well? I don't understand the problem fully.

You mentioned `dns_servers.cgi` wasn't working, how exactly it doesn't work?

**Comment by klugerama** [comment]
```
<meta name="msapplication-TileColor" content="#003374">
<meta name="theme-color" content="#003374">
<script src="/service-worker.js" defer></script>
<link data-link-ref crossorigin="use-credentials" rel="manifest" href="/manifest-webmin.json">
<title>Webmin</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
    --- here is where I expect to find my "head-stuff", but there's nothing --
<script src="/unauthenticated/js/defaults.js?214000009999999999"></script>
<script>theme_server_data_available_acls="/bin/getfacl";theme_server_data_available_selinux=0;</script>
```
![image](https://github.com/webmin/webmin/assets/513715/3222e722-39f8-46f0-9b37-c068d62a60ad)
![image](https://github.com/webmin/webmin/assets/513715/637d0f4c-4f23-495f-9a99-0f16b128bdfa)

This should have `body-stuff-test` as an attribute, but doesn't:
![image](https://github.com/webmin/webmin/assets/513715/e4bf4180-32dd-474a-b16d-afa17fc96cce)

Now, with legacy theme:
![image](https://github.com/webmin/webmin/assets/513715/e829a826-dcd3-4ec0-bbf7-e8c5ecfbdbc3)

I hope that makes things a little clearer.

**Comment by klugerama** [comment]
To clarify further: I would like to have a css file included in the `<head>` section, so that I don't have to add `style` attributes to everything all over my code.

I would like to put all my scripts into a `.js` file that I can include in the `<head>` section so that:
1. I can have all my javascript in one place
2. Some things can be executed prior to webmin js execution, which appears to do a lot of runtime refactoring
3. I don't have multiple "conflicting" scripts in a page, as they may get added programmatically - even though they don't really conflict (I think). Although this last issue is less important.

**Comment by iliajie** [comment]
Hello again, and sorry for the late reply!

I have taken a closer look to my code and unfortunately neither `head-stuff` nor `body-stuff` will work properly! Authentic theme is SPA (Single Page Application) and it just doesn't reload neither head nor body, as it's loaded only once on the initial page load, and without any use of the modules.

Also, you should rather use `ui_print_header` instead of calling `header` function directly.

For the integration of your custom JavaScript and CSS, a plausible solution would be to embed the `<script>` and `<style>` tags immediately post the execution of the `ui_print_header` function (or `header`, in your current implementation). This ensures that your code is recognized and incorporated across all themes.

Besides, you might want to consider positioning the `<style>` tag immediately following the header invocation and placing the `<script>` tag just prior to the footer. This guarantees that all DOM elements are available for your JavaScript code's reference.

**Comment by klugerama** [comment]
@iliaross I see, thank you for checking.

I will do what I can with this advice. I appreciate it.
