### ISSUE TITLE
Editing Config Files - Directories are wrongly associated with files

### ISSUE THREAD

**Issue by ADDISON74** [webmin/webmin#1978]
Bellow is the Postfix configuration directory listing in my case. Please note that it contains both files and directories.

![directory_list](https://github.com/webmin/webmin/assets/8360474/d41acf85-0d68-4c16-b34e-b2f260eafa1f)

Now go to **```Webmin > Servers > Postfix Mail Server```** then choose **[Edit Config Files]**.  Take a look at the dropdown list where you can select files for editing and notice that the 4 directories also appear. iI I choose from the list **/etc/postfix/access**, which is a directory, obviously it doesn't contain anything.

![edit_configuration](https://github.com/webmin/webmin/assets/8360474/df989ba4-a9bd-496b-85ec-de6d867e5939)

**The following issues occur**

1. The save will not be completed, an error message "Failed to save config file: Cannot write to directory /etc/postfix/access will be displayed.

2. Files in these directories cannot be edited. If it is too complicated for the files to be displayed in the dropdown list, then the directories should no longer be displayed to avoid a lack of logic. Or they can be displayed in the list but appear as disabled, they cannot be loaded for editing.

I haven't checked other sections where configuration files can be edited, but I think the situation is similar. possible also in Virtualmin, Cloudmin.

**Comment by iliajie** [comment]
Thanks for the heads up. We will fix this in the next Webmin 2.102 release.

**Comment by addison74** [comment]
@iliaross - I appreciate your help. Did you check if this issue is found in other sections in Webmin/Virtualmin?

**Comment by iliajie** [comment]
I didn't check, as I don't remember this happening anywhere else. Although, if you find anything, please let us know!

**Comment by ADDISON74** [comment]
Could you please take a look to this search result? 

https://github.com/search?q=repo%3Awebmin%2Fwebmin+print+%26ui_select%28%22file%22&type=code

You know better than me what pattern to look for related to this change.

**Comment by iliajie** [comment]
Thanks, Cron module has similar issue. Fixed now!

**Comment by ADDISON74** [comment]
@iliajie - I have identified several sections where you need to make changes. I will make a list for you in another post so you can easily check them off.

**Comment by addison74** [comment]
@iliaross - I posted here https://github.com/webmin/webmin/issues/1979 the list of other sections where I identified the same issue.

**Comment by iliajie** [comment]
Got it, thanks!
