### ISSUE TITLE
Editing Config Files - Directories should not be listed with files

### ISSUE THREAD

**Issue by ADDISON74** [webmin/webmin#1979]
Checking all the sections in Webmin and Virtualmin I think I have identified all the issues that are similar to the one described here https://github.com/webmin/webmin/issues/1978.

I used checkboxes to make it easier to check the solved ones in the list.

### WEBMIN
- [x] ```Servers > Apache Webserver > Edit Config Files```
- [x] ```Servers > BIND DNS Server > Edit Config Files```
- [x] ```Servers > Dovecot IMAP/POP3 Server > Edit Config Files```
- [x] ```Servers > MariaDB Database Server > Edit Config Files```
- [x] ```Servers > ProFTPD Server > Edit Config Files```
- [x] ```Servers > SpamAssassin Mail Filter > Edit Config Files```
- [x] ```Servers > SSH Server > Edit Config Files```
- [x] ```Networking > Apache Webserver > Edit Config Files```
- [x] ```Networking > Fail2Ban Intrusion Detector > Edit Config Files```

### VIRTUALMIN
 - [x] ```Services > SpamAssassin Configuration > Edit Config Files```

**Comment by iliajie** [comment]
Alright, thanks! All done!

**Comment by ADDISON74** [comment]
We should analyze from a logical point of view this feature in Webmin/Virtualim, editing of the configuration files. As it is implemented now it is obvious that it needs the modification reported by me.

However, not all services that Webmin manages have all their configuration files in a single directory. For example, in the case of Dovecot, there is a part in /etc/dovecot, but other important files are located in /etc/dovecot/conf.d. If you want to make a change to the SSL component then you will do it by editing 10-ssl.conf.

I think that dropdown list should contain in alphabetical order both the files from the current directory and the files from one level bellow in the tree.
