### ISSUE TITLE
Editing Config Files - Only the files from the first level of the directory can be edited

### ISSUE THREAD

**Issue by ADDISON74** [webmin/webmin#1980]
This issue is related to
 - https://github.com/webmin/webmin/issues/1978
 - https://github.com/webmin/webmin/issues/197
 
 We should analyze from a logical perspective the editing of the configuration files feature in Webmin/Virtualmin, As it was implemented initially it is obvious that it needed the change to exclude editing directories as a files.

However, not all services that Webmin manages have all their configuration files in a single directory. For example, in the case of Dovecot, there is a part in /etc/dovecot, but other important files are located in /etc/dovecot/conf.d. If you want to make a change to the SSL component then you will do it by editing 10-ssl.conf. Even it is a configuration file it cannot be edited in this section.

I think that dropdown list should join in alphabetical order the files from the current directory and the files from one level bellow in the tree. For example

dovecot.conf
dovecot-dict-auth.conf.ext
dovecot-dict-sql.conf.ext
dovecot.pem
dovecot-sql.conf.ex
conf.d/10-auth.conf
conf.d/10-director.conf
...
conf.d/auth-vpopmail.conf.ext

Another variant would be to open that main directory for editing in File Manager.

**Comment by iliajie** [comment]
Thanks.

However, I see no value in sorting config files, as there is a search in the select already. 

Opening in File Manager - may be a good option.

**Comment by iliajie** [comment]
> Opening in File Manager - may be a good option.

I forgot that we already can detach to a separate editor, so opening it in the File Manager wouldn't have much value.

**Comment by ADDISON74** [comment]
If your replies refer to those buttons below circled by me

![editconfig](https://github.com/webmin/webmin/assets/8360474/618b9d76-1718-419b-9581-8f8960082716)

**```The button on the left```**: searches for a text in all the files in the list, not in others at the same level or bellow

![seach](https://github.com/webmin/webmin/assets/8360474/23c69b26-e81c-4086-a2ca-dd5e933a93b2)

**```The right button```**: opens the active file as an option in the list for editing

![edit](https://github.com/webmin/webmin/assets/8360474/120ccd83-8cfe-4a84-8313-fff5d8830ef4)

From what I checked more in detail, in the case of Dovecot, you have taken into account to list the configuration files from **conf.d** directory too. It is probably also valid for other services. 

In this case, the idea from which I started in the report was not a correct one. In fact, you use the directories created at the installation, not others created later by the user.
