### ISSUE TITLE
User specific theme, locale and language for sudo-capable users

### ISSUE THREAD

**Issue by iliajie** [webmin/webmin#1982]
Jamie, shouldn't we make Webmin aware of sudo-capable users, which are logged in to Webmin to use specific theme, locale and language, i.e. defined in **Webmin ⇾ Change Language and Theme** module?

Currently, it makes impossible to save the `locale_sudocapableusername` or `theme_sudocapableusername` option correctly, as it all saved like `locale_root` or `theme_root`, i.e. using `$base_remote_user` variable.

**Comment by jcameron** [comment]
That's not a bad idea - it would be nice if sudo-capable users could each have their own settings. I guess most of the time this isn't an issue because a typical system only has one user with permissions to sudo to root..

**Comment by iliajie** [comment]
> I guess most of the time this isn't an issue because a typical system only has one user with permissions to sudo to root.

I think you're right. In fact, most use cases would simply involve creating another privileged Webmin user.
