### ISSUE TITLE
Status monitor is enabled by default but not configured

### ISSUE THREAD

**Issue by PitWenkin** [webmin/webmin#1985]
Due to #1984 I became aware that there exists a cronjob, that is executed every 5 minutes by default, which checks if certain services are running.

Apparently all it it supposed to due is [send an email](https://github.com/webmin/webmin/issues/1984#issuecomment-1681562412) when a service is down. Unfortunately the default setup seems to be to "Don't send email"

If this monitoring is enabled by default it should either:
Nag the administrator to properly configure it or send the email to a default address (root ?)

**Comment by jcameron** [comment]
Even if that script doesn't send email, it does update the page showing the results from the most recent checks. So it's legit to run it without emailing...

**Comment by PitWenkin** [comment]
Fair point.

This has nothing to do with the [Servers Status on the Dashboard of virtualmin](https://github.com/virtualmin/virtualmin-gpl/blob/225a693d6052f27397b091ecf3709331173c0fa9/system_info.pl#L257) ?

**Comment by jcameron** [comment]
No, that's different ... it shows the status of various servers known to Virtualmin.
