### ISSUE TITLE
Fail2Ban configuration issues

### ISSUE THREAD

**Issue by Flying--Dutchman** [webmin/webmin#1992]
While setting up a custom fail2ban jail, I noticed that `backend` config property inside `jail.conf` had been set to `systemd`. Therefore, my logfile-based jail did not parse the given logfile. 

Things that I noticed in the fail2ban module:

- Fail2Ban > Filter Action Jails > Edit Jail Defaults
    - `systemd` is missing for the option `Check for log file updates using` ( = `backend`)
    - Saving on that page did break fail2ban for me, as it stored the default drop-down value for `backend` 
    - (there was no logfile given for the default `sshd` jail, therefore fail2ban was not able to start afterwards)
    - Had to manually revert the config back to `backend = systemd`
-  Fail2Ban > Filter Action Jails > Edit Jail
    - There is no option to set the `backend` for the current jail, therefore the default `systemd` will be used
    - Even when given a logfile path, `backend` is not set accordingly (e.g. `auto`)
- At some point prior my custom jail did work "out of the box"
    - I would guess that the `backend` property has been changed 
        - while updating the default `bitwarden` filter
        - or while saving on the `Global Settings` page 
- While updating the `bitwarden` filter, changes are stored in the `jail.conf`, not in the `jail.local` file

Webmin version: 2.101
OS: Debian 11

**Comment by iliajie** [comment]
Hello,

Thanks for the heads up! You're right. It's a bug! It will be fixed in the next Webmin release.
