### ISSUE TITLE
Preserving IP to Webmin from an Apache Proxy

### ISSUE THREAD

**Issue by Preloading** [webmin/webmin#1994]
Hi there!

I've been trying to get my Apache proxy to pass IPs of connected users. Currently, the connected users all show 127.0.0.1
![image](https://github.com/webmin/webmin/assets/60761520/d279bc11-ea03-4db3-9d68-fd0e51a19ce1)
I am not connecting via 127.0.0.1 although I am actually connected from 10.0.0.75, so it should look like this:
![image](https://github.com/webmin/webmin/assets/60761520/ae32c5c4-c902-46b0-bc68-267c5830e526)
I cannot figure out how to get webmin to properly detect these ips. I have followed [the faq](https://webmin.com/faq/#can-i-run-webmin-or-usermin-behind-reverse-proxy)

Here is my apache config:
```
<VirtualHost *:443>
    ServerName webmin.example.com

    # Enable the usage of the SSL/TLS protocol engines
    SSLEngine on
    SSLProxyEngine on

    # Point to files with SSL certificates for virtual host
    SSLCertificateFile /etc/letsencrypt/live/example.com/fullchain.pem
    SSLCertificateKeyFile /etc/letsencrypt/live/example.com/privkey.pem

    # Use only secure version of the TLS protocol (TLSv1.3)
    SSLProtocol         all -SSLv3 -TLSv1 -TLSv1.1 -TLSv1.2
    SSLHonorCipherOrder off
    SSLSessionTickets   off

    # Disables the remote server certificate checks
    # (only needed for self-signed certificates)
    SSLProxyCheckPeerCN     off
    SSLProxyCheckPeerName   off
    SSLProxyCheckPeerExpire off

    # Disable proxying for all /.well-known requests. It will 
    # only be useful, if a domain has "DocumentRoot" defined
    ProxyPass /.well-known !

    # Proxying both HTTP and websockets at the same time,
    # where the websockets URL's are not websocket-only
    # or not known in advance
    ProxyPass / https://localhost:10000/
    RewriteEngine on
    ProxyPreserveHost On
    RewriteCond %{HTTP:Upgrade} websocket [NC]
    RewriteCond %{HTTP:Connection} upgrade [NC]
    RewriteRule ^/?(.*) "wss://localhost:10000/$1" [P,L]

    RewriteEngine On 
    RewriteCond %{HTTPS} off 
    RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI}
</VirtualHost>
```

Any help would be appreciated!

**Comment by iliajie** [comment]
Hello,

Have a look at **Webmin ⇾ Webmin Configuration: IP Access Control** and **Trust remote IP address provided by proxies?** option.

**Comment by Preloading** [comment]
> Hello,
> 
> Have a look at **Webmin ⇾ Webmin Configuration: IP Access Control** and **Trust remote IP address provided by proxies?** option.

Ah, that fixed it! Thanks!
