### ISSUE TITLE
Webmin Name Change in Menu

### ISSUE THREAD

**Issue by qusaialhaddad** [webmin/webmin#1996]
Hi, 

how to change the Webmin name in the top left menu ?

Regards,
![Screenshot 2023-09-04 104511](https://github.com/webmin/webmin/assets/9527146/3a33e6b0-8484-4824-a571-d8bcb7a77f83)

**Comment by iliajie** [comment]
Hello, Qusai!

This can be easily done as explained in this post https://github.com/webmin/authentic-theme/issues/639#issuecomment-271138852.
