### ISSUE TITLE
Tab title - Select content to show

### ISSUE THREAD

**Issue by wingarmac** [webmin/webmin#1998]
Hi,

I would like to know if there's a way to shows in each tab:

- "menu interface name - Webmin version"
... instead of ...
-  "hostname - Webmin menu"  ?

In this screenshot of my main VPN intranet page I can see wich Wireguard/Webmin hosts are connected/available.

Only my 2 ubuntu servers are connected in that specific screenshot and a tab to there respectif Webmin interface is shown:

![image](https://github.com/webmin/webmin/assets/78303089/c3c1e556-bfd7-4a2d-8464-18aaa051c2bd)

The problem is that I can't see wich host it is before clicking the tab. with one or 2 hosts it's ok, but with more it is inconvinient and it would be verry nice to have their respective hostname as tab-title for each Webmin session with the selected menu interface as the Webmin version is lesser important in that case.

Thanks in advance for your answer !
Cheers !

**Comment by iliajie** [comment]
Hello,

The title for Webmin instance can be changed at **Theme Configuration: General defaults -> Document title format** page.

**Comment by wingarmac** [comment]
These are the Webmin settings available:

- IP Access Control
- Ports and Addresses
- Logging
- Proxy Servers and Downloads
- User Interface
- Webmin Modules
- Operating System and Environment
- Language and Locale
- Index Page Options
- Upgrade Webmin
- Authentication
- Two-Factor Authentication
- Reassign Modules
- Edit Categories
- Module Titles
- Webmin Themes
- Trusted Referrers
- Anonymous Module Access
- File Locking
- Mobile Device Options
- Blocked Hosts and Users
- Background Status Collection
- Advanced Options
- Debugging Log File
- Web Server Options
- Webmin Scheduled Functions
- Sending Email
- SSL Encryption
- Certificate Authority

In "User interface" "Real hostname" is selected.
No "Theme   Configuretion" but I've found "Webmin themes" where I can select, install, delete or export a theme.
But not what I'm looking for ...
I've tried to search for "Theme configuration" or "title format" in the Webmin search with no results for both.
Any other clues?

I prefer to edit a configuration file to edit if possible. I use Webmin to monitor rather as to setup my hosts.

Thanks anyway for trying to help !

**Comment by wingarmac** [comment]
Done !
![image](https://github.com/webmin/webmin/assets/78303089/5e87c335-b2cf-432f-8bbb-e4eafc301907)

Many thanks !

**Comment by iliajie** [comment]
> Many thanks !

You are welcome!
