### ISSUE TITLE
Custom Commands: Dropdown menu doesn't show options

### ISSUE THREAD

**Issue by iliajie** [webmin/webmin#1999]
Jamie, hello!

If I use this as a custom command:

```
dhcp_release eth1 $(grep -i $mac /var/lib/misc/dnsmasq.leases | awk '{print $3}') $mac
Remove DHCP lease
root 0 1 0 0 0 0 0 -
mac:9:cat /var/lib/misc/dnsmasq.leases | awk '{print $2" "$3" "$4}' | sort -k 2 -V |:1,1:Device ID
```

e.g.:

<img width="1158" alt="image" src="https://github.com/webmin/webmin/assets/4426533/2a56578f-f298-4db1-a0c5-28f0c2563ff1">

.. then the menu is empty on the main page:

<img width="204" alt="image" src="https://github.com/webmin/webmin/assets/4426533/6aff8b43-e278-4e10-b732-0668d1cb2eff">

**Comment by jcameron** [comment]
What does the command `cat /var/lib/misc/dnsmasq.leases | awk '{print $2" "$3" "$4}' | sort -k 2 -V |:1,1:Device ID` output when you run it?

Also, can you create a command without any `:` characters in it? That is probably messing up Webmin due to the file format used for custom commands..

**Comment by iliajie** [comment]
Oh, I see! It was an issue with the file containing the menu. Sorry about that!
