### ISSUE TITLE
Class not found exception when starting Java applet - File manager

### ISSUE THREAD

**Issue by milosdjakonovic** [webmin/webmin#200]
Tested with latest version of x64 Java, IE11, Chrome-latest, FF latest.
File manager crashes during loading.

**Comment by jcameron** [comment]
On which operating system and version?

**Comment by milosdjakonovic** [comment]
Ubuntu Linux 12.04.5
Linux 3.13.0-32-generic on i686

**Comment by milosdjakonovic** [comment]
Here is additional info
(error report)

Java Plug-in 11.31.2.13
Using JRE version 1.8.0_31-b13 Java HotSpot(TM) Client VM
User home directory = C:\Users\Milos
----------------------------------------------------
c:   clear console window
f:   finalize objects on finalization queue
g:   garbage collect
h:   display this help message
l:   dump classloader list
m:   print memory usage
o:   trigger logging
q:   hide console
r:   reload policy configuration
s:   dump system and deployment properties
t:   dump thread list
v:   dump thread stack
x:   clear classloader cache
0-5: set trace level to <n>
----------------------------------------------------
CacheEntry[http://crl.cacert.org/revoke.crl]: updateAvailable=true,lastModified=Sat Apr 04 16:33:58 CEST 2015,length=7216173

**Comment by jcameron** [comment]
Also, what gets logged to /var/webmin/miniserv.log when you open the file manager?

**Comment by milosdjakonovic** [comment]
On desktop machine I'm currently working, I can't reproduce 'Class not found exception' type of error, instead, it just stops while Java is loading. I'll check from my home machine, maybe there is difference for which I do not know about.

For now, here is single log line written during attempt of loading File Manager:
>(my ip address) - milos [07/Apr/2015:09:50:31 +0200] "GET /file/ HTTP/1.1" 200 3925

and nothing happens further, before I quit attempt.

**Comment by jcameron** [comment]
Perhaps some kind of proxy is blocking access to Java applets?

**Comment by milosdjakonovic** [comment]
I wouldn't know which kind of proxy would block access to Java applets.
I can't think of something unusual I was doing when installing & configuring Webmin.

**Comment by milosdjakonovic** [comment]
Yeah. I can confirm now that something wrong is on my side. Wait for a minute more.

**Comment by milosdjakonovic** [comment]
The very same "Class not found exception" error I got from:

totally different environment - Ubuntu Linux 14.04.2 Intel(R) Core(TM) i7-3930K CPU @ 3.20GHz, 2 cores

different origin-build of Webmin - in first case I was installing .deb package and in second I've downloaded latest release from Github and installed setup.sh script

Since results are the same, I can only conclude, for now, that something is wrong on my side - if Webmin File Manager is working somewhere. I'm not sure what it can be and what kind of proxy you was talking about.

**Comment by jcameron** [comment]
Given how there is no entry in the Webmin miniserv.log file for an attempt to even load the class file, I'd suspect a proxy - unless you are accessing Webmin from a browser on the very same machine?

**Comment by ediazrod** [comment]
Same happen to me webmin last version 1.750 Debian 7 I am getting ClassnotFoundException for Filemanager
