### ISSUE TITLE
Network Unreachable

### ISSUE THREAD

**Issue by BigLOnline** [webmin/webmin#2000]
"Setup repository? (y/N) y
  Downloading Webmin key ..
  ..failed : failed: Network is unreachable. failed: Network is unreachable. "

**Comment by BigLOnline** [comment]
Ign:1 https://download.webmin.com/download/newkey/repository stable InRelease
Err:2 https://download.webmin.com/download/newkey/repository stable Release
  Cannot initiate the connection to download.webmin.com:443 (104.207.151.13). - connect (101: Network is unreachable) Cannot initiate the connection to download.webmin.com:443 (45.76.69.64). - connect (101: Network is unreachable)
Hit:3 http://deb.debian.org/debian bookworm InRelease                 
Hit:4 http://deb.debian.org/debian bookworm-updates InRelease                                                                                                                                                                  
Hit:5 https://download.docker.com/linux/debian bookworm InRelease                                                                                                                                                              
Hit:6 http://security.debian.org/debian-security bookworm-security InRelease                                                                                                                                                   
Get:7 https://pkgs.tailscale.com/stable/debian bookworm InRelease                                                                                    
Hit:8 https://packagecloud.io/ookla/speedtest-cli/debian bookworm InRelease                     
Reading package lists... Done
E: The repository 'https://download.webmin.com/download/newkey/repository stable Release' no longer has a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by jcameron** [comment]
Are you still seeing these errors? We have two mirrors of download.webmin.com on different networks, and as far as I can tell they are both up right now..

**Comment by BigLOnline** [comment]
Checking now, thank you for your time in response regarding this issue sir.

**Comment by BigLOnline** [comment]
![Screenshot_20230909-130142.png](https://github.com/webmin/webmin/assets/70815584/11a5dedc-542f-4644-a168-799d882587c7)

Unfortunately error persists

**Comment by jcameron** [comment]
What output do you get if you run `traceroute download1.webmin.com`

**Comment by BigLOnline** [comment]
Hello sir. Here's in response to last question. ![Screenshot_20230909-131302.png](https://github.com/webmin/webmin/assets/70815584/5f78bff9-aee3-4cc1-841f-4c106539597d)

**Comment by jcameron** [comment]
Hmmm ... can you traceroute to any external address? What if you run `traceroute github.com`

**Comment by BigLOnline** [comment]
Hello sir. Here's in response to following ask. ![Screenshot_20230909-141748.png](https://github.com/webmin/webmin/assets/70815584/936c12cb-a41b-4745-8f07-943eb3f9f68f)

**Comment by chris001** [comment]
What's the output of:
`cat /etc/network/interfaces`

**Comment by BigLOnline** [comment]
# This file describes the network interfaces available on your system
# and how to activate them. For more information, see interfaces(5).

source /etc/network/interfaces.d/*

# The loopback network interface
auto lo
iface lo inet loopback

# The primary network interface
allow-hotplug wlp6s0
iface wlp6s0 inet dhcp
        wpa-ssid REDACTED
        wpa-psk  REDACTED

**Comment by chris001** [comment]
Can you edit that file with the command `nano /etc/network/interfaces`.
After the line `iface wlp6s0 inet dhcp`, 
add the line: `iface wlp6s0 inet dhcp6`.
Then run the commands:
```
ifdown wlp6s0
ifup wlp6s0
ping yahoo.com
```
To stop the `ping`, press `Ctrl C`.

**Comment by BigLOnline** [comment]
its releasing an ip i need. the server has dropped offline, new ip has been assigned after upping iface

**Comment by BigLOnline** [comment]
Yeah that fucked the whole entire server. How are you maintaining webmin?

**Comment by BigLOnline** [comment]
I fixed the server asking DHCP for ip again. Running the command you asked me to run shit  my server down

**Comment by chris001** [comment]
This isn't a bug, it's an issue with configuring your webmin server's WiFi network interface so regular internet can work normally.  Can you find out the current IP?  From the sound of the server, "lapbox", is it a laptop being used as a server?  Do you have physical access to that "lapbox"?

**Comment by BigLOnline** [comment]
Yes I am physically at the machine

**Comment by BigLOnline** [comment]
I have network working fine. Only webmin installation never works

**Comment by BigLOnline** [comment]
I get a ping from Google as well

**Comment by BigLOnline** [comment]
It's all working now. Webmin has installed.

**Comment by chris001** [comment]
Yes, I've also experienced this on debian, IPv6 `inet6` must also be configured as `dhcp`, and an `ifdown` and `ifup`, so that internet data can start to flow normally.
