### ISSUE TITLE
Detect and update operating system version on boot / webmin service startup

### ISSUE THREAD

**Issue by nekohayo** [webmin/webmin#2004]
After upgrading from Debian 11 to Debian 12 (and, inevitably, rebooting), Webmin thought I was still on Debian 11, for some reason.

Some days later, Webmin 2.101 eventually realized:

![image](https://github.com/webmin/webmin/assets/479401/b616ce1c-5b68-44f0-8f64-47ea09eac2e5)

I've seen this delayed behavior happen on two computers I upgraded.

I understand that you're not doing this check in realtime / every minute or something like that for performance reasons, but why not do it on boot / service startup? As  far as I know, a major OS upgrade is pretty much inevitably going to involve kernel upgrades, and thus, a reboot... so I don't see why you would need to do this check more than once per boot, nor why you would need to prompt the user to confirm this instead of just automatically updating this info in the dashboard's info table? It's not like the user has the ability to "refuse" the recognition of the updated OS version anyway.

**Comment by jcameron** [comment]
That's a good suggestion! I'll look into implementing this and update this ticket once it's done ...

**Comment by marclaporte** [comment]
+1 to do check on boot.

I like this confirmation message as it reinforces that the upgrade was successfully detected by Virtualmin. But as Jeff indicates, it's not like we can refuse :-)

**Comment by jcameron** [comment]
Ok, in the next release this message will be displayed immediately after a reboot..
