### ISSUE TITLE
Let's Encrypt is not working

### ISSUE THREAD

**Issue by Lactans** [webmin/webmin#2005]
Hi community,

since several weeks I use Webmin without any issues on two new VPS systems running Debian 11. So a big THANK YOU to the community!

My third VPS is a bit older and is upgraded all the way from Debian 8 to Debian 11. I decided to switch to Webmin 2.102 on this server as well. Installation of Webmin was no issue and the GUI is working. But when I navigate to Webmin Configuration -> SSL Certificates -> Let's Encrypt and request a new certificate, the request fails and I get this error from Webmin:

```
Bootstrapping dependencies for Debian-based OSes... (you can skip this with --no-bootstrap)
Hit:1 http://security.debian.org/debian-security bullseye-security InRelease
Hit:2 http://deb.debian.org/debian bullseye InRelease
Hit:3 http://deb.debian.org/debian bullseye-updates InRelease
Ign:4 https://download.webmin.com/download/newkey/repository stable InRelease
Hit:5 https://download.webmin.com/download/newkey/repository stable Release
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
Package python-virtualenv is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'python-virtualenv' has no installation candidate
```

Python is installed on the system as version 2.7 and 3.9. Manual installation of package python-virtualenv also doesn't word. I installed python3-venv, which somehow is not recognized.

Which additional information do you need? I have no more ideas how to solve this :-(.

Thanks for all help!

Cheers,
Lactans

**Comment by jcameron** [comment]
That's surprising, because Webmin doesn't have a dependency on `python-virtualenv` 

Maybe some other installed package does?

**Comment by Lactans** [comment]
That's what I thought and checked it:

```$ apt-rdepends -r python-virtualenv
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
python-virtualenv
```

**Comment by chris001** [comment]
Does this solve it:
`apt install python3-virtualenv`

**Comment by swelljoe** [comment]
Webmin does not need python3-virtualenv.

**Comment by swelljoe** [comment]
Or, python-virtualenv.

**Comment by chris001** [comment]
Certbot uses a python virtualenv to run safely without touching the system's python installation.
Here's a [guide to get certbot installed and working on debian 11 from the Let's Encrypt site](https://certbot.eff.org/instructions?ws=apache&os=debiantesting) - it uses a snap virtual environment.

**Comment by Lactans** [comment]
Good ideas, thank you!
I tried to uninstall certbot (it is available on the system), but apt doesn't know about this installation:

```
# apt list --installed |grep cert

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

ca-certificates/oldstable,now 20210119 all [installed,automatic]
ssl-cert/oldstable,now 1.1.0+nmu1 all [installed]
```

Certbot binary is here:
```
# which certbot
/usr/bin/certbot
```

Any ideas, how to remove certbot? Target is, to use Webmin for certificates and ideally no workaround.

**Comment by Lactans** [comment]
Issue is solved but just *installing* certbot on the system :-D

Thank you for all your help, you sent me into the right direction!
