### ISSUE TITLE
file manager editor changes &quotes; into "

### ISSUE THREAD

**Issue by pieter-groeneweg** [webmin/webmin#2007]
I noticed in file manager editor that $quotes; automatically is changed into " upon saving.

`pattern="%h %l %u %t &quot;%r&quot; %s %b" `

for instance is changed into 

`pattern="%h %l %u %t "%r" %s %b"` 

causing our service to break

I cannot find any in the configuration to change this behaviour. Is there a way?

Thanks!

**Comment by iliajie** [comment]
Hello,

This is a known and already fixed issue for upcoming Webmin 2.103 release.

**Comment by pieter-groeneweg** [comment]
Awesome! Thanks!
