### ISSUE TITLE
Ability to create .tar archives from the File Manager?

### ISSUE THREAD

**Issue by nekohayo** [webmin/webmin#2009]
This is a very very minor feature suggestion, but maybe you will find it interesting.

It might be nice to offer "**.tar** (uncompressed, but faster)" as an option besides ".tar.gz" and ".zip" when right-clicking a folder (or multiple files) and using the "New > Create new archive" right-click (or File menu) action in the File Manager.

The usecase for this is when bandwidth or space isn't terribly scarce and you value processing speed above all; particularly in cases where compression wouldn't be very effective (ex: folders containing lots of encoded images or videos), or on under-powered machines.

Presumably, as Webmin (and Virtualmin, etc.) already has the ability to create uncompressed tarballs for backups etc., the backend code might already be there, waiting to be used.

**Comment by jcameron** [comment]
@iliaross could we add this to the file manager? It sounds like a good idea ...

**Comment by iliajie** [comment]
Yeah, I'll take a look!

**Comment by iliajie** [comment]
Alright, next Webmin and Authentic Theme releases will have support for plain `tar`, along side with `xz` and `zstd` compressions.

<img width="881" alt="image" src="https://github.com/webmin/webmin/assets/4426533/5a796894-0e90-4e27-976c-9bb47c2bbb26">
