### ISSUE TITLE
FreeBSD 10.1

### ISSUE THREAD

**Issue by jwhulette** [webmin/webmin#201]
Issue with installing authentic-theme. After installing the theme, the error Error - Missing Content-Type Header appears. Test: Fresh install of FreeBSD 10.1, package install webmin, update authentic theme to latest version, error appears. According to them dev, webmin is not installing theme correctly.

**Comment by jcameron** [comment]
I'd recommend you post this bug report on the theme developer's github tracker, at https://github.com/qooob/authentic-theme

**Comment by swelljoe** [comment]
I think it was posted there first, and Ilia didn't know what to do with it. I'm gonna look into why it's happening; I'm guessing it is a Perl path problem. On FreeBSD it is possible to have several Perl versions installed, and it's not difficult to end up with the wrong perl being called in some circumstances (I ran into this a bunch on Mac OS X). It's ugly, but manageable.

But, it's very unlikely to be a Webmin bug, I agree. So this probably isn't the right place for the discussion to take place. It may be resolvable in the theme, or it may require fixing Perl paths and library paths for Perl
