### ISSUE TITLE
Perl execution failed

### ISSUE THREAD

**Issue by petrospap** [webmin/webmin#2015]
Hello, in miniserv.error i got 

```
[30/Sep/2023:11:48:34 +0300] [IP] /mysql/ : Perl execution failed : Can't locate view-lib.pl in @INC (@INC contains: /usr/share/webmin/vendor_perl /usr/share/webmin /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.36.0 /usr/local/share/perl/5.36.0 /usr/lib/x86_64-linux-gnu/perl5/5.36 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl-base /usr/lib/x86_64-linux-gnu/perl/5.36 /usr/share/perl/5.36 /usr/local/lib/site_perl /usr/share/webmin/ .  ..) at ./mysql-lib.pl line 8.
Compilation failed in require at /usr/share/webmin/mysql/index.cgi line 5.
```

I don't get it cos view-lib.pl exist..

**Comment by iliajie** [comment]
Perhaps something went wrong upon installation. Try re-installing Webmin package and restarting it using `/etc/webmin/restart-by-force-kill`. If none of this works, provide more details about OS and version and how Webmin was installed.

**Comment by petrospap** [comment]
OK seems this happen when reload page from browser

reason to reload is, 
when execute in terminal **systemctl status package-name** and the status for any reason failed

in terminal displays the status, and at the end, a white cursor appears and cannot do anything, 
that's why i need to reload

i.e
```
root@server:~# systemctl status mariadb
● mariadb.service - MariaDB 10.11.3 database server
     Loaded: loaded (/lib/systemd/system/mariadb.service; enabled; preset: enabled)
     Active: active (running) since Sat 2023-09-30 09:40:49 EEST; 4h 38min ago
       Docs: man:mariadbd(8)
             https://mariadb.com/kb/en/library/systemd/
   Main PID: 18568 (mariadbd)
     Status: "Taking your SQL requests now.."
      Tasks: 11 (limit: 14299)
     Memory: 226.0M
        CPU: 7.770s
     CGroup: /system.slice/mariadb.service
             └─18568 /usr/sbin/mariadbd

Sep 30 09:40:49 server.2 systemd[1]: Starting mariadb.service - MariaDB 10.11.3 database server..
Sep 30 09:40:49 server.2 systemd[1]: Started mariadb.service - MariaDB 10.11.3 database server.
Sep 30 09:40:49 server.2 /etc/mysql/debian-start[18583]: Upgrading MySQL tables if necessary.
Sep 30 09:40:49 server.2 debian-start[18595]: ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)
[ white cursor? and cannot write so i reload ]
```

Fresh Debian 12
webmin installed 
wget http://www.webmin.com/jcameron-key.asc
apt-key add jcameron-key.asc
apt update
apt install

seems like everything is working, except "Access denied for user 'root'"
So.. searching in logs I found "Perl execution failed"

I am with Firefox 118.01

**Comment by iliajie** [comment]
What do you see when you visit **Servers -> MariaDB Database Server** main page?

**Comment by petrospap** [comment]
I believe everything,

I can create new database, i can edit db, user db table field permissions, server configuration, edit config files, db connections,
system variables, SSL, change Admin password, stop Server, Backup DB

As i said i can create and edit db, i can add user and change password, i can edit files, stop start server, with no errors!

So i think is safe to say that this "Perl execution failed" occur only when i am in  MariaDB Database Server and reload page from browser.

About "Access denied" similar issue found in
https://mariadb.com/kb/en/troubleshooting-connection-issues/#comment_5674

I believe is some bug in debian 12 systemd, I post this issue in debian forum.
