### ISSUE TITLE
"nothing provides /bin/rm needed by webmin-2.102-1.noarch" on Fedora 39

### ISSUE THREAD

**Issue by FBachofner** [webmin/webmin#2016]
I am attempting to install Webmin 2.102-1 on a new installation of Fedora 39 (which is beta)

Whether I use the `setup-repos.sh` and then `dnf install webmin`

*or* manually download Webmin and manually run `dnf install ./webmin-current.rpm`

I get an error along the lines of

> Error: 
>  Problem: conflicting requests
>   - nothing provides /bin/rm needed by webmin-2.102-1.noarch from @commandline
> (try to add '--skip-broken' to skip uninstallable packages)

Meanwhile, rm is indeed available at /bin/rm . . .

**Comment by jcameron** [comment]
What output do you get if you run `rpm -q -f  /bin/rm` ?

**Comment by FBachofner** [comment]
`coreutils-9.3-4.fc39.x86_64`

**Comment by jcameron** [comment]
Ok that's a vey odd error message then, because clearly `/bin/rm` is available! I'm not sure why the `dnf` command isn't finding it ...

**Comment by iliajie** [comment]
Jamie, I think, it is better not to refer to `rm` via symlink, which `/bin` is on all contemporary systems, but directly, using `/usr/bin`. Please check this patch https://github.com/webmin/webmin/commit/b9449c213b2bbd754ad99ea804c0574a91c763ca.

@FBachofner I have made a few changes. You can try it on your development Fedora 39 with latest Webmin development version. I'm pretty sure it will work for you, e.g.:

```
dnf install https://builds.webmin.dev/webmin-latest.rpm -y
```

**Comment by swelljoe** [comment]
The package shouldn't depend on `rm` or any other `coreutils`. That's taking it to an absurd level.

**Comment by swelljoe** [comment]
I mean, it is reasonable to expect that any place Webmin is being installed will be a reasonably complete UNIX/Linux system. If it doesn't have `rm` it is ridiculously broken and Webmin shouldn't try to fix it with dependencies.

**Comment by iliajie** [comment]
> If it doesn't have `rm` it is ridiculously broken and Webmin shouldn't try to fix it with dependencies.

Jamie, why do we really have to depend on `rm`? I think Joe is right, there is no reason to depend on core packages.

**Comment by jcameron** [comment]
I suppose we could just remove it. I'm not sure why it was added in the first place actually!

**Comment by iliajie** [comment]
> I suppose we could just remove it. I'm not sure why it was added in the first place actually!

I think it would be the best solution, as `rm` command should always exist.

**Comment by jcameron** [comment]
Ok, I will do that!

**Comment by iliajie** [comment]
> Ok, I will do that!

Great, thanks!

**Comment by FBachofner** [comment]
> @FBachofner I have made a few changes. You can try it on your development Fedora 39 with latest Webmin development version. I'm pretty sure it will work for you, e.g.:
> 
> ```
> dnf install https://builds.webmin.dev/webmin-latest.rpm -y
> ```

Thank you @iliaross 

Using webmin-latest.rpm an hour or so ago on Fedora 39 beta *did* indeed work
