### ISSUE TITLE
https webmin issue

### ISSUE THREAD

**Issue by TulsaWes** [webmin/webmin#2018]
I updated my server certificate - and it works fine across all my domains/subdomains, but not in webmin any longer. As a work around, I tried using a self-signed created through webmin, but it seems modern broswers won't allow that to work past the first page loaded.
So, reverting back to my legit certificate, now I get this error: ERR_SSL_VERSION_OR_CIPHER_MISMATCH
Nothing else has changed. One possible indicator of where this bug is that when I select to view the "current certificate" is that it appears to list the expiration date of the self-signed and not the cert/key that I have entered on the "SSL Settings" screen. 
So, I think it's referring to an incorrect file some where/how. The actual cert expires in like one year vs. 2027 as this screen indicates, but it does show the correct issuer, etc.
![image](https://github.com/webmin/webmin/assets/147014863/4eefed7d-de9d-48aa-b500-7f3c801b7b2b)

I've deleted the miniserv.pem file thinking that might resolve this, but it did not. I tried uninstalling webmin and reinstalled, but apparently it left behind all the config files since everything is exactly the same as if I did not uninstall it.

So, I think this is a actual bug, where if you go to change the certificate, somehow webmin has part of the old on cached somewhere, and it causes this issue.

I am currently able to access directly by IP and http:

And to reassert - I use the same * certificate currently across amost 100 domains, and all is good on all those sites.

**Comment by jcameron** [comment]
Is this still an issue? I see you closed the ticket ...

**Comment by TulsaWes** [comment]
Not an issue, I realized that the field display length was shorter than the text in there and I was not able to see that for the certificate I had choose the bundle file instead of the actual certificate so it was referring to the issuers certificate instead of mine.
So screw up on my part.
Wes

October 4, 2023 9:46 PM, "Jamie Cameron" ***@***.*** ***@***.******@***.***>)> wrote:
	Is this still an issue? I see you closed the ticket ...
