### ISSUE TITLE
Running Processes size units

### ISSUE THREAD

**Issue by qooob** [webmin/webmin#202]
Jamie, I think it's time to change `kB` units to `MB` or make it optional in `Module Config`.

In case your machine has 128 GB of RAM there are no small numbers and something like `1811888 kB` is difficult to read.

**Comment by jcameron** [comment]
Thanks for pointing this out - I'll change this in the next release of Webmin.

**Comment by qooob** [comment]
I bet same should be done for Usermin! ;)

**Comment by jcameron** [comment]
Yes, it will be.
