### ISSUE TITLE
Webmin 2.103 on Ubuntu Server 22.04.3 - requesting hostname every minute (Dbus call)

### ISSUE THREAD

**Issue by ameinild** [webmin/webmin#2020]
Since the update of Webmin 2.103, Webmin is spamming Dbus every minute with this request to retrieve the static hostname: (`comm="hostnamectl --static " label="unconfined"`)

```
Oct  9 09:48:32 xb dbus-daemon[1267]: [system] Connection :1.18436 (uid=0 pid=1012935 comm="busctl monitor org.freedesktop.hostname1 " label="unconfined") became a monitor.
Oct  9 09:48:49 xb dbus-daemon[1267]: [system] Activating via systemd: service name='org.freedesktop.hostname1' unit='dbus-org.freedesktop.hostname1.service' requested by ':1.18439' (uid=0 pid=1013018 comm="hostnamectl --static " label="unconfined")
Oct  9 09:48:49 xb systemd[1]: Starting Hostname Service...
Oct  9 09:48:50 xb dbus-daemon[1267]: [system] Successfully activated service 'org.freedesktop.hostname1'
Oct  9 09:48:50 xb systemd[1]: Started Hostname Service.
Oct  9 09:49:20 xb systemd[1]: systemd-hostnamed.service: Deactivated successfully.
Oct  9 09:49:49 xb dbus-daemon[1267]: [system] Activating via systemd: service name='org.freedesktop.hostname1' unit='dbus-org.freedesktop.hostname1.service' requested by ':1.18449' (uid=0 pid=1013457 comm="hostnamectl --static " label="unconfined")
Oct  9 09:49:49 xb systemd[1]: Starting Hostname Service...
Oct  9 09:49:49 xb dbus-daemon[1267]: [system] Successfully activated service 'org.freedesktop.hostname1'
Oct  9 09:49:49 xb systemd[1]: Started Hostname Service.
Oct  9 09:50:20 xb systemd[1]: systemd-hostnamed.service: Deactivated successfully.
Oct  9 09:50:49 xb dbus-daemon[1267]: [system] Activating via systemd: service name='org.freedesktop.hostname1' unit='dbus-org.freedesktop.hostname1.service' requested by ':1.18459' (uid=0 pid=1013859 comm="hostnamectl --static " label="unconfined")
Oct  9 09:50:49 xb systemd[1]: Starting Hostname Service...
Oct  9 09:50:50 xb dbus-daemon[1267]: [system] Successfully activated service 'org.freedesktop.hostname1'
Oct  9 09:50:50 xb systemd[1]: Started Hostname Service.
Oct  9 09:51:20 xb systemd[1]: systemd-hostnamed.service: Deactivated successfully.
Oct  9 09:51:49 xb dbus-daemon[1267]: [system] Activating via systemd: service name='org.freedesktop.hostname1' unit='dbus-org.freedesktop.hostname1.service' requested by ':1.18469' (uid=0 pid=1015707 comm="hostnamectl --static " label="unconfined")
Oct  9 09:51:49 xb systemd[1]: Starting Hostname Service...
Oct  9 09:51:50 xb dbus-daemon[1267]: [system] Successfully activated service 'org.freedesktop.hostname1'
Oct  9 09:51:50 xb systemd[1]: Started Hostname Service.
Oct  9 09:52:20 xb systemd[1]: systemd-hostnamed.service: Deactivated successfully.
Oct  9 09:52:49 xb dbus-daemon[1267]: [system] Activating via systemd: service name='org.freedesktop.hostname1' unit='dbus-org.freedesktop.hostname1.service' requested by ':1.18479' (uid=0 pid=1016121 comm="hostnamectl --static " label="unconfined")
Oct  9 09:52:49 xb systemd[1]: Starting Hostname Service...
Oct  9 09:52:50 xb dbus-daemon[1267]: [system] Successfully activated service 'org.freedesktop.hostname1'
Oct  9 09:52:50 xb systemd[1]: Started Hostname Service.
Oct  9 09:53:20 xb systemd[1]: systemd-hostnamed.service: Deactivated successfully.
Oct  9 09:53:23 xb dbus-daemon[1267]: [system] Monitoring connection :1.18436 closed.
Oct  9 09:53:28 xb systemd[1]: Stopped Webmin server daemon.
Oct  9 09:53:28 xb systemd[1]: webmin.service: Consumed 6.105s CPU time.
Oct  9 09:53:48 xb systemd[1]: session-258.scope: Deactivated successfully.
Oct  9 09:53:48 xb systemd[1]: session-258.scope: Consumed 1.629s CPU time.
Oct  9 10:17:01 xb CRON[1027467]: (root) CMD (test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.hourly ))
Oct  9 10:18:34 xb systemd[1]: Started Session 264 of User am.
Oct  9 10:18:46 xb systemd[1]: session-264.scope: Deactivated successfully.
Oct  9 10:18:46 xb systemd[1]: session-264.scope: Consumed 1.140s CPU time.
```

I've isolated the problem to Webmin, beacuse if I stop the Webmin service, this command is no longer triggered each minute.

This is the output of `busctl monitor org.freedesktop.hostname1`:

```
‣ Type=method_call  Endian=l  Flags=0  Version=1 Cookie=2  Timestamp="Mon 2023-10-09 07:48:49.563006 UTC"
  Sender=:1.18439  Destination=org.freedesktop.hostname1  Path=/org/freedesktop/hostname1  Interface=org.freedesktop.DBus.Properties  Member=Get
  UniqueName=:1.18439
  MESSAGE "ss" {
          STRING "org.freedesktop.hostname1";
          STRING "StaticHostname";
  };

‣ Type=method_return  Endian=l  Flags=1  Version=1 Cookie=5  ReplyCookie=2  Timestamp="Mon 2023-10-09 07:48:50.018487 UTC"
  Sender=org.freedesktop.DBus  Destination=:1.18440
  MESSAGE "u" {
          UINT32 1;
  };

‣ Type=method_return  Endian=l  Flags=1  Version=1 Cookie=3  ReplyCookie=2  Timestamp="Mon 2023-10-09 07:48:50.018698 UTC"
  Sender=:1.18440  Destination=:1.18439
  UniqueName=:1.18440
  MESSAGE "v" {
          VARIANT "s" {
                  STRING "xb";
          };
  };

‣ Type=method_call  Endian=l  Flags=0  Version=1 Cookie=4  Timestamp="Mon 2023-10-09 07:49:20.024097 UTC"
  Sender=:1.18440  Destination=org.freedesktop.DBus  Path=/org/freedesktop/DBus  Interface=org.freedesktop.DBus  Member=AddMatch
  UniqueName=:1.18440
  MESSAGE "s" {
          STRING "sender='org.freedesktop.DBus',type='signal',interface='org.freedesktop.DBus',member='NameOwnerChanged',path='/org/freedesktop/DBus',arg0='org.freedesktop.hostname1',arg1=':1.18440',arg2=''";
  };

‣ Type=method_return  Endian=l  Flags=1  Version=1 Cookie=4  ReplyCookie=4  Timestamp="Mon 2023-10-09 07:49:20.024175 UTC"
  Sender=org.freedesktop.DBus  Destination=:1.18440
  MESSAGE "" {
  };

‣ Type=method_call  Endian=l  Flags=0  Version=1 Cookie=5  Timestamp="Mon 2023-10-09 07:49:20.024287 UTC"
  Sender=:1.18440  Destination=org.freedesktop.DBus  Path=/org/freedesktop/DBus  Interface=org.freedesktop.DBus  Member=ReleaseName
  UniqueName=:1.18440
  MESSAGE "s" {
          STRING "org.freedesktop.hostname1";
  };

‣ Type=signal  Endian=l  Flags=1  Version=1 Cookie=5  Timestamp="Mon 2023-10-09 07:49:20.024316 UTC"
  Sender=org.freedesktop.DBus  Destination=:1.18440  Path=/org/freedesktop/DBus  Interface=org.freedesktop.DBus  Member=NameLost
  MESSAGE "s" {
          STRING "org.freedesktop.hostname1";
```

Any idea why this is suddenly the case? This hasn't been an issue on any earlier release.

**Comment by iliajie** [comment]
Hello,

Well, I have just spent quite some time looking into it, and it happens to be a pretty obscure "issue" indeed! Also, it appeared that it was already discussed in this thread: https://github.com/systemd/systemd/issues/13921.

We have indeed transitioned to using `hostnamectl --static` to retrieve the hostname on _systemd_ systems. However, I'm uncertain about its direct link to Webmin, especially since this type of logging occurs approximately every 2.5 - 5 minutes, irrespective of the Webmin/Usermin process.

The _systemd_ developer recommends using `cat /etc/hostname`. My original intent for preferring `hostnamectl --static` was based on instances where I observed discrepancies between the outputs of `hostnamectl --static` and `cat /etc/hostname`. In those scenarios, `hostnamectl --static` consistently provided the expected results.

In the end, based on the linked discussion, it is considered to be normal by _systemd_ developers.

**Comment by ameinild** [comment]
But why does it trigger every minute all the time? This spams the syslog excessively in my opinion.

**Comment by iliajie** [comment]
> but why does it trigger every minute all the time? This spams the syslog excessively in my opinion.

I have already explained everything in my previous comment.


> Could there perhaps be an option to set the interval that this occurs?

How often do you run status collection in Webmin?

**Comment by ameinild** [comment]
Every 5 minutes - yet this triggers each minute. Maybe this could solve a bit - that it actually follows the background collection setting.

![billede](https://github.com/webmin/webmin/assets/434479/9f1bb26a-0054-4fc6-93be-b4530e1ebc98)

**Comment by iliajie** [comment]
You could stop Webmin and Usermin processes completely to find those messages in the logs anyway. I don't know what else we can do here?

**Comment by iliajie** [comment]
> Could you look into having `hostnamectl --static` actually follow the background status collection interval?

As I've previously pointed out, this doesn't seem to be a direct issue in Webmin.

**Comment by ameinild** [comment]
Erhmm ok.....

**Comment by ameinild** [comment]
> You could stop Webmin and Usermin processes completely to find those messages in the logs anyway. I don't know what else we can do here?

I think you missed the main point. If you see in my logfile, it's pretty clear that these messages DO NOT appear every minute when I stop the Webmin service, and thus does this only appear every minute when Webmin is running.

So I'm having a really hard time believing it has NOTHING to do with Webmin, since the issue completely vanishes when Webmin service is stopped.

Anyway, I can't make a more clear report or explanation - do what you want to fix or not fix, I'll live with it anyway...

**Comment by iliajie** [comment]
I can see those messages in logs _even_ if I stop Webmin and Usermin services. Also, _systemd_ developers state that this is "normal".

I can clearly see that those the same log messages appear either way on my Ubuntu 22.04, even if Webmin and Usermin are stopped. But yes, the rate of the messages may be different.

Anyway, what is your suggestion about this? What exactly we're doing wrong? What is wrong about calling `hostnamectl --static` command?

**Comment by ameinild** [comment]
There's nothing wrong with that at all. I'm merely pointing out the frequency that Webmin address Dbus with those messages (by running `hostnamectl` each minute) is somewhat excessive. As pointed out, if the frequency that Webmin calls this would follow the the background collection setting, then it would be better IMO.

**Comment by iliajie** [comment]
> Having 5 lines written to the syslog every minute just to get a hostname is (again in my opinion) quite excessive.

I totally agree on that!

Jamie, is there a way we could do something to completely suppress those dbus messages?

**Comment by jcameron** [comment]
> Jamie, is there a way we could do something to completely suppress those dbus messages?

Unsure, but maybe we should revert to the old solution of reading the hostname from config files?

**Comment by iliajie** [comment]
> Unsure, but maybe we should revert to the old solution of reading the hostname from config files?

Yes, because it appears that `hostnamectl` command is directly dependent on `/etc/hostname` file. It seems that it's just reading it internally.

The fix is here https://github.com/webmin/webmin/commit/d48154d6a000d77204d178a81e37e98d8c262bf7.
