### ISSUE TITLE
Error — Perl execution failed Text Editor 1.4

### ISSUE THREAD

**Issue by alcalpcr** [webmin/webmin#2021]
Bug
```
Error — Perl execution failed
Undefined subroutine &text_editor::ui_switch_theme_javascript called at ../web-lib-funcs.pl line 1122.
```
SO: Ubuntu 22.04.3 x65
Webmin: v2.103
affected module: Text Editor 1.4
download: http://www.webmin.com/download/modules/text-editor.wbm.gz
when it occurs: when I try to edit a text file in this module
screenshot:
![webmin](https://github.com/webmin/webmin/assets/37303411/8b4dc571-55a0-4746-9c28-93ded506de35)
Config:
![Captura de pantalla -2023-10-09 09-44-42](https://github.com/webmin/webmin/assets/37303411/a2171e75-0d60-4cb0-8f40-60b9fdddbf88)
service: normal:
```
sudo service webmin status
● webmin.service - Webmin server daemon
     Loaded: loaded (/lib/systemd/system/webmin.service; enabled; vendor preset: enabled)
     Active: active (running) since Mon 2023-10-09 09:34:07 -05; 13min ago
    Process: 371326 ExecStart=/usr/share/webmin/miniserv.pl /etc/webmin/miniserv.conf (code=exited, status=0/SUCCESS)
   Main PID: 371329 (miniserv.pl)
      Tasks: 1 (limit: 18879)
     Memory: 67.8M
        CPU: 4.210s
     CGroup: /system.slice/webmin.service
             └─371329 /usr/bin/perl /usr/share/webmin/miniserv.pl /etc/webmin/miniserv.conf

oct 09 09:34:04 user systemd[1]: Starting Webmin server daemon...
oct 09 09:34:05 user perl[371326]: pam_unix(webmin:auth): authentication failure; logname= uid=0 euid=0 tty= ruser= rhost=  user=root
oct 09 09:34:07 user webmin[371326]: Webmin starting
oct 09 09:34:07 user systemd[1]: Started Webmin server daemon.
```
Note: This bug did not exist with the previous version of webmin

**Comment by iliajie** [comment]
Hello,

This issue indicates that Webmin wasn't restarted correctly.

Try running `/etc/webmin/restart` or `/etc/webmin/restart-by-force-kill` in case the first command doesn't help.

**Comment by alcalpcr** [comment]
No. I tried it with both. restart the PC. the same problem
![Captura de pantalla -2023-10-09 10-14-41](https://github.com/webmin/webmin/assets/37303411/1644bef6-3c3c-47ce-b0c3-8ab1b0af8b1e)

**Comment by maravento** [comment]
same problem too.

**Comment by iliajie** [comment]
I think I see what the problem is. I don't know what `test_editor::` is but I think it uses `web-lib-funcs.pl` without using `WebminCore`, i.e. Webmin UI library isn't getting loaded, and this is the reason why it fails.

The fix is here https://github.com/webmin/webmin/commit/3c97fc5a326c39438e7e550719ba9340c668c8d8.

Nevertheless, I would suggest not to use this old module and rely on inbuilt Webmin Custom Commands module and/or Authentic theme features (favorites).

**Comment by maravento** [comment]
I appreciate the new commit (I hope it solves this problem), but not your suggestion, since the Tex Edit module is excellent and had worked well and it doesn't matter that it is old (old is not necessarily bad). And in my opinion, the legacy theme is superior to Authentic.

**Comment by iliajie** [comment]
Alright, excellent!

You can apply the patch manually to make it work right now.
