### ISSUE TITLE
since last upgrade error about systemd on sysvinit systems

### ISSUE THREAD

**Issue by aqueos** [webmin/webmin#2022]
hi,

 since the last version we got plenty of error messages like

System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down

on sysvinit system on debian 10.

[~]: webmin --version
2.103

  distro => {
    codename => "buster",
    description => "Debian GNU/Linux 10 (buster)",
    id => "Debian",
    release => {
      full => "10.13",
      major => "10",
      minor => "13"
    }
  },

i think there is an issue in the detection about the init system used by the system.

best regards,
Ghislain.

**Comment by iliajie** [comment]
Hello,

Does your system have `hostnamectl` command? If so, what is the output of `hostnamectl --static` on your system?

**Comment by aqueos** [comment]
hi,

 it returns this message:

[~]:  hostnamectl --static 
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down

best regards,
Ghislain.

**Comment by iliajie** [comment]
> System has not been booted with systemd as init system (PID 1). Can't operate.

Very interesting. Why do you have _systemd_ install if you're using _sysvinit_?

Can you run `echo $?` right after calling `hostnamectl --static` and share its output if any?

Also, does `/etc/hostname` contain the correct and expected hostname?

**Comment by aqueos** [comment]
here it is :  

```
[~]: hostnamectl --static; echo $?
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
1

```

well we have the basic systemd packages because some software require parts of systemd  to run like systemd-tmpfiles.

all the php fpm package of debian sury need systemd-tmpfiles so systemd must be installed installed but not active.

The hostname is set to the fqdn on all machines and is the rigth one.

best regards,
Ghislain.

**Comment by iliajie** [comment]
Got it!

Alright, if you feel comfortable you can try this [latest](https://builds.webmin.dev/webmin-latest.deb) devel build of Webmin and let me know if that works for you.

**Comment by aqueos** [comment]
dont laugh but on debian 10 i got:

```
dpkg -i webmin-latest.deb 
dpkg-deb: error: archive 'webmin-latest.deb' uses unknown compression for member 'control.tar.zst', giving up
dpkg: error processing archive webmin-latest.deb (--install):
 dpkg-deb --control subprocess returned error exit status 2
Errors were encountered while processing:
 webmin-latest.deb

```

**Comment by aqueos** [comment]
well prepare to have another ;p

i installed the zstd and libzstd1 package but:

```
dpkg -i webmin-latest.deb 
dpkg-deb: error: archive 'webmin-latest.deb' uses unknown compression for member 'control.tar.zst', giving up
dpkg: error processing archive webmin-latest.deb (--install):
 dpkg-deb --control subprocess returned error exit status 2
Errors were encountered while processing:
 webmin-latest.deb


apt-get install ./webmin-latest.deb
Reading package lists... Error!
E: Sub-process Popen returned an error code (2)
E: Encountered a section with no Package: header
E: Problem with MergeList /var/home/whmcs01/logs/webmin-latest.deb
E: The package lists or status file could not be parsed or opened.
```

i use the script in https://github.com/yktoo/indicator-sound-switcher/issues/113 to convert it to xz and it is installed now.
```
Preparing to unpack webmin-latest_repacked.deb ...
Unpacking webmin (2.103.202310101029) over (2.103) ...
Setting up webmin (2.103.202310101029) ...
W: Webmin server cannot be restarted. It is advised to restart it manually by
   running "/etc/webmin/restart-by-force-kill" command when upgrade process is finished


[~]: /etc/webmin/restart-by-force-kill
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
```

after using /etc/init.d/webmin restart  it worked and i dont have anymore the issue.

so perhaps the package install script have the same issue as well as /etc/webmin/restart-by-force-kill :)

best regards,
Ghislain.

**Comment by aqueos** [comment]
it also prevented letsencrypt to renew. I guess a lots of other things are blocking now. 
with the dev build it works on the interface to renew a letsencrypt so i guess it ok now.

But the debian package postinstall restart scripts and the  /etc/webmin/restart-by-force-kill dont :)

best regards,
Ghislain.

**Comment by iliajie** [comment]
> after using /etc/init.d/webmin restart it worked and i dont have anymore the issue.
> so perhaps the package install script have the same issue as well as /etc/webmin/restart-by-force-kill :)

Yeah, we're not really doing it right with `init.d/webmin` script, I think.

What is the output of `systemctl ; echo $?` command on your system?

**Comment by aqueos** [comment]
you guessed it:

```
[~]:  systemctl ; echo $?
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
1
```

:)

**Comment by aqueos** [comment]
[~]: cat /proc/1/comm
systemd

[~]: cat /proc/1/comm
init

i think this is a good way to know which init is running, dont know if there is a better one and if it is universal on linux, all my servers are debian/ubuntu so....

best regards,
Ghislain.

**Comment by iliajie** [comment]
Thanks! I will take a look.

**Comment by iliajie** [comment]
We will address this and a few other related issues in this PR https://github.com/webmin/webmin/pull/2026.

Thanks for the heads up! We're looking forward into making Webmin 2.104 as soon as possible!
