### ISSUE TITLE
After upgrading Ubuntu 14.04 to Webmin 2.103 the hostname is bizarre and the usage charts do not update...

### ISSUE THREAD

**Issue by rickripe** [webmin/webmin#2023]
Found this on two Ubuntu 14.04 servers.  The hostname is the collapsed output from `hostnamectl`.  On a Ubuntu 20.04 server this is not the case - it looks more like it is gathered from `hostname`.  See screen shots:
Ubuntu 14.04:
![image](https://github.com/webmin/webmin/assets/7744389/0d5b8565-5b2e-4da7-870f-cedfe4bbd47b)
Ubuntu 20.04:
![image](https://github.com/webmin/webmin/assets/7744389/37dea61b-be83-4320-b67d-6594fac655c9)

Also, why is the Webmin version number now 2103 and not 2.103?

**Comment by rickripe** [comment]
Also, looks fine on Ubuntu 16.04:
![image](https://github.com/webmin/webmin/assets/7744389/30c64939-91db-49e9-98ef-a3df64f3f48f)

**Comment by swelljoe** [comment]
Ubuntu 14.04 reach end of life several years ago. If you're OK with ancient software, just stick with an older version of Webmin that worked OK for you. We try to keep things working for a couple years after a distro reaches EOL (Xenial/16.04 is also EOL), but there's a limit to how much time we can put into testing and maintaining across so many differences.

**Comment by rickripe** [comment]
No problems - thanks Joe.  Any ideas on why the version number is now 2103 and not 2.103?

**Comment by swelljoe** [comment]
I'm not sure. I assume it's a display issue. The actual version is 2.103. https://github.com/webmin/webmin/blob/c4c2c5c38e3fa91fc7b7e0f9f093634f29148c7e/version

**Comment by swelljoe** [comment]
Though it's weird that it also displays that way on Xenial, which probably still works fine.

**Comment by iliajie** [comment]
> No problems - thanks Joe. Any ideas on why the version number is now 2103 and not 2.103?

I also see this. It doesn't work fine. It is a display issue though.

**Comment by jcameron** [comment]
Oh that's a pity :-(
