### ISSUE TITLE
Post installation: Webmin port isn't getting opened automatically

### ISSUE THREAD

**Issue by iliajie** [webmin/webmin#2027]
Hi Jamie!

After Webmin is installed the port 10000 appears to be closed in firewall, on FirewallD system. It seems that nothing triggers `open-ports.pl` after Webmin initial installation.

**Comment by jcameron** [comment]
Actually I was wrong - it's currently only called by Cloudmin when installing Webmin.

I wonder if we should make this happen by default for all new installs? I'm a little leery of doing that though, because the sysadmin might have intentionally blocked all ports.

**Comment by iliajie** [comment]
Good question. It isn't uncommon for a package to open ports upon installation. I think `cockpit` does it as well. But I feel you, and I honestly don't know what'd be right here. Most certainly we won't be able to satisfy all.

**Comment by jcameron** [comment]
Yeah ... I know that some security-conscious users would get really mad if we opened ports without asking them.

**Comment by iliajie** [comment]
Alright, then we shouldn't change it.

Perhaps, we should add support for some evn variables that Webmin installer could read and decide which port a user wants,  if the port in firewall should be opened, which address to bind and etc .. or it's pretty niche feature?

**Comment by chris001** [comment]
`Install complete.  Open port for webmin (10000) ? [y/N]`

**Comment by jcameron** [comment]
Seems like a pretty niche feature to me. But what we could do is add a step to the install docs saying something like "to open port 10000 on your firewall after installation, run `webmin open-port 10000`"

**Comment by swelljoe** [comment]
We absolutely cannot ask questions in the package postinstall script. We're not even supposed to have output in RPMs.

And, Webmin should not change the firewall. This is a job for documentation.
