### ISSUE TITLE
.pro domains are considered "not a valid address"

### ISSUE THREAD

**Issue by benanamen** [webmin/webmin#2037]
Trying to add a virtual host or a Sendmail email address mapping with a .pro domain extension results in "not a valid address" error. Unable to complete tasks.

**Comment by jcameron** [comment]
Can you post the full error message you're getting, and also a screenshot of the page you're getting it on?

**Comment by benanamen** [comment]
![Screenshot 2023-10-25 at 14-36-21 Apache Webserver_Error — Webmin 2 102 (Debian Linux 12)](https://github.com/webmin/webmin/assets/1039435/5f8e4f90-8155-4b1b-8749-d9c7d63e2a96)
![Screenshot 2023-10-25 at 14-36-58 Apache Webserver — Webmin 2 102 (Debian Linux 12)](https://github.com/webmin/webmin/assets/1039435/bd4d2cfc-ed10-4e92-9a03-f2853e8d7126)
![Screenshot 2023-10-25 at 14-38-09 Sendmail Mail Server_Error — Webmin 2 102 (Debian Linux 12)](https://github.com/webmin/webmin/assets/1039435/f756e96e-4d5c-41ee-9097-fce5c5a2d94f)

**Comment by jcameron** [comment]
I think that error means that Webmin cannot resolve anydomain.pro to an IP address. Does it already exist in DNS?

**Comment by swelljoe** [comment]
You've put it in the IP address field. Domain names go in the Server Name field.

**Comment by iliajie** [comment]
@benanamen You should really consider using Virtualmin (the module for Webmin).

www.virtualmin.com/download

**Comment by benanamen** [comment]
> I think that error means that Webmin cannot resolve anydomain.pro to an IP address. Does it already exist in DNS?

I only used that as an example. Same result with my real domain name.

**Comment by jcameron** [comment]
If you SSH into your system, can you ping `virtualmin.pro` or whatever valid hostname you tried entering?

**Comment by benanamen** [comment]
The domain is up and working no problem. The problem is I had to manually edit config files for a .pro extension. A domain name is a perfectly valid value for the address field as per the Apache docs, although not recommended. I have had numerous domains running with the virtualhost directive set to a domain name and not an IP. This is a Webmin issue with .pro extensions for at least two unrelated GUI config settings.

Apache Docs:

\<VirtualHost> and \</VirtualHost> are used to enclose a group of directives that will apply only to a particular virtual host. **Any directive that is allowed in a virtual host context may be used.** When the server receives a request for a document on a particular virtual host, it uses the configuration directives enclosed in the <VirtualHost> section.  **Addr can be any of the following**, optionally followed by a colon and a port number (or *):

The IP address of the virtual host;
**A fully qualified domain name for the IP address of the virtual host (not recommended);**
The character *, which acts as a wildcard and matches any IP address.
The string _default_, which is an alias for *
    
Source: [https://httpd.apache.org/docs/2.4/mod/core.html#virtualhost](url)

**Comment by jcameron** [comment]
So I think the real issue is that Webmin cannot resolve the `.pro` domain name to an IP address. Which is odd if it can be resolved by your Linux system on the command line ...

**Comment by iliajie** [comment]
> The domain is up and working no problem. The problem is I had to manually edit config files for a .pro extension. A domain name is a perfectly valid value for the address field as per the Apache docs, although not recommended.

What output do you get if you run on your system:

```
host yourdomain.pro
```

**Comment by benanamen** [comment]
> > The domain is up and working no problem. The problem is I had to manually edit config files for a .pro extension. A domain name is a perfectly valid value for the address field as per the Apache docs, although not recommended.
> 
> What output do you get if you run on your system:
> 
> ```
> host yourdomain.pro
> ```

host perfectstorage.pro
perfectstorage.pro has address 70.35.199.194
perfectstorage.pro mail is handled by 10 mail.perfectstorage.pro.

**Comment by jcameron** [comment]
One more possibility is that the running Webmin process is somehow caching old DNS records or DNS resolvers. You might want to try SSHing in as `root` and running `/etc/webmin/restart`
