### ISSUE TITLE
Webmin not updating on Ubuntu 16

### ISSUE THREAD

**Issue by kenara** [webmin/webmin#2039]
I have a few virtual servers running Ubuntu 16 that no longer update automatically. For a couple of versions, there was an error that could be solved using `apt-get -y install webmin --allow-unauthenticated`, which I executed with some trepidation given that it's Webmin, but now even that can't get me past 2.102. Here's the result as of today:

`> apt-get -y install webmin --allow-unauthenticated
Reading package lists...
Building dependency tree...
Reading state information...
webmin is already the newest version (2.102).`

I know, Ubuntu 16 is old but I need it.

What would be the simplest way forward?

**Comment by iliajie** [comment]
Hi,

The easiest way would be to setup Webmin repos:

```
wget https://raw.githubusercontent.com/webmin/webmin/master/setup-repos.sh
sh setup-repos.sh
```

**Comment by kenara** [comment]
Thanks! That was easy...
