### ISSUE TITLE
DNS: Remote create zone on slave record is not correct

### ISSUE THREAD

**Issue by iliajie** [webmin/webmin#2041]
Hello Jamie!

I was looking today more into BIND DNS Webmin module when working with its API for creating slaves zones.

As some users reported that _links_ on **Servers ⇾ BIND DNS Server** for **Existing DNS Zones** were looking odd as `edit_*.cgi`, e.g.:

![image](https://github.com/webmin/webmin/assets/4426533/42b30f41-d188-456b-a35b-3a30642c02b0)

As Virtualmin creates a slave zone on remote system using `create_zone_on_slaves` (upon domain creating time), `/etc/webmin/bind8/zone-names` file (on remote system) receives the new record without index, e.g.:

```
zone_8=sub4.ubuntu22-pro.virtualmin.dev         slave   *       0       /var/named/slaves/sub4.ubuntu22-pro.virtualmin.dev.hosts
```

This makes `list_zone_names()` return unexpected data-structures. 

When the cache is manually cleared using `flush_zone_names()` the record inside of `zone-names` then re-created as expected, i.e.:

```
zone_8=sub2.ubuntu22-pro.virtualmin.dev 11      slave   *       0       /var/named/slaves/sub2.ubuntu22-pro.virtualmin.dev.hosts
```

What is the real source of this issue?

**Comment by jcameron** [comment]
Check out the attached patch - it should fix this issue.

**Comment by iliajie** [comment]
This patch fixed the issue! Thank you!
