### ISSUE TITLE
ProFTPd - Add GUI option to enforce TLS/FTPS easily

### ISSUE THREAD

**Issue by shoulders** [webmin/webmin#2045]
|  SYSTEM INFORMATION||
|----------------------|---------------------------|
|  OS type and version |     Ubuntu Linux 22.04.3     |
|  Webmin version      |     2.101      |
|  Usermin version     |     2.001     |
|  Virtualmin version  |     7.8.2       |
|  Theme version       |     21.04      |
|  Package updates     |      3  package updates are available   |

I would like the ability to force TLS for FTP from the GUI for ProFTPd. This is useful because as a lot of people use FTP and do not want to use SFTP + chroot for their clients but yet want more security than just using plain text. The TLS system for ProFTPd is enables, so why not give a quick option to enforce it.

### Solution

in **/etc/proftpd/conf.d/virtualmin.com** you have the following section that enables TLS. The hard work is done. :smile:

```html
# Enable TLS
<IfModule !mod_tls.c>
  LoadModule mod_tls.c
</IfModule>

TLSEngine                     on
TLSRequired                   off
TLSRSACertificateFile         /etc/ssl/certs/proftpd.crt
TLSRSACertificateKeyFile      /etc/ssl/private/proftpd.key
TLSOptions                    NoSessionReuseRequired
TLSVerifyClient               off
TLSLog                        /var/log/proftpd/tls.log
<IfModule mod_tls_shmcache.c>
  TLSSessionCache             shm:/file=/var/run/proftpd/sesscache
</IfModule>
```

This would require the following
- In `Webmin -->Servers --> ProFTPD --> Network Options` add a html option for
  - `TLSRequired` on/off radio field
  - `TLSProtocol`  input fiield,  with a suitable value `TLSv1.2 TLSv1.3` that is pulled from the conf file. If needed this field could have an off value where this values is not written to the conf.

The on/off is obvious, making this easy for the server admin (and newbies) just to turn FTPS on quickly. The `TLSProtocol` option is for going forward as some sysadmins might want to disable TLSv1.2 or even just see what protocols are currently enabled.

**For reference:** 
http://www.proftpd.org/docs/howto/TLS.html

**Comment by jcameron** [comment]
Good idea, I'll look into this ...

**Comment by jcameron** [comment]
Ok this has been implemented for inclusion in the next Webmin release..

**Comment by shoulders** [comment]
@jcameron Did this get implemented, I cannot see the settings (`TLSRequire, TLSProtocol`) in `Webmin -->Servers --> ProFTPD --> Network Options`

![image](https://github.com/webmin/webmin/assets/319997/4531948b-49f2-4f58-88b0-269e768b67ba)

I also looked in the other ProFTPD settings

**Comment by jcameron** [comment]
Yes, it's on the SSL Options page in the ProFTPd module.

**Comment by shoulders** [comment]
there is no `SSL Options` page on authentic theme

![image](https://github.com/webmin/webmin/assets/319997/9dba6ab7-6ef4-460b-a7e5-55c7b59157d9)

 I also had a quick look on framed theme but could not see it there either

![image](https://github.com/webmin/webmin/assets/319997/de0acabd-95ad-42c2-a3df-8e06c63fffbf)

Am I missing something? I have gone through each of the sections (icons) but cannot find these settings

**Comment by jcameron** [comment]
Hmm ... perhaps Webmin isn't detecting the SSL proftpd module?

What does /etc/webmin/proftpd/site contain on your system?

**Comment by jcameron** [comment]
Try deleting that file and then re-opening the ProFTPd module.

**Comment by jcameron** [comment]
What output do you get if you run `proftpd -l` to list the installed modules?

**Comment by shoulders** [comment]
here you go
```
Compiled-in modules:
  mod_core.c
  mod_xfer.c
  mod_rlimit.c
  mod_auth_unix.c
  mod_auth_file.c
  mod_auth.c
  mod_ls.c
  mod_log.c
  mod_site.c
  mod_delay.c
  mod_facts.c
  mod_dso.c
  mod_auth_pam.c
  mod_cap.c
  mod_ctrls.c
  mod_lang.c
```

**Comment by iliajie** [comment]
See this https://github.com/webmin/webmin/pull/2181.

**Comment by shoulders** [comment]
Thanks for to the hard work @jcameron and @iliaross even if I am quiet I do notice 😄 , can't wait to try it.

**Comment by iliajie** [comment]
It's already in the nightly build.

**Comment by shoulders** [comment]
The patch did not allow ` SSL Options page in the ProFTPd module` to become visible.

| SYSTEM INFORMATION ||
|----------|----------|
|  OS type and version |  Ubuntu Linux 22.04.4                                             |
|  Usermin version     |  2.102                                                            |
|  Virtualmin version  |  7.20.2                                                           |
|  Theme version       |  21.20.7                                                          |
|  Apache version      |  2.4.52                                                           |
|  Package updates     |  42 package updates are available, of which 1 is security update  |

![image](https://github.com/user-attachments/assets/b72ada73-1961-4782-89ba-d025a89e36bf)

**Comment by jcameron** [comment]
Posssibly Webmin doesn't know that the SSL module is enabled on your system ... What does `/etc/webmin/proftpd/site` contain on your server?

**Comment by shoulders** [comment]
@jcameron here you go

### /etc/webmin/proftpd/site

```bash
version=1.37
size=1228048
modules=mod_core mod_xfer mod_rlimit mod_auth_unix mod_auth_file mod_auth mod_ls mod_log mod_site mod_delay mod_facts mod_dso mod_auth_pam mod_cap mod_ctrls mod_lang
fullversion=1.3.7
```

### proftpd -l

```
sudouser@myserver:~$ proftpd -l
Compiled-in modules:
  mod_core.c
  mod_xfer.c
  mod_rlimit.c
  mod_auth_unix.c
  mod_auth_file.c
  mod_auth.c
  mod_ls.c
  mod_log.c
  mod_site.c
  mod_delay.c
  mod_facts.c
  mod_dso.c
  mod_auth_pam.c
  mod_cap.c
  mod_ctrls.c
  mod_lang.c
```

**Comment by iliajie** [comment]
You should just `rm -f /etc/webmin/proftpd/site`.

**Comment by shoulders** [comment]
> You should just rm -f /etc/webmin/proftpd/site.

![image](https://github.com/user-attachments/assets/ed696dc8-31f5-4de2-96c5-debce01d65fc)


This has worked this time. 😄 , Thanks

Is there anyway of fixing this for other users?

**Comment by iliajie** [comment]
> Is there anyway of fixing this for other users?

Well, I would just remove the entire `site` caching. I don’t see any value in it. Running `proftpd -vv` is super fast.

We’ll wait and see what Jamie thinks about it.

**Comment by jcameron** [comment]
I recently checked in a fix to better auto-update that `site` file
