### ISSUE TITLE
Running Processes Memory Information

### ISSUE THREAD

**Issue by qooob** [webmin/webmin#205]
Jamie, I just compared data that is provided by `Running Processes -> Memory` _with_ `System Monitor` (in Fedora) - it is drastically different! I think it worth checking!

**Comment by jcameron** [comment]
It looks OK on my system .... can you post what you are seeing?

**Comment by qooob** [comment]
On 02/05/2015 19:57, Jamie Cameron wrote: 

> It looks OK on my system .... can you post what you are seeing? 
> 
> --
> Reply to this email directly or view it on GitHub [1].
 

Links:
------
[1] https://github.com/webmin/webmin/issues/205#issuecomment-98379702

**Comment by qooob** [comment]
Sure, compare two tables please and see the drastic difference. Which software is wrong?? :)

![screenshot from 2015-05-02 21 25 51](https://cloud.githubusercontent.com/assets/4426533/7442249/36832c6c-f112-11e4-9a95-824b60921b2a.png)
![screenshot from 2015-05-02 21 26 02](https://cloud.githubusercontent.com/assets/4426533/7442250/3685c990-f112-11e4-9662-58a348775d07.png)

**Comment by jcameron** [comment]
"memory usage" in Linux isn't an exact science - some tools show how much actual RAM is used right now, and some show the total size of the process. If you run the "top" command, does it agree with Webmin?

**Comment by qooob** [comment]
Yes, it does!  `isn't an exact science` :) Well, yeah but it can't be 4 times different. What should I believe? Webmin (and top) or System Monitor?

**Comment by jcameron** [comment]
Which one does "top" agree with?

A 4x different for a large process is quite possible if it has a lot of shared libraries..

**Comment by qooob** [comment]
`top` agrees with Webmin! ;)

**Comment by swelljoe** [comment]
top is always right. However, top actually shows RSS and virt. I think we should probably show both in Webmin, as well. The "total" memory can be misleading when most of it is swapped out or memory mapped from disk.

**Comment by qooob** [comment]
Probably both, so it would then collerate with System Monitor in Fedora.. meaning don't disgrace System Monitor. :)
