### ISSUE TITLE
Add Windows 11 to the OS list

### ISSUE THREAD

**Issue by shoulders** [webmin/webmin#2055]
I just noticed windows 11 was not on the OS list but this chap on YouTube has installed Webmin on windows 11 via Cygwin.

[How to install Webmin on Window | YouTube](https://www.youtube.com/watch?v=bk0R0RpybnM)

Does it need adding?

https://github.com/webmin/webmin/blob/fd44191c962833457e0ec57ef72154d4957ac399/os_list.txt#L450-L459

**Comment by iliajie** [comment]
Cygwin is a compatibility layer. What you have listed above is meant for systems where Webmin is installed directly, I think. We should ask Jamie &mdash; why do we have all these Windows systems listed .. we don't have direct Windows support? 

Perhaps instead we should remove those mentions of Windows, and fix Cygwin line in `os_list.txt` to support latest versions of Cygwin?

**Comment by jcameron** [comment]
Yeah we did support Windows in the past without Cygwin, but it was very very hacky. I think we should remove the support..

**Comment by iliajie** [comment]
Alright, I have removed it.
