### ISSUE TITLE
Jailkit Page - rsync missing description

### ISSUE THREAD

**Issue by shoulders** [webmin/webmin#2056]
|  SYSTEM INFORMATION||
|----------------------|---------------------------|
|  OS type and version |     Ubuntu Linux 22.04.3     |
|  Webmin version      |     2.105      |
|  Usermin version     |     2.005     |
|  Virtualmin version  |     7.8.2       |
|  Theme version       |     21.09.5      |
|  Package updates     |      19  package updates are available   |

On the page Webmin --> System --> Jailkit Jail Manager 

rsync is missing its second cell with its description in it

![image](https://github.com/webmin/webmin/assets/319997/ebf7cac2-ce4f-469f-a9b1-3596a1a363de)

## Notes
I was not sure if this was a webmin or a Authentic theme issue, is there a good way of deciding?

**Comment by iliajie** [comment]
> I was not sure if this was a webmin or a Authentic theme issue, is there a good way of deciding?

Neither. However, we shouldn't break the table output if the comment is missing. We will fix that.

Thanks for the heads up!
