### ISSUE TITLE
All tabs layers permanently exploded when in Authentic theme

### ISSUE THREAD

**Issue by rdmark** [webmin/webmin#2058]
When you build a tabs layout with the following pseudo code example as an illustration:

```
ui_tabs_start
ui_tabs_start_tab
<p>foo</p>
ui_tabs_end_tab
ui_tabs_start_tab
<p>bar</p>
ui_tabs_end_tab
ui_tabs_end
```

I expect to see only "foo" with a tab to switch to "bar". However when the Authentic theme is enabled, both foo and bar are permanently visible. If you switch to the Framed or Legacy themes the tabs are rendered correctly.

**Comment by rdmark** [comment]
The test case in question is the vsftpd-webmin module, specifically the render_tabs and related functions in: https://github.com/rdmark/vsftpd-webmin/blob/main/libvsftpdconfig/HtmlUICreator.pm

<img width="1278" alt="Screenshot 2023-12-10 at 8 04 25" src="https://github.com/webmin/webmin/assets/2108467/5818842d-ba81-468d-a53d-29077392778d">
<img width="1280" alt="Screenshot 2023-12-10 at 8 03 57" src="https://github.com/webmin/webmin/assets/2108467/7b42e1fe-e9f2-4e1b-b2d3-eef98d4d88e2">

**Comment by jcameron** [comment]
@iliajie possible theme issue?

**Comment by iliajie** [comment]
> @iliajie possible theme issue?

I don't think it is. I think the module incorrectly prints a closing tag, for example `</div>`, in the wrong place. Gray Theme is just more forgiving.

**Comment by rdmark** [comment]
I figured out a workaround. The tabs has to be nested inside the form, and not vice versa.

The code originally did:

```
ui_tabs_start
ui_form_start
...contents
ui_form_end
ui_tabs_end
```

After changing to this the tabs started working in the Authentic theme:


```
ui_form_start
ui_tabs_start
...contents
ui_tabs_end
ui_form_end
```

**Comment by iliajie** [comment]
Alright!
