### ISSUE TITLE
Download not working for files with spaces in filename

### ISSUE THREAD

**Issue by JuergenBausa** [webmin/webmin#2059]
Downloading a file from the server that is managed by webmin does not work if the filename contains a space. Without spaces it works fine.

I use webmin 2.105 on debian bookworm.

Regards,
Jürgen

**Comment by jcameron** [comment]
Thanks for reporting this! Which Webmin module is this error in?

**Comment by JuergenBausa** [comment]
Its under "Tools" - "Upload and Download" - "Download from Server". I attach screenshots.

Jürgen
![Screenshot_20231210_190758](https://github.com/webmin/webmin/assets/54506740/f05ed248-bc1e-4117-939e-1da85c39f639)
![Screenshot_20231210_190901](https://github.com/webmin/webmin/assets/54506740/4313df09-a07e-4c7a-a5d0-95da0e3bf04b)

**Comment by iliajie** [comment]
I can see what's causing this bug! We will fix this in the next Webmin and Authentic Theme release.

Thanks for the heads up!
