### ISSUE TITLE
virtualmin nginx ipv6

### ISSUE THREAD

**Issue by bush6** [webmin/webmin#206]
For every ipv6 listen directive in the config files that virtualmin generates the default directive is included. Also the ipv6only flag is included on every listen directive for ipv6 which causes errors if the ipv6 is shared between multiple websites.

ipv6 only is unnecessary for an ipv6 only address and is default in newer nginx versions anyway.

**Comment by jcameron** [comment]
I'm a bit confused - can you post the incorrect directive that Virtualmin is creating, and highlight the part that is wrong?

**Comment by bush6** [comment]
I have done a bit more research and have figured out that the directives are right but its setting every new server on a shared ipv6 as default. Also the ipv6only flag shouldn't be set to on on shared ipv6 except for the default server.

If i create a new server with a shared ipv6 it sets the ipv6 automatically as default even if there is already a default which prevents nginx from starting as there is multiple default server directives for a single ipv6.

Only one listen block can Be default  And only the default can have ipv6only=on

**Comment by jcameron** [comment]
Ok, I see the bug here - this will be fixed in the next Virtualmin Nginx plugin release.

**Comment by alsemany** [comment]
Hello, 
it seems that this bug is not fixed yet.
can you please tell me a way to modify the code to remove 
`default ipv6only=on
`
thank you

**Comment by jcameron** [comment]
Which version of the plugin are you running there?

**Comment by alsemany** [comment]
I'm using 
`ii  webmin-virtualmin-nginx         1.8                  all                  Webmin module for 'Nginx Webserver'
`

I already changed the code 
`if ($d->{'ip6'}) {
		push(@{$server->{'members'}},
			{ 'name' => 'listen',
			  'words' => [ '['.$d->{'ip6'}.']'.$portstr, 
				      'default' , 'ipv6only=on' ] });
		}
`
to be 
`	if ($d->{'ip6'}) {
		push(@{$server->{'members'}},
			{ 'name' => 'listen',
			  'words' => [ '['.$d->{'ip6'}.']'.$portstr,
				        ] });
		}
`


and it works great 
please let me know if there's something wrong in my configuration 
thank you

**Comment by jcameron** [comment]
Looks like the version you have is behind our latest release. Did you install Virtualmin using the `install.sh` script, and is this the GPL or pro version?

**Comment by alsemany** [comment]
yes I used install.sh, it's the GPL version

**Comment by jcameron** [comment]
Ok, looks like our repository is out of date. The 2.0 version should show up there shortly..

**Comment by vishnunuk** [comment]
I am still getting the same problem with fresh debain 8 installation (GPL install.sh).

**Comment by kangarooo** [comment]
Is it fixed? Witch is correct way to install for ivp6 ? https://www.virtualmin.com/documentation/web/nginx ?
Failed to start service : Job for nginx.service failed because the control process exited with error code. See "systemctl status nginx.service" and "journalctl -xe" for details.

**Comment by JiahanLiu** [comment]
I'm getting the same issue as kangarooo. Following the tutorial: https://www.digitalocean.com/community/tutorials/how-to-set-up-a-node-js-application-for-production-on-ubuntu-14-04
