### ISSUE TITLE
Translation to german: misleading option "Download from server"

### ISSUE THREAD

**Issue by JuergenBausa** [webmin/webmin#2060]
I run webmin 2.105 on debian bookworm with german language settings. The option "Download from server" is translated as "Download zum Server" (="Download to Server"). It should be "Download vom Server".

Regards,

Jürgen

**Comment by jcameron** [comment]
Can you attach a screenshot showing which page in Webmin this error is on?

**Comment by iliajie** [comment]
I think it's here https://github.com/webmin/webmin/commit/e264daebe04259b760db70fac098faf54aefff52.
