### ISSUE TITLE
Install DHCP failed on RHEL 9

### ISSUE THREAD

**Issue by discostur** [webmin/webmin#2066]
Hi,

```
Installing package(s) with command /bin/dnf -y install dhcp ..

Last metadata expiration check: 1:17:40 ago on Thu Dec 28 14:31:50 2023.
No match for argument: dhcp
Error: Unable to find a match: dhcp

``` 

The dhcp server module / rpm is named `dhcp-server` on rhel 9 to the install command should be changed to the new package name. 

Regards,
Kilian

**Comment by jcameron** [comment]
Thanks, we'll fix this in the next Webmin release.
