### ISSUE TITLE
Uninitialized value during install process

### ISSUE THREAD

**Issue by k0nsl** [webmin/webmin#207]
A minor issue and could for all I know already be fixed.

```
Running postinstall scripts ..
Use of uninitialized value in -r at /usr/local/webmin/webalizer/webalizer-lib.pl line 16.
..done
```

System:
```
root@k0nsl-test01:/tmp/webmin-1.740# cat /etc/os-rel*
NAME="Ubuntu"
VERSION="15.04 (Vivid Vervet)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 15.04"
VERSION_ID="15.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
root@k0nsl-test01:/tmp/webmin-1.740#
```

When logging in, it's all fine. It seems. But if you change the theme to the new default (Authentic) it will result in the dreaded "spinning"-forever routine, and my developer console tells me the following:
```Failed to load resource: the server responded with a status of 500 (Perl execution failed)```

**Comment by jcameron** [comment]
Thanks - I will fix this warning up in the next release.
