### ISSUE TITLE
Suggestion: System log viewer

### ISSUE THREAD

**Issue by stigjoergensen** [webmin/webmin#2074]
A way to let people add new commands to interact with the journal... 

Like for the DHCP server it would be nice to be able to see the logs executed by this command:
```
journalctl -u isc-dhcp-server -f
```

and for the DNS server that command could be
```
journal -u named -f
```

perhaps i dont need a fancy webinterface, i could just be a txt file located some please that could be appended to the existing set of commands.

**Comment by iliajie** [comment]
Implemented here https://github.com/webmin/webmin/pull/2170.
