### ISSUE TITLE
Software Package Updates - email notfication for security updates

### ISSUE THREAD

**Issue by shoulders** [webmin/webmin#2075]
|  SYSTEM INFORMATION||
|----------------------|---------------------------|
|  OS type and version |     Ubuntu Linux 22.04.3     |
|  Webmin version      |     2.105      |
|  Usermin version     |     2.005     |
|  Virtualmin version  |     7.9.0       |
|  Theme version       |     21.09.5      |
|  Package updates     |      15  package updates are available   |

## Current
![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/242ea260-7298-4611-915d-21d8ecc20770)

You can set a schedule and then be notified of any updates, but this is for all updates.

## Request
I would like to add the additional option of 
- Just Notify (Security Updates Only)

this would allow me to get notified of security updates that do need applying rather than getting notified by all updates which I would then start ignoring.

**Comment by jcameron** [comment]
Sure, that's a good suggestion! I will look into implementing it now ...
