### ISSUE TITLE
 Websocket error when use Nginx as reverse proxy

### ISSUE THREAD

**Issue by yazdanMhmmdi** [webmin/webmin#2078]
Hi i use nginx as web server and reverse proxy to direct admin.exmaple.com subdomain to http://localhost:1000 and is working very well but as you need to open terminal in webmin, terminal stuck on Connecting...
console log in browser:
bundle.min.js?219500009999999999:178 Mixed Content: The page at 'https://admin.example.com/filemin/index.cgi?xnavigation=1' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://admin.example.com/xterm/ws-559'. This request has been blocked; this endpoint must be available over WSS.

(anonymous) @ bundle.min.js?219500009999999999:178
bundle.min.js?219500009999999999:178 Uncaught DOMException: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.
    at https://admin.example.com/unauthenticated/js/bundle.min.js?219500009999999999:178:81702

nginx /etc/nginx/sites-available/default config i replaced my domain name with example.com:

  server {
	  root /var/www/html;
	  index index.html index.htm index.nginx-debian.html;
	  server_name example.com;
  
	  location / {
		  # First attempt to serve request as file, then
		  # as directory, then fall back to displaying a 404.
		  proxy_pass http://example2.com;
	  }
  
      listen [::]:443 ssl ipv6only=on; # managed by Certbot
      listen 443 ssl; # managed by Certbot
      ssl_certificate /etc/letsencrypt/live/example.com/fullchain.pem; # managed by Certbot
      ssl_certificate_key /etc/letsencrypt/live/example.com/privkey.pem; # managed by Certbot
      include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
      ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
  
  }
  server {
    server_name admin.example.ir;
    
        
          location / {
                  proxy_pass http://127.0.0.1:10000/;
                  proxy_set_header Host $host;
                  proxy_set_header X-Forwarded-For $http_x_forwarded_for;
                  proxy_redirect http://$host:10000/ http://$host/;
                  proxy_read_timeout 86400;
		  proxy_set_header   Upgrade $http_upgrade;
             	  proxy_set_header   Connection Upgrade;
             	  proxy_set_header   Host $host;
  
           }
  
  
      listen 443 ssl; # managed by Certbot
      ssl_certificate /etc/letsencrypt/live/admin.example.com/fullchain.pem; # managed by Certbot
      ssl_certificate_key /etc/letsencrypt/live/admin.example.com/privkey.pem; # managed by Certbot
      include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
      ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
  
  }
#test
  server {
	  root /var/www/html/apps/web;
          server_name test.example.com;
          index index.html index.htm;
	  location / {
		  try_files $uri $uri/ =404;	
  
	  }
          location /api/ {
                  # First attempt to serve request as file, then
                  # as directory, then fall back to displaying a 404.
 		  
                  proxy_pass http://localhost:3000; #whatever port your app runs on
                  proxy_http_version 1.1;
                  proxy_set_header Upgrade $http_upgrade;
                  proxy_set_header Connection 'upgrade';
                  proxy_set_header Host $host;
                  proxy_cache_bypass $http_upgrade;
          }
  
  
  
  
      listen 443 ssl; # managed by Certbot
      ssl_certificate /etc/letsencrypt/live/test.example.com/fullchain.pem; # managed by Certbot
      ssl_certificate_key /etc/letsencrypt/live/test.example.com/privkey.pem; # managed by Certbot
      include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
      ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
  
  }
server {

        root /var/www/html/apps/web;
        server_name ab.example.com;
        index index.html index.htm;
        location / {
                try_files $uri $uri/ =404;      

        }

        location /api/ {
          
                proxy_pass http://localhost:3001; #whatever port your app runs on
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection 'upgrade';
                proxy_set_header Host $host;
                proxy_cache_bypass $http_upgrade;
        }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/ab..example.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/ab..example.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
server {

        root /var/www/html/apps/web;
        server_name dip.example.com;
        index index.html index.htm;
        location / {
                try_files $uri $uri/ =404;

        }

        location /api/ {

                proxy_pass http://localhost:3002; #whatever port your app runs on
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection 'upgrade';
                proxy_set_header Host $host;
                proxy_cache_bypass $http_upgrade;
        }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/dip.example.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/dip.example.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}

server {
    if ($host = example.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

	listen 80 default_server;
	listen [::]:80 default_server;

	server_name example.com;
    return 404; # managed by Certbot

}

server {
    if ($host = admin. example.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

        server_name admin.example.com;
    listen 80;
    return 404; # managed by Certbot

}

server {
    if ($host = test. example.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

        server_name test.example.com;
    listen 80;
    return 404; # managed by Certbot

}

server {
    if ($host = ab.example.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

        server_name ab.example.com;
    listen 80;
    return 404; # managed by Certbot

}
server {
    if ($host = dip.example.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

        server_name dip.example.com;
    listen 80;
    return 404; # managed by Certbot

}

server {
    if ($host = admin.example.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

  server_name admin.example.com;
    listen 80;
    return 404; # managed by Certbot

}

thanks.
![1](https://github.com/webmin/webmin/assets/71337251/6a7b5111-452c-4d2d-bae1-4355f01f2daa)
![2](https://github.com/webmin/webmin/assets/71337251/de46ccdc-eaff-49fb-b80c-3b2d19826d6e)
![3](https://github.com/webmin/webmin/assets/71337251/780d34c2-b6de-410f-b27e-b9dd698cbba7)

**Comment by chris001** [comment]
Your admin page is loaded through HTTPS, so Webmin browser code should detect this and only use WSS - browsers don't allow to "downgrade" security to WS.

**Comment by jcameron** [comment]
Maybe you need to run Webmin in SSL mode and proxy to https://localhost:10000/ ?

**Comment by yazdanMhmmdi** [comment]
i enabled SSL in Webmin Configuration -> SSL Encryption then change nginx config from
```
proxy_pass http://127.0.0.1:10000/;
proxy_redirect http://$host:10000/ http://$host/;
```
to
```
proxy_pass https://127.0.0.1:10000;
proxy_redirect https://$host:10000/ http://$host/;
```
and seems problem is solved thanks for your support.

**Comment by iliajie** [comment]
> and seems problem is solved thanks for your support.

We're glad to hear that! It is also documented here in [FAQ - Can I run Webmin or Usermin behind reverse proxy?](https://webmin.com/faq/#can-i-run-webmin-or-usermin-behind-reverse-proxy).
