### ISSUE TITLE
Inconsistent options in database search vs. advanced search

### ISSUE THREAD

**Issue by PitWenkin** [webmin/webmin#2079]
When viewing a database table a simple search allows to filter the results by a single field, with the options `contain`, `matches`, `doesn't contain`, `doesn't match`, `greater than`, `less than`

![Screenshot 2024-01-17 at 09 59 43](https://github.com/webmin/webmin/assets/45786226/a994f379-415f-4045-aa3c-17d0852c0699)

Should be generated at: https://github.com/webmin/webmin/blob/3a5dcc4723ad1f4174061c4c6d36b69e49dc23dd/mysql/view_table.cgi#L461

The advanced search linked directly below the form, while allowing to search in multiple field only allows the options `contains`, `matches`, `doesn't contain`, `doesn't match` for each field.

![Screenshot 2024-01-17 at 09 59 55](https://github.com/webmin/webmin/assets/45786226/7ed1b709-8562-438b-859f-aea21ed48563)

Should be generated at: https://github.com/webmin/webmin/blob/3a5dcc4723ad1f4174061c4c6d36b69e49dc23dd/mysql/search_form.cgi#L24

(I guess the same is true for postgresql)

Woudl it be possible to get the `greater than` and `less than` options in the advanced search too?

**Comment by iliajie** [comment]
Thank you for an excellent bug report! The fix is here https://github.com/webmin/webmin/commit/70a15314c0544e54da7bdf639f905e139c571b4b.
