### ISSUE TITLE
Failed to install module from /usr/local/csf/csfwebmin.tgz

### ISSUE THREAD

**Issue by actionm** [webmin/webmin#208]
CentOS Linux 6.6
CSF 7.67

http://doxfer.webmin.com/Webmin/ConfigServer_Security_%26_Firewall

Failed to install module from /usr/local/csf/csfwebmin.tgz : Not a valid module file : /bin/tar_orig: You must specify one of the `-Acdtrux' or`--test-label' options Try `/bin/tar_orig --help' or`/bin/tar_orig --usage' for more information.

**Comment by qooob** [comment]
Why don't you extract it manually!? It works fine with Webmin and Authentic Theme supports CSF fully! ;)

**Comment by swelljoe** [comment]
This one is, I think, out of our control, as we don't package that module. I think it'd need to be taken up with the folks who package the module; there is a "create-module.pl" script that makes it easy to make a wbm.gz package from a module (and also a makemodulerpm.pl and makemoduledeb.pl that make it easy-ish to make RPM and deb packages, too). Perhaps the authors of this module can be give pointers to those?

**Comment by qooob** [comment]
After CSF is instilled they provide instructions in console and a link from the installed package that should be paste to Install Module. It's working now at least now for sure.
