### ISSUE TITLE
Halts on save incorrect ipv6 firewall rule

### ISSUE THREAD

**Issue by zoigecyb** [webmin/webmin#2081]
So, what i did.

Added ipv6 fw rule with source address 2xxx:xx::/48 2xxx:xxx::/64

When this 2 ips was from new line webmin stucks that illegal rule 2xxx::/64 in /etc/webmin/firewall6/iptables.save

Ok, i manually opened file and really saw that there is line
2xxx::/64 -j ACCEPT (without  -A INPUT -s) 

When i added this 2 adresses separated with space webmin halts. So i needed to remove line

-A INPUT -s "2xxx::/48 2xxx:bb::/64" - j ACCEPT
and manually via ssh did service webmin restart

As you see this is not correct 2 addresses with quotes.

For now i used 2 separate rules.

**Comment by jcameron** [comment]
When you say "webmin halts", what error message did you get exactly?

**Comment by zoigecyb** [comment]
Oh, sorry for my english..
With "webmin halts" i meant that it is not reponding neither via ipv4 nor via ipv6 address.
got timeout.

So, i tested once again.
When i add simple rule with two ipv6 separated with space and click save webmin starting "running red line" at top of screen and... I waited about 20mins) and when i clicked refresh page in browser i got timeout.

Second test:
i save this rule. And tried to access webmin via ipv4 (is separate tab) It worked for about 5 mins.

Third test:
Access webmin via ipv4. Same ipv6 rule. It is accessable about 5 mins. After that - timeout.

P.s. 
To get ability to access it via ipv6 i had to manually install libsocket6-perl, which is not preinstalled.

P.p.s
With rule
-A INPUT -s "2xxx::/48 2xxx:bb::/64" - j ACCEPT

the whole ipv6 not working anymore. So i had to restart webmin and also make ip6tables-legacy -F

Also, sorry for long post.
Why webmin on one server uses iptables and on another iptables-legacy?
Tested on clean systems ubuntu 20.04

**Comment by jcameron** [comment]
Are you sure that this rule isn't somehow blocking access to Webmin itself? I don't know what IPv6 address your are accessing it from..

Also, yes it is expected that the Socket6 package is required for IPv6 support to work in Webmin. We should add that as a dependency though..

**Comment by zoigecyb** [comment]
So, lets explain.
i have 2XXX:ZZZZ:6040::/48 subnet

Webmin address is 2XXX:ZZZZ:6040:10::1/64 (as part of /48)

So my actual fw rule is
```
-A INPUT -s 2XXX:ZZZZ:6040::/48 -j ACCEPT
```
also i have another 2aXX:50ZZ:12YY:20::/64 subnet in diff place. 
so i also need to add
```
-A INPUT -s 2aXX:50ZZ:12YY:20::/64 -j ACCEPT
```
If in webmin is created 2 separate rules all is ok.
but if in src address is more that 1 ipv6 it have strange behaviour.(like i described in prev posts)
And after some time (abou 5 min in my case) it stops answer to ipv4 address too.
but 
```
netstat -lnutp
```
still shows
 tcp/10000/webmin
tcp6/10000/webmin

**Comment by jcameron** [comment]
Ok I see the bug that causes this now - it will be fixed in the next release of Webmin.
