### ISSUE TITLE
PHP Configuration pages Tell me：You do not have permission to access any PHP configuration files.

### ISSUE THREAD

**Issue by stuffren** [webmin/webmin#2083]
When I go to the php configuration in the un-used modules, the php configuration page tells me: **You do not have permission to access any PHP configuration files.**
![php模块页面提示无权限](https://github.com/webmin/webmin/assets/136626456/4643fbdc-0c7f-4eb6-8f84-94ebc8757b88)

Help: How can I solve this problem?

tip:
The system version of my server is:
Distributor ID: Ubuntu
Description: Ubuntu 22.04.3 LTS
Release: 22.04
Codename: jammy

**Comment by stuffren** [comment]
@iliajie ，Thank you for your reply. 

I solved this problem myself before receiving your reply.
I just installed PHP 7.4 on my system, and now when I logged back into webmin and went to PHP Configuration, I can see the PHP configuration options.
That is to say it no longer prompts - You do not have permission to access any PHP configuration files.
![111已解决](https://github.com/webmin/webmin/assets/136626456/18039651-bda1-47a2-9c25-ec69ebbc20a7)



@iliajie  Can you please help me to see if what I did above, kind of fixed this problem? thank you! sir!

> Hello,
> 
> It means that you either don't have any PHP versions installed or there is a misconfiguration in module's config. For example, this is how the default module config should look like in Ubuntu 22.04:
> 
> <img alt="image" width="1279" src="https://private-user-images.githubusercontent.com/4426533/301886408-e318446d-ea9c-4711-b2dd-68135db47945.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4ODcxMjYsIm5iZiI6MTcwNjg4NjgyNiwicGF0aCI6Ii80NDI2NTMzLzMwMTg4NjQwOC1lMzE4NDQ2ZC1lYTljLTQ3MTEtYjJkZC02ODEzNWRiNDc5NDUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDJUMTUxMzQ2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2QyYTg5YTAwNDA1MTgyNGNkNDZlYjVkODIyYWRhODRlNWMyOTJhY2VkMTE1MzY1NzFlOWVhMjQ4ZWEyZjlmOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.9c85TwAjZA-NXPqnnZ2aJ95maOGpME5qt4INMOYm50o">
> ```
> /etc/php.ini,/etc/*/*/php*/php.ini,/etc/*/*/*php*/php.ini=Configuration for CLI and CGI
> /etc/php-fpm.conf,/etc/*/php*/php-fpm.conf,/etc/*/*/php*/php-fpm.conf=Configuration for FPM
> ```

**Comment by iliajie** [comment]
> Can you please help me to see if what I did above, kind of fixed this problem?

Yes, it all looks good! Well done!
