### ISSUE TITLE
Package Details - Show dependencies

### ISSUE THREAD

**Issue by shoulders** [webmin/webmin#2092]
|  SYSTEM INFORMATION||
|----------------------|---------------------------|
|  OS type and version |     Ubuntu Linux 22.04.3     |
|  Webmin version      |     2.105      |
|  Usermin version     |     2.005     |
|  Virtualmin version  |     7.9.0       |
|  Theme version       |     21.09.5      |
|  Package updates     |      8  package updates are available   |

### The background
This is stating the obvious 😄 Linux packages have dependencies

I can go to https://packages.ubuntu.com/ to look at files and dependencies

### The issue
It would be useful from Webmin to see what dependencies various packages have. This would help in deciding if I wanted to update a package or indeed install another package.

It might also help with diagnostics.

### Solution
I would like to be able to see the package dependences on the following pages:

- Webmin --> System --> Software Package Updates -->Package Update Tab --> _Select an update_ (installed/only updates/only new) --> Package Details
  ![image](https://github.com/webmin/webmin/assets/319997/84781076-d51d-432a-a3d8-1fdf48bee118)
- Webmin --> System -->Software Packages --> Search For Package --> _type a package in_ --> _select a package --> Edit Package
  ![image](https://github.com/webmin/webmin/assets/319997/6993b97b-6177-4216-b7c6-dbce7ffe5908)

### Additional
- Also adding `List Files` and using the `Full Description` to the `Software Package Updates/Package Details` page would also be cool.

**Comment by jcameron** [comment]
That's not a bad idea! I'll look into adding this, and also showing reverse-dependencies..

**Comment by jcameron** [comment]
This has been implemented for inclusion in the next release..
