### ISSUE TITLE
File Manager - Add freetype pagination input

### ISSUE THREAD

**Issue by shoulders** [webmin/webmin#2093]
|  SYSTEM INFORMATION||
|----------------------|---------------------------|
|  OS type and version |     Ubuntu Linux 22.04.3     |
|  Webmin version      |     2.105      |
|  Usermin version     |     2.005     |
|  Virtualmin version  |     7.9.0       |
|  Theme version       |     21.09.5      |
|  Package updates     |      8  package updates are available   |

### The issue
- The most you can advanced is 2 pages at a time (except for the first click) so if you have lots of pages it takes ages to go through the pages.
- You can only use the filter if you know the name of the file or folder you are looking for.

![image](https://github.com/webmin/webmin/assets/319997/894c3322-f24d-4faa-954b-b12dc869be16)

### The solution
Add a free type input box to allow a user to select a page number. This could be a dropdown but the the list could get quite long on some folders.

![image](https://github.com/webmin/webmin/assets/319997/88b7a583-be09-4d2c-9120-166288cd5732)

**Comment by jcameron** [comment]
@iliajie what do you think of this one?

**Comment by iliajie** [comment]
I think an input would make user interface clogged and look bad.

Sorry, I don't think this particular feature worth an effort, considering that you can just hold down left/right key to list among files, and just type to search for a needed file.

**Comment by iliajie** [comment]
@shoulders Please stop changing issue title (in GitHub) after it was published, as it creates an utter mess in our mailbox (Gmail).

**Comment by shoulders** [comment]
> Please stop changing issue title (in GitHub) after it was published, as it creates an utter mess in our mailbox (Gmail).

@iliajie will do, I just assumed you were using an APP to manage GitHub.

**Comment by iliajie** [comment]
> @iliajie will do

Thank you!

> I just assumed you were using an APP to manage GitHub.

We also use email notifications to track issues.
