### ISSUE TITLE
File Manager - Move the content filter to a more logical location

### ISSUE THREAD

**Issue by shoulders** [webmin/webmin#2094]
|  SYSTEM INFORMATION||
|----------------------|---------------------------|
|  OS type and version |     Ubuntu Linux 22.04.3     |
|  Webmin version      |     2.105      |
|  Usermin version     |     2.005     |
|  Virtualmin version  |     7.9.0       |
|  Theme version       |     21.09.5      |
|  Package updates     |      8  package updates are available   |

### Background
When I was searching for a file I had to manually click next on each page. This is related to #2093.

A bit later I found the content filter which would filters the files and folders.

### The issue

- The content filter is hidden and is not in a logical place for a file manager.
- I can see it is in the same filter and export area used for other pages in Webmin/Virtualmin. I believe that this rule should not be followed for the file manager because:
  - The folder filter is in full view at the bottom of the folders which is where I would expect it. So I would expect the 'Files and Folder' filter to be under the 'files and Folder' section
  - This is an active feature and shold not be hidden from view.

### solution
- Rename `Filter content` to `Filter`, this will match the folders filter.
- Move the 'content filter' from the top to as shown below
![image](https://github.com/webmin/webmin/assets/319997/45f9c897-3a30-4775-bd15-6a05d73adc88)

### Additional
- You can leave the export option where it is, but if it has to be moved as a pair, that is ok.
![image](https://github.com/webmin/webmin/assets/319997/42077160-73b2-4c86-8ad5-f3d1b2ae5885)

**Comment by iliajie** [comment]
Nope, that ain't happening, sorry!
