### ISSUE TITLE
Failed loading terminal : WebSocket connection error (webmin behind proxy)

### ISSUE THREAD

**Issue by Zjoz** [webmin/webmin#2096]
Following configuration advice from the [FAQ's](https://webmin.com/faq/#can-i-run-webmin-or-usermin-behind-reverse-proxy), I managed to get webmin functional via https://webmin.mydomain.xx.
Terminal (in the Tools section) is not functioning however, although it was fine without proxy.
Behaviour is that the black terminal window shows briefly, but is replaced with the next:

![image](https://github.com/webmin/webmin/assets/8567238/70d55b53-0c39-4437-83c4-00ead600d4de)

Clicking the button in the right-hand top shows a black overlay window with "CONNECTING .." as follows

![image](https://github.com/webmin/webmin/assets/8567238/7e33cc11-818b-4fb2-89e4-2d0477468857)

This issue has been reported earlier, but I could not find any relevant solution. Most recognition was with [this issue](https://forum.virtualmin.com/t/failed-loading-terminal/122868) on Virtualmin. But that resolved itself automagically.

Anyone suggestions about this?

I am running Ubuntu server 22.04.4 with Webmin 2.105.

**Comment by iliajie** [comment]
Hello,

> Anyone suggestions about this?

You need to proxy WebSockets as well. Have a look at our FAQ:

https://webmin.com/faq/#can-i-run-webmin-or-usermin-behind-reverse-proxy

**Comment by Zjoz** [comment]
Thanks for answering.
I followed the FAQ-item you refered to closely and have the next lines (a.o.) in mij VirtualHost configuration:

`    RewriteCond %{HTTP:Upgrade} websocket [NC]`
`    RewriteCond %{HTTP:Connection} upgrade [NC]`
`    RewriteRule ^/?(.*) "wss://localhost:10000/$1" [P,L]`

**Comment by Zjoz** [comment]
Did not have the reverse directive, since it was not in the FAQ guidelines. Added it, but did not make any difference.
The complete relevant section in the VirtualHost configuration is now:

```
    # Enable the usage of the SSL/TLS protocol engines
    SSLEngine on
    SSLProxyEngine on
    #
    ProxyPass /.well-known !
    # Proxying both HTTP and websockets at the same time, where the websockets URL's are not websocket-only
    # or not known in advance
    ProxyPass        / https://localhost:10000/
    ProxyPassReverse / https://localhost:10000/
    RewriteEngine on
    RewriteCond %{HTTP:Upgrade} websocket [NC]
    RewriteCond %{HTTP:Connection} upgrade [NC]
    RewriteRule ^/?(.*) "wss://localhost:10000/$1" [P,L]
 ```

Any other suggestions?

**Comment by iliajie** [comment]
> Any other suggestions?

Ensure that the Apache modules a for WebSocket proxying are enabled, in particular you'd need at least `mod_proxy` and  `mod_proxy_wstunnel`.

**Comment by iliajie** [comment]
Alright, what logs say in `/tmp/.webmin` and `/var/webmin`? Also, what error message is shown in browser's console?

**Comment by Zjoz** [comment]
There are two files /temp/.webmin with the same timestamp:

ws-555.out:
```
Running shell '/bin/bash -bash' with pid 403287
listening on port 555
timeout waiting for connection at /usr/share/webmin/xterm/shellserver.pl line 103.
```
ws-556.out:
```
Running shell '/bin/bash -bash' with pid 403630
listening on port 556
timeout waiting for connection at /usr/share/webmin/xterm/shellserver.pl line 103.
```

Only one line with the timestamp of the faling terminal in /var/webmin/miniserv.log:
```
<public domain ip> - <myusername> [21/Feb/2024:18:02:34 +0100] "POST /xterm/ HTTP/1.1" 200 4119 
```
No lines with the relevant timestamp in /var/webmin/webmin.log.

The browser console gives the next error:
```
Firefox can’t establish a connection to the server at wss://<mydomainname>/webmin/xterm/ws-555.
```

All this does not look very promising to me.

**Comment by iliajie** [comment]
> The browser console gives the next error:
> 
> ```
> Firefox can’t establish a connection to the server at wss://<mydomainname>/webmin/xterm/ws-555.
> ```

Have you checked Terminal module config, in particular **Hostname for WebSocket connections** option?

**Comment by Zjoz** [comment]
Config for terminal seems to be ok.
Hostname for WebSocket connections is set to Manual <mydomainname>/webmin. 
Tried Automatic, but that led to the same behaviour (showing terminal window briefly, followed by the error screen).

**Comment by iliajie** [comment]
> Hostname for WebSocket connections is set to Manual /webmin.

I wonder why the hostname was set to `/webmin`, when it had to be a valid hostname or IP address.

To be honest, this is a wrong place to ask for help. This is a bug tracker. I think it would be better for you to address this question in our [Virtualmin Forum](https://forum.virtualmin.com). There are plenty of folks willing to help! But you would need to provide detailed information about your proxy configuration, network and OS.

**Comment by Zjoz** [comment]
As a matter of fact the hostname was set correctly, but I forgot to mark the relevant text as code, so the brackets caused `<mydomainname>` to vanish in the final text, leaving only `/webmin`. I corrected it in my earlier comment.
Thanks for your effort anyway and I will reopen the issue in the forum you pointed to.
