### ISSUE TITLE
Request for Enhancement (Failed Services Warning(s))

### ISSUE THREAD

**Issue by SlowFox72** [webmin/webmin#2097]
What I miss in Webmin, but Cockpit has is in the main Dashboard screen something to warn you about failes services:

Cockpit Screendump with a Failed service:
![image](https://github.com/webmin/webmin/assets/122017906/9b5accfd-c4dc-43ef-9603-dbeec5f4bf5c)

Is there a possibility to ad a feature comparable like this to Webnin Dashboard?

Kind Regards

Z

**Comment by iliajie** [comment]
Hello,

I think we already have such functionality but it has to be enabled in **Tools ⇾ System and Server Status ⇾ Configuration** page with **Show monitors on Dashboard?** option.

**Comment by shoulders** [comment]
@iliajie I this this should be closed 😄 

![image](https://github.com/webmin/webmin/assets/319997/59c874db-b22a-4880-80d0-bf2093bbb768)

**Comment by iliajie** [comment]
Thanks for the heads up!
