### ISSUE TITLE
https://webmin.com/download/ & http://autodiscover.webmin.com/deb.html are down. Apt repository is not working either.

### ISSUE THREAD

**Issue by Danrancan** [webmin/webmin#2099]
The sites [https://webmin.com/download/](https://webmin.com/download/) 
& 
[http://autodiscover.webmin.com/deb.html](http://autodiscover.webmin.com/deb.html) 
are down. 

The apt repository is not working either:

```
sudo apt update && sudo apt full-upgrade
E: The repository 'https://download.webmin.com/download/repository sarge Release' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

Please fix and let us know when things get back up and working! Thanks!

**Comment by iliajie** [comment]
Hello,

Thanks for the heads up! I don't see this issue happening at the moment. Are you still unable to access the `webmin.com/download` page - it works for me.

Nevertheless, Jamie, what is this `autodiscover.webmin.com` page - it still seems to be available and not getting redirected to the new website. Could you fix that?

**Comment by iliajie** [comment]
It's still available in search engines because the link is active, for example:

<img width="868" alt="image" src="https://github.com/webmin/webmin/assets/4426533/e1168047-d70b-4400-aa4d-abab33bff387">

**Comment by jcameron** [comment]
I think I'll just delete that DNS entry!

**Comment by Danrancan** [comment]
Its working now on my end. Thanks.

**Comment by iliajie** [comment]
> I think I'll just delete that DNS entry!

I think we should just redirect everything to webmin.com.
