### ISSUE TITLE
Text Login & Root Shell

### ISSUE THREAD

**Issue by qooob** [webmin/webmin#210]
After Chrome 43 was pushed from beta to stable `Text Login & Root Shell` stopped working.

Errors are thrown in any theme. Firefox works alright.

Console output:

```JavaScript
Uncaught TypeError: Illegal invocation                               sarissa.js:260
Uncaught TypeError: Sarissa.clearChildNodes is not a function        sarissa_dhtml.js:99 
```

**Comment by jcameron** [comment]
Thanks for pointing this out - I have committed a fix that will go into the next Cloudmin and Webmin releases.
