### ISSUE TITLE
ERROR — PERL EXECUTION FAILED

### ISSUE THREAD

**Issue by MinerAle00** [webmin/webmin#2101]
Hi, I'm encountering an issue with the latest version of Webmin on Ubuntu 20.04.
When I log in to the GUI, I encounter this error and the PC completely freezes.

```
ERROR — PERL EXECUTION FAILED
Missing right curly or square bracket at /usr/share/webmin/authentic-theme/session_login.cgi line 195, at end of line
syntax error at /usr/share/webmin/authentic-theme/session_login.cgi line 195, at EOF
```
![image](https://github.com/webmin/webmin/assets/66887063/651af16a-7b95-4077-964d-d27f22a9503f)

**Comment by iliajie** [comment]
Hello,

> I'm encountering an issue with the latest version of Webmin.

What is exactly the latest version of Webmin that you're referring to?

What you could try to do is to manually restart Webmin by running:

```
systemctl restart webmin
```

If that doesn't help try running the following command to reinstall Webmin:

```
apt-get install --reinstall webmin
```

**Comment by MinerAle00** [comment]
I restarted the server and now the login is working correctly, but I don't understand why it was giving that error before. Can you tell me the path to the logs so I can attach them? The version I'm using is 2.105.

**Comment by MinerAle00** [comment]
Okay, I found them. Which log do you need?

**Comment by iliajie** [comment]
`miniserv.error` log could have something useful.

**Comment by MinerAle00** [comment]
I found the log, and upon looking inside, there's an error. This is the file.
[miniserv.zip](https://github.com/webmin/webmin/files/14498510/miniserv.zip)

**Comment by iliajie** [comment]
Thanks, though there is nothing interesting in attached log file.

As the issue was solved by restarting Webmin I wouldn't worry about. I will close this issue.
