### ISSUE TITLE
Unhide Reboot Now

### ISSUE THREAD

**Issue by SlowFox72** [webmin/webmin#2102]
Maybe I'm overlooking something, but I do not get the message Reboot Now after kernelupdates.
I while ago I have hid the Reboot Now Alert, but I would like it back if possible.

Thanks in advance....

**Comment by jcameron** [comment]
There is still a message on the dashboard if you need to reboot after a kernel upgrade, assuming that Webmin can detect it.

Which Linux distribution are you running there?

**Comment by SlowFox72** [comment]
At the moment I'm running : Ubuntu Linux 22.04.4 LTS
and I notices when there was a Kernel Update from Linux 5.15.0-97-generic to Linux 5.15.0-100-generic  that I didn't get the "Reboot Now" option.

Thank in advance

**Comment by jcameron** [comment]
Does the file `/var/run/reboot-required` exist on your system?

Also, does `/var/webmin/modules/webmin/postpone-reboot-required` exist?

**Comment by SlowFox72** [comment]
Hi @jcameron 

I have checked in both folders `reboot-required` doesn't exist neither does `postpone-reboot-required' 

I have rebooted the server after the Kernel Update.

**Comment by iliajie** [comment]
The `/var/run/reboot-required` file in Ubuntu is typically created by package post-installation scripts when a package update requires a reboot. I am not sure how we can help that.

Though, what is the output on your Ubuntu system of the following command:

```
needrestart
```

... and right afterwards, without running anything else, what is output of this command:

```
echo $?
```

**Comment by SlowFox72** [comment]
Here are the results:

![image](https://github.com/webmin/webmin/assets/122017906/9a53a375-f253-4c3f-8398-20dca1691f01)

**Comment by iliajie** [comment]
The command should have been `$?`. Try running it again - important to run one command right after another:

```
needrestart
echo $?
```

**Comment by SlowFox72** [comment]
Sorry for the typo
![image](https://github.com/webmin/webmin/assets/122017906/397ceeea-b073-474a-b87f-e04358879a62)

**Comment by jcameron** [comment]
Looks like it Ubuntu doesn't think a restart is needed?

**Comment by iliajie** [comment]
My Ubuntu 22.04 creates `/var/run/reboot-required` file which we check. But we also could utilize `needrestart`, however I don't see it return correct exit code, i.e. even though a restart is needed it still returns `0`. Still testing though ..

**Comment by SlowFox72** [comment]
Just to add : 

After the Kernel Updates I have rebooted the machine. Maybe that is the reason why it doesn't give the correct exit code?

**Comment by SlowFox72** [comment]
```shell
zoran@unifisrv:~$ sudo apt-get install update-notifier-common
[sudo] password for zoran:
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
update-notifier-common is already the newest version (3.192.54.6).
update-notifier-common set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
zoran@unifisrv:~$ sudo touch /var/run/reboot-required
 ```
![image](https://github.com/webmin/webmin/assets/122017906/34b4e9f8-4d79-42ae-9368-73f9af2f7ce5)

I got the "Reboot Now" Alert


But why didn't it Alert me when the new Kernel updates where installed...

**Comment by iliajie** [comment]
We will also check for `needrestart` command output with [this PR](https://github.com/webmin/webmin/pull/2103).



> But why didn't it Alert me when the new Kernel updates where installed.

It may take some time for it to appear/disappear from the dashboard as this data is cached.

**Comment by SlowFox72** [comment]
Even now:

![image](https://github.com/webmin/webmin/assets/122017906/aa3c94c7-ac92-4bd0-a1ca-f571a6a7664d)

**Comment by iliajie** [comment]
This is the command you should run to test it correctly:

```
needrestart -b -k -n
```

**Comment by jcameron** [comment]
Are you sure we want the `-k` flag? That limits the checks to only kernel updates..

**Comment by iliajie** [comment]
I'm not entirely sure, but I can test the `-k` flag. The command output seems ambiguous to me because I would expect `needrestart` to simply return `1` or `0`, but it also provides additional information.

Maybe the lead developer @liske of `needrestart` could clarify things and/or consider adding a new flag that would explicitly make the command return `1` or `0` in case restart is needed. This is what command should do in its essence, I think!

**Comment by SlowFox72** [comment]
FYI:

![image](https://github.com/webmin/webmin/assets/122017906/5c241a3c-9254-4124-9335-92a500bb2b88)

**Comment by iliajie** [comment]
Well, the choice to check if `NEEDRESTART-KSTA` equals 3 seems to be the right choice..

**Comment by jcameron** [comment]
What do the numbers mean though? The man page for `needrestart` isn't very clear : https://manpages.ubuntu.com/manpages/jammy/man1/needrestart.1.html

**Comment by SlowFox72** [comment]
Maybe I'm looking at it from a Non-Developer view but if I do a: ` sudo touch /var/run/reboot-required` and I refresh Webmin I do get the "Reboot Now" alert. After a `sudo rm /var/run/reboot-required` and again a refresh of Webmin, the "Reboot Now" Alert disappears.

**Comment by iliajie** [comment]
> What do the numbers mean though? The man page for `needrestart` isn't very clear

Based on the [docs](https://github.com/liske/needrestart/blob/master/README.batch.md) I found:

The kernel status (NEEDRESTART-KSTA) value has the following meaning:

- 0: unknown or failed to detect
- 1: no pending upgrade
- 2: ABI compatible upgrade pending
- 3: version upgrade pending

**Comment by jcameron** [comment]
Ah ok, so in that case 3 makes sense.

What if there's been an upgrade to some core library like glibc that requires all processes be restarted to apply it?

**Comment by iliajie** [comment]
Well, theoretically, we could compare against `2`. However, I'd prefer not to do it, as it might lead to false-positive results.

**Comment by jcameron** [comment]
Actually, let's not worry about that case. I did some testing, and found that the `needrestart` command recommends restarting every single daemon individually. So best to only check for new kernels...

**Comment by iliajie** [comment]
Yeah, agreed!
