### ISSUE TITLE
Nginx and WordPress custom permalink not working

### ISSUE THREAD

**Issue by aryanrajseo** [webmin/webmin#2105]
Hi, WordPress is the most popular cms and we are having issue setting up custom permalink with nginx webserver. As mentioned here https://forum.virtualmin.com/t/nginx-and-wordpress-custom-permalink-not-working/125450

With Ubuntu 22.04, we have separate domainname.conf file available in /etc/nginx/sites-available/

however with AlmaLinux 9, we hae a single nginx.conf file.

Adding the following code in .conf file works but will get wiped out with any upgrade.

`location / { 
        index index.php index.html index.htm; 
        try_files $uri $uri/ /index.php$is_args$args;
    }`

This code need to be added for each domain in Ubuntu server however for almalinux, it will required one time for domains but for Installations made on SUBFOLDER, it single .conf file will make it more difficult to manage.

Wonder if you could offer a fix as the issue is very genuine. A global variable fix to detect the WordPress install and addd the rule or fix the permalink issue.

**Comment by chris001** [comment]
To protect from nginx upgrades wiping out `nginx.conf` and all your website configs in it, you should answer `No` when it asks you if you want to upgrade the `nginx.conf` file with the default file from the new version.

You can also protect your website `.conf` by including them, like in ubuntu:
```
http {
    …
    include /etc/nginx/conf.d/*.conf;
    include /etc/nginx/sites-enabled/*;
}
```
More:
https://serverfault.com/questions/527630/difference-in-sites-available-vs-sites-enabled-vs-conf-d-directories-nginx

**Comment by aryanrajseo** [comment]
hi @chris001 appreciate the help. could you also confirm the same for Almalinux 9 and why it not have nginx webserver backup module?

**Comment by jcameron** [comment]
@iliajie weren't you looking into a fix for this recently?

**Comment by aryanrajseo** [comment]
I would also appreciate that if it not required to add any additional code in .conf file in new upgrade as we install WordPress on different folders. for staging and demo sites. A global variable rule which detect the WordPress custom permalink changes in nginx webserver would bring more users to switch from expensive control panels. I know it could take more time but trust me, it will be worth because webmin/virtualmin is very powerful but have some issues with nginx webserver/lemp stack.

**Comment by iliajie** [comment]
> @iliajie weren't you looking into a fix for this recently?

Yes, we fixed that on Virtualmin WordPress installer script.

**Comment by aryanrajseo** [comment]
> Yes, we fixed that on Virtualmin WordPress installer script.

Hi, i  installed LEMP stack with Ubuntu 22.04 and Almalinux 9 yesterday and the WordPress custom permalink was not working. is the fix released?

**Comment by iliajie** [comment]
When you install Virtualmin, you might not immediately receive the latest updates for install scripts; this can typically take up to 24 hours. I suggest that if you create a new test domain and attempt to install WordPress again, it should work properly.

**Comment by aryanrajseo** [comment]
hi @iliajie thank you, i see the install script now have username and password (autofilled) and it is working with subfolder too. have you got any reference from my recent forum post or the fix was already in the progress?

**Comment by iliajie** [comment]
The Nginx fix was incorporated a few months ago.

**Comment by aryanrajseo** [comment]
awesome. thank you for working on this in such a short time. I really appreciate it. I wish more hosting provider switch to webmin/virtualmin. i am very happy that i given this a try, it was boring at first but i am in love with it. there are few things that need some improvements but it is almost pretty perfect lightweight control panel.

thanks again.

**Comment by iliajie** [comment]
You're welcome! If you see anything that could be improved, just open a new GitHub ticket, and we'll have a closer look at it.
