### ISSUE TITLE
Backup Configuration Files have no nginx webserver option

### ISSUE THREAD

**Issue by aryanrajseo** [webmin/webmin#2106]
As mentioned here https://forum.virtualmin.com/t/backup-configuration-files-have-no-nginx-webserver-option/125482

the LEMP server have no nginx webserver backup module available. It shows apache webserver to backup but the vps is on LEMP nginx webserver.

Thanks.

![image](https://github.com/webmin/webmin/assets/34836534/44a303c7-2189-4766-bcd8-8e8d6b6cc4b4)

**Comment by iliajie** [comment]
Hello,

Thank you for bringing this to our attention. Indeed, the Virtualmin Nginx module doesn't have yet a `backup_config.pl` for performing configuration backups.

Jamie, is this due to a particular reason, or has it simply been overlooked?

**Comment by jcameron** [comment]
No, I'll look into adding this ...

**Comment by jcameron** [comment]
Ok I've implemented this for the next release of the Nginx plugin ...
