### ISSUE TITLE
add redis server support with phpredis extension

### ISSUE THREAD

**Issue by aryanrajseo** [webmin/webmin#2107]
Redis in LEMP stack is very much recommended. It is offered by almost all the  modern control panels and server management tools. as per the redis install guide available, only few steps required to setup and get it running. Wonder if we can get it in Plugin List? We can keep it inactive by default for minimal installs.

I have installed the Redis server with phpredis extension using ssh and it worked great with WordPress without any additional changes.

This will offer a high performance LEMP stack for WordPress.

**Comment by iliajie** [comment]
Hello,

Thank you for your suggestion!

Though, we're inclined to stick to the "less is more" philosophy, keeping our setup sleek and user-friendly for all.
