### ISSUE TITLE
/inittab/ - Initial System Bootup

### ISSUE THREAD

**Issue by qooob** [webmin/webmin#211]
Initial System Bootup module, if nothing is added there, __shows__ an empty table with __Select All/Inverse Select__ buttons, that return an error on click (if table is empty). 

Should just display Add Button instead as in all other Modules/cases.

**Comment by jcameron** [comment]
Actually, if there is nothing to show, it probably indicates that the system doesn't even use an /etc/inittab files. Which Linux distribution is this on?

**Comment by qooob** [comment]
Fedora 21

**Comment by qooob** [comment]
Oh, now, CentOS 7

**Comment by jcameron** [comment]
I've checked in a fix to make the module look nicer in this case - however, generally if /etc/inittab only contains commented out lines it indicates that the file isn't even being used. In this case, Webmin should place it under the "un-used modules" category.

**Comment by qooob** [comment]
:+1:
