### ISSUE TITLE
Perl Execution Failed

### ISSUE THREAD

**Issue by analogscott** [webmin/webmin#2114]
I’m not sure what’s gone wrong. I’ve had this error almost since i installed Webmin (a month or 2). It doesn’t affect the primary functions of Webmin, the Stats History just fails to load and i get constant pop ups of this error.

“Error: 500 - Perl execution failed - Can’t use string (” “) as a HASH ref while “strict refs” in use - /stats.cgi?xhr-stats=general”

**Comment by jcameron** [comment]
@iliajie can you take a look at this one?

**Comment by iliajie** [comment]
Yes, I'll be able to respond to all the GitHub tickets tomorrow. The last few days have been taken up with migrating virtualmin.com and fixing the forum.

**Comment by iliajie** [comment]
> I’m not sure what’s gone wrong. I’ve had this error almost since i installed Webmin (a month or 2). It doesn’t affect the primary functions of Webmin, the Stats History just fails to load and i get constant pop ups of this error.

Which OS and version are you running Webmin on?

**Comment by analogscott** [comment]
![webmin](https://github.com/webmin/webmin/assets/165829419/88016207-c68d-4e33-80d7-5c966996ccec)

It's an Ubuntu 22.04.4 virtualbox guest on a Windows 10 host.    Webmin 2.105

I've run this setup many times over the years, not necessarily this new version of Ubuntu or Webmin.   Notice in the screenshot the "Stats History" is hung up.    This popup will happen many times as I navigate around Webmin.    

FYI,   I use Webmin to manage the system across the LAN.    I use this machine as a Samba server.

**Comment by jcameron** [comment]
Are there any more details on this error message logged to `/var/webmin/miniserv.error` ?

**Comment by analogscott** [comment]
[miniserv.txt](https://github.com/webmin/webmin/files/14859959/miniserv.txt)
I attached the miniserv file.    It's kinda long and above my head.   I really apologize if somehow i've cause this.   I've used Webmin for a while and never had an issue like this.

**Comment by jcameron** [comment]
Ok, I see an interesting error in there : 

```
[11/Jan/2024:20:27:47 -0800] [127.0.0.1] /stats.cgi : Perl execution failed : Can't use string ("1705033550") as a SCALAR ref while "strict refs" in use at /usr/share/webmin/vendor_perl/JSON/PP.pm line 541.
```

@iliajie I am guessing this is somewhere inside the theme dashboard code?

**Comment by iliajie** [comment]
@analogscott It would be really helpful to see the error stack. Can you edit `/etc/webmin/config` file, add `error_stack=1`, and then try again and check the logs or UI for more detailed error message?

**Comment by analogscott** [comment]
I added error_stack=1 and it's giving me permissions errors now.  I realize the extended logging isn't causing this issue.    I'm tempted to rebuild this server.   If you think we have a bug, i'll ride this out as long as you like (to help however i can).    If you suspect this issue is on my end, then maybe the rebuild is the easiest solution.    Attached is the miniserv error log for today, after the error_stack was added.   After i added it, I rebooted, then started having permission issues.   
[miniserv 2024-04-04.txt](https://github.com/webmin/webmin/files/14875714/miniserv.2024-04-04.txt)

After glancing through this log, I was reminded that after I setup Webmin, I had 2 servers, both using Webmin and wanted to make then visually different to help remind me which server I was on.   I went to Webmin Themes and switched the Current Theme to the other that was available.   I didn't look for any particular themes, I just want something different.   After I did this, the theme was broken.  I can't remember exactly how, but it was an obviously broken interface.

**Comment by iliajie** [comment]
It seems like there's something really weird going on, especially with the message about failing to open `/etc/webmin/config` for writing due to a read-only file system.

Have you tried rebooting your server?

**Comment by analogscott** [comment]
Many times.    I rebooted after adding error_stack.    Like I said i'm thinking to rebuild the system.    Its a virtualbox guest that I could take down and rebuild in a few hours.    If you don't think this is a bug, i'll rebuild it.  It's not really solving the issue but it will get me to fixed in a shorter time.   Like you, i think this is all very odd.   I've used Ubuntu/Samba/Webmin for at least 10 years and never had such difficulty.

**Comment by iliajie** [comment]
If you emailed me your server credentials I would login tomorrow and have a closer look. I'm not sure what could be causing this issue without knowing additional details.

You can deduct my email address by looking into my GitHub profile.

**Comment by analogscott** [comment]
That sounds great but the server is internal and not exposed to the web. I hit it from a LAN machine.

**Comment by iliajie** [comment]
Alright, after taking a closer look I see what's causing this bug! It will be fixed in the next Authentic Theme release.

Meanwhile, you can work-around this issue by deleting `/var/webmin/modules/authentic-theme/stats-root.json` file.
