### ISSUE TITLE
请问支持单/多个服务器之间的面板同步吗？

### ISSUE THREAD

**Issue by shun556618** [webmin/webmin#2116]
例如：
A服务器下有1和2这两个网站，更新1站点内容后面板自动同步内容到2站点。

又例如：
在A服务器的站点更新了内容后面板自动同步到B、C、D等服务器站点中。

**Comment by jcameron** [comment]
English translation : 

> Does it support panel synchronization between single/multiple servers?
> 
> For example:
> There are two websites, 1 and 2, under server A. After updating the content of site 1, the panel automatically synchronizes the content to site 2.
> 
> Another example:
> After the content is updated on the site of server A, the panel is automatically synchronized to server sites such as B, C, and D.

No, Webmin doesn't support this. However, Virtualmin does for sites that have only static HTML or PHP content (no databases).

**Comment by shun556618** [comment]
> English translation :
> 
> > Does it support panel synchronization between single/multiple servers?
> > For example:
> > There are two websites, 1 and 2, under server A. After updating the content of site 1, the panel automatically synchronizes the content to site 2.
> > Another example:
> > After the content is updated on the site of server A, the panel is automatically synchronized to server sites such as B, C, and D.
> 
> No, Webmin doesn't support this. However, Virtualmin does for sites that have only static HTML or PHP content (no databases).

好的  谢谢。
