### ISSUE TITLE
system-status::list_system_info failed : Month '-1' out of range 0..11 at /usr/libexec/webmin/webmin/os-eol-lib.pl line 108.

### ISSUE THREAD

**Issue by FBachofner** [webmin/webmin#2121]
I got bit by the issue referenced in the title on one of my servers today after upgrade to Webmin 2.110

It seems analogous to the [closed issue 1119](https://github.com/webmin/webmin/issues/1119) except for me it is "month" rather than "hour"

Any insight on a fix would be appreciated.

Edit: Additional details ->

Webmin dashboard reports

> Can't locate MD5.pm in @INC (you may need to install the MD5 module) (@INC entries checked: /usr/libexec/webmin/vendor_perl /usr/libexec/webmin /usr/local/lib64/perl5/5.38 /usr/local/share/perl5/5.38 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 /usr/libexec/webmin/ . ..) at (eval 568) line 1. BEGIN failed--compilation aborted at (eval 568) line 1. : web-lib-funcs.pl (line 4223)

I attempted to add this module by issuing:
`sudo cpan`
then
`install Digest::MD5`

This seems to have installed the correct perl module, but logging out of and back into Webmin yields the same error in the dashboard.

**Comment by jcameron** [comment]
@iliajie PTAL at this ASAP, as it appears to come from your new EOL code..

**Comment by iliajie** [comment]
@FBachofner What OS you're seeing it on?

**Comment by FBachofner** [comment]
@iliajie this is on Fedora Linux 40 (Server Edition) _which is in final beta_ (which I installed just yesterday)

I am happy to test any fixes for you as this seems very close to release (possibly without further changes)

**Comment by iliajie** [comment]
I see what's causing this issue. The patch is here https://github.com/webmin/webmin/commit/657113d0c8c2f009c35506da608fc7083648be3d.

**Comment by jcameron** [comment]
@iliajie do we need a new release to fix this bug?

**Comment by iliajie** [comment]
It appears so, yes.

**Comment by jcameron** [comment]
Is the impact limited to super-new distros that don't appear on the supported list yet?

**Comment by iliajie** [comment]
Any new distro which isn't found in Webmin EOL database. I think it's better fix it now.

Ubuntu 24.04 is on the way..

**Comment by iliajie** [comment]
> I look forward to the new release. "Sorry" I found a bug so early in your release, but at least not too many people will be affected this way.

We greatly appreciate it! Thank you for your time and your kind words too!

Webmin 2.111 should have already been released and become available today.

**Comment by FBachofner** [comment]
Hi @iliajie  and @jcameron 

> Webmin 2.111 should have already been released and become available today.

Indeed, I came into the workshop a few moments ago and 2.111 is already installed on the F40 server.  The problem on the Webmin Dashboard is fixed and Webmin seems to work without incident.

**Thank you both for your excellent, ongoing work on this project!**

**Comment by UsamaFoad** [comment]
> Any new distro which isn't found in Webmin EOL database. I think it's better fix it now.
> 
> Ubuntu 24.04 is on the way..

Ubuntu 24.04 was released, and Webmin shows the EOL in two months.
![Screenshot from 2024-04-26 22-30-12](https://github.com/webmin/webmin/assets/8681507/d3573c19-bc33-4a48-8c6b-43cbe74f9a9b)
![Screenshot from 2024-04-26 22-23-54](https://github.com/webmin/webmin/assets/8681507/1b8ea379-35be-430e-979a-004d7b2b34c5)

**Comment by jcameron** [comment]
@iliajie can you take a look at this EOL issue?

**Comment by iliajie** [comment]
> Ubuntu 24.04 was released, and Webmin shows the EOL in two months.

Perhaps it's time to upgrade? 🙂

**Comment by iliajie** [comment]
> @iliajie can you take a look at this EOL issue?

Jamie, this issue is the result of installing Webmin 2.110 in the first place.

@UsamaFoad You should manually edit `/etc/webmin/config` file and remove all `os_eol` keys.

**Comment by UsamaFoad** [comment]
Thank you @iliajie. I edited the config file, and the EOL disappeared from Webmin.

**Comment by jcameron** [comment]
@iliajie but why does Webmin 2.111 think that Ubuntu 24 is deprecated?

**Comment by iliajie** [comment]
Webmin 2.111 doesn't, but Webmin 2.110 did, while adding incorrect records to the Webmin config. This issue could also have been fixed by a simple system information refresh directly from the dashboard or in status collection.

**Comment by jcameron** [comment]
Oh so the possible solution would be just to wait? Excellent !

**Comment by mmjc23** [comment]
Hello everyone,
I’ve just encountered the same error on an Oracle Linux 10 system with Webmin version 2.520.
Is there any way I can fix it?
Thanks.

**Comment by iliaross** [comment]
Does it help if you refresh the system information on the dashboard page using the refresh button at the top right?

**Comment by mmjc23** [comment]
> Does it help if you refresh the system information on the dashboard page using the refresh button at the top right?

Hi iliaross,
...and thanks for your reply.
The Dashboard doesn’t load at all, so I can’t click the refresh button.
(see attached image)
Thank you in advance
Best regards

<img width="1913" height="464" alt="Image" src="https://github.com/user-attachments/assets/be7815b5-7151-4c32-ade0-dd7a8fbb7279" />

**Comment by iliaross** [comment]
Do you have the same issue when using the latest development build of Webmin?

https://download.webmin.dev/webmin-latest.rpm

**Comment by mmjc23** [comment]
Hi iliaross,
Yes, I'm having the same issue with the package you sent me.
I copied the package to the Oracle Linux server and ran the following commands:
`sudo dnf upgrade webmin-latest.rpm`
`sudo systemctl restart webmin`
Then I forced a refresh of the web page using Ctrl+F5.

Thank you

**Comment by iliaross** [comment]
Oh, I see why—Oracle 10 is still in development. Apply the following patch and enjoy the ride:

```
webmin patch https://github.com/webmin/webmin/commit/178c619
```

**Comment by mmjc23** [comment]
**EDIT:**
I apologize, iliaross, I hadn't noticed that version 10 was still in development.
I downloaded it from the [Oracle website](https://yum.oracle.com/oracle-linux-isos.html), and it is not indicated that it is in development.

I replaced the file `/usr/libexec/webmin/webmin/os-eol-lib.pl` with the new one you modified, and now the Dashboard works correctly.
Thank you very much!

**Comment by iliaross** [comment]
You're welcome! Thanks for reporting it!
