### ISSUE TITLE
Webmin  Command Shell

### ISSUE THREAD

**Issue by BorisPerc** [webmin/webmin#2124]
ver, 2.111

Deb linux 12

stop to work Command shell

**Comment by iliajie** [comment]
Hello,

Thanks for the heads up!

It seems like an odd regression in Authentic. I will have to take a closer look. I will update this ticket with progress.

**Comment by iliajie** [comment]
This issue will be fixed in the next theme release.

**Comment by BorisPerc** [comment]
Grazie, thank you.
