### ISSUE TITLE
Usermin Configuration->Usermin Module Configuration->SpamAssassin Mail Filter

### ISSUE THREAD

**Issue by qooob** [webmin/webmin#213]
For some reason, which can be deductively found out, `Usermin Configuration->Usermin Module Configuration->SpamAssassin Mail Filter` is not letting switch tabs in Authentic Theme, while other links' tabs from `Usermin Configuration->Usermin Module Configuration` are fine and are opening! Not sure what it is. May by it's hardcoded in this particular one? Please take a closer look..

> Epic, Authentic Theme v13, is about to be born...

**Comment by qooob** [comment]
For instance, `Usermin Configuration->Usermin Module Configuration->SSH Login` - works fine..

**Comment by jcameron** [comment]
By "switch tabs", do you mean navigating between different sections of the configuration page?

**Comment by qooob** [comment]
No, I mean, when you goto `Usermin Configuration->Usermin Module Configuration->SpamAssassin Mail Filter` and try to switch tabs, nothing happens.

**Comment by jcameron** [comment]
Hmmm ... that is odd. And it works fine in the default theme, and I don't see any errors in the browser. 

As the theme author, you'd probably be better at debugging this, as I assume you completely overrode the function that generates tabs?

**Comment by qooob** [comment]
But it also doesn't work in Virtualmin Framed Theme

**Comment by jcameron** [comment]
It works OK for me in the framed theme.

**Comment by qooob** [comment]
...now it really works in default themes.. :) Hmm... Sorry then, Jamie! I will take a closer look! 

Could you please double check that `SpamAssassin Mail Filter` really is using `theme_ui_tabs_` and it's not hardcoded when tabs are generated? SpamAssassin is the only one where tabs don't work..

**Comment by jcameron** [comment]
Yes, the same code generates that page for all usermin modules.

**Comment by qooob** [comment]
Very strange.. I will do extensive debugging! Sorry.

**Comment by qooob** [comment]
It was happening because the page had an element with the same id as `tab-content` itself. Thanks to this bug, I managed to make all tabs fail-safe.. fixed..
