### ISSUE TITLE
Webmin's systemd service re-enables after every update

### ISSUE THREAD

**Issue by SamSirry** [webmin/webmin#2133]
Hello

I have noticed that after every update, the systemd service for Webmin gets re-enabled to start on boot. This happens even though I manually disable it each time.

## Steps to Reproduce
1. Disable the Webmin service using `systemctl disable webmin`
2. Check the service status using `systemctl status webmin`. The output shows: `Loaded: loaded (/lib/systemd/system/webmin.service; disabled; vendor preset: enabled)`
3. Wait for a new release, and run `apt upgrade`. (I didn't test with automatic upgrades (p.s. security updates are configured to get installed automatically)).
4. Check the service status again using `systemctl status webmin`

## Expected Behavior
After running `apt upgrade`, the service status should remain as disabled: `Loaded: loaded (/lib/systemd/system/webmin.service; disabled; vendor preset: enabled)`

## Actual Behavior
After running `apt upgrade`, the service status shows as enabled: `Loaded: loaded (/lib/systemd/system/webmin.service; enabled; vendor preset: enabled)`

## Additional Information
I prefer to keep the Webmin service disabled and only start it as needed. It's worth noting that the background services like SMART monitoring and automatic package updates still work even when the Webmin service is not running. (good thing)

## Environment
- Webmin version: Current (2.111)
- Operating System: Debian 11
- Systemd version: Current (systemd 247 (247.3-7+1-pmx11u1))

I furnish this issue to be evaluated by the dev team. Thank you.

**Comment by iliajie** [comment]
Hello,

I see the reason why this issue is happening. We overwrite `webmin.service` file after each package upgrade.

Additionally, we need to check:

```
systemctl is-enabled $product.service
```

.. and then as well restore the state in `updateboot.pl` script.

Jamie, what are your thoughts on it? It isn't that hard to do.

**Comment by chris001** [comment]
My 2 cents, what about the default behavior be = as it is currently, to force enable the service after update.
Any user could run command line with flag, to override default, to leave service untouched after update.

**Comment by swelljoe** [comment]
No, the default behavior should be the default behavior of OS packages. And, we _cannot_ require command flags for packages. We don't invent new behaviors for standard OS tools. That's toxic behavior. We should do what the OS packaging guidelines say.

The default behavior in Debian (and Ubuntu and the RPM-based distros, too) is to respect the enabled/disabled state if the package is already installed; if the user disabled it, we should not re-enable it during upgrades. `debhelper` sets up maintainer scripts for that if you have the `--with systemd` flag in `rules` and if you have `#DEBHELPER# in all of the maintainer scripts in the package, so the packager doesn't have to make them manually, but I guess we're not using `debhelper` for our package builds.

But, the right thing is to have a `prerm` that stops the service, a ` postinst` that starts/enables the service when appropriate (on first install it enables+starts, on subsequent installs it does what the enabled state would indicate, a `postrm` that disables/purges/masks the service as appropriate for whether the package is being removed or purged.

**Comment by iliajie** [comment]
This issue will be fixed in the next Webmin and Usermin releases.
