### ISSUE TITLE
Time server sync - additional  information

### ISSUE THREAD

**Issue by shoulders** [webmin/webmin#2134]
|  SYSTEM INFORMATION||
|----------------------|---------------------------|
|  OS type and version |     Ubuntu Linux 22.04.4     |
|  Webmin version      |     2.105      |
|  Usermin version     |     2.005     |
|  Virtualmin version  |     7.9.0       |
|  Theme version       |     21.09.5      |
|  Package updates     |      9  package updates are available   |

### The issue

Webmin --> Hardware --> System Time --> Time server sync

While trying to set my schedule for checking updates I discovered that I could not deselect items and once an item in a column was selected it would always have one.

![image](https://github.com/webmin/webmin/assets/319997/a3d18325-095c-4573-808c-09670dd6180e)

### solution

Using the control key was the key.

Can a small note be put into the tooltip? maybe as follows

> To de-select or multi-select, use the `Ctrl` button while clicking.

I appreciate this might be a user error but I think this is the only place with multi select columns in Webmin.

**Comment by iliajie** [comment]
Thanks for the heads up! We will fix it in the next Webmin release.
