### ISSUE TITLE
problem handlyng old versions of certbot 1.11

### ISSUE THREAD

**Issue by Netmees** [webmin/webmin#2135]
you have a problem handlyng old versions of certbot with --no-renew-keys no handled by old versions of certbot (1.11) on webmin i have to comment on 
webmin/letsencrypt-lib.pl
#else {
#$reuse_flags = " --no-reuse-key";
#}
for certbot to work…

**Comment by iliajie** [comment]
Hello,

Thanks for the heads up!

What OS is this?

**Comment by Netmees** [comment]
it`s redhat fork, still not solved in new releases... i had to change once again after upgrade... its important to remove this old call to  --no-reuse-key

**Comment by jcameron** [comment]
@iliajie I think I mentioned this is another ticket? Do we really need to set that flag at all if ` --no-reuse-key` is the default?

**Comment by iliajie** [comment]
> Do we really need to set that flag at all if ` --no-reuse-key` is the default?

Yes, I clearly remember that it was needed. Things went broken without it.

Though, we need to test if it's supported. Here is the patch https://github.com/webmin/webmin/commit/cf838e5d9ad6a173d12992c8de77e90b1c0ad7c9.

**Comment by Netmees** [comment]
--no-reuse-key its not recogniced ( its removed in new versions) and produce an error that stops generating the certificate

**Comment by iliajie** [comment]
> --no-reuse-key its not recogniced ( its removed in new versions) and produce an error that stops generating the certificate

 I'm a bit confused! What's the output of `certbot --version` on your system? Also, what OS are you running?
 
Can you apply the latest patch and see if it solves the problem for you?

```
webmin patch https://github.com/webmin/webmin/commit/cf838e5d
```
