### ISSUE TITLE
Argument "-" isn't numeric in localtime at /usr/share/webmin/time/log_parser.pl line 17

### ISSUE THREAD

**Issue by shoulders** [webmin/webmin#2136]
|  SYSTEM INFORMATION||
|----------------------|---------------------------|
|  OS type and version |     Ubuntu Linux 22.04.4     |
|  Webmin version      |     2.111      |
|  Usermin version     |     2.010     |
|  Virtualmin version  |     7.10.0       |
|  Theme version       |     21.10      |
|  Package updates     |     All installed packages are up to date   |

While investigating another issue I found this error in my webmin error log. I do not know if this is a problem but might be an incorrect passing of a variable? 

Webmin → System → System Logs Viewer → Webmin error log (/var/webmin/miniserv.error)

```
Argument "-" isn't numeric in localtime at /usr/share/webmin/time/log_parser.pl line 17.
```

it appears many times and seem to roughly match when I manually `applied and synced` my time server settings

```
[26/Apr/2024:12:27:32 +0100] Reloading configuration
[26/Apr/2024:12:27:31 +0100] Reloading configuration
[26/Apr/2024:12:23:07 +0100] Reloading configuration
Argument "-" isn't numeric in localtime at /usr/share/webmin/time/log_parser.pl line 17, <LOG> line 606.
Argument "-" isn't numeric in localtime at /usr/share/webmin/time/log_parser.pl line 17, <LOG> line 374.
Argument "-" isn't numeric in localtime at /usr/share/webmin/time/log_parser.pl line 17, <LOG> line 317.
Argument "-" isn't numeric in localtime at /usr/share/webmin/time/log_parser.pl line 17, <LOG> line 316.
Argument "-" isn't numeric in localtime at /usr/share/webmin/time/log_parser.pl line 17, <LOG> line 234.
Argument "-" isn't numeric in localtime at /usr/share/webmin/time/log_parser.pl line 17.
[26/Apr/2024:12:16:02 +0100] [10.0.0.200] /xterm/ws-555 : Unknown websocket path
[26/Apr/2024:12:16:02 +0100] Reloading configuration
[26/Apr/2024:12:16:01 +0100] Reloading configuration
```

https://github.com/webmin/webmin/blob/8de5c83ca831697a1560e9f7b9c00cf55345e641/time/log_parser.pl#L15-L20

**Comment by iliajie** [comment]
Hello,

It isn't exactly clear how to quickly reproduce this issue. I don't see it on my end.

Can you add above line 17 the following:

```
error_stderr("OBJECT: $object");
```

.. and try syncing time once again to see what `$object` is?

**Comment by shoulders** [comment]
I have added the code.
![image](https://github.com/webmin/webmin/assets/319997/0734a275-c033-47ee-b466-53b2f1f22374)

Stupid question, which log will the output appear? or do I need to run this from the command line (would need a little help here 😄 )

### My settings for reference
![image](https://github.com/webmin/webmin/assets/319997/2b668148-9b21-4f69-b1c7-2a3783dd00e4)

**Comment by iliajie** [comment]
Nevermind, I checked the code and found a bug that was causing it. It was introduced about 8 years ago when `time-lib.pl` was switched to use strict mode.

Try applying this patch https://github.com/webmin/webmin/commit/4db36071b36a3626dfa7c2e9e57bf9dc1fd35a60 and see if it solves your issue. You could also install nightly Webmin version if you feel comfortable doing it.

**Comment by shoulders** [comment]
I have manually made the changes and so far log_parser errors.

I am a little bit off applying GitHub patches directly to my install. 😄 

Thanks for such a quick fix. I wasn't sure if I should close this or if you need to do anything at your end.

**Comment by iliajie** [comment]
> I wasn't sure if I should close this or if you need to do anything at your end.

If it isn't logging that warning anymore then it's fine to close it.
