### ISSUE TITLE
File Manager - change Permissions - Mode input imporvements

### ISSUE THREAD

**Issue by shoulders** [webmin/webmin#2138]
|  SYSTEM INFORMATION||
|----------------------|---------------------------|
|  OS type and version |     Ubuntu Linux 22.04.4     |
|  Webmin version      |     2.111      |
|  Usermin version     |     2.010     |
|  Virtualmin version  |     7.10.0       |
|  Theme version       |     21.10      |
|  Package updates     |     All installed packages are up to date   |

I would like to propose a few improvements to the input of the mode.

File Manager --> Tools --> Change Permissions

![image](https://github.com/webmin/webmin/assets/319997/93e7c45b-4f14-43e7-9063-c89b0e3573bd)

- Make the input wider to show 4 characters
- remove the up and down arrows. I am pretty sure they are never used and just get in the way.
- enforce the requirement of 4 characters

**Comment by iliajie** [comment]
Thanks for the heads up!

Though, it's already the case for me:

<img width="596" alt="image" src="https://github.com/webmin/webmin/assets/4426533/27681bc4-bbe7-401b-a750-6783a96ed2ea">

What browser are you using there?

**Comment by iliajie** [comment]
Alright, I see this issue in Firefox too! Fixed now!

**Comment by shoulders** [comment]
cheers for that, what do you think about the 4 character enforcement?

**Comment by iliajie** [comment]
Alright, sure! Done!
