### ISSUE TITLE
EOL flag still showing on Ubuntu 24.04 after upgrade from Ubuntu 23.10

### ISSUE THREAD

**Issue by tweek11** [webmin/webmin#2139]
EOL flag still showing on Ubuntu 24.04 after upgrade from Ubuntu 23.10

**Comment by tweek11** [comment]
Here's a screen shot of the Dashboard. I like the idea of the EOL flag notification. Just don't know if there is a location i can manually adjust or change. 

![EOL](https://github.com/webmin/webmin/assets/91363983/c787a0c1-e611-46bb-9b4c-dc7b41d5f43c)

**Comment by jcameron** [comment]
Does it help if you click the Refresh icon on the top-right of that page?

**Comment by tweek11** [comment]
> Does it help if you click the Refresh icon on the top-right of that page?

I tried that and it does not change the status flag

**Comment by jcameron** [comment]
@iliajie do you know what's up here?

**Comment by iliajie** [comment]
> @iliajie do you know what's up here?

Yeah, I found a bug that's causing it https://github.com/webmin/webmin/commit/9dcb1da4f517f9baa737eafec65810c7a8d831df.

@tweek11 You need to manually edit `/etc/webmin/config` and remove `os_eol_expiring` key.
