### ISSUE TITLE
 ui_columns_start doesn't honor tags in headings since 2.106

### ISSUE THREAD

**Issue by netcons** [webmin/webmin#2143]
Noticed that one of our modules no longer interpret <option> and <b> tags,
in arrays passed to ui_columns_start &headings, regardless of theme.
The loss of <b> tag is evident in other standard modules as well.

If I add an additional blank element to the beginning or end of the &headings array.
The formatting tags are interpreted correctly.

**Comment by netcons** [comment]
**Apologies, markdown dropped the tag names.**

Noticed that one of our modules no longer interpret `<option>` and `<b>` tags,
in arrays passed to `ui_columns_start &headings`, regardless of theme.
The loss of `<b>` tag is evident in other standard modules as well.

If I add an additional blank element to the beginning or end of the `&headings` array.
The formatting tags are interpreted correctly.

**Comment by iliajie** [comment]
Hello,

> Noticed that one of our modules no longer interpret and tags,
> in arrays passed to ui_columns_start &headings, regardless of theme.

Does it work equally the same in Framed and Authentic themes?



> If I add an additional blank element to the beginning or end of the `&headings` array.
> The formatting tags are interpreted correctly.

Can you show some code? It isn't clear what's going on.

**Comment by netcons** [comment]
Hi Ilia,

Thanks for your response

Worked in Framed and Authentic pre 2.106,
Stopped working post 2.105 in Framed and Authentic.

E.g. https://github.com/netcons/turtlefirewall/blob/master/src/usr/libexec/webmin/turtlefirewall/log.cgi

Seems any formatting tags added to elements in array called head are ignored.
lines 121-122:
 `$hdate .= "<b>DATE<br></b>";`
 `push(@head, $hdate );`
the bold formatting is ignored when called from line 127:
  `print &ui_columns_start(\@head, 100, 0, \@tds);`

If I add a blank element: 
`push(@head, '' );`
to the end or beginning of the head array, the formatting tags are honored.

The other head array elements are more complex, but their tags seem to be ignored for eg. on line 126:
`<option>` and `<select>`

**Comment by netcons** [comment]
Another workaround to get ui_columns_start to honor tags in the heading is to a add an undefined row just before ui_colums_end.

print &ui_columns_row( undef );
print &ui_columns_end();

**Comment by iliajie** [comment]
Not sure; I don't remember us making any changes to neither `ui_columns_row` nor `ui_columns_end` subs.

**Comment by netcons** [comment]
Restored authentic-theme folder from 2.105 and it works correctly in Authentic Theme.
Strangely though, if I restore blue-theme folder from 2.105 it only displays correctly for an instant and then reverts to dropping the tags in Framed Theme.

**Comment by iliajie** [comment]
Can you provide a partial code snippet that worked before but not anymore? I'd like to locally try to reproduce this issue without directly checking the linked module.

**Comment by netcons** [comment]
You can simulate with https://github.com/webmin/webmin/blob/master/mount/index.cgi
Change Line 61 from: 
 `print &ui_columns_start([ $text{'index_dir'},`
to
 `print &ui_columns_start([ "<b>$text{'index_dir'}</b>",`

The Bold tags will be ignored.

As a workground, you can insert the following above line118 :
 `print &ui_columns_row( undef ); `

**Comment by iliajie** [comment]
Thanks for reporting it! It will be fixed in the next release.

**Comment by netcons** [comment]
Thank you.
