### ISSUE TITLE
Cannot edit yaml files on fresh install of Ubuntu 24.04

### ISSUE THREAD

**Issue by myopenflixr** [webmin/webmin#2147]
Hello,

I just did a fresh install of Ubuntu 24.04 on a VM along with an install of Webmin using the repository.

File manager does not give an option to edit .yml or .yaml files. All other file types have the edit file option.

Any Suggestions?

Thanks,
Mike

**Comment by iliajie** [comment]
> File manager does not give an option to edit .yml or .yaml files. All other file types have the edit file option.

```
apt-get install shared-mime-info
```

**Comment by myopenflixr** [comment]
> apt-get install shared-mime-info

```
shared-mime-info is already the newest version (2.4-4).
shared-mime-info set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

**Comment by myopenflixr** [comment]
The patch worked perfectly.

Thank you @iliajie

**Comment by xbypaxl** [comment]
> Ah, I see what's causing this issue. YAML is no longer an experimental MIME type. The latest patch fixes this issue.

Hi, sry but what patch do i need to install? Webmin or Ubuntu or which Patch?

**Comment by iliajie** [comment]
> > Ah, I see what's causing this issue. YAML is no longer an experimental MIME type. The latest patch fixes this issue.
> 
> Hi, sry but what patch do i need to install? Webmin or Ubuntu or which Patch?

It's better to wait until next Webmin release which will include this patch.

**Comment by xbypaxl** [comment]
> > > Ah, I see what's causing this issue. YAML is no longer an experimental MIME type. The latest patch fixes this issue.
> > 
> > 
> > Hi, sry but what patch do i need to install? Webmin or Ubuntu or which Patch?
> 
> It's better to wait until next Webmin release which will include this patch.

Yeah i know, but i have to edit many yaml files in webmin and i dont can wait. :)
But thank you for your fast reply

**Comment by iliajie** [comment]
> Yeah i know, but i have to edit many yaml files in webmin and i dont can wait. :)
> But thank you for your fast reply

You could take a small risk and find out how to install nightly version of Webmin.

**Comment by xbypaxl** [comment]
Thank you for your help, now it works fine!
