### ISSUE TITLE
postfix - `smtp_use_tls` needs removing

### ISSUE THREAD

**Issue by shoulders** [webmin/webmin#2148]
|  SYSTEM INFORMATION||
|----------------------|---------------------------|
|  OS type and version |     Ubuntu Linux 22.04.4     |
|  Webmin version      |     2.111      |
|  Usermin version     |     2.010     |
|  Virtualmin version  |     7.10.0       |
|  Theme version       |     21.10      |
|  Package updates     |      2  package updates are available   |
|  **Postfix**       |   3.6.4 |

### the issue

The value `smtp_use_tls` is obsolete and need removing

`Webmin --> Postfix Mail Server --> SMTP Client Options --> Use TLS for SMTP connections?:

### The evidence

- https://www.postfix.org/postconf.5.html#smtp_use_tls
  - This feature is available in Postfix 2.2 and later. With Postfix 2.3 and later use [smtp_tls_security_level](https://www.postfix.org/postconf.5.html#smtp_tls_security_level) instead.
- My current settings (SMTP Client Options)
      ![image](https://github.com/webmin/webmin/assets/319997/f752bbdc-d04c-4399-ab6e-fce25333f7d7)
- My current settings (**posfconf** and **postconf -d**)
    ![image](https://github.com/webmin/webmin/assets/319997/f45758ee-0863-470c-8f82-aec4201e3880)

### conclusion

As you can see the setting is ignored by postfix and the documentation says you should use `smtp_tls_security_level` instead.

### proposed solution

remove this setting

**Comment by jcameron** [comment]
Good idea, I've removed it here : https://github.com/webmin/webmin/commit/078d3acb98451ebfbf03b15e456e87e65f0a7e51
