### ISSUE TITLE
Postfix - `permit_mx_backup ` and `check_relay_domains` should be removed

### ISSUE THREAD

**Issue by shoulders** [webmin/webmin#2150]
|  SYSTEM INFORMATION||
|----------------------|---------------------------|
|  OS type and version |     Ubuntu Linux 22.04.4     |
|  Webmin version      |     2.111      |
|  Usermin version     |     2.010     |
|  Virtualmin version  |     7.10.0       |
|  Theme version       |     21.10      |
|  Package updates     |      2  package updates are available   |

### the issue

on the page `Webmin --> Postfix Mail Server --> SMTP Authentication And Encryption --> SMTP recipient restrictions`

![image](https://github.com/webmin/webmin/assets/319997/02c44605-507b-42a1-aa5b-6e9965f13a23)

the postfix options  `permit_mx_backup` and `check_relay_domains` for `smtpd_recipient_restrictions` should be removed

-  `permit_mx_backup` = warning in v3.9 to be deprecated
-   `check_relay_domains` = has been removed in v3.9

http://www.postfix.org/DEPRECATION_README.html

This is related to #2149 - there is one freetype input filed and then a more ridged checkbox selection

**Comment by jcameron** [comment]
Thanks, I'll remove these in versions 3.9 and later.
