### ISSUE TITLE
Postfix - SMTP Client Restrictions - Other restrictions option missing

### ISSUE THREAD

**Issue by shoulders** [webmin/webmin#2153]
|  SYSTEM INFORMATION||
|----------------------|---------------------------|
|  OS type and version |     Ubuntu Linux 22.04.4     |
|  Webmin version      |     2.111      |
|  Usermin version     |     2.010     |
|  Virtualmin version  |     7.10.0       |
|  Theme version       |     21.10      |
|  Package updates     |      6  package updates are available   |

## the issue

The options are selected by using checkboxes but this does not cover all options. So I edited the config manually to add all the options I wanted. This then had the result of bringing up a  `Other restrictions` input field which would of been useful.

### Before
![image](https://github.com/webmin/webmin/assets/319997/296f51af-5809-4b67-a7fe-7ad73bc5b327)

### After
![image](https://github.com/webmin/webmin/assets/319997/c98734bb-bebd-4b75-81b4-823d96c17e4c)

## proposed solution

Don't hide the `Other restrictions` input field so it can be used to enter additional values from the GUI

**Comment by jcameron** [comment]
Good idea, I'll change that!
