### ISSUE TITLE
Dovecot - Authentication methos are out of date

### ISSUE THREAD

**Issue by shoulders** [webmin/webmin#2154]
|  SYSTEM INFORMATION||
|----------------------|---------------------------|
|  OS type and version |     Ubuntu Linux 22.04.4     |
|  Webmin version      |     2.111      |
|  Usermin version     |     2.010     |
|  Virtualmin version  |     7.10.0       |
|  Theme version       |     21.10      |
|  Package updates     |      6  package updates are available   |

### The issue

`Webmin --> Servers --> Dovecot IMAP/POP3 Server --> User and Login Options --> Authentication Methods`

![image](https://github.com/webmin/webmin/assets/319997/9f230a05-84cb-4727-9014-8121a1d0d1e6)

- Anonymous
- Plain-text
- Digest-MD5
- Cram-MD5
- APOP
- login

The list of Authentication methods selectable from the GUI are now limited compared to what is available

https://doc.dovecot.org/configuration_manual/authentication/authentication_mechanisms/

![image](https://github.com/webmin/webmin/assets/319997/60b9bd2e-71fa-4496-88d8-ae316780a44d)

### proposed solution

update the list or make freetype

**Comment by jcameron** [comment]
Thanks, I'll update the list
