### ISSUE TITLE
Css and Js 404

### ISSUE THREAD

**Issue by Htmlbelov** [webmin/webmin#2155]
![image](https://github.com/webmin/webmin/assets/59169950/e3f44580-4a52-4217-8e8f-d773930a2f15)
`GET https://www.preprod.effectivesoft.com/webmin/unauthenticated/js/defaults.js?2110001019999999999 net::ERR_ABORTED 404 (Not Found)
webmin/:15
GET https://www.preprod.effectivesoft.com/webmin/service-worker.js 404 (Not Found)
webmin/:23
GET https://www.preprod.effectivesoft.com/webmin/unauthenticated/css/bundle.min.css?2110001019999999999 net::ERR_ABORTED 404 (Not Found)
webmin/:24
GET https://www.preprod.effectivesoft.com/webmin/unauthenticated/css/fonts-roboto.min.css?2110001019999999999 net::ERR_ABORTED 404 (Not Found)
webmin/:25
GET https://www.preprod.effectivesoft.com/webmin/unauthenticated/js/bundle.min.js?2110001019999999999 net::ERR_ABORTED 404 (Not Found)
webmin/manifest-webmin.json:1
GET https://www.preprod.effectivesoft.com/webmin/manifest-webmin.json 404 (Not Found)
manifest-webmin.json:1 Manifest: Line: 1, column: 1, Syntax error.`

webmin -  version: 2.111
OS - Debian 12

After webmin are installed I use this instruction for nginx (step "Want to run under Nginx sub-directory?")
https://webmin.com/faq/#can-i-run-webmin-or-usermin-behind-reverse-proxy
 

But when i entered to /webmin - all css and js send 404 status(

**Comment by jcameron** [comment]
@iliajie this looks like theme JS or CSS?

**Comment by iliajie** [comment]
This isn't our issue. It's a misconfiguration of a reverse proxy server, or possibly because `www.preprod.effectivesoft.com/webmin` is password protected.
