### ISSUE TITLE
Can SpamAssassin do DNS lookups? - Wrong default?

### ISSUE THREAD

**Issue by shoulders** [webmin/webmin#2156]
|  SYSTEM INFORMATION||
|----------------------|---------------------------|
|  OS type and version |     Ubuntu Linux 22.04.4     |
|  Webmin version      |     2.111      |
|  Usermin version     |     2.010     |
|  Virtualmin version  |     7.10.0       |
|  Theme version       |     21.10      |
|  Package updates     |      6  package updates are available   |
| **SpamAssassin version** | **3.4.6**

`Webmin --> Servers --> SpamAssassin Mail Filter --> Miscellaneous User Options --> Can SpamAssassin do DNS lookups?`

![image](https://github.com/webmin/webmin/assets/319997/f104b221-f0a7-4c83-8d98-edb069c28a7c)

I am running **SpamAssassin version v3.4.6** and according to the Docs
https://spamassassin.apache.org/full/4.0.x/doc/Mail_SpamAssassin_Conf.html#dns_available-yes-no-test-:-domain1-domain2...-default:-yes
> Since version 3.4.0 of SpamAssassin a default setting for option dns_available is yes. A default in older versions was test.

I always assumed the `Default` options were dynamically read or that this change of default value has not made it to this release of SpamAssassin?

**NB:** I know this is a small issue but I might not be back to this config for while. 😄

**Comment by jcameron** [comment]
Thanks, we'll fix this in the next release..
