### ISSUE TITLE
Web interface stopped working entirely after update

### ISSUE THREAD

**Issue by balaianu** [webmin/webmin#2158]
I have Webmin/Virtualmin installed on an Ubuntu 20.04.06 LTS server for years, and has been working with no issues until today.

I just did a package update on the server, and it also updated webmin/virtualmin. Now when I try to access the web interface I just get a timeout browser error: "The connection has timed out" (Firefox, but it's the same on any browser).

Doing a `virtualmin info` in the terminal shows:

> virtualmin info
> cpu: 
>     * 26
>     * 3
>     * 72
>     * 0
>     * 0
> disk_free: 1434944253952
> disk_fs: 
>     * 
>         device: UUID=9efb9241-5bbf-4643-8c0b-8bb69393e277
>         dir: /
>         free: 82312753152
>         ifree: 13914956
>         itotal: 14147584
>         iused: 232628
>         iused_percent: 2
>         total: 227017613312
>         type: ext4
>         used: 133098487808
>         used_percent: 62
>     * 
>         device: UUID=4065fd1f-85a8-45ad-adcd-dc907fb63517
>         dir: /boot
>         free: 315547648
>         ifree: 32170
>         itotal: 32768
>         iused: 598
>         iused_percent: 2
>         total: 511266816
>         type: ext3
>         used: 168878080
>         used_percent: 35
>     * 
>         device: /dev/sdb1
>         dir: /home
>         free: 1352315953152
>         ifree: 69397779
>         itotal: 122060800
>         iused: 52663021
>         iused_percent: 44
>         total: 1967301828608
>         type: ext4
>         used: 514976944128
>         used_percent: 28
> disk_total: 2194830708736
> disk_used: 648244310016
> fcount: 
>     aliases: 25
>     dbs: 13
>     dir: 13
>     dns: 12
>     doms: 13
>     ftp: 0
>     logrotate: 13
>     mail: 4
>     mysql: 11
>     postgres: 0
>     spam: 0
>     ssl: 13
>     unix: 13
>     users: 35
>     virus: 0
>     web: 13
>     webalizer: 11
>     webmin: 0
> ftypes: 
>     * doms
>     * dns
>     * web
>     * ssl
>     * mail
>     * dbs
>     * users
>     * aliases
> host: 
>     hostname: [REDACTED]
>     module root: /usr/share/webmin/virtual-server
>     os: Ubuntu Linux 20.04.4
>     root: /usr/share/webmin
>     theme version: 21.10
>     virtualmin version: 7.10.0.gpl-1
>     webmin version: 2.111
> io: 
>     * 0
>     * 1668
> kernel: 
>     arch: x86_64
>     os: Linux
>     version: 5.4.0-181-generic
> load: 
>     * 0.85
>     * 0.71
>     * 0.78
>     * 3717
>     * Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz
>     * GenuineIntel
>     * 8388608
>     * 8
> mem: 
>     * 32730068
>     * 29486012
>     * 16777212
>     * 16777212
>     * 4163148
>     * 
> procs: 311
> progs: 
>     * 
>         * Perl version
>         * 5.030000
>     * 
>         * Path to Perl
>         * /usr/bin/perl
>     * 
>         * Python version
>         * 3.8.10
>     * 
>         * Path to Python
>         * /bin/python3
>     * 
>         * BIND version
>         * 9.16
>     * 
>         * Postfix version
>         * 3.4.13
>     * 
>         * Mail injection command
>         * /usr/lib/sendmail -t
>     * 
>         * Apache version
>         * 2.4.41
>     * 
>         * PHP versions
>         * 5.6.40, 7.4.33, 8.0.30, 8.1.28, 8.2.18, 8.3.6
>     * 
>         * Webalizer version
>         * 2.23-08
>     * 
>         * Logrotate version
>         * 3.14.0
>     * 
>         * MySQL version
>         * 8.0.36-0ubuntu0.20.04.1
>     * 
>         * ProFTPD version
>         * 1.36
>     * 
>         * SpamAssassin version
>         * 3.4.4
>     * 
>         * ClamAV version
>         * 0.103.11
> reboot: 0
> status: 
>     * 
>         feature: web
>         name: Apache Webserver
>         status: 1
>     * 
>         feature: fpm
>         id: 5.6.40
>         name: PHP-FPM 5.6.40 Server
>         status: 1
>     * 
>         feature: fpm
>         id: 7.4.33
>         name: PHP-FPM 7.4.33 Server
>         status: 1
>     * 
>         feature: fpm
>         id: 8.0.30
>         name: PHP-FPM 8.0.30 Server
>         status: 1
>     * 
>         feature: fpm
>         id: 8.1.28
>         name: PHP-FPM 8.1.28 Server
>         status: 1
>     * 
>         feature: fpm
>         id: 8.2.18
>         name: PHP-FPM 8.2.18 Server
>         status: 1
>     * 
>         feature: fpm
>         id: 8.3.6
>         name: PHP-FPM 8.3.6 Server
>         status: 1
>     * 
>         feature: dns
>         name: BIND DNS Server
>         status: 1
>     * 
>         feature: mail
>         name: Postfix Mail Server
>         status: 1
>     * 
>         feature: dovecot
>         name: Dovecot IMAP / POP3 Server
>         status: 1
>     * 
>         feature: saslauthd
>         name: SASL Authentication Server
>         status: 1
>     * 
>         feature: ftp
>         name: ProFTPD FTP Server
>         status: 1
>     * 
>         feature: sshd
>         name: SSH Server
>         status: 1
>     * 
>         feature: mysql
>         name: MySQL Database Server
>         status: 1

Also, `netstat -ln |grep 10000` returns this (port 10000 is open):

> netstat -ln |grep 10000
> tcp        0      0 0.0.0.0:10000           0.0.0.0:*               LISTEN     
> tcp6       0      0 :::10000                :::*                    LISTEN     

`webmin status` shows everything should be running too:

> webmin status
> ● webmin.service - Webmin server daemon
>      Loaded: loaded (/lib/systemd/system/webmin.service; enabled; vendor preset: enabled)
>      Active: active (running) since Fri 2024-05-10 19:35:19 EEST; 26min ago
>     Process: 122562 ExecStart=/usr/share/webmin/miniserv.pl /etc/webmin/miniserv.conf (code=exited, status=0/SUCCESS)
>    Main PID: 122593 (miniserv.pl)
>       Tasks: 1 (limit: 38278)
>      Memory: 98.2M
>      CGroup: /system.slice/webmin.service
>              └─122593 /usr/bin/perl /usr/share/webmin/miniserv.pl /etc/webmin/miniserv.conf

I have no idea what happened, and everything looks good to me. There were no errors during the package updates, and the interface was working ok until I did a server `reboot`.

I should also mention that everything else works as expected on the server: all sites are up, all services are running, everything except the web interface.

Please help!

**Comment by iliajie** [comment]
> There were no errors during the package updates, and the interface was working ok until I did a server `reboot`.

It's likely that something is blocking port 10000.

**Comment by balaianu** [comment]
> It's likely that something is blocking port 10000.

Like what? As I mentioned, everything has been working, including the interface until the post-upgrade server reboot. I did nothing to change any settings neither before or after the package updates.

I'm open to suggestions...

**Comment by balaianu** [comment]
Somehow, the iptebles rules reverted to a (very) old config that was blocking access to the 10000 port except for a specific IP, which is no longer valid.

I managed to find and restore a backup of the correct iptables rules and now it's working properly again.
For anyone interested, the instructions on how to do this are pretty straight forward.

Create a snapshot of the current ruleset with

`iptables-save > /path/to/file`

and restore it later with

`iptables-restore < /path/to/file`

Just wanted to mention this in case someone else stumbles upon this while having the same issue.
