### ISSUE TITLE
SpamAssassin - Header and Body Tests - 2 input boxes for expression? - Time for a single page?

### ISSUE THREAD

**Issue by shoulders** [webmin/webmin#2166]
|  SYSTEM INFORMATION||
|----------------------|---------------------------|
|  OS type and version |     Ubuntu Linux 22.04.4     |
|  Webmin version      |     2.111      |
|  Usermin version     |     2.010     |
|  Virtualmin version  |     7.10.0       |
|  Theme version       |     21.10      |
|  Package updates     |      26  package updates are available   |

### the issue

On the simple page there are 2 input boxes for `Match Expression` and it is not clear what they are for

![image](https://github.com/webmin/webmin/assets/319997/0f09997b-1a84-4210-95b7-9bb346901fbf)

After inspecting the code i think `input box one` is for the expression and `input box 2` is for regex flags

These 2 columns do not tally up directly with those on the advanced mode as thre is just pone box for the regex

### proposed solutions

- on the simple mode, label both of the columns as follows Match expression (Regex / Flags)
- There only needs to be one page, the simple and advanced page is a bit fiddly and adds extra complexity when it could all be done on one page like in cpanel
  ![image](https://github.com/webmin/webmin/assets/319997/7f08e9d3-d8ee-4661-88ef-2fb1289cedf1)
  ![image](https://github.com/webmin/webmin/assets/319997/7e8c5c47-b12d-4c36-922b-2640d8a14ad0)

### Additional
- I assume this template will change Webmin and Virtualmin
- **Allow users to define tests?** is in a weird place. This is hidden under the `advanced mode`. I agree this is related to these tests but it breaks the layout and unless you go hunting you would not expect it here.
   ![image](https://github.com/webmin/webmin/assets/319997/9f0f3198-b2fb-48d3-a9ff-799d19637501)

**Comment by jcameron** [comment]
Wow, for some reason this field is being displayed oddly in the authentic theme. It should look like this, where the first field is the regexp and the second is the flags : 

![image](https://github.com/webmin/webmin/assets/102706/9eb5eae1-b673-4bcc-b512-877f8bb3d73a)

@iliajie any idea what's up here?

**Comment by iliajie** [comment]
> @iliajie any idea what's up here?

It looks like Authentic theme bug. I will update this ticket when I take a closer look at it..

**Comment by iliajie** [comment]
Alright, I have fixed it, making the regex and flag fields look more natural, alongside fixing other bugs:

<img width="1670" alt="image" src="https://github.com/webmin/webmin/assets/4426533/ef3fb405-8871-44b0-9bc5-581a52d23325">

**Comment by jcameron** [comment]
Looks good!

**Comment by iliajie** [comment]
Thanks!

**Comment by shoulders** [comment]
> Looks good!

+1

Also I can wait to see how you added the placeholder in at both ends, very cool. this make the whole page much more logical and it is now obvious what both boxes are for now.

![image](https://github.com/webmin/webmin/assets/319997/0e25ef60-9088-4d5e-8bd5-4fc33f14a53a)

**Comment by iliajie** [comment]
I should have done it from the start. Thanks for pointing this out. Better late than never!
