### ISSUE TITLE
System Logs Viewer - Some improvements

### ISSUE THREAD

**Issue by shoulders** [webmin/webmin#2169]
|  SYSTEM INFORMATION||
|----------------------|---------------------------|
|  OS type and version |     Ubuntu Linux 22.04.4     |
|  Webmin version      |     2.111      |
|  Usermin version     |     2.010     |
|  Virtualmin version  |     7.10.0       |
|  Theme version       |     21.10      |
|  Package updates     |     All installed packages are up to date   |

### background

- On my dev system I got use to looking at the mail.err log file easily just to see mail related stuff and I could do this because I had `rsyslog` installed which used the webmin module `System Logs`
- Ubuntu seem to be moving to `journald` from `rsyslog` and non-longer installs by default `rsyslog` in favour of going forward with `journald`

### the issue

the `System Logs Viewer` is missing some feature to make it a very handy utility with as much functionality as `System Logs`

- Ability to add own journals - current you can only add log files.
- Add some premade/default `journald` logs for the mails systems
  - journalctl -t postfix/smtpd -t postfix/smtp
  - journalctl -t postfix/smtp 
  - journalctl -t postfix/smtpd
  - journalctl -t dovecot
- Ability to add a service filter (maybe this is optional if you can add your own `journald log commands`)
- On the current ones show the full command when you edit it. Currently they are concatenated an when you edit them you they are still concatenated 
  ![image](https://github.com/webmin/webmin/assets/319997/5937fe70-98e8-41cf-b0dd-a76891ec2561)
  ![image](https://github.com/webmin/webmin/assets/319997/5780ca3c-fd0f-46a5-b163-059b3cbc8296)

### Additional

@stigjoergensen asked for the ability to add custom logs into this webmin modue in #2074 

The `-f` command could just be removed by webmin if someone tries to use a command with it. Maybe a note somewhere that `-f` is not currently supported.

### References
- https://askubuntu.com/questions/1508910/is-it-expected-to-not-have-rsyslog-installed-after-a-fresh-install-of-ubuntu-s
- https://forum.virtualmin.com/t/system-logs-viewer-missing-logs/126913/12

**Comment by iliajie** [comment]
Hello,

> * Add some premade/default `journald` logs for the mails systems

I like this idea, I will look into adding it!

**Comment by iliajie** [comment]
Implemented here https://github.com/webmin/webmin/pull/2170.
