### ISSUE TITLE
Apache Webserver - Open

### ISSUE THREAD

**Issue by qooob** [webmin/webmin#217]
Jamie, I think for standard ports (80,443), when clicking open user should get `https://domain.com` not `domain.com:443` - it's useless in most cases. Right? (For port 80 it's alright)

**Comment by jcameron** [comment]
Good point - I will fix this in the next release.

**Comment by qooob** [comment]
Jamies, I still see `http://url:443` instead of `https://url`. Can you please double-check?

**Comment by qooob** [comment]
..it seems to be happening if virtual-server has more than one IP address..

**Comment by jcameron** [comment]
Does this only happen for you when a domain has multiple IPs?

**Comment by qooob** [comment]
Yes, it seems that when it's one IP it works

**Comment by jcameron** [comment]
Are all the IPs on the same port? I'd be interested to see the actual VirtualHost line from your Apache config.

**Comment by qooob** [comment]
Sure, here:

```
<VirtualHost 31.186.102.xxx:80 31.186.102.xxx:80 [2a00:ab00:4300:90:8080:aa31:6d0b:xxxx]:80 [2a00:ab00:4300:90:8080:aa31:6d0b:xxxx]:80>

</VirtualHost>

<VirtualHost 31.186.102.xxx:443 31.186.102.xxx:443 [2a00:ab00:4300:90:8080:aa31:6d0b:xxxx]:443 [2a00:ab00:4300:90:8080:aa31:6d0b:xxxx]:443>

</VirtualHost>

```

**Comment by jcameron** [comment]
Ok, I have committed a fix that should solve this.

**Comment by qooob** [comment]
Yes, thanks! It works now.
