### ISSUE TITLE
Postfix - `permit_networks` does not work

### ISSUE THREAD

**Issue by shoulders** [webmin/webmin#2174]
|  SYSTEM INFORMATION||
|----------------------|---------------------------|
|  OS type and version |     Ubuntu Linux 22.04.4     |
|  Webmin version      |     2.111      |
|  Usermin version     |     2.010     |
|  Virtualmin version  |     7.10.0       |
|  Theme version       |     21.10      |
|  Package updates     |     All installed packages are up to date   |
|  **Postfix**      |     **3.6.4**      |

This might have Virtualmin consequences.

This is a long one but the solution is very easy.

## The background

I am setting up my mail server restrictions rules and found that the `permit_networks` does not work. When you add this setting you would expect the restriction policy to give my local computers a pass but this was not the case.

The restriction rule I was using was:

`smtpd_helo_restrictions = permit_mynetworks, reject_invalid_helo_hostname, reject_non_fqdn_helo_hostname, reject_unknown_helo_hostname`

Yes I could use `permit_sasl_authenticated` and this was working but this should be ignored for the purpose of this issue.

So with my local windows PC, using the outlook client I tried to send an email but instead I got this error in the posftfix log:

```
May 27 07:57:04 server.example.com postfix/smtpd[1072276]: connect from router.example.com[10.0.0.1]
May 27 07:57:05 server.example.com postfix/smtpd[1072276]: NOQUEUE: reject: RCPT from router.example.com[10.0.0.1]: 504 5.5.2 <laptop>: Helo command rejected: need fully-qualified hostname; from=<testuser@example.com> to=<remoteuser@remoteserver.com> proto=ESMTP helo=<mylaptop>
May 27 07:57:07 server.example.com postfix/smtpd[1072276]: disconnect from router.example.com[10.0.0.1] ehlo=1 auth=1 mail=1 rcpt=0/1 quit=1 commands=4/5
```

**NB:** Windows PCs will not send a FQDN in the HELO command unless you are part of a Domain (or maybe added it manually). This is different than the PCs DNS name which is registered correctly with my router i.e. `laptop.example.com`. The dodgy HELO is an issue with Windows PCs. Whichever way you look at it you are not going to add a registry fix to hundreds of PCs manually.

## The issue

`permit_mynetworks` is not allowing my Windows PC (Outlook Client) with dodgy HELO commands to skip the HELO restriction policy.

this means `permit_mynetworks` is not working.

## Research

So researching this I found that the 2 settings that control this are in `main.cf`: 
- [mynetworks_style](https://www.postfix.org/postconf.5.html#mynetworks_style)
   - This defines the networks that are allowed in the `mynetworks` variable
   - there are several types, the default is `host` on v3.6
     - host = `mynetworks = 127.0.0.1/32 10.0.0.41/32 [::1]/128 [fe80::2a0:98ff:fe24:ff08]/128`
     - subnet = `mynetworks = 127.0.0.0/8 10.0.0.0/24 [::1]/128 [fe80::]/64`
     - class = `mynetworks = 127.0.0.0/8 10.0.0.0/8 [::1]/128 [fe80::]/64`
- [mynetworks](https://www.postfix.org/postconf.5.html#mynetworks)
   -  This will override `mynetworks_style`

In virtualmin `mynetworks` is manually set in the `main.cf`

`mynetworks = 127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128`

and as you can see it only allows localhost IPs.

`mynetworks_style` = host give the following:

`mynetworks = 127.0.0.1/32 10.0.0.41/32 [::1]/128 [fe80::2a0:98ff:fe24:ff08]/128`

and as you can see they are slightly different. I suspect the Virtualmin value has been the same for many years and version of Postfix.

In old versions of postfix the `subnet` was the default, but now it is `host`.

## What does this all mean

- `mynetworks = 127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128` in `main.cf` was put there by virtualmin and only allows localhost traffic only.
- `mynetworks_style` will not work with the current config because of the presence of `mynetworks` in `main.cf`
   -  according to the docs: If you specify the [mynetworks](https://www.postfix.org/postconf.5.html#mynetworks) list by hand, Postfix ignores the [mynetworks_style](https://www.postfix.org/postconf.5.html#mynetworks_style) setting.

`mynetworks` needs to be edited or removed.

## Possible solution for virtualmin/Webmin

> **NB:** I can alter the `main.cf` and correct these issues now that I know about them, but this solutions is to prevent this happening to new installs and make it easier for others to fix.

- remove `mynetworks = 127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128` in `main.cf` for new installs. This will cause the default `host` setting to be used for `mynetworks` but can be overridden via the GUI using the `mynetworks_style` setting (as described below).
- in `Webmin --> Servers --> PostfixMail Server --> SMTP Server Options add the following settings
  - `mynetworks` : With default + input box
      ![image](https://github.com/webmin/webmin/assets/319997/ddda1978-5219-4b75-b250-db017ba3014d)
  - `mynetworks_style` with dropdown options of: Default/Host/Subnet/Class
      ![image](https://github.com/webmin/webmin/assets/319997/ee13605d-c88d-4082-8656-6018fac54815)

**Comment by jcameron** [comment]
I feel like this out of the scope of Virtualmin ... for a typical install we don't rely on local network relaying at all. Email is either sent by authenticated clients, or un-authenticated by programs running locally.

**Comment by shoulders** [comment]
I will just clarify this 😄 

All over the internet people use `permit_mynetworks, permit_sasl_authenticated` but I reckon 90% of people don't know the first test is not working as expected.

### Bug

Virtualmin injects `mynetworks = 127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128` into the `main.cf` I suspect was added a long time ago for security because the default `networks_style = subnet` where the permitted networks included all of the local subnets connect to the server. The default is now  `networks_style = host` which as noted above is more correct than the one injected by vitualmin because postfix reads the interfaces and generates the correct `mynetworks` value.

The means, for new installs you should not inject `mynetworks = 127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128` as there is no need anymore to have the incomplete string. The reason you did not inject the part `10.0.0.41/32` which for obvious reasons you cannot predict.

### Improvement

As mentioned above I think it would be a good thing to include `mynetworks` and `mynetworks_style` as these will allow you to control `permit_mynetworks` which is intergral to a well defined security policy from the GUI,.

### We don't rely on local network relaying at all

Not sure what you mean here 😄  . but removing the injected `mynetworks` will not change security but allow the addition of the 2 settings into the GUI to allow people to configure their email server. I appreciate that authenticated users is best but sometimes people who are messing with apps might not want this.

These settings are less about funnelling the user down one particular route but adding in a substancial part of postfix. (i know it is only 2 settings but these ones matter)

**Comment by jcameron** [comment]
Are you sure Virtualmin is setting `mynetworks` ? I couldn't find any code that does this as part of the installer or the UI.

**Comment by shoulders** [comment]
Interesting, I did not expect this answer, I will go and have a look at postfix code for `mynetworks`.

**Comment by shoulders** [comment]
## What I found

`mynetworks = 127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128` is added by Ubuntu upstream

### Postfix 3.6.4 original - main.cf

`https://packages.ubuntu.com/source/jammy/postfix`  --> [postfix_3.6.4.orig.tar.gz](http://archive.ubuntu.com/ubuntu/pool/main/p/postfix/postfix_3.6.4.orig.tar.gz) --> `/postfix-3.6.4/conf/main.cf`

This does not have `mynetworks` declared but this partly out of date message ( let postfix do it for you is in date, but host is the default `networks_style`
```
# You can specify the list of "trusted" network addresses by hand
# or you can let Postfix do it for you (which is the default).
#
# By default (mynetworks_style = subnet), Postfix "trusts" SMTP
# clients in the same IP subnetworks as the local machine.
# On Linux, this works correctly only with interfaces specified
# with the "ifconfig" command.
```
### Ubuntu Patches / Install script

This is where `mynetworks = 127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128` seems to be added (still with an out of date description subnets/host)

`https://packages.ubuntu.com/source/jammy/postfix`  --> [postfix_3.6.4-1ubuntu1.3.debian.tar.xz](http://archive.ubuntu.com/ubuntu/pool/main/p/postfix/postfix_3.6.4-1ubuntu1.3.debian.tar.xz) --> `/postfix_3.6.4-1ubuntu1.3.debian/debian/templates`

```
Template: postfix/mynetworks
Type: string
Default: 127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128
_Description: Local networks:
 Please specify the network blocks for which this host should relay mail.
 The default is just the local host, which is needed by some mail user agents.
 The default includes local host for both IPv4 and IPv6. If just connecting
 via one IP version, the unused value(s) may be removed.
 .
 If this host is a smarthost for a block of machines, you need to specify the
 netblocks here, or mail will be rejected rather than relayed.
 .
 To use the Postfix default (which is based on the connected subnets), leave
 this blank.
```

### What does this mean

- There is no bug in virtualmin
- `mynetworks = 127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128` is added upstream by Ubuntu, not Postfix.
- There is no harm to leave this `mynetworks` value, and also trying to alter this could caused issues in other distros.
- Adding `mynetworks` and `mynetworks_style` into the GUI is a valid point and this will allow easy configuration of these settings and this would make irrelevant what the upstream distros set `mynetworks` too.

**Comment by shoulders** [comment]
@iliajie How did I miss that. Awesome its like this feature was added instantly 😄 . I will update my notes accordingly. I have been at this for 2 weeks and I need a break :smile: , but I also have a nicely working email server, thanks for that.

I do think there should be some small changes though.

**Local networks**
- Remove `(all attached networks) `  and just have `Local Networks`. This is because this setting just means you are specifying them manually. By not specifying them manually does not mean `all attached networks`. If you don't specify anything here the `Automatic local networks (mynetworks_style)` will push the network definition into `mynetworks` depending on the policy and this is not always `All attached networks`, especially the default of `host`.

**Automatic local networks**
- can you add the default option, this is where this setting is not specified in `main.cf` and the default policy of Postfix is choosen if no `local networks (mynetworks)` is choosen. This will also reduce confusion as to why there is an an option specifying local networks and then an automatic one specifyng some thing else. When there is a default options the admin can assume this option might not be present but if it is specified he might assume it should be working.
- Also, simply the default option is missing.

**Comment by shoulders** [comment]
I don't usually bump, but I know you guys have been busy and might of missed this, is there any chance these 2 small changes (above) could be added for the next release?

**Comment by jcameron** [comment]
For the "Local networks" option, do you think there shouldn't be a default at all? Or should it just be named differently?

**Comment by shoulders** [comment]
There should absolutely be a default option for `mynetworks_style` .

- If you define `mynetworks` you should not define `mynetworks_style` and the default option would allow this. 
- Also, default should be the `Webmin` default meaning that there would be not `mynetworks_style` defined in the config.
- also the this would follow with the manual. https://www.postfix.org/postconf.5.html#mynetworks_style
- The default option can change between version (default: Postfix ≥ 3.0: host, Postfix < 3.0: subnet)

**Comment by shoulders** [comment]
lol I read your comment wrong

> For the "Local networks" option, do you think there shouldn't be a default at all? Or should it just be named differently?

Just named different

`Default (all attached networks) ` --> `Default`

**Comment by jcameron** [comment]
Ok that I can do!

**Comment by shoulders** [comment]
This one is definitely on my Christmas list, thanks.

**Comment by shoulders** [comment]
![image](https://github.com/user-attachments/assets/255e8742-4bb2-4522-a980-2cdf96bb1f7a)

- `Local networks` / `mynetworks` = Wording corrected
- `Automatic local networks` / `mynetworks_style ` = now has a default version
