### ISSUE TITLE
Load dynamic modules .conf file in different locations

### ISSUE THREAD

**Issue by aryanrajseo** [webmin/webmin#2175]
Hi, i recently installed Flarum on the path public_html/public and the root directory is set in website options. However with nginx server Flarum includes a .nginx.conf file which doesn't seems to be dynamically included in webserver configuration so any permalink except index is not working.

I can include the following line `include /home/sitename/public_html/.nginx.conf;` by editing _`/etc/nginx/nginx.conf`_

https://IP:10000/virtualmin-nginx/edit_manual.cgi?xnavigation=1

and this work after the webserver reload but i am not sure if this is the right way and if we can detect any .conf file in in different folders dynamically?

Thank you.

Webmin version	2.111 	Usermin version	2.010
Virtualmin version	7.10.0
nginx webserver.

**Comment by jcameron** [comment]
This seems risky, because the owner of that website would effectively be able to edit the global Nginx config via that include file..

**Comment by aryanrajseo** [comment]
oh, you are right, never thought about that. do we have any other ways so it can be modified via user access and not root?

**Comment by jcameron** [comment]
Sadly Nginx has no equivalent to the Apache .htaccess files that could be used to do this safely..

**Comment by aryanrajseo** [comment]
I understand. as i had vps, never thought i would need to look as a user.
