### ISSUE TITLE
Unclear / inconsistent logic for resulting color and style of buttons

### ISSUE THREAD

**Issue by rdmark** [webmin/webmin#2176]
Webmin has logic for automatically picking a color and style of Start/Stop/Restart/Apply type buttons in a `&ui_buttons_row()` context.

However, I am struggling to consistently get the style of button that I want in [my modules](https://github.com/Netatalk/netatalk-webmin/tree/service-control). Can you please help me understand the logic, and/or tell me if there is a manual override (undocumented flag?) to force the style that I want.

I have two specific use cases in my module.

1) I can get Start/Restart styles, but never the Stop style. I know for a fact that one exists, because other modules (e.g. the bundled sshd module) use it.

<img width="535" alt="Screenshot 2024-05-29 at 19 25 14" src="https://github.com/webmin/webmin/assets/2108467/137137f8-d720-4b05-aea5-85218f9dab20">

2) When the second parameter of `&ui_buttons_row()` is a `&text()` function call, the buttons *never* get a style.

<img width="507" alt="Screenshot 2024-05-29 at 19 33 45" src="https://github.com/webmin/webmin/assets/2108467/ae3c00cf-ff71-4d27-b79f-c584a39686ed">

**Comment by rdmark** [comment]
Thank you for the info! This led to my first issue being resolved.

The second issue is still happening, even if I follow the above naming pattern. If the second parameter is something like `&text('running_start', $somevariable)` then the button style does not take effect. Any thoughts on this?

**Comment by iliajie** [comment]
Ah, this wasn't supported until now. But it will in the next Webmin release.

**Comment by rdmark** [comment]
Cool, I’ll keep an eye out and try again when the new release is available. 

Thanks for your support!

**Comment by iliajie** [comment]
You're welcome! I'll close this ticket then.
