### ISSUE TITLE
postfix - SMTP TLS client security level GUI options does not change smtp_tls_security_level

### ISSUE THREAD

**Issue by shoulders** [webmin/webmin#2177]
|  SYSTEM INFORMATION||
|----------------------|---------------------------|
|  OS type and version |     Ubuntu Linux 22.04.4     |
|  Webmin version      |     2.111      |
|  Usermin version     |     2.010     |
|  Virtualmin version  |     7.10.0       |
|  Theme version       |     21.10      |
|  Package updates     |      17  package updates are available   |

### the issue

Webmin --> Postfix Mail Server --> SMTP Client Options --> SMTP TLS client security level`
- does not update `smtp_tls_security_level` value in the config because it is broken.
- If you set `smtp_tls_security_level` manually in the config, the correct value is shown in the GUI

![image](https://github.com/webmin/webmin/assets/319997/f9abaed9-7f15-4b30-8ca9-1ed3529a3ec8)

### proposed solution

fix the parsing and config writing routine for this

**Comment by iliajie** [comment]
Thanks for the heads up! It was a bug!

We will fix it in the next Webmin release!
