### ISSUE TITLE
System and Server Status Perl error

### ISSUE THREAD

**Issue by ArcanumSK** [webmin/webmin#218]
HTTP/1.0 500 Perl execution failed Server: MiniServ/1.750 Date: Sun, 31 May 2015 16:01:16 GMT Content-type: text/html; Charset=iso-8859-1 Connection: close
Error - Perl execution failed
postfix::is_postfix_running failed : Failed to query Postfix config command to get the current value of parameter queue_directory:  at /usr/share/webmin/web-lib-funcs.pl line 1397.

**Comment by jcameron** [comment]
This could happen if Postifx is down, or for some reason the `postconf` command fails. Is Postfix working on your system?

I will add a check for this case in the next Webmin release so that it doesn't cause the status check to completely fail though.

**Comment by ArcanumSK** [comment]
Reinstalled postfix, now working.
