### ISSUE TITLE
Why is the temperature displayed incorrectly using sersors？

### ISSUE THREAD

**Issue by liutt1312** [webmin/webmin#2188]
Why is the temperature displayed incorrectly using sersors？

![image](https://github.com/webmin/webmin/assets/86719542/d22a1b2f-9872-4e8a-9862-63fddffeba57)
![image](https://github.com/webmin/webmin/assets/86719542/f7247b89-b169-4aeb-add6-e0424cbd862a)

**Comment by iliajie** [comment]
Hello,

Be cause `sensors` command output is ridiculously random!

Could you share `sensors` command output in plain text?

**Comment by iliajie** [comment]
I have checked closer and I don't see any issue here. Do you always see this discrepancy?

Is CPU temperature information getting updated if you force refresh system information on the dashboard?

Do you have real-time monitoring enabled in **Theme Configuration** page?

**Comment by liutt1312** [comment]
> I have checked closer and I don't see any issue here. Do you always see this discrepancy?
> 
> Is CPU temperature information getting updated if you force refresh system information on the dashboard?
> 
> Do you have real-time monitoring enabled in **Theme Configuration** page?

Thank you for your guidance, although my device is not displaying correctly

**Comment by iliajie** [comment]
Are the temperatures getting updated ot it's always showing 65C°?

**Comment by iliajie** [comment]
Are 

> The temperature is updating, but the displayed value is always greater than the value displayed by sensors on the command line

Are the numbers consistently greater in a pattern-like manner?
