### ISSUE TITLE
Webmin (UI) breaks with Error: 500 - Perl execution failed - Undefined subroutine (...)

### ISSUE THREAD

**Issue by by** [webmin/webmin#2190]
Since very few days, webmin's dashboard breaks with the error message
```
Error: 500 - Perl execution failed - Undefined subroutine &main:allocate_miniserv_websocket called
/stats.cgi?xhr-stats=general&sdata=1
```
I'm running the nightly versions
Webmin version | 2.111.202406031255
Usermin version | 2.010.202406031255
Authentic theme version | 21.10:79

**Comment by by** [comment]
Maybe commit 5a8b346 is the culprit?

**Comment by iliajie** [comment]
Hello,

Thanks for the heads up!

Have you tried restarting Webmin manually? Did you try a force reload of the browser page?

Also, where exactly are you seeing this error?

Either way, for now, you should disable real-time monitoring in the theme configuration page. I will let you know when I complete the client-side rework, as we're switching real-time monitoring to use WebSockets..

**Comment by jcameron** [comment]
How was this change picked up if we haven't released a new Webmin version yet?

**Comment by iliajie** [comment]
The user mentioned that they are using nightly versions.

**Comment by iliajie** [comment]
Actually, I see the bug that's causing it https://github.com/webmin/webmin/commit/4f7924338d524267c622fa09e0c0bea2051c40fe. Fixed now.

**Comment by by** [comment]
> How was this change picked up if we haven't released a new Webmin version yet?

I'm using https://github.com/webmin/webmin/blob/master/setup-repos-nightly.sh

**Comment by by** [comment]
Yes, it's fixed, thank you!
