### ISSUE TITLE
Gentoo Linux is not detected correctly

### ISSUE THREAD

**Issue by vsc55** [webmin/webmin#2196]
On Linux Gentoo systems where /var/db/repos/gentoo is being used as package repository storage, webmin is detecting the system as Generic Linux.

![imagen](https://github.com/webmin/webmin/assets/13438676/224ed53b-b205-4142-9b53-7aaf8d83ebcc)

**Comment by jcameron** [comment]
Does the directory `/usr/portage` exist on your system?

**Comment by vsc55** [comment]
Hi @jcameron,
No, it is a new installation of the gentoo system, now gentoo uses /var/db/repos/gentoo by default.
I have created a Fix that corrects the system detection.

**Comment by jcameron** [comment]
Cool thanks for that patch!

https://github.com/webmin/webmin/pull/2197/commits/9eec58a1f1bce34701e8560559c6d11ef0e06354

**Comment by vsc55** [comment]
Wow, that was a quick merge 😀
A pleasure to lend a hand wherever I can.
