### ISSUE TITLE
UI subroutine documentation?

### ISSUE THREAD

**Issue by knuxyl** [webmin/webmin#2198]
I know this isn't the place for this but I cannot seem to find any documentation on the ui subroutines for the latest api. I'm trying to write a module for using hostapd and wpa_supplicant to make openwrt obsolete on x86 but I'm getting no where fast with these obscure subroutines. For example, I need to make some tabs, and I'm looking at tcpwrappers index.cgi to get an idea but I can't interpret what in the world is going on with
```
print &ui_tabs_start(
	[ map { [ $_, $text{'index_'.$_.'title'},
		  "index.cgi?type=$_" ] } @types ],
	"type",
	$in{'type'} || "allow",
	1);
```
I'm new to perl so I know I need to learn a lot, but not knowing what the functions webmin provides isn't part of that. The closest I've found is https://webmin.com/docs/development/creating-overlay-themes/ that mentions these functions, but doesn't explain at all what arguments they expect or what it does with them. Can someone give me an idea of where to look? Thanks

**Comment by iliajie** [comment]
You can add `var_dump(\@types);` after `ui_tabs_start` to see what `@types` is.

For more details, check the UI library itself, e.g.:

https://github.com/webmin/webmin/blob/master/ui-lib.pl#L2069-L2098
