### ISSUE TITLE
Virtualmin -> Scheduled Backups

### ISSUE THREAD

**Issue by qooob** [webmin/webmin#220]
When you go to Virtualmin->Scheduled Backups in actions choose `backups` and then do `backup in background` or other option, after it's sent to bg and returns a message, return button returns you _to the list of virtual servers_ - which is wrong. It should be: `/virtual-server/list_sched.cgi`.

**Comment by jcameron** [comment]
Thanks - I'll fix this in the next Virtualmin release.
