### ISSUE TITLE
Held package still showing 

### ISSUE THREAD

**Issue by kenara** [webmin/webmin#2205]
On Ubuntu 22, a package was listed under available updates that I actually wished to hold. So I called `sudo apt-mark hold <package>` and now I have this, 
![image](https://github.com/webmin/webmin/assets/4996484/5e51e34b-22b5-4274-821e-18167433c9a0)
that won't go away, even though clicking on the link does show this:

![image](https://github.com/webmin/webmin/assets/4996484/ed53dfff-ce1c-43ba-953e-dec23cc526c8)

Maybe it will reset when I restart the machine one of these days... :-)

**Comment by jcameron** [comment]
Can you post the output from `dpkg --get-selections` on your system? That is what Webmin uses to find held packages..

**Comment by kenara** [comment]
So, the package I wanted to hold is Google Chrome, and it's right there:

gnupg-l10n                                      install
gnupg-utils                                     install
google-chrome-stable                            hold
gpg                                             install
gpg-agent                                       install

... but `Package updates` has just now been updated! Did `dpkg --get-selections` do that? Weird!


Jun 24, 2024, 22:32 by ***@***.***:

**Comment by jcameron** [comment]
No running `dpkg --get-selections` , but there is some caching in Webmin of available packages, so if you just added a hold it may not be visible right away.

**Comment by kenara** [comment]
Makes sense.. sorry for the disruption!
