### ISSUE TITLE
Error removing packages in FreeBSD 10.1

### ISSUE THREAD

**Issue by jwhulette** [webmin/webmin#221]
![pkg_files](https://cloud.githubusercontent.com/assets/4930051/7991425/04044654-0ac6-11e5-962c-ed3a37576bc6.jpeg)
I can install package fine with Webmin but trying to uninstall results in an error.

![pkg_delete_error](https://cloud.githubusercontent.com/assets/4930051/7991365/ab8ec102-0ac5-11e5-8fa2-9ddddb8dbcb3.jpeg)
![pkg_info](https://cloud.githubusercontent.com/assets/4930051/7991364/ab8ebe1e-0ac5-11e5-9f91-1aa795cbca4e.jpeg)

**Comment by jcameron** [comment]
On the main page of the Software Packages module, which package management system does it show your system is using?

**Comment by jwhulette** [comment]
![pkg_conf](https://cloud.githubusercontent.com/assets/4930051/8006015/cb9d9052-0b5d-11e5-873d-00c184652a96.jpeg)

**Comment by jcameron** [comment]
If you login to your system as `root` and run `pkg delete nginx` , does that remove the package, or display an error?

**Comment by jwhulette** [comment]
It removes the package.

**Comment by jcameron** [comment]
Ok, I see the but that causes this now - it will be fixed in the next Webmin release.
