### ISSUE TITLE
No useable contacts on the website and the forum registration/password recovery does not work for me

### ISSUE THREAD

**Issue by slrslr** [webmin/webmin#2213]
Hello,

I am unable to find contact on a virtualmin.com webmaster. On the forum is a contact link leading to https://www.virtualmin.com/contact/?theme=light

yet beside single non technical related email i am unable to find working contact. Please forward this to appropriate person who is responsible for managing the Virtualmin forum.

I have registered on the forum, username ([mentioned here](https://bin.disroot.org/?436e63c5a2890bf6#7ptouGF7cQYVZ3UccBjVX7ebgjJZfNjvevpuSaZyRZhd))
and have not received an email to the email address associated with that username. And 2 password resets not received email either. I have found an account at https://www.virtualmin.com/account/signin/ yet receive no email from password reset page.

Please activate me manually and fix the issue, ideally also adding contacts to a linked web page. If you need some private detail from me, please kindly point me to a contact where i can tell it in private.

Thank you

**Comment by iliajie** [comment]
> yet beside single non technical related email i am unable to find working contact. Please forward this to appropriate person who is responsible for managing the Virtualmin forum.

I'm here! What's up?

> and have not received an email to the email address associated with that username.

I just ran a test, trying to register using my Proton Mail account, and everything worked just fine. Proton Mail is super strict about mail quality, so if it was delivered without flags to Proton Mail, it should be delivered anywhere else!

> I have found an account at https://www.virtualmin.com/account/signin/ yet receive no email from password reset page.

I think the real issue is with your local mail configuration for your domain. Check the local logs for records related to virtualmin.com.

> If you need some private detail from me, please kindly point me to a contact where i can tell it in private.

If you have further questions or need additional help you can email me at ilia at virtualmin dot dev.

**Comment by slrslr** [comment]
> I'm here! What's up?

And? The mine mentioned contact page contains the link to this issue tracker as the place to ask questions? I do not think so.

**Comment by iliajie** [comment]
> I do not think so.

You don't think the Virtualmin Community forum is a good place to ask questions?

**Comment by slrslr** [comment]
No, the thing I have mentioned in my sentence. I guess that it remains unfixed.
