### ISSUE TITLE
Status of XSS vulnerability

### ISSUE THREAD

**Issue by Orphx** [webmin/webmin#2218]
Hello all,
It seems there is an XSS vulnerability reported for Webmin, see https://github.com/Acklee/webadmin_xss/blob/main/xss.md.
I just wanted to see if the Webmin team is aware of the issue, and if it is already solved or not, as there is no reference to something like this in the releases after 2.105.
Thank you.

**Comment by chris001** [comment]
Good find.  Probably the input should be post-processed so that it won't execute as code in the OS as the root user.

**Comment by iliajie** [comment]
> It seems there is an XSS vulnerability

Can you still reproduce this issue by following the given steps?

**Comment by jcameron** [comment]
Seems like the user can only XSS themselves though?

**Comment by jcameron** [comment]
Also, this was fixed in https://github.com/webmin/webmin/commit/83de10b7c2fb196c6f93a048e6ace489da2ff55b

**Comment by chris001** [comment]
FYI [the steps to reproduce](https://github.com/Acklee/webadmin_xss/blob/main/xss.md) is failing to display the sample code in Step 6 properly. The full steps are:
```
Date : 23th Dec 2023
Step 1 : Go to admin login
Step 2 : Navigate to webmin tab.
Step 3 : Go to System.
Step 4 : Go to Scheduled Cron Jobs.
Step 5 : Create a new scheduled cron job.
Step 6 : write the payload( "><img src=# onerror=prompt(1)> ) in Execute cron job as 
Step 7 : then click create
XSS will execute.
```

**Comment by jcameron** [comment]
Yes, that commit fixes the issue

**Comment by 0R-gb** [comment]
Mentioning the fixed CVE in Changelog might prevent such issues :-)

**Comment by iliajie** [comment]
> Mentioning the fixed CVE in Changelog might prevent such issues :-)

I agree. Though we miss it sometimes. I hoped that community members could help with that, particularly by submitting a PR to:

https://github.com/webmin/webmin.com/blob/main/content/security.md
