### ISSUE TITLE
Dashboard package update - wrong URL

### ISSUE THREAD

**Issue by shoulders** [webmin/webmin#2219]
|  SYSTEM INFORMATION||
|----------------------|---------------------------|
|  OS type and version |     Ubuntu Linux 22.04.4     |
|  Webmin version      |     2.111      |
|  Usermin version     |     2.010     |
|  Virtualmin version  |     7.20.1       |
|  Theme version       |     21.10      |
|  Package updates     |      26  package updates are available   |

### the background

in the dashboard you have this

![image](https://github.com/user-attachments/assets/18518e9c-794f-48c2-8b04-49c2123e31ac)

- the link for package updates are available is `https://server.example.com:10000/package-updates/index.cgi?mode=updates`
- it then said `5 of which are security updates` and the link was `https://server.example.com:10000/package-updates/index.cgi?mode=updates`

### the issue

The link for security updates should be `https://server.example.com:10000/package-updates/index.cgi?mode=security`

### additional

- I had just updated from 7.10.x to 7.20.1
- the reason i don't have the second part of the link in the image is that I refreshed the template cache and now the security updates are either no longer flagged, or they got updated when I did some updates earlier and the theme had just not refreshed itself
- force system information update did not change this either.

**Comment by iliajie** [comment]
Hello,

> The link for security updates should be `https://server.example.com:10000/package-updates/index.cgi?mode=security`

This is one link that directs to the package updates page, displaying both types of updates. Besides, we cannot make the link appear as one link and tell it to open different tabs depending on which part of the link is clicked, as this is a bad practice.

Thanks for the heads up anyway!
