### ISSUE TITLE
DHCP Server - Hosts and Host Groups

### ISSUE THREAD

**Issue by jmendes84** [webmin/webmin#2221]
Hi, Is it possible to have in the DHCP Server Section Under Host and Host Groups a seperate column for descriptions? If not is this something that can be introduced in a next release? It helps to be able to see the Host Name and Host Descriptions Side by Side along with the Hardware Addess and Hostname/IP.

**Comment by jmendes84** [comment]
Thank you for the update but I was hoping this was going to be implemented with the host name and the description being in seperate columns.

**Comment by jcameron** [comment]
Sure, I'll do that in the next release.

**Comment by jmendes84** [comment]
Thank you.
