### ISSUE TITLE
Real time monitoring not working since Upgrade to 2.200 on three different systems

### ISSUE THREAD

**Issue by nemihome** [webmin/webmin#2222]
Hello,

I upgraded to 2.2 today on three VPS systems and on all of them real time monitoring of CPU, network speed, memory, ... is deas. I also checked the setting in dashboard and there are two settings less than in the old version
![Screenshot 2024-07-22 085433](https://github.com/user-attachments/assets/a5ff6f17-15b6-4b53-ab59-15ac9df276f7)

**Comment by flatterrich** [comment]
same problem here

**Comment by iliajie** [comment]
To be clear, stats cannot be collected when opening Webmin instance using the Servers Index module, i.e., with `/link.cgi/` .. although they can still be displayed.

If it's not the case try force reloading the browser's page or using another browser or an incognito tab, and/or try to force restart Webmin by running:

```bash
/etc/webmin/restart-by-force-kill
```

See if this helps to address the issue.

If it's still an issue, check for additional details in `/var/webmin/modules/authentic-theme`.

**Comment by nemihome** [comment]
Restart did not help that was already done at installation. In the them folder I have found log entries:
```
Can't locate JSON.pm in @INC (you may need to install the JSON module) (@INC entries checked: /usr/share/webmin/vendor_perl /usr/share/webmin /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.38.2 /usr/local/share/perl/5.38.2 /usr/lib/x86_64-linux-gnu/perl5/5.38 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl-base /usr/lib/x86_64-linux-gnu/perl/5.38 /usr/share/perl/5.38 /usr/local/lib/site_perl) at /usr/share/webmin/authentic-theme/stats.pl line 12.
BEGIN failed--compilation aborted at /usr/share/webmin/authentic-theme/stats.pl line 12.
```
Is there a change concerning this?

**Comment by nemihome** [comment]
sudo apt install libjson-perl seems to fix it.

**Comment by iliajie** [comment]
> Is there a change concerning this?

Ah, I think I know why this might be happening. What distro are you on?

**Comment by nemihome** [comment]
Ubuntu 24.04

**Comment by iliajie** [comment]
And how did you install Webmin on your Ubuntu 24.04?

**Comment by nemihome** [comment]
Initially? Currently just running the upgrade but initially it is installed via apt but that's a while ago.

**Comment by iliajie** [comment]
We will also try using `JSON::XS` first if available using [this](https://github.com/webmin/authentic-theme/commit/42a4a2569ad6e0d2fee7709d2c62c801b96c4ee9) patch.

**Comment by ptasznikarium** [comment]
same issue on Ubuntu 22.04.4

seems to work again after 
`apt-get install libjson-pp-perl`
`systemctl restart webmin.service`

**Comment by Pr0sT69** [comment]
> sudo apt install libjson-perl seems to fix it in combination with a sudo service webmin restart.

that fixed it for me on Debian 12. thank you

**Comment by SylvainLegrand** [comment]
Too bad, nothing seems to work for me on ubuntu 20.04.6

**Comment by timler** [comment]
Same problem for me on Ubuntu 18.04 - installing `libjson-pp-perl` and restarting webmin didn't work for me either. Stats were working before the Webmin upgrade today.

I see this in the JS console:
```
VM694:1 WebSocket connection to 'wss://app-test.xelt.org:10000/authentic-theme/ws-589' failed: 
VM694:1 WebSocket connection to 'wss://app-test.xelt.org:10000/authentic-theme/ws-590' failed: 
VM694:1 WebSocket connection to 'wss://app-test.xelt.org:10000/authentic-theme/ws-591' failed: 
VM694:1 WebSocket connection to 'wss://app-test.xelt.org:10000/authentic-theme/ws-592' failed: 
VM694:1 WebSocket connection to 'wss://app-test.xelt.org:10000/authentic-theme/ws-593' failed: 
```

I believe it's related because when I de-active the stats the errors disappear.

These stats are very useful, so it would be great to get them fixed, even though I know my server is reaaaaally sold. Thank you!

**Comment by iliajie** [comment]
Is there anything useful logged in `/var/webmin/modules/authentic-theme`?

>These stats are very useful, so it would be great to get them fixed, even though I know my server is reaaaaally sold. 

Can you try the following:

```
webmin patch https://github.com/webmin/webmin/commit/11ae3
webmin patch https://github.com/webmin/authentic-theme/commit/cb60e
systemctl restart webmin
```

**Comment by iliajie** [comment]
> Too bad, nothing seems to work for me on ubuntu 20.04.6

What isn't working for you exactly?

**Comment by oreeke** [comment]
But I ran into the following problem

Dashboard for the first time
![屏幕截图 2024-07-23 130829](https://github.com/user-attachments/assets/a081c8f5-6cee-48d8-8d8d-d45c64f35434)
After system information automatic refresh
![屏幕截图 2024-07-23 130813](https://github.com/user-attachments/assets/6ab1e869-5445-474d-8e09-d356e2cbe6e4)

**Comment by timler** [comment]
> webmin patch https://github.com/webmin/webmin/commit/11ae3
> webmin patch https://github.com/webmin/authentic-theme/commit/cb60e
> systemctl restart webmin

Thanks @iliajie (and obviously I meant old not sold :-P)

Unfortunately that didn't fix it for me on my test server - I got an error on the 2nd patch. But it did run successfully on my prod server where I accidentally run the patches in the wrong order. The other difference with the two servers is that test is running theme version 21.20.2 and prod is still on 21.20.1

Output from the test server:

```
$ sudo webmin patch https://github.com/webmin/webmin/commit/11ae3
Patch applied successfully to:
  bin/patch

$ sudo webmin patch https://github.com/webmin/authentic-theme/commit/cb60e
Patch failed: Hmm...  Looks like a unified diff to me...
The text leading up to this was:
--------------------------
|From cb60e14cfc370173751b02ed54f8ccf922d24573 Mon Sep 17 00:00:00 2001
|From: Ilia Ross <ilia@ross.gdn>
|Date: Mon, 22 Jul 2024 13:40:44 +0300
|Subject: [PATCH] Update JSON dependency to JSON::PP
| https://github.com/webmin/webmin/issues/2222
|
|---
| stats.pl | 2 +-
| 1 file changed, 1 insertion(+), 1 deletion(-)
|
|diff --git a/stats.pl b/stats.pl
|index 6d8177854..f1f4543ed 100755
|--- a/stats.pl
|+++ b/stats.pl
--------------------------
patching file stats.pl
Using Plan A...
Hunk #1 FAILED at 9.
1 out of 1 hunk FAILED -- saving rejects to file stats.pl.rej
done

$ sudo systemctl restart webmin
```

**Comment by UweLoyal** [comment]
Also same Bug on Raspberry Pi4B with Raspbian GNU/Linux 10 (buster)

**Comment by iliajie** [comment]
> Unfortunately that didn't fix it for me on my test server

Is your test server running Rocky or Alma?

> The other difference with the two servers is that test is running theme version 21.20.2 and prod is still on 21.20.1

In this case, it's expected to fail because theme version 21.20.2 already includes it.

Thanks for the detailed response.

> Also same Bug on Raspberry Pi4B with Raspbian GNU/Linux 10 (buster)

You could install the latest version of the theme using **Theme Configuration** page to fix this issue or wait a few days before Webmin 2.201 is out.

**Comment by UweLoyal** [comment]
pi@RASPBERRY-Pi4B-UL:~ $ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

**Comment by timler** [comment]
> Is your test server running Rocky or Alma?

```
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.6 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

Thanks for the explanation about why the 2nd patch didn't work

**Comment by iliajie** [comment]
> VERSION="18.04.6 LTS (Bionic Beaver)"

Does this server have the `patch` command installed?



> Thanks for the explanation about why the 2nd patch didn't work.

You're welcome!




> I had a 3rd server which is the same setup on the theme version 21.20.1 - I ran the patch commands successfully and saw the stats when I reloaded the Webmin Dashboard.

> I then upgraded to 21.20.2 and the stats disappeared again.

That's very interesting! This shouldn't happen!

What is the output of the following command on that server:

```
dpkg -l | grep ii | grep libjson
```

and

```
perl -e "use JSON::XS"
```

**Comment by timler** [comment]
Gosh... all 3 servers had some wildly varying responses to those commands. I inherited these servers about two weeks ago, so their history is unknown

1st (test) server:
```
$ which patch
/usr/bin/patch

$ dpkg -l | grep ii | grep libjson
ii  libjson-c3:amd64                       0.12.1-1.3ubuntu0.3                             amd64        JSON manipulation library - shared library
ii  libjson-perl                           2.97001-1                                       all          module for manipulating JSON-formatted data
ii  libjson-pp-perl                        2.97001-1                                       all          module for manipulating JSON-formatted data (Pure Perl)
ii  libjson-xs-perl                        3.040-1                                         amd64        module for manipulating JSON-formatted data (C/XS-accelerated)

$ perl -e "use JSON::XS"
```

2nd (prod) server - the one where stats are working:
```
$ which patch
/usr/bin/patch

$ dpkg -l | grep ii | grep libjson
ii  libjson-c3:amd64                       0.12.1-1.3ubuntu0.3                             amd64        JSON manipulation library - shared library

$ perl -e "use JSON::XS"
Can't locate JSON/XS.pm in @INC (you may need to install the JSON::XS module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.26.1 /usr/local/share/perl/5.26.1 /usr/lib/x86_64-linux-gnu/perl5/5.26 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.26 /usr/share/perl/5.26 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at -e line 1.
BEGIN failed--compilation aborted at -e line 1.
```

3rd (prod db) server:

```
$ which patch
/usr/bin/patch

$ dpkg -l | grep ii | grep libjson
ii  libjson-c3:amd64                       0.12.1-1.3ubuntu0.3                             amd64        JSON manipulation library - shared library

$ perl -e "use JSON::XS"
Can't locate JSON/XS.pm in @INC (you may need to install the JSON::XS module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.26.1 /usr/local/share/perl/5.26.1 /usr/lib/x86_64-linux-gnu/perl5/5.26 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.26 /usr/share/perl/5.26 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at -e line 1.
BEGIN failed--compilation aborted at -e line 1.
```

**Comment by iliajie** [comment]
Do the second and third servers have the same patches applied? Do both of them work, fail, or .. ?

**Comment by timler** [comment]
1st server:

- theme version 21.20.2
- patches applied, 2nd patch failed (as expected)
- stats not working

2nd server:

- theme version 21.20.1
- patches applied, both worked
- stats working

3rd server:

- theme version 21.20.2
- patches applied before upgrading to 21.20.2, both worked
- stats worked before upgrading to 21.20.2

**Comment by iliajie** [comment]
> 1st server:
> 
> * theme version 21.20.2
> * patches applied, 2nd patch failed (as expected)
> * stats not working

Could you please install the latest nightly version using:

```
wget https://builds.webmin.dev/webmin-latest.deb
apt-get install ./webmin-latest.deb
```

.. and let me know if that fixes the issue for you on this server?

**Comment by UweLoyal** [comment]
pi@RASPBERRY-Pi4B-UL:~ $ dpkg -l | grep ii | grep libjson
ii  libjson-c3:armhf                     0.12.1+ds-2+deb10u1                      armhf        JSON manipulation library - shared library
ii  libjson-glib-1.0-0:armhf             1.4.4-2                                  armhf        GLib JSON manipulation library
ii  libjson-glib-1.0-common              1.4.4-2                                  all          GLib JSON manipulation library (common files)
ii  libjson-perl                         4.02000-1                                all          module for manipulating JSON-formatted data
ii  libjson-pp-perl                      4.02000-1                                all          module for manipulating JSON-formatted data (Pure Perl)
ii  libjson-xs-perl                      3.040-1+b1                               armhf        module for manipulating JSON-formatted data (C/XS-accelerated)

--------------------------

pi@RASPBERRY-Pi4B-UL:~ $ perl -e "use JSON::XS"
pi@RASPBERRY-Pi4B-UL:~ $

**Comment by andrewbernard** [comment]
This was an issue with 2.200 on my Raspberry Pi 5's running Debian 12. Installing the perl library as mentioned here above fixed it nicely.

**Comment by UweLoyal** [comment]
![image](https://github.com/user-attachments/assets/4255a6a0-d97c-46f3-a5c5-73ed96a30739)

Has this something to do with the Bug?

**Comment by iliajie** [comment]
Can anyone seeing this issue please try:

```
wget https://builds.webmin.dev/webmin-latest.deb
apt-get install ./webmin-latest.deb
/etc/webmin/restart && /etc/webmin/restart-by-force-kill
```

**Comment by SylvainLegrand** [comment]
@iliaross 

On ubuntu 20.04.6 the webmin-latest.deb seems to work.

;) Thanks.

**Comment by iliajie** [comment]
Thanks! Very good to know!

**Comment by iliajie** [comment]
Though, I'd like others to also try it and see how it goes, particularly those folks with Raspberry Pi ..

**Comment by UweLoyal** [comment]
pi@RASPBERRY-Pi4B-UL:~ $ sudo apt-get install ./webmin-latest.deb
Paketlisten werden gelesen... Fehler!
E: Unterprozess Popen hat Fehlercode zurückgegeben (2)
E: Encountered a section with no Package: header
E: Problem with MergeList /home/pi/webmin-latest.deb
E: Die Paketliste oder die Statusdatei konnte nicht eingelesen oder geöffnet werden.

**Comment by iliajie** [comment]
Try this instead then:


```
su 
cd /tmp
wget https://builds.webmin.dev/webmin-latest.deb
apt-get install ./webmin-latest.deb
/etc/webmin/restart && /etc/webmin/restart-by-force-kill
```

**Comment by UweLoyal** [comment]
root@RASPBERRY-Pi4B-UL:/tmp# apt-get install ./webmin-latest.deb
Paketlisten werden gelesen... Fehler!
E: Unterprozess Popen hat Fehlercode zurückgegeben (2)
E: Encountered a section with no Package: header
E: Problem with MergeList /tmp/webmin-latest.deb
E: Die Paketliste oder die Statusdatei konnte nicht eingelesen oder geöffnet werden.
root@RASPBERRY-Pi4B-UL:/tmp#

**Comment by iliajie** [comment]
:--) Then simply try installing the latest development version of the theme from the Theme Configuration page:

<img width="1427" alt="image" src="https://github.com/user-attachments/assets/d771e64c-aac6-471f-b8cb-6b09e4b8df9a">

**Comment by UweLoyal** [comment]
I have only this side
![image](https://github.com/user-attachments/assets/3a38a86b-d06f-40ac-93cb-1dd120eb7297)

**Comment by iliajie** [comment]
> I have only this side

Search for "Theme Config" in the drop down as shown in the screenshot ..

**Comment by UweLoyal** [comment]
![image](https://github.com/user-attachments/assets/f5e50cd9-5031-4e66-931d-312bc6b31acf)

![image](https://github.com/user-attachments/assets/e5edacb7-57c7-4186-9221-bb21d1351a69)

![image](https://github.com/user-attachments/assets/83944014-c56e-4470-875d-75e4b3142300)

**Comment by iliajie** [comment]
Try instead clicking the palette icon at the bottom of the menu to get to the **Theme Configuration** page; I think it will be easier, e.g.:

<img width="256" alt="image" src="https://github.com/user-attachments/assets/d076db5b-34ac-4ac4-822a-6d77d6d0e36f">

**Comment by UweLoyal** [comment]
![image](https://github.com/user-attachments/assets/974fb4a0-f7e7-478e-bf80-ebfa1e6667fa)

Works, but no effect, still no page-update

**Comment by UweLoyal** [comment]
Still no effect

**Comment by iliajie** [comment]
> The funny thing is, systemtime is updated.

What's so funny about it?

> Still no effect !

Do you have theme version 21.20.3 installed? If you do and are still getting the issue, what is being logged to `/var/webmin/modules/authentic-theme` after Webmin was restarted and the page was reloaded?

**Comment by UweLoyal** [comment]
I selected install actual beta and it installed 21.20.2

**Comment by iliajie** [comment]
> I selected install actual beta and it installed 21.20.2

There is already a new 21.20.3 release that you should try instead.

**Comment by UweLoyal** [comment]
Still no effect.
Any Logfile (name?) ?

**Comment by timler** [comment]
@iliaross Thank you so much - it has worked for me and all stats are visible again

**Comment by iliaross** [comment]
> @iliaross Thank you so much - it has worked for me and all stats are visible again

I'm very glad to hear that! Thanks for the feedback!

> Any Logfile (name?) ?

Yes, related logs are located in `/var/webmin/modules/authentic-theme` directory and should look like `stats-server-NUM.log` .. You need to check for the latest file in the directory .. Actually it would be easier just to pre-delete all files before restarting Webmin and reloading the browser's page, e.g.:

```
rm -f /var/webmin/modules/authentic-theme/stats-server-*
```

**Comment by UweLoyal** [comment]
Funny, no Logfiles !

root@RASPBERRY-Pi4B-UL:/var/webmin/modules/authentic-theme# ls -l
insgesamt 36
-rw-r--r-- 1 root root 24488 Jul 23 19:17 combined-system-info-pi
-rw-r--r-- 1 root root    13 Jul 23 18:51 software+latest
-rw-r--r-- 1 root root   654 Jul 23 18:52 version-theme-development
-rw-r--r-- 1 root root   654 Jul 23 18:51 version-theme-stable
root@RASPBERRY-Pi4B-UL:/var/webmin/modules/authentic-theme#

**Comment by UweLoyal** [comment]
![image](https://github.com/user-attachments/assets/f1246c34-e9b1-4a79-a82c-755551a34c74)

**Comment by iliajie** [comment]
You should check the browser's console to get more details and see what's going on. Generally, stats are activated by calling the `stats.cgi` file.

Also, I'd suggest trying another browser, with all extensions disabled and seeing what you get.

**Comment by UweLoyal** [comment]
stats.cgi is loaded with Status 200.
![image](https://github.com/user-attachments/assets/29ae9325-9c41-45bf-8a0d-40eb6779852f)

With iPhone and Safari also no Onlinemonitoring!

What's about this error message
![image](https://github.com/user-attachments/assets/1c11e7ab-b15e-4a6f-83ff-8fb5ffa9d50b)

**Comment by iliajie** [comment]
> <img width="1453" alt="image" src="https://github.com/user-attachments/assets/197e9ae8-5f3e-4c16-b55b-5fb6397ccfe3">

I wonder what happens if you try to open the Terminal module?

Also:

  1. Have you tried using `IP:10000` to directly connect to your instance?
  2. Have you tried using another browser like Firefox or Brave?

Either way, I think there is a problem with the network connection between your device and the Raspberry Pi. A firewall or proxy might be interfering with the WebSocket connection. Not sure. But I don't think it's a Webmin issue.

**Comment by UweLoyal** [comment]
1. Port is 10000
2. I tested with different Browser's

Before Update all works fine!
The Problems came after Update.

**Comment by iliajie** [comment]
> So I think the connection is not the problem.

What about Terminal module? Does it work just fine or it also cannot connect?

**Comment by UweLoyal** [comment]
![image](https://github.com/user-attachments/assets/9814ca96-8358-4d43-a182-e356f9d52e77)

Works !

**Comment by UweLoyal** [comment]
A little Problem, Pi is in a private Network!
Any idea?

Mit freundlichen Grüßen

Uwe Loyal
Am 24. Juli 2024, 10:23 +0200 schrieb Ilia Ross ***@***.***>:

**Comment by oreeke** [comment]
@UweLoyal 
I'm having the same issue, but after I turn both options off and back on and clear the cache, it works, don't know what's going on..
![2024-07-24 175450](https://github.com/user-attachments/assets/7c92cefd-d383-4534-bb55-7c31960207ef)

**Comment by UweLoyal** [comment]
No effect on my system, but a good idea!

Mit freundlichen Grüßen

Uwe Loyal
Am 24. Juli 2024, 12:04 +0200 schrieb OREEkE ***@***.***>:

**Comment by oreeke** [comment]
@UweLoyal 
Are you using the latest hotfix? I did it after the update.
Webmin 2.201
Authentic theme 21.20.3

**Comment by UweLoyal** [comment]
Webmin 2.200
Theme 21.20.3

New Version of Webmin isn‘t shown, how can I get the new version?

Mit freundlichen Grüßen

Uwe Loyal
Am 24. Juli 2024, 12:40 +0200 schrieb OREEkE ***@***.***>:

**Comment by oreeke** [comment]
@UweLoyal 
It should show up in the 'Software Package Updates'
Maybe try 'Refresh Available Packages'

**Comment by UweLoyal** [comment]
Nothing shown

Mit freundlichen Grüßen

Uwe Loyal
Am 24. Juli 2024, 12:57 +0200 schrieb OREEkE ***@***.***>:

**Comment by iliajie** [comment]
> New Version of Webmin isn‘t shown, how can I get the new version?

For now, you can install nightly by running:

```
cd /tmp
wget -O webmin-latest.deb https://download.webmin.dev/webmin-latest.deb
apt-get install ./webmin-latest.deb
systemctl restart webmin
```

**Comment by UweLoyal** [comment]
This is not unstable, see above

Mit freundlichen Grüßen

Uwe Loyal
Am 24. Juli 2024, 13:08 +0200 schrieb Ilia Ross ***@***.***>:

**Comment by iliajie** [comment]
Webmin 2.201 is out, and it fixes the original issue!

If anyone still encounters problems after installing Webmin 2.201, please feel free to open a new ticket!
