### ISSUE TITLE
Terminal not working as root since upgrade to 2.200

### ISSUE THREAD

**Issue by fufu65** [webmin/webmin#2223]
Hi,
after upgrading to 2.200, terminal (Tools -> Terminal) runs as Webmin login user and not as root (even trying to force the user in the options).
Trying sudo su: "(user) is not in the sudoers file. This incident will be reported."
All this on 3 Ubuntu 22.04.4 LTS server installations, upgrading from Webmin 2.111.
On 2 of these servers there is also issue #2222.

**Comment by adzmailru** [comment]
I confirm (Ubuntu 22.04.4 LTS)))) I rolled back the upgrade and am waiting for corrections. It was a bad upgrade attempt)))

**Comment by iliajie** [comment]
Hello,

This is expected behavior.

You would either need to log in as `root`, use `sudo`, or disable this new limitation in **Webmin ⇾ Webmin Users: Edit Webmin User / File Manager: Module Access Control** page.

**Comment by adzmailru** [comment]
alex@wgserver:~$ sudo reboot
[sudo] password for alex: 
alex is not in the sudoers file.  This incident will be reported.

**Comment by iliajie** [comment]
Tell me more about user `alex` on your system, and how do you use it to login to Webmin.

**Comment by adzmailru** [comment]
member of:
root
sudo
......

**Comment by iliajie** [comment]
Well, alright, then just use the third option I suggested in my initial comment ..

**Comment by adzmailru** [comment]
I understand that dancing with a tambourine is sacred. Pls, just make a normal upgrade))))

**Comment by qc-1998** [comment]
Same problem here - Multiple systems from Raspberri Pi's to Intel, AMD and ARM servers running Ubuntu Server 20.04, 22.04 etc'.

When I SSH to the system I can sudo with username 'qcadmin'.
In Webmin Terminal I get an error.
Attached example from a random Ubuntu test server - Look at the output of 'groups' and 'sudo' commands.

Sample Webmin terminal output:
---
```

 qcadmin@qcdh1:~$ whoami
 qcadmin
 qcadmin@qcdh1:~$ sudo apt update
 [sudo] password for qcadmin: 
 Sorry, user qcadmin is not allowed to execute '/usr/bin/apt update' as root on qcdh1.
 qcadmin@qcdh1:~$ groups
 qcadmin
 qcadmin@qcdh1:~$ 

```
---

Sample SSH:
---

```
 qcadmin@qcdh2:~$ whoami
 qcadmin
 qcadmin@qcdh2:~$ sudo apt update
 [sudo] password for qcadmin:
 Hit:1 http://il.archive.ubuntu.com/ubuntu focal InRelease
 Get:2 https://apt.syncthing.net syncthing InRelease [15.1 kB]
 Get:3 http://il.archive.ubuntu.com/ubuntu focal-updates InRelease [128 kB]
 ... 
 All packages are up to date.
 qcadmin@qcdh2:~$ groups
 qcadmin adm cdrom sudo dip plugdev lxd docker SyncThingBackup
 qcadmin@qcdh2:~$ sudo -l
 Matching Defaults entries for qcadmin on qcdh2:
     env_reset, mail_badpass,
     secure_path=/usr/local/sbin\:/usr/local/bin\:/usr/sbin\:/usr/bin\:/sbin\:/bin\:/snap/bin
 
 User qcadmin may run the following commands on qcdh2:
     (ALL : ALL) ALL
     (root) NOPASSWD: /usr/lib/sftp-server


```
---

**Comment by iliajie** [comment]
> When I SSH to the system I can sudo with username 'qcadmin'. In Webmin Terminal I get an error. Attached example from a random Ubuntu test server - Look at the output of 'groups' and 'sudo' commands.

Confirmed! Thanks!


> 1. Instructions are unclear - What exactly should be done to restore expected (previous) behavior?

Disable this new limitation in **Webmin ⇾ Webmin Users: Edit Webmin User / Terminal: Module Access Control** page:

<img width="1111" alt="image" src="https://github.com/user-attachments/assets/ed1644f9-6d41-4c77-8972-1ddf9a6b805c">

> 2. Is there any documentation regarding configuring this new 'feature'?

Not yet, sorry.

> 3. Can these changes be scripted / automated? Some of us have many affected systems so manual change is not a good solution.

Yes, you could add to `/etc/webmin/xterm/root.acl` file `sudoenforce=0` option.

> 4. Why would an update change this behavior in the first place? Can you point us to the discussion / feature request that resulted in this change?

Yes, there you go:

https://forum.virtualmin.com/t/feedback-from-a-first-time-user/127250/37?u=ilia

**Comment by iliajie** [comment]
> You might need to end the current terminal session (type 'exit' in terminal).

Yes, you just need to exit and re-open Terminal module. No need to restart Webmin!

**Comment by iliajie** [comment]
> If this fails for some reason, you can restart webmin service via SSH or from Tools->Command Shell (i.e. 'systemctl restart webmin.service' under systemd)

You absolutely cannot restart Webmin from the Command Shell module reliably with the give command. It's not designed for this. Use Webmin Configuration page to restart Webmin.

**Comment by iliajie** [comment]
> Is restarting webmin.service from SSH (or from the local command terminal) safe?

From SSH - yes, only by using `systemctl restart webmin` command, not terminating the process.



> It might not be a good idea, but it still works. ;-)

Yes, it "works" because the Webmin service enters the failed state, and later gets automatically restarted by _systemd_.

**Comment by n-hdev** [comment]
> > 
>     2. Is there any documentation regarding configuring this new 'feature'?
> 

Of course not, these last few years the iliajie approach to software development has often made new releases, of what used to be the best, virtually a game of Russian roulette. You're best waiting a few weeks before upgrading. Half arsed if any testing, you got it. Key but undocumented changes, despite a release notes page, sure. Snarky replies to bugs and hacky workarounds, yup that's what you get now. Not sure why JC still allows the guy to work on his project.

**Comment by jcameron** [comment]
To be fair, the only reason this didn't work was due to a bug in webmin that's been there for at least 15 years!

**Comment by 3ftomi** [comment]
> Disable this new limitation in **Webmin ⇾ Webmin Users: Edit Webmin User / Terminal: Module Access Control** page:

This is the exact path for those, who can't find it (like me):
Webmin ⇾ Webmin Users: ⇾ Edit Webmin User ⇾ **Available Webmin modules ⇾** Terminal (: Module Access Control) **⇾ Enforce sudo-only privileges: ⇾ No**

Anyway, thanks for the info.

Please update change logs on webmin.com.
And giving some tips for those who coming here just because this new _feature_ (maybe a link to the answer here?). I don't think "Fix to allow disabling the newly introduced enforcement of sudo-capable logins in the Terminal module" will be helpfull enough.

Thanks and have a nice day!

**Comment by iliajie** [comment]
> Please update change logs on webmin.com.

We will! Thanks! I have also [updated docs](https://github.com/webmin/webmin.com/commit/350a590bdb9eb0eec9ccf8c62aa0f1bf01473b30) to mention it.

<img width="1426" alt="image" src="https://github.com/user-attachments/assets/b24028ef-35ac-4076-8e21-a59d9148d575">

**Comment by shoulders** [comment]
Thanks for all the info above.

The actual documentation page - https://webmin.com/docs/modules/terminal/

Is it worth adding why this was changed? nothing in-depth.

### Have I got this right:

- It is bad practice to the `root` account for regular admin operations and so this was changed to follow that paradigm.
- This new feature restricts the use of the `root` account through the virtual terminal in Webmin for all sudo users.
- Previously, all users with sudo rights when logging into Webmin got `root` access via the Terminal, this is bad practice and is security flaw that has now been fixed.

**Comment by shoulders** [comment]
I thinks this should be closed because:

- This is expected behavior.
  You would either need to log in as root, use sudo, or disable this new limitation in Webmin ⇾ Webmin Users: Edit Webmin User / Terminal: Module Access Control page.
- To be fair, the only reason this didn't work was due to a bug in webmin that's been there for at least 15 years!
   commit/fix = https://github.com/webmin/webmin/commit/c1f45d6d611db9bab39b69eb93151995a8337dce
- Update changelogs for other users, We will! Thanks! I have also [updated docs](https://github.com/webmin/webmin.com/commit/350a590bdb9eb0eec9ccf8c62aa0f1bf01473b30) to mention it.

**Comment by iliajie** [comment]
Thanks!

**Comment by mxdpeep** [comment]
> * Previously, all users with sudo rights when logging into Webmin got `root` access via the Terminal, this is bad practice and is security flaw that has now been fixed.

this rendered the use of Webmin on mobile to ZERO

**Comment by iliajie** [comment]
> this rendered the use of Webmin on mobile to ZERO

This is optional and can be reverted to the previous behavior as outlined in our documentation:

https://webmin.com/docs/modules/terminal/
