### ISSUE TITLE
show all of the bind software version number

### ISSUE THREAD

**Issue by shoulders** [webmin/webmin#2226]
|  SYSTEM INFORMATION||
|----------------------|---------------------------|
|  OS type and version |     Ubuntu Linux 22.04.4     |
|  Webmin version      |     2.111      |
|  Usermin version     |     2.010     |
|  Virtualmin version  |     7.20.1       |
|  Theme version       |     21.10      |
|  Package updates     |     All installed packages are up to date   |

### the issue

Bind seems to make updates quite often to the point/patch updates but the version number dispalyed only shows the major.minor (9.18) part of the version

![image](https://github.com/user-attachments/assets/9cdea7b1-8756-434a-bf25-b66561b89dcf)

![image](https://github.com/user-attachments/assets/0eda483e-9698-4136-a20a-d4addda6eccd)

### Proposed solution

Can you make it so the bind number show major.minor.patch (9.18.24)

![image](https://github.com/user-attachments/assets/df10c8df-ec03-49d3-97cf-8221f476efd8)

**Comment by jcameron** [comment]
Good suggestion, I'll make that change!
