### ISSUE TITLE
webmin "pollutes" /etc

### ISSUE THREAD

**Issue by Jerome-github** [webmin/webmin#223]
Hi.

I use etckeeper to version /etc.

I tried webmin and it appears it puts a lot of files in /etc, which pollutes the history.

A workaround would be to add /etc/webmin to /etc/.gitignore, or maybe just subdirectories, but there can be other reason to keep only for static config files.

There are other people bothered by this:

https://www.turnkeylinux.org/forum/support/20141206/another-webmin-issue
https://github.com/turnkeylinux/tracker/issues/284

This was reported to webmin [here](https://sourceforge.net/p/webadmin/feature-requests/181/).

Any news about this ?

Thanks.

**Comment by jcameron** [comment]
I'm not sure if I would really classify this as a bug in Webmin - it was just a design choice to use /etc/webmin to store data that gets frequently updated. I suppose it could go in /var/webmin, but it is kind of hard to change now without breaking backwards compatibility.

**Comment by swelljoe** [comment]
I have to agree on this one, actually. /var is for variable data. /etc is for configuration files (which don't change based on automated data collection, for example).

Though, I think Webmin already puts all logs in /var/webmin, by default.

**Comment by Jerome-github** [comment]
> I'm not sure if I would really classify this as a bug in Webmin - it was just a design choice to use /etc/webmin to store data that gets frequently updated. 

I'm no Unix guru, but AFAIK, this infringes the convention about /etc. No big deal for most people, but it is an (small) issue for /etckeeper users (it can be workedaround using .gitignore).

> I suppose it could go in /var/webmin, but it is kind of hard to change now without breaking backwards compatibility.

Maybe make the change optional ?

**Comment by jcameron** [comment]
I've started switching some non-config data stores to be under /var/webmin instead of /etc/webmin .

Are there particular directories under /etc/webmin that are the most problematic currently, in terms of size or update rate?

**Comment by Jerome-github** [comment]
According to the [Debian Handbook](https://debian-handbook.info/browse/stable/sect.filesystem-hierarchy.html), 

- /etc/: configuration files; 
- /var/: variable data handled by daemons. This includes log files, queues, spools, caches and so on. 

So anything that is generated by webmin should go to /var and /etc should contain only webmin configuration files (files that don't change on a regular basis).

/var has its own subdivisions, so depending on what the data is, it may have to go in different subdirectories in /var.

I don't see any /var/application_name directory, for instance. Would it be an issue to use /var/webmin ? I can't tell.

See following links for instance, and maybe have a look at /var on your own machines.

- http://www.tldp.org/LDP/Linux-Filesystem-Hierarchy/html/var.html
- http://linux.about.com/od/lsa_guide/a/gdelsa20.htm

Sorry for the hassle, but while you're at it, you might as well prevent the next "Webmin shouldn't write in /var/webmin" issue and avoid a second move.

**Comment by jcameron** [comment]
There should already be a /var/webmin directory, and for the next release new installs will write data under there instead of /etc/webmin.

**Comment by Jerome-github** [comment]
Great. Thanks.
