### ISSUE TITLE
Webmin Panel Fails to Load After VPS Reboot on Ubuntu 22.04

### ISSUE THREAD

**Issue by MmdBay** [webmin/webmin#2231]
## Description
I'm using Ubuntu 22.04 and I encounter an issue where the Webmin panel does not load after rebooting my VPS. To resolve this, I have to manually kill the default port 10000 and restart Webmin via systemctl.

## Steps to Reproduce
1.Reboot the VPS.
2.Attempt to access the Webmin panel.
3.Observe that the panel does not load.

## Workaround
Kill the process using the default port 10000.

```sudo lsof -i :10000```
```sudo kill <process_id>```

Restart Webmin service using systemctl.

```sudo systemctl restart webmin```

The Webmin panel loads successfully.

## Expected Behavior
The Webmin panel should load automatically after the VPS is rebooted without requiring manual intervention.

## Actual Behavior
The Webmin panel fails to load after a reboot and requires manual steps to restart the service and kill the default port.

## System Information
OS: Ubuntu 22.04
Webmin Version: 2.201

**Comment by jcameron** [comment]
What error do you get in your browser when you try to access port 10000 after a reboot?

**Comment by MmdBay** [comment]
I get this error, dear jcameron

This site can’t be reached <my_ip_vps> unexpectedly closed the connection.
Try:

Checking the connection
Checking the proxy and the firewall
Running Windows Network Diagnostics
ERR_CONNECTION_CLOSED

**Comment by MmdBay** [comment]
I get this error

```systemctl status webmin```

systemctl status webmin
● webmin.service - Webmin server daemon
     Loaded: loaded (/lib/systemd/system/webmin.service; enabled; vendor preset: enabled)
     Active: activating (start) since Sun 2024-07-28 18:18:36 CEST; 12s ago
Cntrl PID: 2196 (miniserv.pl)
      Tasks: 1 (limit: 2255)
     Memory: 28.0M
     CGroup: /system.slice/webmin.service
             └─2196 /usr/bin/perl /usr/share/webmin/miniserv.pl /etc/webmin/miniserv.conf

Jul 28 18:18:36 <my_host> systemd[1]: webmin.service: Scheduled restart job, restart counter is at 24.
Jul 28 18:18:36 <my_host> systemd[1]: Stopped Webmin server daemon.
Jul 28 18:18:36 <my_host> systemd[1]: Starting Webmin server daemon...
Jul 28 18:18:36 <my_host> perl[2196]: pam_unix(webmin:auth): authentication failure; logname= uid=0 euid=0 tty= ruser= rhost=  user=root
Jul 28 18:18:39 <my_host> webmin[2196]: Webmin starting

and journalctl

```journalctl -u webmin.service --since "5 minutes ago"```

-- Logs begin at Sun 2024-07-28 18:12:31 CEST, end at Sun 2024-07-28 18:15:34 CEST. --
Jul 28 18:12:39 <my_host> systemd[1]: Starting Webmin server daemon...
Jul 28 18:12:41 <my_host> perl[808]: pam_unix(webmin:auth): authentication failure; logname= uid=0 euid=0 tty= ruser= rhost=  user=root
Jul 28 18:12:42 <my_host> webmin[808]: Webmin starting
Jul 28 18:12:54 <my_host> miniserv.pl[808]: [28/Jul/2024:18:12:54 +0200] Failed to bind to port 10000 : Address already in use
Jul 28 18:12:54 <my_host> miniserv.pl[808]: [28/Jul/2024:18:12:54 +0200] Failed to bind to port 10000 : Address already in use
Jul 28 18:12:54 <my_host> miniserv.pl[808]: [28/Jul/2024:18:12:54 +0200] Could not listen on any ports
Jul 28 18:12:54 <my_host> systemd[1]: webmin.service: Control process exited, code=exited, status=1/FAILURE
Jul 28 18:12:54 <my_host> systemd[1]: webmin.service: Failed with result 'exit-code'.
Jul 28 18:12:54 <my_host> systemd[1]: Failed to start Webmin server daemon.
Jul 28 18:12:56 <my_host> systemd[1]: webmin.service: Scheduled restart job, restart counter is at 1.
Jul 28 18:12:56 <my_host> systemd[1]: Stopped Webmin server daemon.
Jul 28 18:12:56 <my_host> systemd[1]: Starting Webmin server daemon...
Jul 28 18:12:56 <my_host> perl[1803]: pam_unix(webmin:auth): authentication failure; logname= uid=0 euid=0 tty= ruser= rhost=  user=root
Jul 28 18:12:59 <my_host> webmin[1803]: Webmin starting
Jul 28 18:13:08 <my_host> miniserv.pl[1803]: [28/Jul/2024:18:13:08 +0200] Failed to bind to port 10000 : Address already in use
Jul 28 18:13:08 <my_host> miniserv.pl[1803]: [28/Jul/2024:18:13:08 +0200] Failed to bind to port 10000 : Address already in use
Jul 28 18:13:08 <my_host> miniserv.pl[1803]: [28/Jul/2024:18:13:08 +0200] Could not listen on any ports
Jul 28 18:13:08 <my_host> systemd[1]: webmin.service: Control process exited, code=exited, status=1/FAILURE
Jul 28 18:13:08 <my_host> systemd[1]: webmin.service: Failed with result 'exit-code'.
Jul 28 18:13:08 <my_host> systemd[1]: Failed to start Webmin server daemon.
Jul 28 18:13:11 <my_host> systemd[1]: webmin.service: Scheduled restart job, restart counter is at 2.
Jul 28 18:13:11 <my_host> systemd[1]: Stopped Webmin server daemon.
Jul 28 18:13:11 <my_host> systemd[1]: Starting Webmin server daemon...
Jul 28 18:13:11 <my_host> perl[1806]: pam_unix(webmin:auth): authentication failure; logname= uid=0 euid=0 tty= ruser= rhost=  user=root
Jul 28 18:13:13 <my_host> webmin[1806]: Webmin starting
Jul 28 18:13:23 <my_host> miniserv.pl[1806]: [28/Jul/2024:18:13:23 +0200] Failed to bind to port 10000 : Address already in use
Jul 28 18:13:23 <my_host> miniserv.pl[1806]: [28/Jul/2024:18:13:23 +0200] Failed to bind to port 10000 : Address already in use
Jul 28 18:13:23 <my_host> miniserv.pl[1806]: [28/Jul/2024:18:13:23 +0200] Could not listen on any ports
Jul 28 18:13:23 <my_host> systemd[1]: webmin.service: Control process exited, code=exited, status=1/FAILURE
Jul 28 18:13:23 <my_host> systemd[1]: webmin.service: Failed with result 'exit-code'.
Jul 28 18:13:23 <my_host> systemd[1]: Failed to start Webmin server daemon.
Jul 28 18:13:25 <my_host> systemd[1]: webmin.service: Scheduled restart job, restart counter is at 3.
Jul 28 18:13:25 <my_host> systemd[1]: Stopped Webmin server daemon.
Jul 28 18:13:25 <my_host> systemd[1]: Starting Webmin server daemon...
Jul 28 18:13:25 <my_host> perl[1825]: pam_unix(webmin:auth): authentication failure; logname= uid=0 euid=0 tty= ruser= rhost=  user=root
Jul 28 18:13:27 <my_host> webmin[1825]: Webmin starting
Jul 28 18:13:37 <my_host> miniserv.pl[1825]: [28/Jul/2024:18:13:37 +0200] Failed to bind to port 10000 : Address already in use
Jul 28 18:13:37 <my_host> miniserv.pl[1825]: [28/Jul/2024:18:13:37 +0200] Failed to bind to port 10000 : Address already in use
Jul 28 18:13:37 <my_host> miniserv.pl[1825]: [28/Jul/2024:18:13:37 +0200] Could not listen on any ports
Jul 28 18:13:37 <my_host> systemd[1]: webmin.service: Control process exited, code=exited, status=1/FAILURE
Jul 28 18:13:37 <my_host> systemd[1]: webmin.service: Failed with result 'exit-code'.
Jul 28 18:13:37 <my_host> systemd[1]: Failed to start Webmin server daemon.
Jul 28 18:13:40 <my_host> systemd[1]: webmin.service: Scheduled restart job, restart counter is at 4.
Jul 28 18:13:40 <my_host> systemd[1]: Stopped Webmin server daemon.
Jul 28 18:13:40 <my_host> systemd[1]: Starting Webmin server daemon...
Jul 28 18:13:40 <my_host> perl[1842]: pam_unix(webmin:auth): authentication failure; logname= uid=0 euid=0 tty= ruser= rhost=  user=root
Jul 28 18:13:42 <my_host> webmin[1842]: Webmin starting
Jul 28 18:13:52 <my_host> miniserv.pl[1842]: [28/Jul/2024:18:13:52 +0200] Failed to bind to port 10000 : Address already in use
Jul 28 18:13:52 <my_host> miniserv.pl[1842]: [28/Jul/2024:18:13:52 +0200] Failed to bind to port 10000 : Address already in use
Jul 28 18:13:52 <my_host> miniserv.pl[1842]: [28/Jul/2024:18:13:52 +0200] Could not listen on any ports
Jul 28 18:13:52 <my_host> systemd[1]: webmin.service: Control process exited, code=exited, status=1/FAILURE
Jul 28 18:13:52 <my_host> systemd[1]: webmin.service: Failed with result 'exit-code'.
Jul 28 18:13:52 <my_host> systemd[1]: Failed to start Webmin server daemon.
Jul 28 18:13:54 <my_host> systemd[1]: webmin.service: Scheduled restart job, restart counter is at 5.
Jul 28 18:13:54 <my_host> systemd[1]: Stopped Webmin server daemon.
Jul 28 18:13:54 <my_host> systemd[1]: Starting Webmin server daemon...

**Comment by iliajie** [comment]
> Jul 28 18:13:23 <my_host> miniserv.pl[1806]: [28/Jul/2024:18:13:23 +0200] Failed to bind to port 10000 : Address already in use

I think this might be the answer to your question.

**Comment by MmdBay** [comment]
This is the problem, not the answer, dear iliajie, please read the comment on this issue first

**Comment by iliajie** [comment]
> This is the problem

What is the output of:

```
ss -tnlp | grep 10000
```

**Comment by MmdBay** [comment]
Thanks a lot, iliajie! With the command you gave me, I figured out that port 10000 was already set up on the OpenVPN service and I fixed it. Thanks a bunch!
