### ISSUE TITLE
remove `BIND 4` from monitor list

### ISSUE THREAD

**Issue by shoulders** [webmin/webmin#2232]
|  SYSTEM INFORMATION||
|----------------------|---------------------------|
|  OS type and version |     Ubuntu Linux 22.04.4     |
|  Webmin version      |     2.111      |
|  Usermin version     |     2.010     |
|  Virtualmin version  |     7.20.2       |
|  Theme version       |     21.10      |
|  Package updates     |     All installed packages are up to date   |

## the issue

`BIND 4` is an old package and should not be in the list

![image](https://github.com/user-attachments/assets/202adeb9-82eb-49eb-9696-f215ae315593)

## Additional

You might want to check to see if some of the others should be removed i.e. `QMail`

**Comment by iliajie** [comment]
Hello,

Your suggestion seems understandable! However, let's wait and see what Jamie thinks about it.

**Comment by jcameron** [comment]
Oh god why is that still in the list?? I will remove it ...

**Comment by shoulders** [comment]
Just looking at the code, am I right that a module can define it's own monitor and this will appear automatically in the monitors list?

**Comment by jcameron** [comment]
Correct - this has always been the case.
