### ISSUE TITLE
 System and Server Status - You can add the same service twice

### ISSUE THREAD

**Issue by shoulders** [webmin/webmin#2233]
|  SYSTEM INFORMATION||
|----------------------|---------------------------|
|  OS type and version |     Ubuntu Linux 22.04.4     |
|  Webmin version      |     2.111      |
|  Usermin version     |     2.010     |
|  Virtualmin version  |     7.20.2       |
|  Theme version       |     21.10      |
|  Package updates     |     All installed packages are up to date   |

### the issue 

You can add a service in twice, see `apache webserver` below

![image](https://github.com/user-attachments/assets/b0c8a4ae-6179-413e-b34b-e9af17e3ed6a)

### proposed solution

- prevent a user adding the service twice
- modify the dropdown list to remove already added services
- **with exceptions**, and maybe these should be in a separate dropdown
  - `Check File or Directory`
  - `Check Process`
  - any other non-pre determined ones

![image](https://github.com/user-attachments/assets/611bf391-e848-4a17-bb76-ded1eb3ca34e)

**Comment by iliajie** [comment]
Hello,

Thanks for the heads up!

I believe it's perfectly acceptable to add a monitor for a service multiple times.

**Comment by shoulders** [comment]
I am just adding some small changes to my original post. After, If you are still happy with the status quo, feel free to close this issue 😄 

Extensible, split the pre-configured ones from the custom ones. Just adding and image to better explain.

**Comment by iliajie** [comment]
> After, If you are still happy with the status quo, feel free to close this issue

I don't think it has much to do with the status quo, but rather the ability to configure different **Notification options** or **Commands to run**.

Personally, I wouldn't do it, but some might have it set up that way. If they had, how should we handle it? So, I think it's better not to introduce such a limitation.

However, let's wait and see what Jamie thinks about it.

**Comment by jcameron** [comment]
Yeah I don't think it's necessarily always wrong to add the same monitor twice, because they might have different post-failure commands, number of retries or notification settings.
