### ISSUE TITLE
Make `System Information` tab on dashboard collapsable

### ISSUE THREAD

**Issue by shoulders** [webmin/webmin#2235]
|  SYSTEM INFORMATION||
|----------------------|---------------------------|
|  OS type and version |     Ubuntu Linux 22.04.4     |
|  Webmin version      |     2.111      |
|  Usermin version     |     2.010     |
|  Virtualmin version  |     7.20.2       |
|  Theme version       |     21.10      |
|  Package updates     |     All installed packages are up to date   |

### background

 ![image](https://github.com/user-attachments/assets/376ee24f-fb00-44ce-9484-69ad8f3f832d)

the `System Information` tab shows all of the live graphs at the top of the dashboard but cannot be collapsed and cannot be moved.

### the requested feature

Add the ability to collapse the `System Information` tab just like these

 ![image](https://github.com/user-attachments/assets/6f784194-9533-4ae2-8c1c-42dcca0f5965)

### additional

- maybe add the ability to move the tabs location by a user draggin and dropping the tab.

**Comment by jcameron** [comment]
@iliajie please take a look at this one ...

**Comment by iliajie** [comment]
> * maybe add the ability to move the tabs location by a user draggin and dropping the tab.

Thanks for suggestion!

Though, "System Information" isn't a tab and isn't meant to be draggable or collapsible.
