### ISSUE TITLE
backup - change default name

### ISSUE THREAD

**Issue by shoulders** [webmin/webmin#2239]
|  SYSTEM INFORMATION||
|----------------------|---------------------------|
|  OS type and version |     Ubuntu Linux 22.04.4     |
|  Webmin version      |     2.111      |
|  Usermin version     |     2.010     |
|  Virtualmin version  |     7.20.2       |
|  Theme version       |     21.10      |
|  Package updates     |     All installed packages are up to date   |

### the background

When you generate a full webmin backup it generates a backup called `backup.gz`

### the issue

This name is very non-descriptive and can cause issues if you have more than one webmin system

### proposed solution

I would like some thing like this

`webmin`+ `hostname` + `date`

Example: `webmin-example-server-com-2024-11-31-1315`

These will always be unique and does not need to be renamed by the user.

**Comment by iliajie** [comment]
Thanks for the heads up!

Fixed in the commit above. The save filename will be named like:

```
webmin-backup-config-host.ubuntu24-pro.virtualmin.dev-2024-07-28-20-08.tgz

```
