### ISSUE TITLE
Stats History (CPU, I/O, Processes etc.) not showing after upgrade to 2.201

### ISSUE THREAD

**Issue by RavanH** [webmin/webmin#2243]
The recent upgrade to  2.201 seems to have broken the Stats History on the Webmin Dashboard page. I read on other threads (github/reddit) that this issue appeared in 2.2 but was fixed in 2.201... Not in my case :/

Operating system	Ubuntu Linux 22.04.4
Webmin version	2.201
Usermin version	1.861
Authentic theme version	21.20.3 
Kernel and CPU	Linux 5.15.0-117-generic on x86_64

**Comment by iliajie** [comment]
Hello,

Thanks for the heads up!

Try running:

```
ln -s /usr/bin/perl /usr/local/bin/perl
systemctl restart webmin
```

**Comment by jcameron** [comment]
@iliajie does this only effect users who upgraded the theme outside of the Webmin package?

**Comment by iliajie** [comment]
Yes, only!

Besides, I'm thinking of removing the theme update feature. The theme development isn't that rapid anymore, and there is no necessity for it anymore ..

**Comment by RavanH** [comment]
Hi, the issue has been magically resolved after taking these steps:

1. From the dashboard, search for "upgrade webmin from" (yes, "from" not "form") then click the link Upgrade Webmin to open the upgrade form page (it does **not** show on the Webmin Config page!)
2. Check the box "pgrade even if new version is the same or older?" and hit the button "Upgrade Webmin"
3. after upgrading, go to Webmin Configuration, then Webmin Themes
4. Select Framed theme and hit Change
5. Then go back to  Webmin Configuration, then Webmin Themes and switch to the Authentic theme again

I'm not sure which of the two actions (re-installing or switching themes) did the trick but the dashboard is now showing history again :)

@jcameron 
> does this only effect users who upgraded the theme outside of the Webmin package?
This might indeed have been the case. I remember seeing a message about a theme update being available. Not sure if this was before or after the upgrade to 2.201 though. Also, somehow, package upgrade messages seem to be "sticky" and linger on after executing all OS upgrades. Could this be related to an object cache or something?

@iliajie 
I created the symbolic link but only after the "magic fix" as describe above, so I cannot say if this would have fixed the issue...

**Comment by RavanH** [comment]
Thanks for developing and maintaining this excellent tool :)

**Comment by iliajie** [comment]
> I'm disabling theme updates for the next release.


Theme upgrades, including notifications and the upgrade page in the configuration, will be disabled by default from now on. Upgrading from Git will no longer be possible.

Those who still want this functionality for whatever reason, will need to manually enabled it, by adding `settings_upgrade_allowed = true` to the theme config.


> Thanks for developing and maintaining this excellent tool :)

You're very welcome!

**Comment by rmatzinger** [comment]
Using RavanH's steps, switching back to Authentic Theme from Framed Theme results in this error message:   "Error — File not found" but no indication of what file was not found.  A subsequent page reload results in display of the expected Authentic Theme which offers a theme update to version:  21.20.5.   

Stats History now working correctly.  

Thanks.

**Comment by iliajie** [comment]
> Stats History now working correctly.

Great, thanks for the feedback!

**Comment by RavanH** [comment]
I did notice a  "Error — File not found" the first time as well. This was before applying the fix suggested by @iliajie : 

```
ln -s /usr/bin/perl /usr/local/bin/perl
systemctl restart webmin
```
