### ISSUE TITLE
bind module - no stop, start and restart buttons

### ISSUE THREAD

**Issue by shoulders** [webmin/webmin#2244]
|  SYSTEM INFORMATION||
|----------------------|---------------------------|
|  OS type and version |     Ubuntu Linux 22.04.4     |
|  Webmin version      |     2.111      |
|  Usermin version     |     2.010     |
|  Virtualmin version  |     7.20.2       |
|  Theme version       |     21.10      |
|  Package updates     |     All installed packages are up to date   |

### the issue

There are not stop, start, restart buttons in the bind module

###

please add stop start and restart buttons in the bind module similiar to dovecot module

![image](https://github.com/user-attachments/assets/c8377d3f-40dc-4805-931a-a5f799e7c280)

**Comment by jcameron** [comment]
They're in the top-right corner of each page of the module

**Comment by shoulders** [comment]
I have found them, thanks.

It is confusing to have a mix of buttons, perhaps consider one or the other 😄 , what are your thoughts?

**Comment by jcameron** [comment]
Yeah it is a little confusing, but in the BIND module we decided to add buttons in the top right of every page so that you don't have to return to the home page after editing DNS records.
