### ISSUE TITLE
Setup DNNSEC Key - page improvements

### ISSUE THREAD

**Issue by shoulders** [webmin/webmin#2245]
|  SYSTEM INFORMATION||
|----------------------|---------------------------|
|  OS type and version |     Ubuntu Linux 22.04.4     |
|  Webmin version      |     2.111      |
|  Usermin version     |     2.010     |
|  Virtualmin version  |     7.20.2       |
|  Theme version       |     21.10      |
|  Package updates     |      1  package update is available, of which  1  is security update   |

# proposed changes

Obviously these options only appear if there is a key.

in `Webmin -> Servers -> BIND DNS Server -> whatever.com -> Setup DNSSEC Key`

## change 1

![image](https://github.com/user-attachments/assets/76f5112a-f858-4b04-a6bf-b7cf87f868db)

- this checkbox and message are not is a good place. Maybe putting it directly under the `Remove Key` button.

## change 2

Consider this section

![image](https://github.com/user-attachments/assets/80fe15c2-8d37-43b7-99cf-d2d11222e198)

please can you add this block as shown in `Virtualmin --> DNS Options --> DNSSEC zone keys`

![image](https://github.com/user-attachments/assets/ae347fde-5dc7-4942-a57a-ac49109e1812)

- this makes it easier for user to read
- you could add the words **DS records for domain registrar**

**Comment by iliajie** [comment]
> * this checkbox and message are not is a good place. Maybe putting it directly under the `Remove Key` button.

This was actually a bug on Authentic theme side. Fixed now, e.g.:

<img width="1175" alt="image" src="https://github.com/user-attachments/assets/df6109ea-2e5a-46ea-bbe7-5dd3c80c7309">



> lease can you add this block as shown in `Virtualmin --> DNS Options --> DNSSEC zone keys`

Good suggestion. Implemented here https://github.com/webmin/webmin/commit/8236fb2fd85c7a99571b9ccc4cc0450adecdc8cc.

**Comment by shoulders** [comment]
@iliajie thanks for quick fix

**Comment by iliajie** [comment]
Welcome!
