### ISSUE TITLE
What does RS mean in System Logs RS?

### ISSUE THREAD

**Issue by artquest** [webmin/webmin#2247]
Hi,
what does RS mean in System Logs RS?

**Comment by iliajie** [comment]
Hey,

**RS** represents **Rsyslog** in more specific way, e.g.:

<img width="192" alt="image" src="https://github.com/webmin/webmin/assets/4426533/4ac83694-2a72-4912-b971-f6fd9698ab56">

Note that, it isn't a problem for you to call it whatever you want on your system by changing it on the **Webmin ⇾ Webmin Configuration: Module Titles** page.
