### ISSUE TITLE
Incorrect CPU graph after update to FreeBSD 14.1 and Webmin 2.201

### ISSUE THREAD

**Issue by aspisk** [webmin/webmin#2249]
After updating operating system from 14.0 to 14.1 and Webmin from 2.103 to 2.201 CPU utilization graph shown incorrect. How can I resolve this?
![image](https://github.com/user-attachments/assets/9a017cab-5540-4c07-84c3-5d771d42c094)
In the text module information is correct.
![image](https://github.com/user-attachments/assets/9cf1d1e8-d416-49c5-bdfc-1d56806f651a)

**Comment by iliajie** [comment]
Hello,

What is the output of the following command on your FreeBSD system?

```
vmstat 0.1 2
```

**Comment by aspisk** [comment]
![image](https://github.com/user-attachments/assets/b4bd2135-9cf0-46dd-ae86-76d463b0889f)

**Comment by iliajie** [comment]
Well, the output in the dashboard looks consistent with `vmstat` command output.

Alright, what is the output of the following commands when executed one after the other?

```
vmstat 0.1 2
vmstat 1 2
iostat 0.25 2
iostat 1 2
```

**Comment by aspisk** [comment]
It's look like this
![image](https://github.com/user-attachments/assets/4499852c-608e-4fd7-aab2-1b63949a217d)

**Comment by iliajie** [comment]
Well, okay! But why is the output of `vmstat` like that?

What we could technically do is use CPU info from `iostat`, but that won’t answer why the `vmstat` output is like this. Perhaps it’s an upstream bug?

[freebsd-bugs@freebsd.org#81103](https://www.mail-archive.com/freebsd-bugs@freebsd.org/msg81103.html)

**Comment by aspisk** [comment]
Ok, I'll try to apply this patch tomorrow.

**Comment by chris001** [comment]
Hope [the patch](https://github.com/freebsd/freebsd-src/pull/1344) is merged soon and the next version released.

**Comment by aspisk** [comment]
> Well, okay! But why is the output of `vmstat` like that?
> 
> 
> 
> What we could technically do is use CPU info from `iostat`, but that won’t answer why the `vmstat` output is like this. Perhaps it’s an upstream bug?
> 
> 
> 
> [freebsd-bugs@freebsd.org#81103](https://www.mail-archive.com/freebsd-bugs@freebsd.org/msg81103.html)

Thanks! It worked for me.
