### ISSUE TITLE
After upgrading to version 2.201, there was a problem with Chinese garbled characters

### ISSUE THREAD

**Issue by liutt1312** [webmin/webmin#2250]
![image](https://github.com/user-attachments/assets/45924acc-5472-450d-ac82-edcf952ad67d)
![image](https://github.com/user-attachments/assets/f268f39c-d375-4507-878f-dbaaccf23f6e)

**Comment by iliajie** [comment]
Hello,

Thanks for the heads up!

This issue is going to be fixed in upcoming Webmin 2.202.
