### ISSUE TITLE
I am unable to display normal characters in CPU and memory status

### ISSUE THREAD

**Issue by ncs19960831** [webmin/webmin#2252]
This seems to be a separate character conversion issue. I use **Firefox browser, version 127.0.2** The system was still running well a month ago. But it wasn't until the previous version upgrade. This problem has arisen. I saw an upgrade again today and I think it can solve this problem. But sadly, I still have this problem now. So I chose to report the issue.
When I first opened it, it displayed normally. like next image:
![图片](https://github.com/user-attachments/assets/e9a2ca51-f49c-48a4-b60a-87a8042e68d7)
But after about ten seconds (or possibly longer but not exceeding 20 seconds), it will become an error display after the next automatic parameter update.like next image:
![图片](https://github.com/user-attachments/assets/13c23324-5df5-4092-974b-f8a8f816c0e4)
I don't know what I need to do to solve this problem, please help me, thank you

**Comment by ncs19960831** [comment]
Well, it seems that there is a conflict between the language and region selection project of the previous version and some parts of the new version. I modified it to English again, and then switched to Chinese (I am a Chinese). I was glad that I saw the normal parameters, and it was not wrong after 5 minutes

**Comment by iliajie** [comment]
Did you instal latest Webmin 2.202? It was release a couple of hours ago.
