### ISSUE TITLE
Missing DBI.pm

### ISSUE THREAD

**Issue by zoigecyb** [webmin/webmin#2253]
Hello.

when adding field to mysql database via webmin (latest) faced a problem
`Can't locate DBI.pm in @INC (you may need to install the DBI module) (@INC contains: /usr/share/webmin/vendor_perl /usr/share/webmin /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.34.0 /usr/local/share/perl/5.34.0 /usr/lib/x86_64-linux-gnu/perl5/5.34 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl-base /usr/lib/x86_64-linux-gnu/perl/5.34 /usr/share/perl/5.34 /usr/local/lib/site_perl /usr/share/webmin/ . ..) at (eval 74) line 1. BEGIN failed--compilation aborted at (eval 74) line 1. : ./mysql-lib.pl (line 392)`

actually `apt-get install libdbi-perl` fixed this, but include it in installer later.

Thanks

**Comment by jcameron** [comment]
Good idea, I will add that package as an optional dependency in future releases.
