### ISSUE TITLE
Fedora 22+ replaced yum with dnf

### ISSUE THREAD

**Issue by qooob** [webmin/webmin#226]
Jamie, Fedora 22+ makes `yum` command is deprecated and replaced with `dnf`.

Now when you run package updated it returns this warning `Yum command has been deprecated, redirecting to '/usr/bin/dnf -y install stunnel'.`

Do we have control over which command is used from settings?

**Comment by sgrayban** [comment]
WTF ??? Why would they do that ?? Oh wait.. Fedora is a beta platform for RHEL platform so expect stupid bugs all the time.

Why is dnf better then yum ?

**Comment by qooob** [comment]
Relax man :) dnf in just another new major release of yum. http://dnf.baseurl.org

**Comment by sgrayban** [comment]
Read https://lists.fedoraproject.org/pipermail/devel/2015-April/209580.html

Yum can still be installed.

**Comment by qooob** [comment]
Why? It just works the __same way__. All you need is to replace `yum` with `dnf` in case dnf command is there. 
http://www.linux-magazine.com/Online/Features/Will-DNF-Replace-Yum

**Comment by sgrayban** [comment]
Stupid... dnf is the same thing so why confuse everyone with dnf then ???

I dislike fedora simply for this reason.... they make changes that are absurd and retarded.

**Comment by qooob** [comment]
Dude, please read the article I mentioned:

>The Problems with Yum

>DNF began as a fork of Yum and is meant to address several longstanding problems in Yum, the most pressing of which is dependency resolution and interaction with online repositories.

>“There are better dependency solvers out there,” Kozumplík says, speaking about Yum’s capabilities. DNF’s own solution uses SUSE’s libsolv, with hawkey as a C and Python wrapper. Libsolv, he adds, “employs a very solid algorithm to do the resolving. Its other main strength is effective representation of the packaging data in memory. It has a very generic API able to handle many different packaging tasks and situations, which can make it a bit intimidating to start using. That’s where hawkey comes in, with its simplified workflow.”

>Another problem with Yum according to Kozumplík is that “the API is not documented. One has to browse the code to find the right means to [write a] call. This in effect means that everything in Yum is considered a public API and that means the maintainers have got their hands twisted behind their backs when trying to refactor or remove unused stuff.” For example, “there is a method in Yum with a typo in its name that nobody can remove or fix for this reason. This makes the maintaining and testing difficult, and building new features is slow. DNF is doing a much better job here by documenting the API, keeping it slim and well-specified.”

>Yet another shortcoming of Yum is that it supports only Python for extensions. “Everyone but Python developers has a hard time using it and are calling for a C API,” Kozumplík says. “For instance, PackageKit needs to do packaging in a way that’s guaranteed to be compatible with how DNF does it, and it should be able to without having to spawn a separate DNF process or embed a Python interpreter. That’s why we built hawkey and librepo [a C and Python library for downloading metadata and packages from repositories.]. More C APIs are to come later.”

>Other improvements in DNF include a lower memory reduction and less automatic synchronization of metadata with repositories – a process that users often complain “happens too often and takes too much time.”

>Asked why he did not simply contribute patches to Yum, Kozumplík explains that “gradual patching was technically hard and politically even harder. At the time I was starting to work, it was just not realistically possible to join the Yum upstream development and have changes of this magnitude submitted. The maintainers were against such changes, and when you compare the two code bases now, you can’t blame them. For starts, DNF is 29k lines of code, having had lots of internals moved out into the underlying C libraries, while Yum is 56k lines of code. DNF is still a branch of Yum of sorts, but for practical reasons (early testing, integration within fedora) we are making our own releases.”

>In the end, Kozumplík says, “We had no choice, really,” except to fork.

What OS are you using?

**Comment by sgrayban** [comment]
Accord to other discussions YUM will not be replaced in any near future release of RHEL so that means Joe will have to make copies of yum and dnf packages because the meta data is not the same anymore... god how fu*king stupid can the redhat people get......

**Comment by qooob** [comment]
What OS are you using?

**Comment by sgrayban** [comment]
A smart one... debian

**Comment by jcameron** [comment]
So it should be pretty easy for Webmin to use the `dnf` command instead of `yum` if installed.

Are they designed to be compatible in terms of command line flags and output though?

**Comment by qooob** [comment]
Yes, commands are fully identical. It manages repo data differently but still back compatible, as far as I'm aware.

**Comment by jcameron** [comment]
Are they planning to keep the `yum` command around for compatibility, or is `dnf` going to completely replace it?

**Comment by qooob** [comment]
Hard to say for sure. It will be there for some time, no doubts.

Are there settings, where user can define what package manager to use? Maybe it's worth implementing it, in case there's l not?

**Comment by sgrayban** [comment]
Jamie the meta data used to compile and package the rpm's are not the same -- there is a command to to convert that data to the new dnf format.

Also the yum command was renamed so its not straight forword as qooob is trying to lead you.

**Comment by jcameron** [comment]
I think what I'll do is have Webmin use the `dnf` command instead of `yum` if installed.

I don't have access to a Fedora 22 system though - so can someone check if /etc/yum.conf has been renamed to /etc/dnf.conf ?

**Comment by qooob** [comment]
`$ cat: /etc/dnf.conf: No such file or directory`

`$ whereis dnf`
`dnf: /usr/bin/dnf /etc/dnf /usr/share/man/man8/dnf.8.gz`


`$ cat /etc/dnf/dnf.conf`
```
[main]
gpgcheck=1
installonly_limit=3
clean_requirements_on_remove=true
```

**Comment by jcameron** [comment]
Ok, that should be pretty easy to support.

**Comment by qooob** [comment]
I actually placed your committed file to `/usr/libexec/webmin/software/yum-lib.pl` just to test. Restarted Webmin. Nothing changed. Same warning is thrown? Should you double check?

**Comment by qooob** [comment]
..maybe `&has_command("dnf")` should be placed before `&has_command("yum")`, as later seems to return true and the statement `&has_command("dnf")` never reached?

**Comment by qooob** [comment]
Yes, by the way, I mean CPAN Module, that's where it didn't work.

**Comment by jcameron** [comment]
Does your system have both the `yum` and `dnf` commands installed?

**Comment by qooob** [comment]
Jamie, `yum` is deprecated. When I run `yum`, I don't get error. `dnf` comes with the warning, when you call `yum`. so probably good logic to do 

```Perl
if (...) {
   ....
}
eleif (&has_command("dnf") && &has_command("yum")) {     # for now

}
eleif (&has_command("dnf")) {    # for the future

}
else (&has_command("yum")) {    

}
```

**Comment by jcameron** [comment]
So do you think it would make sense to prefer the `dnf` command if it is installed?

**Comment by qooob** [comment]
That is the whole point. `dnf` replaces `yum`. So far `yum` is available (as reference) but will be removed one day or the other (will takes years in reality).

When you run, that's what you get:

```
Yum command has been deprecated, redirecting to '/usr/bin/dnf install ...'.
See 'man dnf' and 'man yum2dnf' for more information.
To transfer transaction metadata from yum to DNF, run:
'dnf install python-dnf-plugins-extras-migrate && dnf-2 migrate'
```

**Comment by jcameron** [comment]
Thanks - I'll check in a change to prefer `dnf` if installed.
