### ISSUE TITLE
Problems with CPU temperatures

### ISSUE THREAD

**Issue by almodovaris** [webmin/webmin#2267]
CPU Intel(R) N100, 4 cores:

sensors
coretemp-isa-0000
Adapter: ISA adapter
Package id 0:  +51.0°C  (high = +105.0°C, crit = +105.0°C)
Core 0:        +49.0°C  (high = +105.0°C, crit = +105.0°C)
Core 1:        +49.0°C  (high = +105.0°C, crit = +105.0°C)
Core 2:        +49.0°C  (high = +105.0°C, crit = +105.0°C)
Core 3:        +50.0°C  (high = +105.0°C, crit = +105.0°C)

iwlwifi_1-virtual-0
Adapter: Virtual device
temp1:        +36.0°C

acpitz-acpi-0
Adapter: ACPI interface
temp1:       -273.3°C
temp2:        +27.8°C

CPU Intel(R) Core(TM) i3-N305, 8 cores:

sensors
coretemp-isa-0000
Adapter: ISA adapter
Package id 0:  +43.0°C  (high = +105.0°C, crit = +105.0°C)
Core 0:        +40.0°C  (high = +105.0°C, crit = +105.0°C)
Core 1:        +40.0°C  (high = +105.0°C, crit = +105.0°C)
Core 2:        +40.0°C  (high = +105.0°C, crit = +105.0°C)
Core 3:        +40.0°C  (high = +105.0°C, crit = +105.0°C)
Core 4:        +43.0°C  (high = +105.0°C, crit = +105.0°C)
Core 5:        +43.0°C  (high = +105.0°C, crit = +105.0°C)
Core 6:        +43.0°C  (high = +105.0°C, crit = +105.0°C)
Core 7:        +43.0°C  (high = +105.0°C, crit = +105.0°C)

acpitz-acpi-0
Adapter: ACPI interface
temp1:        +27.8°C

nvme-pci-0300
Adapter: PCI adapter
Composite:    +40.9°C  (low  = -273.1°C, high = +89.8°C)
                       (crit = +94.8°C)
Sensor 1:     +40.9°C  (low  = -273.1°C, high = +65261.8°C)
Sensor 2:     +45.9°C  (low  = -273.1°C, high = +65261.8°C)

**Comment by jcameron** [comment]
Are these temperatures being displayed incorrectly in Webmin?

**Comment by almodovaris** [comment]
Yup. For N100 it says 60 to 65 degrees Celsius while sensors reports temperatures in the 50s.

For the other, the temperatures vary so vastly between the first four cores and the last four cores, that it makes no sense.

**Comment by iliajie** [comment]
CPU temperatures can be cached.

**Comment by almodovaris** [comment]
E.g. Core 1: 42°C Core 2: 42°C Core 3: 42°C Core 4: 42°C Core 5: 68°C Core 6: 68°C Core 7: 68°C Core 8: 68°C, while the CPU gets barely used.

**Comment by iliajie** [comment]
It's likely impossible to get an accurate CPU temperature without real-time monitoring enabled, which updates stats in the background without using the CPU nearly at all. Traditional Webmin background status collection can be resource-intensive, heating up your CPU. The sensor readings are taken while the CPU is hot, stored, and displayed until the next update, which is why the temperature seems consistently high.

If you have Webmin 2.202 installed, you should enable the "Enable real-time monitoring" option on the "Theme Configuration: Dashboard and real-time monitoring" page.

**Comment by almodovaris** [comment]
"Enable real-time monitoring" was never disabled on my system.

**Comment by iliajie** [comment]
> Problem: groups of four cores display the same temperature at a given time. That is not a plausible reading of cores temperature.

You're right! My apologies!

I checked the code, and we don't even provide temperatures update from sensors in real-time monitoring. I'll add this to my to-do list and update this ticket with progress in some time ..

**Comment by iliajie** [comment]
> > Problem: groups of four cores display the same temperature at a given time. That is not a plausible reading of cores temperature.
> 
> You're right! My apologies!
> 
> I checked the code, and we don't even provide temperatures update from sensors in real-time monitoring. I'll add this to my to-do list and update this ticket with progress in some time ..


This was a challenging feature to implement, but I found it important and got it fixed.

Thanks for the heads up!
