### ISSUE TITLE
Postfix Virtual Domain (/etc/postfix/virtual) does not handle multi-line correctly

### ISSUE THREAD

**Issue by jeffgoh** [webmin/webmin#2279]
When a virtual alias like a group email is long, it is customary to split it as 

"      multi-line text
              A  logical  line  starts  with  non-whitespace text. A line that
              starts with whitespace continues a logical line."

For example:
```
group   mailbox-a mailbox-b
        mailbox-c mailbox-d
```
Those lines look fine in vim, but in webmin it becomes

```
group                     mailbox-a mailbox-b
mailbox-c                 mailbox-d
```
so instead of mailbox-c becoming a continuation of the alias "group" it looks like an alias in it's own right.

This wasn't a breaking problem because in the past (e.g. webmin 1.991) the GUI would auto-wrap a long alias line correctly (so whoever is CLI inclined just has to agree to a single long  line) but for current webmin (2.202) the RHS of the alias no longer wraps but instead truncates, making viewing or editing quite impossible.

The side-by side tables now take up 10x of my screen so to get the "big picture" I have to set browser zoom to like 10%

I've been a happy webmin user for over 20 years now. Am hoping this niggly bug can be fixed soon!

**Comment by jcameron** [comment]
Is this in the `/etc/aliases` file, or is it in `/etc/postfix/virtual` ? 

It looks like Webmin supports continuations in the aliases file, but not other maps.

**Comment by jeffgoh** [comment]
/etc/postfix/virtual should I move those groups to aliases instead? Now you have me thinking - the function seems to overlap.

**Comment by jcameron** [comment]
Ok the next release of Webmin will properly support multi-line entries in `/etc/postfix/virtual` (and other files)
