### ISSUE TITLE
System and Server Status Web webhook mixed up ? and & 

### ISSUE THREAD

**Issue by sh4xg** [webmin/webmin#2285]
Hi, 

it seems that the detection of ? in the webhook url is mixed up

https://github.com/webmin/webmin/blob/cf876900cf14cca17ba60bc55fb19f2b7c21dd81/status/monitor.pl#L453

should be
`$page .= ($page =~ /\?/ ? "&" : "?");`

**Comment by iliajie** [comment]
Thanks for the heads up! We will fix it in the next Webmin release.
