### ISSUE TITLE
Partitons on Local Disks - IDE parameters - I dont have an IDE drive

### ISSUE THREAD

**Issue by shoulders** [webmin/webmin#2288]
| SYSTEM INFORMATION ||
|----------|----------|
|  OS type and version |  Ubuntu Linux 22.04.5                   |
|  Usermin version     |  2.102                                  |
|  Virtualmin version  |  7.20.2 Pro                             |
|  Theme version       |  21.20.7                                |
|  Apache version      |  2.4.52                                 |
|  Package updates     |  All installed packages are up to date  |

### Background

- I have installed on KVM/TrueNAS using a **VirtIO** device.
- When installing Ubuntu I used the whole disk
- I did not use LVM.

![image](https://github.com/user-attachments/assets/8085451e-bcdf-4548-a0a8-775be31e293e)

![image](https://github.com/user-attachments/assets/51b01084-213f-48f8-8f6b-040ead48c0f2)

![image](https://github.com/user-attachments/assets/53e92d01-5299-4fc3-aafe-ad454ab28786)

### The issue

`VirtIO` is not **IDE**

### proposed solution

Add a checker to make sure the drive is an IDE drive before presenting the `IDE Parameters` button

Also, no-one uses **IDE drives** any more so maybe the `IDE Parameters` button and its settings should be removed.

**Comment by jcameron** [comment]
Ah yes this is a bug, we shouldn't be showing that IDE params link for anything other than real IDE disks. I'll fix this ..
