### ISSUE TITLE
A cosmetic English indefinite article correction

### ISSUE THREAD

**Issue by SamSirry** [webmin/webmin#2289]
For email notification with new program package updates, the message appears as `An update ...` or `An security update ...`

The lines in question are:
https://github.com/webmin/webmin/blob/11ad8d48e669d5af26641c5bca51c9bd297741aa/package-updates/update.pl#L23
https://github.com/webmin/webmin/blob/11ad8d48e669d5af26641c5bca51c9bd297741aa/package-updates/update.pl#L27

The indefinite article "a" or "an" should be included on the line 23 instead of 27.
Perhaps this also affects the translation strings, but I have totally no idea how/where they're implemented.

Thank you.

**Comment by jcameron** [comment]
Thanks, we'll fix this in the next release.
