### ISSUE TITLE
Configure a single email address to be used for notifications

### ISSUE THREAD

**Issue by shoulders** [webmin/webmin#2295]
| SYSTEM INFORMATION ||
|----------|----------|
|  OS type and version |  Ubuntu Linux 22.04.5             |
|  Usermin version     |  2.102                            |
|  Virtualmin version  |  7.20.2 Pro                       |
|  Theme version       |  21.20.7                          |
|  Apache version      |  2.4.52                           |
|  Package updates     |  9 package updates are available  |

## the issue

you can set system notifications to be sent to emails in many places in Webmin (possibly Virtualmin aswell) and in each case you have to enter an email address. This means if you want to change the email you have to go to many areas and change the email address.

**Some examples**

Webmin --> Tools --> System and Server Status --> Scheduled Monitoring --> Email status report to
![image](https://github.com/user-attachments/assets/1e4ec4d7-38cf-4a26-a76c-584f0aeeeaea)

Webmin --> System --> Software Package Updates --> Scheduled Upgrades
![image](https://github.com/user-attachments/assets/e76e5cae-a4a6-483f-9da4-ab82c46e480f)

## proposed solution

This is a 2 part solution (+ a virtualmin option)
- Add a new section where you can the notification emails. I have picked a locatin but I am not fixed to it.
  - In virtualmin possibly set this email during the installer
- update the email fields where required. I will just do one email below

###
in webmin --> webmin configuration --> Sending Email
![image](https://github.com/user-attachments/assets/6dfd9299-09d0-4683-92eb-e77539e42075)

###
In Webmin --> System and Server Status --> Scheduled Monitoring --> Email status report to
![image](https://github.com/user-attachments/assets/c902d119-f72a-458e-a26b-5b8f3cf3e5a2)

- so here you can use the default system notification email or set one of your own.
- The default system notification should be selected by default

## additional

- Maybe also add the **From: address for email** filed to the new setting. Again this will unify the notifications.
- Most monitors should be set by default to send an email and if there is a an email present in the notification field then one will be sent, if there is no emaik then no email will be sent.

**Comment by iliajie** [comment]
I don’t think we should replace “Email status report to” and similar options, but adding a “To default email” radio option would be a good improvement.

**Comment by shoulders** [comment]
That sounds good to me.

**Comment by shoulders** [comment]
One important thing, is to make the default system email radio option the default.

Then reporting can be turned off rather than not knowing what options there are.

This could be done for virtualmin installations only as virtualmin tried to set everything up for users whereas webmin is directed at admins.

**Comment by jcameron** [comment]
This is a good idea to allow a global default to be set which will flow through to other modules. I'll look into this...

**Comment by shoulders** [comment]
> This is a good idea to allow a global default to be set which will flow through to other modules. I'll look into this...

I try my best 😄

**Comment by jcameron** [comment]
I'm working on this now. What other places in webmin would be good to follow the default notification address?

**Comment by shoulders** [comment]
I will all that I can think of, can you make sure they are suitable.

## Virtualmin
- System Settings --> Bandwidth Monitoring --> Also send email to
- System Settings -->Server Templates --> Edit template section: status monitoring --> Additional email address for monitoring messages
- System Settings --> Virtualmin Configuration --> configuration category:  Actions upon server and user creation --> address for email sent by Virtualmin
  - **where is this set ? This is the feature you are implementing now?**
- Web app Installers --> Upgrade notification --> Send upgrade notifiction to
- Disk Quota Monitoring --> Send quota report to
- Limits and Validation --> Validate Virtual Servers --> Scheduled Validation --> Send email report to
- Backup and restore --> Scheduled Backups --> Schedule and reporting --> email backup report to

## Webmin

- reboot notification banner
  - not sure where this one is set
- Webmin --> webmin configuration --> sending email --> sed test message --> send message to
  - I thin this should have it, not 100%
- Webmin --> Webmin --> Backup Configuration Files --> create Scheduled Backup  --> Backup Schedule --> email result to address
- Webmin --> Webmin --> webmin Actions Log --> Email Notification --> send email for Webmin actions?
- Webmin --> System --> software package updates -->scheduled upgrades --> email updates reports to
- Webmin --> Tools --> System and Server status -->Scheduled monitoring --> Email status report to

**Comment by jcameron** [comment]
Ok I think all of these will be covered in the next Webmin and Virtualmin releases!

**Comment by shoulders** [comment]
nice, this is a very useful feature.

+ thanks for implementing this.

**Comment by shoulders** [comment]
| SYSTEM INFORMATION ||
|----------|----------|
|  OS type and version |  Ubuntu Linux 22.04.5                   |
|  Usermin version     |  2.400                                  |
|  wEBmin version     |  2.510                                  |
|  Virtualmin version  |  7.40.1 Pro                             |
|  Theme version       |  25.10                                  |
|  Apache version      |  2.4.52                                 |
|  Package updates     |  All installed packages are up to date  |

@jcameron can you check and then re-open this for me. thanks

I checked and this has not been implemented.

I did not check everywhere but these are the ones I have:

### Virtualmin --> Limits and Validation --> Disk Quota Monitoring --> Send quota report to
  
<img width="696" height="103" alt="Image" src="https://github.com/user-attachments/assets/af33ddc2-2603-44c2-a9ad-9b2fe6cdae5f" />

### Webmin --> Tools --> System and Server Status --> Scheduled Monitoring --> Email status report to    
<img width="659" height="185" alt="Image" src="https://github.com/user-attachments/assets/35abcce9-0041-437e-9a71-32fac34be573" />

### Webmin --> System --> Software Package Updates --> Scheduled Upgrades
   
<img width="944" height="239" alt="Image" src="https://github.com/user-attachments/assets/9bac9d36-968c-460f-955d-780eaa481f50" />

**Comment by jcameron** [comment]
@shoulders would you prefer that these email fields default to the global notification address?

Some of them should already, assuming you have set one in the Webmin Configuration module.

**Comment by shoulders** [comment]
I see what you have done and it is confusing and what not what I wanted.

### What you have done

<img width="715" height="34" alt="Image" src="https://github.com/user-attachments/assets/bdfb4ad2-b8bc-4fde-8e01-2553c4616e8b" />

When you fill this in, it overrides the free type input boxes of the various emails things. This is confusing and not logical and will override all the email address that an admin has already set. The email input fields are not even greyed out implying they are safe to change.

This hybrid approach should be swapped out.

### The request

- Each option where you fill in an email address would get an extra filed called **Webmin**
- So there would be 3 radio options
  - **None**      = none
  - **Webmin**  = this uses the email from `Default destination address for notifications`
  - **Custom** = User fills enters an email address for this option only
- If the webmin email is the default selection, I will leave up to to you 

So some would have the possibility of setting a custom email for the emails allowing emails to go to different departments and a single **webmin** one which allows a single user admin to have all of the emails to come to him and/or easily swap the emails.

<img width="1109" height="637" alt="Image" src="https://github.com/user-attachments/assets/93ec312f-0ecf-48b4-8484-c1d0d94583b0" />

Thanks

**Comment by jcameron** [comment]
Ok, that's a reasonable request. Let me see if we can implement it ...

**Comment by shoulders** [comment]
I see you have changed 3 locations, are you doing the other ones?

If this is a test or If I have rushed the gun, let me know 😄

**Comment by jcameron** [comment]
Don't worry, it's still in progress!

Question about how you'd like this feature to work - if the admin selects to use the Global notification email address and then changes that address for say scheduled monitoring, should a change to the global address also apply to scheduled monitoring?

**Comment by shoulders** [comment]
> Don't worry, it's still in progress!

Thanks for the update, i was starting to have sleelpless nights 😄 🛌 

> if the admin selects to use the Global notification email address and then changes that address for say scheduled monitoring, should a change to the global address also apply to scheduled monitoring?

### If think the answer is no, let me try and re-clarify.

- the **Global notification email address** will only ever be stored here:
    `Webmin --> Webmin Configuration --> Sending Email --> Default destination address for notifications`
- When the **Global notification email address**  radio option is selected for a particular feature (eg `scheduled monitoring` ) , Webmin looks the email address up from:
    `Webmin --> Webmin Configuration --> Sending Email -->Default destination address for notifications`
- if the **Global notification email address** is changed in the webmin config, then this new email address will be used for all features whoes notification email radio option is set to **Global notification email address** .
- The `Default destination address for notifications` does not physical push, parse and write the inputted email address to all of the services. It is a an email address that is to be read and used by services around webmin when they have the  **Global notification email address**  enabled for the email notification. 
- If a users sets a custom email address in `scheduled monitoring` then he has selected the 3rd radio option. This will only affect `scheduled monitoring` and this address is not pushed to the **global email address field** and the custom email address entered in the email input field on the `scheduled monitoring` page is used only for  `scheduled monitoring`
- The custom input filed is only relevant for the 3rd radio option. 

This feature request makes the notification email address that is used "dynamic" in the sense that the admin can just change the notification email for all services in one place but allow for local overrides for particular services. It does not PUSH any email address changes to any individual service config files, it is an email address that can be read globally.


Does this make sense?

**Comment by jcameron** [comment]
Makes sense! I'll update this ticket with progress ... admittedly the first attempt to implement this feature was kind of half-assed, and so didn't work the way you suggested.

**Comment by shoulders** [comment]
I have done worse 😀, I will leave this with you. Thanks.

**Comment by jcameron** [comment]
Ok future releases will work this way
