### ISSUE TITLE
I'd LIKE you to consider RENAMING your script to have the word 'webmin' in the name of the script

### ISSUE THREAD

**Issue by aaronsql2019** [webmin/webmin#2296]
Hey;

I am a lifetime user of webmin..
But I'd LIKE you to consider RENAMING your script to have the word 'webmin' in the name of the script.

Current code:
wget https://raw.githubusercontent.com/webmin/webmin/master/setup-repos.sh
sh setup-repos.sh

Recommended Code:
wget https://raw.githubusercontent.com/webmin/webmin/master/webmin-setup-repos.sh
sh webmin-setup-repos.sh

I think that EVERY vendor should do that. Sorry. I just want some sort of 'self-describing' environment.

To be HONEST? I'd rather have

wget https://raw.githubusercontent.com/webmin/webmin/master/webmin-setup-repos-20241014.sh
sh webmin-setup-repos-20241014.sh

I *THINK* that would make things easier to support. I don't LIKE running around running OLD SCRIPTS like ever. So in MY opinion, all scripts should end in -yyyymmdd whatever.

**Comment by iliajie** [comment]
> Recommended Code:
> wget https://raw.githubusercontent.com/webmin/webmin/master/webmin-setup-repos.sh
> sh webmin-setup-repos.sh

I don’t mind naming it `webmin-setup-repos.sh`, it makes sense to me. Jamie, what do you think?

> To be HONEST? I'd rather have
> 
> wget https://raw.githubusercontent.com/webmin/webmin/master/webmin-setup-repos-20241014.sh sh webmin-setup-repos-20241014.sh

No, that’s not sustainable. What we could do though is print the script version when it runs.

**Comment by jcameron** [comment]
Sure, renaming it to `webmin-setup-repos.sh` is fine with me

**Comment by nfrawley93** [comment]
Make sure to update the instructions on the download page on the website as well. Just happened to get caught a few minutes ago.
https://webmin.com/download/

Thanks again for all the amazing work!

**Comment by iliajie** [comment]
> Sure, renaming it to `webmin-setup-repos.sh` is fine with me

I’ve added a new `webmin-setup-repos.sh`, but we’ll need to keep the link to the old one for a while.



> Make sure to update the instructions on the download page on the website as well. Just happened to get caught a few minutes ago.

Yeah, I’ve updated the `webmin.com` repo — it will be online once Jamie rebuilds the website.

Thanks for the heads up!

**Comment by iliajie** [comment]
Jamie, you should also update:

https://download.webmin.com/download/

**Comment by jcameron** [comment]
> Jamie, you should also update:

Will do!
