### ISSUE TITLE
Network Interfaces (activated at boot) names are missing and not editable in table

### ISSUE THREAD

**Issue by skunker** [webmin/webmin#2297]
I want to add a new ip address (static second ip) through webmin,

Networking > Network Configuration >  Network Interfaces > [Activated at Boot] 
Two of the interfaces listed in this table are showing...
Name as **file** Type as **Unknown**

Something seems wrong odd and they are not editable, which I think they should be as {eno1 and eno2} in my case.
Is it a bug? Check screenshots please.

Webmin version: 2.202
Operating system: AlmaLinux 9.4

![actived at boot](https://github.com/user-attachments/assets/3f116c36-2513-4f71-beb6-806d5d3c3b71)
![active now](https://github.com/user-attachments/assets/29f4388a-81da-4f7c-a66e-d1ff2d48f82a)

**Comment by iliajie** [comment]
Hello,

Can you share the network configurations from `/etc/NetworkManager/system-connections/` and/or `/etc/sysconfig/network-scripts` directories?

**Comment by skunker** [comment]
> ls /etc/NetworkManager/system-connections/
enp0s2.nmconnection
internal.nmconnection
public.nmconnection

**Comment by iliajie** [comment]
> ls /etc/NetworkManager/system-connections/
> enp0s2.nmconnection
> internal.nmconnection
> public.nmconnection

We'd need to have a copy of all those files.

**Comment by skunker** [comment]
internal.nmconnection and public.nmconnection config files had **interface-name=** line missing, I added what is missing in both files as follows:
internal.nmconnection
interface-name=**internal**

public.nmconnection
interface-name=**public**

Great! They are shown now in the network interfaces list table and can be edited, the only this is not right now is the type, though both config files have "type=ethernet" and [ethernet] config..

**Comment by skunker** [comment]
Yes. They were missing for some reason... Thanks @iliajie
