### ISSUE TITLE
Webmin non-admin user gets placholder instead of system details

### ISSUE THREAD

**Issue by shoulders** [webmin/webmin#2299]
| SYSTEM INFORMATION ||
|----------|----------|
|  OS type and version |  Ubuntu Linux 22.04.5             |
|  Usermin version     |  2.102                            |
|  Virtualmin version  |  7.20.2 Pro                       |
|  Theme version       |  21.20.7                          |
|  Apache version      |  2.4.52                           |
|  Package updates     |  8 package updates are available  |

### The issue

When I log into Virtualmin/webmin with one of my users the get details button is there but when I click it I only get what is below, not the full system information as above.

```
| SYSTEM INFORMATION ||
|----------|----------|
```

### proposed solution(s)
- remove the button for al non-admins
- fix the information

**Comment by iliajie** [comment]
Hello,

Can you describe “non-admins” users and how exactly those were created?

**Comment by shoulders** [comment]
As admin I refer to my main admin account (i.e. the one below root).

The virtualmin user I logged in with has these capabailities using my bronze plan

![image](https://github.com/user-attachments/assets/5f7c4990-7841-411b-9f5d-14c660f275e0)

**Comment by jcameron** [comment]
Can you attach a screenshot of what non-admin users are seeing? I don't think it came through in the OP.

**Comment by shoulders** [comment]
@jcameron it is in the first post, lol. I will do it in pictures.

![image](https://github.com/user-attachments/assets/58310b15-11b0-48af-ac92-dbfc90bf607f)

![image](https://github.com/user-attachments/assets/9615684c-80b5-46d7-a5ff-fa48a7b8aace)

![image](https://github.com/user-attachments/assets/fde55fc7-358b-44c3-bdea-343c5aa47b2e)

![image](https://github.com/user-attachments/assets/c1eb7c50-9e1b-40b9-b8d9-565427714497)

**Comment by iliajie** [comment]
>  <img width="749" alt="image" src="https://github.com/user-attachments/assets/7aba7c0b-44a7-4e86-8d9f-1408f4c3e5c5">

I remember fixing that. It won’t display the "System Information" table if the specific user isn’t allowed to see it. Copy system information button isn't working expectedly in this case.

**Comment by jcameron** [comment]
@iliajie will this fix be in the next Webmin release?

**Comment by iliajie** [comment]
This issue will be fixed in the next releases. Thanks for the heads up!
