### ISSUE TITLE
Filemin ignores file write permissions

### ISSUE THREAD

**Issue by JoseGoncalves** [webmin/webmin#2300]
I have created a Webmin priviledged user to use Filemin in a way that he could only access files in `/srv/tftp` executing as `tftp` user. That user can read/add/edit files without any issue. The problem is that I have some files that I want to be read-only for that user, and have setup permissions accordingly (user=tftp, group=tftp, perms=444) but it seems that Filemin completly ignores those files permissions and I can write and delete them. I have this config in my `user.acl` file:
```
work_as_root=0
allowed_paths=$HOME
max=
work_as_user=tftp
allowed_for_edit=text-plain
```
According to info received [here](https://forum.virtualmin.com/t/filemin-ignores-file-write-permissions/130040), the file permissions are ignored because;

> the Webmin privileged user is effectively root by default

I would like to request that, when the `work_as_user` configuration option is used, Filemin would query the filesystem to check which files/folders he can write when executing as that user, to avoid unintended overwrite/delete of files & folders.

**Comment by iliajie** [comment]
Hello,

Thanks for the heads up!



> I would like to request that, when the `work_as_user` configuration option is used

I think it can be tricky, as the Webmin privileged user might operate without an underlying Unix user, while the Webmin safe user requires a corresponding Unix user to handle permissions naturally.

**Comment by JoseGoncalves** [comment]
Hi @iliajie. I've created a `tftp` webmin safe user and verified that it also can write/delete files that don't have the write attribute for the `tftp` user. It seems that file permissions are also ignored for webmin's safe users.

**Comment by iliajie** [comment]
Do you get the same issue when using the Frame theme?

**Comment by JoseGoncalves** [comment]
Yes. Exactly the same behavior.

**Comment by JoseGoncalves** [comment]
Hi @iliajie.  Do you have plans to address this issue soon?

I'm asking this because, if not, I will need to dig into filemin sources to try to fix it or, at leaset, find a workaround that works for my use case (I have no Perl coding skills, so it will be challeging for me).

**Comment by iliajie** [comment]
> Hi @iliajie. Do you have plans to address this issue soon?
> 
> I'm asking this because, if not, I will need to dig into filemin sources to try to fix it or, at least, find a workaround that works for my use case (I have no Perl coding skills, so it will be challenging for me).

I’ll take a look later — I haven’t forgotten, just caught up with running tests for the new Virtualmin release.

**Comment by iliajie** [comment]
Alright, I found a bug and fixed it in this patch https://github.com/webmin/webmin/commit/83457fe4c06084a3aa3d9c5587cf63a19db78385.

For now, it will only work correctly with the old Framed Theme. I’ll also need to fix it for the Authentic Theme, which will require additional work. I’ll update this ticket once it’s ready...

**Comment by iliajie** [comment]
Though, now I’m thinking this should be an option, because deleting a file in a directory for which a user has write permissions—even if the file is owned by another user—is allowed in Linux!

[Jamie](@jcameron ), what are your thoughts? Should we, by default, disallow a normal user from deleting files they don’t own? For example, a file owned by root in the user’s home directory?

**Comment by iliajie** [comment]
…on the other hand, editing a file should definitely not be allowed, but what about deleting—I think now it might be better to stick to the default behavior of Linux...

**Comment by iliajie** [comment]
Alright, I’ve added https://github.com/webmin/webmin/commit/d2db00a5d1be79fd396a67815faf329bea2fb6cc a new ACL option to enforce strict user ownership checks. This will enforce permission checks for regular users, even in directories they have write access to. It will be enabled by default for a safe Webmin user.

I’m now integrating this check into the Authentic Theme.

**Comment by iliajie** [comment]
This has been fully implemented. You can try the latest [Webmin nightly version](https://download.webmin.dev/) to preview this feature.
