### ISSUE TITLE
502 bad gateway

### ISSUE THREAD

**Issue by 6emmestudio** [webmin/webmin#2301]
Hi, I have a problem with all the sites with the third-level domain .developers.site on my server.
In all cases I get a 502 BAD GATEWAY error screen. An example can be seetuscany.develovers.site
What is it?

**Comment by iliajie** [comment]
Hello,

This is the issue tracker, not the right place for questions. Please post your questions in our Virtualmin Community forum.

http://forum.virtualmin.com
