### ISSUE TITLE
postfix - Add IPv4 and IPv6 protocol handling settings

### ISSUE THREAD

**Issue by shoulders** [webmin/webmin#2302]
| SYSTEM INFORMATION ||
|----------|----------|
|  OS type and version |  Ubuntu Linux 22.04.5              |
|  Usermin version     |  2.102                             |
|  Virtualmin version  |  7.20.2 Pro                        |
|  Theme version       |  21.20.7                           |
|  Apache version      |  2.4.52                            |
|  Package updates     |  13 package updates are available  |

## The Background

By default Postfix accepts and sends emails by IPv6 and IPv4 with a preference for IPv6.

The protocol handling seems to be handled by the following settings shown below with their defaults:

- **[inet_protocols](https://www.postfix.org/postconf.5.html#inet_protocols) = all**
  - The Internet protocols Postfix will attempt to use when making or accepting connections.
  - When both IPv4 and IPv6 support are enabled, the Postfix SMTP client will choose the protocol as specified with the [smtp_address_preference](https://www.postfix.org/postconf.5.html#smtp_address_preference) parameter. Postfix versions before 2.8 attempt to connect via IPv6 before attempting to use IPv4.
- **[smtp_address_preference](https://www.postfix.org/postconf.5.html#smtp_address_preference) = any**
  - The address type ("ipv6", "ipv4" or "any") that the Postfix SMTP client will try first, when a destination has IPv6 and IPv4 addresses with equal MX preference. This feature has no effect unless the [inet_protocols](https://www.postfix.org/postconf.5.html#inet_protocols) setting enables both IPv4 and IPv6.
- **[smtp_balance_inet_protocols](https://www.postfix.org/postconf.5.html#smtp_balance_inet_protocols) = yes**
  - When a remote destination resolves to a combination of IPv4 and IPv6 addresses, ensure that the Postfix SMTP client can try both address types before it runs into the [smtp_mx_address_limit](https://www.postfix.org/postconf.5.html#smtp_mx_address_limit).

There are also LMTP equivalent versions of these settings.

There might be more related settings

## The issue that caused me to find these settings missing

I run my Virtualmin server on an IPv4 only network yet it still tries to use a `AAAA` MX record if it is available.

You can see the following errors in the mail queue where the emails are deferred:

![image](https://github.com/user-attachments/assets/480f4561-b2ec-4a96-adf6-413cbd8136a6)

> Host or domain name not found. Name service error for name=example-co-uk.mail.protection.outlook.com type=AAAA: Host not found, try again

After research the settings mentioned in `the background` need to be modified to remove IPv6 lookups.

> this is not a support request for this as I will solve this myself via the `main.cf` by disabling the IPv6 protocol where needed.

## Feature Request

These settings can be set via the `main.cf` config file but because of their importance in configuring what protocols that Postfix works on they should have their settings in the GUI so a user can enable/disable the support of IPv6 and IPv4.

In Postfix maybe create a new section call `Protocols` or `Network`.

![image](https://github.com/user-attachments/assets/5ea694be-0b97-4a6f-84b7-51873bde9f61)

## Additional

When Virtualmin is installed, maybe there should be an option to select your protocol environment i.e.:
- IPv6+ IPv4
- IPv6
- IPv4

**Comment by jcameron** [comment]
Oh that's a good idea - I'm actually surprised we never added support for the `inet_protocols` field. I'll look into adding UI elements for all of these.

**Comment by jcameron** [comment]
Ok these will be in the next release.
