### ISSUE TITLE
Postfix - flush queue button - Does not show results

### ISSUE THREAD

**Issue by shoulders** [webmin/webmin#2303]
| SYSTEM INFORMATION ||
|----------|----------|
|  OS type and version |  Ubuntu Linux 22.04.5              |
|  Usermin version     |  2.102                             |
|  Virtualmin version  |  7.20.2 Pro                        |
|  Theme version       |  21.20.7                           |
|  Apache version      |  2.4.52                            |
|  Package updates     |  46 package updates are available  |

## the issue

when I clicked the `Flush Queue` button I got the following page with no results, however the emails were flushed and sent as expected.

`Webmin -->  Servers --> Postfix Mail Server --> Mail Queue --> Flush Queue`

![image](https://github.com/user-attachments/assets/16b1e6f4-d577-4110-bf6c-ab60c2614115)

## proposed solution

Apply a fix to show the results of the flush onscreen as mentioned on the Queue page.

**NB:** as I no longer have any emails in the queue I do not have the buttons to take a screenshot of them.

**Comment by jcameron** [comment]
Last I checked, we couldn't do this because the `postqueue -f` command doesn't output any progress. Instead it just kicks off a flush of the queue in the background.

**Comment by shoulders** [comment]
On the page with the button I am sure it says it will flush the queue and show the results, also if you see in the picture there clearly is a section for the results.

**Comment by jcameron** [comment]
Sounds like I just need to fix the wording to make it clearer that no progress messages will be shown..

**Comment by shoulders** [comment]
And remove that area that looks like it should have the results in it .

**Comment by jcameron** [comment]
Ah yes, I'll drop that
