### ISSUE TITLE
Configure Apache Modules - If you make changes and navigate away there is no warning

### ISSUE THREAD

**Issue by shoulders** [webmin/webmin#2304]
| SYSTEM INFORMATION ||
|----------|----------|
|  OS type and version |  Ubuntu Linux 22.04.5              |
|  Usermin version     |  2.102                             |
|  Virtualmin version  |  7.20.2 Pro                        |
|  Theme version       |  21.20.7                           |
|  Apache version      |  2.4.52                            |
|  Package updates     |  31 package updates are available  |

On the following page if you make any changes and navigate away you do not get the standard your changes will be lost message.

 `Servers --> Apache Webserver --> Global Configuration --> Configure Apache Modules`

![image](https://github.com/user-attachments/assets/d0b6fefc-287d-4e18-b6c8-9a8fb6696bd2)

**Comment by jcameron** [comment]
@iliajie I believe you implemented this in the authentic theme. Can you take a look?

**Comment by iliajie** [comment]
Hello,

Thanks for the heads up!

I found the source of the issue and fixed it!
