### ISSUE TITLE
MariaDB System Variables - Cannot edit

### ISSUE THREAD

**Issue by shoulders** [webmin/webmin#2305]
| SYSTEM INFORMATION ||
|----------|----------|
|  OS type and version |  Ubuntu Linux 22.04.5              |
|  Usermin version     |  2.102                             |
|  Virtualmin version  |  7.20.2 Pro                        |
|  Theme version       |  21.20.7                           |
|  Apache version      |  2.4.52                            |
|  Package updates     |  46 package updates are available  |

## the issue

there is an edit button but no way of selecting an item to edit, i.e. no check boxes. This is the same if the whole list is displayed or filtered results.

`Webmin --> Servers --> MariaDB Database Server --> MariaDB System Variables`

![image](https://github.com/user-attachments/assets/c0b65aa7-6cde-4f17-b4c0-3e51c1a990d8)

![image](https://github.com/user-attachments/assets/b1bea66a-b831-42f7-974e-5304e1d99be1)

## proposed solution

fix the missing checkboxes

## additional

- should you be allowed to select more than one item?
- Why are these only temporary changes? Tis might be my inexperience showing

**Comment by jcameron** [comment]
The missing checkboxes are intentional - some variables cannot be edited on that page, only on the Server Configuration page.

**Comment by shoulders** [comment]
Ok I found the checkboxes, there are not many.

Can I suggest adding an option to only show editable options. This would make this page more logical and easier to use.
