### ISSUE TITLE
MariaDB Server Configuration - add `sql_mode`

### ISSUE THREAD

**Issue by shoulders** [webmin/webmin#2306]
| SYSTEM INFORMATION ||
|----------|----------|
|  OS type and version |  Ubuntu Linux 22.04.5              |
|  Usermin version     |  2.102                             |
|  Virtualmin version  |  7.20.2 Pro                        |
|  Theme version       |  21.20.7                           |
|  Apache version      |  2.4.52                            |
|  Package updates     |  46 package updates are available  |

## the feature request

I would like the option to change `sql_mode` from the webmin GUI

`Webmin --> Servers --> MariaDB Database Server --> MariaDB Server Configuration`

## why

I have some old apps and to get them to work I need to change `sql_mode` as follows

This is default and has nothing in the config files
> STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION

to

add this line somewhere in the config files
> sql_mode="ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"

**Comment by jcameron** [comment]
Where is this `sql_mode` stored/used though? is it in some config file, or the connection string?

**Comment by shoulders** [comment]
On a default server setup it does not have a physcal presence in a config file because it is a default setting.

If you use postconf equivalent for mariadb you probably can see it.

If you use the GUI option in webmin and look at mariadb sever variables I think it is there.

So this variable is handled like many others and inbuilt default with no config option required unless you want to change from the default.

The changed file I believe would go in /etc/.../my.cnf

I am away from pc so cannot give exact location but I might of mentioned it above.

**Comment by jcameron** [comment]
Do you think we should add a UI for selecting those options like STRICT_TRANS_TABLES and ERROR_FOR_DIVISION_BY_ZERO, or just make it a free text field?

**Comment by shoulders** [comment]
Definitely a free text field

There is a massive amount of options and checkboxes would be confusing and incomplete.

https://mariadb.com/kb/en/sql-mode/#sql_mode-values

**Comment by jcameron** [comment]
Ok look for this in the next release!

**Comment by shoulders** [comment]
When I tried doing a backup through virtualmin I got an error because the following line was in `my.cnf`

## the line in `my.cnf`
> sql_mode="ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"

## The error
> /usr/bin/mysqldump: unknown variable 'sql_mode=ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'

## Additional

The error log onscreen
- did not record any error summary at the end
- and stopped after it could not dump one of my sub-servers on `quantumwarp.com` which I think was the first with a Database it came across.

![image](https://github.com/user-attachments/assets/67683858-7da3-4362-8a79-e999a2430fd0)

**Comment by jcameron** [comment]
What section of your `my.cnf` file was that `sql_mode` line in?

**Comment by shoulders** [comment]
I just put it at the bottom of the file as follows

<details>

```
# The MariaDB configuration file
#
# The MariaDB/MySQL tools read configuration files in the following order:
# 0. "/etc/mysql/my.cnf" symlinks to this file, reason why all the rest is read.
# 1. "/etc/mysql/mariadb.cnf" (this file) to set global defaults,
# 2. "/etc/mysql/conf.d/*.cnf" to set global options.
# 3. "/etc/mysql/mariadb.conf.d/*.cnf" to set MariaDB-only options.
# 4. "~/.my.cnf" to set user-specific options.
#
# If the same option is defined multiple times, the last one will apply.
#
# One can use all long options that the program supports.
# Run program with --help to get a list of available options and with
# --print-defaults to see which it would actually understand and use.
#
# If you are new to MariaDB, check out https://mariadb.com/kb/en/basic-mariadb-articles/

#
# This group is read both by the client and the server
# use it for options that affect everything
#
[client-server]
# Port or socket location where to connect
# port = 3306
socket = /run/mysqld/mysqld.sock

# Import all .cnf files from configuration directory
!includedir /etc/mysql/conf.d/
!includedir /etc/mysql/mariadb.conf.d/

# Added to allow null entries for QWcrm - remove when upgraded
sql_mode="ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
```

</details>

**Comment by jcameron** [comment]
It needs to be in the `[mysqld]` section

**Comment by shoulders** [comment]
> It needs to be in the `[mysqld]` section

This is why I need it in the GUI, lol

In the meantime, I don't have this section in my file, do I just create it at the bottom on `my.cnf`` ?

tar

**Comment by jcameron** [comment]
Yes you can add that section
