### ISSUE TITLE
MariaDB Database Server - add a restart buttom

### ISSUE THREAD

**Issue by shoulders** [webmin/webmin#2309]
| SYSTEM INFORMATION ||
|----------|----------|
|  OS type and version |  Ubuntu Linux 22.04.5              |
|  Usermin version     |  2.102                             |
|  Virtualmin version  |  7.20.2 Pro                        |
|  Theme version       |  21.20.7                           |
|  Apache version      |  2.4.52                            |
|  Package updates     |  31 package updates are available  |

## The request

On the page `Webmin --> servers --> MariaDB Database Server` can you add a restart button

thanks

**Comment by jcameron** [comment]
Good idea, I'll add this for the next release.
