### ISSUE TITLE
System Dashboard does not display CPU and disk information on macOS (read desc)!

### ISSUE THREAD

**Issue by william-texas** [webmin/webmin#2311]
I am trying out webmin as I want to use it for an upcoming project that will be hosted on an M4 Mac mini. I was trying to use it today but it only will show the Real memory usage on the system dashboard. 

<img width="1228" alt="Screenshot 2024-11-10 at 11 56 23 PM" src="https://github.com/user-attachments/assets/271c5a64-ffd7-470c-968a-a307e8512133">

I believe that this may be due to an issue with the file webmin/proc/macos-lib.pl. It seems that the way you access information about the system's CPU has changed since this file was created (8 years ago), with "sysctl -n machdep.cpu.vendor" and "sysctl -a machdep.cpu.cache.size" being deprecated. The latter can be replaced with "sysctl -a hw.l2cachesize". 

Hopefully this helps you crack the issue. I would love to be able to use webmin for my next project.

**Comment by iliajie** [comment]
Hello,

What’s the output of the `uptime` command on your system? Also, do you see CPU info if you switch to the old Framed Theme?

**Comment by iliajie** [comment]
But first, try applying this patch and see if it changes anything for you:

```
webmin patch https://github.com/webmin/webmin/commit/9501220
```

**Comment by iliajie** [comment]
Is this already a production system? If not, I’d like to take a closer look at the problem by logging in remotely. Would that be possible?

**Comment by william-texas** [comment]
This is not a production system. I'm running this on my laptop right now to get a feel for webmin before I deploy it. You can remote in if you'd like, only for the next 75 ish minutes.

**Comment by william-texas** [comment]
<img width="1692" alt="Screenshot 2024-11-11 at 10 04 09 AM" src="https://github.com/user-attachments/assets/2b076673-2d44-4d87-8e8f-710f69af74d1">

Here is my webmin error console as well. hopefully something in here can be useful.

**Comment by iliajie** [comment]
I don’t understand why the CPU info isn’t displaying—it should be.

Can you go to "Webmin ⇾ Webmin Users: Edit Webmin User" page, open the "Available Webmin modules" accordion, click on "System Status" module, and check if all the relevant stats are enabled to be shown?

**Comment by william-texas** [comment]
<img width="805" alt="image" src="https://github.com/user-attachments/assets/900d3a52-816a-485e-9a93-4c138bbbf973">

It was set to Everything by default. If I change it to something else that was not previously there, e.g. free disk space, then the system information dashboard becomes a blank panel.

<img width="1373" alt="image" src="https://github.com/user-attachments/assets/340a277d-1fbc-479e-a1be-bc518cba89c0">

**Comment by iliajie** [comment]
Are you on macOS Sequoia?

**Comment by william-texas** [comment]
Yes, 15.1.

**Comment by iliajie** [comment]
Alright, I had to get a dedicated macOS Server to fix it. Try it out with the nightly Webmin version.

https://download.webmin.dev/webmin-latest.tar.gz

**Comment by william-texas** [comment]
Awesome, it works. Thank you! it doesn't display virtual memory but I don't really care about that. I have also noticed that the terminal does not behave properly on webmin (inconsistent spacing of the terminal).
<img width="1269" alt="image" src="https://github.com/user-attachments/assets/38a1141f-d713-4a95-a943-ad98508454cd">


Should I open a new issue for this as well, or is this expected behavior?

**Comment by william-texas** [comment]
I also did notice that Disk I/O monitoring does not work even on this nightly build.

**Comment by iliajie** [comment]
For now, I didn’t add disk IO support; instead, I’ve patched it so that related graphs won’t display if not supported.

It’s unclear how to implement this cleanly. `iostat -K 1 2` doesn’t seem to provide data in the same format as FreeBSD, where it shows separate read/write values.

Network I/O, I just made to work, but it also differs from FreeBSD and missing an extra `Idrop` column.

For example:
```
# macOS
Name       Mtu   Network   Address    Ipkts Ierrs          Ibytes    Opkts Oerrs     Obytes  Coll

# FreeBSD
Name       Mtu   Network   Address    Ipkts Ierrs   Idrop  Ibytes    Opkts Oerrs     Obytes  Coll
```

The good thing is that we can just grab things from the back, and it still works.

So, if you have any ideas on how to get disk I/O working on macOS, please let me know—I’m open to suggestions.

**Comment by william-texas** [comment]
Perhaps the command `fs_usage` would be good for this operation. using the parameters `-f -w diskio`, we can see in this order:
`
Timestamp        Operation type (r/w)     Disk block number     Byte count (hex)       Device       Pathname     Elapsed time     Process name
`
This requires sudo privileges but I don't think that should be an issue?

**Comment by iliajie** [comment]
I've also fixed that deprecated `sysctl -a machdep.cpu.cache.size` call.

**Comment by iliajie** [comment]
Alright, I have finished all deep tests and it's working just fine for me! Please open a new ticket for Terminal issue. I have no clue what's wrong with it!

**Comment by william-texas** [comment]
Thank you so much for fixing it!

**Comment by iliajie** [comment]
You’re welcome — let me know if you find any bugs though…

**Comment by rcfa** [comment]
Hm, just found this thread since I noticed 2.202 only show RealMemory and VirtualMemory on the dashboard, not CPU and DiskUsage.
Tried installing the latest dev build, but no luck...
