### ISSUE TITLE
MariaDB System Variables - Add editable options filter with a checkbox

### ISSUE THREAD

**Issue by shoulders** [webmin/webmin#2319]
| SYSTEM INFORMATION ||
|----------|----------|
|  OS type and version |  Ubuntu Linux 22.04.5              |
|  Usermin version     |  2.102                             |
|  Virtualmin version  |  7.20.2 Pro                        |
|  Theme version       |  21.20.7                           |
|  Apache version      |  2.4.52                            |
|  Package updates     |  46 package updates are available  |

## the feature request

On the following page add a filter option just to show the editable options, perhaps in the form of a checkbox.

`Webmin --> Servers --> MariaDB Database Server --> MariaDB System Variables`

![image](https://github.com/user-attachments/assets/b1bea66a-b831-42f7-974e-5304e1d99be1)

## Related Github issues

MariaDB System Variables - Cannot edit #2305

**Comment by iliajie** [comment]
Hello,

No need for a filter. We should just place “edible” at the top of the table. This has been fixed in the latest commit.

Thanks for the heads-up!
