### ISSUE TITLE
Problem with quotas

### ISSUE THREAD

**Issue by manfer** [webmin/webmin#233]
If I create a virtualserver with a package that has a quota of 1GB and later a decide to set a higher quota -without changing package, just a custom quota- on that particular virtualserver, lets say 5GB, the quota limit remains 1GB because the owner group quota is not changed to 5GB, only the owner user quota is changed to 5GB.

I have to change the group quota myself with
```
edquota -g
```

It wouldn't be so much of a problem but if I decide later -and this can be months later when I totally forgot about the issue- that I need to change any other option of the virtualserver, then my configured quota for the virtualserver owner group is overwritten again into 1GB limit, both soft and hard limits. It is reverted to the package quota limit not taking into account the configured custom quota.

Well, to be honest, I'm not sure if the first time I had to change the user limit too but if I did it was on the virtualserver admin not in a terminal. And what I'm totally sure is that the user quota limit is not reverted back to the package limit when saving changes to the virtualserver, it remains the custom configured quota, but the group quota limit is reverted to the package quota limit which is annoying.

Webmin 1.760, Virtualmin 4.17.gpl, running on Centos 6.6 32bits.

(sorry if the issue doesn't belong here. It is a virtualmin issue so I'm not sure if it belongs here or not)

**Comment by qooob** [comment]
Have you tried to Re-check Virtualmin Configuration after changing quota and/or clear cache on System Information page? I guess, it's the cache issue.

**Comment by manfer** [comment]
Not sure if I understand what you mean. It is not that the quota is shown incorrectly in the admin interface is the group quota the one that I can confirm is set to 1GB, the package quota limit, instead of using the custom configured 5GB quota limit.

This happens when doing any change to the virtualserver. And I start getting quota excedeed errors everywhere for that virtualserver just after that.

Then I check the group quota for the owner of that virtualserver and I see it was set to 1GB, the package limit, instead of the configured 5GB.

**Comment by jcameron** [comment]
There are two quota settings on the Edit Virtual Server page - one for the user and one for the group/domain. The user limit will apply only to the domain owner, but the group limit applies to the sum of all mailboxes and the domain owner.

**Comment by manfer** [comment]
I rechecked all settings and all were correct. Both quota limits in edit server, Total server quota and Server administrator's quota, are set to 5GB.

I edited the server again and the group quota has not been changed this time.

So I don't know what really happened. I'm going to close this issue until I find out the sequence to reproduce the issue.

Sorry.
