### ISSUE TITLE
Smart module not working on the latest version of Webmin

### ISSUE THREAD

**Issue by risingfish** [webmin/webmin#2331]
Previous to the 2.202 version of Webmin, the SMART module has worked fine. The system is running a AMD Ryzen 7 2700 and an AMD B450 based motherboard (I don't remember the exact vendor, but will look it up if needed). Webmin is showing that no drives were sound

![image](https://github.com/user-attachments/assets/30c3188c-2384-429a-bfda-1e106fb716e5)

The system is running on Ubuntu Server 22.04 and has the smartmontools package installed. 
![image](https://github.com/user-attachments/assets/8d72eb32-5d82-4a2d-b4f3-88a9e6f93123)

Running `smartctl --scan-open` in a terminal on the system shows the following output:

![image](https://github.com/user-attachments/assets/a99deb9b-7f79-48b4-8065-18168e365c60)

**Comment by jcameron** [comment]
Can you post a screenshot of the page at Hardware -> Partitions on Local Disks ?

**Comment by risingfish** [comment]
Dang, fdisk is missing. A system update uninstalled a few other things (including networking), that I had to go through and fix. Apparently fdisk was one of them.

![image](https://github.com/user-attachments/assets/8bbcd8e7-2a50-45a4-95c5-11f84c9df6b5)

It working again after resintalling. Thank you!
