### ISSUE TITLE
MySQL/MariaDB module—Main config has multiple extra lines

### ISSUE THREAD

**Issue by iliajie** [webmin/webmin#2333]
Hello Jamie!

When the main MySQL/MariaDB config is edited via the Webmin MySQL module API, it adds a lot of extra lines. This can be observed on all Virtualmin systems, e.g.:

<img width="772" alt="image" src="https://github.com/user-attachments/assets/4bb73a5d-7b23-475f-9157-26ca91864af3" />

**Comment by jcameron** [comment]
Do you mean all the blank lines after the `[server]` block? Yeah that does seem odd ...

**Comment by iliajie** [comment]
Yeah, all blank lines around all blocks, it's not just limited to `[server]` block.

**Comment by jcameron** [comment]
What action in Webmin / Virtualmin is triggering this?

**Comment by iliajie** [comment]
I’m not sure exactly, but I do know that over time it accumulates multiple empty lines. It seems like every time the config is saved, another extra line gets added.

**Comment by jcameron** [comment]
I'm having trouble re-producing this, or even seeing in the code how it could happen!

**Comment by iliajie** [comment]
No worries, I will hunt it down then.

**Comment by jcameron** [comment]
Or if you can let me know what actions trigger this, I should be able to repro it

**Comment by iliajie** [comment]
I simply do not know yet. I’ve just noticed it happening over time, but I haven’t looked into it deeply yet...

**Comment by iliajie** [comment]
I found the bug. It was caused by the comments being removed, e.g.:


https://github.com/user-attachments/assets/9ca75fdb-4fab-47d6-92b9-73e3aa897ab0

The fix is here https://github.com/webmin/webmin/commit/2732142969a1982bc99b619615cdb0d419487b7d.

Please have a look!

**Comment by jcameron** [comment]
Thanks!

**Comment by iliajie** [comment]
You’re welcome. I’m closing it then.
