### ISSUE TITLE
Creating a new virtual host for Apache Webserver module doesn't update the apache ports.conf file

### ISSUE THREAD

**Issue by wangoland** [webmin/webmin#2341]
I'm running Webmin version 2.202 and I've noticed if you create a new Virtual Host via the Apache Webserver module using a custom port this port won't be added to the apache ports.conf configuration file, so you can't access the virtual host until this step is carried out.

Is it possible to update the module so that if you create a Virtual Host that uses a port which hasn't yet been added to ports.conf file this is carried out automatically?

**Comment by jcameron** [comment]
What directives does the `ports.conf` file contain? Virtualmin should add a `Listen` line for any new ports.

**Comment by wangoland** [comment]
Hey Jamie, 
`/etc/apache2/ports.conf` contains the following:

```
# If you just change the port or add more ports here, you will likely also
# have to change the VirtualHost statement in
# /etc/apache2/sites-enabled/000-default.conf

Listen *:80
Listen *:81
Listen *:82
Listen *:83

<IfModule ssl_module>
    Listen 443
</IfModule>

<IfModule mod_gnutls.c>
    Listen 443
</IfModule>

# vim: syntax=apache ts=4 sw=4 sts=4 sr noet
```
I've had to add those lines manually as Virtualmin didn't do it automatically

**Comment by jcameron** [comment]
On the virtual host creation form, did you check the box "Listen on address (if needed)" ?

**Comment by wangoland** [comment]
Yep, and that's checked by default when I load the form too

**Comment by jcameron** [comment]
Are you entering a "Specific address" to listen on for this virtual host, or is "Any address" selected?

**Comment by wangoland** [comment]
![image](https://github.com/user-attachments/assets/cc0350c1-dd86-4669-90d8-72f1174abc88)
Any address is selected

**Comment by jcameron** [comment]
Ok I see what's going on here - I'll fix this for the next Webmin release.
