### ISSUE TITLE
webmin-setup-repos.sh not working - whole code removed

### ISSUE THREAD

**Issue by balepari** [webmin/webmin#2347]
I've noticed that in your last commit of webmin-setup-repos.sh, the whole code of the script was screwed up. Now there's only 2 commented lines... with this script no one can install webmin via repos.

**Comment by iliajie** [comment]
The link is active and provides the details that should be used, i.e. a new download link. Isn’t it enough?

**Comment by LordGeorge-1992** [comment]
Yeah noticed the same,
For now i have pulled the file prior to the commit,

For anyone else who struggles untill its fixed.

Previous version.
https://github.com/webmin/webmin/blob/599d0967837a8f47290dc2b6f839d00fd6c2fdaf/webmin-setup-repos.sh
git the file down, or copy raw and replace the webmin-setup-repos.sh contence.
Then chmod +x the file
Finally execute webmin-setup-repos.sh

**Comment by LordGeorge-1992** [comment]
> The link is active and provides the details that should be used, i.e. a new download link. Isn’t it enough?

For people who are comfortable using linux its okay, running a curl and apt-get and finding no repo with no error in sight will throw off most users who arent so adept.

**Comment by iliajie** [comment]
> git the file down, or copy raw and replace the webmin-setup-repos.sh contence.
> Then chmod +x the file
> Finally execute webmin-setup-repos.sh


That’s not the right solution—you should download `webmin-setup-repos.sh` file instead.

Though, I will make the old links work without duplicating the code. Thanks for the heads up.

**Comment by iliajie** [comment]
Fixed here https://github.com/webmin/webmin/commit/c6b216ee32cbca1be2ceb9fd674c4f874928ab8c.
