### ISSUE TITLE
Two-factor authentication dropped when saving Webmin user

### ISSUE THREAD

**Issue by qooob** [webmin/webmin#235]
Jamie, everytime, after upgrading Webmin, Two-factor authentication (Google) gets reset.

What is worth, it shows you the third box on the login screen, and you can enter any numbers there and it will work. However, when going to `Edit Webmin User` and looking at `Security and limits options` you can see the correct message: `Two-factor authentication type: None setup yet`. (Like I said, it was setup before actually but was dropped after update.)

Please fix that. 

Also having two-factor authentication in Usermin is a must. Thank you.

**Comment by jcameron** [comment]
How did you do the upgrade? Because the regular process shouldn't touch the two-factor setting at all..

**Comment by qooob** [comment]
As far as I remember I used Webmin popup (on System Information) to upgrade.

**Comment by jcameron** [comment]
So I did some testing, but wasn't able to re-produce this bug (or see how it could happen based on the upgrade code).

**Comment by qooob** [comment]
Is this possible to add `+i` attribute on those files that contain data about auth? In case it's the separate file it would be possible. Where to look at?

**Comment by jcameron** [comment]
They are stored in the main config file /etc/webmin/miniserv.conf

**Comment by qooob** [comment]
Is it changed upon upgrade?

**Comment by qooob** [comment]
Does it have to be writable? `chattr +i` on it  won't break the installation of rpm?

**Comment by jcameron** [comment]
It may break the install, as sometimes new directives get added to the miniserv.conf file as part of the install process.

**Comment by qooob** [comment]
Alright, I will do more testing. Thanks, Jamie!

**Comment by qooob** [comment]
Jamie, finally it's figured out where the problem was.

https://github.com/qooob/authentic-theme/issues/270

..any time you save Webmin user two factor authentication is dropped in every single theme! Please fix! ;)

**Comment by jcameron** [comment]
Ok, I see the bug - this will be fixed in the next release of Webmin.
