### ISSUE TITLE
BSD-Firewall

### ISSUE THREAD

**Issue by jwhulette** [webmin/webmin#236]
OS: FreeBSD 10.1-RELEASE-p15 on amd64
Webmin Version: 1.760

I manually added ipfw firewall rules to the rc.conf file: 
firewall_enable="YES"
firewall_quiet="YES"
firewall_type="workstation"
firewall_myservices="22 80"
firewall_allowservices="any"
firewall_logdeny="YES"
I also, tried firewall_script="/usr/local/etc/webmin/ipfw/ipfw.rules", same issue
When clicking on the BSD Firewall module, I get the error swap_pager: out of swap space. 

If I remove the firewall settings from rc.config file, I can get to the module but the module show, "An error occurred fetching the active firewall rules using the command /sbin/ipfw list : "

**Comment by jcameron** [comment]
That "out of swap space" message indicates that Webmin went into an infinite loop parsing your firewall config. Can you attach your ipfw.rules file to this ticket?

**Comment by jwhulette** [comment]
Ok, I removed the firewall config from my rc.conf file and restarted ipfw. Which gave me a default set of rules which blocked everything. I stopped the ifpw service, went to the BSD Firewall module and it found those rules and copied them into the webmin ipfw.rules file. 
I added a new rule to let webmin through, clicked apply, ipfw did not start, I started manually from the command line and it loaded the default rules, not from webmin as my rule to allow port 10000 was not listed. I selected Start at boot in the module, it did not put anything in the rc.conf file. 

I selected start at boot from the Bootup & Shutdown module for ipfw and it put the entry ipfw_enable="YES" in the rc.conf. This is incorrect according to the documentation, https://www.freebsd.org/doc/handbook/firewalls-ipfw.html

I then put this in the rc.conf file:
firewall_enable="YES"
firewall_script="/usr/local/etc/webmin/ipfw//ipfw.rules"
Start the ipfw service, and every rule erred out with not found. 
This may be because the ipfw.rules file is missing ipfw -q add at the beginning of each rule which is needed according to the documentation.

I hope this helps.

**Comment by jcameron** [comment]
Thanks for the info - it sounds like the format has changed between the FreeBSD version I originally tested with, and 10.1. However, Webmin already sets firewall_enable in rc.conf instead of ipfw_enable though.. are you sure you're running version 1.760 ?

**Comment by jwhulette** [comment]
I am using Webmin 1.760. BSD Firewall IPFW version 1. OS: FreeBSD 10.1-RELEASE-p15
In the BSD Firewall module, clicking activate at boot, refreshes screen, no errors, nothing written to rc.conf file. In Bootup & Shutdown module, clicking on IPFW and selecting start on boot writes, ipfw_enable="YES" to rc.conf. Odd because the script shows:
#!/bin/sh
#
# $FreeBSD: releng/10.1/etc/rc.d/ipfw 250804 2013-05-19 04:10:34Z jamie $
#

# PROVIDE: ipfw
# REQUIRE: ppp
# KEYWORD: nojailvnet

. /etc/rc.subr
. /etc/network.subr

name="ipfw"
rcvar="firewall_enable"
start_cmd="ipfw_start"
start_precmd="ipfw_prestart"
start_postcmd="ipfw_poststart"
stop_cmd="ipfw_stop"
required_modules="ipfw"

set_rcvar_obsolete ipv6_firewall_enable

ipfw_prestart()
{
	if checkyesno dummynet_enable; then
		required_modules="$required_modules dummynet"
	fi
	if checkyesno natd_enable; then
		required_modules="$required_modules ipdivert"
	fi
	if checkyesno firewall_nat_enable; then
		required_modules="$required_modules ipfw_nat"
	fi
}

ipfw_start()
{
	local   _firewall_type

	_firewall_type=$1

	# set the firewall rules script if none was specified
	[ -z "${firewall_script}" ] && firewall_script=/etc/rc.firewall

	if [ -r "${firewall_script}" ]; then
		/bin/sh "${firewall_script}" "${_firewall_type}"
		echo 'Firewall rules loaded.'
	elif [ "`ipfw list 65535`" = "65535 deny ip from any to any" ]; then
		echo 'Warning: kernel has firewall functionality, but' \
		    ' firewall rules are not enabled.'
		echo '           All ip services are disabled.'
	fi

	# Firewall logging
	#
	if checkyesno firewall_logging; then
		echo 'Firewall logging enabled.'
		sysctl net.inet.ip.fw.verbose=1 >/dev/null
	fi
	if checkyesno firewall_logif; then
		ifconfig ipfw0 create
		echo 'Firewall logging pseudo-interface (ipfw0) created.'
	fi
}

ipfw_poststart()
{
	local	_coscript

	# Start firewall coscripts
	#
	for _coscript in ${firewall_coscripts} ; do
		if [ -f "${_coscript}" ]; then
			${_coscript} quietstart
		fi
	done

	# Enable the firewall
	#
	if ! ${SYSCTL} net.inet.ip.fw.enable=1 1>/dev/null 2>&1; then
		warn "failed to enable IPv4 firewall"
	fi
	if afexists inet6; then
		if ! ${SYSCTL} net.inet6.ip6.fw.enable=1 1>/dev/null 2>&1
		then
			warn "failed to enable IPv6 firewall"
		fi
	fi
}

ipfw_stop()
{
	local	_coscript

	# Disable the firewall
	#
	${SYSCTL} net.inet.ip.fw.enable=0
	if afexists inet6; then
		${SYSCTL} net.inet6.ip6.fw.enable=0
	fi

	# Stop firewall coscripts
	#
	for _coscript in `reverse_list ${firewall_coscripts}` ; do
		if [ -f "${_coscript}" ]; then
			${_coscript} quietstop
		fi
	done
}

load_rc_config $name
firewall_coscripts="/etc/rc.d/natd ${firewall_coscripts}"

run_rc_command $*

**Comment by christianrj** [comment]
Hi! Just to provide feedback that this bug is still not fixed on webmin 1.791 for FreeBSD 10.3.

bsd-firewall module makes Webmin consumes all swap space on FreeBSD.

Hope for a fix soon. Thank you!

**Comment by emha-koeln** [comment]
Hi, 
still the same bug (swap space) on FreeBSD 12.1 and Webmin 1.941.
Regards
