### ISSUE TITLE
Phpmyadmin problems

### ISSUE THREAD

**Issue by manfer** [webmin/webmin#239]
I know probably this is not the best place as this is a virtualmin issue. But as far as I know there is no virtualmin public repo.

Phpmyadmin is not working correctly. Only the database that is created on domain creation is available in phpmyadmin (or the databases available in the domain when you install phpmyadmin script if you don't do it upon domain creation). But if you later create more databases they will not be available from phpmyadmin (unless they were create with phpmyadmin itself)

Why? Because in phpmyadmin configuration the following is being added:

```
/**
 * If set to a db-name, only this db is displayed in left frame
 * It may also be an array of db-names, where sorting order is relevant.
 *
 * @global string $cfg['Servers'][$i]['only_db']
 */
$cfg['Servers'][$i]['only_db'] = Array('domaindatabase');
```

That configuration is never updated when adding new databases from the virtualmin UI and it shouldn't. It will not be updated either if you decide to add databases with any other client, and it shouldn't. Nor with command-line nor with any other database manager, and it shouldn't. It would be imposible to handle all those situations.

So in my opinion it is an error to hardcode that option when phpmyadmin script is installed by virtualmin. That option value should be the default empty array and phpmyadmin will work as expected if that option value is an empty array by showing only the databases for the logged in user.

I have not looked for the file with the error but all indicates it is jut an issue in the phpmyadmin virtualmin install script.

**Comment by jcameron** [comment]
When installing phpMyAdmin from Virtualmin, you can select which databases it will have access to - or you can choose the "All databases" option, which will leave that `only_db` list empty as you suggested.

**Comment by manfer** [comment]
Thanks jcameron.

That's ok. But I don't install phpmyadmin from the installer. I implied the error was in there too sorry. I install phpmyadmin automatically from the plan configuration.

I see that in the plan configuration in the options for phpmyadmin script (as any other script) it has a "Database name" parameter which value by default is "Main Database" and that must be changed to "None" if we want all databases shown in phpmyadmin. I would never know that option was for that and it if were fot that I would expect that being "None" by default.

That "Database name" is the same parameter for every script, being it Roundcube, squirrelMail, Wordpress,... Obviously what I understand that parameter means is in which database you want to install the script and obviously it makes no sense for phpmyadmin.

Still don't know why for phpmyadmin that parameter takes a totally different meaning and it means exclude every database from phpmyadmin but this one. 

In the phpmyadmin script installer options it is easy to understand and it is not a problem. Sorry for the confusion.

**Comment by jcameron** [comment]
Ok, that explains it.
