### ISSUE TITLE
Cookie path

### ISSUE THREAD

**Issue by flechaig** [webmin/webmin#240]
Hi,
I have 5 instances of Webmin on my network. I wanted to reach have all of them via a unique Apache2 virtaul server (ProxyPass and ProxyReverse). URLs are like :
- https://www.mydomain.com/webmin1/
- https://www.mydomain.com/webmin2/  
...  
- https://www.mydomain.com/webmin5/

The issue is that when I switched between two instances in my Chrome browser, I loose my session because of the sid cookie path with is fixed to "/". Each time I login to an instance, I loose the previous session id that was set.

The sid cookie path should be set to webprefix parameter which is set in /etc/webmin/config file or default to "/".

Thank anyone who wants to solve this.

**Comment by jcameron** [comment]
Thanks for pointing this out - the next release of Webmin will allow you to add a line like cookiepath=/webmin1 to /etc/webmin/miniserv.conf to control this.

**Comment by flechaig** [comment]
Thank you very much.
