### ISSUE TITLE
&copy_source_dest and &rename_file copy move not the directory itself, but it's content.

### ISSUE THREAD

**Issue by Real-Gecko** [webmin/webmin#245]
I have 'openlayers' directory in '/root/.1' path.
If I call copy_source_dest like this
`&copy_source_dest('/root/.1/openlayers', '/root/.1/1')`
then not the 'openlayers' directory is copied to '/root/.1/1' but it's content.
Same happens with
`&rename_file('/root/.1/openlayers', '/root/.1/1')`

**Comment by jcameron** [comment]
Yeah, that API is a bit confusing - unfortunately a lot of other code depends on the current behavior, so it isn't easy to change. I'd recommend changing Filemin to first create the target directory in this case.

**Comment by Real-Gecko** [comment]
In earlier versions I used system calls to perform this operations. Later I switched to Webmin API function to get more verbose error reporting. I guess I have to switch back to system :D
