### ISSUE TITLE
package updater does not update already installed packages when using dnf

### ISSUE THREAD

**Issue by pcsrule** [webmin/webmin#254]
On both Fedora 22 workstation and server (and presumably anything else using dnf) the webmin package updater fails to update packages because it runs the command `dnf install -y XXX` which returns:
````
Package XXX is already installed, skipping.
...
Nothing to do.
Complete!
````
The command that should be run is `dnf update -y XXX` which updates the already installed package as expected.

**Comment by jcameron** [comment]
Should it instead be running `dnf upgrade webmin` ?

**Comment by pcsrule** [comment]
It appears both update and upgrade work and have the same effect. This is most likely to avoid confusion with aptitudes update/upgrade.

**Comment by sdellenb** [comment]
I can confirm the described behavior on Fedora 21 (where both yum and dnf are available) with Webmin 1.770.

**Comment by qooob** [comment]
Jamie, it run `Installing package(s) with command /bin/dnf -y install XXX ..` instead of `/bin/dnf -y upgrade XXX`

**Comment by jcameron** [comment]
So with `yum`, there is no difference between the `install` and `upgrade` commands. Has this changed with `dnf` ?

**Comment by pcsrule** [comment]
This has changed with dnf. `install` no longer updates existing packages. Both `upgrade` and `update` perform the same action and upgrade existing packages.

**Comment by qooob** [comment]
@pcsrule - true.

**Comment by jcameron** [comment]
That's annoying - can the `dnf upgrade` command also install packages?

**Comment by pcsrule** [comment]
It appears it can't. Just tried it out on Fedora 22 Workstation:
`sudo dnf update golang
Last metadata expiration check performed 0:00:23 ago on Thu Oct  8 22:18:31 2015.
Package golang not installed, cannot update it.
No match for argument: golang
Error: No packages marked for upgrade.`

**Comment by jcameron** [comment]
Ok, I've checked in a fix (linked from this issue) that will fix the problem - for inclusion in the next Webmin release.
