### ISSUE TITLE
create-domain.pl "No quota specified"

### ISSUE THREAD

**Issue by jruix** [webmin/webmin#257]
Hi, 
not sure if I'm reporting this bug in the correct so apologies if it is the case.

When executing the command line script  create-domain.pl with --uquotas 0 and --quotas 0 or --uquotas UNLIMITED and --quotas UNLIMITED, the script ends up failing because quotas weren't specified.

I think the script is misunderstanding 0 value at some point as false

Please let me know were could I do the pull request to fix this issue if possible.

**Comment by jcameron** [comment]
What's the exact error message that you are getting?

**Comment by swelljoe** [comment]
Closed due to inactivity.
