### ISSUE TITLE
webmin / rhel7 / dhcpd / systemd

### ISSUE THREAD

**Issue by meoso** [webmin/webmin#258]
`ISC DHCPd version 4.2.5`
`Webmin version 1.760`
```
cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.1 (Maipo)
```
In DHCP Server, the `Start Server` button will start the service, but the button doesn not toggle to say `Stop Server`; therefore, one may believe the service is failing to start.

I also do not see `Apply Changes` probably for the same reason.

**Comment by meoso** [comment]
Had to manually edit Module Config with the following (which i resumed would have been automatic):
`Command to start DHCP server` : `systemctl restart dhcpd`
`Command to apply configuration `: `systemctl restart dhcpd`
`Command to stop DHCP server` : `systemctl stop dhcpd`
`Path to DHCP server PID file` : `None`

**Comment by jcameron** [comment]
Do the commands "service dhcpd stop" and "service dhcpd start" work on  your system to restart the server? Because that's what Webmin uses by default.

**Comment by meoso** [comment]
hmmm. yes they do:
```
[root@dhcp ~]# service dhcpd stop
Redirecting to /bin/systemctl stop  dhcpd.service
[root@dhcp ~]# service dhcpd start
Redirecting to /bin/systemctl start  dhcpd.service
[root@dhcp ~]# service dhcpd status
Redirecting to /bin/systemctl status  dhcpd.service
dhcpd.service - DHCPv4 Server Daemon
   Loaded: loaded (/usr/lib/systemd/system/dhcpd.service; disabled)
   Active: active (running) since Tue 2015-09-29 15:07:10 CDT; 4s ago
     Docs: man:dhcpd(8)
           man:dhcpd.conf(5)
 Main PID: 1949 (dhcpd)
   Status: "Dispatching packets..."
   CGroup: /system.slice/dhcpd.service
           └─1949 /usr/sbin/dhcpd -f -cf /etc/dhcp/dhcpd.conf -user dhcpd -group dhcpd --no-pid
[...]
```

With that said, maybe it is simply the fact that there is no pid file by default, thus changing `Path to DHCP server PID file` to `None` is the real solution.

**Comment by jcameron** [comment]
Thanks - I will make that PID file change in the next release.
