### ISSUE TITLE
Add To Group button leads to delete_user.cgi

### ISSUE THREAD

**Issue by Real-Gecko** [webmin/webmin#261]
Based on post from Filemin discussion thread:
http://virtualmin.com/node/36839?page=4#comment-154743
Trying to add user or users to group leads to delete_user.cgi.
Webmin 1.770, tried under Authentic and various other themes.

Steps to reproduce:
Go to Webmin - Webmin Users (/acl/ module), select users and hit "Add To Group" button.

**Comment by jcameron** [comment]
That's expected - the `delete_user.cgi` script is also used for adding users to groups.

Or are you finding that it is actually deleting users?

**Comment by Real-Gecko** [comment]
When I select all users including myself (or just select myself) and click "Add to group" it says "You cannot delete yourself".
 And also a quote from forum thread `When i click [Add to Group:] , page change to " Failed to delete users : One of the selected users is marked as non-editable " .. like if i want delete the users ...`
That's frustrating :)

**Comment by jcameron** [comment]
There's a couple of bugs here, which will be fixed in the next (1.771 or higher) release.

**Comment by Real-Gecko** [comment]
Nice :)
