### ISSUE TITLE
Webmin 1.770 upgrade returns Firefox error in all themes - unknown directive 'child-src'

### ISSUE THREAD

**Issue by qooob** [webmin/webmin#262]
Console error message using all themes:
`Content Security Policy: Couldn't process unknown directive 'child-src'`

![screenshot from 2015-10-07 14-13-56](https://cloud.githubusercontent.com/assets/4426533/10335969/be3a63e8-6cfd-11e5-9b89-b7c6b96efb8d.png)

**Comment by jcameron** [comment]
That's odd, it is documented at http://www.html5rocks.com/en/tutorials/security/content-security-policy/

**Comment by johnp** [comment]
CSP child-src [isn't supported](http://caniuse.com/#feat=contentsecuritypolicy2) in Firefox-Release, but it got committed to [mozilla-central](https://bugzilla.mozilla.org/show_bug.cgi?id=1045891) a month ago, so it'll be in Firefox 45.

Maybe [adding](https://www.fxsitecompat.com/en-US/docs/2015/csp-directive-frame-src-has-been-deprecated-in-favor-of-child-src/) an equivalent ´´frame-src´´ will [do](https://stackoverflow.com/questions/30023608/how-to-use-frame-src-and-child-src-in-firefox-and-other-browsers) in the meantime?

**Comment by jcameron** [comment]
Webmin already also adds `frame-src: self`

**Comment by qooob** [comment]
Jamie, I just wouldn't bother! Firefox release 45 should remove this warning.
