### ISSUE TITLE
Porting System Information->Status to Webmin

### ISSUE THREAD

**Issue by qooob** [webmin/webmin#263]
Jamie, I think it will take no effort to port Status about running services to system information page, like Virtualmin does. It think it makes more sense to have it as Webmin package, not Virtualmin.

https://github.com/qooob/authentic-theme/issues/266

**Comment by jcameron** [comment]
Do you mean which servers are up, like Apache, Postfix, etc?

**Comment by qooob** [comment]
Yes, like in a screenshot on the link.

**Comment by jcameron** [comment]
That's a good idea .. I will look into adding this.
