### ISSUE TITLE
ADO.NET Problem

### ISSUE THREAD

**Issue by patrik5** [webmin/webmin#265]
I Can't mapping mysql table with ADO.NET. 

![config1](https://cloud.githubusercontent.com/assets/7016455/10561294/159ecb0c-752c-11e5-905c-d3a55da8c938.png)
![step1](https://cloud.githubusercontent.com/assets/7016455/10561304/390e6246-752c-11e5-9f4d-cdb76d711e4b.png)
![step2](https://cloud.githubusercontent.com/assets/7016455/10561308/42bd2714-752c-11e5-84ad-ec46f652fd60.png)

Press forward and the window closes. I do not see the tables. No error. Just disappears!

**Comment by swelljoe** [comment]
I don't believe your question or your problem have anything to do with Webmin.

**Comment by jcameron** [comment]
Yeah, this ticket doesn't seem Webmin-related at all.
