### ISSUE TITLE
webprefixnoredir does not work? 

### ISSUE THREAD

**Issue by muhahacz** [webmin/webmin#267]
I have proxied webmin (finally) at https://10.0.0.47:55555/webmin/ (SSL on apache), but when i login in webmin, i get redirect to nonSSL  http://10.0.0.47:55555/ which cause a bad request.
I have ssl=0 and ssl_redirect=1 in miniserv.conf

Found a similar bug here:
http://sourceforge.net/p/webadmin/bugs/4659/?limit=25

Also when i access Running Proccess, chrome say warning about mixed content. Other links work fine i guess..
Mixed Content: The page at 'https://10.0.0.47:55555/webmin/' was loaded over HTTPS, but requested an insecure resource 'http://10.0.0.47:55555/proc/index_tree.cgi'. This request has been blocked; the content must be served over HTTPS.

```
/etc/webmin/config
webprefix=/webmin
webprefixnoredir=1

/etc/webmin/miniserv.conf
ssl_redirect=1
cookiepath=/webmin
ssl=0
```

@jcameron

**Comment by jcameron** [comment]
Have you tried just removing `webprefixnoredir=1` ?

**Comment by muhahacz** [comment]
yes, same behavior.

**Comment by jcameron** [comment]
Which theme are you using in Webmin? It may be worth trying to switch to the "Gray Framed Theme", rather than the default "Authentic Theme"

**Comment by qooob** [comment]
Jamie, you didn't set _Authentic Theme_ as default yet, right?

**Comment by muhahacz** [comment]
Default theme

**Comment by jcameron** [comment]
To clarify which theme you are using, can you attach a screenshot?

**Comment by muhahacz** [comment]
http://doxfer.webmin.com/mediawiki/images/e/eb/System_Information.png

**Comment by qooob** [comment]
@muhahacz Why don't you upgrade Webmin to version 1.770?

Have you tried latest [Authentic Theme](https://github.com/qooob/authentic-theme)?

**Comment by jcameron** [comment]
Agreed, I'd recommend upgrading Webmin first of all.

**Comment by muhahacz** [comment]
its just prtscn from internet (to show theme), its not mine ,  im usign latest version of webmin..

**Comment by muhahacz** [comment]
@jcameron 
There is also problem with strings that are not showing in webmin category:
http://s13.postimg.org/5ilwb4fgn/image.jpg

cat /var/webmin/miniserv.error
http://pastebin.com/HSfByHCA

**Comment by jcameron** [comment]
That screenshot is really low res - do you have a larger one?

**Comment by muhahacz** [comment]
http://oi65.tinypic.com/23w8nsz.jpg

**Comment by jcameron** [comment]
That is very strange - I can't even think of a way that text labels could go missing in Webmin!

Does it happen in any other module?

**Comment by qooob** [comment]
Did you try disabling all browser's add-ons? Or trying other browser?

**Comment by muhahacz** [comment]
Other modules are working fine. Only Webmin category doesnt work. I will post more screenshoots afternoon...

..except Running Processes link . Chrome say warning about mixed content.  
I guess relative path doesnt work correctly:

```
Mixed Content: The page at 'https://10.0.0.47:55555/webmin/' was loaded over HTTPS, but requested an insecure resource 'http://10.0.0.47:55555/proc/index_tree.cgi'. This request has been blocked; the content must be served over HTTPS.
```

**Comment by jcameron** [comment]
One more question  -which language do you have selected in Webmin?

**Comment by muhahacz** [comment]
(ENG) 
Its all default configuration, except one option in webmin configuration.
I turned on "Redirect all requests to https" option.

I will check servers locale settings..

**Comment by muhahacz** [comment]
So only "Webmin Actions Log" and  "Webmin Configuration" have problems with disappearing strings.
But i noticed, when i click on "Module Config" in these two subcategories, error message shows up: "You are not allowed to access this module"

So i guess, there will be a problem with permissions also.

Img n.3 shows error when accessing "Running processes".

http://imgur.com/a/WGHue

**Comment by muhahacz** [comment]
Accessing miniserv directly, without proxy:
http://i.imgur.com/gS3rr85.jpg

Same problem..

**Comment by jcameron** [comment]
What if you access Webmin directly, but without webprefix=/webmin in /etc/webmin/config ?

**Comment by muhahacz** [comment]
Without  webprefix=/webmin in /etc/webmin/config
http://i.imgur.com/LSIaRwI.jpg

**Comment by muhahacz** [comment]
@jcameron ?

**Comment by jcameron** [comment]
So, to get basic proxying working you need to remove `webprefixnoredir=1` from `/etc/webmin/config` .

To be honest, it is much much simpler to have a separate Apache virtualhost that proxies to webmin without using a sub-directory at all. That way you don't need any of these `webprefix` settings.

**Comment by marktamis** [comment]
I fixed the mixed content error by making the code redirect to a relative url rather than the full path after executing the action.
````
webprefix=/webmin
webprefixnoredir=0
relative_redir=1`

```
sub redirect in web-lib-funcs.pl looks whether the HTTPS SERVER_PORT and environment variables are set and contructs the url based on these. the reverse proxy doesn't pass these, so we get http and the webmin port.

relative_redir makes it relative, but loses the webprefix. setting the webprefixnoredir to 0 adds this again.

so far so good. will test other modules now
