### ISSUE TITLE
MySQL Navigation: Database and table name

### ISSUE THREAD

**Issue by qooob** [webmin/webmin#268]
https://github.com/qooob/authentic-theme/issues/280
> Fw: While navigation databases and tables for a MySQL Database Server, there doesn't seem to be any indication as to what database and table I'm looking at. I should know since I just navigated there, but I have to leave the page in order to confirm the exact naming of the table. Also, if I left a tab open on that table and come back to it later, I won't know for sure if it's the table I need or not.

**Comment by jcameron** [comment]
The DB and table should appear in the subheading - at least, they do using the old theme :

![image](https://cloud.githubusercontent.com/assets/102706/11201996/61e8fb3a-8c98-11e5-9719-bcac7b39bec2.png)

**Comment by qooob** [comment]
Oh, man, true!! Alright! I will take a look! Thanks and sorry Jamie! ;)
