### ISSUE TITLE
RAID module bugs

### ISSUE THREAD

**Issue by fortran77** [webmin/webmin#269]
I have encountered a couple of RAID module bugs in 1.770 on CentOS Linux 5.11. I hope this is the right place for reporting them.

First, if a newly-created RAID 1 array has not yet been sync'd, but is waiting for some other RAID array to get sync'd first, Webmin reports the newly-created RAID 1 array as clean, even though it's not really clean.

Second, if two entire disks (e.g., all of /dev/sdb and /sdc) have been configured into a RAID volume, without any partitions having been created (i.e., no /dev/sdb1 or /dev/sdc1 exists), Webmin offers to let you create yet another RAID array using "SCSI device B partition 1" and "SCSI device C partition 1". This would presumably cause data to be overwritten (but I didn't try to actually create this new RAID array as I had live data on those disks).

If more details are needed, please let me know.

**Comment by jcameron** [comment]
For your first issue, can you post the contents of the /proc/mdstat file on your system when the RAID array is in that state?

For your second issue, I'll fix this bug in the next Webmin release.

**Comment by fortran77** [comment]
For the first issue, I tried to attach a screenshot excerpt of what Webmin shows on the screen, and github gave me a "Something went really wrong" error. I have made that screenshot available at the link below. It will show that /dev/md4 is being reported as clean, even though it's waiting for a delayed resync.

https://drive.google.com/file/d/0B9Aje_xcyQxxMXJKX1N1eHo4dVk/view?usp=sharing

Below are the contents of /proc/mdstat, with original formatting preserved, i.e., no newlines have been added or removed.

    Personalities : [raid1] [raid10] 
    md4 : active raid1 sde4[1] sdb4[0]
          163742400 blocks [2/2] [UU]
            resync=DELAYED
      
    md3 : active raid1 sdc[0] sdd[1]
          292968640 blocks [2/2] [UU]
      
    md0 : active raid1 sde1[0] sdb1[1]
          200704 blocks [2/2] [UU]
      
    md2 : active raid1 sde2[1] sdb2[0]
          98301632 blocks [2/2] [UU]
          [========>............]  resync = 43.6% (42875712/98301632) finish=6.1min speed=150647K/sec
      
    md1 : active raid1 sde3[0] sdb3[1]
          30716160 blocks [2/2] [UU]
      
    unused devices: <none>

**Comment by jcameron** [comment]
Thanks! Can you also post the output of `mdadm --detail md4` in this state?

**Comment by fortran77** [comment]
I recreated the scenario, and below is the output from both `cat /proc/mdstat` and `mdadm --detail`.

    # cat /proc/mdstat 
    Personalities : [raid1] [raid10] 
    md4 : active raid1 sde4[1] sdb4[0]
          163742400 blocks [2/2] [UU]
            resync=DELAYED
          
    md3 : active raid1 sdc[0] sdd[1]
          292968640 blocks [2/2] [UU]
          
    md0 : active raid1 sde1[0] sdb1[1]
          200704 blocks [2/2] [UU]
          
    md2 : active raid1 sde2[1] sdb2[0]
          98301632 blocks [2/2] [UU]
          [===>.................]  resync = 19.0% (18756544/98301632) finish=9.2min speed=143584K/sec
          
    md1 : active raid1 sde3[0] sdb3[1]
          30716160 blocks [2/2] [UU]
          
    unused devices: <none>
    
    
    # mdadm --detail /dev/md4
    /dev/md4:
            Version : 0.90
      Creation Time : Sat Nov 28 22:44:05 2015
         Raid Level : raid1
         Array Size : 163742400 (156.16 GiB 167.67 GB)
      Used Dev Size : 163742400 (156.16 GiB 167.67 GB)
       Raid Devices : 2
      Total Devices : 2
    Preferred Minor : 4
        Persistence : Superblock is persistent
    
        Update Time : Sat Nov 28 22:44:05 2015
              State : clean
     Active Devices : 2
    Working Devices : 2
     Failed Devices : 0
      Spare Devices : 0
    
               UUID : db4d173f:6070c8ef:2ddc5e09:c71493c0
             Events : 0.1
    
        Number   Major   Minor   RaidDevice State
           0       8       20        0      active sync   /dev/sdb4
           1       8       68        1      active sync   /dev/sde4

**Comment by jcameron** [comment]
Thanks - the next release of Webmin should display this properly.

**Comment by fortran77** [comment]
Thank-you, you're very prompt and responsive.

Regarding the image I tried to attach: if anybody reading this is able to download it from the link and attach it here directly, that would be great for historical completeness—just in case my link ever becomes invalid.
