### ISSUE TITLE
MDADM Systemd service mdmonitor cannot be created unless a command is given

### ISSUE THREAD

**Issue by kintoxo** [webmin/webmin#270]
I have installed:
*Debian Linux 8.2*
*Webmin 1.770*
*MDADM 3.3.2*

Using webmin module *Linux RAID* I configured *RAID1 (Mirrored)* and wanted to further customize the *RAID problem notification options*, but when I install *Monitoring enabled?* = YES and press the *Save* button, it displays the following error:
```
Failed to save RAID problem notification options: Systemd service mdmonitor can not be created unless a command is given.
```

Command `systemctl status mdmonitor.service` displays the following message:
```
mdmonitor.service - MD array monitor
    Loaded: loaded (/lib/systemd/system/mdmonitor.service; static)
    Active: active (running) since Sun 2015-11-29 12:45:44 OMST; 52min ago
  Main PID: 8771 (mdadm)
    CGroup: /system.slice/mdmonitor.service
            └─8771 / sbin / mdadm --monitor --scan
```

**Comment by jcameron** [comment]
If you go to System -> Bootup and Shutdown in Webmin, do you see `mdmonitor` or `mdmonitor.service` in the list?

**Comment by kintoxo** [comment]
If I go to System -> Bootup and Shutdown in Webmin, I see `mdmonitor.service` in the list, with parameters:
- *Start at boot?* = *Always*
- *Running now?* = *Yes*

![1](https://cloud.githubusercontent.com/assets/10782838/11463297/958bf3da-9741-11e5-8628-c8878c718964.jpg)

**Comment by jcameron** [comment]
Does the file `mdmonitor.service` exist in any of `/etc/systemd/system` , `/usr/lib/systemd/system` or `/lib/systemd/system` on your system?

**Comment by kintoxo** [comment]
On my system `mdmonitor.service` exist only in `/lib/systemd/system`

**Comment by jcameron** [comment]
Ok, I see the bug that causes this - it will be fixed in the next Webmin release.
