### ISSUE TITLE
[bind8] DSSet retrival

### ISSUE THREAD

**Issue by gmt2001** [webmin/webmin#272]
This may be specific to some versions of dnssec-dsfromkey, but when I run Webmin on the latest CentOS 6.5 version, the bind8 module is not able to retrieve the DS record set and display it in my DNSSEC settings page. Reasearch and testing has shown the cause to be that on bind8-lib.pl#4003 the following code is used
```perl
if (&has_command("dnssec-dsfromkey")) {
	# Generate with a command
	my $out = &backquote_command("dnssec-dsfromkey -f ".quotemeta(&make_chroot(&absolute_path($zonefile)))." ZONE 2>/dev/null");
	return undef if ($?);
	$out =~ s/\r|\n//g;
	return $out;
	}
```

However, using **ZONE** as the *zonename* parameter causes the following error
```
dnssec-dsfromkey: error: dns_master_load: /var/named/example.com.db:13: example.com: not at top of zone
dnssec-dsfromkey: fatal: can't load /var/named/example.com.db: not at top of zone
```

This can be corrected by changing line 4005 to 
```perl
my $out = &backquote_command("dnssec-dsfromkey -f ".quotemeta(&make_chroot(&absolute_path($zonefile)))." ".$dom." 2>/dev/null");
```

Additionally, after applying this fix, the newline is removed from the output which causes a formatting issue when the DS record set is displayed to the user. This can be fixed by only removing **\r** from the output and not **\n**

I therefore submit that the code block beginning on line 4003 and ending on line 4009 of webmin/bind8/bind8-lib.pl be changed to

```perl
if (&has_command("dnssec-dsfromkey")) {
	# Generate with a command
	my $out = &backquote_command("dnssec-dsfromkey -f ".quotemeta(&make_chroot(&absolute_path($zonefile)))." ".$dom." 2>/dev/null");
	return undef if ($?);
	$out =~ s/\r//g;
	return $out;
	}
```

This has been tested on CentOS 6.5 with live data.

**Comment by jcameron** [comment]
Thanks - I will include your fix (with some slight changes) in the next Webmin release.
