### ISSUE TITLE
[Q] How do I use a unix socket instead of port 10000?

### ISSUE THREAD

**Issue by txtsd** [webmin/webmin#274]

**Comment by jcameron** [comment]
Sorry, but this isn't supported ... and in fact, even if Webmin could use a Unix domain socket, I don't think browsers could connect to it.

**Comment by txtsd** [comment]
Not for browsers, but for reverse proxies. I'd like my nginx to connect to webmin via a unix socket instead of a port.
It isn't necessary, but it would be a good feature.

**Comment by jcameron** [comment]
Are you interested in using a unix domain socket for performance reasons, or something else?

**Comment by txtsd** [comment]
Yep. Webmin is pretty slow at times anyway, but I guess that's a separate issue.

**Comment by jcameron** [comment]
I suspect that you wouldn't gain much speedup vs. using a localhost connection, compared to the total execution time of a Webmin operation.

**Comment by txtsd** [comment]
Alright.
