### ISSUE TITLE
Webmin authentic theme the icons are not visible

### ISSUE THREAD

**Issue by hasseA** [webmin/webmin#276]
When choosing for example postfix Mail server under servers-> the page is empty and no icons are visable
![icons are not visable](https://cloud.githubusercontent.com/assets/14984262/12217715/295f4f62-b709-11e5-8a3b-a3e655b33be4.JPG)

**Comment by qooob** [comment]
Did you try to reload the page? Does this only happen in Postfix module?

**Comment by hasseA** [comment]
I tried reloading the page, I tried changing theme and changing it back again, I tried log out and log in again but the issue still remains. when I point the cursor in empty space the icon appears but as soon as I remove the cursor, it disappear again..

**Comment by hasseA** [comment]
By the way the theme is the MOST impressive one I have ever seen. Kudos and great job :+1:

**Comment by qooob** [comment]
What browser are you using and what is the theme version that you have installed?

Try going to theme settings and change Table options->Animate table icons on focus. Does it work if you set it to no? Tried small buttons instead?

**Comment by qooob** [comment]
Thank you for the kind words.

**Comment by hasseA** [comment]
yes, If I choose Table options->Animate table icons on focus== no then it work. Thank you

**Comment by qooob** [comment]
Please tell me which browser do you use?

**Comment by hasseA** [comment]
The problem could be seen both in Google chrome and firefox

**Comment by swelljoe** [comment]
Pretty sure this has been fixed.

**Comment by mrluisiko99** [comment]
I'm having the same problem as @hasseA . Also if I disable the Animate table icons on focus it works.
I'm using the last version of Virtualmin/Webmin.

**Comment by qooob** [comment]
What is the browser that you're using.

What are the exact versions of Webmin/Virtualmin and Authentic Theme you have installed?

**Comment by mrluisiko99** [comment]
I'm using Firefox 59.0.2, Authentic Theme 19.12 stable, Webmin 1.881 and Virtualmin 6.02-3 .

Specs of the VM:
Intel Xeon Processor (Skylake, IBRS), 1 core
2GB RAM
OS: Ubuntu Linux 16.04.3 / Linux 4.4.0-116-generic de x86_64

**Comment by qooob** [comment]
This is interesting. I can't reproduce it. 

It's possible due to glitch GPU driver. It happened before, I remember.

It would be interesting to see the video-screencast for the future reference.

What is your GPU? Did you try proprietary drivers to out-out the source of the problem?

**Comment by mrluisiko99** [comment]
If you mean the GPU of the VM, it is Ubuntu Server, so it doesn't have graphic mode. It's the cheaper VM of Hetzner. That option requires a GPU to be enabled?
If you mean the GPU of my PC, i don't think that it has something to do with this.

**Comment by qooob** [comment]
GPU of your PC. What is it? Do you use Nouveau driver?

**Comment by mrluisiko99** [comment]
I'm using Windows 10, not Linux. I have a AMD Radeon RX 470.

**Comment by qooob** [comment]
> I'm using Windows 10, not Linux. I have an AMD Radeon RX 470.

I have setup real Windows 10 machine (not virtual machine) and I can't reproduce it. It just works fine in Firefox, Chrome and Edge.

Doesn't work for you only in Firefox?

> These icons are not showing neither.

These icons must be shown and colored when you hover on the row.

Try purging your Firefox cache and all its data folder. Before doing that you can create new account in Windows and see if it helps. I think this could a reason, other than that, you would have to try to think it out yourself, what and why it is broken and share debug info. In case it's possible to fix, I would love to do it.
