### ISSUE TITLE
ui_* functions vs Webmin/*.pm classes

### ISSUE THREAD

**Issue by pcfreak30** [webmin/webmin#279]
Can you please explain what the difference between the two are and how the ui classes work with the theme? Are there plans to move to the Webmin::* from ui_?

**Comment by jcameron** [comment]
The Webmin::* classes were part of an experimental API that is not recommended for future development. You should use the ui_* functions instead.

**Comment by pcfreak30** [comment]
Is there a reason they still exist if they wont be used?

**Comment by jcameron** [comment]
They are used, by only by the Solaris Zones module.

**Comment by pcfreak30** [comment]
Why not port it back and reduce the code base?

**Comment by jcameron** [comment]
We just haven't had the time, and it's low priority since the current code still works.
