### ISSUE TITLE
System Logs: View Log add select for other logs

### ISSUE THREAD

**Issue by qooob** [webmin/webmin#283]
Jamie, today I found very inconvenient to go back and forth to look at `prosody.err` and then to `prosody.log` and then back again.

I would like to propose for Log View Mode (`/syslog/save_log.cgi?idx=XX&view=1`) to have floating select on the top right (right next to refresh button but floating ~~left~~ **right**), that would have all logs that are on System Logs main page, so you could click on it and switch between logs quickly. I will add search to that select and it will be great.

**Comment by qooob** [comment]
Here is the example, but instead of that EXT2, EXT3 and etc. It should be the logs paths
![screenshot from 2016-02-24 20-20-18](https://cloud.githubusercontent.com/assets/4426533/13294262/36b115ca-db34-11e5-813d-3809e3a5ddb8.png)

**Comment by qooob** [comment]
It makes it easy if just inserted to the `form` where that refresh button is, at the very end and make it `style="float: right"`.

**Comment by jcameron** [comment]
Nice idea .. I'll add that.

**Comment by qooob** [comment]
Look good. There is an error for non-custom logs, for example, if you view the following form the main page select is not displayed:

`File /var/log/httpd/error.log	Yes	Apache error log`

**Comment by jcameron** [comment]
Do you mean a log that's not in syslog.conf ?

**Comment by qooob** [comment]
Yes, when you view it, for example `/var/webmin/miniserv.error` you can see what I'm talking about.
