### ISSUE TITLE
Disk quota not working when creating new system user

### ISSUE THREAD

**Issue by taoteh1221** [webmin/webmin#285]
Creating a new user in "Webmin -> System -> Users and Groups" seems to set a disk usage quota somewhere, even though under "Webmin -> System -> Disk Quotas" it says unlimited. I was syncing a geth (Ethereum) blockchain node and it stalled saying "disk quota exceeded". This was in a fresh install of Virtualmin GPL, on a fresh install of Ubuntu 14.04 LTS. When I ran geth as a Virtaulmin virtual server user instead, everything worked fine.

**Comment by taoteh1221** [comment]
Disk usage is as follows:

> du -h /home/ethereum
4.0K	/home/ethereum/.ethereum/keystore
20K	/home/ethereum/.ethereum/dapp
1.0G	/home/ethereum/.ethereum/chaindata
572K	/home/ethereum/.ethereum/nodes
1.0G	/home/ethereum/.ethereum
1.0G	/home/ethereum

**Comment by jcameron** [comment]
Check if you have default disk quotas set for new users, at System -> Disk Quota -> /home -> Default quotas.

**Comment by taoteh1221** [comment]
I'm not seeing a "/home -> Default Quotas" option in my Webmin Disk Quotas page: [http://www.dragonfrugal.com/transfer/DiskQuotasWebmin1.782UbuntuLinux14.04.4.png](url)

Here is the user setup: [http://www.dragonfrugal.com/transfer/DiskQuotasforEthereumuser.png](url)

This not not critical, as I merely moved running the Ethereum node over to a Virtualmin website account user instead and all is good now...just figured I'd report this as a potential Webmin bug. I even set it from unlimited to 200GB just to try and kick it into gear, but the user account still said 'disk quota exceeded' in the geth command line console when trying to sync the blockchain. Looks like the quota is set somewhere to 1GB judging by the home directory contents, just can't find where it shows that. Says unlimited in the Quotas setting.

**Comment by jcameron** [comment]
Sorry, you need to click on / instead of /home

**Comment by taoteh1221** [comment]
Looks ok from what the GUI reports: [http://www.dragonfrugal.com/transfer/Defaultquotas.png](http://www.dragonfrugal.com/transfer/Defaultquotas.png)  Groups quotas looks exactly the same as this too.

**Comment by taoteh1221** [comment]
Here is what geth via command line reports:

> I0227 18:15:19.772751 eth/downloader/downloader.go:295] Block synchronisation started
I0227 18:15:25.754812 core/blockchain.go:1259] imported 3 block(s) (0 queued 0 ignored) including 0 txs in 3.009978929s. #230960 [1f92ed9c / 91cdb17e]
I0227 18:15:25.890237 core/blockchain.go:1259] imported 3 block(s) (0 queued 0 ignored) including 4 txs in 135.139074ms. #230963 [53872ac9 / e6f0bb21]
I0227 18:15:36.589916 eth/downloader/downloader.go:274] Synchronisation failed: write /home/ethereum/.ethereum/chaindata/009314.log: disk quota exceeded
I0227 18:15:53.546893 eth/downloader/downloader.go:274] Synchronisation failed: write /home/ethereum/.ethereum/chaindata/009314.log: disk quota exceeded

**Comment by jcameron** [comment]
For this user, you should also check if any group quotas have been setup for his primary group.

**Comment by taoteh1221** [comment]
Bingo, that was it. So apparently creating a new user in Webmin at "Webmin -> System -> Users and Groups -> Create a New User" for some reason set it's group quota to 1024MB (soft and hard limit). I'm guessing this is a bug, as I am running the stock setup from a fresh OS / Virtualmin GPL install? Thanks for your time, I appreciate it.

**Comment by taoteh1221** [comment]
One important note I forgot to mention: When I created this user at "Webmin -> System -> Users and Groups -> Create a New User", I chose  "New group with same name as user".

**Comment by taoteh1221** [comment]
Weird, I just tried to replicate this creating a new user the same way, and it looks fine on group quotas. Maybe this was just some really rare system glitch.
