### ISSUE TITLE
Software Package Updates to run update for all

### ISSUE THREAD

**Issue by qooob** [webmin/webmin#286]
Jamie, hi!

It would make sense, if on the input you would check, if a number of initially available packages equals to the number of passed (selected) packages. In case numbers are equal, you would want to run instead of individual package updates (`dnf -y update package-name`) updates **for all**, e.g.: `dnf -y update`.

It would make things run _much_ faster, as in most case, I bet, people run updates for all packages, not individual, right?

**Comment by jcameron** [comment]
Personally, I do targetted updates rather than all at once.

Is running `dnf -y update` actually faster than `dnf -y update <all packages>` though?

**Comment by qooob** [comment]
Yes, I think it runs faster. Besides, it makes a lot of sense to run it for all in case all is selected by the user.

It will produce less output as well.

**Comment by qooob** [comment]
Besides running it individually floods the `yum/dnf` history log and makes impossible to revert to undo update in a bulk way.

**Comment by jcameron** [comment]
OK, I will move to updating all packages at once in a single command

**Comment by jcameron** [comment]
The next Webmin release will update multiple packages at once.

**Comment by qooob** [comment]
Added commit and will test it before release couple of times. In case something goes wrong will let you know. Thank you, Jamie!! ;)
