### ISSUE TITLE
letsencrypt email for domain defaults to non-existant alias/email.

### ISSUE THREAD

**Issue by xinomilo** [webmin/webmin#287]
using virtualmin gpl and tried letsencrypt feature for the first time. noticed that email is root@$DOM 
(https://github.com/webmin/webmin/blob/e780c2fa1c10f496ca709b8ce142f9a1f0f73272/webmin/letsencrypt-lib.pl#L29)
but this alias/email isn't created by default in virtual servers. 
so in cases of no system customization, these email notifications from letsencrypt will be missed/discarded.
maybe $email should be defaulted to some email that already exists (domain owner or root@$hostname), so user(s) will be alerted every 3 months.

thanks,
d.

**Comment by jcameron** [comment]
The next release of Virtualmin will fix this, by using the domain owner email as the contact.
