### ISSUE TITLE
webmin fail after upgrade

### ISSUE THREAD

**Issue by TheBudda** [webmin/webmin#288]
I have just upgraded and now I am getting connection refused, please see screenshot

[webmin](https://cloud.githubusercontent.com/assets/16983376/13569915/e914ee94-e462-11e5-852f-d06086cb910b.png)

**Comment by qooob** [comment]
I had this on my debug machine as well. The only thing that worked for me was moving away from previously used port. It can be tweaked in minserve.cfg file.  I think this issue is related to:

https://github.com/qooob/authentic-theme/issues/418#issuecomment-193221843

**Comment by TheBudda** [comment]
thanks for your comment. I just tried to downgrade but with no luck I am still getting 
This site can’t be reached

************ refused to connect.

I will wait for a fix or upgrade

**Comment by jcameron** [comment]
Try SSHing in as root and running `/etc/webmin/start`

**Comment by qooob** [comment]
I remember doing it when had this issue and it didn't work. I thought it was a bug of my installation.

**Comment by TheBudda** [comment]
yep that worked on both machines! Nice 1 thank you :+1:

**Comment by qooob** [comment]
@TheBudda - what OS you have installed on your servers?

**Comment by qooob** [comment]
@Jamie, isn't `service webmin restart` the same as `/etc/webmin/start`? I surely tried it on debug server (Debian 8) and it didn't work for me.

**Comment by TheBudda** [comment]
Debian Linux 8.3 it work like a charm for me

**Comment by jcameron** [comment]
`service webmin start` is the same as `/etc/webmin/start`

**Comment by TheBudda** [comment]
I just used it again after the upgrade tonight. I have only been working with Debian for a year. I am loving the OS
