### ISSUE TITLE
Cron jobs: Configuration->Maximum Cron jobs to show

### ISSUE THREAD

**Issue by qooob** [webmin/webmin#291]
Jamie,

Imagine you have 10 Cron Jobs. If you set the option `Maximum Cron jobs to show` to the value lower than 10 (the number of available cron jobs) - nothing is displayed? Is this intended?

OS: Fedora 23

It happens in all themes.

**Comment by jcameron** [comment]
If you have more than 10 cron jobs, you should instead see a search form to find jobs by user or command line. This is pretty standard across Webmin (rather than limiting the list to 10).

**Comment by qooob** [comment]
Thank you for clarifying this up.
