### ISSUE TITLE
Unable to get Users to log into Webmin

### ISSUE THREAD

**Issue by KeiroD** [webmin/webmin#293]
Hi,

So, I've been struggling with trying to get user logins to Webmin to WORK.

Root and sudo users are able to log in just fine to Webmin. Not so for user logins that do not have sudo access.

I've tried several different ways of adding a user to the server in question, via SSH, via Webmin Users and Groups UI... nothing's working.

Also, I find this in my logs:

`boxen sudo: exampleuser : command not allowed ; TTY=pts/2 ; PWD=/usr/share/webmin ; USER=root ; COMMAND=list`

What gives?

**Comment by jcameron** [comment]
Are these users who would normally be able to sudo to root?

Also, have they been added at Webmin -> Webmin Users, and if so using which authentication method?

**Comment by KeiroD** [comment]
I did have plans for giving them the ability to sudo to root.

I did not, no. Is that a step that's supposed to take place?

I added them via the System > Users and Group > Create new user method, which implies the ability to SSH into the server.

Speaking of that, SSH for the user works just fine. Just not logging into Webmin for whatever reason.

**Comment by jcameron** [comment]
So, there are two kinds of users who can login to  Webmin :

1 - Users created explicitly in the Webmin Users module
2 - Unix (SSH) users who have the ability to run ALL commands via sudo

**Comment by swelljoe** [comment]
There's been no follow-up in over a year, so I'll assume this is resolved.
