### ISSUE TITLE
Webmin Servers: Select All/Invert Selection

### ISSUE THREAD

**Issue by qooob** [webmin/webmin#294]
Jamie, hi! It appears that those buttons don't work in all themes (Authentic and VM Framed Theme), returning error on `Show servers as Table` mode. In `Icons` mode it work in Authentic but some wrapped module's scrips still throws an error.

**Comment by jcameron** [comment]
I just tested this, and it works fine for me. What's the error exactly?

**Comment by qooob** [comment]
Here, Jamie:

https://rostovtsev.ru/pub/src/authentic/17.80b/webmin294-authentic.webm

https://rostovtsev.ru/pub/src/authentic/17.80b/webmin294-vmft.webm

**Comment by jcameron** [comment]
Ok, I see - submitting a change with a fix.

**Comment by qooob** [comment]
Thanks! ;)
