### ISSUE TITLE
Detecting user directory for wheel users

### ISSUE THREAD

**Issue by qooob** [webmin/webmin#299]
Jamie, hi!

I've been trying to figure out why `filemin/bookmarks.cgi` doesn't work and came to the conclusion that in case user being in wheel group logged in (but not root) - there is a problem.

Home directory always resolves to `/root`. It should be `/home/username`. It seems that Webmin sees the current user as administrator and default's it's path to `/root`.

To reproduce it just login to Webmin using non-root user name (but with user that is in wheel group) - it will not work correctly. For `root` and other users - it's fine.

https://github.com/qooob/authentic-theme/issues/389

**Comment by qooob** [comment]
I'm aware about `switch_remote_user()`

**Comment by jcameron** [comment]
Are you logging into Webmin as a sudo-capable user? The issue may be that Filemin is running with  the permissions of that user, but thinks that `/root` is the home directory (which it cannot write to).

**Comment by qooob** [comment]
Correct, Jamie. I double checked and found that it didn't really happen because Webmin Core wasn't loaded there properly.

I tried it on the changed/optimized version of the theme and all seems correct - `switch_to_remote_user()`does what it should. 

Sorry for bothering.

I will fix that Filemin bug under _Authentic Theme_ first and it'll work correctly. Later I'll check the fix for the distro. (bookmarks in Filemin are going to be reworked right now, all we need a minus button near bookmark and ability to add them)..

**Comment by qooob** [comment]
..content of the bookmark file and the path must be toggled not constantly added..
