### ISSUE TITLE
Bootup and Shutdown: shutdown and reboot actions

### ISSUE THREAD

**Issue by qooob** [webmin/webmin#302]
Hi, Jamie.

I think it's worth adding some sort of a salt for submitting _Shutdown/Reboot_ actions, because if you shutdown the machine and then close the browser, and later turn the machine on, and start the browser with option `Continue where you left off`, it loads Webmin at the same page and again re-submits shutdown action - it's not desired and annoying. At the same time after shutdown is hit you can't quickly navigate away to other Webmin page, to work-around this problem.

Makes sense?

**Comment by jcameron** [comment]
Good point - I will change all those buttons to use a POST form, which should prevent a double submit.

**Comment by qooob** [comment]
:+1:
