### ISSUE TITLE
syslog-ng read/write network() source

### ISSUE THREAD

**Issue by MrUlmo** [webmin/webmin#303]
syslog-ng module needs to be able to read/write network() source, since BSD syslog protocol is obsolete.

network() source:
https://www.balabit.com/sites/default/files/documents/syslog-ng-ose-latest-guides/en/syslog-ng-ose-guide-admin/html/reference-source-network.html

BSD syslog protocol:
https://www.balabit.com/sites/default/files/documents/syslog-ng-ose-latest-guides/en/syslog-ng-ose-guide-admin/html/configuring-sources-tcpudp.html

**Comment by jcameron** [comment]
Ok, but how is this related to Webmin? Does the UI not support the network source?

**Comment by MrUlmo** [comment]
It can only read/write BSD syslog protocol (tcp, tcp6, udp, udp6).
![write](https://cloud.githubusercontent.com/assets/16691924/14406466/a59b207e-fea8-11e5-8ebc-ffccce45714b.jpg)


Reading network() source, results in "none"
![read](https://cloud.githubusercontent.com/assets/16691924/14406411/f41eb730-fea6-11e5-917b-4161ce47a254.jpg)

Am I missing something? should the module be able to read/write network() source from/to the syslog-ng config file?

**Comment by jcameron** [comment]
Oh, I see what you mean now ... I'll add support for this network() source.

**Comment by MrUlmo** [comment]
Thank you

**Comment by jcameron** [comment]
This has been implemented, for inclusion in the next Webmin release.
