### ISSUE TITLE
Updating Kernel in Fedora 23

### ISSUE THREAD

**Issue by qooob** [webmin/webmin#304]
Jamie, hi!

After updating the kernel on Debian 8, for example, you get a message on System Information page (about kernel update and necessity to restart the machine). This doesn't happen in Fedora 23 for some reason?

Could you take a look please?

**Comment by jcameron** [comment]
It happens on Debian because the kernel package create a flag file indicating that a reboot is needed. I don't know of any way of detecting that a new kernel has been installed and needs a reboot to apply on Fedora.
