### ISSUE TITLE
Software Package Updates: Doesn't install updates

### ISSUE THREAD

**Issue by qooob** [webmin/webmin#311]
Jamie, hi!

When I ran today (it happened surely before but I didn't have debug information) `Update Selected Packages` it seemed to start the process. After a while the whole thing were just spinning.

I typed `ps aux |grep dnf` and had in return strange output:

```
root      46342  0.0  0.0  11752  2808 ?        S    20:05   0:00 sh -c /bin/dnf  -y update dnf\.noarch dnf\-conf\.noarch dnf\-plugins\-core\.noarch dnf\-yum\.noarch emacs\-filesystem\.noarch gcc\.x86_64 gnutls\.x86_64 libblkid\.x86_64 libfdisk\.x86_64 libgcc\.x86_64 libgcc\.i686 libgomp\.x86_64 libmediainfo\.x86_64 libmfx\.x86_64 libmount\.x86_64 libsmartcols\.x86_64 libsmbclient\.x86_64 libstdc\+\+\.x86_64 libstdc\+\+\.i686 libuuid\.x86_64 libwbclient\.x86_64 mediainfo\.x86_64 postgresql\-libs\.x86_64 python\-dnf\-plugins\-core\.noarch python2\-dnf\.noarch python3\-dnf\.noarch python3\-dnf\-plugins\-core\.noarch samba\-client\-libs\.x86_64 samba\-common\.noarch samba\-common\-libs\.x86_64 samba\-common\-tools\.x86_64 samba\-libs\.x86_64 samba\-winbind\.x86_64 samba\-winbind\-modules\.x86_64 setroubleshoot\-server\.x86_64 traceroute\.x86_64 util\-linux\.x86_64 vim\-minimal\.x86_64 </dev/null 2>&1
root      46343  0.8  0.1 548060 101932 ?       S    20:05   0:02 /usr/bin/python3 /bin/dnf -y update dnf.noarch dnf-conf.noarch dnf-plugins-core.noarch dnf-yum.noarch emacs-filesystem.noarch gcc.x86_64 gnutls.x86_64 libblkid.x86_64 libfdisk.x86_64 libgcc.x86_64 libgcc.i686 libgomp.x86_64 libmediainfo.x86_64 libmfx.x86_64 libmount.x86_64 libsmartcols.x86_64 libsmbclient.x86_64 libstdc++.x86_64 libstdc++.i686 libuuid.x86_64 libwbclient.x86_64 mediainfo.x86_64 postgresql-libs.x86_64 python-dnf-plugins-core.noarch python2-dnf.noarch python3-dnf.noarch python3-dnf-plugins-core.noarch samba-client-libs.x86_64 samba-common.noarch samba-common-libs.x86_64 samba-common-tools.x86_64 samba-libs.x86_64 samba-winbind.x86_64 samba-winbind-modules.x86_64 setroubleshoot-server.x86_64 traceroute.x86_64 util-linux.x86_64 vim-minimal.x86_64

```

Most importantly `dnf update` in console didn't even complain about the process above and proposed to perform an update.

OS: Fedora 23

Please take a look.

**Comment by jcameron** [comment]
That DNF command looks OK to me - if you run `strace` on the stuck process, does it show any progress?

**Comment by qooob** [comment]
I would say no, because `yum/dnf` doesn't allow parallel processes and always typed warnings (like there is another process running.. please wait)

Why is it ok if it's 2 of them? What I have for `ps aux |grep dnf` in the example above is what produced after clicking `Update Selected Packages` - isn't should be only one?

Anyway - it doesn't work. I will let you know how it goes on the next major update. Tell me what you would need me to stat so you have better debug info.

**Comment by jcameron** [comment]
I meant, you can run `strace -p 46343` to trace the running process.

**Comment by qooob** [comment]
Well, I will do, as for now I've `killed -9` it.

**Comment by qooob** [comment]
Alright, today things didn't got stuck. It was installed but after installation Webmin displayed:

`Successfully installed 3 packages.`

However, it was _59_ + _3_ packages, 3 of which security (kernel).

Index page showed things correctly but not post install message. I think, this malfunctioning is connected with not clearing packages from System Information page after applying the updates.

[#282](https://github.com/webmin/webmin/issues/282)
