### ISSUE TITLE
Doesn't work with MySQL 5.7.12

### ISSUE THREAD

**Issue by mbnoimi** [webmin/webmin#312]
Hi,

Webmin was working fine with MySQL server but suddenly today (after upgrading to recent MySQL server) I noticed Webmin unable to connect to MySQL server although MySQL is running fine!
1. Webmin 1.791
2. Ubuntu Linux 14.04.4
3. Linux 3.13.0-85-generic on x86_64
4. MySQL Community Server 5.7.12 
5. /etc/webmin/mysql

```
webmin_subs=0
nopwd=0
style=1
perpage=25
passwd_mode=0
date_subs=0
my_cnf=/etc/mysql/my.cnf
max_dbs=50
blob_mode=0
add_mode=1
mysql_data=/var/lib/mysql
start_cmd=service mysql start
mysqlimport=/usr/bin/mysqlimport
login=root
stop_cmd=service mysql stop
mysqlshow=/usr/bin/mysqlshow
mysql=/usr/bin/mysql
mysqldump=/usr/bin/mysqldump
mysqladmin=/usr/bin/mysqladmin
mysql_libs=/usr/local/mysql/lib
access=*: *
nodbi=0
max_text=1000
pass=mypassword
port=
sock=
charset=
encoding=
mysqld=
host=
```

![screenshot_2016-04-17_16-38-51](https://cloud.githubusercontent.com/assets/284547/14605374/ec2d6194-0580-11e6-9802-cbda9bb34af2.png)

**Comment by qooob** [comment]
What theme version are you using?

**Comment by mbnoimi** [comment]
> What theme version are you using?

I don't know but I use the theme shipped with Webmin

**Comment by mbnoimi** [comment]
BTW, Although I believe theme isn't related to this bug but I changed the theme to the default one but the bug still occurs,

**Comment by JCMais** [comment]
were you able to fix this?

**Comment by swelljoe** [comment]
If the DBI module causes it to break, an upgrade to a more recent version of that Perl module might fix it, as well. But, if you aren't doing anything heavy with the MySQL module, turning it off should also be fine. I don't think any functionality is missing, it'd just be a little slower and take more memory (as when you don't use the DBI, Webmin interacts with the CLI mysql client).

**Comment by swelljoe** [comment]
I think MySQL 5.7 is working pretty well now. There have been a number of patches for MySQL 5.7 and people are using it in product since this issue so I'm guessing this specific issue is gone. If I'm wrong, feel free to re-open.
