### ISSUE TITLE
System Documentation: No `pre` tag makes things broken

### ISSUE THREAD

**Issue by qooob** [webmin/webmin#313]
Jamie, hi!

I just noticed that in CentOS 6.7 (unlike in Fedora 23) the documents are not displayed properly and everything looks funky and broken.

To reproduce it, search `httpd` on CentOS 7 and nothing is displayed correctly, without wrapping things in `pre` tag.

Seems like this part of `view_man.cgi` doesn't work correctly:

``` Perl
# Old version of man2html
$cmd .= " $qout | $config{'man2html_path'} -H \"\" -M \"view_man.cgi\"";
$out = &backquote_command("$cmd 2>&1", 1);
$out =~ s/^.*Content-type:.*\n//i;
$out =~ s/http:\/\///ig;
$out =~ s/\?/\?sec=/ig;
$out =~ s/\+/&opts=$in{'opts'}&page=/ig;
$out =~ s/<HTML>.*<BODY>//isg;
$out =~ s/<\/HTML>//ig;
$out =~ s/<\/BODY>//ig;
$out =~ s/<A HREF="file:[^"]+">([^<]+)<\/a>/$1/ig;
$out =~ s/<A HREF="view_man.cgi">/<A HREF=\"\">/i;
}
&show_view_table(&text('man_header', $in{'page'}, $in{'sec'}),
     $out);
```

Broken output on CentOS:
![screenshot from 2016-04-23 21-01-39](https://cloud.githubusercontent.com/assets/4426533/14763180/202a2fb4-099f-11e6-96a9-a2a342320d24.png)

Alright output on Fedora:
![screenshot from 2016-04-23 21-02-15](https://cloud.githubusercontent.com/assets/4426533/14763184/2dd45464-099f-11e6-978a-2900f0fee789.png)

**Comment by jcameron** [comment]
It seems like on CentOS, the man command is outputting HTML which Webmin then escapes itself to produce that invalid output. Or it could be that Webmin is using the `man2html` command wrong.

Do you have the `man2html` command on your system?

**Comment by qooob** [comment]
Yes, 


```
[root@debug ~]# whereis man2html
man2html: /usr/bin/man2html /usr/share/man/man1/man2html.1.gz

```

**Comment by jcameron** [comment]
I just tested this on a CentOS 7 system with `man2html` installed, and the `httpd` man page worked fine for me. That was with the old theme though ...

**Comment by jcameron** [comment]
I also tried with your latest theme code - it mostly works, but the layout is strange.

Is there something about the output from man2html that makes its HTML difficult to include?

**Comment by qooob** [comment]
This is why I wrote, it was the same with the old theme. It's not looking right on CentOS but on Fedor's is fine.

**Comment by qooob** [comment]
What do you mean? Notably I can see that there is no pre tag. I don't think it should be in HTML having its own formatting, as theme is responsible for that, right?

**Comment by jcameron** [comment]
The `man2html` command outputs HTML though, so putting that inside a pre tag would just cause the raw HTML to be displayed.

**Comment by qooob** [comment]
May be I'm missing something but whtat is the point of using HTML there? Couldn't that be just in plain format? Or it's defined by package itself? If not, on my opinion, non HTML, meaning text wrapped in pre tag is much user friendly/better readable.

**Comment by jcameron** [comment]
The benefit is that bold/italics/fixed-width text in the man page are preserved in the HTML.
