### ISSUE TITLE
Hash Sum mismatch

### ISSUE THREAD

**Issue by stutteringp0et** [webmin/webmin#314]
I saw the post on your homepage about removing the invalid repository - but I never added that repo.  Going by the instructions on the Wiki - I only added:
deb http://download.webmin.com/download/repository sarge contrib

When I attempt install, I get this:

Get:1 http://download.webmin.com/download/repository sarge/contrib amd64 webmin all 1.791 [28.2 MB]
Err:1 http://download.webmin.com/download/repository sarge/contrib i386 webmin all 1.791
  Hash Sum mismatch

Ubuntu 16.04

**Comment by mtompkins** [comment]
Confirming same

**Comment by swelljoe** [comment]
This is a year+ old, so I'm gonna assume whatever problem was happening in the apt repo on webmin.com has been resolved (presumably we would have heard a lot more about it).

**Comment by isos** [comment]
I have the same problem
