### ISSUE TITLE
Usermin Configuration -> Edit Categories - there are two return buttons

### ISSUE THREAD

**Issue by qooob** [webmin/webmin#318]
Jamie, have a look, it happens in all themes:

![screenshot from 2016-04-30 21-12-16](https://cloud.githubusercontent.com/assets/4426533/14937706/e7c7b25e-0f20-11e6-9737-f1c84ee07dc8.png)

https://github.com/qooob/authentic-theme/issues/454

**Comment by qooob** [comment]
..and two buttons on top..

**Comment by qooob** [comment]
..however on top only in Authentic..

**Comment by jcameron** [comment]
This will be fixed in the next Webmin release.

**Comment by qooob** [comment]
👍
