### ISSUE TITLE
WebminCore: redirect() - ability redirect special links

### ISSUE THREAD

**Issue by qooob** [webmin/webmin#324]
Jamie, hi.

Anytime you pass to _redirect()_ something like `index.cgi?/boot/lost+found` it removes the plus in-between.. At least it happens from under '/filemin'. Is there anything could be done about that?

**Comment by jcameron** [comment]
+ is a special character in URLs (it's actually a space). You should call urlize() on any strings used in URLs like this.

**Comment by qooob** [comment]
Yes, true! Is this possible to make it inbuilt in `redirect()`? It could parse the query string and `urlize()` on it, so it would do the following automatically.

From:
`index.cgi?path=/boot/lost+found`

To:
`index.cgi?path=%2Fboot%2Flost%2Bfound`

What you think?

**Comment by jcameron** [comment]
All my existing code that calls redirect already does the appropriate urlize-ation though, so doing it again would cause double quoting. It's up to the caller to do the correct quoting.

**Comment by qooob** [comment]
Alright, I expect that. I will do it on my side. Thanks.
