### ISSUE TITLE
turns off bind, only me or everyone ?

### ISSUE THREAD

**Issue by nkv123** [webmin/webmin#338]
![screenshot - 10 05 2016 - 22 48 23](https://cloud.githubusercontent.com/assets/4409902/15162248/3038d480-1702-11e6-9a17-7916237e2968.png)
You have a screen shot of`# crontab -e` as root
Why does webmin turn off bind at 19 :14 h every day?
I have not made any setting telling it to do so!
Is it only me?

**Comment by jcameron** [comment]
That `resign.pl` script re-generates DNSSEC keys, but it shouldn't turn off BIND - only tell it to reload zone files.

**Comment by swelljoe** [comment]
There's been no follow up in a year, so I'll assume it has been resolved.
