### ISSUE TITLE
Username regexp checking is not checked when adding new users

### ISSUE THREAD

**Issue by jacques** [webmin/webmin#34]
When adding users the username regular expression checking is only checked on bulk user additions.  Adding a single user at a time via the useradmin, ldap-useradmin, and virtualmin do not check for usernames against the regexp.  However adding regexp seems to not work correctly from within webmin.

using a regexp of ([a-z]([a-z0-9-]+?[a-z0-9])?) for username_re seems to not allow usernames like "john" on webmin 1.550.

**Comment by shoulders** [comment]
this should be closed because @jamie says

> but this will be fixed in the next Webmin release.

and 2012
