### ISSUE TITLE
Support request and generation of UTF8 certificates

### ISSUE THREAD

**Issue by victor-rds** [webmin/webmin#353]
It's a simple problem, if you try to generate a certificate that has non-ascii characters the generates garbled text certificate, example: `Informação` becomes `InformaÃ§Ã£o`

Windows built-in certificate fix on the certificate viewer, but some browsers, like firefox, and other SSL utilities have problems with that, also in OpenSSL gives another reason do support:
> string_mask = utf8only #only UTF8Strings (PKIX recommendation after 2004).

That's another reason to support.
This is a two step fix: 

*  Add this to the default openssl.cnf: 
```
string_mask = utf8only
utf8        = yes
```

* Pass `-utf8`, when possible, to the openssl command (req, ca)  

Example of the same certificate by webmin and with `-utf8` 
![certs](https://cloud.githubusercontent.com/assets/5115084/15394871/a00b310e-1dab-11e6-8c20-c96996106972.PNG)

**Comment by jcameron** [comment]
Thanks, I will have webmin / virtualmin use the utf-8 flag in the next version. It looks like those openssl.cnf options are already set by default in modern distros.
