### ISSUE TITLE
Starge commas at `Change Passwords`

### ISSUE THREAD

**Issue by qooob** [webmin/webmin#354]
Jamie, have a look:

![screenshot from 2016-05-20 22-02-22](https://cloud.githubusercontent.com/assets/4426533/15438828/0ff90e44-1edf-11e6-912c-73d0b882f2c1.png)

That looks wired, have a look, fix it please. There those strange `,,,` appear on Ubuntu (probably all debian like systems) for some users. No sure what causes it. You know better.

**Comment by jcameron** [comment]
This can happen if there are extra (empty) fields in the real name. I'll fix it.
