### ISSUE TITLE
Ubutnu 14.04, Webmin 1.801, Potgresql 9.5.3 users don't work

### ISSUE THREAD

**Issue by costa974** [webmin/webmin#359]
PostgreSQL Users	
SQL select usename,usesysid,usecreatedb,usesuper,usecatupd,passwd,valuntil from pg_user failed : column "usecatupd" does not exist

**Comment by jcameron** [comment]
If you run the query `desc pg_user` , what columns does it show the table has?

**Comment by costa974** [comment]
I ran the following sql:
SELECT * FROM information_schema.columns WHERE table_name = 'pg_user';

and exported the result as csv:

"table_catalog","table_schema","table_name","column_name","ordinal_position","column_default","is_nullable","data_type","character_maximum_length","character_octet_length","numeric_precision","numeric_precision_radix","numeric_scale","datetime_precision","interval_type","interval_precision","character_set_catalog","character_set_schema","character_set_name","collation_catalog","collation_schema","collation_name","domain_catalog","domain_schema","domain_name","udt_catalog","udt_schema","udt_name","scope_catalog","scope_schema","scope_name","maximum_cardinality","dtd_identifier","is_self_referencing","is_identity","identity_generation","identity_start","identity_increment","identity_maximum","identity_minimum","identity_cycle","is_generated","generation_expression","is_updatable"
"intellipeg","pg_catalog","pg_user","usename",1,"","YES","name",,,,,,,"",,"","","","","","","","","","intellipeg","pg_catalog","name","","","",,"1","NO","NO","","","","","","","NEVER","","NO"
"intellipeg","pg_catalog","pg_user","usesysid",2,"","YES","oid",,,,,,,"",,"","","","","","","","","","intellipeg","pg_catalog","oid","","","",,"2","NO","NO","","","","","","","NEVER","","NO"
"intellipeg","pg_catalog","pg_user","usecreatedb",3,"","YES","boolean",,,,,,,"",,"","","","","","","","","","intellipeg","pg_catalog","bool","","","",,"3","NO","NO","","","","","","","NEVER","","NO"
"intellipeg","pg_catalog","pg_user","usesuper",4,"","YES","boolean",,,,,,,"",,"","","","","","","","","","intellipeg","pg_catalog","bool","","","",,"4","NO","NO","","","","","","","NEVER","","NO"
"intellipeg","pg_catalog","pg_user","userepl",5,"","YES","boolean",,,,,,,"",,"","","","","","","","","","intellipeg","pg_catalog","bool","","","",,"5","NO","NO","","","","","","","NEVER","","NO"
"intellipeg","pg_catalog","pg_user","usebypassrls",6,"","YES","boolean",,,,,,,"",,"","","","","","","","","","intellipeg","pg_catalog","bool","","","",,"6","NO","NO","","","","","","","NEVER","","NO"
"intellipeg","pg_catalog","pg_user","passwd",7,"","YES","text",,1073741824,,,,,"",,"","","","","","","","","","intellipeg","pg_catalog","text","","","",,"7","NO","NO","","","","","","","NEVER","","NO"
"intellipeg","pg_catalog","pg_user","valuntil",8,"","YES","abstime",,,,,,,"",,"","","","","","","","","","intellipeg","pg_catalog","abstime","","","",,"8","NO","NO","","","","","","","NEVER","","NO"
"intellipeg","pg_catalog","pg_user","useconfig",9,"","YES","ARRAY",,,,,,,"",,"","","","","","","","","","intellipeg","pg_catalog","_text","","","",,"9","NO","NO","","","","","","","NEVER","","NO"

**Comment by costa974** [comment]
Something has changed in Postgres 9.5:

https://www.postgresql.org/docs/9.5/static/view-pg-user.html

**Comment by jcameron** [comment]
Ok, the next release of Webmin will handle PostgreSQL 9.5 permissions properly.

**Comment by costa974** [comment]
Great!
