### ISSUE TITLE
$dom is undefined in dt_resign_zone?

### ISSUE THREAD

**Issue by swelljoe** [webmin/webmin#360]
I'm converting bind8-lib.pl to be strict/warnings compliant, and it's found what looks like a bug:

https://github.com/webmin/webmin/blob/master/bind8/bind8-lib.pl#L3964

Function call is:

    @recs = &read_zone_file($z, $dom);

But, $dom isn't defined anywhere. I don't understand what's happening here enough to fix it.

**Comment by jcameron** [comment]
It's defined on line 3929

**Comment by swelljoe** [comment]
Oh, I linked the wrong line. I'm actually trying to figure out dt_sign_zone and dt_resign_zone, not that one. Line is here:

https://github.com/webmin/webmin/blob/master/bind8/bind8-lib.pl#L3692

And here:

https://github.com/webmin/webmin/blob/master/bind8/bind8-lib.pl#L3772

$dom is not defined in either function, but it looks $d is, and it looks like $d is actually what we need there (or $d needs to be renamed $dom).

**Comment by jcameron** [comment]
You're right, in both cases $d should be used instead of $dom
