### ISSUE TITLE
$module_config undefined, think it's a bug

### ISSUE THREAD

**Issue by swelljoe** [webmin/webmin#361]
This looks like a bug:

https://github.com/webmin/webmin/blob/master/bind8/bind8-lib.pl#L2447

&lock_file($module_config);

$module_config is only used in four places in all of Webmin; in this one module. Seems like a bug, and should probably actually be $module_config_file. You don't need to fix it (and shouldn't because I'm in the middle of a huge commit to make bind8-lib.pl use strict/warn), just confirm this is actually a bug and should actually call $module_config_file.

**Comment by jcameron** [comment]
That's a bug ... I've checked in a fix for it.

**Comment by swelljoe** [comment]
I fixed it in my pull request, too, as I was pretty confident that was bug.

**Comment by swelljoe** [comment]
And, now we have conflicts in that pull request. Poop. I dunno how to resolve conflicts in git. ;-)

**Comment by jcameron** [comment]
You may have to copy bind8-lib.pl to /tmp, create a new pull request, copy bind8-lib.pl back in, and re-submit.
