### ISSUE TITLE
Restoring Security Alerts that were removed in Authentic Theme 18.00+

### ISSUE THREAD

**Issue by qooob** [webmin/webmin#363]
Jamie, hi!

Please be kind adding _Security Alerts_ to WebminCore what we agreed to remove from the theme side. 

Something simple - customizable notifications for: 
   1. Landing on login page;
   2. Failed login attempt;
   3. Succesful login.

It should be tweaked by user. Also please add `user_agent` part (..but this time (unlike me) doing proper escaping.. )

Something like that:

>Subj: Webmin pre-login page access alert (host.cloud.com)

>Msg: Webmin pre-login page is accessed by unauthenticated user from 1.3.4.9

>Webmin 1.791 on cloud.qooob.ru (Fedora Linux 22)
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2661.94 Safari/537.36

**Comment by jcameron** [comment]
Sure, I'll look into adding a feature for this. Some of this is covered by a new feature in webmin 1.801 to show recent logins on the system information page, although email could also be useful.

**Comment by qooob** [comment]
Alright, we're looking forward to it.

**Comment by swelljoe** [comment]
It might be worth thinking on a destination agnostic approach to this. e.g. a notifications system that maybe expands on webmin_log, and can be fed to a pluggable consumer (Status module could also be configured to talk to such a thing eventually, and also be a consumer of those notifications for simple status display). Plugins for it could be things like email, NagiOS, InfluxDB or Prometheus, Pager Duty, log, etc. (We don't need to actually provide al those, just the hooks for it.)

I think email is probably suboptimal for all but the tiniest deployments. Would likely be quite noisy with more than a couple public servers. The goal for any alert is to only get someone's attention when there is an actionable problem. I don't want an email every time someone tries to login...I want automatic mitigation of brute force attacks (which Webmin has and fail2ban improves upon). But a log or database of who has logged in and when is useful and actionable (or at least auditable).

**Comment by qooob** [comment]
Yes, the alerts could be noisy. It's optional (like it was in the theme) so it would satisfy all.

There are multiple ways of doing things but it's better to provide direct solutions (by Webmin), rather than using third-party.

I removed this function because I expected that we agreed to have it on Webmin side (which makes much more sense having it in the theme). 

In case it's off by default and provides same or better functionality that it was in the theme, all will be happy, I bet! ;)

**Comment by jcameron** [comment]
What I'll do is make the log destination configurable. Currently logins are already tracked in the Webmin Actions Log module, which could be enhanced to optionally send email or other notifications.

Emailing `root` on the local machine isn't too useful though, as in the majority of systems nobody ever reads email to `root`

**Comment by qooob** [comment]
It should be configurable either local user, like root or valid email address.

**Comment by swelljoe** [comment]
I'm not arguing against having the functionality, Ilia. I just think email is a sub-optimal way to notify users of problems, and that login attempts are a sub-optimal metric to measure. I'm like Tron, fighting for the user! ;-)

But, something configurable is the right way to go, and most of the functionality already exists in Webmin.

**Comment by qooob** [comment]
In addition to emails, I would enroll XMPP messages notifications (support across all Webmin). I'm still having in mind adding XMPP chat for the theme, to tie all Webmin users together!

Emails can be considered bad or good, it's all about preferences. But it's surely an _option_ that we can't ignore.

**Comment by swelljoe** [comment]
Don't put XMPP into the theme! Make a new module for it. ;-)

**Comment by jcameron** [comment]
Logging via email has been implemented in webmin for inclusion in the next release.

**Comment by qooob** [comment]
When I get to it, Joe, we'll discuss it! ;)

Jamie, is there a way to take a look at the changes? Are they checked?

**Comment by jcameron** [comment]
Yes, see the following commits :

https://github.com/webmin/webmin/commit/17f3235798b65d104d43792b3264e16061443fa7
https://github.com/webmin/webmin/commit/005857ccd17fa495eb27aa89b317938e305052c3
https://github.com/webmin/webmin/commit/025be61e1edc8481f91e2b65d1ccf748261de257

**Comment by qooob** [comment]
Thanks, Jamie!

Will it log and thus send emails upon landing the login page?

**Comment by jcameron** [comment]
Yes, it will support that.

**Comment by qooob** [comment]
Thank you, Jamie!
