### ISSUE TITLE
$view is undefined in delete_zone.cgi

### ISSUE THREAD

**Issue by swelljoe** [webmin/webmin#368]
In this line:

https://github.com/webmin/webmin/blob/master/bind8/delete_zone.cgi#L10

&can_edit_zone($zconf, $view) ||
    &error($text{'master_edelete'});

I think this should be $in{'view'}, instead of $view. If that's right, no need to do anything, as that's the change I've made. If it's wrong, holler at me.

**Comment by jcameron** [comment]
Actually, $view isn't needed at all, as it can be gotten from the $zone object by can_edit_zone. I'll fix that..
