### ISSUE TITLE
$ipv6revzone is undefined in delete_zone.cgi

### ISSUE THREAD

**Issue by swelljoe** [webmin/webmin#369]
In this line:

```
my $rev = ($zconf->{'value'} =~ /in-addr\.arpa/i ||
      $zconf->{'value'} =~ /\.$ipv6revzone/i);
```

I don't see it being defined in bind8-lib.pl; it appears to be defined in records-lib.pl, but that's not included into delete_zone.cgi, so I think this is bug-like.

I don't understand what's happening here well enough to know if the definition in records-lib.pl would solve it (`my $ipv6revzone = $config{'ipv6_mode'} ? "ip6.arpa" : "ip6.int";`).

**Comment by jcameron** [comment]
It's defined in records-lib.pl , but due to the `my` it isn't in scope in delete_zone.cgi (and other CGI scripts). Since it's basically a global, `our` should be used instead.

**Comment by swelljoe** [comment]
It won't need to be an our variable in records-lib.pl, it'll just need to be declared as our in the file where it is used, right? Or am I misunderstanding scope at the package level? (And, I see now that records-lib.pl gets pulled in by bind8-lib.pl.)

**Comment by jcameron** [comment]
I've checked in a fix that should set the scope properly.
