### ISSUE TITLE
$bconf is undefined in edit_delegation.cgi

### ISSUE THREAD

**Issue by swelljoe** [webmin/webmin#371]
I believe I just need this, to fix it:

```
      my $bconf = &get_config();
      print &move_zone_button($bconf, $zone->{'viewindex'}, $in{'zone'});
```

Holler if that's wrong.

**Comment by swelljoe** [comment]
There is a $zconf defined, maybe that's what it wants instead?

**Comment by jcameron** [comment]
I've checked in https://github.com/webmin/webmin/commit/1bd406d5c8247c17d79cfc366f356f53860bbaa1 to fix this.
