### ISSUE TITLE
edit_slave.cgi/edit_stub.cgi has an unused $soa variable

### ISSUE THREAD

**Issue by swelljoe** [webmin/webmin#374]
This line sets $soa:

https://github.com/webmin/webmin/blob/master/bind8/edit_slave.cgi#L37

`if ($r->{'type'} eq "SOA") { $soa = $r; }`

But, nothing happens with $soa.

I guess it's dead code and should disappear?

**Comment by jcameron** [comment]
Thanks, I'll remove that
