### ISSUE TITLE
Invalid use of $in in edit_zonedt.cgi

### ISSUE THREAD

**Issue by swelljoe** [webmin/webmin#375]
On this line:

https://github.com/webmin/webmin/blob/master/bind8/edit_zonedt.cgi#L36

```
        print &ui_hidden_start($text{'dt_zone_expandsep'},
                                 "sep", 0, "edit_zonedt.cgi?$in");
```

$in isn't gonna ever contain anything. I'm guessing it should be $in{'zone'} or maybe $in{'view'}. I don't have the dnssectools setup, so I can't test this to see what it's supposed to be, but it definitely should be something other than what it is.

**Comment by swelljoe** [comment]
Same problem in edit_zonekey.cgi.

**Comment by jcameron** [comment]
Actually, `$in` is set by `&ReadParse();` to be the full query string for this CGI.

**Comment by swelljoe** [comment]
Ah, so I just need to declare it with our. Can do.
