### ISSUE TITLE
`hwclock` new format on Fedora 23+

### ISSUE THREAD

**Issue by qooob** [webmin/webmin#379]
Jamie, hi!

It seems that `hwclock` has been upgraded. Please take a look:

![screenshot from 2016-06-02 13-09-47](https://cloud.githubusercontent.com/assets/4426533/15741768/32d22c74-28cc-11e6-8f0c-9169ea4e557d.png)

**Comment by jcameron** [comment]
Can you try out the patch that I just committed above?

**Comment by qooob** [comment]
No, Jamie, same output (2016-06-10 22:58:17.999536+3:00) - it didn't help. Something else is missing..

**Comment by jcameron** [comment]
Ok, I've committed a new fix that should handle this format.
