### ISSUE TITLE
@vals is undefined and only used once; probably a typo

### ISSUE THREAD

**Issue by swelljoe** [webmin/webmin#380]
In this line:

https://github.com/webmin/webmin/blob/master/bind8/save_record.cgi#L135

```
       &valname($in{'value0'}) ||
                  &error(&text('edit_ehost', $vals[0]));
```

I'm pretty sure $vals[0] is supposed to be $vals

Unless this is some Perl semantic I don't understand. But, strict complains about it, so even if it is supposed to be providing some subset of $vals, it should probably be rewritten. I'm changing it to $vals in my next pull request, unless you object.

**Comment by jcameron** [comment]
You're right ... I'm checking in a fix now
