### ISSUE TITLE
$conf is undefined in save_slave.cgi

### ISSUE THREAD

**Issue by swelljoe** [webmin/webmin#381]
In this line: 

https://github.com/webmin/webmin/blob/master/bind8/save_slave.cgi#L45

`$file = &base_directory($conf)."/".$file;`

$conf is undefined. Looks like just adding this at the top will fix that:

my $conf = &get_config();

I'll add that to my next pull request, unless that's a wrong thing.

**Comment by jcameron** [comment]
No, that seems like the right thing to do
