### ISSUE TITLE
@views is undefined in slave_add.cgi

### ISSUE THREAD

**Issue by swelljoe** [webmin/webmin#382]
In this line:

https://github.com/webmin/webmin/blob/master/bind8/slave_add.cgi#L48

```
foreach my $v (@views) {
      push(@zoneconfs, &find("zone", $v->{'members'}));
      }
```

I'm not immediately seeing the right solution to that, as I don't see where @views would come from.

**Comment by jcameron** [comment]
Checking in a fix for this now
