### ISSUE TITLE
Incorrect IP resolve in "Recent Webmin logins"

### ISSUE THREAD

**Issue by Trejjam** [webmin/webmin#388]
Hello,

my Webmin installation do not properly log IP address behind reverse proxy. I see in "Recent Webmin logins" IP address of reverse proxy. But for example `/var/webmin/miniserv.log` has real remote IP addess (value from `X-Real-IP`)

**Comment by jcameron** [comment]
You can fix this by adding the line `trust_real_ip=1` to `/etc/webmin/miniserv.conf` and then running `/etc/webmin/restart`

It isn't on by default, to protect Webmin systems that are directly connected from having the client IP faked.

**Comment by Trejjam** [comment]
:+1: Thank you
