### ISSUE TITLE
@time_now undefined in bandwidth-lib.pl

### ISSUE THREAD

**Issue by swelljoe** [webmin/webmin#392]
https://github.com/webmin/webmin/blob/master/bandwidth/bandwidth-lib.pl#L347

In these lines:

```
my $tm = timelocal($sec, $min, $hr, $day,
                               &month_to_number($mon), $time_now[5]);
if ($tm > $time_now + 24*60*60) {
   # Was really last year
   $tm = timelocal($sec, $min, $hr, $day,
                            &month_to_number($mon), $time_now[5]-1);
```

The time_now array is undefined, as far as I can tell. $time_now is defined in this line from the arguments:

```
my ($line, $hours, $time_now) = @_;
```

Unless that's a reference to an array instead of a scalar (but if it is it's not being used as such). I can't find any callers to this function, so I don't know exactly what's supposed to be happening.

In rotate.pl, @time_now gets set this way:

````
@time_now = localtime($time_now);
```
Maybe that's the right thing here?

**Comment by jcameron** [comment]
Yeah, that's correct - checking in a fix for this now.
