### ISSUE TITLE
Connection to GitHub using http_download() not working.

### ISSUE THREAD

**Issue by qooob** [webmin/webmin#393]
Jamie, hi.

It seems that connection to GitHub using `http_download()` no longer works.

https://github.com/qooob/authentic-theme/issues/491

**Comment by qooob** [comment]
It seems related to the changes that were made to SSL recently.

**Comment by jcameron** [comment]
What specific URL is failing? Also, do you have any error message?

The issue may be that github is throttling or rejecting connections from Webmin.

**Comment by qooob** [comment]
Theme's direct link: https://raw.githubusercontent.com/qooob/authentic-theme/master/.build/authentic-theme-latest.wbt.gz and https://raw.githubusercontent.com/qooob/authentic-theme/master/VERSION.txt that always worked.

Should I then change the headers and make the call outside of `http_download()`. I'm still having a thought that this is SSL related, that recently was changed.

**Comment by jcameron** [comment]
If you download the URL https://raw.githubusercontent.com/qooob/authentic-theme/master/.build/authentic-theme-latest.wbt.gz in the Upload and Download module in Webmin on a system that's seeing this problem, does it still fail? Because that worked for me.

**Comment by qooob** [comment]
I see the problem now.

Look what's added by Webmin to a file after it was downloaded, for example (VERSION.txt)[https://raw.githubusercontent.com/qooob/authentic-theme/master/VERSION.txt]:

```
X-GitHub-Request-Id: 87CC1C13:0476:A347AA:00337844
Content-Length: 6
Accept-Ranges: bytes
Date: Sun, 19 Jun 2016 08:37:56 GMT
Via: 1.1 varnish
Connection: close
X-Served-By: cache-ams4143-AMS
X-Cache: HIT
X-Cache-Hits: 1
Vary: Authorization,Accept-Encoding
Access-Control-Allow-Origin: *
Expires: Sun, 19 Jun 2016 08:42:56 GMT
Source-Age: 95

18.03
```

File should only contain `18.03`. I bet the same stuff added to other files, including `authentic-theme-latest.wbt.gz` and which is why Webmin says that it's not correct .gzip files:

`
: Not a valid module file : gzip: stdin: not in gzip format tar: Child returned status 1 tar: Error is not recoverable: exiting now`

This makes all downloads broken across Webmin installations and we should release new version as soon as possible.

**Comment by jcameron** [comment]
Ok, I was able to re-produce this. However, only for github downloads!

**Comment by qooob** [comment]
Jamie, GitHib has forced https!

**Comment by jcameron** [comment]
I just checked in a fix for this : https://github.com/webmin/webmin/commit/941f110edaa1d2f2917184a216a428e904dec139

Turns out that github is sending an HTTP header with no value, which breaks web (and probably isn't even allowed by the HTTP spec)

**Comment by qooob** [comment]
Yes, thanks Jamie, quantifier  `between zero and unlimited times` works fine.

**Comment by qooob** [comment]
When are you planning to release 1.802 maybe? Could you also please include version 18.03 of the theme?

**Comment by jcameron** [comment]
I need to clean up a few issues with the BIND module strict/warnings compliance that Joe did first.

**Comment by qooob** [comment]
Sure.

**Comment by qooob** [comment]
Thank you.
