### ISSUE TITLE
Postfix Forward Emails not adding all attachments

### ISSUE THREAD

**Issue by pierrejochem** [webmin/webmin#397]
I'm not sure wheather this is a bug or a feature. 

If I tick more than one email from a user inbox and click on forward then only one email is added (in the received mail). Attachment views Show all selected mails.

Is this correct or should this add all emails as attachment to the new email? 

Version: 1.801

**Comment by jcameron** [comment]
This is a known bug in the current webmin / usermin releases - it also effects forwarding multiple attachments. It will be fixed in the next release though.

**Comment by pierrejochem** [comment]
Thank you for this Information 👍
