### ISSUE TITLE
Webmin can´t start "webmin Error - Perl execution failed"

### ISSUE THREAD

**Issue by bcutter** [webmin/webmin#398]
Hi,

out of nowhere Webmin stopped working. When trying to access it one hour ago, I got a "Error - Perl execution failed" in browser.

So I did a "sudo service webmin restart" and also tried starting it manually - no chance. Result:

```
● webmin.service - LSB: Start or stop the Webmin server
   Loaded: loaded (/etc/init.d/webmin)
   Active: failed (Result: exit-code) since Fr 2016-06-24 21:07:29 CEST; 4min 20s ago
  Process: 28170 ExecStop=/etc/init.d/webmin stop (code=exited, status=0/SUCCESS)
  Process: 30590 ExecStart=/etc/init.d/webmin start (code=exited, status=139)

Jun 24 21:07:29 servername systemd[1]: webmin.service: control process exited, code=exited status=139
Jun 24 21:07:29 servername systemd[1]: Failed to start LSB: Start or stop the Webmin server.
Jun 24 21:07:29 servername systemd[1]: Unit webmin.service entered failed state.
```
So I did a "sudo tail -50 /var/webmin/miniserv.error" which gave me:
```
[20/Jun/2016:16:55:37 +0200] Using MD5 module Digest::MD5
[20/Jun/2016:16:55:37 +0200] PAM authentication enabled
[24/Jun/2016:20:28:17 +0200] [192.168.0.24] / : Perl execution failed : syntax error at (eval 33) line 4, near ";
                        tie"

[24/Jun/2016:20:28:30 +0200] [192.168.0.24] / : Perl execution failed : syntax error at (eval 33) line 4, near ";
                        tie"
```

**I have no idea which script is referred here.**

There was no update of Webmin or perl recently. Latest perl changes on affected system according to "/var/log/apt/history.log" was on 2016-06-05. Server and therefore Webmin has been rebootet once since that time, so I don´t think perl is the root cause here.

I checked running processes, no Webmin left. I checked for existence of "/var/webmin/miniserv.pid" which fails (maybe it is generated on succesful start of Webmin?).

Running Webmin v1.801. It worked until yesterday evening. Timestamp of file "/var/webmin/sessiondb.pag" is "Jun 23 22:26" - which might be the last working time.

**What can I do to fix this (quickly - because Webmin performs my daily SQL backups among lots of other important things!)???**

**Comment by bcutter** [comment]
Hope to here from @jcameron or other experts soon.

**Comment by jcameron** [comment]
Which perl version are you running there? `perl -v` will tell you.

**Comment by bcutter** [comment]
v5.20.2 arm-linux-gnueabihf-thread-multi-64int

**Comment by bcutter** [comment]
Any idea? Any log to check, any magic command, ...?

**Comment by bcutter** [comment]
Giving up for this night. Hope to get some inspiration here after few hours of sleep & downtime.

**Comment by jcameron** [comment]
It looks like perl on your system is unable to run some of the webmin code ... which is odd, because nobody else has reported this. Which linux distribution and version are you running there?

**Comment by bcutter** [comment]
/etc/webmin/config
```
passwd_mindex=4
acceptlang=0
webprefix=
passwd_file=/etc/shadow
passwd_pindex=1
product=webmin
log=1
ld_env=LD_LIBRARY_PATH
theme=authentic-theme
passwd_cindex=2
path=/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin
os_version=8.0
real_os_type=Debian Linux
lang=de.UTF-8
find_pid_command=ps auwwwx | grep NAME | grep -v grep | awk '{ print $2 }'
md5pass=1
real_os_version=8.0
referers_none=0
passwd_uindex=0
by_view=0
os_type=debian-linux
tempdelete_days=7
```

==> Raspbian Jessie (= Debian 8)

**Comment by bcutter** [comment]
Hmm, very strange: I tried installing "debsums" using apt-get for further investigations. Received a very strange error (memory access error). So I performed a reboot. After that, install of debsums worked AND: Webmin runs fine and smooth like it always did. Just for documentary:

- The perl skript which was referenced in above error log is "/usr/share/webmin/miniserv.pl"
- According to webminstats the last entries are from 22.06.2016 21:43, so about 2,5 days ago
- Latest change was already 12 hours before that according apt-get history:
```
Start-Date: 2016-06-22  13:02:27
Commandline: apt-get -y install libraspberrypi-bin libraspberrypi-dev libraspberrypi-doc libraspberrypi0 raspberrypi-bootloader raspberrypi-kernel
Upgrade: libraspberrypi-doc:armhf (1.20160523-1, 1.20160620-1), raspberrypi-kernel:armhf (1.20160523-1, 1.20160620-1), libraspberrypi-bin:armhf (1.20160523-1, 1.20160620-1), raspberrypi-bootloader:armhf (1.20160523-1, 1.20160620-1), libraspberrypi0:armhf (1.20160523-1, 1.20160620-1), libraspberrypi-dev:armhf (1.20160523-1, 1.20160620-1)
End-Date: 2016-06-22  13:06:38
```
So at the end I´ve got NO idea why perl execution failed. It seems only Webmin is using it regularly, so I thought it would be a Webmin issue (and because I found lot of error topics with the same error message regarding Webmin, but usually older versions < 1.701). Therefore closed.

**Comment by jcameron** [comment]
Ok, glad you got that fixed!
