### ISSUE TITLE
$dir is undefined in write_maildir in mailboxes/boxes-lib.pl

### ISSUE THREAD

**Issue by swelljoe** [webmin/webmin#403]
On this line:

https://github.com/webmin/webmin/blob/master/mailboxes/boxes-lib.pl#L2201

Looks like it ought to be $_[1].

So, I'm gonna re-factor that function and capture arguments into variables and replace the @_ stuff. 

If that's wrong, holler.

**Comment by jcameron** [comment]
Yeah, I've checked in a fix for this.
