### ISSUE TITLE
MAIL filehandle is only used in one location, think it should be $h->{'fh'}

### ISSUE THREAD

**Issue by swelljoe** [webmin/webmin#404]
In this line:

https://github.com/webmin/webmin/blob/master/mailboxes/boxes-lib.pl#L933

MAIL seems to be dangling there. I'm not confident of $h->{'fh'}, either, but it's being used in other locations. Once I figure out how to write tests for this, I'll sort out the right/wrong thing but if you know off-hand what's going in there, that's cool, too.

**Comment by jcameron** [comment]
Actually, `$h->{'fh'}` is what should be there - I've checked in a fix
