### ISSUE TITLE
Bind Views incorrectly shown since webmin 1.810

### ISSUE THREAD

**Issue by philrandal** [webmin/webmin#411]
Webin 1.810, with and without the fixed BIND module, claims that all my defined zones are in my "localhost_resolver" zone.

1.801 works just fine

**Comment by bigdogchris** [comment]
I noticed this as well. I had to roll back to 1.801.

I have 2 views. I had zones from 1 view showing up in both views. Deleting them from the wrong view deleted them from the view they should be in. Tried multiple browsers and they all displayed incorrectly. 

This happened immediately after applying 1.810. I rolled back to 1.801 and it was back to normal again.

**Comment by philrandal** [comment]
Can't post screenshots, alas.  Had to revert to earlier version as I only have production boxes.

It lists the views, but gets the contents wrong.

**Comment by jcameron** [comment]
Ok, but did you have webmin configured to display your zones under the views they were members of?

**Comment by philrandal** [comment]
Yes indeed.

**Comment by jcameron** [comment]
I did some testing, but was unable to re-produce this.

Can you attach your named.conf file to this bug?

**Comment by philrandal** [comment]
I'd have to create a test box with imaginary zones, sorry.  That's not possible at this precise moment, alas.

I forgot to say that the platform is CentOS 7.

**Comment by StefanSa** [comment]
Jamie,
i have exactly the same problem. But it does not always appear in all zones / views,
depending on the refresh of webmin page.

**Comment by jcameron** [comment]
Any idea if there is some specific config that triggers it?

**Comment by jcameron** [comment]
Ok, I see the bug now - thanks Phil for the zone file. This will be fixed in the next Webmin release.
