### ISSUE TITLE
DNSSEC DS records automatic propogration between virtual servers

### ISSUE THREAD

**Issue by chris001** [webmin/webmin#414]
It would be great to automate the following for DNSSEC, to save a lot of time and aggravation.
When webmin or virtualmin is hosting the DNSSEC DNS of BOTH the subdomain and the parent domain, webmin can and should simply copy the subdomain's DS records into the parent domain's zone, and it's probably OK to overwrite any DS records that are already in there.
For example:
virtual server: `mydomain.com`  DS records are `ds1` and `ds2`.
virtual server or sub-server : `www.mydomain.com` DS records are `ds3` and `ds4`.

webmin should add `ds3` and `ds4` to DNS zone of `mydomain.com` because webmin knows that it's hosting the DNS for `mydomain.com` and has the ability to automatically propagate the two DS records that locally from `www.mydomain.com` to `mydomain.com` with no human intervention.

**Comment by jcameron** [comment]
Is this necessary if the parent and sub-domain are both in the same zone file (which is usually the case in most Virtualmin setups) ?

**Comment by jcameron** [comment]
Is that necessary even when Virtualmin has the parent and sub-domain in the same zone file (which is the usual case) ?

**Comment by chris001** [comment]
@jcameron Good question.  I've looked at the way the DNSSEC protocol works regarding DS records.  
1. First it queries the root `( dot )` zone to verify it has a DS record for the `com` zone.
2. Then it queries  the `com.` zone contains a DS record for the `mydomain.com.` zone, plus RRSIG and RRKEY records.
3. Next it queries the `mydomain.com.` zone to verify it has a DS record from the `subdomain.mydomain.com.` zone, plus RRSIG and RRKEY records.
4. Then it queries the `subdomain.mydomain.com.` zone to verify the RRSIG and RRKEY records.

So, whether the DS records are in the same zone file or not, isn't relevant?

The DNS server, bind 9 in our case, must answer a query for the DS record and Resource-Record Key and Resource-Record Signature queries with values that compute to satisfy the cryptographic hash that DNSSEC is expecting.

Those DS records need to be propagated up the hierarchy, and could/should be propagated automatically, for those parts of the hierarchy which are totally under the control of webmin.

The only DS record propagation webmin can't automate (at the moment) is the one from `mydomain.com` to the registrar of `mydomain.com`.  The domain owner has to copy paste that themselves once the log into their account at the domain registrar.  The registrar then takes your DS record and automatically provides the DS record to the `com` zone to complete the chain.

**Comment by chris001** [comment]
Here's a good FAQ page on how DNSSEC works from the ISC itself.
https://users.isc.org/~jreed/dnssec-guide/dnssec-guide.html
Of note, google public dns has enabled DNSSEC validation on zones which are secured by DNSSEC, so that any forged/poisoned/bad/fraudulent DNS records will not get propagated out into the internet, at least by the google public DNS.
Other dns servers, which are non-validating of the DNSSEC checks, could still propagate bad/poisoned DNS records.

**Comment by jcameron** [comment]
Thanks for the info - we will work on adding DS records to hosted super-domains for the next release of Virtualmin.

**Comment by chris001** [comment]
@jcameron This is great! To answer your question, will it work if you have the DS record for the subdomain in the same zone file and NOT propagate it to the superdomain, I'd answer, it depends on whether BIND answers the query for DS record for the superdomain `mydomain.com`.  If BIND replies with the DS record then OK.  If I recall correctly it does not, so then that DS record would need to be propagated upward the hierarchy. from the subdomain into the actual superdomain.

**Comment by jcameron** [comment]
This has been implemented, for inclusion in the next Virtualmin release.
