### ISSUE TITLE
Anti-spoofing. Auto generate TLSA DNS records for all TLS service ports

### ISSUE THREAD

**Issue by chris001** [webmin/webmin#417]
This would be a great feature to protect the server from spoofing, phishing, financial fraud, information theft, identity theft.  

Since webmin is usually fully aware of all (or most all) TLS services running - dovecot imap and 993, postfix smtp 25 465 and 587 submission, webmin itself 9000 or whatever port in miniserv.conf, nginx, apache2, nginx, etc.

Webmin should generate the TLSA record for each port running TLS, and include it in the local BIND DNS for the appropriate zone corresponding to the fully qualified domain name which the service is running under.

Once TLSA records are added to DNS, any browser (or application) will be able to detect whether the TLS service is spoofed by a middle man or phishing / financial fraud / organized crime, and if so, will be able to alert the user.  Some browsers require an add-on to check TLSA and alert the user, such as, in firefox, "DNSSEC/TLSA Validator" available from https://www.dnssec-validator.cz/

References:

Tutorial:
https://joscor.com/blog/dane-tlsa-tutorial/

Record generator web form:
https://www.huque.com/bin/gen_tlsa

Command line to auto-create TLSA DNS records:
http://www.internetsociety.org/deploy360/resources/hashslinger-a-tool-for-creating-tlsa-records-for-dane/

**Comment by jcameron** [comment]
Interesting idea ... but don't certs already contain a domain name that clients (like a web browser) are supposed to check when connecting? How could real certs (not self-signed) be spoofed in this case?

**Comment by chris001** [comment]
The reason DANE TLSA records were invented and made part of DNSSEC, is because, motivated criminals (and/or evil admins) can steal TLS certs as well as the private keys, straight off the server.  I've seen servers where this has happened - broken into, root obtained, and certs/keys stolen.

Take for example, myswissbank.ch , they can set up a server as a man-in-the-middle (MITM) running on a different IP address, do a cache-poisoning attack, or spoof the DNS records, so that the user receives the MITM server IP for the bank IP, proxy the entire original mysuissbank.ch website, except with the added gotcha, it will sniff the user account login credentials, account number, pin number, login cookies, perform transfers of funds behind the scenes and not display those to the user.

What DANE does is reduce the attack surface of the TLS (X.509) public/private key security used by the web.  The TLSA icon in firefox shows green padlock for the correct server, red for spoofed/incorrect/fraudulent server.

References and more information:
http://blogs.verisign.com/blog/entry/how_dane_strengthens_security_for
http://dane.verisignlabs.com/
http://tools.ietf.org/html/rfc6698
http://singapore49.icann.org/en/schedule/wed-dnssec/presentation-dnssec-dane-26mar14-en.pdf
http://conferences.npl.co.uk/satin/papers/satin2012-Osterweil.pdf
http://www.verisign.com/en_US/innovation/verisign-labs/dane-protocol/index.xhtml?cmp=SO-BLOG

**Comment by jcameron** [comment]
I'll add support for this to my TODO list for Virtualmin.

Although, if an attacker can MITM the server's SSL connections, couldn't he also MITM the DNS lookups?

**Comment by chris001** [comment]
@jcameron Excellent yes please do add automatic TLSA records generation for all encrypted service ports known by webmin:  smtp, imap, sftp, mail submission, proxy, manually added, the webmin port itself, apache2, nginx, etc.

To answer your question, is TLSA possibly pointless to implement, if the evil actor can MITM both DNS and the SSL connection?

DNSSEC makes DNS much, much harder to MITM, by creating a hierarchy of strong cryptographic hashes, the DS records, generated by a domain and propagated up to the superdomain, which extends up to the internet DNS root.  Consequently, since TLSA is living inside DNSSEC, TLSA is a strong hash of the cert, and so the TLSA hash protects the cert by making the certs/keys much, much harder to fake up a new cert/key for the same domain, and use it for an MITM/phishing/spoofing attack.

Another way TLSA improves the security picture is how it removes the old vulnerability of being totally dependent on the ability of a Certificate Authority to fend off every attack without zero exceptions. 

Many CAs have been compromised and keys stolen in the past few years, and those stolen certs/keys were used for high profile MITM attacks - for example to produce fake google certs!  For financial crime and phishing.  Browser makers mozilla, microsoft, etc, had to removed those broken-into CAs from the browsers' built in list of acceptable CAs.  As you can see with any recent update readme/notes from debian, ubuntu, windows, etc,, they remove many CAs from the ilst of trusted CAs, which ships with the OS.

Reference: http://www.internetsociety.org/deploy360/resources/dane/

**Comment by jcameron** [comment]
Good point about DNSSEC - I guess without it TLSA doesn't offer strong guarantees, but since Virtualmin already supports DNSSEC it makes sense to do TLSA as well.

**Comment by jcameron** [comment]
So I've almost completed TLSA support ... but I ran into a couple of problems combining it with Let's Encrypt. Have you had any success with this (or with other SSL CAs that have a chained cert)? If so, how did you include the chained cert in the TLSA record?

**Comment by chris001** [comment]
I made the TLSA records for a few domains manually by inputting the hostname, port and cert into this web form which computes the TLSA record for you, from the input parameters.
https://www.huque.com/bin/gen_tlsa
After I manually added TLSA record to the DNS zone, did `service bind9 reload`, and cleared client DNS cache, checked it with this form:
https://www.huque.com/bin/danecheck
As a control, enter for hostname `www.huque.com` and port `443`, and it should return success.
This matches the Firefox add-on for DNSSEC and TLSA which show a green key and padlock icons respectively, for the website, but this is not just for web, it's for mail and all services that use SSL/TLS.

For scripted use, better to do command line TLSA record generation. There's an RPM and DEB package of tools called `hash-slinger`, one of these is a command line tool `tlsa` which takes as input parameter the domain name, port and protocol, fetches the TLS cert from the web/mail/other server directly, and then generates the TLSA record.
http://www.internetsociety.org/deploy360/resources/hashslinger-a-tool-for-creating-tlsa-records-for-dane/
http://people.redhat.com/pwouters/hash-slinger/
`apt-get install hash-slinger`
`yum install hash-slinger`
```
    $ tlsa
usage: tlsa [-h] [--verify] [--create] [--version] [-4] [-6] [--insecure]
            [--resolvconf /PATH/TO/RESOLV.CONF] [--port PORT]
            [--protocol {tcp,udp,sctp}] [--only-rr]
            [--rootkey /PATH/TO/ROOT.KEY] [--ca-cert /PATH/TO/CERTSTORE]
            [--debug] [--quiet] [--certificate CERTIFICATE]
            [--output {generic,rfc,both}] [--usage {0,1,2,3}]
            [--selector {0,1}] [--mtype {0,1,2}]
            hostname
    $ tlsa --create ietf.org
    No certificate specified on the commandline, attempting to retrieve it from the server ietf.org.
    Attempting to get certificate from 64.170.98.30
    Got a certificate with Subject: /O=*.ietf.org/OU=Domain Control Validated/CN=*.ietf.org
    _443._tcp.ietf.org. IN TLSA 3 0 1 54f3fd877632a41c65b0ff4e50e254dd7d1873486231dc6cd5e9c1c1963d1e4e
```
With the `tlsa` tool, you don't have to touch the certificate, so there is no chance of providing it the wrong certificate, or a chain when it should be just a cert.  The tool fetches the cert for you as part of opening a tls connection, on any server port, udp or tcp.

Are you getting the letsencrypt certs by using your own code? Or are you using the official `certbot-auto` script privded by letsencrypt, to get the 4 certificate files per domain ( `cert.pem`, `chain.pem`, `fullchain.pem`, `privkey.pem` ) from letsencrypt.org ?

What problems did you run into?

**Comment by jcameron** [comment]
Thanks for that info - I was able to figure out what I was doing wrong with the Let's Encrypt cert, which was putting the domain and CA certs in the wrong order when generating the hash!

The next Virtualmin release will add a config option to create TLSA DNS records for new and updated domains.

**Comment by chris001** [comment]
I just ran a check of the TLSA DNS records online, and it came back with a fail for SMTP port 587 (submission).

It appears that webmin isn't generating all of the TLSA records.  Only generating for some of the https web services running on the server?

Webmin should generate one TLSA record for each port/protocol/hostname combination, which is running TLS.

For TCP TLS and also UDP TLS services which are rare but do exist (real time streaming audio or video media services).

They resemble the microsoft active directory type of generated DNS records.

Transcript below:
```
Check a DANE TLS Service

This application checks a DANE TLS Service. It connects to the specified TLS service and then attempts to authenticate its TLS server certificate according to its corresponding DANE TLSA records in the DNS.

Port: 587
Domain name: mail.myserver.com
STARTTLS application: smtp

DANE Authentication Failed.


Checking Transcript:

FAIL: _587._tcp.mail.myserver.com: Non existent domain name.
No TLSA records found.
```

**Comment by chris001** [comment]
Yes Postfix is running on port 587.
Yes there's a line for smtpd_tls_cert_file
No there's not a smtpd_tls_CAfile
Here's the entire section:
```
# TLS parameters
smtpd_tls_cert_file = /etc/postfix/postfix.cert.pem
smtpd_tls_key_file = /etc/postfix/postfix.key.pem
smtpd_use_tls=yes
smtpd_tls_session_cache_database = btree:${data_directory}/smtpd_scache
smtp_tls_session_cache_database = btree:${data_directory}/smtp_scache
smtpd_tls_mandatory_ciphers = high
smtpd_tls_mandatory_exclude_ciphers = aNULL, MD5
smtpd_tls_security_level = encrypt
```

**Comment by jcameron** [comment]
Was SSL perhaps enabled for Postfix after the `myserver.com` domain was created?

**Comment by chris001** [comment]
Possibly.  The `mydomain.com` domain has been running on Virtualmin GPL for 4 years, starting with virtualmin 3.94 which was released August 2012, and upgraded at every new release.

**Comment by jcameron** [comment]
Try forcing the re-generation of TLSA records by SSHing in as `root` and running `virtualmin modify-dns --domain mydomain.com --enable-tlsa`

**Comment by chris001** [comment]
It's still saying `FAIL: _443._tcp.server6.mydomain.com: Non existent domain name.  No TLSA records found.` probably because, although `https` is serving a page (403 due to no website), the `secure https` feature shows as disabled in the `Edit virtual server` `Enabled features` page, which must be why virtualmin decided to not generate record `_443.tcp.server6.mydomain.com`.

**Comment by jcameron** [comment]
That's expected - Virtualmin will not generate a TLSA record for port 443 unless the domain has it's own SSL website enabled.

**Comment by chris001** [comment]
The instant you enable `SSL website` on the virtual server, and reload the page, which was previously secured with Lets Encrypt and loading fine (yet TLSA was invalid), you get this self-signed cert security error in Firefox 50.  Webmin clobbers the Lets Encrypt cert with a self signed cert:
```
Your connection is not secure

The owner of server6.mydomain.com has configured their website improperly. 
To protect your information from being stolen, Firefox has not connected to this website.

Learn more…

Go Back      Advanced

Report errors like this to help Mozilla identify and block malicious sites

server6.mydomain.com uses an invalid security certificate. 
The certificate is not trusted because it is self-signed. 
The certificate is not valid for the name server6.mydomain.com. 
Error code: SEC_ERROR_UNKNOWN_ISSUER 
```

**Comment by jcameron** [comment]
Are you getting that error from the domain's regular website (on port 443), or from the Virtualmin UI on port 10000 ?

**Comment by chris001** [comment]
From the regular website on port 443.  The virtualmin UI on port 10000 is still using the good green padlock let's encrypt cert.

**Comment by jcameron** [comment]
I'm confused - if the SSL feature wasn't enabled for the website, it shouldn't have had any SSL cert at all previously?

**Comment by chris001** [comment]
Also confused.  Some possible reasons why webmin overwrote the cert in the conf file:

1. the webmin has been running for some time, and SSL website was turned on/off many times, possibly left traces of old self signed certs around, which now signal to webmin that it should use self signed certs.

2. I'm running `certbot-auto` from the command line by `cron` every day to obtain/renew the let's encrypt certs.  At the first run, after answering a couple of simple prompts, it can automatically install its certs into apache2, nginx, a few other web servers' conf files, if the certs aren't already installed.  Webmin may not be aware of this.

**Comment by jcameron** [comment]
Note that by default, when enabling SSL for a domain for the first time which doesn't yet have an SSL cert, Virtualmin will generate a self-signed cert.

**Comment by chris001** [comment]
Yes, self signed certs are handy for certain situations.
Does Virtualmin detect when an outside entity, such as an admin or a script, has added an entry pointing to an SSL cert to the web server conf file, and therefore, it should neither automatically generate a self-signed cert, nor automatically overwrite the existing line referring to the SSL cert, with a line referring to a self-signed cert?
This issue brings up question about how to handle certificate management (let's encrypt CA vs paid public internet CA's vs self signed no CA vs certs from a local CA such as in an organization with its own CA servers) , priority of one cert over another, preference in how Virtualmin is to auto renew or auto replace expired certs, and default actions what to do when a cert is needed and admin doesn't state any preference about which one to use.

**Comment by jcameron** [comment]
Do you mean if an entry was manually added to the Apache config? No, this isn't automatically detected.

The way certs are handled is that if a domain already has a cert (because it has SSL enabled, or had in the past), that cert is preserved. Otherwise, by default a self-signed cert is generated if one is needed. And then there's a config option to immediately request a Let's Encrypt cert at domain creation / SSL enable time to replace it.

**Comment by chris001** [comment]
This feature is not totally working correctly, it should be re-opened.

1. The DANE TLSA record which webmin is supposed to create for its own Let's Encrypt cert, can easily become invalid and trigger security warnings.  See below.  The LE cert was created on the command line using the `certbot-auto` official Let's encrypt script.

*As soon as the LE TLS cert is renewed, either by webmin directly or by the external script, webmin currently neither notices, nor recalculates all the TLSA records, yet it should. This is critically important to maintain a good security score, and display a green padlock on the DANE/TLSA Validator Firefox Add-on.*

```
Check a DANE TLS Service

This application checks a DANE TLS Service. It connects to the specified TLS service and then attempts to authenticate its TLS server certificate according to its corresponding DANE TLSA records in the DNS.

Port: 9001
Domain name: p-subdomain.e-domain.com

DANE Authentication Failed.

Checking Transcript:

TLSA records found: 1
TLSA: 3 1 1 244d3a5d8a7eb81218164c059fd9691b3130b4bf7ca8daac880945c1f67465e6

Connecting to IPv4 address: 198.x.x.x port 9001
TLSv1.2 handshake succeeded.
Cipher: TLSv1.2 DHE-RSA-AES256-GCM-SHA384
Peer Certificate chain:
 0 Subject CN: server5.e-domain.com
   Issuer  CN: Let's Encrypt Authority X3
 SAN dNSName: p-subdomain.e-domain.com
 SAN dNSName: server5.e-domain.com
Error: peer authentication failed. rc=65 (No matching DANE TLSA records)

[2] Authentication failed for all (1) peers.
```

2. There's still the problem/bug, where webmin fails to generate TLSA records for many port and hostname combinations, which are running a TLS service.

Every port/hostname combo which is serving TLS, needs a TLSA record.

Web, email, sip, rtp audio/video streaming gateway, skype gateway, the list is endless.

Many of these servers could currently be running outside the management scope of webmin yet running on the webmin server and connected to other web services managed by webmin.

a. Webmin could automatically pull the hostnames from the certs without needing to ask the user to provide that part.

b. Either webmin should auto detect all ports serving TLS by scanning itself via `netstat`, and/or, webmin could provide a page, for use by the sysadmin, reseller, and virtual server owner, to specify a list of all the ports and hostnames combinations running TLS therefore needing a TLSA record, which webmin would then generate (and automatically detect a new/updated cert and re-generate) TLSA records for.

**Comment by jcameron** [comment]
If you use Virtualmin's support for renewing Let's Encrypt certs (which I recommend), it will also re-generate the TLSA records. It isn't practical to be continually scanning the local system for manual SSL cert changes and updating DNS to match. Similarly, I don't think it's practical to automatically scan all open ports for certificates - especially if services use something like STARTTLS to switch to SSL mode.

**Comment by chris001** [comment]
1. Have had no choice but to stay with using the command line `certbot-auto` because Virtualmin gives an error, saying it cannot manage LE certs because it has detected a prior use of `certbot-auto` on the system.  LE certs have been used on the system prior to Virtualmin's support of LE.

2. About the TLSA expired records, how about when it's time to manually change the paid cert, installed on the nginx ssl reverse proxy, with a new paid cert (because it expires after only 12 months), then the TLSA record for this paid cert will need to be regenerated, preferably automatically by Virtualmin, so Virtualmin should try to detect when it's expired, or when the cert has been replaced, and regenerate the TLSA's.

3. Then there still remains the problems with the ports combinations for the TLSA records, the only remaining option is to let the sysadmin/reseller/virtual server owner explicitly specify in a list, which ports and hostnames and running TLS for the purpose of telling virtualmin the inputs for all of the TLSA record combinations it needs to generate.

**Comment by jcameron** [comment]
For problems 1 and 2, you may be better off by simply running the command :

`virtualmin modify-dns --domain yourdomain.com --enable-tlsa`

after any manual cert changes. This will re-sync all records based on the current certs.

For problem 3, I think that allowing the admin to specify extra ports is the only viable solution. This would take some time to implement in Virtualmin though.

**Comment by chris001** [comment]
I've made some progress on fixing this bug, and adding the full set of TLSA records automatically, when virtualmin hasn't added them because it believes most of the SSL/TLS services aren't running.

If it wouldn't be too much to ask, would it be possible to add functionality into the  `virtualmin` script, to scrape the cert from the server (or maybe easier, grab the cert in `.pem` format directly from the local filesystem) and generate the TLSA record for the first time, insert it into the DNS zone file, and do a reload of the bind dns zone?

Such as, `virtualmin modify-dns --domain mydomain.com --generate-tlsa --port 587 --starttls --protocol tcp`

The algorithm, including command line, just could work, as follows:

1. Input parameters: `mydomain.com`, `portNumber`, `protocol` (tcp, udp, sctp, dccp, ws, wss, etc), and `--starttls` for services which require to connect in plaintext first then, need a command `STARTTLS` to switch to TLS mode and give us the cert.

2. Either grab the cert from the local filesystem, or, Execute the command `openssl s_client -servername mydomain.com -connect mydomain.com:portNumber`
This command retrieves the X.509 TLS certificate for mydomain.com using SNI (server name indication) such as through `https`.  This works conveniently when the web server uses the same TLS cert as the service (mail, webmin, usermin, virtualmin, etc.) running on the port/protocol which we're generating the TLSA record for.  Which is usually, yet not always, the case, you have one letsencrypt (or paid) cert securing all encrypted services running on host mydomain.com .

3. Trim the X.509 TLS certificate starts with and includes `-----BEGIN CERTIFICATE-----` and ends with and includes `-----END CERTIFICATE-----`.

4. Pass the domain, port number, protocol, and cert, to the function to generate the TLSA record for the first time.  The result is a one line string DNS TLSA record to add to the domain's dns zone.

5. Add the TLSA record to the domain's BIND v9 zone file, which is in different location on rpm vs. deb distros, on debian the zone file to insert the record into is `/var/lib/bin/mydomain.com.hosts`  Use virtualmin's built in functions to determine the path to the zone files depending on which distro we're running on, etc.

**Comment by ktyak** [comment]
+1 "Then there still remains the problems with the ports combinations for the TLSA records, the only remaining option is to let the sysadmin/reseller/virtual server owner explicitly specify in a list, which ports and hostnames and running TLS for the purpose of telling virtualmin the inputs for all of the TLSA record combinations it needs to generate." For some reason '--generate-tlsa' did not generate an entry for port 25 even though it is in use on my vmin setup.

**Comment by ruediger12** [comment]
+1 "For some reason '--generate-tlsa' did not generate an entry for port 25 even though it is in use on my vmin setup." - Same issue here

**Comment by jcameron** [comment]
@ruediger12 - is there a line for `smtp` in your `/etc/postfix/master.cf` file?

**Comment by ruediger12** [comment]
Hello jcameron,

yes, there are two line:
`smtp	inet	n	-	y	-	-	smtpd -o smtpd_sasl_auth
_enable=yes`
`smtp      unix  -       -       y       -       -       smtp`

**Comment by jcameron** [comment]
Ok, I see the issue .. Virtualmin adds an entry for port 587 (native SSL) but doesn't do one for port 25 (STARTTLS mode). I will fix this in the next release.

**Comment by ruediger12** [comment]
Thanks!
