### ISSUE TITLE
LDAP Server module: ldap browser don't detect convenient port to use

### ISSUE THREAD

**Issue by dhia-eddine** [webmin/webmin#419]
when ldap server is set to use SSL so uses port 636,
- "Browse Database" throws `The LDAP browser cannot be used : Failed to connect to LDAP server port 389`
  even that "LDAP server port" is set to "Detect automatically" in module configuration
- when,  in module configuration, "LDAP server port" is set to 636 , "Browse Database" throws `The LDAP browser cannot be used : Failed to bind to LDAP server 127.0.0.1 as cn=admin,dc=mydom,dc=com : Unexpected EOF`
- with "LDAP server port" left to "Detect automatically" and "Use encryption with LDAP server?" is set to "Yes" ldap browser connects successfully

**Comment by jcameron** [comment]
In automatic mode, Webmin tries to figure out the port and SSL mode by reading a config file like /etc/ldap.conf or /etc/nslcd.conf. Do those exist on your system?

**Comment by dhia-eddine** [comment]
it's Ubuntu 14.04.5 server and none of both files is there
no package contains those path files in repository
found `libldap-2.4-2: /etc/ldap/ldap.conf` but no port or server config is there
no ldap client config setup, only openldap server to authenticate to
it's "LDAP Server" webmin module, shouldn't it be looking at server config? it's stored at `/etc/default/slapd`
`SLAPD_SERVICES="ldaps:/// ldap:/// ldapi:///"`

**Comment by jcameron** [comment]
Ok .. in that case, the behavior is about what I'd expect. Without a local LDAP client config file, you need to configure the LDAP Client module to use the right port and SSL mode.
