### ISSUE TITLE
Debian/Ubuntu build's §/etc/init.d/webmin§ is faulty: fails to start Webmin

### ISSUE THREAD

**Issue by rautamiekka** [webmin/webmin#421]
Tested on Ubuntu 16.04 LTS x64, that script always fails to start Webmin, but running the referenced `/etc/webmin/start` works just fine. I fixed the script myself:
```shell
#!/bin/sh
### BEGIN INIT INFO
# Provides: webmin
# Required-Start: $network $syslog
# Required-Stop: $network
# Default-Start: 2 3 5
# Default-Stop:
# Description: Webmin
### END INIT INFO

case "$1" in
    'start')
        . /etc/webmin/start &
        RETVAL=$?
        ;;
    'stop')
        . /etc/webmin/stop &
        RETVAL=$?
        ;;
    'restart')
        $0 stop ; $0 start
        RETVAL=$?
        ;;
    *)
        echo "Usage: $0 { start | stop }"
        RETVAL=1
        ;;
esac

exit $RETVAL
```

Also, I don't think it's necessary to have the `RETVAL=$?` in the restart section.

**Comment by jcameron** [comment]
Is that the unmodified init script that you get after installing Webmin from the package from www.webmin.com ? Because it looks a bit different from what our test systems have after doing a regular install.

**Comment by rautamiekka** [comment]
Yep, it's that. I have `deb http://download.webmin.com/download/repository sarge contrib` in `/etc/apt/sources.list`.

The script in OP is the fixed one; added `. ` to the start of the lines `/etc/webmin/*` and ` &` to the end of them, and added indentation.

**Comment by jcameron** [comment]
Ok .. so with the original script, did it actually fail to start Webmin? Or did it just report that it had failed?

**Comment by rautamiekka** [comment]
Doesn't start. Running `/etc/webmin/start` does start it.

**Comment by jcameron** [comment]
I assume you ran `/etc/init.d/webmin start` ?

**Comment by rautamiekka** [comment]
And `sudo service webmin start`.

**Comment by jcameron** [comment]
What if you run `/etc/init.d/webmin stop` first?

**Comment by rautamiekka** [comment]
That's the weird part: it works just fine.

**Comment by jcameron** [comment]
Ok, I know what causes this now - the next Webmin release should fix this.
