### ISSUE TITLE
LVM with thinpool breakes webmin

### ISSUE THREAD

**Issue by Enrica-r** [webmin/webmin#422]
LVM offers a thin pool layer between volume group and logical volumes. Thin pool will be used more and more (eg. DRBD or Proxmox VE) because it offers oversizing lvs.

Webmin can't show the thin pool layer but it shows the the lvs nevertheless. This should be solved over time no issue.

But I found a critical situation:
I have two physical volumes and two volume groups (vg1 = 3TB and vg2 = 2TB). On vg1 I created a thinpool layer and three lvs via cli. Webmin shows the vg and all three lvs. Then I created on vg2 (without thinpool) one lv (say lv1) with 50GB. Webmin shows a size of 3TB!! even if "lvs" shows 50GB.

Then I create a file system with webmin on vg2/lv1 and webmin shows warining that vg1/lv1-lv3 have files systems already! Webmin tries to create file systems on not selected local volumes!!

Then I tried to remove vg2/lv1. Webmin says "file system in use" even if lv1 isn't mounted. I recognize that webmin is checking the other lvs also!

Conclusion:
An LVM with thin pool breakes webmin on volume groups without thin pool also. I propose two steps:
1. bugfix webmin so that it isn't confused by thin pool.
2. enhance webmin so that thin pools are visible and so that thin pools can be managed also. This step could be done later.

BTW: The presentation of LVM isn't very clearly arranged. I personally would prefer a tree view or list of vg - (thinpool) - lv. A first step is done on page of physical volume. There is a list of all connected logical volumes.

**Comment by jcameron** [comment]
Thanks for raising this - is Thinpool a core part of LVM now, or something built on top of it?

Also, which Linux distribution and version are you running there?

**Comment by Enrica-r** [comment]
I use Debian 8.5 at the moment. Thin pool has been introduced definitively since Debian Jessie. In Wheezy it was buggy.

Almost all distribution works with thin provisioning in the kernel. Thin provisioning does define the size of a lv virtually. The space is allocated by using it. Therefore overprovisioning is possible.
Examples: 
Red Hat since 6.5
Fedora since 21
Unbuntu since 12.04 LTS (lvm2 version 2.02.122 year 2012)

It seems that lvm2 thin provisoning is prepared for some time already but it wasn't common yet. In the meantime  it's used by some components like DRBD 9.0 and others.

You could find a lot of information in internet. One of the best description with screenshots you could see under http://www.tecmint.com/setup-thin-provisioning-volumes-in-lvm/

**Comment by jcameron** [comment]
Thank ... I'll look into adding support for thinpools in Webmin.

**Comment by luison** [comment]
Just following this issue. We have the same case with intensive use of thinpools on host machines as many virtualization systems (we hse LXC/Proxmox) now recommend thinpool enabled LVM partition to create the containers drives. 
It would be great to see LVM module correctly recognising this pools. Thanks.

**Comment by jcameron** [comment]
Good news - the next release of Webmin (1.840) will have LVM thin pool support.
