### ISSUE TITLE
File Manager do not show all files inside folder ?

### ISSUE THREAD

**Issue by ochbob** [webmin/webmin#424]
Hi  everyone :)

I don't know what i've done, but since last night i can't see all my files inside my "telechargements" folder when i use Webmin File Manager...
I can see only folder and files inside this folder.
I have some archive .rar which i can't see.

But when i use ls command in the terminal, i can see everything...

Any idea ?

Thanks !

**Comment by qooob** [comment]
What theme do you use? What Webmin version? Can you post a screenshot?

**Comment by Real-Gecko** [comment]
[Install latest Filemin](https://github.com/Real-Gecko/filemin/wiki), it does not have such problems :D

**Comment by ochbob** [comment]
I use Webmin 1.801 with Authentic Theme  18.02. Exactly same when i do not have the issue.
Maybe i change something without realizing it ?

Here screenshot from File Manager:

http://img4.hostingpics.net/pics/387703Capture.jpg

In red you can see webmin did not show all files

**Comment by ochbob** [comment]
Find issue. 
It's character in one folder name which was not correctly encode.

I rename it in terminal, refresh filemin, and voilà ! All my files are correctly listed.

I upgrade to latest Filemin like Reak Gecko said, but i do not like open a new tab...
Any way to stay in webmin interface ? (like my upper screen)

Thx !

**Comment by qooob** [comment]
Alright, first of all update your Webmin to 1.810 and get latest Authentic Theme that fixes a lot of issues on File Manger.

Good luck.

**Comment by ochbob** [comment]
Done. After all update, everything is good.

Thx !

**Comment by qooob** [comment]
You're welcome!
