### ISSUE TITLE
Unable to log in as sudo user by default on CentOS

### ISSUE THREAD

**Issue by busyfritz** [webmin/webmin#425]
When installing webmin on centos 7 the option "Allow users who can run all commands via sudo to login as root" is not checked by default. This is because perl module "perl-IO-Pty-Easy" is not installed.

**To fix this you have to add the EPEL repo first:** (run all commands as root)
yum install epel-release

**And then install the module:**
yum install perl-IO-Pty-Easy

The webmin script needs to be updated to install this module when installing webmin.

**Comment by jcameron** [comment]
There isn't really any way to automatically install a package that isn't available in the distribution's core repository. RPM allows dependencies to be specified, but can't enable other repos at install time.

**Comment by busyfritz** [comment]
What is the best way to work around this behavior then?

**Comment by jcameron** [comment]
Install the perl module manually.

**Comment by busyfritz** [comment]
I have install the module and its working. I just wondered if there's any way to work around this issue in the install script or at least put it in the instructions.

**Comment by jcameron** [comment]
Unfortunately not that I can see - on Debian (where sudo mode is the default), Webmin has a dependency on `libio-pty-perl` which contains that Perl module.

**Comment by busyfritz** [comment]
Ok, might be good to put this in the instructions at least then.

**Comment by busyfritz** [comment]
This module should probably be put in here:

![image](https://cloud.githubusercontent.com/assets/16666495/18584538/5c6eac9a-7bdf-11e6-8352-74455731ff97.png)

**Comment by jcameron** [comment]
Wait ... doesn't the `perl-IO-Tty` package contain this module already?

**Comment by busyfritz** [comment]
hmm it does say that...
Now I think I know what happened. I was following this guide: [spiceworks](https://community.spiceworks.com/how_to/128459-how-to-install-squid-proxy-on-centos-7-with-webmin-apache-and-sarg)

I'll have respond on that thread
