### ISSUE TITLE
Can't login/connect to Webmin after IP changed

### ISSUE THREAD

**Issue by mat-l** [webmin/webmin#433]
Hello together,

I am running Webmin on a Odroid-X which is similar to a Raspberry Pi. The other day, the internet provider changed after severals weeks the IP address of my router. Now, after changing the IP in my domain settings, I am still not able to login or even connect to my server using ssh.

While using ssh it just says "Connection refused". Visiting the site 192.168.178.20:10000 for the webmin interface always says "Error: Secure Connection Failed". The same issue if I use the external IP of my router to access from external.
Is it possible that Webmin saved a fixed IP on which it is listening? Is there a special config folder created my Webmin, where I can change something? Cause the only way I can right now do some changes is to put the SD card of my Odroid-X into the PC and configure manually something.

Any ideas on this issue? Thanks in advance.
Regards matl

**Comment by jcameron** [comment]
No, webmin won't limit itself to a specific IP unless you explicitly configured that. 

Make sure  that it's actually running on your system though, by SSHing in as `root` and running `/etc/webmin/stop ; /etc/webmin/start`

**Comment by mat-l** [comment]
@jcameron No I didn't limit something manually.
Right now I cannot login using SSH because the connection is refused :(

**Comment by jcameron** [comment]
Sounds like you have a larger problem then, not just limited to Webmin.

**Comment by mat-l** [comment]
Seems that it is a problem by python which makes the board to die. :(
