### ISSUE TITLE
Webmin crashes frequently

### ISSUE THREAD

**Issue by Real-Gecko** [webmin/webmin#435]
I have Debian 8 and Webmin 1.820. Since version 1.780 I noticed that Webmin crashes frequently.
`service webmin status` gives
```
● webmin.service - LSB: Webmin
   Loaded: loaded (/etc/init.d/webmin)
   Active: active (exited) since Tue 2016-10-04 21:01:33 +06; 15h ago
  Process: 16372 ExecStop=/etc/init.d/webmin stop (code=exited, status=1/FAILURE)
  Process: 16406 ExecStart=/etc/init.d/webmin start (code=exited, status=0/SUCCESS)
```
I crawled Webmin logs, but no error messages regarding reasons of failure were found.
With the latest update things are even worse, restarting service helps only for ten minutes or so.
Where can I see reasons of failure?

**Comment by jcameron** [comment]
Does anything get logged to `/var/log/messages` or `dmesg` indicating why the crash happened? Perhaps the kernel killed the process due to lack of RAM?

**Comment by Real-Gecko** [comment]
Yep, it was memory issue. Mysql started crashing too, but it displayed errors in `service mysql status` saying something like this `InnoDB: Cannot allocate memory`. I've increased swap file size and everything looks good now.
However no errors regarding Webmin crashes in `/var/log/messages` or `/var/log/dmesg` or any Webmin log.

**Comment by jcameron** [comment]
Yeah, Webmin just gets killed by the kernel when the system is low on memory - so it doesn't get a chance to log anything.
