### ISSUE TITLE
MAGEIA Config

### ISSUE THREAD

**Issue by crishack** [webmin/webmin#44]
Congratulations for the work you do with webmin.

Mageia is the fork of Mandriva, and the configurations of webmin don't run on mageia, please can you add mageia to the suported SO. the paths should be the same of mandriva.

thanks

**Comment by shoulders** [comment]
this should closed because
- 2012
- the user never got back to you

**Comment by jcameron** [comment]
Yeah I don't think we're going to add support for Mageia
