### ISSUE TITLE
ClamAV error Ubuntu 16.04 xenial

### ISSUE THREAD

**Issue by chris001** [webmin/webmin#441]
`System Settings > Re-check Configuration`:

```
The ClamAV program clamscan does not appear to be working properly :

LibClamAV Error: cli_loaddbdir(): No supported database files found in /var/lib/clamav
ERROR: Can't open file or directory

----------- SCAN SUMMARY -----------
Known viruses: 0
Engine version: 0.99.2
Scanned directories: 0
Scanned files: 0
Infected files: 0
Data scanned: 0.00 MB
Data read: 0.00 MB (ratio 0.00:1)
Time: 0.003 sec (0 m 0 s)

. Either change the program on the spam and virus scanners page, or disable this feature.
.. your system is not ready for use by Virtualmin.
```

System specs: 
Ubuntu 16.04 Xenial i686, 
256MB RAM (61 MB in use), 
250GB disk (99%  free space).

It's been stuck on that error for days.

**Comment by jcameron** [comment]
If you run the `freshclam` command, what does it output?

**Comment by chris001** [comment]
```
~# freshclam
ERROR: /var/log/clamav/freshclam.log is locked by another process
ERROR: Problem with internal logger (UpdateLogFile = /var/log/clamav/freshclam.log).
```

**Comment by jcameron** [comment]
Maybe try checking for any other `freshclam` process that is running, and killing it?

**Comment by chris001** [comment]
OK this process was running
```
clamav     296  0.0  0.1  74652   440 ?        Ss   Oct16   2:53 /usr/bin/freshclam -d --foreground=true
```
Does webmin configure the system so the user `clamav` runs that process?

Once killed, running `freshclam` from the command line, as root, ran, then failed with this error.
```
~# kill 296
~# freshclam
ClamAV update process started at Tue Oct 18 13:41:27 2016
nonblock_connect: connect timing out (30 secs)
Can't connect to port 80 of host db.local.clamav.net (IP: 209.198.147.20)
Trying host db.local.clamav.net (69.12.162.28)...
Downloading main.cvd [100%]
ERROR: Database load killed by signal 9
ERROR: Failed to load new database
```

**Comment by jcameron** [comment]
That error "Database load killed by signal 9" looks like the real issue.

Is your system perhaps low on RAM?

**Comment by chris001** [comment]
Yes it's running with the webmin minimum required RAM 256MB (20 MB used, 120MB free, 125 MB buffer cache) and 128MB vswap (80 MB used, .

**Comment by jcameron** [comment]
Try going to 512 MB or even 1 GB if you can. Freshclam uses a surprisingly large amount of RAM :-(

**Comment by chris001** [comment]
It works on 512.  Why does freshclam use so much ram when all it's doing is downloading virus defs?!

**Comment by jcameron** [comment]
That is a very good question .... for the freshclam developers

**Comment by chris001** [comment]
@jcameron   I've asked them why it bombs out, probably due to the high amount of ram required, in this issue https://github.com/vrtadmin/clamav-faq/issues/41

**Comment by sjabbott78** [comment]
I know this is an older post but I had the same issue with freshclam. I resized my server to have at least 1GB of ram and it works now.

**Comment by iliarostovtsev** [comment]
I had to go with 2GB of RAM on **CentOS 8** to make the command run successfully. Probably _1.5GB_ would also work but _DigitalOcean_ didn't have such option.

**Comment by chris001** [comment]
Suggestion: add a note to the release notes, something along the lines of: 
"For users who want to use `clamav` antivirus, and update the virus definitions data with the `freshclam` command, and most of you will, for antivirus updates to work without error/fail, you'll require a minimum system RAM of between `512MB` (`Ubuntu 16.04`) and `2GB` (`CentOS 8`), depending on `linux` distribution and which other services you have enabled. Lesson, `ClamAV` uses a lot of `RAM`."

**Comment by jcameron** [comment]
I will increase the recommended RAM in the config check when ClamAV is in use.
