### ISSUE TITLE
Can't connect through browser

### ISSUE THREAD

**Issue by stevland** [webmin/webmin#445]
I can't open the web interface using Chrome/ FF / Edge:

   ERR_CONNECTION_TIMED_OUT

webmin is running on my CentOS 6.8 VM with no errors:

```
[21/Oct/2016:17:31:30 -0700] miniserv.pl started
[21/Oct/2016:17:31:30 -0700] Using MD5 module Digest::MD5
[21/Oct/2016:17:31:30 -0700] PAM authentication enabled
```

```
# ps aux | grep miniserv.pl
root      2201  0.0  0.8  73532 20764 ?        Ss   17:40   0:00 /usr/bin/perl /usr/libexec/webmin/miniserv.pl /etc/webmin/miniserv.conf
root      2984  0.0  0.0   6440   716 pts/0    S+   17:50   0:00 grep miniserv.pl
```

I have updated everything I can think of. 

I have verified that nothing else is using the port:

```
# netstat -tanp | grep :10000
tcp        0      0 0.0.0.0:10000               0.0.0.0:*                   LISTEN      2201/perl
# ps aux | grep 2201
root      2201  0.0  0.8  73532 20756 ?        Ss   17:40   0:00 /usr/bin/perl /usr/libexec/webmin/miniserv.pl /etc/webmin/miniserv.conf
```

I've made sure that I'm up-to-date:

```
# yum update webmin
Loaded plugins: fastestmirror
Setting up Update Process
Loading mirror speeds from cached hostfile
 * base: centos.s.uw.edu
 * epel: mirror.prgmr.com
 * extras: centos.s.uw.edu
 * updates: centos.s.uw.edu
 * webtatic: us-east.repo.webtatic.com
No Packages marked for Update
```

There is nothing relevant in any of these log files:

Apache access
Apache SSL access
Apache error
nginx access
nginx SSL access
nginx error

I have added my IP to fail2ban's whitelist. And for good measure I've added my IP to CSF.

Out of ideas. Anyone?

**Comment by stevland** [comment]
I forgot to mention above that I have rebooted the server about a thousand times in between troubleshooting attempts.

I have subsequently tried the following, to no avail:

I stopped nginx... probably not related but I'm getting desperate.

I've tried connecting using the server's IP address:

`https://<myip>:10000/`

I have verified that port 10000 is open:

```
# netstat -ntlp | grep LISTEN
tcp   0   0 0.0.0.0:10000  0.0.0.0:*  LISTEN  2201/perl
```

Meh.

**Comment by stevland** [comment]
Yikes.

I **stopped iptables** and now I can log into webmin.

Thanks, everyone!  :)

**Comment by chris001** [comment]
@stevland  You should get `csf` it makes managing `iptables` allowed ports super easy.
