### ISSUE TITLE
NTP-Server configuration ignored

### ISSUE THREAD

**Issue by DavidBruchmann** [webmin/webmin#447]
The page "hardware -> system time" seems ignoring the ntp-configuration or just missing some points.
A common configuration is this (and it seems working):

pool 0.ubuntu.pool.ntp.org iburst
pool 1.ubuntu.pool.ntp.org iburst
pool 2.ubuntu.pool.ntp.org iburst
pool 3.ubuntu.pool.ntp.org iburst

I've the impression it's just scanned for the keyword "server" as the input-field "Timeserver hostnames or addresses" is empty.
Furthermore it's not clear how to seperate lines in that single-line field (semicolon, comma, ...)

**Comment by jcameron** [comment]
This is a known bug in the current release - the options entered in the NTP servers form don't get saved properly. It will be fixed in the next release though.

**Comment by DavidBruchmann** [comment]
Ok thank's, nice that it will be fixed.

**Comment by Triplethread** [comment]
Does not work on my installation too, looked @help.ubuntu
[Ubuntu](https://help.ubuntu.com/lts/serverguide/NTP.html):
Starting with Ubuntu 16.04 **timedatectl / timesyncd** (which are part of systemd) replace most of ntpdate / ntp 
………
 If **ntpdate / ntp** are installed timedatectl steps back to let you keep your old setup. That shall ensure that no two time syncing services are fighting and also to retain any kind of old behaviour/config that you had through an upgrade. But it also implies that on an upgrade from a former release ntp/ntpdate might still be installed and therefore renders the new systemd based services disabled.
So I installed ntp & ntpdate.
`NTP-Zeitsynchronisation fehlgeschlagen : 13 Mar 00:37:25 ntpdate[11699]: Can't adjust the time of day: Operation not permitted `

ntpdate is considered deprecated in favour of timedatectl and thereby no more installed by default.

**Comment by jcameron** [comment]
@Triplethread - are you running Webmin on a VM? On some VM types, the guest OS cannot change the system time (ie. OpenVZ)

**Comment by Triplethread** [comment]
Yep, running in a LXC-Container - thank you for answering. The thing is that I wanted to query the ntp time server over an ip, that should work, right?

**Comment by jcameron** [comment]
Yes, querying NTP should work - but you won't be able to apply the time change

**Comment by Triplethread** [comment]
So sad…
Thank u for replying.
