### ISSUE TITLE
Missing button for restarting apache-server

### ISSUE THREAD

**Issue by DavidBruchmann** [webmin/webmin#448]
Missing button for restarting apache-server would be desirable perhaps.

**Comment by jcameron** [comment]
There are several buttons for this in Webmin - which page did you expect to see the button on?

**Comment by DavidBruchmann** [comment]
On the page "Servers -> Apache Web Server", I never found any buttons somewhere else but that location would be most logical in my opinion.

**Comment by DavidBruchmann** [comment]
On the page "Servers -> Apache Web Server", I never found any buttons
somewhere else but that location would be most logical in my opinion.

**Comment by jcameron** [comment]
There's a button or link on the top-right corner of the Apache module for restarting the server.

**Comment by DavidBruchmann** [comment]
Ok, thanks.
Seems I've to remove the tomatoes from my eyes :D
