### ISSUE TITLE
Postgres 9.6 issues

### ISSUE THREAD

**Issue by bilekt3** [webmin/webmin#449]
New version of PostgreSQL 9.6 has different set of OPTIONS for Alter USER and this causing user creation. Please refer PostgreSQL manual

**Comment by jcameron** [comment]
Thanks for the info. Which Linux distribution are you running there, and does it come with PostgreSQL 9.6 by default?

**Comment by bilekt3** [comment]
I do not use official repository. I use Ubuntu with 16.04 with official PostgreSQL repository.

I fixed it in three places and works fine for me. Only difference is that new 9.6 has no NOCREATEUSER.

**Comment by jcameron** [comment]
Ok, this will be fixed in the next release of Webmin.
