### ISSUE TITLE
option to add php.ini-files

### ISSUE THREAD

**Issue by DavidBruchmann** [webmin/webmin#450]
Currently there is an option to change php.ini files by search, but it's not possible to add these files to the list on "Others -> PHP Configuration". This is especially then desirable if several PHP-Versions run on a system but also for cgi, cli, fpm, apache2, etc.

**Comment by singhdd93** [comment]
+1
Now, its python's time. Webmin/Virtualmin needs configurations options for python now

**Comment by jcameron** [comment]
Are you saying you want a way to have multple php.ini files appear on the "PHP Confguration" page for editing?

**Comment by DavidBruchmann** [comment]
Yes, that's right.
My current matter is I run Nginx on Ubuntu and two PHP versions (for different Versions of TYPO3).
So having the option to add a choice of config-files is quite important if I decide to use webmin for configuration. Could be even more required if there are still users with own accounts running there own php-instances and want to adjust some things.
I think adding the option itself probably won't be so hard as an individual choice exists already anyway, it's just not saved yet.

**Comment by jcameron** [comment]
Ok, in that case this feature already exists - in the PHP Configuration module, you can click on the Module Config link (or the gear icon in the new theme), and on that page is a text box for entering additional php.ini files to edit.

**Comment by DavidBruchmann** [comment]
Yes right, but there is an option missing (if I don't mistake) to add that file to the list that is displayed next time(s) when you first call the php-modul.
So my desire is just about usability, the functionality is already completely existent.
As far as I see the list is generated dynamically and it had to be merged or replaced then with some static list that had to be saved somewhere.
If you've several php-files in the moment you've to remember all the locations (and type), if they are added to the list, you can once adjust all the paths and afterwards you see it all in the list.

**Comment by DavidBruchmann** [comment]
OK, sorry this issue can be closed.
I remarked the module configuration now where the files can be added, that's exactly what I desired.

**Comment by DavidBruchmann** [comment]
Yes right, but there is an option missing (if I don't mistake) to add that
file to the list that is displayed next time(s) when you first call the
php-modul.
So my desire is just about usability, the functionality is already
completely existent.
As far as I see the list is generated dynamically and it had to be merged
or replaced then with some static list that had to be saved somewhere.
If you've several php-files in the moment you've to remember all the
locations (and type), if they are added to the list, you can once adjust
all the paths and afterwards you see it all in the list.
