### ISSUE TITLE
Configuration for HTTP-Tunnel

### ISSUE THREAD

**Issue by DavidBruchmann** [webmin/webmin#452]
Would be nice having the option to increase timeout and perhaps memory for the tunnel only.

**Comment by jcameron** [comment]
Memory? The tunnel should hardly be using any RAM at all ... it just streams data through.

**Comment by DavidBruchmann** [comment]
ok, perhaps I'm mistaking here.
The issue I remarked is that streaming videos by tunnel is not possible but desired due to national censorship.
And no, it's not about anything reprehensible ;-)

**Comment by DavidBruchmann** [comment]
ok, perhaps I'm mistaking here.
The issue I remarked is that streaming videos by tunnel is not possible but
desired due to national censorship.
And no, it's not about anything reprehensible ;-)

**Comment by chris001** [comment]
@DavidBruchmann   Do yoy mean `stunnel`?  Or `apache proxy`?

**Comment by DavidBruchmann** [comment]
@chris001  Neither nor (if modules never link to each other).
It's the module tunnel with the label "HTTP Tunnel".
If there is a module more appropriate to my desire would be fine too though ...

**Comment by chris001** [comment]
For watching video while you're inside a country which unfairly blocks video from other regions of the world?  Are you renting a decent strong server in the country such US, where it is OK to stream the video?  For this I'd recommend you to install Artica Proxy on the server in the US..  Then you can stream thru your Artica server. Obviously you should activate full ECDHE PFS TLSv1.2 encryption so the country's unfair censorship cannot detect your stream as a video stream.

**Comment by DavidBruchmann** [comment]
Yes I've encryption anyway already.
Concerning Censorship it's more or less done randomly by just blocking vimeo completely and other sites more targeted in Indonesia. Target sites are primary nude-pages++ but also some proxies.
Our VPS can tunnel Vimeo even it's located in Indonesia itself but somehow it's not enough to stream any videos.
Technically I know that a VPS might not be the best base to realize video streaming but it would be a nice-to-have and not a real requirement. Nevertheless it might be interesting what's really required to get it running and where are the bottlenecks.

**Comment by jcameron** [comment]
The HTTP tunnel module wasn't really designed to be used to stream video - I'd recommend using a proper VPN instead.

**Comment by DavidBruchmann** [comment]
Yeah ok, will close it for the moment as I've not the time too to dig deeper in it.

**Comment by jkrobbin** [comment]
another thing is it possible to increase the max simultaneous download request per file 
for example am tunneling through the tunnel and am downloading a file using internet download manaher but it turns out that there is no resume support for the file since max connection is 1

**Comment by chris001** [comment]
@DavidBruchmann 
Here's Artica open source proxy server for you to stream video from indonesia thru your debian 8 VPS server, hope it helps:
http://artica-proxy/how-to-install-artica-manually-on-debian-8-x/

**Comment by DavidBruchmann** [comment]
Thank's @chris001 , I will have a look at it.
My first impression is that it's quite dominant and it might be difficult to run still all the other things I'm using on the server. Have no experience with own proxies ...

btw the corrected link is http://artica-proxy.com/how-to-install-artica-manually-on-debian-8-x/

**Comment by chris001** [comment]
Thanks, link corrected.  Yes, artica takes over the entire server when it installs, but after it installs, you can still add features, such as mail, web, etc. However, since mail/spam virus filtering and web can be somewhat heavy tasks, if your vps is not high enough ram/cpu spec to handle all of these jobs, for best vpn/proxy performance, you can rent a vps just for artica, prices at this time are quite cheap.
