### ISSUE TITLE
Source access problem

### ISSUE THREAD

**Issue by prassaschr** [webmin/webmin#453]
Hi,
I edit the /etc/apt/sources.list in a Debian 8 system and try to apt-get update.

It is stucked to webmin repository.

Can you please check it?

**Comment by chris001** [comment]
Same issue.  The server http://software.virtualmin.com is down not responding and times out.

**Comment by jcameron** [comment]
Server was down due to a hardware issue, but it's back up now.

**Comment by prassaschr** [comment]
Still got the problem... trying to install webmin but repo is probably down.

**Comment by jcameron** [comment]
Try again now.
