### ISSUE TITLE
Virtualmin bandwidth counter excluded the http status 206 ?

### ISSUE THREAD

**Issue by omidkosari** [webmin/webmin#459]
Hi,

In the virtualmin , the script that counts each domain bandwidth usage has excluded the http status code 206 . AFAIK the 206 related to partial connections and it should be counted as user bandwidth quota .

Please look at following files 
/usr/share/webmin/virtualmin-nginx/virtual_feature.pl

```
# feature_bandwidth(&domain, start, &bw-hash)
# Searches through log files for records after some date, and updates the
# day counters in the given hash
sub feature_bandwidth
{
my ($d, $start, $bwinfo) = @_;
my @logs = ( &get_nginx_log($d, 0) );
return if ($d->{'alias'} || $d->{'subdom'}); # never accounted separately
my $max_ltime = $start;
foreach my $l (&unique(@logs)) {
	foreach my $f (&virtual_server::all_log_files($l, $max_ltime)) {
		local $_;
		if ($f =~ /\.gz$/i) {
			open(LOG, "gunzip -c ".quotemeta($f)." |");
			}
		elsif ($f =~ /\.Z$/i) {
			open(LOG, "uncompress -c ".quotemeta($f)." |");
			}
		else {
			open(LOG, $f);
			}
		while(<LOG>) {
			if (/^(\S+)\s+(\S+)\s+(\S+)\s+\[(\d+)\/(\S+)\/(\d+):(\d+):(\d+):(\d+)\s+(\S+)\]\s+"([^"]*)"\s+(\S+)\s+(\S+)/ && $12 ne "206") {
				# Valid-looking log line .. work out the time
				my $ltime = timelocal($9, $8, $7, $4, $virtual_server::apache_mmap{lc($5)}, $6-1900);
				if ($ltime > $start) {
					my $day = int($ltime / (24*60*60));
					$bwinfo->{"web_".$day} += $13;
					}
				$max_ltime = $ltime if ($ltime > $max_ltime);
				}
			}
		close(LOG);
		}
	}
return $max_ltime;
}
```

/usr/share/webmin/virtual-server/feature-web.pl

```
# bandwidth_web(&domain, start, &bw-hash)
# Searches through log files for records after some date, and updates the
# day counters in the given hash
sub bandwidth_web
{
local @logs = ( &get_apache_log($_[0]->{'dom'}, $_[0]->{'web_port'}),
		&get_apache_log($_[0]->{'dom'}, $_[0]->{'web_sslport'}) );
return if ($_[0]->{'alias'} || $_[0]->{'subdom'}); # never accounted separately
local $l;
local $max_ltime = $_[1];
foreach $l (&unique(@logs)) {
	local $f;
	foreach $f (&all_log_files($l, $max_ltime)) {
		local $_;
		if ($f =~ /\.gz$/i) {
			open(LOG, "gunzip -c ".quotemeta($f)." |");
			}
		elsif ($f =~ /\.Z$/i) {
			open(LOG, "uncompress -c ".quotemeta($f)." |");
			}
		else {
			open(LOG, $f);
			}
		while(<LOG>) {
			if (/^(\S+)\s+(\S+)\s+(\S+)\s+\[(\d+)\/(\S+)\/(\d+):(\d+):(\d+):(\d+)\s+(\S+)\]\s+"([^"]*)"\s+(\S+)\s+(\S+)/ && $12 ne "206") {
				# Valid-looking log line .. work out the time
				local $ltime = timelocal($9, $8, $7, $4, $apache_mmap{lc($5)}, $6-1900);
				if ($ltime > $_[1]) {
					local $day = int($ltime / (24*60*60));
					$_[2]->{"web_".$day} += $13;
					}
				$max_ltime = $ltime if ($ltime > $max_ltime);
				}
			}
		close(LOG);
		}
	}
return $max_ltime;
}
```

I think this is a mistake and the 206 status should be counted like 200 status code . For example if you download a file normally with your browser it logs status 200 but if you download same file with Internet Download Manager(IDM) , it will split the file in several parts/connections to boost the download and in this case you will see status code 206 .

I can provide a lot of other samples .

I tried to edit the file in repository but could not find them .
Please clarify if i am wrong .
Thanks

**Comment by jcameron** [comment]
The reason I did this was that the webserver would log a 206 for each segment, and then a 200 for the entire size of the file - so counting 206's would lead to double-counting. 

Can you check if that's the case on your system?

**Comment by pendaresh** [comment]
my server : Ubuntu+Nginx+Virtualmin
I have download a File with Size of  667MB
This is my log after download the file  
`
192.168.250.1 - - [17/Nov/2016:10:46:21 +0330] "GET /ubuntu-16.04.1-server-amd64.iso HTTP/1.1" 200 91194247 "http://domain.com/" "Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko"
192.168.250.1 - - [17/Nov/2016:10:46:22 +0330] "GET /ubuntu-16.04.1-server-amd64.iso HTTP/1.1" 206 87398824 "http://domain.com/" "Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko"
192.168.250.1 - - [17/Nov/2016:10:46:22 +0330] "GET /ubuntu-16.04.1-server-amd64.iso HTTP/1.1" 206 23530172 "http://domain.com/" "Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko"
192.168.250.1 - - [17/Nov/2016:10:46:23 +0330] "GET /ubuntu-16.04.1-server-amd64.iso HTTP/1.1" 206 90347404 "http://domain.com/" "Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko"
192.168.250.1 - - [17/Nov/2016:10:46:23 +0330] "GET /ubuntu-16.04.1-server-amd64.iso HTTP/1.1" 206 14243445 "http://domain.com/" "Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko"
192.168.250.1 - - [17/Nov/2016:10:46:23 +0330] "GET /ubuntu-16.04.1-server-amd64.iso HTTP/1.1" 206 6940512 "http://domain.com/" "Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko"
192.168.250.1 - - [17/Nov/2016:10:46:23 +0330] "GET /ubuntu-16.04.1-server-amd64.iso HTTP/1.1" 206 5422148 "http://domain.com/" "Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko"
192.168.250.1 - - [17/Nov/2016:10:46:24 +0330] "GET /ubuntu-16.04.1-server-amd64.iso HTTP/1.1" 206 11993441 "http://domain.com/" "Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko"
192.168.250.1 - - [17/Nov/2016:10:46:24 +0330] "GET /ubuntu-16.04.1-server-amd64.iso HTTP/1.1" 206 2553784 "http://domain.com/" "Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko"
192.168.250.1 - - [17/Nov/2016:10:46:24 +0330] "GET /ubuntu-16.04.1-server-amd64.iso HTTP/1.1" 206 71320685 "http://domain.com/" "Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko"
192.168.250.1 - - [17/Nov/2016:10:46:24 +0330] "GET /ubuntu-16.04.1-server-amd64.iso HTTP/1.1" 206 1041512 "http://domain.com/" "Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko"
192.168.250.1 - - [17/Nov/2016:10:46:24 +0330] "GET /ubuntu-16.04.1-server-amd64.iso HTTP/1.1" 206 89629084 "http://domain.com/" "Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko"
192.168.250.1 - - [17/Nov/2016:10:46:24 +0330] "GET /ubuntu-16.04.1-server-amd64.iso HTTP/1.1" 206 1166179 "http://domain.com/" "Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko"
192.168.250.1 - - [17/Nov/2016:10:46:24 +0330] "GET /ubuntu-16.04.1-server-amd64.iso HTTP/1.1" 206 59500526 "http://domain.com/" "Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko"
192.168.250.1 - - [17/Nov/2016:10:46:24 +0330] "GET /ubuntu-16.04.1-server-amd64.iso HTTP/1.1" 206 459084 "http://domain.com/" "Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko"
192.168.250.1 - - [17/Nov/2016:10:46:24 +0330] "GET /ubuntu-16.04.1-server-amd64.iso HTTP/1.1" 206 929981 "http://domain.com/" "Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko"
192.168.250.1 - - [17/Nov/2016:10:46:24 +0330] "GET /ubuntu-16.04.1-server-amd64.iso HTTP/1.1" 206 76459885 "http://domain.com/" "Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko"
192.168.250.1 - - [17/Nov/2016:10:46:24 +0330] "GET /ubuntu-16.04.1-server-amd64.iso HTTP/1.1" 206 217795 "http://domain.com/" "Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko"
192.168.250.1 - - [17/Nov/2016:10:46:24 +0330] "GET /ubuntu-16.04.1-server-amd64.iso HTTP/1.1" 206 114619 "http://domain.com/" "Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko"
192.168.250.1 - - [17/Nov/2016:10:46:24 +0330] "GET /ubuntu-16.04.1-server-amd64.iso HTTP/1.1" 206 88174924 "http://domain.com/" "Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko"

`

**Comment by omidkosari** [comment]
As my colleague commented, there is no 200 code . At least Nginx behaves like this .

**Comment by omidkosari** [comment]
After more investigation i've found that there will be one status 200 code . But it is one of the segments and it is not size of the whole file . I am pretty sure that the 206 MUST be counted . Right now we have edited those perl files and everything works fine but i hate of hacking every time and after each update of virtualmin .

apache access.log
```
192.168.250.1 - - [17/Nov/2016:12:49:12 +0330] "GET /sql.zip HTTP/1.1" 206 589289 "http://domain.com/" "Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko"
192.168.250.1 - - [17/Nov/2016:12:49:12 +0330] "GET /sql.zip HTTP/1.1" 206 665040 "http://domain.com/" "Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko"
192.168.250.1 - - [17/Nov/2016:12:49:12 +0330] "GET /sql.zip HTTP/1.1" 206 596865 "http://domain.com/" "Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko"
192.168.250.1 - - [17/Nov/2016:12:49:12 +0330] "GET /sql.zip HTTP/1.1" 206 685440 "http://domain.com/" "Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko"
192.168.250.1 - - [17/Nov/2016:12:49:12 +0330] "GET /sql.zip HTTP/1.1" 200 733040 "http://domain.com/" "Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko"
192.168.250.1 - - [17/Nov/2016:12:49:12 +0330] "GET /sql.zip HTTP/1.1" 206 650080 "http://domain.com/" "Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko"
192.168.250.1 - - [17/Nov/2016:12:49:14 +0330] "GET /sql.zip HTTP/1.1" 206 172720 "http://domain.com/" "Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko"
192.168.250.1 - - [17/Nov/2016:12:49:14 +0330] "GET /sql.zip HTTP/1.1" 206 146092 "http://domain.com/" "Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko"
192.168.250.1 - - [17/Nov/2016:12:49:14 +0330] "GET /sql.zip HTTP/1.1" 206 146092 "http://domain.com/" "Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko"
192.168.250.1 - - [17/Nov/2016:12:49:14 +0330] "GET /sql.zip HTTP/1.1" 206 220743 "http://domain.com/" "Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko"
192.168.250.1 - - [17/Nov/2016:12:49:12 +0330] "GET /sql.zip HTTP/1.1" 206 388960 "http://domain.com/" "Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko"
192.168.250.1 - - [17/Nov/2016:12:49:12 +0330] "GET /sql.zip HTTP/1.1" 206 191760 "http://domain.com/" "Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko"

```

nginx access.log
```
192.168.250.1 - - [17/Nov/2016:12:55:55 +0330] "GET /ubuntu-16.04.1-server-amd64.iso HTTP/1.1" 200 90913927 "http://domain.com/" "Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko"
192.168.250.1 - - [17/Nov/2016:12:55:55 +0330] "GET /ubuntu-16.04.1-server-amd64.iso HTTP/1.1" 206 87242814 "http://domain.com/" "Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko"
192.168.250.1 - - [17/Nov/2016:12:55:55 +0330] "GET /ubuntu-16.04.1-server-amd64.iso HTTP/1.1" 206 90399964 "http://domain.com/" "Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko"
192.168.250.1 - - [17/Nov/2016:12:55:56 +0330] "GET /ubuntu-16.04.1-server-amd64.iso HTTP/1.1" 206 90271484 "http://domain.com/" "Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko"
192.168.250.1 - - [17/Nov/2016:12:55:56 +0330] "GET /ubuntu-16.04.1-server-amd64.iso HTTP/1.1" 206 87403061 "http://domain.com/" "Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko"
192.168.250.1 - - [17/Nov/2016:12:55:56 +0330] "GET /ubuntu-16.04.1-server-amd64.iso HTTP/1.1" 206 90592684 "http://domain.com/" "Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko"
192.168.250.1 - - [17/Nov/2016:12:55:56 +0330] "GET /ubuntu-16.04.1-server-amd64.iso HTTP/1.1" 206 77102285 "http://domain.com/" "Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko"
192.168.250.1 - - [17/Nov/2016:12:55:56 +0330] "GET /ubuntu-16.04.1-server-amd64.iso HTTP/1.1" 206 18532458 "http://domain.com/" "Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko"
192.168.250.1 - - [17/Nov/2016:12:55:56 +0330] "GET /ubuntu-16.04.1-server-amd64.iso HTTP/1.1" 206 16550245 "http://domain.com/" "Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko"
192.168.250.1 - - [17/Nov/2016:12:55:57 +0330] "GET /ubuntu-16.04.1-server-amd64.iso HTTP/1.1" 206 14719405 "http://domain.com/" "Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko"
192.168.250.1 - - [17/Nov/2016:12:55:57 +0330] "GET /ubuntu-16.04.1-server-amd64.iso HTTP/1.1" 206 8725649 "http://domain.com/" "Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko"
192.168.250.1 - - [17/Nov/2016:12:55:57 +0330] "GET /ubuntu-16.04.1-server-amd64.iso HTTP/1.1" 206 4231847 "http://domain.com/" "Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko"
192.168.250.1 - - [17/Nov/2016:12:55:57 +0330] "GET /ubuntu-16.04.1-server-amd64.iso HTTP/1.1" 206 10351085 "http://domain.com/" "Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko"
192.168.250.1 - - [17/Nov/2016:12:55:57 +0330] "GET /ubuntu-16.04.1-server-amd64.iso HTTP/1.1" 206 2685696 "http://domain.com/" "Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko"
192.168.250.1 - - [17/Nov/2016:12:55:57 +0330] "GET /ubuntu-16.04.1-server-amd64.iso HTTP/1.1" 206 6788686 "http://domain.com/" "Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko"
192.168.250.1 - - [17/Nov/2016:12:55:57 +0330] "GET /ubuntu-16.04.1-server-amd64.iso HTTP/1.1" 206 1641288 "http://domain.com/" "Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko"
192.168.250.1 - - [17/Nov/2016:12:55:57 +0330] "GET /ubuntu-16.04.1-server-amd64.iso HTTP/1.1" 206 5118877 "http://domain.com/" "Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko"
192.168.250.1 - - [17/Nov/2016:12:55:57 +0330] "GET /ubuntu-16.04.1-server-amd64.iso HTTP/1.1" 206 1461838 "http://domain.com/" "Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko"
192.168.250.1 - - [17/Nov/2016:12:55:57 +0330] "GET /ubuntu-16.04.1-server-amd64.iso HTTP/1.1" 206 709209 "http://domain.com/" "Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko"
192.168.250.1 - - [17/Nov/2016:12:55:57 +0330] "GET /ubuntu-16.04.1-server-amd64.iso HTTP/1.1" 206 1325366 "http://domain.com/" "Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko"
192.168.250.1 - - [17/Nov/2016:12:55:57 +0330] "GET /ubuntu-16.04.1-server-amd64.iso HTTP/1.1" 206 271461 "http://domain.com/" "Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko"
192.168.250.1 - - [17/Nov/2016:12:55:57 +0330] "GET /ubuntu-16.04.1-server-amd64.iso HTTP/1.1" 206 3589057 "http://domain.com/" "Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko"
192.168.250.1 - - [17/Nov/2016:12:55:57 +0330] "GET /ubuntu-16.04.1-server-amd64.iso HTTP/1.1" 206 566415 "http://domain.com/" "Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko"
192.168.250.1 - - [17/Nov/2016:12:55:57 +0330] "GET /ubuntu-16.04.1-server-amd64.iso HTTP/1.1" 206 19286285 "http://domain.com/" "Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko"
192.168.250.1 - - [17/Nov/2016:12:55:57 +0330] "GET /ubuntu-16.04.1-server-amd64.iso HTTP/1.1" 206 202288 "http://domain.com/" "Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko"
192.168.250.1 - - [17/Nov/2016:12:55:57 +0330] "GET /ubuntu-16.04.1-server-amd64.iso HTTP/1.1" 206 442157 "http://domain.com/" "Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko"
192.168.250.1 - - [17/Nov/2016:12:55:57 +0330] "GET /ubuntu-16.04.1-server-amd64.iso HTTP/1.1" 206 112304 "http://domain.com/" "Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko"

```

**Comment by jcameron** [comment]
Are  you running Apache with Nginx in front of it there? Or did you get these logs from two completely separate servers?

**Comment by omidkosari** [comment]
The log are from two complete separate servers . Nginx logs are from Ubuntu-16.04 and apache logs are from CentOS 6.8 . I have tested to be sure that apache logs and nginx logs behaves same .

I wonder why nobody else did not complain before ?!

**Comment by jcameron** [comment]
I  think in the past, people did complain about the *old* behavior in which 206's were counted! But maybe Apache and Nginx changed the way they log these kinds of requests.

What are you using to do these downloads?

**Comment by omidkosari** [comment]
So i think it is better to webmin also use new behavior.

Actually i am trying to use virtualmin for static download sites . Something like CDN or download mirror. But it should not be problem just in my situation . As you know nowadays the 206 is very popular between applications . I can provide some statistics if you want . So incorrect calculation of that may result huge mistakes .

**Comment by jcameron** [comment]
Ok .. but so I can test this, what client program or browser were you using to download `ubuntu-16.04.1-server-amd64.iso` ?

**Comment by omidkosari** [comment]
As my colleague mentioned https://github.com/webmin/webmin/issues/459#issuecomment-261177201 it is Internet Download Manager 6.25 (IDM) .

Also i want to show another way . Lets assume we have a file with the name movie.mkv on the server . Then we open that url directly from VLC media player (Open Network Stream menu) . Then you will see just 206 status code .

```
192.168.250.1 - - [19/Nov/2016:11:15:51 +0330] "GET /movie.mkv HTTP/1.1" 206 271257 "-" "VLC/2.2.4 LibVLC/2.2.4"
192.168.250.1 - - [19/Nov/2016:11:15:51 +0330] "GET /movie.mkv HTTP/1.1" 206 31569 "-" "VLC/2.2.4 LibVLC/2.2.4"
192.168.250.1 - - [19/Nov/2016:11:15:51 +0330] "GET /movie.mkv HTTP/1.1" 206 142774 "-" "VLC/2.2.4 LibVLC/2.2.4"
192.168.250.1 - - [19/Nov/2016:11:15:51 +0330] "GET /movie.mkv HTTP/1.1" 206 337 "-" "VLC/2.2.4 LibVLC/2.2.4"
192.168.250.1 - - [19/Nov/2016:11:17:37 +0330] "GET /movie.mkv HTTP/1.1" 206 19753494 "-" "VLC/2.2.4 LibVLC/2.2.4"

```

**Comment by jcameron** [comment]
I did some tests, and it looks like in most cases Apache doesn't log both a 200 and 206. So I will count the 206 in future releases.

**Comment by omidkosari** [comment]
Thanks .
I am not sure but that code existed in 2 different files but you patched just one file . As mentioned in https://github.com/webmin/webmin/issues/459#issue-189735602 , the other file is
/usr/share/webmin/virtual-server/feature-web.pl

**Comment by jcameron** [comment]
Yes, I patched both file - however, you may not be able to see the commit for feature-web.pl , as its in a private repository.
