### ISSUE TITLE
Shell module history

### ISSUE THREAD

**Issue by qooob** [webmin/webmin#469]
Jamie, hi.

Could you change the way history is stored in shell module?

Now, when you run command that is already in history it doesn't get logged. I have made shell port on the new 18.30 and you could use arrows up and down to list through the history of commands that are derived from the server response. It would be good to keep all commands or at least push the latest command to the top of the list.

**Comment by jcameron** [comment]
So, if you re-run a command it would be listed twice?

**Comment by qooob** [comment]
This is what happens in regular shell.

However, if you think it's redundant just putting the duped and latest command on the top and removing it from the list would be also ok.

Listing twice is better and produces very logical result.

Try entering the following commands and see what I mean:
```BASH
ls -lsa
ls -ls
ls -lsa
```

In the example above the latest command in history will be `ls -ls` when should be `ls -lsa`.

The history should either contain all of it or the latest command should be the one that was run last.

_Cloudmin_ module will also require a fix as the theme interacts with it as well and extracts history for each server individually.

**Comment by jcameron** [comment]
Ok, I'll change it so that the new command appears first in the history if it's a duplicate.
