### ISSUE TITLE
Show external ip address

### ISSUE THREAD

**Issue by victories** [webmin/webmin#473]
Can we print the external ip address under the ip address?
Ip addresses 172.16.3.3
External Ip Adresses 123.456.789.0

Thank you.

**Comment by jcameron** [comment]
How would Webmin reliably determine that though?

**Comment by victories** [comment]
If the external ip address is specified while creating the virtual server, can it show this ip address?

**Comment by jcameron** [comment]
Sure, for Virtualmin domains. 

Which specific page are you suggesting for this to appear on though?

**Comment by victories** [comment]
Edit virtual server \ Virtual server details section, under the IP addresses would be fine.
Thank you.

**Comment by jcameron** [comment]
The external IP should already show up on that page though.

**Comment by victories** [comment]
Please correct me if I am wrong. External ip addresses only show Server configuration > Change ip addresses, please take a look these screen shot
![screenshot_20161220-104609](https://cloud.githubusercontent.com/assets/1463038/21342186/be8e53b4-c6a1-11e6-9e72-b00bc79e8f72.png)


![screenshot_20161220-104237](https://cloud.githubusercontent.com/assets/1463038/21342099/20406094-c6a1-11e6-8a83-ecb05b74b6b7.png)
![screenshot_20161220-104209](https://cloud.githubusercontent.com/assets/1463038/21342102/2b90b516-c6a1-11e6-9385-02b31dee0ad5.png)

**Comment by jcameron** [comment]
Oh, I see what you mean now. This will be added in the next release of Virtualmin.
