### ISSUE TITLE
Copy SSL to webmin copies to usermin

### ISSUE THREAD

**Issue by DJSADERS** [webmin/webmin#483]
When i try to copy the SSL certificate to webmin it copies to usermin

**Comment by Zen4All** [comment]
I noticed the same, but suspect it is only the message that is wrong. Since Ssl is working after copying.

**Comment by jcameron** [comment]
No, it is copying wrong ... but this will be fixed in the next release.

The work-around is to SSH in and run `virtualmin install-service-cert --domain whatever.com --service webmin`
