### ISSUE TITLE
Package Updates: Server returns inconsistent table

### ISSUE THREAD

**Issue by qooob** [webmin/webmin#491]
Jamie, have a look. 

**Goto:**
`Webmin->System->Software Package Updates->Only new`

**Put in find packages matching:** 
`libjpeg` and hit search..

Webmin delivers inconsistent table, that has in rows, in header 5 `<th>` and in the body 4 `<td>`. 
It makes the _**dataTable**_ fail.

https://github.com/qooob/authentic-theme/issues/661#issuecomment-277458096

**Comment by jcameron** [comment]
Ok, this will be fixed in the next Webmin release.
