### ISSUE TITLE
Scheduled Cron Jobs: Edit manually

### ISSUE THREAD

**Issue by qooob** [webmin/webmin#492]
Jamie, hi!

It would be great to add a button for manually editing all cron jobs at once?

**Comment by jcameron** [comment]
Possible ... but not simple, as cron jobs can be spread across multiple files, so a manual editing option would need to combine and separate them somehow.

**Comment by qooob** [comment]
Yes, I expected that.

It wouldn't be possible to split them properly afterwards. Just make multiple buttons and I will process it in to a single drop down button, may be?

**Comment by jcameron** [comment]
I suppose I could add a page to allow manual editing, with a drop-down menu for selecting the file - like in other modules?

**Comment by qooob** [comment]
Oh, yeah, right! That would be just perfect!

**Comment by jcameron** [comment]
This has been implemented, for inclusion in the next release of Webmin.
