### ISSUE TITLE
Disk Quotas: Removing action link for devices without mountpoint

### ISSUE THREAD

**Issue by qooob** [webmin/webmin#493]
Jamie, hi.

What is the need of having action link (enable/disable) quotas in the column Action for some paths?

For example, running it on the console return the following error:

`quotaon: Mountpoint (or device) /var/spool/mail not found or has no quota enabled.`

The same, when you click the link for this filesystem it does nothing.

I think it would be better to either add class `hidden` on it or completely avoid printing it.

**Comment by jcameron** [comment]
That link should only appear for filesystems defined in /etc/fstab and which have quotas enabled in the fstab file. 

In your case, what type of filesystem is this (XFS, EXT4, or something else) ?

**Comment by qooob** [comment]
It's EXT4.

They are already on the left in the Filesystems column and **not marked** as blue (not links) but at the same time still have links in Action Column. It would worth rely on the same detection mechanism for Actions as you do for Filesystems, I suppose.

**Comment by jcameron** [comment]
Can you attach a screenshot?

**Comment by qooob** [comment]
Sure, here, Jamie:

![screenshot from 2017-02-15 22-19-32](https://cloud.githubusercontent.com/assets/4426533/22991332/f26198c4-f3cc-11e6-9173-f77bf5365655.png)

**Comment by jcameron** [comment]
That looks OK to me. For filesystems with quotas enabled, the link in the first column is for editing users and/or group quotas. For those without quotas active (but which could potentially use them), the link in the last column should setup the needed files and run `quotaon` to active quotas.

**Comment by qooob** [comment]
Those last 4 links are not eligible for being enabled/disabled. When you click on them in the last column, nothing happens, unlike upper ones, when you click it it gets enabled, disabled. As well, when you use console with `quotaon` command on them, you get this error:

```
quotaon: Mountpoint (or device) /var/spool/mail not found or has no quota enabled.
```

**Comment by jcameron** [comment]
That's odd - is `/var/spool/mail` actually a mount on your system? Also, can you post it's like from `/etc/fstab` ?

**Comment by qooob** [comment]
`cat /etc/fstab`

```
/dev/sda2	/		ext4	usrquota,grpquota	0	1
/dev/sda1	/boot	ext4	usrquota,grpquota	0	2
/dev/sda3	/tmp	ext4	usrquota,grpquota	0	2
/dev/sda5	swap	swap	defaults			0	0
```

After the boot, init script runs to mount LUKS encrypted device:

`/sbin/cryptsetup luksOpen /dev/disk/by-uuid/c0000a22-81a3-1ac-0600-0007d9e11f00 RAID-10`
`/bin/mount -t ext4 -o rw,usrquota,grpquota /dev/mapper/RAID-10 /mnt/raid_10`

Finally, **_mount bind_** is run. (this is probably what causing the issue):

`/bin/mount --bind /mnt/raid_10/var/spool/mail /var/spool/mail`

The initial system message is correct - it's not a mount device.

**Comment by jcameron** [comment]
Ok, I think that post-boot bind mount is confusing webmin. I suppose it should be possible to enable quotas on /mnt/raid_10 , but not on /var/spool/mail ?

I'll check in a fix for this.

**Comment by qooob** [comment]
No, Jamie. This fix is not going to work.

None of the output from `$_[0]`, `$_[1]`, `$_[2]` or `$_[3]` provide _bind_ in the string. Actually output from these arrays are identical whether  it was binded or not.

The best thing to do and to leave those binds but not to display false _Enable_ in action is to edit `quota/index.cgi` on line 90 and 

Replace:

`push(@cols, &ui_link("activate.cgi?dir=$dir&active=$qn&mode=$qc", $chg) );`

with

`push(@cols, (!$qn ? "" : &ui_link("activate.cgi?dir=$dir&active=$qn&mode=$qc", $chg)) );`

Then on the right side for those binds there will be no Enable/Disable link.

----

Other than that we could go higher to the code and find line 34 and add right below add:

```Perl
next if (!$qn);
```

Then the whole row is not going to be printed at all. Exactly what we're trying to do.

**Comment by jcameron** [comment]
`$_[0]->[2]` should be the filesystem type, which should be `bind` in the case of your `/var/spool/mail`

**Comment by jcameron** [comment]
If not, I'd be interested in seeing the contents of your `/etc/mtab` file.

**Comment by qooob** [comment]
```BASH
[root@serv ~]# cat /etc/mtab 
...
/dev/sda2 / ext4 rw,seclabel,relatime,quota,usrquota,grpquota,data=ordered 0 0
/dev/mapper/RAID-10 /mnt/raid_10 ext4 rw,seclabel,relatime,quota,usrquota,grpquota,data=ordered 0 0
/dev/mapper/RAID-10 /var/spool/mail ext4 rw,seclabel,relatime,quota,usrquota,grpquota,data=ordered 0 0
/dev/mapper/RAID-10 /var/www ext4 rw,seclabel,relatime,quota,usrquota,grpquota,data=ordered 0 0
/dev/mapper/RAID-10 /var/lib/mysql ext4 rw,seclabel,relatime,quota,usrquota,grpquota,data=ordered 0 0
/dev/mapper/RAID-10 /srv ext4 rw,seclabel,relatime,quota,usrquota,grpquota,data=ordered 0 0
...
```

**Comment by jcameron** [comment]
Hmm .. that's going to confuse Webmin, because `/var/spool/mail` is really a loopback mount and not actually mounted on `/dev/mapper/RAID-10` . I'm not sure if there is a way to safely detect this case without breaking the ability to enable quotas for other filesystems.

**Comment by qooob** [comment]
First mounted RAID10. It has the a directory there. Later I mount that directory into other directory using bind, what's wrong with that?

I would detect it using a link. Are there valid for quotas FileSystems that has no clickable link? At least based on the same principle, not printing Enable/Disable link on the right column would be great already.

**Comment by qooob** [comment]
Yeah, relying on `$qn` is not going to work with disabled quotas.

What could I do? Is it my setup?

**Comment by jcameron** [comment]
In your case, is the problem just the filesystems are shown incorrectly, or are you prevented from enabling quotas on a filesystem that you really want them active on? I'm pretty sure that separate quotas on a loopback FS aren't possible.

**Comment by qooob** [comment]
No, quotas for RAID-10 work fine. You can enable it and disable it.

Quotas for those that mounted using `mount --bind` option are **_not expected to have quotas on_** BUT there are links on the right in the action column. When you click it, the page reloads but nothing changes - it always stays `Enable quotas`. What I say, that removing `Enable quotas` action link would be good enough and wouldn't look if something doesn't work.

Debian bug report [mount: Bind mounts not shown as such in mount output](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=691151) discusses things we're talking about. They recommend using `findmnt` command. 

I think, it's also related to [#34301](https://www.virtualmin.com/node/34301) and some other, where quotas don't work when they should. 

I don't expect quotas work on directories but in my case, RAID-10 is physical device. Webmin can enable/disable quotas correctly for this device _already_. But as I mentioned above, it also lists `--bind` mounts that are not possible to enable/disable.

Like I mentioned in the VM tracker for quotas problem - they don't work for RAID-10 properly. 


----


**Reason and solution**

I have user(s): `domain1.com`, `domain2.com` and etc. Their home is `/var/www/domain1.com`, `/var/www/domain2.com` and etc.

What happens afterwards the system was loaded? I run this command:

```BASH
/sbin/cryptsetup luksOpen /dev/disk/by-uuid/c0000a22-81a3-1ac-0600-0007d9e11f00 RAID-10
/bin/mount -t ext4 -o rw,usrquota,grpquota /dev/mapper/RAID-10   /mnt/raid_10

/bin/mount --bind /mnt/raid_10/var/www   /var/www
```

That means that data for quotas for virtual-servers now **_BELONGS TO_** RAID-10 and **NOT** /.

Right now, when you go to `Webmin->Disk Quotas` - all displayed correctly (more or the less). When I go to see the information for `/` - it shows `32kb` for my domains/virtual-servers. But If I go to `RAID-10`, then I see **_proper/expected_** numbers, like `/var/www/domain1.com` : _**30 GB**_;  `/var/www/domain2.com` : **_2GB_** and etc.

WebminCore has to check if the path hasn't been overwritten with other mounts and if it was, it has to consider that device as the one to retrieve data from.

Now on System Information page and in `Virtualmin->Edit Virtual Server->Quotas and Limits` there is everywhere `32kb/16kb/-8kb` for my disk space for virtual-servers. At the same time the size of the database is shown, but it seems to be larger that the actual.

Jamie, _please fix this_.

**Comment by qooob** [comment]
Any luck with this one?

**Comment by jcameron** [comment]
I'm not quite sure I understand the suggested fix - I wonder if you could send in a patch?

**Comment by qooob** [comment]
My previous commit was wrong.

Yours is potentially correct but I can't make to be passed to `mount` command _bind_ option, that would be reflected in `mtab`, and which made your commit work. But it should be left, I think as it might be different in other systems.

When you do bind, it inherits all of the options for the physical filesystem, and it's not possible to say which is which from looking at mtab. 

-----

### The only proof working way I found that will list bind mounts correctly is by running:

`findmnt | grep  "\["`

The output will list all of the filesystems that _**must not be listed**_ in _Disk Quotas_

[Ref.](http://unix.stackexchange.com/a/290441/34581)

**Comment by jcameron** [comment]
Can you create a patch for that?

**Comment by qooob** [comment]
Oh, yeah, I could try of course.. 😀👌

**Comment by qooob** [comment]
Here is the fix:

https://github.com/webmin/webmin/pull/526
