### ISSUE TITLE
Switching website from FCGID to PHP-FPM mode causes fatal error

### ISSUE THREAD

**Issue by chris001** [webmin/webmin#495]
* Apache is logging this error:
`AH01144: No protocol handler was valid for the URL /index.php. If you are using a DSO version of mod_proxy, make sure the proxy submodules are included in the configuration using LoadModule.`
There are multiple other virtual servers running FCGID, serving http only on port 8080, working fine.

* The browser shows a 500 Internal Server error, internal error or misconfiguration.

**Comment by jcameron** [comment]
Which Linux distribution and version is this on? From the error, it sounds like the required fcgid proxy module isn't loaded.

**Comment by chris001** [comment]
``
 	proxy 	Enabled
  	proxy_ajp 	Disabled
  	proxy_balancer 	Enabled
  	proxy_connect 	Enabled
  	proxy_express 	Disabled
  	proxy_fcgi 	Disabled
  	proxy_fdpass 	Disabled
  	proxy_ftp 	Disabled
  	proxy_html 	Disabled
  	proxy_http 	Enabled
  	proxy_scgi 	Disabled
  	proxy_wstunnel 	Disabled
``

**Comment by chris001** [comment]
Also getting this bug:
```
# service apache2 start
Job for apache2.service failed. See 'systemctl status apache2.service' and 'journalctl -xn' for details.
# systemctl status apache2.service
● apache2.service - LSB: Apache2 web server
   Loaded: loaded (/etc/init.d/apache2)
  Drop-In: /lib/systemd/system/apache2.service.d
           └─forking.conf
   Active: failed (Result: exit-code) since Sat 2017-02-18 17:57:34 EST; 2s ago
  Process: 20828 ExecStart=/etc/init.d/apache2 start (code=exited, status=1/FAILURE)

Feb 18 17:57:34 server1 apache2[20828]: Starting web server: apache2 failed!
Feb 18 17:57:34 server1 apache2[20828]: The apache2 configtest failed. ... (warning).
Feb 18 17:57:34 server1 apache2[20828]: Output of config test was:
Feb 18 17:57:34 server1 apache2[20828]: AH00526: Syntax error on line 56 of /etc/apache2/sites-enabled/subserver.virtualserver.com.conf:
Feb 18 17:57:34 server1 apache2[20828]: Invalid command 'php_admin_value', perhaps misspelled or defined by a module not included in the server configuration
Feb 18 17:57:34 server1 apache2[20828]: Action 'configtest' failed.
Feb 18 17:57:34 server1 apache2[20828]: The Apache error log may have more information.
Feb 18 17:57:34 server1 systemd[1]: apache2.service: control process exited, code=exited status=1
Feb 18 17:57:34 server1 systemd[1]: Failed to start LSB: Apache2 web server.
Feb 18 17:57:34 server1 systemd[1]: Unit apache2.service entered failed state.
Hint: Some lines were ellipsized, use -l to show in full.
#
```
The `php_admin_value` is being generated and placed there, virtualmin is making an assumption that `mod_php` is enabled.  

`mod_php` is disabled.  Only `fcgid` is being used while trying to get `php-fpm` to work, then all will switch over to `php-fpm` it's faster and about 10x more efficient.

**Comment by chris001** [comment]
OK when you 
1. manually comment out the line `php_admin_value Off` in every `.conf` file in `/etc/apache2/sites-available`, then 
2. manually enable the apache module `proxy_fcgi`, you get a different error.

* The browser says "503 Service Unavailable. The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.`
* The virtual server's `error_log` says: 
```
[Sat Feb 18 18:21:31.273381 2017] [proxy:error] [pid 22760] (111)Connection refused: AH00957: FCGI: attempt to connect to 127.0.0.1:8000 (*) failed
[Sat Feb 18 18:21:31.273409 2017] [proxy_fcgi:error] [pid 22760] [client 127.0.0.1:47536] AH01079: failed to make connection to backend: localhost, referer: https://www.virtualserver.com/administrator/index.php?option=com_installer&view=update
```

**Comment by singhdd93** [comment]
Even I got stuck at exactly the above error after enabling proxy modules in Apache. I tried this on Ubuntu 16.04 local server.

**Comment by jcameron** [comment]
The resolve the second error, try going to Webmin -> System -> Bootup and Shutdown, and make sure the `fpm` service is running.

**Comment by jcameron** [comment]
I am still looking into this issue - it seems like it happens only on some Linux distributions, like Fedora 25. For some reason, Apache isn't even trying to use the unix domain socket under `/var/php-fpm` to connect to the FPM server. Manually configuring it to use a TCP socket works though.

**Comment by sgrayban** [comment]
It's not just on Fedora but Debian/Ubuntu as well.

**Comment by sgrayban** [comment]
I had to switch all sites to cgi because fcgi and FPM because of 503 errors

**Comment by chris001** [comment]
Upgraded to `webmin-virtualserver 5.06-2` on debian 8.   Changed the virtual server's Website Settings PHP Script Execution Mode from FCGID back to FPM again just to try it and got these 2 message in the `error_log` when trying to reload the site:
```
[Sun Feb 19 12:24:01.729415 2017] [proxy:error] [pid 11199] (111)Connection refused: AH00957: FCGI: attempt to connect to 127.0.0.1:8000 (*) failed
[Sun Feb 19 12:24:01.729446 2017] [proxy_fcgi:error] [pid 11199] [client 127.0.0.1:47498] AH01079: failed to make connection to backend: localhost, referer: https://www.virtualserver.com/
```
Browser error again is `503 Service Unavailable`.

Let us know if you need any more information from the logs etc.

**Comment by jcameron** [comment]
For anyone who is seeing this, please post your Linux distribution and version, and Apache version.

**Comment by chris001** [comment]
I found this page which refers a similar situation.  Is it?
https://www.howtoforge.com/community/threads/bug-fix-php-fpm-fastcgi-mod_proxy_fcgi-sockets-not-working-together.72154/

**Comment by jcameron** [comment]
@sgrayban - are you saying that you also saw problems with fcgid mode?

**Comment by sgrayban** [comment]
Correct Jamie... I have some very pissed off clients now.

**Comment by sgrayban** [comment]
And the only way to get sites working again was to switch everyone to cgi mode.

**Comment by chris001** [comment]
Here, the fcgid is still working OK - at least it apears to be working OK.  All virtual servers are set to use fcgid and they all load pages.  Have disabled modules for mod_php and most other server api modes which are not in use in the interest of lowering the memory consumption of apache.

**Comment by singhdd93** [comment]
@jcameron I experience this on latest Virtualmin GPL on Ubuntu 16.04, Apache is 2.4

**Comment by jcameron** [comment]
Ok, it seems that on some systems Apache doesn't support using a Unix socket for FPM .. despite all the docs saying that this works.

For this reason, the next release of Virtualmin will use a TCP socket instead for new FPM servers.
