### ISSUE TITLE
Freebsd CPU info

### ISSUE THREAD

**Issue by jwhulette** [webmin/webmin#498]
Add the cpu info to the webmin main screen.

> sysctl hw.model hw.machine hw.ncpu
hw.model: Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz
hw.machine: amd64
hw.ncpu: 2

**Comment by jcameron** [comment]
Thanks! Which FreeBSD version are you running there though?

**Comment by jwhulette** [comment]
I'm running FreeBSD 11

**Comment by jcameron** [comment]
Thanks - the next release of Webmin will support detection of the CPU model on freebsd.

**Comment by jwhulette** [comment]
I'm not seeing this active in the latest release of webmin. Is there setting I need to activate?

**Comment by jcameron** [comment]
It should show up on the System Information page (but you may need to wait 5 minutes for cached data to be refreshed if you just upgraded Webmin).

**Comment by qooob** [comment]
Jamie, CPU chart is not shown on FreeBSD, which I install today to check on this issue.

CPU info is shown but there are only 2 charts on System Information page. Memory and Disk. CPU, the very left chart, that is shown on other installs is not showing.

**Comment by jwhulette** [comment]
![system_information_ _webmin_1_840_on_clients_ckadvertising_com__freebsd_11_0_](https://cloud.githubusercontent.com/assets/4930051/25968498/b07a6532-365f-11e7-9fdd-e61e79ac9c37.png)
This is what I'm seeing. The update has been install for almost 2 days.

**Comment by qooob** [comment]
Same was on my FreeBSD install. 

Maybe some packages need to be installed?

**Comment by jcameron** [comment]
Ilia - how does the theme get the CPU usage and type? Does it call the `proc` module's `get_cpu_info` function.

**Comment by qooob** [comment]
Jamie, I will only be able to check it tomorrow. I can say that I ether used Gray Theme as an example or used WebminCore. Gray Theme also doesn't show it.

**Comment by qooob** [comment]
Jamie, I think it's WebminCore and `$info->{'cpu'}`. `authentic-lib.pm` line 1003.

**Comment by jcameron** [comment]
Damn, I see the issue ... this is only populated on Linux, using the `vmstat` command which outputs CPU utilization as a percentage. I need to find an equivalent command for FreeBSD.

**Comment by jwhulette** [comment]
https://www.freebsd.org/cgi/man.cgi?query=vmstat&sektion=8

FreeBSD 11 output:
vagrant@:~ % vmstat
procs  memory       page                    disks     faults         cpu
r b w  avm   fre   flt  re  pi  po    fr   sr ad0 pa0   in    sy    cs us sy id
1 0 12 2.7G   65M    10   0   1   0    43  616 6358   0  419  3232  2428 18  7 75

I hope this helps.

**Comment by jcameron** [comment]
Thanks, I will update Webmin in the next release to support the FreeBSD `vmstat` command.

**Comment by jwhulette** [comment]
That's great. Will that also fix why the processor information is not shown under OS/CPU on the system info screen?

**Comment by jcameron** [comment]
Ilia, where does the theme get the CPU info from?

**Comment by qooob** [comment]
Jamie,  I think it's coming from `system_status::get_collected_info`

**Comment by jcameron** [comment]
The CPU model should be populated on FreeBSD then (in the `load` element of the collected info hash)

**Comment by qooob** [comment]
Jamie, I'll check on your patch in my FreeBSD installation and let you know if it works.

**Comment by qooob** [comment]
I confirm that it works after applying the patch on _FreeBSD_:

![screenshot from 2017-05-16 11-02-24](https://cloud.githubusercontent.com/assets/4426533/26095722/47c0970c-3a27-11e7-9e78-ba3601599bb6.png)

**Comment by jwhulette** [comment]
That's great that the CPU percentage is now showing, but I the original purpose of the ticket was for Processor Information:
![47c0970c-3a27-11e7-9e78-ba3601599bb6](https://cloud.githubusercontent.com/assets/4930051/26107528/99a544d8-3a17-11e7-9177-713e0a3ce93e.png)
<img width="567" alt="webmin-screenshot" src="https://cloud.githubusercontent.com/assets/4930051/26107529/99b46274-3a17-11e7-88cb-345bc7ca6bf6.png">

**Comment by jcameron** [comment]
If you go to System -> Running Processes -> CPU, does the CPU type appear there?

**Comment by jwhulette** [comment]
No it does not.

**Comment by jcameron** [comment]
@jwhulette - are you running the latest Webmin version (1.840) there?

Also, what does `sysctl hw.model hw.ncpu` output on your system?

**Comment by jwhulette** [comment]
Webmin version	1.840 

[wes@mooreandscarry ~]# sysctl hw.model hw.ncpu
hw.model: Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz
hw.ncpu: 2
[wes@mooreandscarry root]#

**Comment by jcameron** [comment]
Also, what  does the `uptime` command output on your system?

**Comment by jwhulette** [comment]
[wes@mooreandscarry root]# uptime
 3:36PM  up 202 days,  3:13, 0 users, load averages: 0.39, 0.27, 0.25

**Comment by jcameron** [comment]
Ah, I see now .. the uptime command output format has changed. See the patch that I am adding to this bug report right now for a fix.

**Comment by qooob** [comment]
This fix might only work in some cases:

https://github.com/webmin/webmin/pull/565

**Comment by qooob** [comment]
I was rushing so I couldn't do proper fix. The regex should include both with `@` and without, I think.

**Comment by jcameron** [comment]
@iliaross  - what does it output on your system?

**Comment by qooob** [comment]
Jamie, in the current state, in case my processor's gathered info from the command doesn't have @ it fails to show anything, obviously. Regex should respect both formats with and without @ in the output.

**Comment by FreeDal** [comment]
Hi Jamie. I've been using Webmin for many years. Thanks for all your hard work on this project. It has saved lives I'm sure :-)

We've recently begun migrating all our Ubuntu and Centos machines to FreeBSD and have noticed a problem with the CPU usage graphic in Webmin. It shows the CPU running at over 100%. It seems to work fine on some machines but not others. I originally thought it had to do with machines running inside FreeBSD jails but we're seeing the problem on the hosts as well.

**Comment by FreeDal** [comment]
<img width="1419" alt="screen shot 2017-10-28 at 4 05 37 pm" src="https://user-images.githubusercontent.com/33173507/32132702-1109241c-bbfb-11e7-8178-c34c9c5aa6cc.png">

**Comment by FreeDal** [comment]
<img width="1420" alt="screen shot 2017-10-28 at 4 05 54 pm" src="https://user-images.githubusercontent.com/33173507/32132705-2359858a-bbfb-11e7-8cc8-f7f5aabc6895.png">

**Comment by FreeDal** [comment]
Hi Jamie - Were you able to look into the above CPU issue? We're still struggling with it. Thanks.

**Comment by jcameron** [comment]
Yes, I've implemented a fix for this, and will include it in the next release : https://github.com/webmin/webmin/commit/7fa1927121f4a442864bf008fd28eb4a89fe3e68

**Comment by FreeDal** [comment]
Legend. Thank you.
