### ISSUE TITLE
Webmin Configuration -> Default Mobile Device Options

### ISSUE THREAD

**Issue by qooob** [webmin/webmin#501]
Jamie,

Isn't worth setting _Authentic Theme_ as default for _Mobile Device Options_ in _Webmin Configuration_?

**Comment by jcameron** [comment]
How does it look when accessed on mobile? We have another theme called the "Virtualmin Mobile Theme" that has a special limited-size UI that works pretty well..

**Comment by qooob** [comment]
It looks pretty usable. Please give it a try.

**Comment by jcameron** [comment]
I had a look, but it still seems to be lacking some of the features of the Virtualmin Mobile theme - for example, a lot of forms are too wide and don't fit on a phone screen.

**Comment by qooob** [comment]
Alright, great. I will use it as an example, a bit later, to improve Authentic. Whenever it's the same good, I'll let you know. 😉
