### ISSUE TITLE
SSL + Let's Encrypt + Mail Server DANE + TLSA Records Paradox 

### ISSUE THREAD

**Issue by hsntgm** [webmin/webmin#503]
Hi,

When i first  start to use webmin/virtulamin i said that this is incredible framework to manage things but after Let's Encrypt integration things goes crazy for me. Now i have lots of logic confusion. It seems for your side it is also complicated. 

Please correct me if i am wrong in default virtualmin setup, when you create a new virtual host e.g. example.com it assign mx record mail.example.com to DNS. This is our mail server now.

After you request new certificate from **Manage SSL Certificate** in vhost level you are able to copy them postfix and devocot. 

1) What does it mean? Why you let me to copy example.com issued webserver certificate for postfix and dovecot. I mean this is a webserver level certificate issued for example.com and **example.com != mail.example.com**.

2) Then you create auto TLSA records even for mail.example.com for all ports **with example.com issued certificate**. I mean smtp:example.com = mail.example.com and TLSA record for mail.example.com generated with example.com issued certificate. 

So, first i created new vhost for **mail.example.com** and requested Let's Encrypt certificate for mail.example.com then i copied this certificate to postfix and dovecot. Now my mail server has a correct certificate mail.example.com = mail.example.com. 

For TLSA records, for my mail server (smtp,pop3,imap) i manually generated them with **mail.example.com issued certificate**. smtp:example.com TLSA records:

_993._tcp.mail	TLSA 3 0 1 70197bacff244e2617922122987a3f....
_587._tcp.mail  TLSA 3 0 1 70197bacff244e2617922122987a3f....
_465._tcp.mail  TLSA 3 0 1 70197bacff244e2617922122987a3f....
_995._tcp.mail  TLSA 3 0 1 70197bacff244e2617922122987a3f....
_25._tcp.mail	TLSA 3 0 1 70197bacff244e2617922122987a3f....
_110._tcp.mail  TLSA 3 0 1 70197bacff244e2617922122987a3f....
 
**For port 80 and 443 I used webserver certificate to generate TLSA records.**

Now maybe i able to setup DANE TLS authentication with below config:

```
main.cf:

smtp_dns_support_level = enabled
smtp_dns_support_level = dnssec
smtp_tls_security_level = dane

master.cf:

    dane       unix  -       -       n       -       -       smtp
      -o smtp_dns_support_level=dnssec
      -o smtp_tls_security_level=dane
```

Now there are two possibilites one of them is i completly lost my way ,the second there is something wrong virtualmin logic.

Sincerely,

**Comment by jcameron** [comment]
Ok, this is really a missing feature in Virtualmin - it should also request the cert for mail.domain so that SMTP and IMAP connections work properly. We'll fix this in the next release.
