### ISSUE TITLE
Bind module does not recognise IPs combined with keys in also-notify

### ISSUE THREAD

**Issue by mjhodgkinson** [webmin/webmin#506]
Hi Jamie,

To reliably transfer zones to slaves with in views we need to couple notify IPs with keys. For an example of this please see here:
https://kb.isc.org/article/AA-00851/0 

However if I try to enter an IP and key into a zone also-notify option it breaks into multiple lines, for example:
192.168.0.1 key test
192.168.0.2 key test

When saved becomes:
192.168.0.1
key test
192.168.0.2
key test

or:
also-notify {
  192.168.0.1;
  key test;
  192.168.0.2;
  key test;
};

I even tried putting ; on the end of the lines, but that broke things even worse.

There may also be an issue with zone masters statements with IPs and keys, but I have not tested this. Need to build a test environment to confirm.

Cheers
Mike

**Comment by jcameron** [comment]
Thanks for reporting this - there is code in Webmin that was attempting to handle this, but it didn't work properly :-(  The next release will do it right though.
