### ISSUE TITLE
Enterupt executed server process - add Terminate button to the table header?

### ISSUE THREAD

**Issue by qooob** [webmin/webmin#507]
Jamie, hi.

Any time we `Install Script` or `Update Packages` or do any other operation that involves _buffered headers_, the table's header should contain the _**Terminate**_ button (link) that would just send kill or terminate signal to the process and it's tree.

It would be good to use the same mechanism of adding such buttons (links), like on BIND module for example, where you have stop and other buttons on the top-right.

I prefer it to have static _href_, containing certain text, like `terminate.cgi` or something.

I think it's good to have it and I hope not very difficult to implement?

**Comment by jcameron** [comment]
I'm not sure if that's a good idea - can't the user just click the stop button in the browser?

**Comment by qooob** [comment]
Stop button? It will not terminate the process on the server side? It will not send `kill -9 pidNumber`, right?

**Comment by jcameron** [comment]
It will terminate, because the process will receive a SIGPIPE signal due to inability to produce output because the network connection was closed.

**Comment by qooob** [comment]
I see. Is there a way to send such signal without using browser's button? Using JavaScript and/or server request?

**Comment by jcameron** [comment]
Not that I know of. That said, why would you want to do this? Most long-running operations in virtualmin or cloudmin really shouldn't be interrupted or else you'll end up with a half-created domain or VM.

**Comment by qooob** [comment]
It would be great, I though, to be possible for the user to terminate it. For install script or package updates, that are run accidentally or taking a long time.. Like user can always hit Ctrl+C in console. You shouldn't do it, but you have opportunity.

**Comment by jcameron** [comment]
For those kinds of operations, as long as they are producing output, clicking "stop" in the browser should terminate the script.

**Comment by qooob** [comment]
I know now. Thanks, Jamie. I just believe that having a button inside of Webmin would be much more user-friendly. Not many aware about SIGTERM.

On the other hand, having a button is very clear and intuitive. Terminate is terminate.. Stop button in browser is not that clear.

**Comment by jcameron** [comment]
I suppose the theme could add a button for this, for pages that call ui_print_unbuffered_header

**Comment by qooob** [comment]
Yes, it could. I'll see what I can do.
