### ISSUE TITLE
DNS Bind: `verisign-grs.com` is not working

### ISSUE THREAD

**Issue by qooob** [webmin/webmin#509]
Jamie, probably this address (verisign-grs.com) is dated? It doesn't seem to work at all.

**Comment by jcameron** [comment]
Wait, where are you seeing that address?

**Comment by qooob** [comment]
Jamie, it's _Lookup WHOIS Information_:

![screenshot from 2017-03-08 14-24-03](https://cloud.githubusercontent.com/assets/4426533/23702180/42002bf4-040b-11e7-9c26-17faa3c565ae.png)

There are other services that work great.

**Comment by jcameron** [comment]
The "Whois" lookup in Webmin just runs the  `whois` command on your system though. Maybe it's out of date and is contacting the wrong whois server?

**Comment by qooob** [comment]
Alright, it was my Firewall. Very sorry for disturbance.
