### ISSUE TITLE
How do I use Java client through XML call webmin module functions?

### ISSUE THREAD

**Issue by wandk000** [webmin/webmin#51]
I through the url:http://root:123456@10.10.10.55:10000/xmlrpc.cgi
 interview results returned to 
<methodResponse><fault><value><struct><member><name>faultString</name><value><string>Invalid XML :  no element found at line 1, column 0, byte -1 at /usr/local/lib64/perl5/XML/Parser.pm line 187</string></value></member><member><name>faultCode</name><value><int>4</int></value></member></struct></value></fault></methodResponse>
What should I do?

**Comment by shoulders** [comment]
his should be closed because
- 2013
- this is a support request and not a feature or bug
