### ISSUE TITLE
CRON module: Move buttons

### ISSUE THREAD

**Issue by qooob** [webmin/webmin#510]
Jamie, hi.

There are strange move buttons in CRON module. It's two rows of them and they seem to make the same thing? Could you double check please. The same happens in all themes.

Screenshot:

![screenshot from 2017-03-08 18-07-40](https://cloud.githubusercontent.com/assets/4426533/23709439/84b15e68-042a-11e7-83d7-87b9d2fed4f5.png)

In case it's a bug, I think it's better to remove the last row of buttons.

**Comment by jcameron** [comment]
Do you mean that the move buttons have no effect?

**Comment by qooob** [comment]
There are two columns of them, doing the same thing?

**Comment by jcameron** [comment]
Oh I see what you mean. The first column moves up and down, the second column moves to the top or bottom.

**Comment by qooob** [comment]
Ohh, I see now.
