### ISSUE TITLE
Users and groups: Wrong documentation in Edit User

### ISSUE THREAD

**Issue by qooob** [webmin/webmin#513]
Jamie, look at the help pop up and what is says:

>..with the exception of the username.

![screenshot from 2017-03-13 21-16-28](https://cloud.githubusercontent.com/assets/4426533/23868998/8f85d4e8-0832-11e7-91a0-af1d822e40ba.png)

This is not valid. You can change the _username_.

**Comment by jcameron** [comment]
Thanks! Will fix ..
