### ISSUE TITLE
Webmin Users: Two-Factor Authentication go back button is missing

### ISSUE THREAD

**Issue by qooob** [webmin/webmin#514]
Hi, Jamie.

When _Two-Factor Authentication_ _**is not set up**_ the footer, blue back button is missing. At the same time, when it's set up it's alright. Please have a look. I mustn't be adding it on the theme side. 
https://github.com/qooob/authentic-theme/issues/678

**Comment by qooob** [comment]
Example:

![screenshot from 2017-03-16 14-08-03](https://cloud.githubusercontent.com/assets/4426533/23993555/115b1d2c-0a52-11e7-9789-44bb34aa6811.png)


When it's set up all look fine:

![screenshot from 2017-03-16 14-09-29](https://cloud.githubusercontent.com/assets/4426533/23993592/3e88a346-0a52-11e7-874f-17aed23b2512.png)

**Comment by jcameron** [comment]
Someone else reported this just yesterday - I checked in a fix for it last night.
