### ISSUE TITLE
Webmin doesn't seem to notice updated SSL

### ISSUE THREAD

**Issue by Sarke** [webmin/webmin#515]
This has happened few times now, whenever we update our SSL Webmin still serves the expired on (even several days after) until we go into `/webmin/edit_ssl.cgi` and reselect the same key and cert file.

I would be nice if Webmin periodically checks if the cert or private key files have changed (simply by timestamp even), so that it can serve the new one.

**Comment by jcameron** [comment]
Did you update the SSL cert and key files directly, or via the Webmin UI? Because it (intentionally) won't re-read the cert unless it is restarted.

**Comment by Sarke** [comment]
@jcameron directly, not through webmin.  So what is the best way to trigger the update?  `service webmin restart` ?

**Comment by jcameron** [comment]
Yes, or you can run `/etc/webmin/restart`
