### ISSUE TITLE
Usermin: Disk quotas in Debian

### ISSUE THREAD

**Issue by qooob** [webmin/webmin#522]
Jamie, hi.

On Debian systems there is a very old and ugly chart-bar tries to get inside of the top table, making dataTables fail.

At the same time on RHEL systems it's not rendered and the table loads beautifully with working sorting for size.

This is how bad it is in Debian.

![screenshot from 2017-03-21 14-07-00](https://cloud.githubusercontent.com/assets/4426533/24144967/5f9f8f08-0e40-11e7-9e0d-3b2d09933065.png)

Could you just remove it?

**Comment by jcameron** [comment]
Do you mean that the same module appears differently in Debian vs Redhat?

**Comment by qooob** [comment]
Yes they do.

This is how it looks on Fedora:

![screenshot from 2017-03-22 15-23-28](https://cloud.githubusercontent.com/assets/4426533/24197699/bcf638a4-0f13-11e7-82a0-529126d1414f.png)

**Comment by jcameron** [comment]
In the second screenshot, the user doesn't appear to have any quota limits. Maybe that's why no bar charts appear?

**Comment by qooob** [comment]
Yes, probably.

Do we really need those? The way it is now it breaks the table.

**Comment by jcameron** [comment]
I suppose they could be dropped. Is there a way a bar chart could be included without causing breakage though ... or does spanning multiple columns inherently cause problems?

**Comment by qooob** [comment]
Having no thead or invalid number of colspans is the main problem for dataTables.

In this case, taking bar outside of the table and using a standard chart output (like on sysinfo page for quotas or bandwidth) would probably make things look good and definitly would stop the breakage.

Using tables for creating chars is a bit dated and hard to style properly.

**Comment by jcameron** [comment]
OK, I'll remove it in the next usermin release.
