### ISSUE TITLE
Two Gray Themes: very confusing

### ISSUE THREAD

**Issue by qooob** [webmin/webmin#523]
Jamie, hi again.

This is most confusing thing. You should do something with that, to make sure the select doesn't get 2 options for Gray Framed Theme.

![img_20170321_140925](https://cloud.githubusercontent.com/assets/4426533/24148910/ccce2d62-0e51-11e7-8969-5b1449c39847.jpg)

**Comment by jcameron** [comment]
This will be gone in the next release.

**Comment by swelljoe** [comment]
This is fixed in new versions.
