### ISSUE TITLE
Let's Encrypt enhanced renewal planning request

### ISSUE THREAD

**Issue by jobhh** [webmin/webmin#524]
I've noticed a couple times that my mailbox is filled with Let's Encrypt emails. I've found 2 separate reasons: 
1. The challenges could fail repeatedly, which leads to Let's Encrypt stopping to accept challenges after 5(?) attempts. But since Webmin just keeps trying I get 5 mails with a usable error message and 100+ with the "too many attempts, wait a couple hours please" from Let's Encrypt.
2. Yesterday a renewal failed because I entered an incorrect sub-domain among the correct domains. I got 205 emails in 18 hours before I noticed it.

I have two requests/suggestions:
1. Can Webmin reduce the amount of emails produced by a certificate renewal fail? Eg. Wait longer before making another attempt when it notices a certificate renewal fails? 10+ emails per hour seems a bit excessive.
2. More advanced scheduling of the certificate renewal. I currently set the "Months between automatic renewal" to 2, because I'd like some time to fix it if a automatic renewal fails. A simple input option like 2.5 months or 2m14d would lower the stress on the Let's Encrypt servers. Things like "on Saturday at 19:00 2 weeks before the certificate expires" or "the 3rd saturday of the month before the certificate expires" seems ideal.

**Comment by jcameron** [comment]
Webmin and Virtualmin should already add a delay of between 1 and 24 hours between renewal re-attempts to prevent this.

Did you setup this renewal at Webmin -> Webmin Configuration -> SSL Encryption?

**Comment by jobhh** [comment]
The SSL certificate in my last example were configured via Virtualmin -> *Select domain* -> Server Configuration -> Manage SSL Certificate -> Let's Encrypt -> Request certificate for -> Domain names listed here. I listed 3 domains, 1 of which was erroneous during the last renewal. The one a couple months earlier used " Domains associated with this server" in stead of "Domain names listed here", but also via the Virtualmin GUI.

With regards to the more renewal advanced scheduling: Would this be possible? Setting a number of months feel rather restricted given the maximum lifetime of 3 months for a certificate.

**Comment by jcameron** [comment]
You can enter a non-integer for the number of months between renewals, like 2.5.

**Comment by jobhh** [comment]
Hmmm, I was convinced I tried that a couple months back. But it works, so that's nice :)

But that doesn't completely answer the questions:
1. Can the amount of failure emails be limited?
2. Can a more advanced renewal scheme be implemented? Something like "on a Saturday 2 weeks before the certificate expires" would be convenient if something goes wrong with the renewal.

**Comment by jcameron** [comment]
There was a bug in the previous version of Virtualmin that could cause renewals to be re-tried without waiting for the proper delay, but that will be fixed in the next release.

More advanced scheduling isn't likely to be implemented though.

**Comment by jobhh** [comment]
Thanks for the quick reply and the fix :) 
I'll close this issue if the advanced scheduling won't be implemented to keep the issue tracker clean.
