### ISSUE TITLE
Deprecated MySQL syntax

### ISSUE THREAD

**Issue by laukstein** [webmin/webmin#53]
Virtualmin and Webmin does not handle correctly MySQL 5.6.10 and has a deprecated SQL syntax on adding database and does not let to install phpMyAdmin.

**Comment by mdimarino** [comment]
There are any workaround for this problem? I'm using webmin 1.801 and MySQL 5.6.31 packages from Oracle.

**Comment by laukstein** [comment]
@mdimarino, check
> ... it works fine after removing sql_mode=STRICT_TRANS_TABLES from /usr/my.cnf

**Comment by mdimarino** [comment]
For me it didn't work.
What solved this problem for me was installing Perl modules DBI and DBD::mysql.
