### ISSUE TITLE
DNSSEC error while saving edited DNS records in virtualmin.

### ISSUE THREAD

**Issue by chris001** [webmin/webmin#532]
DNSSEC-signzone Error when doing the following:
1. Under top level virtual server "server1.mydomain.com", go into the add-on domain "mydomain.com". 
2. Click "Server configuration", "DNS records".
3. Edit the record for "server6" and change the IP4 address, and click Save.

```
Failed to save DNS record : Record was not fully saved : 
DNSSEC signing failed : DNSSEC signing after records change failed : 
dnssec-signzone: warning: /var/lib/bind/mydomain.com.hosts:52: signature has expired 
dnssec-signzone: fatal: 'server1.mydomain.com': found DS RRset without NS RRset 
```

**Comment by jcameron** [comment]
Can you post the contents of `/var/lib/bind/mydomain.com.hosts` to this bug report? I'd like to see what Virtualmin is doing wrong with the file.

**Comment by chris001** [comment]
Do you want the entire file or just the line 52 with the error?
Line 52 is the first RRSIG line.
It's a big zone file, 148 lines.  Would be better to share on email, too much to sanitize for posting here.

**Comment by jcameron** [comment]
You can email the whole file to me at jcameron@webmin.com

**Comment by chris001** [comment]
Emailed, thanks.

**Comment by pgporada** [comment]
Was there ever a resolution to this? I don't use webmin, but I'm trying to figure out what to do about the `found DS RRset without NS RRset` problem on my own server.

**Comment by chris001** [comment]
@pgporada 
I found this explaining why this error can happen.
https://help.directadmin.com/item.php?id=652
```
The signging of the jbmc-software.com zone will fail when the DS records for subtest exist in jbmc-software.com, but the NS records for subtest are not explicitly set in the jbmc-software.com zone.  This error would look like:

dnssec-signzone: fatal: 'subtest.jbmc-software.com': found DS RRset without NS RRset
```

**Comment by chris001** [comment]
Update: To fix this DNSSEC error, it appears that, for each subdomain, you must add the subdomain's NS records (the hostname of the subdomain's nameserver?) in the parent zone (domain).
Example:
For `parent.com` zone (domain), you must add an `NS` (nameserver) record for `sub.parent.com` and maybe set it to `ns1.sub.parent.com` (when the subdomain manages its own domain resource records, which is typical).

**Comment by jcameron** [comment]
@chris001 is this needed even both the parent and sub-domains are hosted on the same Virtualmin system?

**Comment by chris001** [comment]
@jcameron Yes, the `NS` records for the `sub.mydomain.com`, are required to exist in the parent domain zone `mydomain.com`, even when both the parent and sub-domains are hosted on the same Virtualmin system (`bind9` server).  

Without those `NS` records, Virtualmin's `bind9` DNS server bombs when signing/re-signing the zone, you get this error: `dnssec-signzone: fatal: 'sub.mydomain.com': found DS RRset without NS RRset`. 

Also, once you get that error, the domain fails general `DNSSEC` validation on the internet, and is no longer signed, and no longer secure.

**Comment by jcameron** [comment]
ok, that should be possible to add

**Comment by jcameron** [comment]
Ok, this will be implemented in the next release.

**Comment by CTM-Chris** [comment]
Just wanting to know it this has been implemented yet, having the same issue with Webmin version 1.941

Thanks in advance,
Chris

**Comment by jcameron** [comment]
@CTM-Chris the fix will be in the next Virtualmin release
