### ISSUE TITLE
Theme update to 18.45 breaks file edit

### ISSUE THREAD

**Issue by pieter-groeneweg** [webmin/webmin#534]
Today I upgraded three different setups (a centos, raspbian and debian) from 18.31 to 18.45

On all the file manager -> right click -> edit fails. 

The expected editor screen does not pop up anymore.

**Comment by qooob** [comment]
I'll take a look when get to the PC

**Comment by pieter-groeneweg** [comment]
thanks, meanwhile i did some more research.. This is what I get in my browser console (chrome) when opening a folder in the file manager:

```
init.min.js?1845:6 Uncaught TypeError: Cannot read property 'replace' of undefined
    at decode_html (init.min.js?1845:6)
    at HTMLTableRowElement.<anonymous> (file-manager.min.js?1845:6)
    at HTMLBodyElement.dispatch (bundle.min.js?1845:2)
    at HTMLBodyElement.r.handle (bundle.min.js?1845:2)
```

and when clicking right to edit:

```
Uncaught TypeError: Cannot read property 'replace' of undefined
    at decode_html (init.min.js?1845:6)
    at HTMLBodyElement.<anonymous> (file-manager.min.js?1845:6)
    at HTMLBodyElement.dispatch (bundle.min.js?1845:2)
    at HTMLBodyElement.r.handle (bundle.min.js?1845:2)
    at Object.trigger (bundle.min.js?1845:2)
    at HTMLBodyElement.<anonymous> (bundle.min.js?1845:2)
    at Function.each (bundle.min.js?1845:2)
    at bw.fn.init.each (bundle.min.js?1845:2)
    at bw.fn.init.trigger (bundle.min.js?1845:2)
    at HTMLAnchorElement.<anonymous> (file-manager.min.js?1845:6)
```
Tx

**Comment by qooob** [comment]
Clear browser's cache or try incognito tab, please.

**Comment by pieter-groeneweg** [comment]
cache had been cleared... incognito mode.. both show the same errors...

**Comment by qooob** [comment]
Do you use proxy? Did you restart Webmin afterwards?

**Comment by pieter-groeneweg** [comment]
checked for a proxy - no proxy
restarted webmin
cleared cache again

Even checked on my smartphone..

All the same errors.

**Comment by pieter-groeneweg** [comment]
clicked the wrong button... :( reopened it.

**Comment by qooob** [comment]
Hi,

I couldn't reproduce an issue. After clearing cache things were working fine. On the other server I didn't even have to clear the cache.

Besides, there is `decode_html()` in [init.js#L148-L166](https://github.com/qooob/authentic-theme/blob/master/unauthenticated/js/init.js#L148-L166)

**Comment by qooob** [comment]
Can any one else reading this reproduce an issue?

**Comment by pieter-groeneweg** [comment]
Is there a way to revert to 18.31 and then try and reinstall 18.45..

I cannot imagine three different machines with different setups suffer from the same.. centos, raspbian, debian....

**Comment by qooob** [comment]
Yes, you could download it from releases. You could also update using shell script. The procedure described on the README.md.

**Comment by pieter-groeneweg** [comment]
I updated manually as described in https://github.com/qooob/authentic-theme/blob/master/README.md
now I get a notice to upgrade to 18.46 beta3?

**Comment by qooob** [comment]
Yes, you can enable it in theme's settings at the very bottom of the page.

So, does it work now?

**Comment by pieter-groeneweg** [comment]
On one machine yes, (centos) raspbian wines about git commandline not installed....
Is that new? I never had issues updating before as I remember...

**Comment by qooob** [comment]
It shouldn't be an issue in most cases.

**Comment by pieter-groeneweg** [comment]
the centos 6.9 works ok with the new theme 18.45
the raspbian (debian 8) I reverted back to 18.32 and now it works again.
same with the full debian 8.

I can't tell why debian 8 has issues... maybe the paths to something? as your manual install intructions paths needed to be changed to match those of debian... the centos machine paths are same as in your instructions.

**Comment by qooob** [comment]
I tested it on Debian as well and it was fine. I actually test it on CentOS and Fedora as well before the release.

Maybe you could try again using the `theme-update.sh` script on those machines?

**Comment by pieter-groeneweg** [comment]
no joke... them-update.sh disappeared...... ?

**Comment by qooob** [comment]
Yes. It's not in 18.31 yet. Just add it there manually and make it executable with `chmod 755 theme-update.sh`

**Comment by pieter-groeneweg** [comment]
just copy that one file from github?

**Comment by qooob** [comment]
Yes.

**Comment by pieter-groeneweg** [comment]
This is what I get. It did not update.

```
Would you like to update Authentic Theme for Webmin? [y/N] y                    
Pulling in latest changes for Authentic Theme (https://github.com/qooob/authenti
c-theme)...                                                                     
Cloning into '/usr/share/webmin/.~authentic-theme'...                           
remote: Counting objects: 1309, done.                                           
remote: Compressing objects: 100% (1057/1057), done.                            
remote: Total 1309 (delta 97), reused 1173 (delta 49), pack-reused 0            
Receiving objects: 100% (1309/1309), 3.87 MiB | 3.33 MiB/s, done.               
Resolving deltas: 100% (97/97), done.                                           
error: waitpid for --shallow-file failed: No child processes                    
fatal: index-pack failed                                                        
error: waitpid for fetch-pack failed: No child processes                        
Updating Authentic Theme, failed.   
```

**Comment by qooob** [comment]
Jamie, do you know what this could be the cause of it?

The only thing I can think of is the memory issue.

Add the following into file `.gitconfig` under `/root` directory (if you run the script as root):

```Config
[core] 
packedGitLimit = 512m 
packedGitWindowSize = 512m 
[pack] 
deltaCacheSize = 2047m 
packSizeLimit = 2047m 
windowMemory = 2047m
```

If it doesn't work, try few times.

**Comment by pieter-groeneweg** [comment]
though I installed git after it wined about not having it, I cannot find the .gitconfig.. and I do run as root.

**Comment by qooob** [comment]
Just `nano `~/.gitconfig` and add those lines.

**Comment by pieter-groeneweg** [comment]
did that with the install file in the 18.46 package.. now right click on a file opens an empty showing the path without the filename....

going to rvert back to 18.31 again.

Is there some dependency on virtualmin versions? running 5.04 currently

**Comment by qooob** [comment]
I think 5.07 latest. Are you on Ubuntu?

**Comment by pieter-groeneweg** [comment]
The one that works is on Centos that is ok.
Second as I said Raspbian (Debian 8 on a Pi3) this one does not work ok.. file editor (and maybe more) are not functioning ok on edit.
The third also is on Debian 8 on an old Atom based (n570) that is not complaining about updates needed for the theme....

**Comment by qooob** [comment]
Do those installs that don't work have latest Webmin? Did you try to reboot the server?

I can not reproduce it, how ever I try :(

**Comment by qooob** [comment]
Today I made a fix to prevent fatal errors. Try latest Git version. Update using script.

**Comment by pieter-groeneweg** [comment]
webmin 1.831

**Comment by qooob** [comment]
None 3 of us can reproduce the issue on absolutely different machines, with different distros. I wish I could do more for you but I have no idea what you're facing.

**Comment by pieter-groeneweg** [comment]
Much appreciated.

Only thing I can think of now is armhf set and the fact virtualmin is installed as webmin module.
Coming few days I don't have much time.
What I plan to do is install another pi3 with the same. Two options
Starting from scratch. compared with a clone of current setup and see if I can tweak.

Will be somewhere in next week.

**Comment by qooob** [comment]
Jamie, this issue can be closed. 

I could reproduce this issue only on first load, and only after `localStorage` is cleared. 
https://github.com/qooob/authentic-theme/issues/731#issuecomment-297657731

**Comment by qooob** [comment]
It's fixed.

**Comment by pieter-groeneweg** [comment]
Partial.. 
Installing the new theme 18.47 using the normal update method takes forever. After some 15 minutes I refreshed browser window. 18.7 appeared to be installed.

Upon checking if the editor works ok again I noticed the colored markup to be gone in scripts.
Just plain white on black. No colors anymore for code like html, php and on.

**Comment by qooob** [comment]
It's all fixed in Git version and will be added on 18.48. There is Git updates and even a button now, to update with one click (in update notice), so just update using script. It's very stable.

I'm finishing now the support for encodings in FM, when editing files - from now on, will respect initial file encoding on both, displaying and saving.
18.48 will be cooked right after.

**Comment by pieter-groeneweg** [comment]
Awesome! I can't wait.
Thanks for all the good work!

**Comment by pieter-groeneweg** [comment]
Just upgraded all my three (different) machines to 18.48.
They all installed without a hitch, did not run forever and all "color-coding" in scripts is back in the editor.

Great work and many thanks!

**Comment by qooob** [comment]
You're very welcome. 😉
