### ISSUE TITLE
Make it possible to hide/remove the Reboot Now!

### ISSUE THREAD

**Issue by Sopor** [webmin/webmin#538]
When i upgrade Ubuntu i sometimes get this message on the dashboard,
```
Warning!
Recent package updates (such as a new kernel version) require a reboot to be fully applied.
Reboot Now!
```
but if i don't want to reboot now i'm stuck with this text. So i wondering if you could make it disappear (a button that will make it go away) until the `reboot-required` get changed again? It must be easy to check the date/time of the file or delete the file `reboot-required`. Use whatever you think is the best way to detect it has been changed (I'm not the expert here). As it is now i have to manually delete the file because this Reboot Now is only annoying to see when i know i won't reboot.

**Comment by sgrayban** [comment]
NO !!!

**Comment by jcameron** [comment]
I suppose this could be done, but you could also just delete the `reboot-required` file to clear the message.

**Comment by qooob** [comment]
By the way, where is this file located?

**Comment by Sopor** [comment]
@iliaross you will find it in the folder /run but i believe it is not there if no reboot is required.

@jcameron of course but as i'm already sudo in Webmin and i always have the Dashboard available it would be much easier to press a button and it was gone. There are always alternative things to perform something.. Same as Webmin, we don't need Webmin because everything you do in Webmin you can do from a terminal window. Webmin only makes it a bit easier, at least for me :)
It seems that these updates required an update: `libssl1.0.0, dbus, libc6` at least according to the file `reboot-required.pkgs`.

**Comment by qooob** [comment]
@Sopor- Maybe cresting custom command, that would delete a file? You could add to theme's favorites and it's literally one click to run it.

**Comment by Sopor** [comment]
@iliaross Add a custom command to the favorites? This will only open the Custom commands. So to get there i first have to open favorites, then press the added favorites and then press the custom command to run it. Now i'm at three mouse click. If i then want to go back to the Dashboard again it will be four mouse click. I don't call that one click ... Maybe you know something i don't know on how to create a custom command? It would be nice if it was possible to add custom commands as buttons below the navigation menu. Maybe you will do that in your theme if i ask for it :)

**Comment by qooob** [comment]
No, you're missing one thing. Theme lets you add the star (add to favorites) any page really.

After you create your custom command, go ahead and run it, so it does what it should. Right there, when it's run and progress/server respond is printed - _add a star_. It will get directly to favorites. Later when you hit the link from favorites it will directly runs it, no extra clicks needed.

You can rename it or call it the way you want by editing the file. When you open the favorties screen-overlay, there will be the link for editing it. :wink: 

Does it sound better?

**Comment by Sopor** [comment]
@iliaross It will still be three mouse clicks but it works as you described...
1. Favorites (open favorites)
2. Command (run the command)
3. Dashboard (go back to dashboard)
Maybe you could think of adding custom buttons to the Navigation menu 😃

**Comment by qooob** [comment]
Custom buttons to navigation menu? Virtualmin has the ability to add custom links to the navigation (left) menu.

It would be cool to run a command in background. It would be cool to mark the items in Favorites as to be executed in the background. Sounds like an improvement  to me. I also don't like when you need to run a command from favorites that it takes me to the other page.

In case no one against it, wait a while @Sopor- (12 hours) and then add a ticket to my repo.

**Comment by adiastra** [comment]
There should also be an button to schedule a reboot and for that matter there needs to be a place to schedule recurring reboots

**Comment by qooob** [comment]
Theme just does representation in this regard. You can schedule it your-self. You need to submit/comment about this issue to Webmin repo, as theme receives data from it.

**Comment by qooob** [comment]
Oh, sorry. This is Webmin repo :laughing:

**Comment by jcameron** [comment]
I suppose we could add a "maybe later" button to suppress the reboot message..

**Comment by ilinbxu** [comment]
I have the same error, restart many times, still report an error.

Operating system
CentOS Linux 7.6.1810
Time on system
Tuesday, August 6, 2019 11:22 AM

Linux 3.10.0-957.27.2.el7.x86_64 on x86_64
All installed packages are up to date
Reboot Now
--

**Comment by rostovtsev** [comment]
It's been fixed for Webmin 1.921+. You can have it updated using command:


 ```Bash
yum update https://download.webmin.com/devel/rpm/webmin-1.921-1.noarch.rpm
```

**Comment by ilinbxu** [comment]
> It's been fixed for Webmin 1.921+. You can have it updated using command:
> 
> ```shell
> yum update https://download.webmin.com/devel/rpm/webmin-1.921-1.noarch.rpm
> ```

Already the latest version

Webmin version | 1.921 | Usermin version | 1.771
Virtualmin version | 6.07 | Authentic theme version | 19.38

**Comment by rostovtsev** [comment]
That shouldn't be happening on CentOS for sure.

Have you tried restarting Webmin?

Do you have any custom kurnels installed?

**Comment by ilinbxu** [comment]
System information screenshot
https://www.scall.xyz/rtx.jpg

The system has been restarted many times, including webmin

**Comment by rostovtsev** [comment]
Okay, I have done the tests on _**exactly**_ the same machine as yours, and it seems to work.

#### Example [(link to fast-forward the video)](https://authentic-theme.com/src/19.38/working_post_kernel_install_reboot_alert_and_after_reboot.webm)

![working_post_kernel_install_reboot_alert_and_after_reboot](https://user-images.githubusercontent.com/4426533/62616114-703dde80-b917-11e9-9b74-1e8e6a40f8f3.gif)



#### Looking for cause

What is the output of the following commands:

1. 

~~~Bash
rpm -q kernel --qf "%{INSTALLTIME}\n"
~~~

2. 

~~~Bash
sed -n '/^btime /s///p' /proc/stat
~~~

3. 

~~~Bash
rpm -q kernel-3.10.0-957.27.2.el7.x86_64
~~~

**Comment by ilinbxu** [comment]
After entering your command, restart the server, the prompt has disappeared, thank you very much!

[root@somick ~]# rpm -q kernel --qf "%{INSTALLTIME}\n"
1564978899
1565068905
[root@somick ~]# rpm -q kernel
kernel-3.10.0-957.el7.x86_64
kernel-3.10.0-957.27.2.el7.x86_64
[root@somick ~]# sed -n '/^btime /s///p' /proc/stat
1565060986
[root@somick ~]# rpm -q kernel-3.10.0-957.27.2.el7.x86_64
kernel-3.10.0-957.27.2.el7.x86_64

**Comment by rostovtsev** [comment]
Very interesting.

Okay, anyway, it was pleasure to assist you. Good luck.

**Comment by IntrovertedFL** [comment]
@iliaross I am using Centos7 LXC on Proxmox, is it because the lxc uses the debian kernal I get error? ``` Warning!
Recent package updates (such as a new kernel version) require a reboot to be fully applied.```

**Comment by rostovtsev** [comment]
@TechGuyTN 


What is the output of the following commands:

1. 

~~~Bash
rpm -q kernel --qf "%{INSTALLTIME}\n"
~~~

2. 

~~~Bash
sed -n '/^btime /s///p' /proc/stat
~~~

3. 

~~~Bash
rpm -q kernel-3.10.0-957.27.2.el7.x86_64
~~~

**Comment by gstlouisgit** [comment]
@iliaross 
I have this problem as well.  I know for a fact that my provider cannot offer an updated kernel on the hosting platform I am on.
uname -r = 2.6.32-042stab128.2

could this problem be for me because I cannot update to the latest kernel?  This seem to have happened since some latest virtualmin update packages

**Comment by rostovtsev** [comment]
@gstlouisgit 


What is the output of the following commands:

1. 

~~~Bash
rpm -q kernel --qf "%{INSTALLTIME}\n"
~~~

2. 

~~~Bash
sed -n '/^btime /s///p' /proc/stat
~~~

3. 

~~~Bash
rpm -q kernel-3.10.0-957.27.2.el7.x86_64
~~~

**Comment by rostovtsev** [comment]
> Could this problem be for me because I cannot update to the latest kernel? This seem to have happened since some latest Virtualmin update packages.

Refer to the opened issue https://github.com/webmin/webmin/issues/1091#issuecomment-527096490 with the command output.

What is the output of the following commands:



1. 

~~~Bash
rpm -q kernel --qf "%{INSTALLTIME}\n"
~~~

2. 

~~~Bash
sed -n '/^btime /s///p' /proc/stat
~~~

3. 

~~~Bash
rpm -q kernel-3.10.0-957.27.2.el7.x86_64
~~~
