### ISSUE TITLE
File Manager: File edit doesn't let save files in Usermin (critical to fix before next release)

### ISSUE THREAD

**Issue by qooob** [webmin/webmin#548]
Jamie, with latest File Manager, there is a bug that doesn't let save files in _**Usermin**_.

It says:

`You are not allowed to access /.atconfig. The allowed directories are : /var/spool/mail/username , /var/spool/mail/username`.

I think it's been there for a long time as it has nothing to do with our recent changes.

It happens in Gray Theme as well.

**Comment by qooob** [comment]
Besides if doubles the allowed path in the notice making look strange.

**Comment by jcameron** [comment]
Fix submitted, will be included in webmin 1.840
