### ISSUE TITLE
Logrotate configuration. Create missing log files.

### ISSUE THREAD

**Issue by chris001** [webmin/webmin#552]
Couldn't Virtualmin be fixed to just work, by `touch`ing these missing files by itself, so that you don't have to manually go to the command line two times, and enter the touch command for each file ?

```
Failed to save enabled features : Current logrotate configuration is not valid :

error: stat of /var/log/virtualmin/server6.mydomain.com_access_log failed: No such file or directory

. This must be fixed, or log file rotation will not be done.
```

```
Failed to save enabled features : Current logrotate configuration is not valid :

error: stat of /var/log/virtualmin/server6.mydomain.com_error_log failed: No such file or directory

. This must be fixed, or log file rotation will not be done.
```

**Comment by jcameron** [comment]
Yesss ... but they should never be missing in the first place, unless there is some bug in which an old incorrect logrotate config file was left around.

Is this a deleted domain, or does it still exist on your system?

**Comment by chris001** [comment]
> Is this a deleted domain, or does it still exist on your system?
Good question.  If I remember correctly... while troubleshooting a DNS issue, I deleted the virtual server, which was empty anyway, in order to see if recreating the virtual server would fix the issue.  It was the only virtual server in virtualmin.  Virtualmin bugged out and gave an error and didn't want to delete the last virtual server.  So maybe it left the logrotate config file around.

**Comment by jcameron** [comment]
Right, that seems like the real cause. The fix in this case is to delete the entries for those missing logs from logrotate.conf
