### ISSUE TITLE
1.840 upgrade: Use of uninitialized value in string eq at /usr/local/webmin/time/time-lib.pl line 23.

### ISSUE THREAD

**Issue by berni421** [webmin/webmin#553]
Upgrade Ubuntu 10.4 lts .... from 1.831

elbournb@test:~/webmin-1.840$ sudo ./setup.sh /usr/local/webmin
***********************************************************************
*            Welcome to the Webmin setup script, version 1.840        *
***********************************************************************
Webmin is a web-based interface that allows Unix-like operating
systems and common Unix services to be easily administered.

Installing Webmin from /home/elbournb/webmin-1.840 to /usr/local/webmin ...

***********************************************************************
Webmin uses separate directories for configuration files and log files.
Unless you want to run multiple versions of Webmin at the same time
you can just accept the defaults.

Config file directory [/etc/webmin]: 
Found existing Webmin configuration in /etc/webmin

Copying files to /usr/local/webmin ..
..done

Inserting path to perl into scripts..
..done

Creating start and stop scripts..
..done

Updating config files..
..done

Creating uninstall script /etc/webmin/uninstall.sh ..
..done

Changing ownership and permissions ..
..done

Running postinstall scripts ..
Use of uninitialized value in string eq at /usr/local/webmin/time/time-lib.pl line 23.
..done

Attempting to start Webmin mini web server..
Starting Webmin server in /usr/local/webmin
Pre-loaded WebminCore
..done

***********************************************************************
Webmin has been installed and started successfully. Use your web
browser to go to

  http://test:10000/

and login with the name and password you entered previously.

elbournb@test:~/webmin-1.840$ perl --version

This is perl, v5.10.1 (*) built for x86_64-linux-gnu-thread-multi

Copyright 1987-2009, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.

**Comment by jcameron** [comment]
This is harmless, but I'll fix it in the next webmin release.
