### ISSUE TITLE
bug in filter_chains code #551

### ISSUE THREAD

**Issue by gnadelwartz** [webmin/webmin#555]
there is a bug in my code #551 wich I didn't found while testing because I was using "direct" mode.
A fix is already in my local installation and will be checked in tomorrow.

In short: works only with direct mode, when "using save to file" mode filtered chains will be silently disacarded.

**Comment by jcameron** [comment]
OK, please send me the fix when you have it.

**Comment by gnadelwartz** [comment]
OK, fix is in pull request #557

**Comment by gnadelwartz** [comment]
UI changes should be also finished, pls review  #557 and #558
