### ISSUE TITLE
Detects mod_php on server using php-fpm.

### ISSUE THREAD

**Issue by chris001** [webmin/webmin#577]
`This virtual server is using the mod_php execution mode for PHP, such does not allow per-directory version selection.`
The virtual server is actually using `php-fpm`.
Debian 8 with latest version of virtualmin.

**Comment by jcameron** [comment]
Which page in Virtualmin are you seeing this on exactly?

**Comment by chris001** [comment]
It's shows that when you click under "Server Configuration", "PHP Versions".

**Comment by jcameron** [comment]
Ok, this is a misleading message - it should also say that version selection is not supported when FPM is in use. I'll fix that.

**Comment by chris001** [comment]
OK.  It's supposed to be possible to run multiple versions of PHP on FPM, it's just not implemented, right?
https://www.howtoforge.com/how-to-use-multiple-php-versions-php-fpm-and-fastcgi-with-ispconfig-3-ubuntu-12.10

**Comment by jcameron** [comment]
Right now, you can't. In theory we could implement multi-version support, but it's  complex due to the way FPM pools work.

**Comment by chris001** [comment]
When I rank the most wanted features added or bugs fixes, it looks like:
1. to add a feature for automatic https subdomain and shell script for dynamic host IP address update, something like this https://github.com/andreasscherbaum/bind-dynamic-dns-update
2. making the DNSSEC code so it's managed by BIND so the renew and key management are more bulletproof and don't serve expired keys and non-existent domains.
3. TLSA on all detected listening ports. Let server admin manually enter multiple hostnames per port for virtual hosts not detected by the software. Because the server is running services (varnish, nginx https proxy, icecast2) not detected or managed by Virtualmin and so the TLSA hostname and port combos need to be entered manually.
....
99. way at the bottom is multiple PHP versions on FPM!

**Comment by jcameron** [comment]
Interestingly, quite a few users do care about multiple PHP versions and want to run FPM mode.

**Comment by chris001** [comment]
I must represent the users who believe multiple PHP versions on FPM would be great to have but what's the point without first running high security automatically key managed DNSSEC with autonomous dyn dns server that cannot get owned easily by man-in-the-middle dns hijackers.

**Comment by labor4** [comment]
but is it needed to distinguish versions inside a single pool.d?
i ask because i think i did run different versions of php in different pool.d, "because" Virtualmin generated them based on the installed php versions at the time of generation.
to me it seemed that the different $version/pool.d/*.conf triggers started cleanly and separate.

sorry if the question is still huge, i cannot know really.
best
manu

**Comment by jcameron** [comment]
If we were to support multiple PHP versions in FPM mode, each version would have it's own pool.d directory.

**Comment by jbatun21564065** [comment]
I will ask this question, I hope it is not uncomfortable, and you can give me some solution with it, if possible

I am using a configuration of running centos 7 with this kernel
Linux 3.10.0-862.11.6.el7.x86_64 # 1 SMP x86_64 x86_64 x86_64 GNU / Linux

The FPM packages installed on machine is

rh-php56-php-fpm.x86_64 5.6.25-1.el7 @ centos-sclo-rh
rh-php71-php-fpm.x86_64 7.1.8-1.el7 @ centos-sclo-rh

the two FPM servers are running one on port 9000 to 5.6 and on other port 9900 to 7.1, but when I re-check the configuration, Webmin displayed the messages, " can not detect the FPM mode".

How can I solve it? some help, with this problems.
I will appreciate your help.

**Comment by jcameron** [comment]
Where are the config directories for these FPM servers?

**Comment by DeniR** [comment]
> Interestingly, quite a few users do care about multiple PHP versions and want to run FPM mode.
I'm want too.
Also, there is no individual php.ini per domain in fpm mode currently, want it too.
Can't use FCGId coz there is no single memory pool for OpCache and APCu, each php worker on single domain has own cache.
Please add php-fpm version select on all domains, it's more easy that domain based.

**Comment by jcameron** [comment]
Yes, we have an open feature request to support multiple PHP versions in FPM mode in Virtualmin, but it's fairly complex to implement.
