### ISSUE TITLE
Can't install version 1.650 on Ubuntu or Debian

### ISSUE THREAD

**Issue by immohuneke** [webmin/webmin#59]
When I open my Webmin home page on most of the half-dozen servers I manage, I get the following message:

Webmin version 1.650 is now available, but you are running version 1.630.

But clicking the "Upgrade Webmin Now" button just gives me:

No package signature verification done.
Failed to upgrade from www.webmin.com : Not a valid Webmin Debian package file

What's going on? One of the servers offered the upgrade via the standard package management function and this worked fine. So that one is on 1.650 now, while all the others remain on 1.630.

**Comment by swelljoe** [comment]
There's been no follow-up in 3+ years, so calling this one done.
