### ISSUE TITLE
Software Packages Updates: Source repo name

### ISSUE THREAD

**Issue by qooob** [webmin/webmin#603]
Hi, Jamie.

When the security update is coming, like kernel or other it's important not to replace the actual repo name (Source column) with label _Security_ only. It should rather be _repoName (Security)_. In some case situations, when it's a Security Update the repo name is replaced and it's hard to figure things out.
![screenshot from 2017-06-12 11-17-52](https://user-images.githubusercontent.com/4426533/27507479-d22eef5e-58d8-11e7-849f-fb163bdcd509.png)

Can you please make it like Updates (Security) or something you would think to be good enough but without wiping out the repo name?

**Comment by swelljoe** [comment]
Actually...looking at the source, I don't think "Updates" is actually the repo name either! It seems to get it from metadata for the packages rather than the repo it came from. I'll have to dig deeper to understand how that's actually getting its information, but I also tend to think repo name would be valuable.

**Comment by qooob** [comment]
_Updates_ is just the repo name that I have, it can be anything.

**Comment by jcameron** [comment]
Which Linux distro is this on? The meaning of that column varies widely between YUM and APT-based systems.

**Comment by qooob** [comment]
It's RHEL based but it's irrelevant as it shows _Security_ label only, overwriting the actual repo name, which should be preserved in my opinion.

**Comment by jcameron** [comment]
Good point ... I'll fix that.

**Comment by qooob** [comment]
How is it going to look now? I don't see how your patch will display both.

Maybe something like:

```Perl
$done->{$name}->{'source'} .= ' (security)';
```

**Comment by jcameron** [comment]
Currently then show up in red, and are displayed when security-only updates are selected.

**Comment by qooob** [comment]
Jamie, hi.

I give it a quick test so it could be included to upcoming 18.50.

First of all, line 289 in `yum-lib.pl` must also be replaced.

After doing it as well here is the output I'm getting. Like I expected it's just marked read which might be confusing for those that never used Webmin Software Package Updates module.

![screenshot from 2017-06-25 14-28-59](https://user-images.githubusercontent.com/4426533/27515736-5398cd82-59b3-11e7-9c00-0ecaf05dfce5.png)


What I propose is to replace lines 289 and 302 with `$done->{$name}->{'source'} .= ' (security)';` to have explanatory output, like this:

![screenshot from 2017-06-25 14-31-16](https://user-images.githubusercontent.com/4426533/27515744-70ebf1a2-59b3-11e7-9607-c43108d71c26.png)

**Comment by swelljoe** [comment]
Jamie has already tagged/released 1.850. We will probably need one more Webmin dev release before VM6 to address fail2ban issues, so it's likely it'll only be a few more days before another release.

I also like Ilia's suggestion here.

**Comment by qooob** [comment]
Jamie, it's still not implemented in 18.51. Could you please take a look?

**Comment by jcameron** [comment]
In 1.851, the original repo is shown - but you can select to show only security updates via links at the top of the page.

**Comment by qooob** [comment]
I'm not sure I understand what links you are talking about?

It's just a good practice, I believe, not to alter initial repo name. Now I don't see initial repo name (for example when using console and `dnf update` - I do). In Webmin it's replace with `Security` label and thus becomes ambiguous, as I can't define the source's name.

**Comment by jcameron** [comment]
In 1.851 the repo name shouldn't be replaced though. Note that the name comes from the `yum list` or `dnf list` commands, so if it appears as `security` there it will also in Webmin.

**Comment by qooob** [comment]
Yes, it's not. Thank you, Jamie. However, I think, having a label _Security_, along with repo name in red, would be great.

```Perl
$done->{$name}->{'source'} .= ' (security)';
```

**Comment by qooob** [comment]
Jamie, it seems that it's still not working correctly and overwrites repo name:

![screenshot from 2017-09-07 16-25-29](https://user-images.githubusercontent.com/4426533/30165634-69ac916a-93e9-11e7-9e64-52524ac9c30c.png)


Here is how it looks on the console:

![screenshot from 2017-09-07 16-27-47](https://user-images.githubusercontent.com/4426533/30165681-9a8a4750-93e9-11e7-9603-18bdef28911b.png)


Is there a way not to overwrite actual repo name? It would be preferable if it would write 

`RepoName (Security)`, e.g. `Updates (Security)`.

**Comment by jcameron** [comment]
Ok, I found another case in which the source is being incorrectly over-ridden. It will be fixed in the next release.
