### ISSUE TITLE
majordomo docu on http://doxfer.webmin.com

### ISSUE THREAD

**Issue by gnadelwartz** [webmin/webmin#607]
Hi Jamie,

afer my recent changes (and may be before) the majordomo documentaion on http://doxfer.webmin.com is outdated.

If I can have edit access I would volunteer to start updating and hopefully remove the unmaintained message, as I will take care about the module :-)

**Comment by swelljoe** [comment]
I'll see if I can create an account for you.

**Comment by swelljoe** [comment]
OK, figured it out. Is there an email address I can send the credentials to?

**Comment by gnadelwartz** [comment]
on github you cant send a pm, or i did not find it.

**Comment by swelljoe** [comment]
OK, I've created an account for you. You should hopefully receive an email with a temporary password. Let me know if it doesn't show up in the next few minutes (I disabled account creation a few months back so I don't know for sure that all the parts are working right now, but I think they are).

**Comment by gnadelwartz** [comment]
i got the mail and can login, but whenmforce to change password i got a database error
[WVndtg5Qr37PrBvQXq1kWgAAAAI] 2017-07-03 06:01:26: Fataler Ausnahmefehler des Typs „DBQueryError“

**Comment by gnadelwartz** [comment]
on an other pc I noticed that the login dialog is unencrypted...(no https)

**Comment by gnadelwartz** [comment]
i cant login because i get an database error, see above

**Comment by swelljoe** [comment]
Oh, right, sorry. I saw this earlier while in the middle of something but never got back to looking at it. I'm looking into it now.

**Comment by gnadelwartz** [comment]
no hurry, i'm on vacation now 😀

**Comment by swelljoe** [comment]
Fixed! Database needed updating after the last MediaWiki update. I didn't even know update.php existed. MediaWiki is a little bit more opaque about stuff like that than I'd like at times. 

Also, SSL is enabled for the site. It's not redirecting yet, but you can hit https://doxfer.webmin.com and it'll be secured with a Let's Encrypt cert. I'll setup a redirect shortly.

Thanks for the heads up!

**Comment by gnadelwartz** [comment]
thanks, now i can login and change my password.
nevertheless, after login on  https you are redirected to http and i was wondering why im not logged in uhtil noticed the redirect.

**Comment by gnadelwartz** [comment]
can you please give me edit rigths for majordomo listmanager
https://doxfer.webmin.com/Webmin/Majordomo_List_Manager

**Comment by gnadelwartz** [comment]
next problem, I started translating the modules list and was able to save individual german translations.
butwhen leaving the page the message you have unsaved translations appears and i cant save. afterwards eve4thing was lost

**Comment by swelljoe** [comment]
Damn, there's a lot of stuff broken now with the mediawiki install! I guess recent updates have borked it up pretty good. I'm looking into it (but I can't login anymore, so that's fun). ;-)

**Comment by swelljoe** [comment]
OK, I've granted your Bureaucrat rights which means you should be able to do anything you need with pages. But, it sounds like there are other problems (and the session problem I found...I was able to work around that by using a different browser). Weird, as it's not giving errors in the log for any of this stuff, it's just not working.

**Comment by swelljoe** [comment]
Oh, I see what's happening. Sessions can't cross http/https! What a silly thing. And, you mentioned it above, even. I guess I need to get that redirect happening.

**Comment by swelljoe** [comment]
OK, there's now a redirect in place, so session weirdness should be gone. And, I think you have the privileges you need to edit/create/etc. Thanks for updating docs and for letting me know about the problems you ran into! Let me know if you find any new problems. I think I have handled everything that's been brought up in this issue so I'm gonna close it. You can start a new one for any new problems that pop up (and, I'm gonna poke around to make sure nothing obvious is still broken).

**Comment by gnadelwartz** [comment]
thanks alot and yes media wiki is a strange beast ☺
