### ISSUE TITLE
Error setting LanguagePriority to default in Apache Webserver module

### ISSUE THREAD

**Issue by Gulpy** [webmin/webmin#608]
> Operating system: CentOS Linux 7.3.1611
> Webmin version: 1.850
> Apache version: 2.4.6

Go into the Apache Webserver module, select Default Server, open Languages, set "Language priority for multi-views" to Default, Save, Apply Changes. The following error is then given:
```
AH00526: Syntax error on line 381 of /etc/httpd/conf/httpd.conf:
LanguagePriority requires at least one argument, space-delimited list of MIME language abbreviations
```
Putting one language in the "Language priority for multi-views" box such as "en" fixes this, however the "default" option does not work, at least not on my setup.

**Comment by jcameron** [comment]
Thanks - this will be fixed in the next Webmin release.
