### ISSUE TITLE
System Logs: Configuration option to reverse log output

### ISSUE THREAD

**Issue by qooob** [webmin/webmin#614]
Hi, Jamie.

It would be convenient to read log from top to bottom. The way it is now is that you have to scroll down each time after reload.

I could probably do this on the theme side but I think it's better to try to add it to the core functionality.

**Comment by jcameron** [comment]
Good suggestion ... I will add a config option for this.

**Comment by qooob** [comment]
Simply great, thanks!

**Comment by qooob** [comment]
Jamie, you forgot to add `tac` command onto search. When using search in the log, this new option is disrespected.

**Comment by qooob** [comment]
Adding the following to line 98 of _/syslog/save_log.cgi_ does things right:

```Perl
if ($config{'reverse'}) {
	$tailcmd .= " | tac";
}
```

**Comment by jcameron** [comment]
Thanks, I'll fix that
