### ISSUE TITLE
Webmin 1.850 behind Apache Reverse Proxy

### ISSUE THREAD

**Issue by thealliancenetwork** [webmin/webmin#615]
I have Apache setup with HTTPS and reverse proxying to Webmin which has SSL switched off.

I followed https://doxfer.webmin.com/Webmin/Running_Webmin_Under_Apache to do this.

Webmin seems to try and return 302's in some circumstances to http://myfqdn:10000 when it should be https://mfqdn:443 it's generally actions like Login or Create directory or Chown etc.

Example from login page

```
POST https://MYFQDN/webmin/session_login.cgi HTTP/1.1
Accept: text/html, application/xhtml+xml, */*
Referer: https://MYFQDN/webmin/
Accept-Language: en-GB
User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; rv:11.0) like Gecko
Content-Type: application/x-www-form-urlencoded
Accept-Encoding: gzip, deflate
Host: MYFQDN
Content-Length: 46
Connection: Keep-Alive
Cache-Control: no-cache
Cookie: redirect=1; testing=1

user=REMOVED



HTTP/1.1 302 Moved Temporarily
Date: Thu, 27 Jul 2017 11:49:13 GMT
Server: MiniServ/1.850
Location: http:// MYFQDN:10000/
Set-Cookie: sid=REMOVED; path=/; expires="Thu, 31-Dec-2037 00:00:00"; httpOnly
Keep-Alive: timeout=5, max=100
Connection: Keep-Alive
Transfer-Encoding: chunked

0


```

Apache Config
```
ProxyPass /webmin/ http://localhost:10000/
ProxyPassReverse /webmin/ http://localhost:10000/

ProxyPassReverseCookieDomain /webmin/ http://localhost:10000/
ProxyPassReverseCookiePath /webmin/ http://localhost:10000/
```

Webmin Config
```
webprefix=/webmin
webprefixnoredir=1
referer=MYFQDN
```

Miniserv Config
```
ssl=0
ssl_redirect=0
```

I think it's down to line 4074 - 4105 in the miniserv.pl file

I have managed to work around this by adding in the below.
ProxyPassReverse /webmin/ http://MYFQDN:10000/

**Comment by qooob** [comment]
You don't have to disable SSL, it's possible to make it work by adding above _ProxyPass_:

```Config
SSLProxyEngine On
SSLProxyVerify None 
SSLProxyCheckPeerCN Off
SSLProxyCheckPeerName Off
SSLProxyCheckPeerExpire Off
```

Try to change your config a little bit and restart Apache:

```Config
RewriteRule ^/webmin$ /webmin/ [R]
ProxyPass "/webmin" "https://localhost:10000"
ProxyPassReverse "/webmin" "https://localhost:10000"
```

In case it still doesn't work, try, edit `/etc/webmin/config` with the following:

```Config
referer=webmin
```

.. and `/etc/webmin/miniserv.conf`:

```Config
ssl=1
ssl_redirect=1
```

**Comment by ionbasa** [comment]
I seem to have the exact same issue. I have my apache reverse proxy set up correctly, albeit with Webmin's SSL on. The issue arises whenever I log out, then if I try logging back in get a 302 to "localhost:10000" instead of "FQDN/webmin". Theme is Authentic theme, I don't recall this happening on the older theme.

**Comment by qooob** [comment]
Upcoming version of the theme 19.00-RC8, will have proxy fixes.

When it's ready, I'll let you know. Most likely, within 24 hours.

**Comment by qooob** [comment]
@ionbasa Please try theme Version [19.00-RC8](https://github.com/qooob/authentic-theme/releases/download/19.00-RC8/authentic-theme-19.00-RC8.wbt.gz).

**Comment by ionbasa** [comment]
Logging out seems to be much better now. 

Logging in still an issue. I cleared browser cookies and restarted the webmin miniserver before trying it out. After entering my login credentials, I still get redirected to "localhost:10000". Retyping in "FQDN/webmin" in the browser then takes me to webmin properly.

**Comment by qooob** [comment]
Are you saying that you login from `FQDN/webmin` and get redirected to `localhost:10000`? That is strange. Are you 100% sure that the same _**doesn't**_ happens in _Gray Theme_? In case it does you probably forgot to add one or two things on the `config` and `miniserv.conf`.

Can you please switch to _Gray Theme_ and tell me how it is?

**Comment by ionbasa** [comment]
Interesting, the same thing happens on Gray Theme. I followed the instructions "Webmin In A Sub-Directory Via A Proxy" from: http://www.webmin.com/apache.html

The miniserve.conf file has:
`cookiepath=/webmin`

and webmin/config has:
```
webprefix=/webmin
webprefixnoredir=1
referer=FQDN
```

My apache config looks like the following:
```
ProxyPreserveHost On
	SSLProxyEngine On
	SSLProxyVerify none
	SSLProxyCheckPeerCN off
	SSLProxyCheckPeerName off
	SSLProxyCheckPeerExpire off
    
	ProxyPass /webmin/ https://localhost:10000/
ProxyPassReverse /webmin/ https://localhost:10000/
```

**Comment by qooob** [comment]
Everything seems correct. I also remember having issues setting it up the first time using the manual. We should rewire and update it, I believe. We will do this as soon as we rework the whole _webmin.com_ website.

Right now, try what works for me.

For your _Apache_ config:

```Conf
RewriteRule ^/webmin$ /ucontrol/ [R]
ProxyPass "/webmin" "https://localhost:10000"
ProxyPassReverse "/webmin" "https://localhost:10000"
```

For your `/etc/usermin/config` try:

```Config
referers_none=1
referer=webmin
```

I don't remember why but in my case _FQDN_  didn't work as well.

Let me know if it helps.

**Comment by ionbasa** [comment]
Sorry, I should have specified more details, my apache conf includes those rewrite rules as well. I've adjusted the apache conf not to have a trailing slash in Proxypass andProxyPassReverse. I still seem to be getting the same issue. I've also changed the referer in the webmin config from FQDN to 'webmin'.

I noticed you're running usermin (bascause of the config file location you specified), I do not have usermin. Maybe there is some difference when running webmin instead of usermin?

**Comment by qooob** [comment]
@ionbasa I need to reproduce the problem first in order to fix it. 

Did you look at the logs? `/var/webmin/miniserv.error` for example.

**Comment by ionbasa** [comment]
Nothing interesting on my end in the error log for the past few days:
```
[08/Sep/2017:12:10:47 -0700] miniserv.pl started
[08/Sep/2017:12:10:47 -0700] IPv6 support cannot be enabled without the Socket6 perl module
[08/Sep/2017:12:10:47 -0700] Using MD5 module Digest::MD5
[08/Sep/2017:12:10:47 -0700] PAM authentication enabled
Use of uninitialized value $newoverlay in string ne at /usr/share/webmin/change-user/change.cgi line 79.
Use of uninitialized value $oldoverlay in string ne at /usr/share/webmin/change-user/change.cgi line 79.
Use of uninitialized value in split at /usr/share/webmin/acl/acl-lib.pl line 625.
[08/Sep/2017:12:16:43 -0700] Reloading configuration
Use of uninitialized value $newoverlay in string ne at /usr/share/webmin/change-user/change.cgi line 94.
Use of uninitialized value $oldoverlay in string ne at /usr/share/webmin/change-user/change.cgi line 94.
[08/Sep/2017:12:17:09 -0700] Reloading configuration
[08/Sep/2017:12:17:49 -0700] miniserv.pl started
[08/Sep/2017:12:17:49 -0700] IPv6 support cannot be enabled without the Socket6 perl module
[08/Sep/2017:12:17:49 -0700] Using MD5 module Digest::MD5
[08/Sep/2017:12:17:49 -0700] PAM authentication enabled
[08/Sep/2017:12:25:51 -0700] Reloading configuration
[08/Sep/2017:14:23:52 -0700] miniserv.pl started
[08/Sep/2017:14:23:52 -0700] IPv6 support cannot be enabled without the Socket6 perl module
[08/Sep/2017:14:23:52 -0700] Using MD5 module Digest::MD5
[08/Sep/2017:14:23:52 -0700] PAM authentication enabled
[08/Sep/2017:14:25:01 -0700] miniserv.pl started
[08/Sep/2017:14:25:01 -0700] IPv6 support cannot be enabled without the Socket6 perl module
[08/Sep/2017:14:25:01 -0700] Using MD5 module Digest::MD5
[08/Sep/2017:14:25:01 -0700] PAM authentication enabled
[08/Sep/2017:14:27:44 -0700] miniserv.pl started
[08/Sep/2017:14:27:44 -0700] IPv6 support cannot be enabled without the Socket6 perl module
[08/Sep/2017:14:27:44 -0700] Using MD5 module Digest::MD5
[08/Sep/2017:14:27:44 -0700] PAM authentication enabled
[08/Sep/2017:12:10:47 -0700] miniserv.pl started
[08/Sep/2017:12:10:47 -0700] IPv6 support cannot be enabled without the Socket6 perl module
[08/Sep/2017:12:10:47 -0700] Using MD5 module Digest::MD5
[08/Sep/2017:12:10:47 -0700] PAM authentication enabled
Use of uninitialized value $newoverlay in string ne at /usr/share/webmin/change-user/change.cgi line 79.
Use of uninitialized value $oldoverlay in string ne at /usr/share/webmin/change-user/change.cgi line 79.
Use of uninitialized value in split at /usr/share/webmin/acl/acl-lib.pl line 625.
[08/Sep/2017:12:16:43 -0700] Reloading configuration
Use of uninitialized value $newoverlay in string ne at /usr/share/webmin/change-user/change.cgi line 94.
Use of uninitialized value $oldoverlay in string ne at /usr/share/webmin/change-user/change.cgi line 94.
[08/Sep/2017:12:17:09 -0700] Reloading configuration
[08/Sep/2017:12:17:49 -0700] miniserv.pl started
[08/Sep/2017:12:17:49 -0700] IPv6 support cannot be enabled without the Socket6 perl module
[08/Sep/2017:12:17:49 -0700] Using MD5 module Digest::MD5
[08/Sep/2017:12:17:49 -0700] PAM authentication enabled
[08/Sep/2017:12:25:51 -0700] Reloading configuration
[08/Sep/2017:14:23:52 -0700] miniserv.pl started
[08/Sep/2017:14:23:52 -0700] IPv6 support cannot be enabled without the Socket6 perl module
[08/Sep/2017:14:23:52 -0700] Using MD5 module Digest::MD5
[08/Sep/2017:14:23:52 -0700] PAM authentication enabled
[08/Sep/2017:14:25:01 -0700] miniserv.pl started
[08/Sep/2017:14:25:01 -0700] IPv6 support cannot be enabled without the Socket6 perl module
[08/Sep/2017:14:25:01 -0700] Using MD5 module Digest::MD5
[08/Sep/2017:14:25:01 -0700] PAM authentication enabled
[08/Sep/2017:14:27:44 -0700] miniserv.pl started
[08/Sep/2017:14:27:44 -0700] IPv6 support cannot be enabled without the Socket6 perl module
[08/Sep/2017:14:27:44 -0700] Using MD5 module Digest::MD5
[08/Sep/2017:14:27:44 -0700] PAM authentication enabled
```

Seems there's an issue with IPv6 and not having the proper Pearl module installed. Interesting, i'll try disabling IPv6 and see if it makes a difference.

**Comment by ionbasa** [comment]
Just a follow up, this isn;t an isolated incident
See: https://github.com/webmin/webmin/issues/351
https://github.com/webmin/webmin/issues/350
https://sourceforge.net/p/webadmin/discussion/600155/thread/6eb89f60/

It seems there is a fundamental error in the way the miniserver handles login redirects. I have added a pull request: https://github.com/webmin/webmin/pull/627

It seems line 4099 is the issue, specifically `&write_data("Location: $prot://$hostport$in{'page'}\r\n");`
The variable $hostport does not seem to obey the fact that the the webprefix flag is set! I believe this means that at login, the listen port (10000) is inserted to the URL such that it appears as "hostname:10000' instead of 'hostname/webmin". I think the fix should work, but not sure what happens for people not running behind a reverse proxy, or what happens when a listen port other than 10000 is used. This is something you guys need to look into and fix.

**Comment by ionbasa** [comment]
Having setting the following directive in my Apache config fixed all my issues: `ProxyPreserveHost` to off. Having it set to on will break redirects at login.

**Comment by qooob** [comment]
Good to know.

Issue is resolved then.

**Comment by gene1wood** [comment]
I can confirm that the only thing that fixed this for me is @ionbasa 's suggestion to add

```
ProxyPreserveHost off
```

To my apache virtualhost config

**Comment by sergiomb2** [comment]
Hum with centos 7 selinux block proxy 
aureport -a shows :
27-04-2018 15:45:54 httpd system_u:system_r:httpd_t:s0 42 tcp_socket name_connect system_u:object_r:unreserved_port_t:s0 denied 782

/usr/sbin/setsebool -P httpd_can_network_connect 1
but now 

tail -f  /var/webmin/miniserv.error 

Failed to initialize SSL connection

**Comment by Globerada** [comment]
Hi.

My problem was after following this tutorial:

https://www.digitalocean.com/community/tutorials/how-to-install-webmin-on-ubuntu-18-04

For instance, I want webmin to be under: https://webmin.example.com, but also, https://www.example.com is a production web server.

After that, whenever I add a new domain with SSL (for instance, https://www.example.com), it messes up my webmin address (https://webmin.example.com) and points it to the new domain directory I just created. 

I solved changing VirtualHost from <VirtualHost *:443> to <VirtualHost publicIP:443> from the apache config of webmin

**Comment by iwikus** [comment]
I have found this issue with haproxy as frontend and webmin as backed. Using webmin discusion https://sourceforge.net/p/webadmin/discussion/600155/thread/6eb89f60 I had found solution for haproxy:

```
backend webmin
        mode http
        option forwardfor
        http-request set-header X-Forwarded-Port %[dst_port]
        http-request set-header X-Forwarded-Proto https if { ssl_fc }
        #fix stupid login redirect port problem
        http-response replace-value Location (.*):.* \1
        server webmin 127.0.0.1:10000 ssl verify none

```

**Comment by Taomyn** [comment]
@iwikus I just tried your solution but it only partially works - the login page finally redirects later but some other links within Webmin fail, e.g. System, Running processes now tries to go to: https://webmin.domain.com/proc/:10000/proc/index_cpu.cgi?&xnavigation=1

**Comment by BobWs** [comment]
Having the same problem. I'm using webmin on Debian VM on a Synology NAS with nginx reverse proxy and everything works fine except when logging in. When I login I'm redirected to webmin.mydomain.com:10000 I have to manually the port-number
Anyone know hw to fix this for nginx reverse proxy?

**Comment by iliarostovtsev** [comment]
`/etc/webmin/miniserv.conf` file has an applicable option `redirect_host`, try using it.

**Comment by BobWs** [comment]
> `/etc/webmin/miniserv.conf` file has an applicable option `redirect_host`, try using it.

So What should I put in there? 
This `redirect_host=webmin.mydomain.com`?

**Comment by BobWs** [comment]
I have added `redirect_host=webmin.mydomain.com` to `/etc/webmin/miniserv.conf` but it doesn't help it keeps redirecting me to `webmin.mydomain.com:10000` after login

**Comment by iliarostovtsev** [comment]
Have you restarted Webmin using `/etc/webmin/restart` command?

**Comment by BobWs** [comment]
> Have you restarted Webmin using `/etc/webmin/restart` command?

Yes

**Comment by iliarostovtsev** [comment]
What if you set `redirect_port` as well to `443` or `80` depending on your setup?

**Comment by BobWs** [comment]
> redirect_port

Yes Thanks! That worked for me!

So recap I've added 
`redirect_host=webmin.mydomain.com` and
`redirect_port=80` to `/etc/webmin/miniserv.conf` restarted webmin and no-more redirect to `webmin.mydomain.com:10000`

Thank you!
