### ISSUE TITLE
INFO: Freebsd Version

### ISSUE THREAD

**Issue by jwhulette** [webmin/webmin#616]
Just dropping this here for information purposes since I don't know how the Kernel / CPU info is obtained.

**uname(1) shows the version as compiled into the kernel itself. If you use a binary update tool like freebsd-update(1), and the patch is in a userland program, then the kernel isn't touched and the patch level shown by uname(1) doesn't increment.**

**This was causing confusion, so they came out with the freebsd-version(8) tool. This shows the current patch level of the OS, and is incremented any time a patch is applied, whether it be via freebsd-update(8) or a manual compilation process.**

**Thus, only if you use the buildworld process for keeping the system up-to-date, should you use uname(1), as that's the only way to keep the data current. For all other setups, use freebsd-version(1).**

**Or, just always use freebsd-version(1) to keep things simple.**
ref: [https://forums.freebsd.org/threads/52005/](url)

If uname is used it can cause confusion after an update is applied.

**Comment by jcameron** [comment]
Webmin doesn't really care much about the kernel version - but it does care about userspace versions.

What exactly does the `freebsd-version` command output on your system?

**Comment by jwhulette** [comment]
$ freebsd-version
11.0-RELEASE-p10

**Comment by jcameron** [comment]
Thanks! Do all FreeBSD versions have this command, or was it only introduced recently?

**Comment by jwhulette** [comment]
It first appeared in Freebsd 10.

**Comment by jcameron** [comment]
Thanks - I'll use that if available in the next Webmin release.
