### ISSUE TITLE
[WIN] Launch error:  " Perl module Authen::PAM needed for PAM is not installed"

### ISSUE THREAD

**Issue by seanvree** [webmin/webmin#618]
OS:  WIndows 10E x64 1703

Got everything installed (not gracefully BTW), however when I try to launch the WebUI, PERL starts to listen on the port I have defined, but as soon as I try to navigate to the WebUI, the console displays this error:

```
Administrator@VreePlexDesktop MINGW64 /c/webmin
$ perl miniserv.pl /c/webmin/miniserv.conf
Pre-loaded web-lib-funcs.pl in main
Segmentation fault
```

 I get the following error in miniserv.error:

```
[16/Aug/2017:05:51:01 -0700] miniserv.pl started
[16/Aug/2017:05:51:01 -0700] Using MD5 module Digest::MD5
[16/Aug/2017:05:51:01 -0700] Perl module Authen::PAM needed for PAM is not installed : Can't locate Authen/PAM.pm in @INC (you may need to install the Authen::PAM module) (@INC contains: C:/Perl64/site/lib C:/Perl64/lib .) at (eval 15) line 1.
BEGIN failed--compilation aborted at (eval 15) line 1.

[16/Aug/2017:05:51:01 -0700] Random number generator file /dev/urandom is not reliable
Free to wrong pool 5a5c870 not 4957760 at miniserv.pl line 917.
```

I don't see a PERL package for Authen::PAM, or anything close?  

What am I missing?

**Comment by jcameron** [comment]
Wait, you are running on Windows? That is not a supported operating system anymore, sorry..

**Comment by seanvree** [comment]
@jcameron yes, I am running on windows.  Oh, well you guys should note that on your wiki:


http://www.webmin.com/windows.html

**Comment by swelljoe** [comment]
We used to have some people that helped maintain Windows support. We just don't have enough expertise there to keep it working well. We'd need more volunteers to keep Windows support alive. (And, yeah, the site should be updated to reflect that.)

**Comment by seanvree** [comment]
@swelljoe  - I'm VERY good at making shit work on Windows.  Shoot me a PM, I can maybe help out.
