### ISSUE TITLE
Disk Usage module (disk-usage) fails

### ISSUE THREAD

**Issue by chrispolley** [webmin/webmin#624]
Hi,
In a recent Perl version upgrade, the expression "defined(%hash)" is now unsupported (was previously deprecated from v5.6.1 AFAICT) (see http://perldoc.perl.org/functions/defined.html) and therefore disk-usage-lib.pl fails at line 203 on the statement "if (!defined(%skip_cache))".  

Changing this to "if (!(%skip_cache))" seems to work, but I am not a Perl expert and don't know what side effects this change might have.  I'll update the issue if I see anything.

Using perl 5, version 24, subversion 1 (v5.24.1) built for x86_64-linux-gnu-thread-multi

Thanks!

**Comment by qooob** [comment]
Where is this module?

**Comment by swelljoe** [comment]
It's an old non-core module Jamie made: http://www.webmin.com/download/modules/disk-usage.wbm.gz

Hasn't been updated in 12 years, as far as I can tell. I've never looked at it.

@chrispolley Does it do something that the disk usage reports in the dashboard (in Authentic and the framed theme) don't do?

**Comment by chrispolley** [comment]
Sorry, I was thinking this was core since it is distributed from the webmin server but I see now it is not.

It provides a tree view of usage, as in "du -d <n>" 

Is there another (core) module that does this?

Thanks!

**Comment by swelljoe** [comment]
Ah, OK, I can see how that'd be useful and I don't think there is any way to do it in core.

I'll try to fix it really quick (if it's a bear, I'll have to tap out, but if it's really just a one line change, I'll get it sorted, and make a github repo for it). File Manager could probably integrate that functionality, as well, but that's a lot more work than fixing this one module, probably.

**Comment by chrispolley** [comment]
It is in the webmin sources at https://github.com/webmin/webmin/tree/master/disk-usage, however I see this bug has been fixed there, probably before it was imported to git in 2011.  The version I have must have been from another repository.  Maybe this is just an issue of needing to update the wbm at http://www.webmin.com/cgi-bin/search_third.cgi?search=disk%20usage to the current module, or removing it from there so people don't overwrite new code with old as I seem to have done.

**Comment by swelljoe** [comment]
It's not in the Webmin distribution (tarball or packages); there's no risk of overwriting it. I guess Jamie developed it in the Webmin source tree, and it's just been carried into git from that practice. I've asked him to update the third party modules entry for it when he gets a chance.

**Comment by chrispolley** [comment]
Great, thanks!

**Comment by qooob** [comment]
I like this module.

Yes, adding it to File Manager sounds like a great improvement.

**Comment by jcameron** [comment]
Ok, a new version of that module is available at http://www.webmin.com/download/modules/disk-usage-1.2.wbm.gz

The functionality probably isn't suitable for the File Manager, as it relies on a cron job to update a cache of disk space used.

**Comment by swelljoe** [comment]
Yeah, I wouldn't want File Manager creating cronjobs. But, a realtime view of du output is a reasonable addition I think (e.g. Right-click->Show Usage or something along those lines, pops up a view of the disk usage for the selected directory, or maybe hide if behind some sort of advanced option).
