### ISSUE TITLE
Redirect when URL contains trigger

### ISSUE THREAD

**Issue by qooob** [webmin/webmin#632]
To upcoming release, we need to make little changes.

Anytime URL contains `xnavigation=1` is it possible to force redirection to main URL?

Example:

```Bash
https://debug-centos1.com/webmin/custom/?xnavigation=1 -> https://debug-centos1.com/webmin
```

or

```Bash
https://debug-debian:10000/bind8/?xnavigation=1 -> https://debug-debian:10000
```

**Comment by qooob** [comment]
https://github.com/qooob/authentic-theme/issues/848
https://github.com/qooob/authentic-theme/issues/844

**Comment by jcameron** [comment]
Is this a change we need to make in Webmin?

**Comment by qooob** [comment]
Not anymore. I will try to make it work on the theme side.

**Comment by qooob** [comment]
It happens to be crucial.

Please merge:
https://github.com/webmin/webmin/pull/652
