### ISSUE TITLE
Port needed for Master/slave replication

### ISSUE THREAD

**Issue by Extarys** [webmin/webmin#634]
Hey!

So I had a strange error while trying to add a Cluster Slave Server, I disabled my firewall and it worked.

Port 10000 is open. I read I had to open port 10014 too but I still had the error even open.
Should I need another port?

Thanks.

**Comment by swelljoe** [comment]
You need 1000:10010 for fast RPC in Webmin; though it should fall-back if the other ports aren't available (I thought). Not sure what 10014 would be for. Obviously, you also need the DNS port (53) to allow both TCP and UDP for zone transfers.

**Comment by Extarys** [comment]
i need 1000 to 10000 ? OMG that is  a huge hole in the wall :P, you sure?

**Comment by jcameron** [comment]
I think what Joe meant was 10000 to 10100

**Comment by Extarys** [comment]
Oh that make a lot more sense, ok thanks I'll try that! Thank you @jcameron

**Comment by swelljoe** [comment]
Jamie, is it actually 100 ports? I thought it cycled through 10.

**Comment by jcameron** [comment]
It's as many as there are concurrent RPC channels - I recommended 100 just to be safe.

**Comment by Extarys** [comment]
TCP only right?

**Comment by Extarys** [comment]
I'll close as this is now off topic
