### ISSUE TITLE
[Improvement] Hide items in menu

### ISSUE THREAD

**Issue by Extarys** [webmin/webmin#635]
I usually install webmin for a couple of features, it should be nice to hide all the stuff I don't use.

Right now I have one installation to manage Bind9 on two servers, and one installation only to monitor cpu usage.. It's nice to have many options but sometimes it's too much when you only need a couple of features.

Also, any plans on supporting nginx?

**Comment by swelljoe** [comment]
nginx is well-supported in Virtualmin, but it does require Virtualmin to work (though it does have a proper nginx UI, as well, similar to the Apache module in Apache...not sure why that bit depends on Virtualmin, actually...it might be possible to exract it into a standalone Webmin module).

**Comment by Extarys** [comment]
Oh ok - I didnt install Virtualmin because it install everything and I like to have only a couple of thing per server... but I'll see. Thanks!!

**Comment by swelljoe** [comment]
That's valid. Virtualmin is very large, and if you only want to manage one service (nginx), it doesn't make sense to pile on the whole thing. It's reasonable to want a standalone module. I don't know how easy it is to split it out, though. I haven't actually looked at the code. Jamie might have thoughts on that.

And, I didn't answer your initial question: To hide modules you don't want, just remove them from your ACLs in the Webmin Users module. You can unselect all of the modules you don't want to see. There are other ways to do it, but this won't be affected by upgrades or other changes.

**Comment by Extarys** [comment]
Yea it all depends how hard coded everything is uynderneath
