### ISSUE TITLE
Debian stretch php7.0

### ISSUE THREAD

**Issue by dedetok** [webmin/webmin#642]
Location php.ini (PHP 7.0) on Debian 9 (Stretch) has change. The new folder is:
/etc/php/7.0/apache2/php.ini=Configuration for mod_php
/etc/php/7.0/cgi/php.ini=Configuration for scripts run via CGI
/etc/php/7.0/cli/php.ini=Configuration for command-line scripts

**Comment by jcameron** [comment]
Virtualmin should already detect these PHP ini file paths, if you're using PHP 7.

**Comment by dedetok** [comment]
yes. php 7.0.
