### ISSUE TITLE
Webmin Version 1.860 Changes?

### ISSUE THREAD

**Issue by war59312** [webmin/webmin#655]
Hi,

Seems Webmin Version 1.860 has been out for a few days.

But version changes info missing from http://www.webmin.com/changes.html .

Also, http://www.webmin.com/changes-1.860.html is basically blank.

Thanks,

Will

**Comment by jcameron** [comment]
Sorry, I forgot to update the website! You can check out http://www.webmin.com/changes.html now.

**Comment by war59312** [comment]
Thanks!
