### ISSUE TITLE
FreeBSD CPU Graph is showing incorrect 

### ISSUE THREAD

**Issue by jwhulette** [webmin/webmin#659]
The CPU graph is showing the wrong CPU percentage.
![31778666-3da2effa-b4bf-11e7-99da-e2549a4aac44](https://user-images.githubusercontent.com/4930051/31781647-ffc8aa1e-b4c6-11e7-8af6-a3875564f751.png)

**Comment by jcameron** [comment]
What does the command `vmstat 1 2` output on your system when the CPU is shown as 111% ?

**Comment by qooob** [comment]
Here is my output of `vmstat 1 2`

```Bash
root@debug-freebsd:~ # vmstat 1 2
procs  memory       page                    disks     faults         cpu
r b w  avm   fre   flt  re  pi  po    fr   sr ad0 cd0   in    sy    cs us sy id
0 0 0 660M  1.7G  1019   0   3   0  1047   18   0   0   36  1801   314  0  0 99
0 0 0 660M  1.7G     3   0   0   0     0   23   0   0   10   126   143  0  0 100
```

I also have funky CPU usage data:

![debug-freebsd_10000_](https://user-images.githubusercontent.com/4426533/31881929-d950c9a0-b7ed-11e7-98e7-49ad602d1e6a.png)

**Comment by jwhulette** [comment]
$ vmstat 1 2
procs  memory       page                      disks   faults         cpu
r b w  avm   fre   flt  re  pi  po    fr   sr ad0   in    sy    cs us sy id
0 0 0 1.1G  1.0G  1311   0   0   0  1290   71   0  636  1245  1082  2  1 97
0 0 0 1.1G  1.0G     3   0   0   0     0   60   1   48   133    97  0  0 100

**Comment by jwhulette** [comment]
$ vmstat 1 2
procs  memory       page                      disks   faults         cpu
r b w  avm   fre   flt  re  pi  po    fr   sr ad0   in    sy    cs us sy id
0 0 0 1.1G  1.0G  1311   0   0   0  1290   71   0  636  1245  1082  2  1 97
0 0 0 1.1G  1.0G     3   0   0   0     0   60   1   48   133    97  0  0 100

**Comment by jcameron** [comment]
Ok, I've just checked in a patch for inclusion in the next Webmin release that will fix this.

**Comment by qooob** [comment]
Great, works correctly on my FreeBSD. Thanks, Jamie.
