### ISSUE TITLE
CHANGELOG not up to date

### ISSUE THREAD

**Issue by swelljoe** [webmin/webmin#660]
The CHANGELOG hasn't been updated since 1.790. I know it's on the website, but it's probably misleading to have an unmaintained one in the repo. I could go through and bring the ones from the website over, but if there's an automated process for updating it that is just broken and can be fixed, I won't bother with it.

**Comment by jcameron** [comment]
Which specific CHANGELOG file is this?

**Comment by swelljoe** [comment]
https://github.com/webmin/webmin/blob/master/CHANGELOG

**Comment by jcameron** [comment]
Oh, ok ... due to the strange structure of our CHANGELOG files, this one is only used for changes made outside of any module. So it's normal that it hasn't been updated recently.

**Comment by swelljoe** [comment]
OK, I'll close this, since it seems like it's expected, and I see it isn't included in the distribution, so it's not harmful. Maybe one of these days we can automate updating it for every release.

**Comment by qooob** [comment]
It is confusing to keep that CHANGELOG file at all and have it outdated. It's either should be removed or updated according. I was one of those confused ones when looking at it months ago.
