### ISSUE TITLE
Updating "Network Interfaces" Configuration Removes Call to Firewall Script

### ISSUE THREAD

**Issue by JaredF** [webmin/webmin#662]
To reproduce:

Under the module **Linux Firewall** select to **Activate at boot**

The line **post-up iptables-restore < /etc/iptables.up.rules** now appears under the Ethernet interface configuration.

Now under the module **Network Configuration** option **Network Interfaces**, select the corresponding interface and click the **Save and Apply** button.

The line **post-up iptables-restore < /etc/iptables.up.rules** is now missing from the interface configuration.

**Comment by jcameron** [comment]
That sounds like a bug! Which Linux distribution and version are you running there?

**Comment by JaredF** [comment]
Sorry; should have included that info.  I am running Ubuntu Zesty (17.04) Server x64 and the Webmin version is 1.860.

**Comment by jcameron** [comment]
Thanks - this will be fixed in the next Webmin release.
