### ISSUE TITLE
check for correct version of ip(6)tables.save file

### ISSUE THREAD

**Issue by gnadelwartz** [webmin/webmin#667]
after updating from github changing protcol in firewall seems to be broken.
I'll investigate whats going wrong and provide a fix

**Comment by gnadelwartz** [comment]
Hi again, it was simply dcause the ip6tables.save file had the content of iptables.save.
Strange, how this can happen?

After deleting firewall6 reads the actual config from ip6tables and offers to save them in the file.
May be we should implement a check for the correct version on the first line of the file:

# Generated by iptables-save v1.4.21 on Wed Nov  1 11:16:20 2017
# Generated by ip6tables-save v1.4.21 on Wed Nov  1 11:16:06 2017

**Comment by jcameron** [comment]
Is the problem that the IPv6 Firewall module was editing the IPv4 firewall config?

**Comment by gnadelwartz** [comment]
this was also my first thought, but it was much simpler.
the /etc/webmin/firewall6/ip6tables.save file had the content from ipv4 :(
atter deleting the ipv6 save file everything works as expected.

this may or may not related, but this happened after an updatefrom 8.60 to the latestversion from gihub.

**Comment by gnadelwartz** [comment]
a simple check can be running `iptables --test` against the saved file wnd display a warming if an error occours, like its d9ne in kubernets https://github.com/kubernetes/kubernetes/issues/36850

**Comment by jcameron** [comment]
There was a period during which the contributed code in github for this module was incorrect, which may have caused this.
