### ISSUE TITLE
Webmin using incorrect slashes for CIFS

### ISSUE THREAD

**Issue by evil666** [webmin/webmin#68]
Also it seems Webmin is using incorrect slashes for CIFS. Example:
\example\examp /blah/blah cifs uid=.....etc
when it should be
//example/examp /blah/blah cifs uid=.....etc

Using incorrect slashes prevents CIFS from mounting on next reboot.

**Comment by shoulders** [comment]
this should be closed becasue @jamie says

> Ok, I see the bug now - this will be fixed in the next Webmin release. Thanks for your persistence!
