### ISSUE TITLE
System Logs: Log unescape escaped characters

### ISSUE THREAD

**Issue by qooob** [webmin/webmin#686]
Hi, Jamie.

When reading Apache log files and looking into escaped URL, they look like:

```
1.2.3.4 - - [01/Nov/2017:01:01:01 +1200] "GET /dir/%D0%94%D0%B6%D1%83%D0%BD%D1%80%D0%BE%20%D0%A8%D0%BE%D0%B4%D0%B0%D0%BD-%D0%9D%D0%B8%D0%B4%D0%B0%D0%BD%20.mp4 HTTP/1.1" 200 11595582 ..
```

This is practically useless. Is there a way to convert it to human-readable format:

```
1.2.3.4 - - [01/Nov/2017:01:01:01 +1200] "GET /dir/Джунро Шодан-Нидан .mp4 HTTP/1.1" 200 11595582 ..
```

It's okay if it's optional in System Log configurations.

**Comment by jcameron** [comment]
That would be dangerous, as it could allow HTML from HTTP requests to be displayed un-escaped in Webmin. Better to show the logs as they actually are..

**Comment by qooob** [comment]
Jamie, we could `escape_html()` on decoded string or we could set a range of characters to decode. It's practically non Unicode alphabetical chars that I'm talking about. Regex like `\p{L}` could do it. We don't need the whole range. Just read the link as it is..as it is in English for example.

**Comment by jcameron** [comment]
I'd access a patch to add a config option to do this, however I don't think it should be on by default.

**Comment by qooob** [comment]
Yes, sure. It's okay if it's off by default. Would you be able to make the patch?

**Comment by qooob** [comment]
Jamie, I didn't quite understand what you'd meant in your last reply?

**Comment by jcameron** [comment]
I looked into this some more, and decided that it isn't really practical to do - the reason is that it would require parsing the log files to determine which are from Apache or Nginx, and then which parts of each line contain URL-encoded characters. 

A better option may be to check if Apache itself has a way of logging URLs with the original encoding.

**Comment by qooob** [comment]
Alright, then. Let's find for other ways to do it.

Thanks for taking a look.

**Comment by chris001** [comment]
@iliaross @jcameron Very good points.  Would be very nice to activate support for UTF-8 on all system services, apache2, nginx, imap, smtp, bind9 DNS, ftp, ssh, etc.  Good places to look for the apache2 settings for to write log entries with the original encoding from the URL.
1. https://serverfault.com/questions/463757/linux-not-interpreting-utf8-encoded-characters
2. https://stackoverflow.com/questions/913869/how-to-change-the-default-encoding-to-utf-8-for-apache
3. https://webmasters.stackexchange.com/questions/38862/how-does-the-web-server-choose-between-unicode-and-utf-8-for-accented-characters
4. https://forums.cpanel.net/threads/utf-8-filenames-and-urls.359841/
5. https://confluence.atlassian.com/jirakb/how-to-get-unicode-non-ascii-characters-in-https-url-to-appear-correctly-675384991.html
6. http://httpd.apache.org/docs/current/mod/mod_log_config.html

**Comment by qooob** [comment]
The latest commit adds such, very useful functionality. It's HTML escaped, thus save. I was only talking about decoding, that would let to read non-latin characters as they are.
