### ISSUE TITLE
Command Shell: Progressive output

### ISSUE THREAD

**Issue by qooob** [webmin/webmin#687]
Hi,

I would like to ask if possible to let _Command Shell_ module to support progressive output.

Right now, if I type 

```
yum -y update *kernel* *grub*
```

I don't see the results until it's completely done. (in old themes as well)

I think, I would be able to do cool things with that feature using my drop-down ported shell.

**Comment by jcameron** [comment]
That's a good idea .. I'm pretty sure it was progressive at one point, but I broke it.  I'll take a look.

**Comment by jcameron** [comment]
Ok, this has been implemented

**Comment by qooob** [comment]
Great, thanks.
