### ISSUE TITLE
download.webmin.com is not reachable

### ISSUE THREAD

**Issue by dannoe** [webmin/webmin#700]

**Comment by swelljoe** [comment]
https://twitter.com/virtualmin/status/931772790667128832

**Comment by dannoe** [comment]
Thanks for the information.

**Comment by swelljoe** [comment]
Also, BTW, if it's ever urgent, everything in the Webmin repos (I think) is also in the Virtualmin GPL repos: http://software.virtualmin.com/vm/6/universal for yum or /vm/6/apt for apt

Though after tonight download.webmin.com will have a mirror or two, just like software.virtualmin.com does, so it'll never have downtime.

**Comment by jcameron** [comment]
Its back up now
