### ISSUE TITLE
Error editing and saving miniserv.conf after installing a Let's Encrypt certificate

### ISSUE THREAD

**Issue by Boldairdev** [webmin/webmin#701]
Hi,

With Webmin 1.860, I recently installed Let's Encrypt certificates on a couple of servers in order to access Webmin on SSL with a proper certificate instead of an auto-signed one.

The certificates were properly created and copied into the /etc/webmin directory

Nonetheless after that when I try to edit the SSL settings in order to change the ciphers list to something a little more robust than the default, I'm getting an error : 

`Failed to save SSL options : The SSL private key file /etc/webmin/letsencrypt-key.pem does not exist or does not contain a PEM format key`

Needless to say I checked the existence of said .pem files in said path,  and that they were indeed in pem format. Despite that, I still get the same error.

However manually adding to miniserv.conf the line :

`ssl_cipher_list=ECDHE-RSA-AES256-SHA384:AES256-SHA256:AES256-SHA256:HIGH:+TLSv1.1:+TLSv1.2:!MD5:!ADH:!aNULL:!eNULL:!NULL:!DH:!ADH:!EDH:!AESGCM:!RC4:!DES:!MEDIUM` 

and restarting Webmin works, and accessing Webmin through the browser, the certificate is indeed the Let's encrypt one I've created.

It's still annoying because I can't make any more modification to miniserv.conf through Webmin (and finding the right list of ciphers I wanted and those I wanted to exclude manually was a little bit difficult)

My let's Encrypt certificate as reported by Webmin :

![screenshot](https://user-images.githubusercontent.com/4577713/33123969-f0b9c10a-cf7b-11e7-9d63-e63247b2fdfc.png)

The ssl settings tabs before editing :

![screenshot_1](https://user-images.githubusercontent.com/4577713/33123052-47e70af8-cf79-11e7-8c89-c9fcac6236d2.png)

from this point trying to save gives this error message : 
![screenshot_2](https://user-images.githubusercontent.com/4577713/33123273-08722ffa-cf7a-11e7-97fa-3db84a7fd23a.png)

Any idea why this happens ?

**Comment by jcameron** [comment]
This is a bug in Webmin parsing the SSL cert file - it will be fixed in the next release though.

You can also see the fix here : https://github.com/webmin/webmin/commit/8065688231f9ec269a9c47e79882510073b0f996#diff-cff604ba3a30e80b9ba34e0f32241d69

**Comment by Boldairdev** [comment]
I applied the fix, it worked like a charm :)
Thank you :)
