### ISSUE TITLE
Webmin file explorer rar files no extract option

### ISSUE THREAD

**Issue by Keltere** [webmin/webmin#702]
Hi, i've tried everything to fix the rar files extraction but i can't find a solution.

![capture](https://user-images.githubusercontent.com/8084245/33225833-6fbb9992-d17f-11e7-8174-18a3cf59b641.PNG)

I have the last version of archlinux and this bug is extended on all distro based on archlinux like manjaro.
On the last version of mime-shared-info the MIME of rar files was changed from "application/x-rar" to "application/vnd.rar" and that i think that caused some problems (with ark file manager it did but the ark developers fixed it).

- I've installed unrar and rar
- I've tried to add a custom mime in webmin but i can't add the vnd.rar because of the dot.
- I've tried to add a custom mime on arch linux with this [guide](https://wiki.archlinux.org/index.php/default_applications#New_MIME_types)
- I've tried to edit this files but i can't get it to work with vnd.rar
`/opt/webmin/authentic-theme/extensions/file-manager/extract.cgi`
`/opt/webmin/filemin/extract.cg`

**Comment by qooob** [comment]
Are you on Arch Linux?

I will have to install it first in order to reproduce it.

In case `rar` and `unrar` installed and on the _path_ they should just work.

**Comment by chris001** [comment]
Maybe have the code test if rar and unrar are installed.
`which rar`
`which unrar`
And if they not installed, warning toaster notification to user, "this feature will not work until rar/unrar are installed. Want to install them? Click to install."
Then `apt install unrar-free` or the matching command and package name for the OS.

**Comment by Keltere** [comment]
Like i said, i've installed and tested with rar and unrar, they are working fine but webmin won't recognize.

I've wrote a post on arch forum but still could't find a solution [link](https://bbs.archlinux.org/viewtopic.php?pid=1748314#p1748314)

**Comment by Corvalan** [comment]
Is there any progress in this issue?

**Comment by chris001** [comment]
Same bug on ubuntu 16.04.  `example.rar` fails to give an option to `Extract`.  `example.gz` does give the option to `Extract`.

**Comment by qooob** [comment]
Are those rar/unrar commands on the path?

**Comment by chris001** [comment]
@iliaross  You're right.  The `rar` and `unrar` command weren't installed.  After running the command `apt install rar unrar`, and click the refresh icon, click on the `three dots` (menu icon) next to the file, Filemin gives the `Extract` option for this `rar` file type.

**Comment by qooob** [comment]
The same should work for other extensions. I have made it work for all kind of archive types, as far as I remember.

**Comment by qooob** [comment]
Yes, sure. I'll do it.

**Comment by Keltere** [comment]
I think just Arch distributions are affected by the MIME bug. I've tried to search in webmin files for application/rar and change it to application/vnd.rar but without success.
I've dropped my search, hope someone will fix it in the future.

Really can't understand why they changed from application/rar to application/vnd.rar

**Comment by chris001** [comment]
The two places where this code decides if the file is a rar type and to extract it:
1. https://github.com/webmin/webmin/blob/2ee32e71cfba6adfc024747b3cd92f4a1724f19d/filemin/extract.cgi#L27
2. https://github.com/webmin/webmin/blob/2258c2dd4ec63e429cb733e53f6fb055d7571607/filemin/filemin-lib.pl#L344

* Big question is, when you spin up an Arch vm or docker container, and run the Filemin unit/functional tests, what are the results, does the `rar`/`unrar` test pass or fail.

**Comment by iliaross** [comment]
It's also [/extensions/file-manager/extract.cgi](https://github.com/iliaross/authentic-theme/blob/master/extensions/file-manager/extract.cgi).

Can someone, for those it doesn't work just `print $archive_type;` and share the output?

**Comment by Keltere** [comment]
@chris001 really thanks, i've tried to modify those as

` elsif ($archive_type =~ /\/vnd.rar/) { `

`|| ( index( $type, "application-x-rar" ) != -1 && has_command('unrar') ) `

@iliaross 
where i need to place that, in the code?

**Comment by qooob** [comment]
Try replacing in `extract.cgi` in the mentioned theme file.

Replace line 27 from:

```
} elsif ($archive_type =~ /\/x-rar/) {
```

to:

```
} elsif ($archive_type =~ /\/x-rar|\/vnd.rar/) {
```

When you edited the file, just hit refresh button in the File Manager UI.

Report back if it worked for you, pelase.

**Comment by Keltere** [comment]
@iliaross nope, not working

**Comment by qooob** [comment]
Did you reload the page or you refresh it using an circlular icon near the File dropdown, in the menu?

Okay, try

```
} elsif ($archive_type =~ /\/x-rar|\/vnd-rar/) {
```
} elsif ($archive_type =~ /\/x-rar|\/vnd.rar/) {

**Comment by Keltere** [comment]
Each edit i refresh the browser and restart webmin to check if it's working. Even this edit doesn't work.

**Comment by qooob** [comment]
That's the point, you only need to refresh the page for now.

![screenshot from 2018-04-04 21-31-46](https://user-images.githubusercontent.com/4426533/38326904-a3de6664-384f-11e8-8bcf-49f3ef9598a0.png)

**Comment by Keltere** [comment]
Yup, i've tried to edit again and just refresh it. Same problem

**Comment by qooob** [comment]
I've miss-lead you, sorry.

It's `file-manager-lib.pm` file, line 372. 

```
($type =~ /application-x-rar/ &&
```

->

```
($type =~ /application-x-rar|application-vnd-rar|application-vnd.rar/ &&
```

**Comment by Keltere** [comment]
Ok now it show me the extract option, it has no rar icon and if i try to extract some rar (without password) it give me a success message but it didn't extract anything.

**Comment by qooob** [comment]
Now, you need to edit `extract.cgi` file accordingly, to make sure that it would fall into _rar_ block.

**Comment by Keltere** [comment]
Ok so 

`($type =~ /application-x-rar|application-vnd-rar|application-vnd.rar/ &&`
and 
`} elsif ($archive_type =~ /\/x-rar|\/vnd.rar/) {`

It's working fine except for the rar icon (it's still a ?) not recognized as an archive.

**Comment by qooob** [comment]
Could you please give it a try with _zip_ archives? Do they work for you?

**Comment by qooob** [comment]
About the icons, could you please check at:

```
/filemin/images/icons/mime/application-x-rar.png
```

Try renaming it please.

**Comment by qooob** [comment]
@Keltere Could you also check which one is valid for you for sure in the statement below:

```
$type =~ /application-x-rar|application-vnd-rar|application-vnd.rar/ &&
```

`-vnd-rar` or `-vnd.rar`?

**Comment by Keltere** [comment]
Zip and 7zip are working fine from the beginning, just with rar i've got some problems. 

-vnd.rar it's the right one.

**Comment by Keltere** [comment]
The icon renamed to `application-vnd.rar.png` it's working.

Thanks for your time and for your help.
Really sorry for the trouble.

**Comment by qooob** [comment]
We'll add it to the distro. Thanks

**Comment by qooob** [comment]
> -vnd.rar it's the right one.

It would always work because `.` there means any char. Can you try exact match?

```
-vnd\.rar
```

or

```
-vnd-rar
```

Please?

**Comment by Keltere** [comment]
@iliaross the first one `-vnd\.rar`

**Comment by Keltere** [comment]
@iliaross just a question. In future will be possible to extract password protected archive, and maybe some error message? Until now it show success even if it doesn't extract anything, for any type of archive (7z, zip, rar).

**Comment by qooob** [comment]
Yes, of course. I will add this to my todo. Thanks!

Also create password protected videos.

**Comment by chris001** [comment]
Excellent! @iliaross 
Question: 
What's the minimal amount of hard-coding of mime types (in the code), required to accomplish this (and other) filemin tasks (extract, compress, anything) ?  Because this feature could get broken again when any distro decides to change its MIME type to file extension list.
Would it be possible to encode none of the mime types in the perl code, and just dynamically match the file's extension, to the extension looked up from the corresponding MIME type of the file which the OS has in its list of MIME types ( varies from OS to OS), and from there, match to which type of compressed archive is this, and the commands for compression/extraction.

**Comment by qooob** [comment]
It haven't checked, so I can say for now.

It's important, that it works across all kind of distros. Using Perl lib seems to be safe. Other than that, it has to be tested.

Distros don't change types out of the blue. _Vnd_ is used for proprietary stuff. `Rar` had to go like this since the beginning.

**Comment by 0dp** [comment]
$uname -a
`4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u6 (2018-10-08) x86_64 GNU/Linux`
webmin v. 1.900

I am having the same issue as OP, no extract method in context menu / right click.
This goes for rar, tar, zip
<img width="181" alt="screenshot 2019-02-20 at 21 29 51" src="https://user-images.githubusercontent.com/3642367/53122400-d21baf00-3556-11e9-9ceb-15bbd7a90cd2.png">

I have checked and verified that rar/unrar, zip and tar is available on the system.

**Comment by rostovtsev** [comment]
Maybe wrong MIME? Please enable to display _type_ column in File Manager configuration? What is the type for the given _.rar_ file?

Make sure that `unrar` command is on the path. Try opening drop-down command shell and run `unrar`. Do you get the output?

**Comment by 0dp** [comment]
rar, unrar, zip, unzip, tar are all available.
tar.gz files show as type, application-octet-stream
rar files show as type, application-octet-stream
zip files show as type, application-octet-stream

**Comment by 0dp** [comment]
I read here https://github.com/authentic-theme/authentic-theme/issues/839#issuecomment-374905698

> Maybe your OS does not have the correct shared mime types.

Installing/reinstalling `shared-mime-info` seems to fix the issue.

It seems like some OS' does not provide sufficient info, or that packages (rar, unrar(free, non-free), zip, unzip) does not provide the info needed.

I don't really know. I've installed webmin on a wide range of OS', this is the first time it has happend

**Comment by rostovtsev** [comment]
Password protected archives are supported in 19.32. https://github.com/authentic-theme/authentic-theme/issues/1320#issue-432834927

Give it a try. :wink:
