### ISSUE TITLE
Use of uninitialized value $ in pattern match (m //)

### ISSUE THREAD

**Issue by TMTYD** [webmin/webmin#704]
Hi

I have discovered this error in the miniserv.error log
Use of uninitialized value $ in pattern match (m //) at /usr/share/webmin/bind8/bind8-lib.pl line 4133.

how can you fix it?

**Comment by jcameron** [comment]
That's pretty harmless - but what is on line 4133 of ` /usr/share/webmin/bind8/bind8-lib.pl` on your system?

**Comment by TMTYD** [comment]
`sed -n '4133 p' bind8-lib.pl
return undef if ($en !~ /yes/i);
`
this here

**Comment by jcameron** [comment]
OK, known issue which will be fixed in the next Webmin release (1.870)

**Comment by TMTYD** [comment]
ok thx
