### ISSUE TITLE
Modules controls redirection to main page

### ISSUE THREAD

**Issue by qooob** [webmin/webmin#710]
Jamie, hi.

It would be right to redirect back to previous or index page after actions were applied in BIND, Apache and other modules, using top right table-header links.

Otherwise, if URL is different after apply/restart/stop theme's Favorites is not working logically right.

**Comment by qooob** [comment]
https://github.com/qooob/authentic-theme/issues/911

**Comment by jcameron** [comment]
I'm confused - the apply button should redirect back to the same page.

**Comment by qooob** [comment]
Please forgive my overconfidence. When fixing [authentic-theme/#905](https://github.com/qooob/authentic-theme/issues/905) issue recently, I was the one who broke it.
