### ISSUE TITLE
cannot delete firewall rule in firewall module

### ISSUE THREAD

**Issue by gnadelwartz** [webmin/webmin#711]
I'm not able to delete or move selected firewall rules in firewall module. If I klick on delete or move it calls save_policy.cgi but the rules are not delete/moved and diplayed again. I'm using direct mode.

![grafik](https://user-images.githubusercontent.com/4593242/33530213-c1b18172-d87c-11e7-8b5b-80a218b9fb13.png)

create edit is working, also delete from edit form.
can pls someone test and confirm it?

I had a look at save_policy (deslsel/movesel) and save_table() in firewall_lib but can't locate the issue.

**Comment by qooob** [comment]
Did it happen before?

**Comment by gnadelwartz** [comment]
did not test it, but when I go back to 1.860 its the same. So please can someone test if its my setup (proxy/updates from repo) or a general error.

Test should really simple: add a new rule, select it in the table and try to delete it.

**Comment by qooob** [comment]
I also couldn't delete it on my Debian Linux.

Looks like a bug. I wish you told me that before the release. It's nothing but I'll only be able to look at it in the morning.

**Comment by gnadelwartz** [comment]
sorry, noticed it a few minutes ago as my server sudently reboots an I wanted to delete some duplicate rules from fail2ban.

**Comment by qooob** [comment]
You mean Linux Firewall module or Fail2Ban?

**Comment by gnadelwartz** [comment]
linux firewall

**Comment by qooob** [comment]
It will need a fix. This module has issues with HTML output. It's not directly theme issue.

**Comment by gnadelwartz** [comment]
I knon, thats why I post it ro webmin :-)

**Comment by jcameron** [comment]
Ilia, what's the HTML issue exactly?

**Comment by qooob** [comment]
Jamie, I still see the issue but it's not what I saw last night.

Anyway, right now, _after further investigation_, I have noticed that Gray Theme passes `input[name="table"]` and `input[name="chain"]` values to `save_policy.cgi`.

![screenshot from 2017-12-04 12-27-12](https://user-images.githubusercontent.com/4426533/33545638-e03cd628-d8ef-11e7-9ff3-1945a51ca105.png)
![screenshot from 2017-12-04 12-27-39](https://user-images.githubusercontent.com/4426533/33545639-e05a2188-d8ef-11e7-8f61-52e300e279a2.png)

------

Again, right before posting this comment, I remembered that I had [issue request](https://github.com/qooob/authentic-theme/issues/875#issuecomment-341777364) in this regard, that addressed issue with not working _Showing IP table_ and _Add a new chain named_ button at the very top of the page.

My patch had broken `table` and `chain` inputs exactly as it was applied to all of them, instead to only first ones.

Here is what I mean by omitted/empty forms (Gray Theme, same as Authentic Theme):

![screenshot from 2017-12-04 12-55-09](https://user-images.githubusercontent.com/4426533/33546772-f64fbd38-d8f2-11e7-8d17-5450ac3d38ca.png)

Look, you see the form is soaring somewhere else, all empty? Well, it's not going to work with AJAX calls properly.

I made a fix to my fix (just now) to make it look/work properly, so the form will contain needed elements unambiguously.

To address this issue, I will fix my code for now, **_because it still needs a fix anyway_**. In the future, we'd better fix server part or/and not build modules this way.

I will go with 19.05 just in a bit for upcoming Webmin release. I will also try to beautify buttons above for switching IPv4/IPv6 protocols.

**Comment by qooob** [comment]
It's been fixed. Jamie, you can just `git pull` to include these changes for upcoming Webmin release.

**Comment by gnadelwartz** [comment]
as already stated in private chat this fixed the issue at least for me. thanks for investigating and sorry for the last minute report.

**Comment by jcameron** [comment]
Fix in Webmin is here : https://github.com/webmin/webmin/commit/f5a4dcb4deb9405acf751c09ec9aa6a024f357b2

**Comment by qooob** [comment]
Alright, Jamie. I have pushed force update for 19.04. Please pull the latest changes.


@gnadelwartz Could you please pull the latest changes for the theme and Jamies and try again to be fully sure?

**Comment by gnadelwartz** [comment]
its working for me...

**Comment by gnadelwartz** [comment]
ipv6 is also working
