### ISSUE TITLE
Services showing up in webmin but not systemd

### ISSUE THREAD

**Issue by Vagrantin** [webmin/webmin#716]
Hello,
I'm running Webmin 1.860 on a Debian 9, and for testing purpose i have installed php5.6 and php5.6-fpm.
But since I have purged it, the services are still available on the webmin interface...

![webmin_services](https://user-images.githubusercontent.com/19902259/33717799-927d70f8-db9e-11e7-85bf-7c936651e986.PNG)

But if I look on systemd side two of the 3 services listed above doesn't exist...(see picture in link below)
php5.6-fpm >> doesn't exist anymore 
php7.0-fpm >> doesn't exist 
php7.0-fpm.services >> This one is running well

![systemd_services](https://user-images.githubusercontent.com/19902259/33717808-9c061d28-db9e-11e7-8bf4-3e7444ba53be.PNG)

And Webmin trigger an error if I try to delete those services, because the don't point to any existing files.
Error message is Failed to save action : Missing or invalid action name
The impact is quite heavy because, when I add a new Virtualhost on Virtualmin, php-fpm don't get rebooted(even if it doesn't through any error) and I have to restart php7.0-fpm.services manually each time I'm creating a new Virtualhost.

From here my question is, is there any way to have Webmin refreshing the Services to retrieve the exact service list running ?
If not what would be the best way to clean up those "non-existing" service from Webmin ?

Thanks in Advance for any input
Matth

**Comment by jcameron** [comment]
Does `php5.6-fpm` perhaps exist under `/etc/init.d` on your system?

**Comment by Vagrantin** [comment]
Yes ! Didn't though about that... I think i was expecting to have everything handle trough systemd only.
Is it safe to delete those files or should a follow a cleaner procedure ?

Thanks for the clarification !

Matth

**Comment by jcameron** [comment]
Yes, you can delete them. I'm actually surprised they still exist, as I would have expected they be removed when the PHP FPM packages were.

**Comment by Vagrantin** [comment]
HUm, just tried that and re-run a config check evrything seems ok only php7.0 is detected. But now webmin, is complaining that it can't find php5.6-fpm, when restarting php-fpm at the creation of a new vhost, Wondering if it's not due to a badly packaged Debian package as soon as I delete php5.6 with ``aptitude purge`` command line.
Should i go to a manuel clean up onf everything related to php5.6 ? Or is there a way to make sure Webmin is really using php7-fpm ?

Thanks for  the clarification.
Matth

**Comment by jcameron** [comment]
I'd recommend deleting all PHP 5.6 configs and scripts if you aren't using it.

**Comment by Vagrantin** [comment]
Ok, this issue was effectively due to php5.6 probably badly package so the aptitude purge didn't fully cleanup everything.
