### ISSUE TITLE
File apache/mod_cgid.pl is missing

### ISSUE THREAD

**Issue by adbario** [webmin/webmin#718]
Hi, latest Virtualmin checks if Apache has CGI enabled or not, and this works fine with MPM prefork as it uses mod_cgi. But MPM worker and event is using mod_cgid, which makes Virtualmin "re-check configuration" to fail as file apache/mod_cgid.pl doesn't exist.

This was verified by simply creating empty file at apche/mod_cgid.pl and Virtualmin configuration check succeeded.

**Comment by jcameron** [comment]
Thanks .. this will be fixed in the next Webmin release.
