### ISSUE TITLE
Incorrect encoding in Russian

### ISSUE THREAD

**Issue by Hubaxis7** [webmin/webmin#719]
For the last few versions I have problems encoding the title menu "scheduled cron jobs". And today I have updated webmin to 1.860 1.870 and got the wrong encoding on the dashboard.
![2017-12-10_15-42-16](https://user-images.githubusercontent.com/22938004/33804956-18af30ca-ddc1-11e7-95cf-1d87740c662a.png)

**Comment by qooob** [comment]
It's been fixed on the latest commit. Force upgrade the theme using theme configuration.

Dupe: https://github.com/qooob/authentic-theme/issues/921
