### ISSUE TITLE
miniserv.error log file

### ISSUE THREAD

**Issue by TMTYD** [webmin/webmin#721]
Hi 

here is a output from the logfile miniserv.error

```
untie attempted while 1 inner references still exist at /usr/share/webmin/ajaxterm/index.cgi line 86.
untie attempted while 1 inner references still exist at /usr/share/webmin/ajaxterm/index.cgi line 44.
untie attempted while 1 inner references still exist at /usr/share/webmin/ajaxterm/index.cgi line 86.
untie attempted while 1 inner references still exist at /usr/share/webmin/ajaxterm/index.cgi line 44.
Use of uninitialized value in split at ./webmin-lib.pl line 1649.
Use of uninitialized value $_[0] in array element at ./time-lib.pl line 247.
Use of uninitialized value $en in pattern match (m//) at /usr/share/webmin/bind8/bind8-lib.pl line 4133.
Use of uninitialized value $en in pattern match (m//) at /usr/share/webmin/bind8/bind8-lib.pl line 4133.
Use of uninitialized value $en in pattern match (m//) at /usr/share/webmin/bind8/bind8-lib.pl line 4133.

[09/Dec/2017:05:00:10 +0100] [192.168.178.21] /stats.cgi : Perl execution failed : Undefined subroutine &proc::get_cpu_io_usage called at /usr/share/webmin/authentic-theme/stats.cgi line 25.
Use of uninitialized value $en in pattern match (m//) at /usr/share/webmin/bind8/bind8-lib.pl line 4133.
```

**Comment by jcameron** [comment]
Which operating system are you running Webmin on there?

**Comment by TMTYD** [comment]
debian stretch 9.3

**Comment by jcameron** [comment]
We're going to release a new minor version that fixes this perl error shortly.

**Comment by TMTYD** [comment]
Hi 
the logfile have new inputs

`TERM environment variable not set.
Subroutine is_dictionary_word redefined at /usr/share/webmin/useradmin/md5-lib.pl line 261.
Subroutine validate_password redefined at /usr/share/webmin/useradmin/md5-lib.pl line 220.
Subroutine encrypt_sha512 redefined at /usr/share/webmin/useradmin/md5-lib.pl line 210.
Subroutine check_sha512 redefined at /usr/share/webmin/useradmin/md5-lib.pl line 203.
Subroutine unix_crypt_supports_sha512 redefined at /usr/share/webmin/useradmin/md5-lib.pl line 194.
Subroutine encrypt_blowfish redefined at /usr/share/webmin/useradmin/md5-lib.pl line 170.
Subroutine check_blowfish redefined at /usr/share/webmin/useradmin/md5-lib.pl line 162.
Subroutine encrypt_sha1_hash redefined at /usr/share/webmin/useradmin/md5-lib.pl line 154.
Subroutine encrypt_sha1 redefined at /usr/share/webmin/useradmin/md5-lib.pl line 145.
Subroutine check_sha1 redefined at /usr/share/webmin/useradmin/md5-lib.pl line 137.
Subroutine to64 redefined at /usr/share/webmin/useradmin/md5-lib.pl line 126.
Subroutine unix_crypt_supports_md5 redefined at /usr/share/webmin/useradmin/md5-lib.pl line 117.
Subroutine encrypt_md5 redefined at /usr/share/webmin/useradmin/md5-lib.pl line 29.
Subroutine check_md5 redefined at /usr/share/webmin/useradmin/md5-lib.pl line 11.
find: '/usr/local/lib/x86_64-linux-gnu/perl/5.24.1': No such file or directory
find: '/usr/local/share/perl/5.24.1': No such file or directory
Use of uninitialized value $_[0] in array element at ./time-lib.pl line 247.
Use of uninitialized value in split at ./webmin-lib.pl line 1649.
TERM environment variable not set.
`

**Comment by jcameron** [comment]
Those are all pretty harmless ... you can ignore then. There are minor perl warnings in Webmin that we are working through fixing.
