### ISSUE TITLE
Use exported Virtualmin Framed Theme on new Virtualmin instance produce weird display

### ISSUE THREAD

**Issue by eldk** [webmin/webmin#725]
Hello,

I've created a brand new Virtualmin instance a few days ago .

Authentic theme seems to be the default now on new installation. And "Virtualmin Framed Theme" can't be find in Webmin theme list.

So, as I prefer to use the "Virtualmin Framed Theme" for now.

I export VFT from one other instance, but installled a long ago with default VFT : same virtualmin/webmin release, the last one : webmin 1.870, virtualmin 6.02gpl.

Then, import and install it in the new instance from Webmin Theme Manager.

In the new instance, some styles are now full green or red. The most impacted module is File Manager. This is the same with Firefox(57) and Chromium(63)  I join a screenshot.

![virtualmin_framed_theme_green_red](https://user-images.githubusercontent.com/11083657/34168908-0909e152-e4e6-11e7-9a2b-d7bdd9eac9d7.jpg)

Table css : 
- "old Virtualmin + Framed Theme" : html body form#list_form.ui_form table#sortableTable**2**.wrapper

- "new Virtualmin + imported Framed Theme" : html body form#list_form.ui_form table#sortableTable**NaN**.wrapper

The red :
- html body form#list_form.ui_form table#sortableTableNaN.wrapper tbody tr td table#sortableTableNaN.ui_table.sortable.ui_columns thead tr.ui_columns_heads
- `<tr class="ui_columns_heads" bgcolor="#D0E0FC class='maintitle'">`

The green : 
- html body form#list_form.ui_form table#sortableTable2.wrapper tbody tr td table#sortableTable3.ui_table.sortable.ui_columns tbody tr#row_name_boot
- `<tr id="row_name_boot" bgcolor="#f5f5f5 class='row0 ui_checked_columns mainbody'">`

Where should I find the original wbt file for Virtualmin Framed Theme ?

Thanks,

Eric

**Comment by qooob** [comment]
There is package on _RHEL_ system:

```
wbt-virtual-server-theme
```

and on Debian it's:

```
webmin-virtual-server-theme
```

You can install them easily.

**Comment by swelljoe** [comment]
Those bugs have been fixed in the latest version of the Virtualmin framed theme packages referenced by Ilia. This comes from changes in the ui-lib in Webmin. The theme should be available in all repositories, but if not let me know (I've just checked the RHEL/CentOS one and the wbm repos, it's definitely in those).

**Comment by eldk** [comment]
Hello,
I will try in next days and come back.
So I close it and reopen it if needed
Thanks @iliaross and @swelljoe ,
