### ISSUE TITLE
Server download filename param

### ISSUE THREAD

**Issue by qooob** [webmin/webmin#726]
Hi, Jamie.

We need to send filename param in content disposition attachment.

Example:

```
Content-Disposition: attachment; filename="filename.jpg"
```

Otherwise, it's not clear what file type is that. For example, MySQL/Database Backup, in case set to compress, even thought it does compress, it returns `.sql` file name. It's not cool.

When you do it, I will parse it on the theme side to make it work with XHR calls.

**Comment by jcameron** [comment]
Yeah, the mysql module is clearly doing this wrong - will fix.

Any other instances that you've noticed?

**Comment by qooob** [comment]
Jamie, 

Probably and mos likely:

```Shell
/mailboxes/detach.cgi
/file/show.cgi
/virtual-server/pro/save_bkey.cgi
/server-manager/onebackup.cgi
/server-manager/show.cgi
```

**Comment by qooob** [comment]
Probably other places where you push by default `backup.tgz`. It would be great if we could create proper file name, reflection module and content, one way or the other.

I made a commit for the theme to properly name downloaded files:
https://github.com/qooob/authentic-theme/commit/337f9457e14b7330f57e3242957c7b07711c7e34

**Comment by jcameron** [comment]
Probably best to fix these in the core Webmin code. Actually in most cases I attempt to force a filename using a path like something.cgi/filename.tar.gz , which also works in older browsers.
