### ISSUE TITLE
CPU and HD usage not correct on Synology NAS

### ISSUE THREAD

**Issue by gnadelwartz** [webmin/webmin#728]
see https://github.com/qooob/authentic-theme/issues/954

I managed to install webmin on my Synology NAS, it works but CPU and HD usage is wrong

![grafik](https://user-images.githubusercontent.com/4593242/34273289-06bdd250-e694-11e7-95ed-66dd43e107ed.png)

![grafik](https://user-images.githubusercontent.com/4593242/34273271-f74a54e2-e693-11e7-9c03-dfa81e9de4d3.png)

```
bash-4.3# df
Filesystem      1K-blocks      Used  Available Use% Mounted on
/dev/root         2451064    963636    1385028  42% /
none               254900         4     254896   1% /dev
/tmp               256796       512     256284   1% /tmp
/run               256796      2016     254780   1% /run
/dev/shm           256796         4     256792   1% /dev/shm
/dev/vg1000/lv 3840953648 484462900 3356388348  13% /volume1
```
![grafik](https://user-images.githubusercontent.com/4593242/34273129-5caa801a-e693-11e7-9440-2d2c79973a21.png)

top:
`%Cpu(s): 35.2 us, 15.2 sy,  0.0 ni, 38.8 id,  3.0 wa,  0.0 hi,  7.9 si,  0.0 st`

What commands are used to get the numbers?

**Comment by gnadelwartz** [comment]
interesstingly HD usage is shown correct after updating today to latest theme/webmin AND set realtime stats updates to 5 seconds:
![grafik](https://user-images.githubusercontent.com/4593242/34303574-4c5bea34-e736-11e7-9ad6-cdfaaeb7a68a.png)
when the page is first diplayed HD usage shows 90+% and goes down to the correct value on next update.

@iliaross : may be the deafault delay of 1000ms should be raised.

nevertheless CPU always show 0% :-(

**Comment by qooob** [comment]
For CPU you need to have `vmstat` installed.

**Comment by gnadelwartz** [comment]
I managed to install ipkg to add commands to my NAS, unfortunatly `vmstat` is not availible as of now :-(
is there an alternative?

**Comment by qooob** [comment]
Theoretically, yes but practically Webmin and the theme relies on `vmstat` command output.

**Comment by gnadelwartz** [comment]
I found and installed dstat it has all functions of vmstat iostat and netstat in one (phyton tool)
if I use `dstat -c 12` it can be an alternative for getting CPU usage:

```
root@NAS:~# dstat -c 1 2
----total-cpu-usage----
usr sys idl wai hiq siq
  4   2  93   0   0   1
 29   8  63   0   0   0
 25  42  33   0   0   1
```

**Comment by qooob** [comment]
Kay, Jamie could do it and include it into standard API. However, I see the output is different and this is a work to do. Please report it to Jamie. Theme will just work in case it receives pre-structured data from the back-end.

**Comment by gnadelwartz** [comment]
Im already tracking this down, but it much comlicated :-(

**Comment by gnadelwartz** [comment]
it was not so complicated, I looked in the rigth place fix, but then lost in webmin ... and found it again :-)
fixed: https://github.com/webmin/webmin/pull/733

**Comment by gnadelwartz** [comment]
![grafik](https://user-images.githubusercontent.com/4593242/34314067-7972f352-e770-11e7-8285-063964e32aaa.png)

![grafik](https://user-images.githubusercontent.com/4593242/34314081-8fdf4122-e770-11e7-9ba4-2cfcc6da51fd.png)

**Comment by gnadelwartz** [comment]
next fix for embedded ARM systems: https://github.com/webmin/webmin/pull/734
show CPU Type and info ...

**Comment by gnadelwartz** [comment]
solved by deleting /etc/system-status/info

**Comment by jcameron** [comment]
You mean `/etc/webmin/system-status/info`, right?
