### ISSUE TITLE
can't change login screen  to authetic after updating from (very) old version 

### ISSUE THREAD

**Issue by gnadelwartz** [webmin/webmin#732]
To install webmin on my Synology, I had to install (very) old version 1.6xx of webmin, having a nice theme called stressfree. Updating to webmin 1.870 from the webinterface worked like an charm.
![grafik](https://user-images.githubusercontent.com/4593242/34300596-16c613a2-e729-11e7-9f4e-be4cd148c60d.png)

Authentic-theme is also working, but login screen can not be changed to authentic:
![grafik](https://user-images.githubusercontent.com/4593242/34299839-68bcac10-e725-11e7-8d70-597acfe19b9b.png)

![grafik](https://user-images.githubusercontent.com/4593242/34299790-1ba3b22a-e725-11e7-9abe-bb3840151771.png)

a look at miniserv.conf shows two `preroot` entrys:
```
preroot=theme-stressfree
preroot_admin=authentic-theme
```

When I put  `preroot=authentic-theme` I get the following error, same wenn I remove `preroot_admin`:

```
> Error - Perl execution failed
> 
> Can't locate theme-stressfree/authentic-init.pm in @INC (you may need to install the theme-stressfree::authentic-init module) (@INC contains: /var/packages/webmin/target/webmin/authentic-theme/lib /var/packages/webmin/target/webmin /usr/local/lib/perl5/site_perl /usr/local/share/perl5/site_perl /usr/local/lib/perl5/vendor_perl /usr/local/share/perl5/vendor_perl /usr/local/lib/perl5/core_perl /usr/local/share/perl5/core_perl . /var/packages/webmin/target/webmin/ ..) at /var/packages/webmin/target/webmin/authentic-theme/authentic-lib.pm line 18. Compilation failed in require at /var/packages/webmin/target/webmin/authentic-theme/session_login.cgi line 10. 
```

How do I get the autentic login, e.g. delete miniserv.conf and install from official tar again?

**Comment by swelljoe** [comment]
Looks like Stress Free is the default theme (in *Webmin->Webmin Configuration->Webmin Themes*), and Authentic has been set as the user theme (*Webmin->Change Language and Theme*) for root.

The login page is always determined by the "default" theme. `preroot` is only half of the theme config; you also have `theme` in the `/etc/webmin/config` file. Both change when you change it in the UI. As I understand it, preroot is setting up the library path for the theme, theme actually determines which theme module to use. I don't really understand why there's two parts for it...I can't think of any reason the theme directory shouldn't be the preroot automagically (I mean, why would it need to ever be different from the theme?), but that's how it is.

And you have to restart Webmin after any default theme change. I'm not sure if user-level theme change (set by, e.g. `preroot_root` in miniserv.conf and `theme_proot` in config) needs a restart, but it might.

**Comment by gnadelwartz** [comment]
Hi Joe, it was my fault, yes I didnt change the default theme!
Thanks for pointing out.

I did'nt notice, because all my other webmin installs are with authentic as default theme :-(
