### ISSUE TITLE
system-status/info should be ignored when crontab command not availible

### ISSUE THREAD

**Issue by gnadelwartz** [webmin/webmin#735]
when valid information is gatered by webmin. If wrong/old info is in this file correctly gathered information is not displayed.

see: https://github.com/webmin/webmin/pull/734 and https://github.com/webmin/webmin/issues/728

Happy Xmas!

**Comment by jcameron** [comment]
How would it get stale if you have background status collection enabled in webmin though? When this is disabled, Webmin will not used the cached info.

**Comment by gnadelwartz** [comment]
don't know :-) I simply found information from there. was used even it was not correct. may be a simple solution is to delete the cached info on update?

**Comment by gnadelwartz** [comment]
backgound data collection is set to 5 minutes, but it seems it was not updated. may be because backgound collection it is not working on synology?

**Comment by gnadelwartz** [comment]
ok, found the issue, setup of cron jobs seems not to work ...

**Comment by jcameron** [comment]
It's odd that there would be a dependency on regular cron though, as status collection is done by Webmin's own server.

Anyway, I will add a check to prevent use of an old collected file in the next release.

**Comment by gnadelwartz** [comment]
thanks! this will solve the problem of showing wrong/outdated information, i'll try to fix the more general problem with cron
