### ISSUE TITLE
can syslog-ng module handle includes in conf?

### ISSUE THREAD

**Issue by gnadelwartz** [webmin/webmin#738]
on my NAS there are include lines in my syslog-ng.conf, e.g.:

`include "/etc/syslog-ng/patterndb.d/";`

this seems not to work correctly, because e.g  list-option.cgi runs forever and then abort.
a qiuck look to syslog-ng.lib does not show if processing on include statements is done in `read_config_file`

If I remove the include line or skip them like comments in `read_config_file`, everything works (but onyl with the contents of /etc/syslog-ng/syslog-ng of corse)

**Comment by jcameron** [comment]
You're right, includes aren't currently supported. I'll look into fixing this ..

**Comment by gnadelwartz** [comment]
until its implemented I simply ignore includes:
```
--- syslog-ng-lib.pl    2017-12-24 14:22:40.189663078 +0100
***************
*** 46,51 ****
--- 46,52 ----
        $line =~ s/\/\/.*$//g if ($line !~ /".*\/\/.*"/);
        $line =~ s/\/\*.*\*\///g;       # Remove multi-line comment
        $line =~ s/^\s*@.*$//g;         # Remove @version line
+       $line =~ s/^\s*include\s.*//g;
        while(1) {
                if (!$cmode && $line =~ /\/\*/) {
                        # start of a C-style comment

```

**Comment by jcameron** [comment]
Good suggestion

**Comment by jcameron** [comment]
Proper support for includes has been implement for inclusion in the next Webmin release.
