### ISSUE TITLE
Firewall6 issue?

### ISSUE THREAD

**Issue by peterlaws** [webmin/webmin#739]
(Sorry, I hit enter with blank content)

Whenever I select No to **Directly edit firewall IPv6 rules instead of save file?**
I get this
![fireshot-297](https://user-images.githubusercontent.com/9319293/34327549-82435da0-e8bf-11e7-9b1a-e55384eba25e.png)

**Comment by qooob** [comment]
Could you provide more information please? 😆

**Comment by peterlaws** [comment]
(Sorry, I hit enter with blank content)

**Comment by jcameron** [comment]
This is a known bug in Webmin 1.870, which is fixed in the 1.871 and later releases.

**Comment by peterlaws** [comment]
Thank you
