### ISSUE TITLE
Optionaly exclude `?xhr-` from loggin

### ISSUE THREAD

**Issue by qooob** [webmin/webmin#740]
Jamie, I improved `stats.cgi` to only collect data, when user is active with Webmin tab/window. Any time user switches away to another tab or changes the browser in its X to some other program, the collection of real-time stats will stop. On getting back it will be restarted.

I propose to add an option to _Webmin Configuration/Logging_ that would exclude any URLs containing `?xhr-`to prevent pollution of log files. In case user wants it, it could be enabled.

I don't think it's going to hurt as all `?xhr-xxx` calls are hardcoded on the theme side.

**Comment by jcameron** [comment]
Sure, I've added a `nolog` config option to miniserv for specifying regexps to not log. You could set this at theme install time.

**Comment by qooob** [comment]
> You could set this at theme install time.

How exactly do I do this?

Adding string `nolog=xhr` to `/authentic-theme/config` or as `$config{'nolog'} = "xhr";` in the theme code doesn't do anything? What am I understanding wrong?

Latest Webmin from git was installed and restarted.

**Comment by jcameron** [comment]
You could use code like : 

```
if (!$gconfig{'nolog'}) {
  $gconfig{'nolog'} = ".*xhr.*";
  &save_module_config(\%gconfig, "");
}
```

**Comment by qooob** [comment]
Jamie, your code could work potentially, in case `$config{'nolog'}` would be read [here](https://github.com/webmin/webmin/commit/1b833bb4c0ce844bc49a9283353162d9f65097d6#diff-8b0d1e2d31f69c1826d4ecc01adb23f1R3127).

It doesn't get evaluate in `miniserv.pl`. Maybe you need to do some security check for the new key `nolog`? .. because having `nolog=` key at `/etc/webmin/config` doesn't get printed in your commit above. At the same time, if you print `$config{'log'}` - then it's printed fine there.

I don't know if it's a cache issue or something else, but `$config{'nolog'}` has no value there, even if set.

**Comment by qooob** [comment]
I obviously restarted Webmin.

**Comment by jcameron** [comment]
Oops, sorry ... I got this wrong. The code should be : 

```
my %miniserv;
&get_miniserv_config(\%miniserv);
if (!$miniserv{'nolog'}) {
    $miniserv{'nolog'} = ".*xhr.*";
    &put_miniserv_config(\%miniserv);
    &reload_miniserv();
    }
```

**Comment by qooob** [comment]
Great, thanks.
