### ISSUE TITLE
Incomplete backup of sendmail config files on FreeBSD 11.0

### ISSUE THREAD

**Issue by gjpc** [webmin/webmin#741]
Webmin is only backing up the following sendmail config files on FreeBSD 11.0

- etc/mail/sendmail.cf
- etc/mail/local-host-names
- etc/mail/access

I tried adding the aliases file path to the sendmail/config-freebsd file line 2:
`alias_file=/etc/mail/aliases`

I tried forcing the aliases file in the backup_config.pl line 26:
`push(@rv, '/etc/mail/aliases');`

I also tried just adding the file to the Webmin config **Include in backup** _additional files_ dialog box.  which seems to not work at all on FreeBSD. The additional files do not even persist once you leave the config backup page and return.

If someone can explain why my two efforts did not work I may be able to develop a patch and submit a PR.

**Comment by jcameron** [comment]
Webmin should pick up the aliases file automatically based on the reference to it from `sendmail.cf` . If you run `grep aliases /etc/mail/sendmail.cf` , what does it output?

**Comment by gjpc** [comment]
` grep aliases /etc/mail/sendmail.cf
O AliasFile=/etc/mail/aliases
# verify RHS in newaliases?
# local host aliases and pseudo-domains are always canonical
###   Ruleset 5 -- special rewriting after aliases have been expanded   ###
# deal with plussed users so aliases work nicely
`

**Comment by jcameron** [comment]
Ok, I see the bug that causes this - it will be fixed in the next Webmin release.

**Comment by gjpc** [comment]
Outstanding!  Thanks!

**Comment by gjpc** [comment]
Hi jcameron,

I just had time this morning to test your change. Unfortunately I have to report that it has had no effect.

I added the @ sign to the push call, in backup_config.pl, restarted webmin, deleted the old backup.tgz and ran backup with the button. the file **aliases** is still not being backed up.
