### ISSUE TITLE
to much escaping in mount module?

### ISSUE THREAD

**Issue by gnadelwartz** [webmin/webmin#751]
somewhere between Christmas and yesterday a patch introduced to much HTML escaping in module mount:
![screenshot_20171230-172904](https://user-images.githubusercontent.com/4593242/34461775-20c2f2e6-ee34-11e7-9be4-57bef4628e21.png)

note root and virtual

**Comment by qooob** [comment]
Yes, we discussed it and it's expected.

I think we only should filter content that is coming from some other user, like directory name in File Manager or some other very rare cases. Otherwise, we will break more that gain.

**Comment by gnadelwartz** [comment]
what about not escaping some HTML tags lkie <i> and <tt>? so we can use them in e.g. language strings but avoid also injected HTML by file names and user Imput?

**Comment by jcameron** [comment]
You're right, this is indeed escaped too much. I'll fix it in the next Webmin release.
