### ISSUE TITLE
Unable to access remote Webmin via "Login via Webmin with username"

### ISSUE THREAD

**Issue by speedaemon1** [webmin/webmin#763]
I have been trying to use the Webmin Servers Index to access remote Webmin servers from central Webmin Server.  In the past I have been able to accomplish this while using "Login via Webmin with username" link type selected for each remote Webmin Server.  Not long ago this functionality stopped causing the request to circle back to the central Webmin Server.  For example, I log-in to Server A...access the Webmin Server Index page and select Server B...a new page appears displaying the information (Dashboard) for Server A.  This happens for any remote server where the "Login via Webmin with username" Link Type is selected.  If I use the "Normal Link to server" Link Type selection it works fine (just have to log in for each server).

I am using Webmin version 1.870 on all servers (central and remote) using Debian (Version 8) on most (1 Ubuntu server; version 16,04.3).  I am currently using the Authentic Theme (version 19.04) and have seen a similar issues (https://github.com/qooob/authentic-theme/issues/147).  If I try the "Gray Framed Theme" or "Old Webmin Theme" it still takes me to the Central server (Server A in example above) but no Dashboard ever displays (only the menu to the left) and the red progress bar at the top bounces back and forth from left to right and back (using the "Authentic Theme").

Any thoughts or help would be great.

**Comment by qooob** [comment]
Hi,

We have made quite a lot of improvements and bug fixes since Authentic Theme 19.04. The exact issue for Servers Index been fixed starting from 19.05, two hours ago, I updated to 19.08 that is most accurate release of 19 branch. 

Please use theme's configuration page to Force Update to the latest stable version.

Servers Index should not have any issues. I tested it quite a lot, with stored login and password in SI module.

Please tell us more if it works or not for you, and if we could provide more information.

**Comment by speedaemon1** [comment]
I update to 19.08 but it did not resolve the issue.  Is there any other thoughts on what the issue may be or possible solutions.  Let me know if there is any additional information I can provide which may help troubleshoot.

**Comment by qooob** [comment]
Can you share the screenshot with configuration for the server index? You can choose the actual names but keep the pattern.

**Comment by qooob** [comment]
I completely forgotten. Webmin fix is also needed. It's only the part of 1.872+.

In case you don't have it installed please use this patch.

https://github.com/webmin/webmin/commit/7dfa97c6ca703f814cff4cd1a65c50bf0232315f

**Comment by qooob** [comment]
I completely forgotten. Webmin fix is also needed. It's only the part of 1.872+.

In case you don't have it installed please use this patch.

https://github.com/webmin/webmin/commit/7dfa97c6ca703f814cff4cd1a65c50bf0232315f

**Comment by speedaemon1** [comment]
I patched the central server and it appears to work for all remote servers except for 1.  It still routes back to the central server.  Can you think of any reason why it would not work for the one remote server.

**Comment by qooob** [comment]
Stuck cache? Restart Webmin?

**Comment by speedaemon1** [comment]
Restarted Webmin on both servers and also rebooted the servers and no change.

**Comment by qooob** [comment]
You you sure that you patched files on both servers and updated themes to 19.08, the only thing left is browser's cache.

There should be no problem. It's just must work. Make sure that you really patched and updated everything.

**Comment by speedaemon1** [comment]
Found the issue...didn't actual upgrade the Authentic-Theme on the remote server to 19.08 as I thought I had done.  Works now...Thanks and appreciate your help and patience.

**Comment by qooob** [comment]
I'm glad it worked.

You're welcome.

Tell us if we could help you any further.
