### ISSUE TITLE
Feature request fail2ban use jail.local instead jail.conf by default

### ISSUE THREAD

**Issue by Vagrantin** [webmin/webmin#764]
I'm running Webmin 1.870 on Debian 9 with fail2ban 0.9.6 ( not tested any other version)
I noticed that when setting up Fail2ban with Webmin, any config changes are set on the ``.conf`` file instead of ``.local`` file.
The issue here is in case of an upgrade of fail2ban you'll most-likely loose your configuration and get back to the basic setup.
As a start using ``jail.local`` instead of ``jail.conf`` would be very nice.

Matth

**Comment by gnadelwartz** [comment]
From reading the source I would say fail2ban module write config to the same file it was read from.

I would support your request that the new/changed config should instead written to the responding `.local` file, e.g. if its read form `fail2ban.conf` write to  `fail2ban.local`.

**Comment by jcameron** [comment]
That's correct, currently changes are written to the same config file they are read from.

However, this should be fine - package managers won't over-write config files on upgrade.

**Comment by Vagrantin** [comment]
then maybe it could be good at the first setup to save data in a jail.local?
the advantages i'm seeing here is when new features are coming in the jail.conf, you can take advantages of it if you have a higly customized one.
At the end of the day if package managers don't over-write the config files there is not much point bothering with this feature.
I'll work that way only for myself  :)
thanks

**Comment by gnadelwartz** [comment]
the reason for .local files is exactly like you described, new features in macros etc.
pls reopen the issue, l'll have a deeper look if there is an easy way to save at least new settings in .local

there are also parsing issues because of the meanwhile very complex fail2ban configuration macros. and the additional .local files

**Comment by swelljoe** [comment]
I have to agree on this one. jail.local is really what we ought to be editing, per the recommendations from the project itself. There's another issue I opened a while back about a related issue, not sure if it got sorted: https://github.com/webmin/webmin/issues/599

I don't think there'd be any negative to leaving jail.conf alone and only adding to jail.local. It even kinda simplifies logic (which is currently a little bit broken).

**Comment by Vagrantin** [comment]
Also introducing what fail2ban calls **internal interpolation**, what i understand as **variables** would be interesting to have in the UI, but maybe a different Feature request is required.

**Comment by gnadelwartz** [comment]
@swelljoe  IMHO jamie fix the read order, but the problem of having different parsing results beween f2b and webmin sometimes remain

**Comment by gnadelwartz** [comment]
@Vagrantin yes this would be nice, but also means implement a parser for all f2b macro and variables logic :-( and I fear this will be impossible.

for now we should should keep it simple and if you want to benefit from these features you have to fill the values by hand. Nevertheless webmin can read and display these handcrafted rules, but not interpret them.

fail2ban pr

**Comment by qooob** [comment]
Why not just create the symlink?

**Comment by jcameron** [comment]
Ok, I'll see about having webmin update jail.local instead

**Comment by gnadelwartz** [comment]
So, whats the outcome of https://github.com/webmin/webmin/issues/599#issuecomment-356954688 for saving changes in jail.local instead of original file?

- not all changes can go to jail.local, because jail.d/*.local overrides them
-  changes should instead go to the corresponding .local file:
    jail.conf -> jail.local
    jail.d/xxx.conf -> jail.d/xxx.local

**Comment by jcameron** [comment]
I've started working on support for updating .local file instead of .conf , but I have a question for fail2ban experts - do all version support .local files by default, or is it a recent thing?

Also, any directive or section that already exists in a .local file will already by updated by Webmin. The only thing that's not supported is adding a new .local file if one is completely missing.

**Comment by swelljoe** [comment]
I don't know if it is all versions, but it is not recent. It dates back to at least the version shipped with CentOS 6, which is the oldest version Virtualmin supports, and probably the oldest non-EOL distribution that Webmin supports. It has the same recommendation to not modify jail.conf and instead use jail.local (and it has a jail.d, as well) in the jail.conf file.

I think it is safe to assume every fail2ban installation on a maintained system has jail.local and jail.d.

**Comment by gnadelwartz** [comment]
yes, I've neverseen a fail2ban config without an existing .local file

**Comment by jcameron** [comment]
In the next Webmin release, all updates will happen in .local files.
