### ISSUE TITLE
Shoreline Firewall submit buttons

### ISSUE THREAD

**Issue by qooob** [webmin/webmin#765]
Jamie, could fix submit buttons, that are placed again outside of the form. We had familiar issues in Linux Firewall module?

https://github.com/qooob/authentic-theme/issues/957
https://github.com/qooob/authentic-theme/issues/899#issuecomment-356293765

**Comment by jcameron** [comment]
Sure ... done!

**Comment by qooob** [comment]
Thanks. I expect it will also affect Shoreline6.
