### ISSUE TITLE
MySQL/PostgreSQL - missing manually edit config file

### ISSUE THREAD

**Issue by qooob** [webmin/webmin#766]
Jamie, hi.

I just relalised that we're missing an ability to manually edit config files in MySQL/PostgreSQL modules. I think this crucial to have.

Could you do it?

**Comment by jcameron** [comment]
Do you mean for files like `my.cnf` ?

**Comment by qooob** [comment]
Yes, and from `my.cnf` and `/etc/my.cnf.d/`.

**Comment by jcameron** [comment]
I'll add this to my TODO list

**Comment by jcameron** [comment]
This has been implemented for mysql and postgresql, for inclusion in the next release.

**Comment by qooob** [comment]
Thanks a lot, Jamie. I will make sure that the code highlight is working properly for this module as well.

There is an issue though, with paths and double `//` in select. Take a look at the screenshot.

![screenshot from 2018-01-29 13-04-49](https://user-images.githubusercontent.com/4426533/35504905-6c59c784-04f5-11e8-8b13-29e465dae9b1.png)

**Comment by qooob** [comment]
Besides, could you please add this `onchange_form_submit_triggger` class on select or add `onchange` attr with `form.submit()` as you used to do?

**Comment by qooob** [comment]
One more, thing. You used to use for name _attr_ in _select_ value `file` but not `manual`. It's better not to alternate the core triggers. Could you also fix it to `file` from `manual`?

**Comment by jcameron** [comment]
Do you mean the name of the CGI script?

**Comment by qooob** [comment]
I meant:

```
$in{'file'}
ui_select("file" ...)
```

**Comment by qooob** [comment]
...but okay, I will make theme recognize it as well.

Please fix `//` issue as in screenshot. My installation has in config:

```
# Import all .cnf files from configuration directory
!includedir /etc/mysql/conf.d/
!includedir /etc/mysql/mariadb.conf.d/
```

It ends with `/` and results in `//` in the select.
