### ISSUE TITLE
proposal: move module desc to lang files ...

### ISSUE THREAD

**Issue by gnadelwartz** [webmin/webmin#770]
move module desc to lang files and add them to module.info when creating release tarballs.

having different encodings and the mix of unicode and ASCII in `module.info` often leads to confusion by humans and editors. moving the desccription strings to the corresponding lang files should solve this problems and translators have no more to deal with module.info.

after creating the UTF-8 language files for a release, we add the descriptions to module.info for release again, basicly something like this, but more sohpisticated:

 `grep "^desc|^longdesc" lang/* >> module.info`

As a bonus we will have all descritpions in UTF-8 encodings availible in module.info.

**Comment by jcameron** [comment]
I'm actually thinking of going the other way - update all modules' index.cgi pages to not use `index_title` from the lang file, and instead use `$module_info{'desc'}`

**Comment by gnadelwartz** [comment]
that will fit, because after installation/update the desc is in module.info.
I want only to avoid mixing encoding while developing.

**Comment by gnadelwartz** [comment]
here is a script moving all desc from module.info to lang files on a fresh  clone from repo.

- skip move if no lang dir exsit
- keep english desc in module.info as fallback
- add english desc to lang file if no desc_lang exist

if not argument is given it processes only apache as testcaae
for processing all modules run `./move2lang.sh */module.info`

whats now missing is to extend setpup.sh to copy vaules bak while setup

``` .sh
#!/bin/bash
# move2lang.sh
# move descriptions out of module,info
FILES=apache/module.info
[ "$1" != "" ] && FILES="$*"

for file in $FILES
do
    echo "processing $file ..."
    # get dir
    dir=`dirname $file`
    [ ! -d "$dir/lang" ] && echo "skipping $dir: no lang dir" && continue
    # move to temp file
    sed '/desc_.*=/d' $file >$file.tmp
    grep -a -e '^desc' -e '^longdesc' $file | sort >$file.desc
    mv $file.tmp $file

    # move desc to lang files
    for line in `ls $dir/lang`
    do
        lang="_$line"
        [ "$lang" = "_en" ] && lang=""
        sed -n  "s/^desc$lang=/desc=/p" $file.desc >$dir/lang/$line.tmp
        sed -n  "s/^longdesc$lang=/longdesc=/p" $file.desc >>$dir/lang/$line.tmp
        if [ ! -s "$dir/lang/$line.tmp" ]
        then
            sed -n  "/^desc=/p" $file.desc >$dir/lang/$line.tmp
            sed -n  "/^longdesc=/p" $file.desc >>$dir/lang/$line.tmp
        fi
        cat $dir/lang/$line >>$dir/lang/$line.tmp
        mv $dir/lang/$line.tmp $dir/lang/$line
    done
done
echo "cleanup ..."
rm -f */module.info.desc */*.tmp */*/*.tmp

```

**Comment by gnadelwartz** [comment]
best place may be in chinese-to-uft8.pl:

``` .pl
diff -c webmin/chinese-to-utf8.pl  webmin-desc/chinese-to-utf8.pl
*** webmin/chinese-to-utf8.pl  2018-01-15 13:47:44.492182059 +0100
--- webmin-desc/chinese-to-utf8.pl      2018-01-15 13:46:47.961211910 +0100
***************
*** 119,124 ****
--- 119,135 ----
                                &DefaultToUTF8($minfo{'desc_'.$l});
                        }
                }
+       # copy module desc from lang files to module.info
+       opendir(DIR, "$m/lang");
+       foreach $l (readdir(DIR)) {
+               local $desc='desc_'.$l;
+               $desc='desc' if ( $l == 'en' );
+               local %dinfo;
+               &read_file("$m/lang/$1", \%dinfo);
+               $minfo{$desc} = $dinfo{'desc'};
+               $minfo{'long'.$desc} = $dinfo{'longdesc'};
+
+       }
        &write_file_diff("$m/module.info", \%minfo);

        # Translate the config.info file
```

**Comment by gnadelwartz** [comment]
so far it seem to work ...

original apache/module.info

> desc_nl=Apache Webserver
> desc_ko_KR.euc=Apache webServer
> risk=low medium high
> desc_ru_SU=▒▒▒ ▒▒▒▒▒▒ Apache
> desc_zh_TW.Big5=Apache ▒▒▒A▒▒
> desc_pl=Apache - serwer WWW
> desc_de=Apache Webserver
> name=Apache
> desc_zh_CN=Apache ▒▒▒▒▒▒
> desc_pt=Servidor Web Apache
> category=servers
> desc_tr=Apache Web Sunucusu
> os_support=solaris *-linux aix hpux freebsd osf1 irix unixware openserver macos openbsd netbsd windows
> desc=Apache Webserver
> desc_es=Servidor Web Apache
> desc_sv=Apache Webserver
> desc_fr=Serveur Web Apache
> desc_hu=Webszerver (Apache)
> desc_ru_RU=▒▒▒ ▒▒▒▒▒▒ Apache
> desc_ca=Servidor Web Apache
> longdesc=Configure almost all Apache directives and features.
> desc_bg=����� ��� ������
> desc_ja_JP.euc=Apache Web▒▒▒▒▒▒
> readonly=1
> syslog=1
> desc_zh_TW.UTF-8=Apache 網頁伺服器
> desc_zh_CN.UTF-8=Apache 服务器
> desc_ja_JP.UTF-8=Apache Webサーバ
> desc_ko_KR.UTF-8=Apache webServer
> desc_da=Apache Webserver
> desc_cz=Apache WWW server
> desc_ru.UTF-8=Веб сервер Apache
> desc_pt_BR=Servidor Web Apache
> desc_hu.UTF-8=Apache Webkiszolgáló
> desc_cz.UTF-8=Apache WWW server
> desc_pl.UTF-8=Serwer WWW Apache
> desc_no=Apache Webtjener
> longdesc_hu=Apache direkt▒v▒k ▒s szolg▒ltat▒sok be▒ll▒t▒sa
> longdesc_ms_MY=Mengkonfigurasi hampir kesemua arahan Apache dan ciri-ciri yang ada.
> desc_ms_MY=Pelayan Web Apache
> longdesc_de=Konfiguriert fast alle Apache-Direktiven und Features.
> longdesc_pl=Konfiguracja niemal wszystkich opcji i dyrektyw Apache.
> longdesc_ca=Configura gaireb▒ totes les directives  caracter▒stiques d'Apache.

apache/module.info after moving desc to lang

> risk=low medium high
> name=Apache
> category=servers
> os_support=solaris *-linux aix hpux freebsd osf1 irix unixware openserver macos openbsd netbsd windows
> desc=Apache Webserver
> longdesc=Configure almost all Apache directives and features.
> readonly=1
> syslog=1

apache/module.info after chinese-to-utf8.pl with all existing and not existing translations:

> risk=low medium high
> name=Apache
> category=servers
> os_support=solaris *-linux aix hpux freebsd osf1 irix unixware openserver macos openbsd netbsd windows
> desc=Apache Webserver
> longdesc=Configure almost all Apache directives and features.
> readonly=1
> syslog=1
> longdesc_en.UTF-8=Configure almost all Apache directives and features.
> desc_pt.UTF-8=Servidor Web Apache
> desc_cz.UTF-8=Apache WWW server
> longdesc_uk_UA.UTF-8=Configure almost all Apache directives and features.
> desc_nl=Apache Webserver
> desc_no=Apache Webtjener
> longdesc_no=Configure almost all Apache directives and features.
> desc_gr=Apache Webserver
> desc_ja_JP.euc=Apache Web▒▒▒▒▒▒
> desc_ru.UTF-8=Веб сервер Apache
> desc_ms_MY.UTF-8=Pelayan Web Apache
> desc_hu=Webszerver (Apache)
> desc_uk_UA=Apache Webserver
> longdesc_gr=Configure almost all Apache directives and features.
> longdesc_de.UTF-8=Konfiguriert fast alle Apache-Direktiven und Features.
> desc_bg=����� ��� ������
> desc_it.UTF-8=Apache Webserver
> desc_ru_RU=▒▒▒ ▒▒▒▒▒▒ Apache
> longdesc_fa=Configure almost all Apache directives and features.
> desc_sv=Apache Webserver
> longdesc_fr=Configure almost all Apache directives and features.
> longdesc_cz.UTF-8=Configure almost all Apache directives and features.
> longdesc_fr.UTF-8=Configure almost all Apache directives and features.
> longdesc_zh_CN=Configure almost all Apache directives and features.
> desc_es=Servidor Web Apache
> desc_da=Apache Webserver
> desc_hr=Apache Webserver
> longdesc_zh_TW.UTF-8=Configure almost all Apache directives and features.
> longdesc_it=Configure almost all Apache directives and features.
> longdesc_ru.UTF-8=Configure almost all Apache directives and features.
> desc_de.UTF-8=Apache Webserver
> desc_hu.UTF-8=Webszerver (Apache)
> longdesc_it.UTF-8=Configure almost all Apache directives and features.
> longdesc_da.UTF-8=Configure almost all Apache directives and features.
> desc_uk_UA.UTF-8=Apache Webserver
> desc_zh_TW.Big5=Apache ▒▒▒A▒▒
> longdesc_ru_SU=Configure almost all Apache directives and features.
> longdesc_hr=Configure almost all Apache directives and features.
> longdesc_pt_BR=Configure almost all Apache directives and features.
> desc_ja_JP.UTF-8=Apache Webサーバ
> longdesc_pl=Konfiguracja niemal wszystkich opcji i dyrektyw Apache.
> longdesc_ja_JP.euc=Configure almost all Apache directives and features.
> longdesc_ru_RU.UTF-8=Configure almost all Apache directives and features.
> longdesc_ru_RU=Configure almost all Apache directives and features.
> desc_ko_KR.euc=Apache webServer
> desc_nl.UTF-8=Apache Webserver
> desc_ru_RU.UTF-8=Веб сервер Apache
> desc_es.UTF-8=Servidor Web Apache
> longdesc_bg.UTF-8=Configure almost all Apache directives and features.
> longdesc_es.UTF-8=Configure almost all Apache directives and features.
> longdesc_sv.UTF-8=Configure almost all Apache directives and features.
> longdesc_nl.UTF-8=Configure almost all Apache directives and features.
> longdesc_ca=Configura gaireb▒ totes les directives  caracter▒stiques d'Apache.
> longdesc_ms_MY.UTF-8=Mengkonfigurasi hampir kesemua arahan Apache dan ciri-ciri yang ada.
> desc_ca=Servidor Web Apache
> longdesc_ca.UTF-8=Configura gairebé totes les directives  característiques d'Apache.
> desc_fr.UTF-8=Serveur Web Apache
> desc_pl=Apache - serwer WWW
> desc_it=Apache Webserver
> longdesc_pt=Configure almost all Apache directives and features.
> desc_zh_TW.UTF-8=Apache 網頁伺服器
> desc_zh_CN.UTF-8=Apache 服务器
> longdesc_nl=Configure almost all Apache directives and features.
> longdesc_ja_JP.UTF-8=Configure almost all Apache directives and features.
> desc_de=Apache Webserver
> longdesc_no.UTF-8=Configure almost all Apache directives and features.
> longdesc_ko_KR.UTF-8=Configure almost all Apache directives and features.
> longdesc_cz=Configure almost all Apache directives and features.
> desc_fa=Apache Webserver
> desc_ca.UTF-8=Servidor Web Apache
> longdesc_ko_KR.euc=Configure almost all Apache directives and features.
> longdesc_pt_BR.UTF-8=Configure almost all Apache directives and features.
> desc_pt_BR.UTF-8=Servidor Web Apache
> longdesc_tr=Configure almost all Apache directives and features.
> longdesc_uk_UA=Configure almost all Apache directives and features.
> longdesc_pl.UTF-8=Konfiguracja niemal wszystkich opcji i dyrektyw Apache.
> longdesc_da=Configure almost all Apache directives and features.
> desc_zh_CN=Apache ▒▒▒▒▒▒
> desc_en.UTF-8=Apache Webserver
> desc_pl.UTF-8=Apache - serwer WWW
> desc_tr=Apache Web Sunucusu
> desc_ru_SU=▒▒▒ ▒▒▒▒▒▒ Apache
> desc_cz=Apache WWW server
> longdesc_hu.UTF-8=Apache direktívák és szolgáltatások beállítása
> longdesc_ms_MY=Mengkonfigurasi hampir kesemua arahan Apache dan ciri-ciri yang ada.
> desc_no.UTF-8=Apache Webtjener
> longdesc_zh_CN.UTF-8=Configure almost all Apache directives and features.
> longdesc_sv=Configure almost all Apache directives and features.
> desc_ms_MY=Pelayan Web Apache
> longdesc_pt.UTF-8=Configure almost all Apache directives and features.
> desc_sv.UTF-8=Apache Webserver
> desc_ko_KR.UTF-8=Apache webServer
> longdesc_hu=Apache direkt▒v▒k ▒s szolg▒ltat▒sok be▒ll▒t▒sa
> desc_bg.UTF-8=пїЅпїЅпїЅпїЅпїЅ пїЅпїЅпїЅ пїЅпїЅпїЅпїЅпїЅпїЅ
> desc_pt_BR=Servidor Web Apache
> desc_da.UTF-8=Apache Webserver
> longdesc_bg=Configure almost all Apache directives and features.
> desc_fr=Serveur Web Apache
> longdesc_es=Configure almost all Apache directives and features.
> longdesc_zh_TW.Big5=Configure almost all Apache directives and features.
> desc_pt=Servidor Web Apache
> longdesc_de=Konfiguriert fast alle Apache-Direktiven und Features.

**Comment by gnadelwartz** [comment]
one remaining question:

whats the correct UTF-8 sting for en in module.info?

- desc_en.UTF-8=Apache Webserver
- desc.UTF-8=Apache Webserver

**Comment by gnadelwartz** [comment]
for script and changes to chinese-to-utf-8.pl see https://github.com/webmin/webmin/pull/776/files

**Comment by jcameron** [comment]
So if all desc= lines are moved out of module.info  file, how are they going to be populated in the code that uses them - for example, when the left menu of modules is displayed?

**Comment by gnadelwartz** [comment]
they are copied back to module.info when making a release, so they are availible as before, see #776 

this sounds stupid first, but has an important advantage: no more mixed charsets and no more accidently damaged descriptions while developing. this hits me many times when my editor guesses a wrong charset

**Comment by jcameron** [comment]
Yeah, having mixed character sets in module.info files does cause problems. 

Maybe a better option is separate `module.info.$LANG` files, which are merged by Webmin at runtime?

**Comment by gnadelwartz** [comment]
This was my first idea, but then we may have many additional files with max 2 lunes, possibly doubled after converting to utf-8. since I already don't like these many config-info files I avoid this route.

**Comment by gnadelwartz** [comment]
As an alternative we can move them to config-info lang files, but I fear this will irritate the modul configuration ...

**Comment by jcameron** [comment]
I think the `module.info.LANG` files are the most consistent solution with the rest of Webmin. I'll work on implementing this, and update this  bug ..

**Comment by jcameron** [comment]
Ok, all webmin core module.info files have had their language-specific desc_XX lines extracted to new module.info.XX files. This is committed to github, and will be included in the next release.
