### ISSUE TITLE
download.webmin.com is not avalaible

### ISSUE THREAD

**Issue by MarkyMarc35** [webmin/webmin#772]
Hello,
I'm trying to install webmin on my Ubuntu 16.04 but download.webmin.com always return as not avalaible.
 
Failed to fetch http://download.webmin.com/download/repository/dists/sarge/InRelease  Could not connect to download.webmin.com:80 (108.60.199.109), connection timed out

Marc

**Comment by jcameron** [comment]
Try again .. it's back up now.
