### ISSUE TITLE
Debian package 1.872

### ISSUE THREAD

**Issue by Vagrantin** [webmin/webmin#777]
Hello,

Simple question, I notice webmin is now in 1.872, but if i try to update it through admin interface  
```
Webmin configuration > upgrade webmin > latest version from webmin.com
```
It says i'm running the latest version.

Also If i'm trying to upgrade it through ``aptitude`` same thing I'm running the latest version.  
Is this version is kind of a beta something like that ? 

Thanks for the clarification

**Comment by gnadelwartz** [comment]
the latest release is 1.870, see  https://github.com/webmin/webmin/releases .
Latest development version is 1.872.

to update to latest dev version run `./update-from-repo` in webmin dir ..

**Comment by Vagrantin** [comment]
Ah ok understand now, version 1.872 is commit on Master branch so I guessed it was the official release.
Thanks for the clarification
