### ISSUE TITLE
Command Shell: Truncated output

### ISSUE THREAD

**Issue by qooob** [webmin/webmin#778]
Jamie, hi.

Is this really necessary to truncate output??

When running simple `ls -lsaZ /usr/lib64/` you get this:

```
...
16600 -rwxr-xr-x.  1 root root    system_u:object_r:lib_t:s0           16996720 Aug  6 18:26 libgdal.so.20.1.4
    0 lrwxrwxrwx.  1 root root    system_u:
Total output of 270.32 kB was truncated at 97.66 kB.
```

Can the size be increased to something more real?

**Comment by jcameron** [comment]
There's an option on the config page for the command shell module that controls how much output is displayed.

**Comment by qooob** [comment]
Ohh, I should've checked that first.  :open_mouth:

Sorry. Thanks.
