### ISSUE TITLE
*/lang/ar files will not be convertedt to UTF-8

### ISSUE THREAD

**Issue by gnadelwartz** [webmin/webmin#780]
while testing to move desc to lang files, I noticed that some modules have lang files which will not converted to UTF-8:

`acl/lang/ar  adsl-client/lang/ar` same for `*/lang/fa`

is this because they are rtl languages?

**Comment by jcameron** [comment]
No, it's because the UTF-8 conversion script currently doesn't support that character set.

**Comment by gnadelwartz** [comment]
does iconv support them?

**Comment by jcameron** [comment]
So maybe I should just update the character set in the `lang_list.txt` file?

**Comment by gnadelwartz** [comment]
fa is already declared as utf-8 in lang_list.txt
