### ISSUE TITLE
is it save to offer install button in software/edit_pack.cgi?

### ISSUE THREAD

**Issue by gnadelwartz** [webmin/webmin#786]
Will it be save to offer an istall button in `software/edit._pack.cgi` if software is not installed?

For my `ipkg-lib.pl `its save, but I don't know if it may not work with other software-libs ...

![image](https://user-images.githubusercontent.com/4593242/35386857-cbfcea02-01cd-11e8-858e-277d37bf0cdd.png)

**Comment by gnadelwartz** [comment]
nevertheless I can not figure out the correct parameters for do_install.cgi, seems to be magic :-(

**Comment by qooob** [comment]
There are entries populated from URI into `%in` hash that are passed to `do_install.cgi`? There are some other vars that are initialized from embedded libs.

This is my very quick guess. I don't know exactly what you're doing.

**Comment by jcameron** [comment]
The `edit_pack.cgi` script is only supposed to be run for packages that are actually installed. Any new package system code in the `software` module shouldn't include packages that aren't installed yet.

**Comment by gnadelwartz** [comment]
hm, so also tree should only show installed packages?

**Comment by gnadelwartz** [comment]
IMHO edit package is a bit misleading, in practice it edits nothing. it simply display package details and optionally offer list files and uninstall.

a better name may Package Details

**Comment by jcameron** [comment]
I think the right place for installing packages is the Software Package Updates module.

**Comment by gnadelwartz** [comment]
i'll have a look ...

**Comment by gnadelwartz** [comment]
Done, see https://github.com/webmin/webmin/pull/785

**Comment by jcameron** [comment]
Thanks!
