### ISSUE TITLE
Install Updates Button needs better placement.

### ISSUE THREAD

**Issue by f3bruary** [webmin/webmin#804]
I got Mono installed on my machine and each time there's an update, it's for +150 packages at once. When there are updates, I have to scroll down all the packages and click Update Selected Packages. Then I have to scroll all the way up again to click Install.

Surely this can be improved?

**Comment by qooob** [comment]
It's possible to improve. I will be able to add pagination to the table, I think.  Is it Software Update Packages module?

By the way, why not just hitting end button on the keyboard to be to the bottom of the page?

**Comment by gnadelwartz** [comment]
I provided ad PR to add the buttons also on the top of the list ...

**Comment by gnadelwartz** [comment]
@f3bruary  your request will included in the next release.

if you want to test it now, go to your webmin installtion dir and run `./update-from-repo.sh -force`

**Comment by gnadelwartz** [comment]
@jcameron can be closed
