### ISSUE TITLE
webmin.com down?

### ISSUE THREAD

**Issue by gnadelwartz** [webmin/webmin#812]
webmin reports only an ngix not found message

**Comment by swelljoe** [comment]
It's a SourceForge thing. Someone from SF.net said it'd be back "soon" a couple days ago...still down. Not sure why, as their status blog posts indicate the outage is over. I think we're bringing something up on one of our servers today since this isn't the first long SF outage.

**Comment by gnadelwartz** [comment]
yes, this us bad and i did nit expect such outages from sf side, it was a highly reputated site for a long time ...

besides i was already wondering about the "double" bugtracker on sf and gh  :)

**Comment by jcameron** [comment]
It's back now though.

**Comment by gnadelwartz** [comment]
Project web is currently offline pending the final migration of its data to our new datacenter.

**Comment by gnadelwartz** [comment]
back again

**Comment by qooob** [comment]
But, it's so slow now?

**Comment by qooob** [comment]
Also, certificate needs to be fixed.
