### ISSUE TITLE
Cannot add server to cluster servers

### ISSUE THREAD

**Issue by anotherMe** [webmin/webmin#813]
Hello, I'm running webmin 1.870 on Debian 9 (amd64). Let's call this box **MACHINE_A**.

I've added one of my other webmin servers ( call it **MACHINE_B** ) to the "Webmin Servers Index" so when I open the "Cluster Webmin Servers" page, I see **MACHINE_B** in the drop down beside the "Add server" button.

The problem is, when I select **MACHINE_B** and I push the "Add Server" button, nothing happens. Same if I try to add **MACHINE_A** ( aka "this server" ) machine.

It seems there is something wrong in the HTML of the "Cluster Webmin Servers" page:

```
...
    <form action="add.cgi"></form>
    <td>
    <input type="submit" name="add" value="Add server" class="btn btn-default">
    <select name="server" class="heighter-34">
    <option value="0">MACHINE_A (this server)</option>
    <option value="183475039">MACHINE_B</option>
    </select>
    </td>
...
```

As you can see, **input** elements are outside of the **form** element, so when you push the submit button, nothing happens.

PS: It's the same problem for the "Add group" function.

**Comment by qooob** [comment]
It's been fixed few weeks ago.

Thank you for reporting.

**Comment by anotherMe** [comment]
I see, thank you.
