### ISSUE TITLE
Ubuntu Repo not up to date.

### ISSUE THREAD

**Issue by eangulus** [webmin/webmin#826]
Latest version on Ubuntu Repo is 1.870 instead of 1.873

**Comment by vampywiz17** [comment]
I think tke latest stable is 1.870

**Comment by eangulus** [comment]
Webmin itself says it's out of date, and also authentic them is complaining about version too.

**Comment by jcameron** [comment]
The repos intentionally contain only the stable versions.

**Comment by eangulus** [comment]
If that's the case, then why is Webmin telling me it's out of date if it cannot update? Should it only tell me it's out of date if the repo version is actually higher?

This has never happened before in the 5+ years I have been using it, only happened since the Webmin site went down for a few days.

**Comment by jcameron** [comment]
What's the error you're seeing in Webmin exactly?

**Comment by eangulus** [comment]
On the System Info Page the Webmin Version is in RED and when you hover it, it reads "This version is outdated"

**Comment by qooob** [comment]
Yes, it's what the theme reports, because theme expects it to be outdated.

I made this premise based on RHEL repo, that has Webmin 1.872 in it. Isn't Debian repos are in logical sync with RHEL?

**Comment by qooob** [comment]
Webmin yum repo doesn't seem to contain 1.872 version but `http://software.virtualmin.com/gpl` does.

This is confusing.

**Comment by jcameron** [comment]
@iliaross - how does the theme detect what the latest version is?

**Comment by iliaross** [comment]
At the moment, it's just static, hardcoded values. Later, it will probably do online checking.

https://github.com/iliaross/authentic-theme/blob/master/authentic-funcs.pm#L56

**Comment by jcameron** [comment]
That's not a very reliable approach. Actually the theme shouldn't need to care or even check, as by default the system information page will display a message when a new version of Webmin is available.

**Comment by qooob** [comment]
Yes, I know. It was done at the beginning only for CSF to warn a user that old version is used. I added those just as an extension to the original idea. I could remove it or use only stable  numbers in the future.

Can user disable the version check? If so, after upgrading the theme and not upgrading Webmin, I think it's better to show such message to the user.

**Comment by jcameron** [comment]
Better maybe to add a check to the theme for the range of Webmin versions it supports.

**Comment by qooob** [comment]
I don't think it needs a range. In case user installs the theme that thinks that Webmin is too old, the version number will be wrapped in red block with tooltip, saying it's dated.

**Comment by jcameron** [comment]
Yes, the theme could detect what the min version of Webmin is that it's able to support, and display a warning if that's not met.

**Comment by Ryonez** [comment]
@jcameron 

Any chance you could make an actual dev branch to do updates and whatnot on?
I only found out about the repo having a version mismatch because authentic-theme is notifying me about an update I can't install. (Reference: https://github.com/authentic-theme/authentic-theme/issues/1167)

There is nothing in the readme or the installation instructions indicating that the repo is considered stable and the git dev. In fact the install instructions state:
> By adding the webmin repository and Jamie Cameron's key it is possible to install & maintain the latest Webmin/Usermin versions.

Could you please provide some clarification on what is happening please?

**Comment by swelljoe** [comment]
The issue here is in Authentic Theme. It shouldn't be suggesting development versions of Webmin.
