### ISSUE TITLE
systemd: incomplete service list

### ISSUE THREAD

**Issue by vampik** [webmin/webmin#829]
Webmin 1.870. Gentoo x86_64 with systemd.
Bootup and Shutdown is configured to use systemd.
The problem is that only a small part of services is shown in the list. 
I think there should be something similar to issue #430  - something causes subsequent calls to "systemctl show" to fail.

![webmin-1](https://user-images.githubusercontent.com/726409/36632174-1f6ebbba-1994-11e8-971f-d1ad82ed8de4.JPG)

[systemctl list-units --full --all.txt](https://github.com/webmin/webmin/files/1754603/systemctl.list-units.--full.--all.txt)

[systemctl list-unit-files.txt](https://github.com/webmin/webmin/files/1754590/systemctl.list-unit-files.txt)

[ls -la libsystemdsystem.txt](https://github.com/webmin/webmin/files/1754591/ls.-la.libsystemdsystem.txt)

**Comment by jcameron** [comment]
How many units are on your system, and how many appear in Webmin?

This may be related to #430, but on the other hand I don't see any template units in the output from `systemctl list-units --full --all.txt`

**Comment by vampik** [comment]
> How many units are on your system
systemctl list-units --full --all: 218 loaded units listed.
systemctl list-unit-files: 217 unit files listed.
> how many appear in Webmin?
47
> This may be related to #430, but on the other hand I don't see any template units in the output from
I mean that something causes "systemctl show" to fail. This does not necessarily mean that it should be a template.

**Comment by vampik** [comment]
There is one strange entry in Webmin service list: mariadb@bootstrap.service.d.service

Webmin erroneously assumes /lib/systemd/system/mariadb@bootstrap.service.d drop-in directory as a service.

Unfortunately, it is not the cause of this issue (missing services does not appear after removing this directory). Nonetheless, this is a bug too.

**Comment by jcameron** [comment]
I guess the only way to figure out what's failing would be to run `systemctl show` on each of the units on your system and see which produces an error. 

You could do this with a command like : 

```
for u in `systemctl list-units -t service --full --all --no-legend | awk '{ print $1 }'`; do systemctl show -- $u >/dev/null || echo $u failed; done
```

**Comment by vampik** [comment]
I've found it.

there is a following string in the"systemctl list-units --full --all" output:

218 loaded units listed.

Webmin parses "218" as a service name and systemctl throws this error:

Failed to get properties: Unknown object '/org/freedesktop/systemd1/job/218'.

**Comment by vampik** [comment]
Fixed by adding **--no-legend** to the command line:

`systemctl list-units --full --all --no-legend`

**Comment by jcameron** [comment]
Thanks - I'll have webmin use --no-legend in the next release.

**Comment by vampik** [comment]
> Thanks - I'll have webmin use --no-legend in the next release.

Consider adding this command line option to the `systemctl list-unit-files` call too, for consistency and to prevent potential errors.

**Comment by jcameron** [comment]
Will do
