### ISSUE TITLE
bind8: slave server IPs are not added to master

### ISSUE THREAD

**Issue by vampik** [webmin/webmin#832]
Software: Webmin 1.870, BIND 9.11.2_p1, Gentoo Linux

Action: Add a cluster slave server. Enable the following options: "Create secondary on slave when creating locally?" and "Create all existing master zones on slave?"

Expected behaviour: Existing zones are created on slaves. Slave server IPs are added to "also-notify" and "allow-transfer" blocks of the zones on master.

Actual result: Existing zones are created on slaves, but slave server IPs are not added to the zones on master. 

I've found that this functionality should exist for a long time: commit c9425917d5aca576363052a1a86e4814afa8e4bd but it seems that it doesn't work now.

New zones are created correctly because it is handled by another code: https://github.com/webmin/webmin/blob/master/bind8/bind8-lib.pl#L1882

Master's named.conf (zone names and IP addresses changed for security reasons):

```

zone "already.existing.zone" {
        type master;
        file "pri/already.existing.zone";
        };
zone "another.existing.zone" {
        type master;
        file "pri/another.existing.zone";
        };
zone "newly.created.zone" {
        type master;
        file "pri/newly.created.zone";
        also-notify {
                1.2.3.4;
                };
        allow-transfer {
                1.2.3.4;
                };
        notify yes;
        };
```

**Comment by jcameron** [comment]
Thanks - I see the cause of this, and will fix it in the next Webmin release.

**Comment by vampik** [comment]
Thanks. There is also a little inconsistency.

The code in https://github.com/webmin/webmin/blob/master/bind8/bind8-lib.pl#L1882 also adds `notify yes;` while the code in slave_add.cgi doesn't add this option.

This usually doesn't break the desired behaviour because the default value for `notify` is `yes`. But this may cause issues, for example, if a global notify statement exists in the config file.
