### ISSUE TITLE
bind8: default zone files permissions for slave zones are wrong

### ISSUE THREAD

**Issue by vampik** [webmin/webmin#834]
Software: Webmin 1.870, BIND 9.11.2_p1, Gentoo Linux

When creating a new zone, the zone file ownership is set to that of a parent directory by default. But permissions are not set and thus usually defaults to 0644.

This is usually not a problem for master zones. But default permissions for slave zones prevents zone transfer.

Directory for master zones: /var/bind/pri root:named 0750
Directory for slave zones: /var/bind/sec root:named 0770
Slave zones created as root:named 0644 -> no write permissions for named.

Currently one can set configuration option "file_owner" to, for example, named:named and/or "file_perms" to 0660, but that permssions would apply to master zones too which is unnecessary (master zones should be read-only).

I suggest to respect parent directory permissions when creating a zone file.
```
--- /usr/libexec/webmin/bind8/bind8-lib.pl.bak  2017-12-06 21:07:02.000000000 +0300
+++ /usr/libexec/webmin/bind8/bind8-lib.pl      2018-02-27 12:34:04.570000000 +0300
@@ -1472,15 +1472,15 @@
 sub set_ownership
 {
 my ($user, $group, $perms);
+if ($_[0] =~ /^(.*)\/([^\/]+)$/) {
+       # Match parent dir
+       my @st = stat($1);
+       ($perms, $user, $group) = ($st[2] & 0666, $st[4], $st[5]);
+       }
 if ($config{'file_owner'}) {
        # From config
        ($user, $group) = split(/:/, $config{'file_owner'});
        }
-elsif ($_[0] =~ /^(.*)\/([^\/]+)$/) {
-       # Match parent dir
-       my @st = stat($1);
-       ($user, $group) = ($st[4], $st[5]);
-       }
 if ($config{'file_perms'}) {
        $perms = oct($config{'file_perms'});
        }
```

**Comment by jcameron** [comment]
I don't think we can make  that change, because it would effect the behavior of other users' systems. Better to just fix your local perms for now.

**Comment by vampik** [comment]
Yes, "file_owner" and "file_perms" configuration options may be used as a workaround.

But there is a security issue: these permissions are applied to both master and slave zones.

**Comment by vampik** [comment]
Another possible solution: do not create a zone file when creating a slave zone. Let the BIND server create it automatically.

**Comment by jcameron** [comment]
The reason Webmin creates the slave zone file is to handle systems where the slave directory isn't writable by the `bind` user.

Maybe the solution is a separate permissions option for slave zones?

**Comment by vampik** [comment]
> Maybe the solution is a separate permissions option for slave zones?

Yes, that would be a good option.

**Comment by vampik** [comment]
If you implement this option, I also suggest to add the appropriate permissions to the default Gentoo config:
root:named 0750 for primary zones
root:named 0770 for slave zones

**Comment by jcameron** [comment]
This has been implemented for inclusion in the next release.
