### ISSUE TITLE
init: systemd auto-detection doesn't work on Gentoo

### ISSUE THREAD

**Issue by vampik** [webmin/webmin#835]
Webmin 1.870. Gentoo x86_64 with systemd.

Webmin does not detect SystemD if "Boot system" is set to "Detect automatically"

This happens because the detection code checks for existence of `$config{'init_base'}` for some reason. 

`init_base` doesn't exist in Gentoo config because Webmin doesn't support OpenRC.

I've just removed this check to fix the issue. I cannot understand why is it needed? This is a config option for old init-based systems.

```
--- /usr/libexec/webmin/init/init-lib.pl.bak    2017-12-06 21:16:48.000000000 +0300
+++ /usr/libexec/webmin/init/init-lib.pl        2018-02-27 18:06:57.716000000 +0300
@@ -62,8 +62,7 @@
        &execute_command("/sbin/init --version") == 0) {
        $init_mode = "upstart";
        }
-elsif ($config{'init_base'} && -d "/etc/systemd" &&
-       &has_command("systemctl") &&
+elsif (-d "/etc/systemd" && &has_command("systemctl") &&
        &execute_command("systemctl list-units") == 0) {
        $init_mode = "systemd";
        }

```

**Comment by jcameron** [comment]
You're right - I'll fix this in the 1.890 Webmin release.
