### ISSUE TITLE
German Lang

### ISSUE THREAD

**Issue by TMTYD** [webmin/webmin#836]
Hi

I have discovered two errors, you can fix them please.
![unbenannt](https://user-images.githubusercontent.com/29516076/36878280-744d34b2-1dbe-11e8-905c-e68fa9674815.png)

**Comment by gnadelwartz** [comment]
noticed this also. interestingly this happens only on my NAS, my Linux server displays März correct.

btw: welches NAS? Synology?

**Comment by qooob** [comment]
Are you using UTF8?

**Comment by TMTYD** [comment]
ich habe ein NAS mit debian stretch, habe mir das selber zusammen gebaut, also kein gekauftes NAS.

@iliaross 

I think, i use UTF8

I use DE UTF8

`
LANG=de_DE.UTF-8
LANGUAGE=
LC_CTYPE="de_DE.UTF-8"
LC_NUMERIC="de_DE.UTF-8"
LC_TIME="de_DE.UTF-8"
LC_COLLATE="de_DE.UTF-8"
LC_MONETARY="de_DE.UTF-8"
LC_MESSAGES="de_DE.UTF-8"
LC_PAPER="de_DE.UTF-8"
LC_NAME="de_DE.UTF-8"
LC_ADDRESS="de_DE.UTF-8"
LC_TELEPHONE="de_DE.UTF-8"
LC_MEASUREMENT="de_DE.UTF-8"
LC_IDENTIFICATION="de_DE.UTF-8"
LC_ALL=
`

**Comment by qooob** [comment]
:smiley: What is the output of the following command, if you run it on the browser's console?

```
get_server_data('charset')
```

**Comment by TMTYD** [comment]
```
>get_server_data('charset')
-su: Syntaxfehler beim unerwarteten Wort `'charset''
```

**Comment by qooob** [comment]
You need to run in in the tab, where your Webmin is opened.

Output as you provided simply not possible.

**Comment by qooob** [comment]
Oh, no, no. You mustn't run it on the regular console but in the browser's console.

**Comment by gnadelwartz** [comment]
To open console in Firefox type: `Ctrl + Shift + K`

**Comment by qooob** [comment]
Check for `Webmin/Webmin Configuration/Language` or/and `Webmin/Change Language and Theme` and make sure that you have it set to _UTF-8_ variant.

**Comment by TMTYD** [comment]
ok thx i have wrong language in the settings
