### ISSUE TITLE
Host of webmin(dot)com down?

### ISSUE THREAD

**Issue by JohanPirlouit** [webmin/webmin#837]
Hi Jamie, hi everyone,

I try to download the latest release of Webmin for five days now but _webmin.com_ is still unreachable, whatever browser I use..

Is the host of Webmin down? I still try but Webmin website is still unreachable... Even from the Webmin interface (I use Webmin version 1.850 with Authentic Theme on a Xubuntu 16.04 LTS).

Regards,
Johan

**Comment by qooob** [comment]
Unfortunately there is ongoing issue with _SourceForge_.

We're planning to move _Webmin_ site to the separate private server instead.

We're sorry about that.

**Comment by Syndrogo** [comment]
Do we have an ETA?

**Comment by JohanPirlouit** [comment]
@iliaross > Thanx for your answer ;-) .. In my case, I don't _require_ the very last release, so now that I know the reason why, I will wait until you find a good solution (and I won't say anything about SourceForge, that I know for years, because if I do, it may appear to be nothing but some kinf of troll)...

Regards,
Johan

**Comment by swelljoe** [comment]
Downloads are available here:

RPM: http://download.webmin.com/download/yum/

deb: http://download.webmin.com/download/deb/

Those are on our (Virtualmin) servers.

We don't have an ETA for SF coming back online; this is the second (ridiculously long) outage in just the past few days, so we have decided to get off of SourceForge. If they can't keep static sites up, I don't have a lot of confidence in their ability to do much else, at this point. It's frustrating, as we've been on SF for nearly 20 years. But, things change, and I guess they don't have a lot of resources these days (which I'm extremely sympathetic to, as we don't have a lot of resources, either!).

**Comment by chris001** [comment]
I suggest https://pages.github.com for webmin/virtualmin to host directly from your github repo.  You just edit, push, and your changes are live.  Tons and tons of github projects use this hosting service now, with extremely high uptime and performance.

**Comment by jcameron** [comment]
If it's not back tomorrow, I'm going to move the static pages to our own server.

**Comment by gnadelwartz** [comment]
can't find the tar.gz files on download area of dowload.webmin.com.
can you please provide them and remove the redirect to SF ...

**Comment by RaylynnKnight** [comment]
Doing apt update on Debian installs with sources.list entry of:
`deb http://download.webmin.com/download/repository sarge contrib`
that has worked for years is now resulting in the following error:
`E: The repository 'http://download.webmin.com/download/repository sarge Release' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.`

**Comment by Syndrogo** [comment]
@RaylynnKnight its because of the website outage

**Comment by jcameron** [comment]
Give it a shot now - the site should be back online

**Comment by gnadelwartz** [comment]
yeah, and it's really fast!

**Comment by chris001** [comment]
One small problem, https://webmin.com is using a self-signed cert, it needs some of that Let's Encrypt TLS cert goodness.

Also a good time to harden it by enabling DNSSEC, TLSA, HSTS, and Pinned public cert keys.

**Comment by jcameron** [comment]
Thanks, I'll fix that cert

**Comment by RaylynnKnight** [comment]
Working now and as mentioned it's much faster!

**Comment by gnadelwartz** [comment]
@jcameron solved, can be closed
