### ISSUE TITLE
Error when modifying an existing printer

### ISSUE THREAD

**Issue by mvglasow** [webmin/webmin#848]
Steps to reproduce:

* Go to **Hardware > Printer Administration**.
* Add a new printer if none is present yet.
* Click a printer in the list.
* Change any setting on the page that appears and click **Save**.
* Click the printer again and verify settings have been saved.

Expected behavior:

* Printer properties are saved and a confirmation is shown.

Behavior seen:

* An error message: `Failed to save printer : 'foobarfoobar' is not a valid printer name` (the actual printer name being `foobar`—it is doubled in the message)
* Printer settings are not saved.

System configuration:

* Server side: Raspbian Squeeze, Webmin 1.880
* Client side: Ubuntu MATE 16.04, Firefox 58.0.2 (64-bit)

**Comment by jcameron** [comment]
Ok, I see the cause of this - it will be fixed in the next Webmin release.

**Comment by Triplethread** [comment]
Does not work at me also: may be its wrong user rights management?

**Comment by jcameron** [comment]
No, it's a bug in the UI
