### ISSUE TITLE
Webmin error

### ISSUE THREAD

**Issue by caodecaca** [webmin/webmin#850]
Hello
Need some help.
After upgrade my webmin to the last version throw webmin application, i can´t enter again.

Error - Perl execution failed
Nested quantifiers in regex; marked by <-- HERE in m/(\Slink.cgi/[\d]{8,16}+ <-- HERE )/ at /opt/webmin-1.880/authentic-theme/authentic-init.pm line 1103. Compilation failed in require at /opt/webmin-1.880/authentic-theme/authentic-lib.pm line 18. Compilation failed in require at /opt/webmin-1.880/authentic-theme/session_login.cgi line 10.
*

please some help

**Comment by caodecaca** [comment]
Solution

Edit /etc/webmin/config and add the line

theme=mscstyle3
Edit /etc/webmin/miniserv.conf and add the line

preroot=mscstyle3
Restart Webmin with the command

/etc/webmin/stop ; /etc/webmin/start

**Comment by swelljoe** [comment]
What Perl version do you have there?

`perl -v`

**Comment by qooob** [comment]
..and what Linux distro are you on?

**Comment by qooob** [comment]
@caodecaca What is your Perl version and Linux distro?

**Comment by qooob** [comment]
I have made a patch to support Perl prior to 5.10 and eliminate this error:
_Fix unnecessary possessive quantifier to be greedy -_ https://github.com/qooob/authentic-theme/commit/41172189e9238aa133218c6f31776f6020e62012

You might still gonna have issues with Webmin 1.880+.
https://github.com/qooob/authentic-theme/issues/1049
