### ISSUE TITLE
feature request: selectable default "show # entries" in File Manager

### ISSUE THREAD

**Issue by FBachofner** [webmin/webmin#857]
File Manager always defaults to showing 25 entries.

It is easy to change the number, but the user has to do it on each return to File Manager.

If I change to the "_old webmin theme_" and go to Configuration For module File Manager, then I see "Items to display per page (for old themes only)"

Authentic Theme (probably the most used) does not seem to provide for this default in any way.

Could this be changed so that ALL themes have access to such a default?  Seems like a good idea, if possible.

**Comment by FBachofner** [comment]
Being able to select the default sort column and default sort order could be great enhancements as well.

Thanks for your consideration!

**Comment by qooob** [comment]
I will be able to make it persistent, I think, let me see.

**Comment by qooob** [comment]
It's been added on the latest commit. For having an option for default sort column and default sort order - will check tomorrow.

**Comment by qooob** [comment]
Install latest dev version, clear cache and give it a try.

**Comment by FBachofner** [comment]
Thank you.

That's **_fantastic_**!  It works and persists across logout from Webmin.

Authentic Theme 19.10-beta2
tested on Ubuntu 16.04.4

I'll put it on a number of other servers tomorrow evening when I have some time for further testing.

**Comment by qooob** [comment]
Thanks, I'm glad you liked it. Starting tree-view tomorrow.

**Comment by FBachofner** [comment]
Looking forward to testing that feature.

Tree view should really help with quicker navigation, particularly for those averse to typing in directory names into the Ctrl-L dialog . . .
