### ISSUE TITLE
Module names in Menu are displayed in eglish with de-UTF-8

### ISSUE THREAD

**Issue by gnadelwartz** [webmin/webmin#865]
since webmin 1.880 module names are displayed in english if de.UTF-8 is selected:
![image](https://user-images.githubusercontent.com/4593242/37366918-2c4dcb52-2702-11e8-9283-42d07722b434.png)
 If I select in addition "Language based on Browser" they are displayed in German:

![image](https://user-images.githubusercontent.com/4593242/37367000-70e7a968-2702-11e8-9e61-ba85ac06ded6.png)

![image](https://user-images.githubusercontent.com/4593242/37367034-89fd8404-2702-11e8-946f-e0cdec1a9faf.png)

module titles in rigth frame are always correct ... same in authentic theme

**Comment by jcameron** [comment]
Ok, I see what caused this - it will be fixed in the 1.881 Webmin release.
