### ISSUE TITLE
proposal: support for `user: *` in file `webmin.acl`

### ISSUE THREAD

**Issue by gnadelwartz** [webmin/webmin#866]
from time to time there are issues that a module is not availible for main admin user.
the solution often is to got to `edit user` and select all availible modules.

The downside of this is (at least for main admin user) that newly availible modules after an update are not availible in menu, even in "not used modules".

It would be nice to allow `user: *` in file `webmin.acl` to allow this user access to all modules instead of listing them all seperatly.

**Comment by jcameron** [comment]
Actually that already works! However, you have to edit `webmin.acl` manually, as it can't be set in the UI.

**Comment by gnadelwartz** [comment]
ups, did try but seems not to work.
I'll test again ..

**Comment by qooob** [comment]
Jamie, done have a single command that would try to fix common issues in settings/installation? It would be good to have such script, for instance to fix empty menu as a result of no modules set in ACL file.

**Comment by gnadelwartz** [comment]
OK, can confirm its working! may be I made an error last time.

It would be nice to has an Option to set it to `*` also in the UI, this would help much.

**Comment by jcameron** [comment]
I don't offer this option in the UI, because it could lead to surprising results where extra modules are granted to a user on upgrading. Although maybe it could be argued that if you're already granted access to everything, new modules should be added by default anyway.

**Comment by gnadelwartz** [comment]
l would support you last statement 😇
