### ISSUE TITLE
how to move self defined Categories to top of menu?

### ISSUE THREAD

**Issue by gnadelwartz** [webmin/webmin#867]
I use a self defined category "RRR" to place most important modules in one location.

I know that I can use favorites to do something similar on personal level,
but I used this to make it easy for my part time admins to find important modules.

But now they are complaining: "RRR" is at the end and if an other category is open it's no more vislible :-)
I looked already in the source on how to reorder categories, but did not find a solution.

Any hints?

**Comment by qooob** [comment]
Call it AAA :) or hack it on the theme side and reverse the output of the hash for the menu.

Maybe calling RRR but starting with the space?

**Comment by gnadelwartz** [comment]
il try if it will sort by alfabetical order...

**Comment by gnadelwartz** [comment]
AAA is diplayed below RRR, so no alphabetical order 🤔

**Comment by qooob** [comment]
Actually you could extend `get_navigation_menu_webmin()` function and inject few more lines of code to move RRR to the top of the navigation menu.
