### ISSUE TITLE
sysstats.pl failure

### ISSUE THREAD

**Issue by re3lex** [webmin/webmin#871]
Hi
Recently my Webmin on NAS is upgraded  to 1.880.

Today I noticed that postfix is creating local mail every minute.
After investigation I found that sysstats.pl is called by CRON every minute and fails with errors like below:
```

do "users.pl" failed, '.' is no longer in @INC; did you mean do "./users.pl"? at ./sysstats.pl line 127.
do "process.pl" failed, '.' is no longer in @INC; did you mean do "./process.pl"? at ./sysstats.pl line 127.
do "network.pl" failed, '.' is no longer in @INC; did you mean do "./network.pl"? at ./sysstats.pl line 127.
do "services.pl" failed, '.' is no longer in @INC; did you mean do "./services.pl"? at ./sysstats.pl line 127.
do "netstat.pl" failed, '.' is no longer in @INC; did you mean do "./netstat.pl"? at ./sysstats.pl line 127.
do "cpu.pl" failed, '.' is no longer in @INC; did you mean do "./cpu.pl"? at ./sysstats.pl line 127.
do "firewall.pl" failed, '.' is no longer in @INC; did you mean do "./firewall.pl"? at ./sysstats.pl line 127.
do "mailq.pl" failed, '.' is no longer in @INC; did you mean do "./mailq.pl"? at ./sysstats.pl line 127.
do "disk.pl" failed, '.' is no longer in @INC; did you mean do "./disk.pl"? at ./sysstats.pl line 127.
do "load.pl" failed, '.' is no longer in @INC; did you mean do "./load.pl"? at ./sysstats.pl line 127.
do "mem.pl" failed, '.' is no longer in @INC; did you mean do "./mem.pl"? at ./sysstats.pl line 127.
do "diskio.pl" failed, '.' is no longer in @INC; did you mean do "./diskio.pl"? at ./sysstats.pl line 127.
do "irq.pl" failed, '.' is no longer in @INC; did you mean do "./irq.pl"? at ./sysstats.pl line 127.
```

Any idea how to fix that?

**Comment by jcameron** [comment]
Which module is this coming from? The sysstats module isn't a core part of Webmin, so you may need to bring this up with it's author.

**Comment by re3lex** [comment]
I thought this is built-in module.
Looks like this is 3rd party webminstat module as per file name but I cannot find it in installed modules.

What is correct way to determine which module that script is related on server?

**Comment by re3lex** [comment]
I see that "sysstats" word is appeared in /etc/webmin folder only two times: in installed.cache and webmin.acl files. but I do not see that module on UI.
How can I remove it without further pain?

> user@nas:/etc/webmin# grep -rnw '/etc/webmin/' -e 'sysstats'
> /etc/webmin/installed.cache:112:**sysstats**=1
> /etc/webmin/webmin.acl:1:root: acl adsl-client ajaxterm apache at backup-config bacula-backup bandwidth bind8 burner change-user cluster-copy cluster-cron cluster-passwd cluster-shell cluster-software cluster-useradmin cluster-usermin cluster-webmin cpan cron custom dfsadmin dhcpd dovecot exim exports fail2ban fdisk fetchmail file filemin filter firewall firewalld fsdump grub heartbeat htaccess-htpasswd idmapd inetd init inittab ipfilter ipfw ipsec iscsi-client iscsi-server iscsi-target iscsi-tgtd jabber krb5 ldap-client ldap-server ldap-useradmin logrotate lpadmin lvm mailboxes mailcap man mon mount mysql net nis openslp package-updates pam pap passwd phpini postfix postgresql ppp-client pptp-client pptp-server proc procmail proftpd qmailadmin quota raid samba sarg sendmail servers shell shorewall shorewall6 smart-status smf software spam squid sshd stunnel syslog-ng syslog tcpwrappers telnet time tunnel updown useradmin usermin vgetty webalizer webmin webmincron webminlog wuftpd xinetd minidlna theme-metal bootstrap **sysstats** firewall6 clamav system-status

**Comment by re3lex** [comment]
Answering to myself: this module is called **Historic System Statistics** on UI.
