### ISSUE TITLE
can not open the site of webmin

### ISSUE THREAD

**Issue by yeniugo** [webmin/webmin#883]
i can open it in my localhost,but can not open it in others,and ever telnet ip:10000 failer,but in the log,i only see the ipv6 error,because my vps have not a ipv6 address.

**Comment by gitarent** [comment]
Sounds like a firewall issue. Something (router?) is blocking port 10000.

**Comment by yeniugo** [comment]
thanks,i know why,and it my vps have a firewall,and i have to allow port 10000.this is the first time my vps have a firewall.thanks
