### ISSUE TITLE
suggest using /etc/os-release for oschooser

### ISSUE THREAD

**Issue by chrstphrchvz** [webmin/webmin#892]
I'm wondering if it helps in the long run for oschooser.pl to check /etc/os-release (if present) before trying e.g. /etc/issue since it's somewhat easier to parse. Preferably the script-suitable `ID` and `VERSION_ID` parameters are checked, as the documentation suggests (https://www.freedesktop.org/software/systemd/man/os-release.html). E.g. for detecting Ubuntu 18.04 there will be lines `ID=ubuntu` and `VERSION_ID=18.04`.

The file is backed by freedesktop so it should be present on recent Linux distributions and/or any using systemd (cf. http://0pointer.de/blog/projects/os-release).

I might be able to prototype some of this functionality.

The question I have though is, does Webmin need to keep a list of known distributions and versions, or would it be alright that as long as Webmin report the version correctly it shouldn't need a hardcoded list?

**Comment by chris001** [comment]
Good idea, that file is on all distros with `systemd`.  
* http://0pointer.de/blog/projects/os-release
In case the file's missing or lacking information, `webmin` would have to fall back to something else.
Also, feature detection (detect existence of package manager commands at runtime) is probably better than OS detection.
* https://unix.stackexchange.com/questions/351557/on-what-linux-distributions-can-i-rely-on-the-presence-of-etc-os-release

**Comment by chrstphrchvz** [comment]
@jcameron /etc/os-release has been included Ubuntu since 12.10, so all supported versions of Ubuntu have it. Cf. https://bugs.launchpad.net/ubuntu/+source/base-files/+bug/947236

**Comment by jcameron** [comment]
Ok, I've updated Webmin's os detection code to use this file if available.
