### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by carlosnewmusic** [webmin/webmin#898]
debconf: no se pudo inicializar la interfaz: Gnome
debconf: (Can't locate Gtk3.pm in @INC (you may need to install the Gtk3 module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.26.1 /usr/local/share/perl/5.26.1 /usr/lib/x86_64-linux-gnu/perl5/5.26 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.26 /usr/share/perl/5.26 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /usr/share/perl5/Debconf/FrontEnd/Gnome.pm line 151, <> line 1.)
debconf: probando ahora la interfaz: Dialog
debconf: no se pudo inicializar la interfaz: Dialog
debconf: (La variable TERM no está establecida, por lo que no se puede utilizar la interfaz «dialog».)
debconf: probando ahora la interfaz: Readline
Use of uninitialized value $ENV{"TERM"} in pattern match (m//) at /usr/lib/x86_64-linux-gnu/perl5/5.26/Term/ReadLine/Gnu.pm line 86, <> line 1.
Seleccionando el paquete webmin previamente no seleccionado.
(Leyendo la base de datos ... 382506 ficheros o directorios instalados actualmente.)
Preparando para desempaquetar .../archives/webmin_1.881_all.deb ...
Desempaquetando webmin (1.881) ...
Configurando webmin (1.881) ...
so he gets caught infinitely and when giving enter says this

grep: /etc/webmin/miniserv.conf: No existe el fichero o el directorio
Webmin install complete. You can now login to http://blablabla:/
as root with your root password, or as any user who can use sudo
to run commands as root.
Procesando disparadores para systemd (238-4) ...

**Comment by swelljoe** [comment]
You have a Perl version not provided by your OS in your path, and it seems to be missing some stuff. But, these errors are about modules that Webmin does not use, so it must be something in the package manager trying to load those modules (Webmin does not use or depend on Gtk3.pm, but I guess your package manager does...maybe aptitude or synaptic, or something?).

In short: This is not a Webmin-related error.

But, you can fix it by removing that locally installed Perl from your path whenever you run the package manager that needs Gtk3.pm. You might also be able to install Gtk3.pm in your local Perl, but I'd just make sure you use the system Perl when installing software.
