### ISSUE TITLE
Webmin Actions Log: Export as CSV

### ISSUE THREAD

**Issue by qooob** [webmin/webmin#904]
Jamie, due to new `make_date()` function there is an issue for such downloads as they don't seem to cancel Webmin UI preset (`$main::webmin_script_type eq 'web'`). It shouldn't be set to _web_, in these kind of case scenarios, I think.

Download looks like this:

```
"Changed index page options","Webmin Configuration","root","192.168.122.1","<x-md-d>1523722001;0</x-md-d> <x-md-t>1523722001</x-md-t>"
"Changed index page options","Webmin Configuration","root","192.168.122.1","<x-md-d>1523721416;0</x-md-d> <x-md-t>1523721416</x-md-t>"
"Changed index page options","Webmin Configuration","root","192.168.122.1","<x-md-d>1523721394;0</x-md-d> <x-md-t>1523721394</x-md-t>"
"Changed index page options","Webmin Configuration","root","192.168.122.1","<x-md-d>1523721363;0</x-md-d> <x-md-t>1523721363</x-md-t>"
"Changed index page options","Webmin Configuration","root","192.168.122.1","<x-md-d>1523720765;0</x-md-d> <x-md-t>1523720765</x-md-t>"
"Changed index page options","Webmin Configuration","root","192.168.122.1","<x-md-d>1523720409;0</x-md-d> <x-md-t>1523720409</x-md-t>"
"Changed index page options","Webmin Configuration","root","192.168.122.1","<x-md-d>1523720352;0</x-md-d> <x-md-t>1523720352</x-md-t>"

```

Besides, the file name, short and clean, should be passed to headers because now it looks like this: 

```
webminlog.csv_uall=1&user=anonymous&nuser=anonymous&ouser=&mall=1&module=global&tall=2&from_d=&from_m=1&from_y=&to_d=&to_m=1&to_y=&desc=&fall=1&file=&dall=1&diff=&long=0&csv=1
```

**Comment by jcameron** [comment]
Maybe we need an extra param to make_date to prevent any special formatting from happening?

**Comment by qooob** [comment]
May be but isn't more code to fix? This is obviously non `web` type?

**Comment by jcameron** [comment]
It's still set to "web" (at least in the current Virtualmin code), as the script is being executed by the webmin webserver.

**Comment by qooob** [comment]
What is the solution? Additional param? I'm fine with that too.

**Comment by jcameron** [comment]
Ok, I just checked in a few of fixes for this that will cause the theme's make_date override to be only called on an actual web page.

**Comment by qooob** [comment]
Thanks, it works fine now.

Please consider [my comment](https://github.com/webmin/webmin/commit/0eb45125c84422babf076f04d49efc532f8ca0b0#commitcomment-28789126). What do you think?
