### ISSUE TITLE
Repo error: Hash sum mismatch

### ISSUE THREAD

**Issue by chris001** [webmin/webmin#906]
```
$ apt upgrade
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
  webmin-virtual-server
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 2,505 kB of archives.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n]
Get:1 http://software.virtualmin.com/gpl/ubuntu virtualmin-universal/main amd64 webmin-virtual-server all 6.03.gpl [2,505 kB]
Err:1 http://software.virtualmin.com/gpl/ubuntu virtualmin-universal/main amd64 webmin-virtual-server all 6.03.gpl
  Hash Sum mismatch
Fetched 1,767 kB in 1s (1,664 kB/s)
E: Failed to fetch http://software.virtualmin.com/gpl/ubuntu/dists/virtualmin-universal/main/binary-amd64/webmin-virtual-server_6.03.gpl_all.deb  Hash Sum mismatch
```

**Comment by jcameron** [comment]
@swelljoe Virtualmin repository issue?

**Comment by chris001** [comment]
The expected size 2505 KB is different from the actual size 1767 KB.

**Comment by isos** [comment]
I have the same problem in ubuntu Xenial 16.04

**Comment by chris001** [comment]
* Looks like the repo is now fixed (thanks @swelljoe ) because now the expected size and actual size are both 1767 KB and the update is accepted by the OS.

* However, the `postinstall.pl` script fails:
```
virtual-server/postinstall.pl failed : virtual-server::module_install failed : Failed to open /etc/letsencrypt/live/server1.somedomain.com/../../archive/server1.somedomain.com/cert10.pem.webmintmp.32487 : Permission denied at web-lib-funcs.pl line 1465, <readout9> line 1.
```

**Comment by swelljoe** [comment]
Please report Virtualmin repo issues in a Virtualmin tracker (any Virtualmin tracker will probably do...the one at Virtualmin.com, maybe virtualmin-install here at github). Jamie maintains the Webmin.com stuff, as well as the Webmin github, and I maintain the Virtualmin.com stuff and Virtualmin github...we communicate and I usually see stuff here, too, of course, but this one went unnoticed for a little while).

I've never seen that specific postinstall.pl script failure. That's a different issue than the repo issue, though, and *would* be a Jamie kinda issue probably. I don't know what's happening there, but I would guess the code is dropping privileges and is unable to poke at root-owned files.

**Comment by swelljoe** [comment]
I'm gonna close this one, as the initial issue has been fixed. If your postinstall issue persists, feel free to open a new ticket and we can probably sort it out.

**Comment by ajaybhargav** [comment]
> 
> 
>     * Looks like the repo is now fixed (thanks @swelljoe ) because now the expected size and actual size are both 1767 KB and the update is accepted by the OS.
> 
>     * However, the `postinstall.pl` script fails:
> 
> 
> ```
> virtual-server/postinstall.pl failed : virtual-server::module_install failed : Failed to open /etc/letsencrypt/live/server1.somedomain.com/../../archive/server1.somedomain.com/cert10.pem.webmintmp.32487 : Permission denied at web-lib-funcs.pl line 1465, <readout9> line 1.
> ```
> 
> The user running this apt update is `root` and the permissions are `644` and owner `root:root` on all the files in that directory.

Hi @chris001 I know I am replying to an old issue which might have been resolved. but I am having exact same error while updating webmin-virtual-server package. How did you resolve this permission denied issue.
Thanks in advance.
