### ISSUE TITLE
Custom module not showing third column title .. "Actions" .. and Edit | Form links.

### ISSUE THREAD

**Issue by datavectors** [webmin/webmin#907]
I have an odd issue I have been trying to fix in Custom module.

Now since I have been hacking code in creating a new custom module I decided to go for a fresh installation of webmin 1.881 (running on Ubuntu 16.04 with Chromium browser 65.0.335.181). And the issue is still there.

**Issue:**  I cannot see the third column heading title: [Actions] .. rendered in browser.
It should be as below ..

[Command] ... [Description] ... [Actions] 

...

To check if third column title is hidden  I swapped references in index.cgi line 165

	print &ui_columns_start([
		$text{'index_cmd'},
		$text{'index_desc'},
		$text{'index_acts'},
		], 100, 0, \@tds);
		
to ...

	print &ui_columns_start([
		$text{'index_cmd'},
		$text{'index_acts'},
		$text{'index_desc'},
		], 100, 0, \@tds);
		
and after reloading I see a change in column names with Actions as second column title (the third column not visible).

[Command] ... [Actions]

So somehow the third column title is not being printed to browser.

All of the links at end of each command row are [Edit].

....

Now it gets stranger.   I have previously copied (not cloned) Custom module to create another module (based on Custom) into which I can use parameter forms with each command.   In this copied module I _do_ see the three columns title ..

Command .. Description ... Actions

and in the third column against each of the commands I see the links .. Edit | Form

I can click on the Edit link to edit the command.
I can click on the Form link to inspect the parameters form, choose parameters from drop down menus in ini file, and click on execute Button.

....

Can anybody confirm that there is no "Actions" title seen at top of third column in Others > Custom module?
And any ideas on how to I fix it to show three column titles?

**Comment by jcameron** [comment]
You're right, I also see this on my test systems.

@iliaross  - is this something the Authentic theme changes in the Custom Commands module?

**Comment by datavectors** [comment]
Thanks, Jamie, for confirming that layout quirk. I was knocking my head against a brick wall.

Now to try to pin this down further.
First step.  Using [SearchMonkey](http://searchmonkey.embeddediq.com/index.php) in Ubuntu I searched through /usr/share/webmin/authentic-theme/
looking for occurrences of "custom" as text pattern.

I see quite a few occurrences and I wonder if use of "custom" in module name causes a conflict between Authentic theme and Custom module. Is perhaps "custom" a reserved word or variable?

This theory fits with my earlier observation that if I change the name of custom module (creating a copy named **custom-ansible** instead of a linked clone of **custom**) the layout renders in browser as expected.

Another point. I was unable to switch to an alternative older theme for testing.

**Comment by qooob** [comment]
Yes, it's not possible to use some bundled modules names, with the same name for modified module. Consider it reserved. I would give it completely different name to avoid collisions.

**Comment by qooob** [comment]
Changing theme should just work without an issue, Authentic does nothing in this regard, besides helping to reload the page after the theme was changed for better UX.

**Comment by datavectors** [comment]
iliaross .. I do understand that **copied** modules must have different names to avoid naming conflicts.

The question is whether Authentic-theme and the default Custom module both use "custom" as a reserved word, and so cause a conflict?

**Comment by qooob** [comment]
In terms of using module name (in this case _custom_) to run module-specific customisations - yes.

You can consider it reserved in this sense, because using it will cause unintended behaviour for your new module. Use completely different name to be safe in this regard.

**Comment by datavectors** [comment]
I disagree since I have edited a copy of custom module throughout to change **all** occurrences of **custom** to **custom-ansible**.

I have a working prototype **custom-ansible** module .. working as I would expect the default Custom module to work (but it does not).

**Comment by qooob** [comment]
Please try, for example:
```
xcustom-ansible
```

**Comment by datavectors** [comment]
But why .. custom-ansible works .. as explained.
Are you suggesting that custom-ansible clashes with original custom?

**Comment by qooob** [comment]
I have some lazy wild selectors for matching for occurrence of the word, in this case _custom_ is the match. It won't happen again in the future but some old implementations have it.

Actually `xcustom` will also match. Try the different name, like `kustom-ansible`.

**Comment by datavectors** [comment]
iliaross - Just to simplify this troubleshooting I have just removed **all** copied and cloned modules out of my webmin folder, restarted webmin, and I have the quirk in Custom Commands view as reported at the beginning.  So this does point to some conflict **only** between Authentic theme and Custom module.

Now I am not too experienced in perl but my suspicion is that namespacing might possibly remove the conflict.

**Comment by qooob** [comment]
Now I'm confused.

Yes, like I mentioned enhanced name-spacing are used now, but that part of the code (for custom module) is old and needs to be rewritten, along with few other.

I don't understand where you are having an issue. Is the issue in original _Custom Module_ or modified version?

**Comment by datavectors** [comment]
Original Custom Module.
Modified module has been purged from system to eliminate this as a possible cause.

**Comment by datavectors** [comment]
So you now confirm the quirk I reported at beginning?
Anything that differs from past usage and is not explained is the "deal".

> Column name was removed on purpose.

My usage is to use commands which have multiple arguments each referring to drop down menus fron ini files.  For example each dropdown menu will be commands for specific frameworks such as google cloud, heroku, aws, ubuntu and so on ...
That is a command repo within webmin which goes beyond one liner commands.
At the end of each command row I expected to see two buttons/links .. Edit | Form
Instead there is just one Edit link now in this redesign.

Actually I don't see nice buttons, only links.

I will probably switch to a new custom grid UI layout using jqueryui so that I can design to suit my purposes.

**Comment by qooob** [comment]
I made a fix to display Action column.

You don't see nice action buttons? Not like in screenshot below?

![screenshot from 2018-04-30 13-38-57](https://user-images.githubusercontent.com/4426533/39423795-460845d2-4c7c-11e8-8ab1-84885fc1c701.png)

**Comment by qooob** [comment]
@jcameron Jamie, could you make default value in configuration _Main page shows_ changed from _All commands and parameters_ to _Links to commands_. It looks much better and easily tweakable from UI perspective, unlike the default. 

When set to  _Links to commands_, commands are sortable and **searchable** from simply starting typing anywhere, while in custom module.

**Comment by datavectors** [comment]
I see that but I would not call the end link a "button". That apart, let's not split hairs..
Now take one of your commands (e.g. ls) and add some arguments with say drop down menus per argument.  These args are taken from ini files in /etc/webmin/custom.
e.g. You might want to specify the folder path in your arguments.

Now after saving do you see at end of command line ...........    [Edit | Form]

My issue is that I do not see Edit | Form in Custom module (only in my modified module).

If you click on Form link/button you are taken to parameters form.

**Comment by qooob** [comment]
Oh, I didn't even know that it exists.

All you needed to do is to provide the screenshot in Gray Theme.

I'm checking what's wrong...

Thanks a lot.

**Comment by qooob** [comment]
Okay, I see now. But clicking on the link will actually take you to form, right?

**Comment by qooob** [comment]
Okay, last commit will display all buttons nicely.

![screenshot from 2018-04-30 14-26](https://user-images.githubusercontent.com/4426533/39425107-78d38408-4c82-11e8-8443-e155b02aa2fc.png)

**Comment by datavectors** [comment]
That is looking much nicer.
I'm considering pushing further and adding "Create a Mongodb command" tab later.
