### ISSUE TITLE
"Amazon S3 Buckets" module stuck loading when Perl module "XML::Simple" is not installed

### ISSUE THREAD

**Issue by lunarovic** [webmin/webmin#911]
The "Amazon S3 Buckets" module says that Amazon access needs to be configured first. Then after configuring access in "Cloud Storage Providers", "Amazon S3 Buckets" module doesn't load anymore.

I found out why in another module "Scheduled Backups" where an error said that it couldn't create a scheduled backup to Amazon because Perl module "XML::Simple" is not installed, and that module is used for communicating with Amazon.

So I installed that Perl module and then I could use the Amazon module again, but that error could also be displayed in the "Amazon S3 Buckets" module, instead of getting stuck loading.

**Comment by jcameron** [comment]
Good suggestion - I'll fix this in the next Virtualmin release.
