### ISSUE TITLE
System Log: Error from `tac` when no log file

### ISSUE THREAD

**Issue by qooob** [webmin/webmin#912]
Jamie, when there is no log file, instead of just returning empty file,  the error pops up

```
/bin/sh: -c: line 0: syntax error near unexpected token `|'
/bin/sh: -c: line 0: ` | tac'
```

It's not an issue when `tac` is not used. Can you please fix it to make sure it's just returns the same output (empty)?

**Comment by jcameron** [comment]
Thanks - checking in a fix now.

**Comment by qooob** [comment]
Thanks, it works but still has an issue if [search is run](https://github.com/webmin/webmin/commit/9079be4b0ddd3315f5e97a4192067dceb49b2ec2#commitcomment-28789279).

**Comment by qooob** [comment]
Works great now, thanks.
