### ISSUE TITLE
Problem when downloading the source code in Windows.

### ISSUE THREAD

**Issue by vsc55** [webmin/webmin#914]
Hi,

When trying to download the source code, the file "/acl/Authen-SolarisRBAC-0.1/blib/man3/Authen::SolarisRBAC.3" can not be downloaded because the ":" character is not supported in Windows.

A greeting.

**Comment by jcameron** [comment]
Did you download the source from the ZIP file, or are you checking out from github?

**Comment by vsc55** [comment]
The problem is that the file "/acl/Authen-SolarisRBAC-0.1/blib/man3/Authen::SolarisRBAC.3" has the character ":" in the file name.
As Windows does not support this character in the name of a file, it fails to clone github.

**Comment by datavectors** [comment]
The colon ":" is indeed a reserved character in Windows.

[Windows - Naming Files, Paths, and Namespaces ](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396)

I am a Ubuntu user .. but could the reserve character(s) in filepath be escaped with backslash?

**Comment by jcameron** [comment]
Ok, turns out that those files don't really need to be in the source code anyway ... I've removed them.

**Comment by vsc55** [comment]
Hi.
Another problem that I detect in Windows.
In the repository exists "/fdisk/help/A.ca.html" and "/fdisk/help/a.ca.html.
In Linux there is no problem, but in Windows it crushes one for the other and detects that the file has been modified.
The problem is that Windows does not distinguish between uppercase and lowercase.

**Comment by jcameron** [comment]
Try again now - I've deleted those files from the repository.
