### ISSUE TITLE
custom commands menu parameter in ini file does not ignore #comments

### ISSUE THREAD

**Issue by datavectors** [webmin/webmin#915]
In custom commands I am using several ini files placed in /etc/webmin/custom
to render multiple parameter menus in a form.
However I see that comment lines starting with # are shown
in the form drop down menu. I can put comments in a separate file but it would be convenient
to add a few comment lines as header in ini  which are ignored in processing the ini file.

**Comment by jcameron** [comment]
Good idea .. I will add support for comments in that file.
