### ISSUE TITLE
Temporary directory must be removed upon account modifications

### ISSUE THREAD

**Issue by qooob** [webmin/webmin#919]
Jamie, hi.

Joe and I we had a discussion about the cases, when user is deleted and new user created, with new/other _uid/gid_ but **the same** username. It will cause an error coming from `tempname()` sub in case user tmp dir was previously used and left over:

```Perl
if ($tries >= 10) {
	my @st = lstat($tmp_dir);
	&error("Failed to create temp directory $tmp_dir : uid=$st[4] mode=$st[2]");
	}
```

I know you would advise to use `transname()` for such cases but it's not always possible (as far as I know) on multiple asynchronous calls.

While you create userdir in `tempname_dir()` with:

```Perl
@remote_user_info ? $tmp_base."-".$remote_user : ...
```

It would be good to make sure that the temporary directory **is deleted** when:

 1. User is deleted using `useradmin` module;
 2. User's _uid_ or _gid_ is change, again using `useradmin`.

Otherwise we're going to have left temp directory name with possibly different ids, causing an error.

**Comment by jcameron** [comment]
Better than that, we can just include the UID in the temp path - that will prevent this problem for ever happening.

**Comment by qooob** [comment]
Let's also include GUI to be sure?
