### ISSUE TITLE
can't create a timestamp Null Default Null field using Mysql Database Server

### ISSUE THREAD

**Issue by Bulmer** [webmin/webmin#921]
Using Mysql Database Server module I can't create a timestamp, Null, Default Null field without an error. It won't allow a default of NULL - "timestamp default 'NULL' failed : Invalid default value for...
I'm pretty sure this is a bug, as that fieldtype can be successfully created using an SQL command and also phpmyadmin. I'm using webmin 1.881

**Comment by jcameron** [comment]
You shouldn't need to enter "NULL" as the default value though - just leaving it empty (as long as nulls are allowed) will make new rows default to null.

**Comment by Bulmer** [comment]
Leaving the default empty gives this error "Failed to save field : SQL alter table `customers` add `test` timestamp default '' failed : Invalid default value for 'test'"
