### ISSUE TITLE
Allow 'Direct to Module' for individual users

### ISSUE THREAD

**Issue by TrojanCoder** [webmin/webmin#922]
There is an option to set the landing module globally but as far as I can tell it's not possible to set this individually for users. This is fine if a user only has one module because of the special option for that but if they have 2 or 3 they will always go to the global setting. If there's a way more me to set this manually in a config file that would be a decent work around until an interface option is added.

**Comment by jcameron** [comment]
Right now, there is no way to configure this on a per-user basis, sorry.

**Comment by rostovtsev** [comment]
You want a user, in Usermin himself choose module after logging in? Are you using Authentic Theme?

**Comment by TrojanCoder** [comment]
I'm using Authentic Theme yes. Ideally I'd like an option on the user configuration page that allows me to set the default module for a given user. For example I'm the primary user and I want my first module to be system information so that's the default in `Index Page Options`. Another user doesn't have access to that module so they just get a message about needing permission to see it so I'd like the module they get on login to be something else.

**Comment by rostovtsev** [comment]
Why not let the user, from settings page in Usermin, select wanted moudle, from the list of available modules?

**Comment by TrojanCoder** [comment]
Sorry I should have been more clear, I'm talking about Webmin modules not Usermin modules. And it's fine for the user to select the module from the list on the lefthand side, it just removes a step if they can login directly to that module. It sounds like this isn't possible so I'm going to close this ticket.

**Comment by rostovtsev** [comment]
A user now can select default module for Usermin.
https://github.com/authentic-theme/authentic-theme/commit/d098413d61eb8fe08904260d5f4383659f1a9880

![Screenshot from 2019-05-05 20-20-08](https://user-images.githubusercontent.com/4426533/57197738-87191180-6f73-11e9-92f2-633fc0a37968.png)
