### ISSUE TITLE
Cant install Webmin in Debian 7

### ISSUE THREAD

**Issue by lRoberth** [webmin/webmin#923]
As the title says. These are the logs:

`admin@ip-172-31-31-179:~/webmin-master$ sudo ./setup.sh
***********************************************************************
*            Welcome to the Webmin setup script, version 1.883        *
***********************************************************************
Webmin is a web-based interface that allows Unix-like operating
systems and common Unix services to be easily administered.

Installing Webmin in /home/admin/webmin-master ...

***********************************************************************
Webmin uses separate directories for configuration files and log files.
Unless you want to run multiple versions of Webmin at the same time
you can just accept the defaults.

Config file directory [/etc/webmin]:
Log file directory [/var/webmin]:

***********************************************************************
Webmin is written entirely in Perl. Please enter the full path to the
Perl 5 interpreter on your system.

Full path to perl (default /usr/bin/perl):

Testing Perl ...
Perl seems to be installed ok

***********************************************************************
Operating system name:    Debian Linux
Operating system version: 7

***********************************************************************
Webmin uses its own password protected web server to provide access
to the administration programs. The setup script needs to know :
 - What port to run the web server on. There must not be another
   web server already using this port.
 - The login name required to access the web server.
 - The password required to access the web server.
 - If the webserver should use SSL (if your system supports it).
 - Whether to start webmin at boot time.

Web server port (default 10000):
Login name (default admin):
Login password:
Password again:
The Perl SSLeay library is not installed. SSL not available.
Webmin does not support being started at boot time on your system.
***********************************************************************
Creating web server config files..
..done

Creating access control file..
..done

Inserting path to perl into scripts..
..done

Creating start and stop scripts..
..done

Copying config files..
..done

Creating uninstall script /etc/webmin/uninstall.sh ..
..done

Changing ownership and permissions ..
..done

Running postinstall scripts ..
system-status/postinstall.pl failed : system-status::module_install failed : Require cron/cron-lib.pl failed : <pre>Can't locate Time/Local.pm in @INC (@INC contains: /home/admin/webmin-master/cron . /home/admin/webmin-master /etc/perl /usr/local/lib/perl/5.14.2 /usr/local/share/perl/5.14.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.14 /usr/share/perl/5.14 /usr/local/lib/site_perl ..) at /home/admin/webmin-master/cron/cron-lib.pl line 35.
BEGIN failed--compilation aborted at /home/admin/webmin-master/cron/cron-lib.pl line 35.
</pre> at web-lib-funcs.pl line 1493.

webmin/postinstall.pl failed : webmin::module_install failed : Undefined subroutine &cron::create_wrapper called at /home/admin/webmin-master/webmin/postinstall.pl line 40.

cron/postinstall.pl failed : Require cron/postinstall.pl failed : <pre>Can't locate Time/Local.pm in @INC (@INC contains: /home/admin/webmin-master/cron . /home/admin/webmin-master /etc/perl /usr/local/lib/perl/5.14.2 /usr/local/share/perl/5.14.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.14 /usr/share/perl/5.14 /usr/local/lib/site_perl ..) at /home/admin/webmin-master/cron/cron-lib.pl line 35.
BEGIN failed--compilation aborted at /home/admin/webmin-master/cron/cron-lib.pl line 35.
Compilation failed in require at /home/admin/webmin-master/cron/postinstall.pl line 2.
</pre> at web-lib-funcs.pl line 1493.

time/postinstall.pl failed : time::module_install failed : Undefined subroutine &cron::list_cron_jobs called at /home/admin/webmin-master/time/time-lib.pl line 22.

..done

Attempting to start Webmin mini web server..
Starting Webmin server in /home/admin/webmin-master
Can't locate Time/Local.pm in @INC (@INC contains: /home/admin/webmin-master /etc/perl /usr/local/lib/perl/5.14.2 /usr/local/share/perl/5.14.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.14 /usr/share/perl/5.14 /usr/local/lib/site_perl .) at /home/admin/webmin-master/miniserv.pl line 8.
BEGIN failed--compilation aborted at /home/admin/webmin-master/miniserv.pl line 8.
ERROR: Failed to start web server!
`

**Comment by swelljoe** [comment]
There are docs for this: http://webmin.com/deb.html

We recommend you install using the appropriate package for your distribution, if one is available, rather than the tarball. The errors you see are because your system is missing some Perl modules that Webmin needs. The docs linked covers installing those dependencies. If you use the apt repository method, it will automatically resolve those dependencies when installing with the apt-get command.
