### ISSUE TITLE
Dynamic DNS hosts aren't displayed in Bind module

### ISSUE THREAD

**Issue by imcdona** [webmin/webmin#928]
I originally reported this in a comment on issue [870](https://github.com/webmin/webmin/issues/870) . Seeing as how 870 is already "solved" I'm opening a new issue. 

Records added to a dynamic zone via nsupdate don't appear in Webmin unless you freeze the zone first.

**Steps to reproduce:**

**1.** Add a record to dynamic DNS zone via RFC 2136 (eg nsupdate)
**2.** Open the zone in question in Webmin
**3.** Note how the records added to the zone in question don't appear in Webmin
**4.** Click the "Freeze Zone" button in Webmin for the zone in question
**5.** Note how the records you added in step 1 are now visible in Webmin

**Comment by chris001** [comment]
What command are you running to do the `nsupdate` in step 1?  
(Obviously, redact your personally identifiable info.)

**Comment by imcdona** [comment]
I believe the issue stems from the fact that Webmin is loading whatever records in finds in the zone file "on disk". For non-dynamic zones this works. When it comes to dynamic zones, the REAL zone data isn't written to disk until the zone is either frozen or Bind is restarted.


Here's the syntax for the nsupdate command. It's interactive so type "nsupdate -y keyname:secret" and then hit enter.
```
nsupdate -y keyname:secret
server 127.0.0.1
update add subdomain.example.com 60 A 127.0.0.1
send
```

**Comment by imcdona** [comment]
This has been fixed. See issue [870](https://github.com/webmin/webmin/issues/870)
