### ISSUE TITLE
Feature Request:  Add Additional AT&T Option to 'Service Status' 'Scheduled Monitoring'

### ISSUE THREAD

**Issue by JaredF** [webmin/webmin#932]
Under "Others-->System and Service Status-->Scheduled Monitoring-->Send SMS to" the AT&T option uses the e-mail address format "XXXXXXXXXX@txt.att.net" to generate SMS messages.

This does work; however, messages received are sent from a random text number generated by AT&T that follows the format +1 (410) XXX-XXX.  Each time a new message is received, it is added to a new conversation on the phone's messaging app and it is very difficult or not possible to add all of the number combinations to a single contact in order to assign a specific text tone, action, etc.

AT&T has another e-mail address format "XXXXXXXXXX@mms.att.net" which will send an MMS message in lieu of an SMS.  These messages will use a "Caller ID" matching the e-mail address that sent them.  This will cause all messages to appear in a single conversation and a source address that can be easily assigned to a single contact!

Requesting for the MMS address be added as an additional AT&T option or to replace the existing SMS entry.

**Comment by jcameron** [comment]
Sure, we can do this - look for it in the next Webmin release.
