### ISSUE TITLE
Search: Fails on Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by reers** [webmin/webmin#933]
Search not working. The error is:

<code>HTTP/1.0 500 Perl execution failed Server: MiniServ/1.883 Date: Mon, 2 Jul 2018 08:57:56 GMT Content-type: text/html; Charset=iso-8859-1 Connection: close
Error - Perl execution failed
Undefined subroutine &main::cgi_page_title called at /usr/share/webmin/webmin_search.cgi line 55. 
</code>

Fresh install using ./install.sh -b LEMP
Upgrading to  Authentic Theme 19.19 and switching theme - same error.

**Comment by jcameron** [comment]
To clarify - are you only seeing this on Ubuntu 18.04 systems?

**Comment by reers** [comment]
The error is present on Ubuntu 18.04 running Webmin 1.883. After downgrading to Webmin 1.881 the error is still there. Another machine running Ubuntu 16.04 and Webmin 1.881 doesn't have the error.

**Comment by jcameron** [comment]
Ok, I finally managed to track this down - it's due to a slight difference in the behavior of the Perl version in Ubuntu 18. It will be fixed in the next release though.

**Comment by jcameron** [comment]
Patch is here : https://github.com/webmin/webmin/commit/dbe8bfb7d6dcaf45374c58c1e7ac9b194fcfd167
