### ISSUE TITLE
BIND: "Source IP address for transfers" doesn't accept IPv6 addresses

### ISSUE THREAD

**Issue by imcdona** [webmin/webmin#936]
The Bind module won't let you enter an IPv6 address in the "Source IP address for transfers". The syntax for  specifying an IPv6 source address is **transfer-source-v6**. Having the option to specify either or both (transfer-source and/or transfer-source-v6) options would nice. 

Also note that I couldn't find a way to specify a custom notify source address. The syntax is **notify-source** for IPv4 and **notify-source-v6** for IPv6. These two options are used when transferring zones via IPv6. If your system has more than one IPv6 address you need a way to tell Bind which address to use.

**Comment by jcameron** [comment]
Good suggestion ... look for this in the next Webmin release.
