### ISSUE TITLE
 German Language is a mix of german and english 

### ISSUE THREAD

**Issue by htttito** [webmin/webmin#938]
Hi webmin supporters!
Please look at the picture....
Language is German (de.UTF-8)
![bildschirmfoto von 2018-07-14 13-12-10](https://user-images.githubusercontent.com/40149753/42725622-2952a73e-8787-11e8-8f0c-859dcd714980.png)

**Comment by jcameron** [comment]
This will be fixed in the upcoming Webmin 1.890 release.
