### ISSUE TITLE
Error - Perl execution failed

### ISSUE THREAD

**Issue by TheBudda** [webmin/webmin#941]
I just upgraded. When I go to Linux Firewall I get this error

![error - perl execution failed-screenshot_20180717_021827](https://user-images.githubusercontent.com/16983376/42791291-c8f62d24-8967-11e8-8f13-f8cab795371e.png)

**Comment by jcameron** [comment]
Which version did you upgrade to?

**Comment by TheBudda** [comment]
Webmin version: 1.890, Ubuntu 18.04, Authentic Theme 19.19

**Comment by jcameron** [comment]
If you go to Networking -> Network Configuration -> Network Interfaces, do interfaces show up OK?

**Comment by TheBudda** [comment]
Yes, I can please see screenshot

![screenshot 2018-07-20 06 44 01](https://user-images.githubusercontent.com/16983376/42985353-ff6eb26c-8be8-11e8-9d1a-4d71130a7175.png)

**Comment by Actpohomoc** [comment]
May be in this module we should have something like it is done for `&net::active_interfaces()`:
`
if (&foreign_check("net")) {
&foreign_require("net");
@active = grep { $_->{'name'} ne 'lo' } &net::active_interfaces();
`

**Comment by jcameron** [comment]
The quick work-around for this is to add the line `force_init=1` to `/etc/webmin/firewall/config`

A proper fix will be in the next release.

**Comment by TheBudda** [comment]
I just added force_init=1 to /etc/webmin/firewall6 and IPv6 now works as well

**Comment by nicorac** [comment]
On my side (Ubuntu 18.04) the `force_init=1` workaround removes the error but also won't show any firewall rule.

Everything appears as unconfigured:
![webmin firewall ubuntu linux 18 04](https://user-images.githubusercontent.com/2361673/43063444-0fae7804-8e5c-11e8-931d-4feb9f836c5c.png)

Downgraded to 1.883 (with `force_init=1` still in place) and I have the same behavior (empty firewall rules). Finally resetting `force_init=0` on 1.883 fixes everything.

PS: it also shows only one green "Add rule" button; the green one changes at each page refresh.

So:
Webmin 1.890 + `force_init=0` = PERL error
Webmin 1.890 + `force_init=1` = No PERL error, no firewall rules shown
Webmin 1.883 + `force_init=0` = All OK
Webmin 1.883 + `force_init=1` = No PERL error, no firewall rules shown

**Comment by jcameron** [comment]
Did you setup your firewall rules on an older Ubuntu version, and then upgrade?

If so, the fix is to find the file containing your rules under the /etc directory, and then edit `/etc/webmin/firewall/config` and add a line like `save_file=/etc/your-rules-files`

**Comment by nicorac** [comment]
No, I don't.
Firewall rules were created on the same 18.04 version with Webmin 1.883.
I've always left "Save file" config option as "Use operating system or Webmin default".

Thanks to a daily backup script + iptables-restore I was able to restore iptables rules; after clicking on "Revert Configuration" rules now are back in place and they are shown in both versions (with `force_init=1` workaround on 1.890).

**Comment by roblaw80** [comment]
Just as a note,
I got this same error on a fresh install of Ubuntu Server 18.04.1 and webmin 1.890

**Comment by jcameron** [comment]
We haven't released a full version yet with the fix, just a dev version (1.893) available from http://www.webmin.com/devel.html

**Comment by mattish91** [comment]
@jcameron You should push 1.893 to stable channel sooner than later to resolve this issue. I just installed it and it's all working fine now. 

Thanks for making this awesome tool available!

**Comment by lambda-with-curry** [comment]
> @jcameron You should push 1.893 to stable channel sooner than later to resolve this issue. I just installed it and it's all working fine now.
> 
> Thanks for making this awesome tool available!

I ran into this issue today while tinkering with Ubuntu 18.04.  I'm guessing the fix hasn't been pushed out yet -- I'm using the APT repository, if that makes any difference -- but I want to echo the thanks.  Webmin is by far the most helpful resource I've used while attempting to learn and use Linux.

**Comment by bcutter** [comment]
Same for other pages like "Running processes":

![grafik](https://user-images.githubusercontent.com/13799156/97790233-2d74c000-1bc7-11eb-94e8-ff82de0ac313.png)

How to fix this perl error?

**Comment by iliarostovtsev** [comment]
Hi,

>  How to fix this perl error?

Are you running latest Webmin 1.960? I would suggest reinstalling Webmin package, and restarting Webmin manually:

~~~
/etc/webmin/restart
~~~

**Comment by bcutter** [comment]
> 
> 
> Hi,
> 
> > How to fix this perl error?
> 
> Are you running latest Webmin 1.960? I would suggest reinstalling Webmin package, and restarting Webmin manually:
> 
> ```
> /etc/webmin/restart
> ```

Yes I do, v. 1.960. Restarted several times, even reinstalled once. No change.

**Comment by iliarostovtsev** [comment]
Is anything gets logged to `/var/webmin/miniserv.error` log file?

I assume you don't have Perl or some of its libs installed properly system wide.

**Comment by bcutter** [comment]
Perl is installed. **What libs are required by Webmin?** I´ve done
`sudo apt install perl libnet-ssleay-perl openssl libauthen-pam-perl libpam-runtime libio-pty-perl apt-show-versions python` prior to installing Webmin. **What is missing?**

Log output from loading Webmin once:

`[01/Nov/2020:13:42:20 +0100] [192.168.0.42] /stats.cgi : **Perl execution failed : Undefined subroutine &proc::list_processes called at /usr/share/webmin/authentic-theme/stats.cgi line 192**.

[01/Nov/2020:13:42:21 +0100] [192.168.0.42] /stats.cgi : Perl execution failed : Undefined subroutine &proc::list_processes called at /usr/share/webmin/authentic-theme/stats.cgi line 192.

[01/Nov/2020:13:42:21 +0100] [192.168.0.42] /stats.cgi : Perl execution failed : Undefined subroutine &proc::list_processes called at /usr/share/webmin/authentic-theme/stats.cgi line 192.

Error: system-status::list_system_info failed : Undefined subroutine &proc::list_processes called at /usr/share/webmin/system-status/system-status-lib.pl line 35.

[01/Nov/2020:13:42:23 +0100] [192.168.0.42] /stats.cgi : Perl execution failed : Undefined subroutine &proc::list_processes called at /usr/share/webmin/authentic-theme/stats.cgi line 192.

Use of uninitialized value in open at /usr/share/webmin/bind8/bind8-lib.pl line 156.
Use of uninitialized value $_[0] in hash element at /usr/share/webmin/bind8/bind8-lib.pl line 201.
Use of uninitialized value $bind8::config{"no_chroot"} in int at /usr/share/webmin/bind8/bind8-lib.pl line 2406.
Argument "" isn't numeric in int at /usr/share/webmin/bind8/bind8-lib.pl line 2406.
Use of uninitialized value in string ne at /usr/share/webmin/bind8/bind8-lib.pl line 2406.
Error: system-status::list_system_info failed : Undefined subroutine &proc::list_processes called at /usr/share/webmin/system-status/system-status-lib.pl line 35.

[01/Nov/2020:13:42:24 +0100] [192.168.0.42] /stats.cgi : Perl execution failed : Undefined subroutine &proc::list_processes called at /usr/share/webmin/authentic-theme/stats.cgi line 192.`

**Comment by bcutter** [comment]
Update: I installed Webmin using apt according to https://doxfer.webmin.com/Webmin/Installation#apt_.28Debian.2FUbuntu.2FMint.29 (before I installed it manually which worked like sh** as all the errors proved) and now everything seems to work fine.

**Comment by iliarostovtsev** [comment]
> [01/Nov/2020:13:42:20 +0100] [192.168.0.42] /stats.cgi : Perl execution failed : Undefined subroutine &proc::list_processes called at /usr/share/webmin/authentic-theme/stats.cgi line 192.

You should install Webmin using `./setup.pl` script, rather than `./setup.sh`.

**Comment by iliarostovtsev** [comment]
@jcameron Should we exclude _setup.sh_ from _.tar_ ball not to be confusing?

**Comment by jcameron** [comment]
OK I just checked in a fix for this which we will include in the next release : https://github.com/webmin/webmin/commit/6833ce004a8d723d5e85024456f5e00f613c7e9a

Using setup.sh is still recommended over setup.pl.
