### ISSUE TITLE
No Perl MD5 hashing module found!

### ISSUE THREAD

**Issue by systemD2540** [webmin/webmin#942]
Im running on centos 7 [url=https://www.img.in.th/image/5uEZuf]
@webmin <img src="https://www.img.in.th/images/c49b2e5f70d5df3047f67a21504b9ccc.png" alt="c49b2e5f70d5df3047f67a21504b9ccc.png" border="0" />

**Comment by lemonsoftltd** [comment]
me too :/
![ekran alintisi](https://user-images.githubusercontent.com/30117203/42865124-55ea1c36-8a71-11e8-8e9c-b450bcfb7764.PNG)

**Comment by systemD2540** [comment]
Yeah waitting answer from dev.

**Comment by systemD2540** [comment]
Now i can fix this

**Comment by lemonsoftltd** [comment]
@systemD2540 how can you achieve that? For now, I use SSH bash with "top" command to see CPU. I just need CPU times.

**Comment by rostovtsev** [comment]
Try installing _Digest::MD5_. Package name for _RHEL_ is **perl-Digest-MD5** and for _Debian_  is **libdigest-perl-md5-perl**.

**Comment by systemD2540** [comment]
@lemonsoftltd  let you make Certificate Authority

**Comment by Playragnarok** [comment]
@iliaross that true

**Comment by rostovtsev** [comment]
Did it fix the issue?

**Comment by lemonysoft** [comment]
@iliaross thank you, fixed.

**Comment by swelljoe** [comment]
Why is the MD5 module being used in the dashboard?

**Comment by rostovtsev** [comment]
It's not the Dashboard that's using it. I think, it's some of _WebminCore_ functionality that's requiring it, as far as I can tell.

**Comment by swelljoe** [comment]
Huh. OK, I'll dig in and see what's going on there...I can't think of any reason to depend on that module at this point.

**Comment by swelljoe** [comment]
For those who saw this error, what Perl version do you have? This should never result in an error...it's supposed to be caught, so something is going wrong. Maybe Perl eval behavior has changed recently or something.

**Comment by lemonysoft** [comment]
@swelljoe I haven't noticed version of Perl before this error. Now the version is the latest after installing as stated by @iliaross "_RHEL_ is perl-Digest-MD5" 

> This is perl 5, version 16, subversion 3 (v5.16.3) built for x86_64-linux-thread-multi
(with 33 registered patches, see perl -V for more detail)

**Comment by megarockradio** [comment]
iliaross nailed it. appears  perl-Digest-MD5 was not installed with the original OS image from my VPS provider and was not installed with Webmin for some reason. 

I did a yum install  perl-Digest-MD5 command line and as soon as it installed I refreshed and the error went away. This was off a fresh OS install as I was moving the server up to Centos 7 from an old 6 install.

**Comment by cormos** [comment]
Yes, after:
yum install perl-Digest-MD5
the error gone away

**Comment by swelljoe** [comment]
Hopefully @jcameron will have thoughts on this, as the module being missing should not lead to an error. It ends up installed, anyway, in a lot of cases because several other Perl programs rely on it (awstats, among others), so Virtualmin systems won't have this problem, but it shouldn't be needed by Webmin except when using the features that need it (Apache digest auth functions need it, I think, and a few others). So...even though installing the module makes the error go away, it's still bug-like that there's an error at all.

I looked at the code, but don't see why it would result in an error...it seemingly wrapped in an eval, so it should just log it and move on rather than stopping the world and spitting an error on the dashboard.

**Comment by jcameron** [comment]
This looks like a bug to me - the subsequent code can deal with an MD5 module being missing, so that error message is un-necessary. I will submit a fix to remove it.

**Comment by vitobeto** [comment]
@swelljoe I had this error too after updating to version 1.890.
After installing perl-Digest-MD5 and perl-Digest (as dependence) error is gone.

Summary of my perl5 (revision 5 version 16 subversion 3) configuration:
  Platform:
    osname=linux, osvers=2.6.32-573.18.1.el6.x86_64, archname=x86_64-linux-thread-multi
    uname='linux worker1.bsys.centos.org 2.6.32-573.18.1.el6.x86_64 #1 smp tue feb 9 22:46:17 utc 2016 x86_64 x86_64 x86_64 gnulinux '

**Comment by 3n32002** [comment]
yum install perl-Digest-MD5

THX

**Comment by avecias** [comment]
THANKS

**Comment by nguyenmanhhien** [comment]
Thank Cormos

**Comment by Rhenan** [comment]
yum install perl-Digest-MD5

Works fine, thanks

**Comment by saruman** [comment]
@Rhenan thanks

**Comment by Sabidos** [comment]
Thanks!!!

yum install perl-Digest-MD5 

Work..!!!
