### ISSUE TITLE
E: There were unauthenticated packages and -y was used without --allow-unauthenticated

### ISSUE THREAD

**Issue by Bluscream** [webmin/webmin#950]
![grafik](https://user-images.githubusercontent.com/3318223/43766945-580c6e3a-9a23-11e8-9e15-bab6f7b1bffb.png)

Can you add that as default switch for apt operations?

**Comment by rostovtsev** [comment]
Hi,

Running the following:

```
sudo apt-get update
```

Should be enough to fix it.

**Comment by rostovtsev** [comment]
Try:

```
sudo apt-key update
sudo apt-get update
```

Do you have proxy setup?

**Comment by Bluscream** [comment]
```
blu@xxx:~$ sudo apt-key update
[sudo] password for blu:
Warning: 'apt-key update' is deprecated and should not be used anymore!
gpg: key 9165938D90FDDD2E: "Mike Thompson (Raspberry Pi Debian armhf ARMv6+VFP) <mpthompson@gmail.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
W: Removed keys keyring '/usr/share/keyrings/raspbian-archive-removed-keys.gpg' missing or not readable
```

**Comment by swelljoe** [comment]
I don't think this can be considered a bug. If the key isn't installed for a package that is signed, it *shouldn't* be installed until you figure out why. It could be a security issue to override that in the GUI.

**Comment by swelljoe** [comment]
Why not install the keys for the repos in question?

**Comment by swelljoe** [comment]
It's been a month and a half with no follow up, so I'm gonna close this one. I think it's working as it should...a package from a repo that is signed should be checked. The solution to the original problem is to add the keys for the repo to apt using the `apt-key add` command, not to override and install them without checking the signature.
