### ISSUE TITLE
Your version of Squid is not supported by Webmin. Only versions from 1.1 to 3.4 are supported by this module. 

### ISSUE THREAD

**Issue by roshanroche** [webmin/webmin#952]
Hi,
after squid upgrade im getting following error in webmin squid module.
Your version of Squid is not supported by Webmin. Only versions from 1.1 to 3.4 are supported by this module.
The command squid -v returned :

Squid Cache: Version 4.2
Service Name: squid

**Comment by rostovtsev** [comment]
This has been fixed in the latest commits.

You can manually apply [the patch](https://github.com/webmin/webmin/commit/0ec818b517b4741ca28cbe6e06c54122260855f2) and give an extra test for Squid 4.x.

**Comment by rostovtsev** [comment]
You can manually update the [file](https://github.com/webmin/webmin/blob/0ec818b517b4741ca28cbe6e06c54122260855f2/squid/index.cgi) but don't forget to replace:

```
#!/usr/local/bin/perl
```

to

```
#!/usr/bin/perl
```

**Comment by Ramaqele** [comment]
just update squid about a week ago and i get the similar
Your version of Squid is not supported by Webmin. Only versions from 1.1 to 3.4 are supported by this module.
The command /usr/local/sbin/squid -v returned :

Squid Cache: Version 4.1
Service Name: squid
i am on webmin 1.890
