### ISSUE TITLE
Diacritics not shown correctly in dashboard but they should be supported by the charset

### ISSUE THREAD

**Issue by ctrlbru** [webmin/webmin#954]
I'm not sure about the rest, but the current date in the dashboard does not show correctly in italian. E.g. "monday" should be "lunedì", but it shows "lunedÃ¬". If I ssh the server and ask for the date with the full localized name, I get the correct value. I see webmin is using charset iso-8859-1, which should indeed support symbol "ì", so maybe something is lost in translation when the date is obtained (the locale of the system is it_IT.UTF-8).

I also tried forcing the charset to utf-8 in the settings, same thing.

This happens with webmin 1.890 on debian stretch, authentic theme, using Chrome 68 or Firefox 61.

**Comment by rostovtsev** [comment]
Hi,

The charset should be set to UTF-8. What do you have set in Webmin/Change Language and Theme module?

**Comment by ctrlbru** [comment]
I had custom ui lang (I don't know the exact translation of the option) with "Italian UTF-8". Now I tried with "Global language .. Italian (it.UTF-8)" and suddenly I see the "ì" symbol correctly. Maybe something was messed up in the configuration and now it's fixed. Anyway, I'm closing this ticket since it's now ok. Thanks!
