### ISSUE TITLE
Webmin - Managing multiple servers proxied by Nginx

### ISSUE THREAD

**Issue by tvvignesh** [webmin/webmin#963]
I have 3 servers each with webmin installed behind an nginx reverse proxy - Due to some org restrictions, I can have only port 80 and 443 open and hence all domains go through Nginx proxy.

I have setup webmin in all 3 servers like so:

https://server1.com/webmin

https://server2.com/webmin

https://server3.com/webmin

I wanted to cluster and manage all these servers from a single webmin instance/UI.

I went through clustering Webmin but it was asking me for the hostname/ip and port. How do I do it since I have exposed my webmin instances via Nginx?

PS: All 3 webmin servers work when I use it individually. Thanks in advance.
I asked the same question in SO here: https://serverfault.com/questions/930754/webmin-managing-multiple-servers-proxied-by-nginx

**Comment by jcameron** [comment]
There's no way to manage all of these from a single UI, but you could setup proxying from each of those paths to a different Webmin server IP address.

**Comment by BobWs** [comment]
Did you managed to get this to work? I have the same question.

**Comment by iliarostovtsev** [comment]
https://github.com/webmin/webmin/issues/1445#issuecomment-778147592
