### ISSUE TITLE
Webmin won't load after other vhosts enabled

### ISSUE THREAD

**Issue by selfagency** [webmin/webmin#964]
Webmin works just fine until I activate virtual hosts, either using Webmin or a2ensite on the command line, and restart Apache.  After restart, Webmin won't load, throwing an SSL error (SSL_ERROR_RX_RECORD_TOO_LONG). If I disable my virtual hosts and restart Apache, then Webmin starts working again. 

Here's an example of one of my .conf files:

```
<VirtualHost *:80>
DocumentRoot /var/www/self.agency
ServerName self.agency
ServerAlias www.self.agency
<Directory "/var/www/self.agency">
allow from all
Options None
Require all granted
</Directory>
</VirtualHost>

<VirtualHost *:443>
DocumentRoot /var/www/self.agency
ServerName self.agency
ServerAlias www.self.agency
<Directory "/var/www/self.agency">
allow from all
Options None
Require all granted
</Directory>
</VirtualHost>
```

**Comment by jcameron** [comment]
That doesn't make much sense, as Webmin runs its own webserver on port 10000 and so doesn't depend on the Apache config at all..

**Comment by selfagency** [comment]
I think it has to do with the Nginx configuration because the web server on port 1000 is being proxied on port 80 through Nginx.

**Comment by jcameron** [comment]
OK, that could cause it. Maybe instead you should just access Webmin directly on port 10000 ?

**Comment by selfagency** [comment]
not entirely ideal (i don't really want random open ports) but yes, that does work

**Comment by swelljoe** [comment]
I'm gonna close this, as it isn't a Webmin issue. Seems to be a web server configuration issue.
