### ISSUE TITLE
MySQL/PostgreSQL: Export CSV File

### ISSUE THREAD

**Issue by rostovtsev** [webmin/webmin#971]
Jamie, this feature also doesn't work. Going to _**Edit Table**_, clicking _**Export as CSV**_ and hitting **Export Now** always returns an error:

```
Missing where clause
```

In case you put where clause like `1=1` it still returns the same error. :beetle:

**Comment by jcameron** [comment]
I just tested this in the MySQL module, and on the authentic theme I actually get no output at all.

On the old framed theme, it does work though. Maybe this is a case where the .cgi not calling the right header function doesn't work?

**Comment by rostovtsev** [comment]
Interesting. I tested it before in Debian and it didn't work. Tested in CentOS works fine. I'll find the cause.
