### ISSUE TITLE
Webmin version and operating system version exposed in tab

### ISSUE THREAD

**Issue by Zen4All** [webmin/webmin#972]
The Webmin version and operating system name and version are exposed in the browser tab. I do not want this, as it gives away important details to potential bad guys.
now it shows
```html
<title>Webmin 1.893 on MY_SERVER_ADDRESS (Ubuntu Linux 16.04.5)</title>
```

Where do I change the title to only show 
```html
<title>Webmin on MY_SERVER_ADDRESS</title>
```

**Comment by rostovtsev** [comment]
Hi,

Webmin Configuration page has an option not to show hostname in the URL titles.

For your information, it doesn't expose anything to unauthorized user. You need to be authorized in order to see hostname details. I would worry about it.

**Comment by Zen4All** [comment]
Simply by going to the log in scrren reveals everything. See image
![tab title](https://user-images.githubusercontent.com/2766593/46903745-9b16fc00-ced9-11e8-84a2-10ff706cc626.png)

**Comment by rostovtsev** [comment]
That is the bug! It's fixed. Thank you very much for reporting!

**Comment by Zen4All** [comment]
Thanks
