### ISSUE TITLE
How to delete modules after the inital setup (maybe a script)

### ISSUE THREAD

**Issue by gremo** [webmin/webmin#973]
Can I delete modules simply deleting the corresponding folder in `/usr/webmin`?

**Comment by rostovtsev** [comment]
You should not do it. After the upgrade it will be returned.

On contrary, you should disable modules in ACL module.

You can get there by clicking on your username in navigation menu:

![screenshot from 2018-10-14 12-36-27](https://user-images.githubusercontent.com/4426533/46914974-eef31500-cfad-11e8-8f0f-f74e9249be9b.png)

..later there will be **_Available Webmin modules_** tab where you could disable and block access to specific modules.

![screenshot from 2018-10-14 12-37-21](https://user-images.githubusercontent.com/4426533/46914997-38436480-cfae-11e8-884b-cf2ce35fddf7.png)

Doing so, will survive updates and provide you with the expected result.

Good luck. :wink:

**Comment by gremo** [comment]
@iliaross thanks for your answer. So, I should all be done using the GUI... not after the initial setup (something like unattended installation)?

There is no CLI support for disabling modules (and removing module folder... to save space)?

**Comment by rostovtsev** [comment]
Yes, you should use UI to disable modules. You could edit correspondent module's config file but there is no need for doing that, I suppose.

To save space? Well if you need to save space, you could actually delete modules manually.

Make a script for yourself to delete all unnecessary modules after each Webmin package upgrade, but make sure you have disabled them prior in UI, the way described above.

**Comment by gremo** [comment]
@iliaross thanks for the answer.

> Make a script for yourself to delete all unnecessary modules after each Webmin package upgrade

How to "hook" the update process?

> make sure you have disabled them prior in UI

Can I disable them editing some config file (which)?

**Comment by rostovtsev** [comment]
The way you could disable other modules using ACL module, described above (post with screenshot).

How to monitor package change? I would just put it into `sys-upd.sh` and ran it from there, right after package manager finishes its run.

**Comment by gremo** [comment]
Ok I disable all unused modules using the interface. Which file should I backup in order to save my configuration? I exported the main webmin configuration file (Webmin -> Backup configuration file) but I can't find any reference to "disabled modules".

**Comment by rostovtsev** [comment]
Hi,

Check for:

```
/etc/webmin/webmin.acl
```

In order to have these files backup up by _Backup Configuration Files_ module you would need to select in **Modules to backup** an option called **Webmin Users**.

You could also back up any wanted files by adding them to **Include in backup** field.

**Comment by abcbarryn** [comment]
There should be a way to easily disable specific modules for all users, not one user at a time.
