### ISSUE TITLE
Module installation copying the wrong config file on CentOS 7

### ISSUE THREAD

**Issue by swelljoe** [webmin/webmin#980]
This issue pointed out that the wrong config file is being copied into place on CentOS 7 for the virtualmin-nginx module, even though the OS is detected correctly. https://github.com/webmin/usermin/issues/43

There is a config-CentOS-Linux-7.0-ALL config file in that module that is correct (and ones for Scientific and RHEL, as well, that are different but would also work), but the config-redhat-linux (which does not work, since it uses /etc/init.d paths) is the one that gets copied into place. I thought I remember this being fixed, but I tested and confirmed the current package does copy the wrong file into place.

**Comment by jcameron** [comment]
That's odd, because that config file should get used on a CentOS 7 system.

What does `grep os /etc/webmin/config` output on this system?

**Comment by swelljoe** [comment]
It's detected correctly, as far as I can tell.

```
os_type=redhat-linux
os_version=15.5
real_os_type=CentOS Linux
real_os_version=7.5.1804
```

**Comment by jcameron** [comment]
How was the module installed exactly? I can't reproduce this, but I wonder if the trigger is the way the module is installed (from an RPM, tar.gz, or part of webmin core).

**Comment by swelljoe** [comment]
RPM. I never install anything from tarball. This is from the virtualmin-nginx package in the Virtualmin repos, built with makemodulerpm.pl (did something change there to support ALL or whatever that maybe I haven't pulled onto my build system?).

**Comment by jcameron** [comment]
If you're missing this patch https://github.com/webmin/webmin/commit/e55e1a32ddf947b43a0a2798746d7a095f06c06e#diff-939646f13d39fc1754b49412739285ba it could cause that problem.

**Comment by swelljoe** [comment]
That's it. I have updated, but the version of virtualmin-nginx in our repos was built with the old makemodulerpm.pl that didn't handle it.

Thanks for the pointer. Will roll a new package with the current version of makemodulerpm.pl.
