### ISSUE TITLE
Debian Iptables on systemd - aka netfilter support

### ISSUE THREAD

**Issue by burnbabyburn** [webmin/webmin#982]
Hi,

i tried running webmin 1.890 and 1.894 on Kernel 4.18 with debian testing and iptables v1.8.1 (nf_tables), but ran into the following issue:

`iptables: Invalid argument. Run dmesg for more information.`

OFC dmesg and journalctl don't show errors

IMHO this error comes from a (recent ? ) debian change on iptables. 
See e.g. https://github.com/docker/libnetwork/pull/2286 

Instead of just iptables they now have iptables-legacy and iptables-nft command.
```
root@pihole:~# iptables
iptables                    iptables-legacy-restore     iptables-nft-restore        iptables-restore-translate  iptables-xml
iptables-apply              iptables-legacy-save        iptables-nft-save           iptables-save
iptables-legacy             iptables-nft                iptables-restore            iptables-translate
```

Both are known under alias iptables?
```
update-alternatives: using /usr/sbin/iptables-legacy to provide /usr/sbin/iptables (iptables) in auto mode
update-alternatives: using /usr/sbin/iptables-nft to provide /usr/sbin/iptables (iptables) in auto mode
```

iptables-legacy is the easy way to go, as it seem to behave like "standard" iptables (e.g. accepting -m conntrack)

**Comment by burnbabyburn** [comment]
quickfix is updating aliases
```
rm /etc/alternatives/iptables-restore
rm /etc/alternatives/iptables-save
rm /etc/alternatives/iptables
ln -s /usr/sbin/iptables-legacy-restore /etc/alternatives/iptables-restore
ln -s /usr/sbin/iptables-legacy-save /etc/alternatives/iptables-save
ln -s /usr/sbin/iptables-legacy /etc/alternatives/iptables
```

**Comment by burnbabyburn** [comment]
IS [netfilter](https://netfilter.org/projects/nftables/) on the roadmap?

**Comment by jcameron** [comment]
Sounds like the right thing to do for now is use the -legacy commands if they exist.
