### ISSUE TITLE
Webmin utf issue

### ISSUE THREAD

**Issue by anirbanchakrabarty** [webmin/webmin#986]
I am trying to run scripts via webmin but I am getting utf issues.

The error is as follows:

stdout encoding 'ascii' detected. googler requires utf-8 to work properly. The wrong encoding may be due to a non-UTF-8 locale or an improper PYTHONIOENCODING. (For the record, your locale language is <unknown> and locale encoding is <unknown>; your PYTHONIOENCODING is not set.)

Please set a UTF-8 locale (e.g., en_US.UTF-8) or set PYTHONIOENCODING to utf-8.
I converted the iso8859 to EN. utf-8 in webmin lang folder. Webmin language Configuration does not show the utf8 file. Is there any way I can run utf-8 in webmin?

Thank you.

**Comment by jcameron** [comment]
What do you mean by running scripts via Webmin exactly? Is this using the Command Shell or Custom Commands page?

**Comment by anirbanchakrabarty** [comment]
list of command set saved in a .sh file.
here is the command set:
/usr/local/bin/googler -n 40 -C --np KEYWORD > result.txt
cm=$(grep 'SEARCH TEXT' result.txt | awk '{print $1}')
and some more lines.
when i am running the file,i am getting that error.
my locale output is as under:
LANG=en_US.utf8
LC_CTYPE="en_US.utf8"
LC_NUMERIC="en_US.utf8"
LC_TIME="en_US.utf8"
LC_COLLATE="en_US.utf8"
LC_MONETARY="en_US.utf8"
LC_MESSAGES="en_US.utf8"
LC_PAPER="en_US.utf8"
LC_NAME="en_US.utf8"
LC_ADDRESS="en_US.utf8"
LC_TELEPHONE="en_US.utf8"
LC_MEASUREMENT="en_US.utf8"
LC_IDENTIFICATION="en_US.utf8"
LC_ALL=

let me know if you need any further information.i am stuck.

**Comment by jcameron** [comment]
Did you try going to Webmin -> Language and selecting a UTF-8 encoded language?

**Comment by anirbanchakrabarty** [comment]
there is no en.UTF-8 in webmin language configuration.but i followed this thread:https://github.com/authentic-theme/authentic-theme/issues/27,   converted the EN to en.UTF-8 and pasted in /usr/libexec/webmin/lang folder but i dont see the file in the language menu of webmin to select. should it be going in any other folder?
Thanks in advance

**Comment by jcameron** [comment]
Which Webmin version are you running there?

**Comment by anirbanchakrabarty** [comment]
webmin 1.350 on fc9. sorry i cant use latest version as my pc wont support.

**Comment by jcameron** [comment]
1.350?? That's really really old ... are you sure you don't mean 1.850?

**Comment by anirbanchakrabarty** [comment]
Yes

**Comment by swelljoe** [comment]
It's not reasonable to keep running software that is many, many, years out of date. It's dangerous, and impossible for us to support in any meaningful way (we certainly don't have any systems running a version that old). FC9 has been unsupported by the Fedora project for about a decade.

You need to upgrade your OS and your Webmin version to something from this decade. Use a current CentOS version (CentOS 7) or the current LTS release of Ubuntu, as both of those have a long life cycle, and we commit to supporting them through their whole lifecycle (so Webmin will not stop supporting CentOS 7 before it's scheduled EOL several years from now in, I think, something like 2023).

Or downgrade whatever other applications you're using that are misbehaving...this isn't even Webmin complaining, is it? Isn't it the other application (`googler`, whatever that is)? So..maybe take it up with whoever maintains that (or upgrade your OS and version to something reasonable and supported).

**Comment by anirbanchakrabarty** [comment]
Googler is a github project. The script is working fine from terminal. But
giving issues by webmin. I am unable to understand the utf issue. I have
given the locale file. Hope you can help me.
TIA

**Comment by swelljoe** [comment]
I just tried googler, and it's not going to work in the Webmin terminal or as a scheduled command.

The command shell in Webmin is a not an interactive terminal; it just runs one command and accepts the output. googler seems to require an interactive terminal (I don't know why...even with the `--np` option it refuses to run without an interactive terminal, which seems bug-like on the part of googler).

So, while we *could* set the LANG environment in the command shell, it won't make this command run the way you want it to run, because it also wants an interactive terminal, which the Command Shell in Webmin is not. There is an open ticket about making the popup shell provided by Authentic Theme an interactive terminal, but it's not possible yet (it needs quite a lot of work to make it happen, so I don't know how long it will take).

**Comment by swelljoe** [comment]
OK, I just tested in ajaxterm and googler does work as expected. So...use that. I doubt ajaxterm is included in your version of Webmin, however. You might be able to install it from the third party modules repo, but I wouldn't bet on it.

**Comment by anirbanchakrabarty** [comment]
hi, can you send me the appropriate link of the third party module please? could not get hold of it.TIA.

**Comment by rostovtsev** [comment]
@anirbanchakrabarty Search for _Text Login_ in the navigation menu.

**Comment by anirbanchakrabarty** [comment]
I have already solved it. Thank you all for your generous consideration.
Thank you again.

**Comment by anirbanchakrabarty** [comment]
I could not close the issue. It shows already closed. Pls suggest.

**Comment by rostovtsev** [comment]
The issue was closed. No worries.

**Comment by anirbanchakrabarty** [comment]
Do you interest in what I did? Tf so I can share.
Thank you

**Comment by rostovtsev** [comment]
Sure, please share.

**Comment by anirbanchakrabarty** [comment]
I added your line and export BROWSER =elinks at the top. That's all. Thanks
bro

**Comment by anirbanchakrabarty** [comment]
The other line is export LANG=en_US.utf8
