### ISSUE TITLE
[Feature Request] Cron Jobs - show execution date/time

### ISSUE THREAD

**Issue by FBachofner** [webmin/webmin#988]
It would be great if at
"Scheduled Cron Jobs"

there would be an ability to show a column for the execution date + time for each cron job

given that these can be quite complex, a potentially *more* useful partial implementation would be to show the *_next_* execution time for each cron job

**Comment by jcameron** [comment]
That's not a bad idea, however I have done this in the past and it turns out that computing the next execution time is actually quite slow and complex because of all the possibilities. So this would slow down the UI noticably.

**Comment by FBachofner** [comment]
Hi @jcameron 

I wonder whether it might be possible to have this batch processed once (or a few times) a day so as to not slow down the Webmin UI.

I think for the majority of people, most of their cron jobs happen weekly, daily (or _perhaps_ a couple times a day) .  If more, it would probably be adequate for the average user to report like "frequently" in the next run column.

Those whose cron jobs are much more frequent (such as sysadmins) also probably won't pay much attention to the "next @" column anyway.  They likely know which jobs are very frequent.

Also, I would suggest the presentation of the column be _optional_.


Another cool option would be a "last run" (optional) column and have the UI show the time, for example, in green (successful) or red (not successful).

This of course, is a much dicier proposition as it is probably only realistic to show whether the cron job invoked or not (not whether it accomplished what was planned!).

Thanks for your continued great work on Webmin!  :-)

**Comment by rostovtsev** [comment]
Possibly and maybe cache and run in background calculations for cron date time?

**Comment by jcameron** [comment]
I'll put this on my TODO list for future implementation, as I agree it would be nice to have and could potentially be cached.

**Comment by jcameron** [comment]
The next release of Webmin will (optionally) show the next run times of cron jobs.

**Comment by FBachofner** [comment]
Fabulous news!

Thanks.
