### ISSUE TITLE
Login request for webmin wiki

### ISSUE THREAD

**Issue by cschnaars** [webmin/webmin#989]
May I have a login for the webmin wiki, please? Thanks.

**Comment by swelljoe** [comment]
Absolutely! We'll take all the help we can get.

I've created an account for you using the email address you have on your account here at github. You should have received login details. You can change the password, if you like.

Please let me know if you have any questions.

**Comment by swelljoe** [comment]
Yes! Sorry, I have no idea what I'm doing. Fixed now.

**Comment by cschnaars** [comment]
Sorry, but I still can't edit. Apologies for the hassle.

**Comment by swelljoe** [comment]
Not your fault. My internet is absolute trash right now (I'm on mobile, and I ran out of data so I'm being throttled to a trickle...the form didn't actually save...trying again...).

**Comment by swelljoe** [comment]
Looks like it worked this time. Let me know if I'm lying.

**Comment by cschnaars** [comment]
It works! Thanks, Joe.
