### ISSUE TITLE
Encoding issue for special chars?

### ISSUE THREAD

**Issue by rostovtsev** [webmin/webmin#991]
Jamie, hi.

It seems that 1.900 has broken encoding (I have it set to UTF-8). For example multi-select arrows are broken.

Example:

![image](https://user-images.githubusercontent.com/4426533/48709483-a535c400-ec16-11e8-9fea-cd70a11d48c0.png)

**Comment by jcameron** [comment]
Looks like some unicode in the source was broken? Looking into why ..

**Comment by jcameron** [comment]
Are there any other cases where you can see these kinds of errors?

**Comment by rostovtsev** [comment]
I see it in all multiselect arrows, in Authentic Theme the width of the buttons is broken.

**Comment by jcameron** [comment]
Ok, but just multi-select arrows?

I checked in a fix for that here : https://github.com/webmin/webmin/commit/664802ac56b3c8f0dcda1e9892ece47bd5345323

**Comment by rostovtsev** [comment]
Jamie, I didn't notice any other places.

It fixes the issue.

**Comment by rostovtsev** [comment]
..and arrows are displayed as expected again.

![image](https://user-images.githubusercontent.com/4426533/48829722-07600780-ed84-11e8-8065-440fa7db672c.png)

Thank you.
