### ISSUE TITLE
Every 5min contact to " api.github.com" ?

### ISSUE THREAD

**Issue by v-i-r-u-s** [webmin/webmin#993]
Why does Webmin now call home every 5 minutes ?

**Comment by rostovtsev** [comment]
It's possible in case you have option _Check for Authentic Theme updates_ in theme configuration enabled.

**Comment by swelljoe** [comment]
Every 5 minutes feels like huge overkill for theme update checks. Maybe every hour or every 24 hours would be more appropriate.

**Comment by rostovtsev** [comment]
It's tied to 300 seconds system update interval, by default. It's also new announcement system - it also does connection every 300 seconds by default. 

There is no reason to block those connections, as there is nothing vicious in them. It just checks for text file on webmin.com server, looking for possible announcements.

**Comment by Zen4All** [comment]
But 5 minutes send to be overkill indeed. May be the default can be changed to once every 24 hours

**Comment by rostovtsev** [comment]
By design checking for announcements and updates is tied to default System Information updates (that is cached), which is 300 seconds by default and could be changed in _**Webmin Configuration/Scheduled Functions**_.

**Comment by rostovtsev** [comment]
Okay, my bad. Announcements are checked once a day.

I will see how I could improve theme updates run daily too.

**Comment by rostovtsev** [comment]
Okay, [latest commit @8e8459e ](https://github.com/authentic-theme/authentic-theme/commit/40b9149e2b2dbc6d1b891ba2cb6e60df682468c2) adds _**caching**_ for checking _theme updates_ and updates for _ConfigServer Security and Firewall_ to be set to 24 hours by default. You could also change this value to whatever suits best for you.

![image](https://user-images.githubusercontent.com/4426533/48981624-111d9e00-f0e9-11e8-980d-2431f44cf63c.png)
