### ISSUE TITLE
Fail2ban jail save bug with abuseipdb action

### ISSUE THREAD

**Issue by NielBuys** [webmin/webmin#996]
Problem is that jails with an abuseipdb action do not save correct, if changes are made in webmin jail screen.

I added in the jail.local config file directly an abuseipdb action to my jails. Correct jail code
`[sshd]
enabled = true
action = %(action_)s
         %(action_abuseipdb)s[abuseipdb_apikey="<APIKEY>", abuseipdb_category="18,22"]
findtime = 3200
bantime = 86400`
and everything worked fine.

Later I went in to change the jail time of the jail on the webmin screen see screenshot.
![image](https://user-images.githubusercontent.com/8427483/49208524-a7d7ac80-f3c0-11e8-8d99-1db496fcdb30.png)

After save there were 2 problems with the config file.
1. Brackets are added after the abuseipdb action see below how the config file looked wrong. The jail did not start. with this problem.
2. The 2 actions line actions were next to each other from what I could see the action do not trigger if the actions are on the same line. The action would not trigger with this problem.

Worng jail code after save action
`[sshd]
enabled = true
action = %(action_)s %(action_abuseipdb)s[abuseipdb_apikey="<APIKEY>", abuseipdb_category="18,22"][][]
findtime = 3200
bantime = 86400`

Note: sorry I see github issues is not displaying the code snippets correct.
Thanks in advance

**Comment by jcameron** [comment]
Thanks for pointing this out - this will be fixed in the next Webmin release.
