### ISSUE TITLE
Mis-identified RAID device in version 1.890 for RSTe RAID using mdadm

### ISSUE THREAD

**Issue by sylnsr** [webmin/webmin#998]
For some odd reason, Intel's RSTe RAID setup seems to setup some sort of psuedo RAID aliases.  This part is a long story, but basically its on-board (hardware) RAID .. which relies on mdadm. ( ??)

In this case Webmin seems to have a problem with correctly identifying the correct RAID container because of the way RSTe names things (I am guessing)

When using mdadm from the command line, and a little intuition, its actually quite simple to correctly identify the real RAID device name and use a slightly different mdadm command than the one constructed and executed by Webmin, to get the job done.  It would be great if Webmin could correctly identify the correct RAID container device name and therefore properly construct the correct mdadm command params to execute.  Please see [this Server Fault post](https://serverfault.com/questions/673501/thinkserver-rd440-raid-mess/942451#942451) where this is documented better than I can explain here.

_What I get using Webmin_:

Webmin tries to add the second device to the wrong container using  
`mdadm --manage /dev/md126 --add /dev/sdc`

_What I would expect_:

Webmin should correctly identify the real RAID container device name and do:  
`mdadm --manage /dev/md127 --add /dev/sdc`

In the case of an array created with RSTe things seem to be all jumbled up from Webmins point of view.

**Comment by sylnsr** [comment]
It actually moves around a bit with RSTe. I have no idea why. Today its this:

```Personalities : [raid1] [linear] [multipath] [raid0] [raid6] [raid5] [raid4] [raid10] 
md124 : active raid1 sda[1] sdd[0]
      488383488 blocks super external:/md127/0 [2/2] [UU]
      
md125 : active raid1 sdb[1] sdc[0]
      244195328 blocks super external:/md126/0 [2/2] [UU]
      
md126 : inactive sdb[1](S) sdc[0](S)
      6512 blocks super external:imsm
       
md127 : inactive sdd[1](S) sda[0](S)
      6192 blocks super external:imsm
       
unused devices: <none>```

But basically, there are times when its at md127 for example (according to mdstat), and Webmin thinks its at md126.

**Comment by sylnsr** [comment]
I see there is a nagios plugin project which also had to be modified for Intel fake RAID managed under mdadm: https://github.com/glensc/nagios-plugin-check_raid/issues/34
Maybe its a similar challenge here?

**Comment by jcameron** [comment]
Maybe webmin should just ignore md126 and md127 then?

**Comment by jcameron** [comment]
If you have a code fix for this, could you send it as a patch file or even better a github pull request?

It's hard for me to write fixes since I don't have this same hardware setup.

**Comment by sylnsr** [comment]
Its been ages since I did any Perl, but if my proposed solution is acceptable, I guess I can take a stab at it when I have some time.

**Comment by jcameron** [comment]
Sure, go for it!

**Comment by sylnsr** [comment]
Closing issue. After 3 outages with data loss and finding much information that concurs with my own experience, that *fake raid is bad*, I believe it would be bad for the community to perpetuate fake raid support in any tool, including Webmin.
